### ISSUE TITLE
Only services in default namespace are allowed?

### ISSUE THREAD

**Issue by aledbf** [nginxinc/kubernetes-ingress#1]
https://github.com/nginxinc/kubernetes-ingress/blob/master/nginx-controller/main.go#L44

**Comment by munnerz** [comment]
I've created #5 to resolve this

**Comment by pleshakov** [comment]
Thanks for pointing out the problem!

**Comment by pleshakov** [comment]
Fixed in https://github.com/nginxinc/kubernetes-ingress/pull/13
