### ISSUE TITLE
Ingress resource cannot get the corresponding IP address

### ISSUE THREAD

**Issue by Leozhanggg** [nginxinc/kubernetes-ingress#1000]
**Describe the bug**
Ingress resource cannot get the corresponding IP address

**To Reproduce**
1. Installed the NGINX Ingress Controller in your Kubernetes cluster using Kubernetes manifests.
This is according to https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/
2. Found that the Ingress resource did not obtain the corresponding IP address
3. And cannot access the app through the Ingress entrance

**Expected behavior**
Ingress resource can get the corresponding IP address

**Your environment**
Version of the Ingress Controller - 1.7.1
Version of Kubernetes - 1.17.5
Kubernetes platform (e.g. Mini-kube or GCP) - kubeadm
Using NGINX or NGINX Plus - NGINX

**Additional context**
- [x] [root@k8s-32 deployments]# kubectl apply -f common/ns-and-sa.yaml
namespace/nginx-ingress created
serviceaccount/nginx-ingress created
[root@k8s-32 deployments]# kubectl apply -f rbac/rbac.yaml
clusterrole.rbac.authorization.k8s.io/nginx-ingress created
clusterrolebinding.rbac.authorization.k8s.io/nginx-ingress created
[root@k8s-32 deployments]# kubectl apply -f common/default-server-secret.yaml
secret/default-server-secret created
[root@k8s-32 deployments]# kubectl apply -f common/nginx-config.yaml
configmap/nginx-config created
[root@k8s-32 deployments]# kubectl apply -f common/vs-definition.yaml
customresourcedefinition.apiextensions.k8s.io/virtualservers.k8s.nginx.org created
[root@k8s-32 deployments]# kubectl apply -f common/vsr-definition.yaml
customresourcedefinition.apiextensions.k8s.io/virtualserverroutes.k8s.nginx.org created
[root@k8s-32 deployments]# kubectl apply -f common/ts-definition.yaml
customresourcedefinition.apiextensions.k8s.io/transportservers.k8s.nginx.org created
[root@k8s-32 deployments]# kubectl apply -f common/gc-definition.yaml
customresourcedefinition.apiextensions.k8s.io/globalconfigurations.k8s.nginx.org created
[root@k8s-32 deployments]# kubectl apply -f common/global-configuration.yaml
globalconfiguration.k8s.nginx.org/nginx-configuration created
[root@k8s-32 deployments]# kubectl apply -f daemon-set/nginx-ingress.yaml
daemonset.apps/nginx-ingress created
[root@k8s-32 deployments]# kubectl create -f service/nodeport.yaml
service/nginx-ingress created
[root@k8s-32 deployments]# kubectl get pods --namespace=nginx-ingress
NAME                  READY   STATUS              RESTARTS   AGE
nginx-ingress-5jmt4   0/1     ContainerCreating   0          0s
[root@k8s-32 deployments]# kubectl get svc --namespace=nginx-ingress
NAME            TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
nginx-ingress   NodePort   10.108.242.46   <none>        80:31773/TCP,443:32182/TCP   8s
[root@k8s-32 deployments]#
[root@k8s-32 deployments]#
[root@k8s-32 deployments]# kubectl get pods --namespace=nginx-ingress
NAME                  READY   STATUS    RESTARTS   AGE
nginx-ingress-5jmt4   1/1     Running   0          12s
[root@k8s-32 deployments]# cd ..
[root@k8s-32 kubernetes-ingress-1.7.1]# kubectl apply -f examples/
complete-example/             daemon-set/                   jwt/                          proxy-protocol/               ssl-services/
custom-annotations/           externalname-services/        mergeable-ingress-types/      rbac/                         tcp-udp/
customization/                grpc-services/                multiple-ingress-controllers/ rewrites/                     websocket/
custom-templates/             health-checks/                opentracing/                  session-persistence/          wildcard-tls-certificate/
[root@k8s-32 kubernetes-ingress-1.7.1]# kubectl apply -f examples/mergeable-ingress-types/
ingress.extensions/cafe-ingress-master created
secret/cafe-secret created
deployment.apps/coffee created
service/coffee-svc created
deployment.apps/tea created
service/tea-svc created
ingress.extensions/cafe-ingress-coffee-minion created
ingress.extensions/cafe-ingress-tea-minion created
[root@k8s-32 kubernetes-ingress-1.7.1]#
[root@k8s-32 kubernetes-ingress-1.7.1]#
[root@k8s-32 kubernetes-ingress-1.7.1]# kubectl get ing
NAME                         HOSTS              ADDRESS   PORTS     AGE
cafe-ingress-coffee-minion   cafe.example.com             80        26s
cafe-ingress-master          cafe.example.com             80, 443   27s
cafe-ingress-tea-minion      cafe.example.com             80        26s
[root@k8s-32 kubernetes-ingress-1.7.1]# kubectl get svc
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
coffee-svc   ClusterIP   10.97.123.12    <none>        80/TCP    43h
kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP   43h
tea-svc      ClusterIP   10.99.106.211   <none>        80/TCP    43h
[root@k8s-32 kubernetes-ingress-1.7.1]# curl 10.97.123.12
Server address: 10.11.255.134:8080
Server name: coffee-7c45f487fd-s755s
Date: 22/Jun/2020:06:08:24 +0000
URI: /
Request ID: fcf87c7b5c1695fea4f7d9494c80a0cf
[root@k8s-32 kubernetes-ingress-1.7.1]# tail -n1 /etc/hosts
10.88.77.32 cafe.example.com
[root@k8s-32 kubernetes-ingress-1.7.1]# curl cafe.example.com
curl: (7) Failed connect to cafe.example.com:80; Connection refused

**Comment by Leozhanggg** [comment]
https://github.com/nginxinc/kubernetes-ingress/issues/587
I found the same as this question

**Comment by Leozhanggg** [comment]
Why repeatedly prompt "kube-scheduler doesn't exist"???

> 2020/06/22 10:05:23 [notice] 11#11: signal 17 (SIGCHLD) received from 37
2020/06/22 10:05:23 [notice] 11#11: worker process 36 exited with code 0
2020/06/22 10:05:23 [notice] 11#11: worker process 37 exited with code 0
2020/06/22 10:05:23 [notice] 11#11: worker process 38 exited with code 0
2020/06/22 10:05:23 [notice] 11#11: signal 29 (SIGIO) received
2020/06/22 10:05:23 [notice] 11#11: signal 17 (SIGCHLD) received from 38
2020/06/22 10:05:23 [notice] 11#11: signal 17 (SIGCHLD) received from 35
2020/06/22 10:05:23 [notice] 11#11: worker process 35 exited with code 0
2020/06/22 10:05:23 [notice] 11#11: signal 29 (SIGIO) received
I0622 10:05:23.166991       1 verify.go:74] success, version 4 ensured. iterations: 5. took: 125ms
I0622 10:05:23.167080       1 event.go:278] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"nginx-ingress", Name:"nginx-config", UID:"885d4a1e-1759-4724-9161-5f8495d80429", APIVersion:"v1", Resourcersion:"396684", FieldPath:""}): type: 'Normal' reason: 'Updated' Configuration from nginx-ingress/nginx-config was updated
I0622 10:05:24.974347       1 handlers.go:84] Endpoints kube-scheduler changed, syncing
I0622 10:05:24.974373       1 task_queue.go:56] Adding an element with a key: kube-system/kube-scheduler
I0622 10:05:24.974394       1 task_queue.go:84] Syncing kube-system/kube-scheduler
I0622 10:05:24.974402       1 controller.go:665] Syncing kube-system/kube-scheduler
I0622 10:05:24.974410       1 controller.go:408] Syncing endpoints kube-system/kube-scheduler
I0622 10:05:24.974418       1 controller.go:1447] Service kube-system/kube-scheduler doesn't exist
I0622 10:05:24.974426       1 controller.go:1507] Service kube-system/kube-scheduler doesn't exist
I0622 10:05:25.038810       1 handlers.go:84] Endpoints kube-controller-manager changed, syncing
I0622 10:05:25.038829       1 task_queue.go:56] Adding an element with a key: kube-system/kube-controller-manager
I0622 10:05:25.038848       1 task_queue.go:84] Syncing kube-system/kube-controller-manager
I0622 10:05:25.038854       1 controller.go:665] Syncing kube-system/kube-controller-manager
I0622 10:05:25.038862       1 controller.go:408] Syncing endpoints kube-system/kube-controller-manager
I0622 10:05:25.038898       1 controller.go:1447] Service kube-system/kube-controller-manager doesn't exist
I0622 10:05:25.038910       1 controller.go:1507] Service kube-system/kube-controller-manager doesn't exist
I0622 10:05:27.029821       1 handlers.go:84] Endpoints kube-scheduler changed, syncing
I0622 10:05:27.029852       1 task_queue.go:56] Adding an element with a key: kube-system/kube-scheduler
I0622 10:05:27.029902       1 task_queue.go:84] Syncing kube-system/kube-scheduler
I0622 10:05:27.029914       1 controller.go:665] Syncing kube-system/kube-scheduler
I0622 10:05:27.029927       1 controller.go:408] Syncing endpoints kube-system/kube-scheduler
I0622 10:05:27.029940       1 controller.go:1447] Service kube-system/kube-scheduler doesn't exist
I0622 10:05:27.029949       1 controller.go:1507] Service kube-system/kube-scheduler doesn't exist

**Comment by Leozhanggg** [comment]
![image](https://user-images.githubusercontent.com/31919498/85276755-e823e180-b4b4-11ea-9ec4-5f1c79fa1eb3.png)

![image](https://user-images.githubusercontent.com/31919498/85276831-fe31a200-b4b4-11ea-8ecf-2ea975f94408.png)

**Comment by Leozhanggg** [comment]
And I cannot access the coffee service through ingress

> [root@k8s-32 kubernetes-ingress-1.7.1]# kubectl get svc -A
NAMESPACE              NAME                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
default                coffee-svc                  ClusterIP   10.106.48.146    <none>        80/TCP                       5m1s
default                kubernetes                  ClusterIP   10.96.0.1        <none>        443/TCP                      2d
default                nginx                       ClusterIP   10.104.121.132   <none>        80/TCP                       112m
default                tea-svc                     ClusterIP   10.99.137.91     <none>        80/TCP                       5m1s
kube-system            kube-dns                    ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP       2d
kubernetes-dashboard   dashboard-metrics-scraper   ClusterIP   10.104.22.150    <none>        8000/TCP                     47h
kubernetes-dashboard   kubernetes-dashboard        NodePort    10.109.21.45     <none>        443:30001/TCP                47h
nginx-ingress          nginx-ingress               NodePort    10.103.59.239    <none>        80:30270/TCP,443:31095/TCP   13m
[root@k8s-32 kubernetes-ingress-1.7.1]# kubectl get ing
NAME           HOSTS              ADDRESS       PORTS     AGE
cafe-ingress   cafe.example.com   10.88.77.32   80, 443   5m1s
[root@k8s-32 kubernetes-ingress-1.7.1]# kubectl describe ing cafe-ingress
Name:             cafe-ingress
Namespace:        default
Address:          10.88.77.32
Default backend:  default-http-backend:80 (<none>)
TLS:
  cafe-secret terminates cafe.example.com
Rules:
  Host              Path  Backends
  ----              ----  --------
  cafe.example.com
                    /tea      tea-svc:80 (10.11.255.185:8080,10.11.255.187:8080,10.11.255.188:8080)
                    /coffee   coffee-svc:80 (10.11.255.184:8080,10.11.255.186:8080)
Annotations:
  kubectl.kubernetes.io/last-applied-configuration:  {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{},"name":"cafe-ingress","namespace":"default"},"spec":{"rules":[{"host":"cafe.example.com","http":{"paths":[{"backend":{"serviceName":"tea-svc","servicePort":80},"path":"/tea"},{"backend":{"serviceName":"coffee-svc","servicePort":80},"path":"/coffee"}]}}],"tls":[{"hosts":["cafe.example.com"],"secretName":"cafe-secret"}]}}

Events:
  Type    Reason          Age   From                      Message
  ----    ------          ----  ----                      -------
  Normal  AddedOrUpdated  5m5s  nginx-ingress-controller  Configuration for default/cafe-ingress was added or updated
[root@k8s-32 kubernetes-ingress-1.7.1]# curl 10.106.48.146
Server address: 10.11.255.184:8080
Server name: coffee-7c45f487fd-9rpgw
Date: 22/Jun/2020:10:19:10 +0000
URI: /
Request ID: 0869b9186537b5c84a6d1f6194d77812

[root@k8s-32 kubernetes-ingress-1.7.1]# curl cafe.example.com:30270/coffee
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.19.0</center>
</body>
</html>

**Comment by LorcanMcVeigh** [comment]
Hi @Leozhanggg 

By default we redirect all traffic from port 80 to port 443, this can be disabled with `ingress.kubernetes.io/ssl-redirect` annotation and setting it to `False` 

for your last comment there are 2 choices 
1. use https ports for your curl so `curl https://cafe.example.com:31095/coffee` or 
2. Follow redirects with curl `curl cafe.example.com:31095/coffee -L` note the `-L` follows redirects in curl 

As for the `ERR_SSL_VERSION_OR_CIPHER` that seems to be a problem with your client/browser

let me know if this help.

**Comment by Leozhanggg** [comment]
Thank you very much for your help, my problem has been solved.
But why does it keep saying "Service kube-system/kube-scheduler doesn't exist" in the controller log?

**Comment by Rulox** [comment]
@Leozhanggg those are debug messages. Because there are certain `endpoints` created by k8s that have no service, the Ingress Controller watches all endpoints in the cluster and is informing that it can't access those services.

You should not see those debug logs if your logging level is `v=1`. By default it should be like that, you can set it with the `v` [cli argument](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/command-line-arguments/#cmdoption-v).

You can ignore those type of messages safely. For a production environment, we recommend to set `v=1` as default.

**Comment by Leozhanggg** [comment]
@Rulox Thank you for your help。
