### ISSUE TITLE
How many characters the rewrite annotation support?

### ISSUE THREAD

**Issue by katlimruiz** [nginxinc/kubernetes-ingress#1027]
I have this definition

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ing
  annotations:
    kubernetes.io/ingress.class: nginx-my-ing
    cert-manager.io/issuer: my-ing-cert
    nginx.org/rewrites: >
      serviceName=my-service-for-entity-svc1 rewrite=/;
      serviceName=my-service-for-entity-svc2 rewrite=/;
      serviceName=my-service-for-entity-svc3 rewrite=/;
spec:
```

And this is more a question than a feature, how many characters the rewriting will support? I expect to add around 30 rules.

I know that the annotation is going to be limited by kubernetes, but I couldn't find any information about that.

Thanks

**Comment by lucacome** [comment]
Hi @katlimruiz 

Unfortunately, I couldn't find an answer either reading the docs.
I tried adding 40+ rules and everything was working fine. I'll let you know if I find out more and can give you a more accurate answer.

Cheers,
Luca
