### ISSUE TITLE
Any traffic to the IP address without a hostname defined in request

### ISSUE THREAD

**Issue by Leozhanggg** [nginxinc/kubernetes-ingress#1038]
**Is your feature request related to a problem? Please describe.**

> apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: test-svc
          servicePort: 80

> [root@k8s-master ~]# kubectl get ing
NAME           HOSTS         ADDRESS        PORTS   AGE
test-ingress   *                                             80      3h28m

> I can't get Address when I don't define the host field

**Describe the solution you'd like**
Any traffic to the IP address without a hostname defined in request

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/31919498/86733475-cf462f00-c063-11ea-958b-66179e375436.png)

**Comment by Leozhanggg** [comment]
@Dean-Coakley  Can you help?

**Comment by Leozhanggg** [comment]
When deploy kubernetes/ingress-nginx it is ok

**Comment by Dean-Coakley** [comment]
Hi @Leozhanggg 

In this implementation of an Ingress Controller we require the host field as an intentional restriction.

Can the following workaround help you?:
https://github.com/nginxinc/kubernetes-ingress/issues/209#issuecomment-581691384

**Comment by Leozhanggg** [comment]
@Dean-Coakley Thank you for your help
