### ISSUE TITLE
Extend Ingress  General Customization with client-header-buffer-size

### ISSUE THREAD

**Issue by andrusstrockiy** [nginxinc/kubernetes-ingress#1045]
**Is your feature request related to a problem? Please describe.**
Currently we are facing issues with nginx ingress when it starts to receives big header more than 1k. 
In our case that's a jwt token inside Cookie HTTP request header i.e:
`AUTH_SESSION_ID=793114ad-5c06-4aac-840f-95054914da92.sso-idm; KEYCLOAK_LOCALE=ar; KEYCLOAK_IDENTITY=...removed.h; KEYCLOAK_SESSION=dev/a330df90-8c96-49cd-a18d-30e320f8aa04/793114ad-5c06-4aac-840f-95054914da92; JSESSIONID=7F7343FB026A7AB88540B87579DA08B3.sso-idm; experimentation_subject_id=ImUwNzIxMGVmLTliNDItNGMzMS05ZWFjLWVkZmJhNWMyZDFlNyI%3D--f76afeb15d060b202c824000e2dd5691868a15ed; _ga=GA1.2.19533997.1581670713; _fbp=fb.1.1582107701161.1640740530; _ym_uid=1582898215448474570; _ym_d=1582898215; __utma=241266590.19533997.1581670713.1583847414.1591001534.7; __utmz=241266590.1582898216.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); BCSI-AC-56bfb99e3cdd3762=2B79F72D00000306ytyJzJZxn87HqvF6spiO51sKPFl9AAAABgMAAEFBEgKAUQEAAAAAAIIvAAAAAAAA; JSESSIONID=2A1A677A54F19B8AB9E5C570E4D31A57; MPTrack=319593ac.5a07dedded4e1; __utmc=241266590`

so ingress returned an error HTTP 400

```
HTTP/1.1 400 Bad Request
Server: nginx/1.17.8
Date: Fri, 01 Jul 2020 15:57:13 GMT
Content-Type: text/html
Content-Length: 233
Connection: close

<html>
<head><title>400 Request Header Or Cookie Too Large</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>Request Header Or Cookie Too Large</center>
<hr><center>nginx/1.17.8</center>
</body>
</html>
```
To increase Request limit the following standard nginx config option should used https://nginx.org/en/docs/http/ngx_http_core_module.html#client_header_buffer_size

However that's option doesn't available either as CofigMap or as Annotations inside Ingress resources

**Describe the solution you'd like**
So I propose to extend nginx.ingress.tmpl or nginx.tmpl with variable which would be rendered from either from Annotations `"nginx.org/client-header-buffer-size" `or from` ingress-nginx-configmap`  as a key client-header-buffer-size 

**Describe alternatives you've considered**
To overcome above we turned to last resort `custom-templates`https://github.com/nginxinc/kubernetes-ingress/tree/v1.7.2/examples/custom-templates to include inside server block of  nginx.ingress.tmpl client_header_buffer_size
However that's not very convened way due-to the fact that's now nginx ingress is configured from 3 different sources i.e annotations,configmap and now custom-templates
**Additional context**
Community Nginx Ingress already equipped with  the following option
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#client-header-buffer-size

**Comment by pleshakov** [comment]
Hi @andrusstrockiy 

Thanks for the proposal. The ConfigMap key and optionally annotation make sense.

As a workaround, could you try to use the snippets feature? Snippets allow you to insert NGINX config snippets into the generated NGINX config. This will remove the need to use custom templates.

For example, with the configmap:
```yaml
server-snippet: client_header_buffer_size  2K;
```

Or, with an annotation:
```yaml
nginx.org/server-snippets: client_header_buffer_size  2K;
```

See also:
* https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#snippets-and-custom-templates
* https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/#snippets-and-custom-templates

**Comment by andrusstrockiy** [comment]
>As a workaround, could you try to use the snippets feature?

Thanks , for above advice it's definitely saved my day and made ingress resource easier to maintain
However, I decided to stick with  with an annotation i.e 

`nginx.org/server-snippets: client_header_buffer_size  2K;`

for some reasons configmap key `server-snippet: client_header_buffer_size  2K;` 
was ignored  in final config file after running
```bash
$ kubectl exec -n nginx-ingress nginx-ingress-nginx-ingress-27mzb -- nginx -T > final.conf
```
maybe that's just my local setup environment ingress controller of version v1.6.2 or something else, anyway annotation is totally ok.

If possible  @pleshakov could you clarify the following issue:
Now i had the following line of annotation inside ingress resource 
```bash
nginx.org/server-snippets: client_header_buffer_size  2K;
```
so one day we would like to extend ingress with another nginx.org/server-snippets with
```bash
    nginx.org/server-snippets: |
      location / {
        return 302 /coffee;
      }
```
so how i should merge\join these two annotation so both of them will be rendered correctly. My guess is that it should something like:
 
```bash
   nginx.org/server-snippets: client_header_buffer_size  2K
   nginx.org/server-snippets: |
      location / {
        return 302 /coffee;
      }
```
Am I right ?

**Comment by pleshakov** [comment]
@andrusstrockiy 

glad the solution worked for you!

> for some reasons configmap key server-snippet: client_header_buffer_size 2K;
was ignored in final config file after running

there is a typo here. in should be `server-snippets`

> so how i should merge\join these two annotation so both of them will be rendered correctly. My guess is that it should something like:

only one annotation is allowed. so the following would be a way to go:
```
   nginx.org/server-snippets: |
      client_header_buffer_size  2K;
      location / {
        return 302 /coffee;
      }
```

when using snippets, it is easy to make a mistake (for example, forget to place `;` after a directive). I suggest looking the events section of an Ingress resource after you add a snippet to confirm that the configuration was successfully updated.  See https://docs.nginx.com/nginx-ingress-controller/troubleshooting/#checking-the-events-of-an-ingress-resource

**Comment by andrusstrockiy** [comment]
will close the issue
