### ISSUE TITLE
Is CloudFlare proxy option supported?

### ISSUE THREAD

**Issue by vforv** [nginxinc/kubernetes-ingress#1049]
I have CloudFlare and added on it added A record of haproxy loadbalancer, behind loadbalancer are worker nodes of kubernetes cluster and your ingress controller.

Ingress routing traffic good when proxy option on CloudFlare on A record is disable as soon I enable proxy option on CloudFlare it will stop working and I will get only default cloud flare page in browser..

Anyone know what is issue?

**Comment by pleshakov** [comment]
Hi @vforv 

Were you able to resolve the issue?

I don't think we can help much as we don't have expertise with CloudFlare

**Comment by serain** [comment]
FWIW, I have the same issue with the Kong Ingress. Everything works fine until I switch Cloudflare proxy on.

This seems to be a wider issue between Cloudflare and k8s ingress.

(I'm using DigitalOcean's managed k8s, with the Kong Ingress)

**Comment by sonnd08** [comment]
The same issue with Cloudflare proxy, @serain do you have any updates?
