### ISSUE TITLE
Created ingress without ADDRESS, and connection refused..

### ISSUE THREAD

**Issue by zhangtiny123** [nginxinc/kubernetes-ingress#105]
Hi ,

I followed the complete-example to deploy a nginx ingress controller, but it seems not working well for me.

Follow the steps and create an ingress , when I run `kubectl get ingress` or `kubectl describe ingress`, I can't see the expected **ADDRESS**.

And try to run `curl --resolve ...` , always be refused.

I noticed the logs of nginx ingress controller pod, every time I create the ingress, it print a start process information
`2016/12/29 xx:xx:xx [notice] 19#19: signal process started
2016/12/29 xx:xx:xx [notice] 24#24: signal process started
2016/12/29 xx:xx:xx [notice] 29#29: signal process started`

Thanks in advance

**Comment by zhangtiny123** [comment]
I checked the nginx config file in the container, it looks well..

And the `ps aux ` command out put seems the process is OK.

Tried to ping the backend container IP, it's OK.

But I run `netstat -lntp` on the host where the nginx-ingress-controller lives, the host is not listening port 80 and 443...

Maybe this is the problem.

**Comment by pleshakov** [comment]
@zhangtiny123 
Please check this issue https://github.com/nginxinc/kubernetes-ingress/issues/72 Maybe your issue is similar.

You can try to use the hostNetwork option: add `hostNetwork: true` to the Pod spec.

> Follow the steps and create an ingress , when I run kubectl get ingress or kubectl describe ingress, I can't see the expected ADDRESS.

the controller doesn't set the ADDRESS yet.

**Comment by zhangtiny123** [comment]
@pleshakov 
Thanks for your reply!
I set the `hostNetwork: true` , and it works well.
