### ISSUE TITLE
add proxy headers

### ISSUE THREAD

**Issue by vforv** [nginxinc/kubernetes-ingress#1056]
**Is your feature request related to a problem? Please describe.**

Yes I cannot add proxy headers for the app to function properly

**Describe the solution you'd like**

I want when I configuring ConfigMap to be able to update all proxy headers and add custom

**Describe alternatives you've considered**

I don't know any alternatives expect to start using other ingress controller

**Additional context**

No

**Comment by pleshakov** [comment]
Hi @vforv 

Could you possibly give an example of what headers you're trying to add?

One way to accomplish adding custom proxy headers - use the location-snippets. You can add them either in the configmap (` location-snippets` key) or as an annotation (`nginx.org/location-snippets`).

For example:
```yaml
location-snippets: "proxy_set_header my-header my-value;"
```

**Comment by vforv** [comment]
Awesome! thanks
I am trying to add: `add_header "Access-Control-Allow-Origin" * always;`
Could you tell me is there any header to keep socket connection alive? Or it is by default?

**Comment by pleshakov** [comment]
@vforv 
> I am trying to add: add_header "Access-Control-Allow-Origin" * always;

the snippets approach should work.

> Could you tell me is there any header to keep socket connection alive? Or it is by default?

is it between the client and NGINX? if that is the case, it is enabled by default. It is also controlled by `keepalive-timeout` and `keepalive-requests` configmap keys.

for keepalives between NGINX and backends, see the `keepalive` configmap key. it is disabled by default
