### ISSUE TITLE
Question : Support SSL passthrough

### ISSUE THREAD

**Issue by prongcs** [nginxinc/kubernetes-ingress#1057]
Does this version of ingress controller support SSL passthrough?

**Comment by Dean-Coakley** [comment]
Hi @prongcs 

We support TLS Passthrough. Please see the following example:
https://github.com/nginxinc/kubernetes-ingress/tree/master/examples-of-custom-resources/tls-passthrough

**_Please note_**: This feature is only available when using our Custom Resources. - It is not compatible with the Ingress resource.

**Comment by Dean-Coakley** [comment]
@prongcs Did the above example work for you? - Do you have any further questions?

**Comment by prongcs** [comment]
@Dean-Coakley Sorry for the late reply.So, when i try to create a transportserver object using kubectl it gives an error "no matches for kind "TransportServer" in version "k8s.nginx.org/v1alpha1"". Can you please help on this?

**Comment by prongcs** [comment]
@Dean-Coakley Never mind. I've skipped installing TransportServer CRD earlier. Once i install,i was able to create TransportServer resource successfully. However, I've noticed this behavior:
When i run this command "openssl s_client -connect {HostName}", its referring to the "NGINXIngressController" default certificate rather it should return my custom certificate which is defined in the nginx pod. However, it routes to the correct backend though.

Here's the complete output of the openssl s_client -connect command:
CONNECTED(00000003)
depth=0 CN = NGINXIngressController
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = NGINXIngressController
verify return:1
---
Certificate chain
 0 s:/CN=NGINXIngressController
   i:/CN=NGINXIngressController
---
Server certificate
-----BEGIN CERTIFICATE-----
MIICvjCCAaYCCQDAOF9tLsaXXDANBgkqhkiG9w0BAQsFADAhMR8wHQYDVQQDDBZO
R0lOWEluZ3Jlc3NDb250cm9sbGVyMB4XDTE4MDkxMjE4MDMzNVoXDTIzMDkxMTE4
MDMzNVowITEfMB0GA1UEAwwWTkdJTlhJbmdyZXNzQ29udHJvbGxlcjCCASIwDQYJ
KoZIhvcNAQEBBQADggEPADCCAQoCggEBAL/7hHPKEXdLv3riC7BPk13iZKyy9rCO
GlYQv2+a3P1tk2+Kv0TayhdBl4krsTq6sfo/YI5ceanL8Xc7SZrBEQboD7dDmk5B
8x6KKlGYNHZX4FnTgEOi+e3jmLQqFPRcY3VsOk1EyFA/BgZRUnCGeKFxDR7KPthr
kjIunzKTEu2h58NZtKmRqBGt10q3Qc8YOq13agnj/QdcsFXa2g20u+YXd7hgy+fK
ZN/UI1AD4c6r3YfkVVReGwYqAZuYsvWDJmmF5dptC37Mup0OELULLRjFI96W5r0H
5NgOsnMXRMWXXVZb5dqOttJdmKqagnSgRPAZP7c0B1PSajc6c4fQUzMCAwEAATAN
BgkqhkiG9w0BAQsFAAOCAQEAjKokQtdOpK+O8bmeOsyrJgIIrrqQUcfNR+coHYUJ
thkbxHLS3GuAMb9vmyTLOclqx/Zc2OnQ00BB/9SoK0r+EgU6RUkEkVr+SLP757TZ
3eb8vgOtGn1/bzs7o3Ai/drY+qB9Ci5KyOsqGLmTKlEiKNbG2GVrMlcKFXAO4a67
IgsXsbKMm40WU7pofpimSVfiqRvEybcw7CX81zpQ+S+uxtX+eAgut4xwVR9wb2Uv
zXnfOGmhV58CwWHBsJkI15xZkeTYwR7GbhALJFTRI7vHoAzkMb3n01B42Z3k7tW5
IP1fNZH8U/9lbPshOmEDVdv1yg+UERqm+FJ+6GJ1xRFpfg==
-----END CERTIFICATE-----
subject=/CN=NGINXIngressController
issuer=/CN=NGINXIngressController
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 1376 bytes and written 431 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: CD6F1F93A4197746D940CF1B2EB3AA25D492226C135D9261C085226064393FEF
    Session-ID-ctx:
    Master-Key: 24C93517A70F6A3288A77A612DDF36125FEF57071DA6A000432CFB95AD19F21E1A1927D46D6754A424E3EBF66975B67D
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 01 fb 52 3c 93 1f ea ae-f8 6e 7e 8e 65 3e 65 3c   ..R<.....n~.e>e<
    0010 - 5a 9a 9b 5e 7b ed f4 97-f7 5b af c8 26 ac 6d 24   Z..^{....[..&.m$
    0020 - 96 a7 40 0b 5d 47 a6 68-2e 8b 64 de bc 0f ef a8   ..@.]G.h..d.....
    0030 - cb ab 26 48 78 18 b8 3f-44 ef 88 91 56 6e f7 b7   ..&Hx..?D...Vn..
    0040 - 7e a5 4a 5f b0 bc ad 6b-e3 38 86 d9 d2 ce e3 58   ~.J_...k.8.....X
    0050 - e2 e6 8a 23 da 16 d4 aa-76 de 0e 89 ff 08 2a a9   ...#....v.....*.
    0060 - 89 98 ac b9 59 dd 60 20-e9 4f f2 1a 90 86 df 6e   ....Y.` .O.....n
    0070 - fe 80 0a 02 e3 74 23 77-3f 4c 46 f8 eb 93 d0 45   .....t#w?LF....E
    0080 - 2c 72 da 42 ab f2 79 fb-21 30 8b 07 0c 60 12 57   ,r.B..y.!0...`.W
    0090 - 21 ac d5 ce 8d c7 67 79-1d 57 be 53 27 f8 b0 73   !.....gy.W.S'..s
    00a0 - 22 ed 73 49 ca f0 46 7d-92 47 98 6a f8 81 01 59   ".sI..F}.G.j...Y

    Start Time: 1596562042
    Timeout   : 300 (sec)
    Verify return code: 18 (self signed certificate)
---
closed

**Comment by Dean-Coakley** [comment]
@prongcs Sorry for the delay in my response.

As far as I know the `openssl` client does not set the SNI by default, which is required for TLS passthrough.

I think if you set the SNI like the following example you should see the custom certificate in the response rather than the default one:
```bash
openssl s_client -connect {HostName} -servername {HostName}
```

**Comment by Dean-Coakley** [comment]
Closing. 

Feel free to open a new issue if you have any further questions!
