### ISSUE TITLE
recv() failed (104: Connection reset by peer) while reading response header from upstream

### ISSUE THREAD

**Issue by harshsharma22** [nginxinc/kubernetes-ingress#1063]
**Describe the bug**
sometimes receives this error message on my nginx

**To Reproduce**
1. Deploying nginx with some openresty conf
2. View log on console

**Expected behavior**
it should not through this error

**Your environment**
* custom image of nginx with openresty
* Version of Kubernetes v1.18.2+k3s1
* k3s
* Using NGINX 

**Additional context**
using nginx with some open restry configuration 
here  is my server conf
worker_processes auto;
pid /app/logs/nginx.pid;
events {
    worker_connections 8192;
}

include ./expose_env_var.conf;

include ./conf.d/main/main__ENV__.conf;

http {
    include mime.types;
    include ./conf.d/http/default__ENV__.conf;
    default_type text/html;
    proxy_connect_timeout       1200;
    proxy_send_timeout          1200;    
    proxy_read_timeout          1200;
    send_timeout                1200;
    client_max_body_size 100M;
    sendfile on;
    keepalive_timeout 65;
# proxy_set_header Accept-Encoding "";

## -- block for detailed logging and capturing req & res in http block
    init_by_lua_block {
        cjson = require "cjson"
        jwt = require "resty.jwt";
    }

    lua_need_request_body on;
    
    log_by_lua_file ./build/lua/log.lua;

    log_format json escape=json '{ "type":"gateway", "timestamp": "$time_local", '
    '"req_body": "$req_body", '
    '"resp_body": "$resp_body", '
    '"user_email": "$user_email", '
    '"host": "$host", '
    '"remote_addr": "$remote_addr", '
    '"remote_user": "$remote_user", '
    '"time_local": "$time_iso8601",'
    '"server_protocol": "$server_protocol", '
    '"status": $status, '
    '"bytes_sent": $bytes_sent, '
    '"http_referrer": "$http_referer", '
    '"http_user_agent": "$http_user_agent",'
    '"request_time": $request_time, '
    '"upstream_response_time": $upstream_res_time, '
    '"upstream_connect_time": "$upstream_connect_time", '
    '"request_uri": "$request_uri", '
    '"request_method": "$request_method"}';

    ## tail this file for logs as stdout logs impact nginx performance and logs to syslog gets affected.
    # access_log logs/access_log.log json;

    access_log /dev/stdout json;

    error_log stderr info;
}

**Comment by Rulox** [comment]
Hi @harshsharma22 

Are you using the NGINX Ingress Controller of this repository? It seems you're using a custom NGINX Image inside a k8s cluster. I am sorry but we can't help you here, as this repository is only for the NGINX Ingress Controller, and we can't offer support outside of this.

As you're using Openresty (which is a different project), I suggest you open an issue in their [repository](https://github.com/openresty/openresty). Additionally, you can also use the NGINX mailing list for [support](http://nginx.org/en/support.html) with NGINX open source.

Let me know if this makes sense.
