### ISSUE TITLE
[Helm chart] Only watch current namespace.

### ISSUE THREAD

**Issue by agniveshadhikari** [nginxinc/kubernetes-ingress#1069]
**Is your feature request related to a problem? Please describe.**
I can't seem to find a way to configure the controller to only watch the current namespace, i.e., the namespace I deployed the chart into. I could override the `controller.watchNamespace` value, but an option like `controller.onlyWatchCurrentNamespace` would great.

If I am missing an obvious way to achieve this, I'd be happy to learn.

**Describe the solution you'd like**
`controller.onlyWatchCurrentNamespace` (or some better name) as a value

**Describe alternatives you've considered**
Overriding the value for each release. But I want to use `{{ .Release.namespace }}`

**Comment by pleshakov** [comment]
Hi @agniveshadhikari 

Configuring `controller.watchNamespace` should do the job.  I wonder what doesn't work? if the namespace is not known in advance, perhaps `$(POD_NAMESPACE)` can do the trick? That env variable is available and is used in the other IC arguments.

**Comment by agniveshadhikari** [comment]
Yep, I was only thinking from the perspective of *how to get helm to inject the namespace in the manifest itself*. Missed the fact that it could be inferred at runtime too. I'm not sure, given both the options (helm put it in manifest v/s runtime inference), which is neater. I'll try out your suggestion for now. Thanks!
