### ISSUE TITLE
Remove extra lines in vs/vsr snippets

### ISSUE THREAD

**Issue by mkryshak** [nginxinc/kubernetes-ingress#1074]
This is a purely cosmetic suggestion when you need to "view" the raw configuration.  When using snippets with vs/vsr, extra new lines are added.  For example, this snippet:

```
spec:
  http-snippets: |
    auth_jwt_claim_set $jwt_aud aud;
    auth_jwt_claim_set $jwt_tid tid;

    proxy_cache_path /var/cache/nginx/jwk levels=1 keys_zone=jwk:64k max_size=1m;
```
Results in this configuration output:
```
auth_jwt_claim_set $jwt_aud aud;

auth_jwt_claim_set $jwt_tid tid;


proxy_cache_path /var/cache/nginx/jwk levels=1 keys_zone=jwk:64k max_size=1m;
```

I can get around this by modifying the template, for example:
```
{{ range $snippet := .HTTPSnippets }}
{{- $snippet }}
{{ end }}
```
It would be great if I didn't have to modify the template though.

**Comment by pleshakov** [comment]
Hi @mkryshak  Thanks for the proposal. It makes sense to preserve user-provided NGINX config as is. We'll implement it.
