### ISSUE TITLE
got too many 307 redirects

### ISSUE THREAD

**Issue by lw8008** [nginxinc/kubernetes-ingress#1079]
**Describe the bug**
We got too many 307 redirects when use nginx inc.

> curl https://10.8.24.25 -H "Host: argocd.pc8-deliverytools-ilb.xx.xx.xx" -kL
curl: (47) Maximum (50) redirects followed

redirect details:
< HTTP/1.1 307 Temporary Redirect
* Server nginx/1.19.0 is not blacklisted
< Server: nginx/1.19.0
< Date: Wed, 29 Jul 2020 06:48:02 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 85
< Connection: keep-alive
< Location: https://argocd.pc8-deliverytools-ilb.xx.xx.xx/

Ingress yaml:
> kubectl get ing -n argocd argocd-server-ingress -oyaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  name: argocd-server-ingress
  namespace: argocd
spec:
  rules:
  - host: argocd.pc8-deliverytools-ilb.xx.xx.xx
    http:
      paths:
      - backend:
          serviceName: argocd-server
          servicePort: 443
  tls:
  - hosts:
    - argocd.pc8-deliverytools-ilb.xx.xx.xx
    secretName: wildcard.pc8-deliverytools-ilb.xx.xx.xx
status:
  loadBalancer:
    ingress:
    - ip: 10.8.24.25

**Your environment**
* Version of the Ingress Controller - release version or a specific commit
nginx-ingress:1.7.2

* Version of Kubernetes
1.17.4

* Kubernetes platform (e.g. Mini-kube or GCP)
Rancher

* Using NGINX or NGINX Plus
NGINX

It was works in ingress controller with below config in configmap:
data:
  ssl-redirect: "false"
  use-forwarded-headers: "true"
reference: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/

Wondering how can i make it work in nginx inc?

**Comment by Rulox** [comment]
Hi @lw8008 

The annotations and ConfigMap keys from the [community Ingress Controller](https://github.com/kubernetes/ingress-nginx) are different than the ones for the NGINX Ingress Controller (this repository), and they can't be used. Let me explain the main differences of your example:

For the annotations of the Ingress Resource:

* `nginx.ingress.kubernetes.io/backend-protocol`. We don't have this distinction in our Ingress Controller.
* `nginx.ingress.kubernetes.io/ssl-passthrough`. We don't support TLS passthrough with Ingress Resources. If you want to use TLS Passthrough, we support this by using our own resource `TransportServer`. Check the [example](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples-of-custom-resources/tls-passthrough) for more information.

For the ConfigMap Keys:

* `ssl-redirect` This is fine, we use the same.
* `use-forwarded-headers` We don't support this. What are you trying to do with this? Maybe there's a workaround that we can do for this. Is it to forward the `X-Forward-*` headers to the upstream servers? We support the following headers by default (this means, you don't have to use any annotation):
```
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Port $server_port;
proxy_set_header X-Forwarded-Proto... # this will be set to http/https depending on the request schema;
```


In general, what are you trying to accomplish? Maybe with more information I'll be able to help. Do you want to use TLS Passhtrough for your backend? If yes, the only way we support this is using our custom resources (the example I just gave to you about TransportServers).

I hope this all makes sense. Let me know if you have any more questions.
