### ISSUE TITLE
Question: Serving static content

### ISSUE THREAD

**Issue by Mr-Reca** [nginxinc/kubernetes-ingress#1081]
Hello everyone,

I'm using v1.8.0 in a v1.16.3 k8s cluster and I'm trying to deploy a Django application. As I checked in their documentation, Django doesn't serve static files in a production environment, but they can be collected in a path/host.
[Django Deployment](https://docs.djangoproject.com/en/3.0/howto/static-files/#deployment)
[Django Deploying static files](https://docs.djangoproject.com/en/3.0/howto/static-files/deployment/)

Is there a way to configure NGINX Ingress to serve that content from a pod?

Example:
- The browser will request `https://myapp/static/css/style.css` 
- I need to serve the file `/static_assets/css/style.css` which is stored in the pod that serves `myapp`.

Maybe creating a location with `nginx.org/server-snippets` can do the trick. 

Thanks in advance,

**Comment by Dean-Coakley** [comment]
Hi @Mr-Reca 

Do you have an nginx running, doing a `proxy_pass` in your django pod? 

If you don't, I'd recommend adding one. This will allow django to handle your dynamic context and nginx to handle your static content.

You can just configure another location for the static files. 
Something like the following should work:
```nginx
location /static/ {
  root /static_assets;
}
```
See: https://docs.nginx.com/nginx/admin-guide/web-server/web-server/ for additional details/if you run into issues.


Alternatively, you can have a different pod for the static files with an nginx serving them and configure a new path in the ingress. But from your described use case it doesn't sound like that makes much sense.

**Comment by Mr-Reca** [comment]
Hi @Dean-Coakley 

Thank you so much for your quick response.

What I have now is NGINX Ingress Controller running in the cluster. I've created a Pod which runs Django, and I configured an Ingress to serve that pod outside the cluster.

So what I need to do is to run another NGINX pod (different from the one created with the Ingress Controller) with the Django pod, and share the static content with the NGINX pod? It will also require to configure the Ingress resource to serve Django at / and NGINX at /static/, is that correct?

I was thinking about using the pod that Ingress Controller creates, but I guess it's not possible because they are different "machines".

Thanks you so much,

**Comment by Dean-Coakley** [comment]
There are many ways to configure it.
* You could deploy an additional nginx pod, separate to Django pod and ingress controller pod.
* You could add an additional nginx container to your Django pod.

Both of the above seem reasonable.

While it is possible from a technical perspective to make the Ingress Controller serve static content. I would not recommend it. The role of the nginx deployed by the ingress controller is to loadbalance traffic to your backend applications and not much else. You should try keep it that way. (Good practice: Separation of Concerns)

Hope that makes sense.

**Comment by Mr-Reca** [comment]
Good morning @Dean-Coakley 

Thank you so much for your answer. I understand your Good Practice. I thought that it would be better to use the Ingress for serving static. I also thought that having an NGINX that redirects to an NGINX that serves content was a bad practice and unefficient.

I'll deploy an additional NGINX (like static.mysite.com) and it will serve the content. Now I need to configure how to copy all the static content to that pod, but it's not a topic for this issue (and repository).

Thank you so much.
