### ISSUE TITLE
Warning when configuring proxy on VirtualServerRoute

### ISSUE THREAD

**Issue by grandfield** [nginxinc/kubernetes-ingress#1087]
**Describe the bug**:

In the [Cross-Namespace Configuration ](https://github.com/nginxinc/kubernetes-ingress/tree/v1.8.0/examples-of-custom-resources/cross-namespace-configuration) example, I tried to add a [Proxy Action](https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#action-proxy)  to my VirtualServerRoute, which is a valid property of [SubRoute](https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#virtualserverroute-subroute).

```
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: tea 
  namespace: tea
spec:
  host: cafe.localhost
  upstreams:
  - name: tea 
    service: tea-svc
    port: 80
  subroutes:
  - path:  /tea
    action:
      proxy:
        upstream: tea
        rewritePath: /mynewpath
```

When I call

`kb describe vsr tea -n tea`

i can see the line:
``` 
Events:
  Type     Reason          Age   From                      Message
  ----     ------          ----  ----                      -------
  Warning  Rejected        6s    nginx-ingress-controller  VirtualServerRoute tea/tea is invalid and was rejected: spec.subroutes[0].action: Required value: action must specify exactly one of `pass`, `redirect` or `return`
  Warning  Ignored         6s    nginx-ingress-controller  Ignored by VirtualServer cafe/cafe: spec.subroutes[0].action: Required value: action must specify exactly one of `pass`, `redirect` or `return`
  Normal   AddedOrUpdated  6s    nginx-ingress-controller  Configuration for tea/tea was added or updated

 ```

This proxy did not work in version 1.6.1 and did work in 1.8.0. I just want to confirm that this is supported functionality and if the "warning rejected" message above is incorrect?

**Your Environment**:
version: nginx-ingress:1.8.0

**Kubernetes version**

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

- **OS** Window 10 Professional

**Comment by pleshakov** [comment]
Hi @grandfield 

The proxy action was added in 1.8.0. So it is expected that you get a warning rejected message in 1.6.1., because 1.6.1 doesn't know about that field.

Note that in 1.8.0 we added the status field to VirtualServer and VirtualServerRoutes -- https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/reporting-resources-status/#virtualserver-and-virtualserverroute-resources The status field will also reflect if a resource was rejected.

**Comment by grandfield** [comment]
Hi, thanks for the response. Just to clarify, my issue was that it was working in 1.8.0, but I was still getting the error message.

I looked up this diff [1.8.0](https://github.com/nginxinc/kubernetes-ingress/commit/9bc383caa142cf192b244dc9be65147ff59bb022) and noticed the error message was indeed correct in the 1.8.0 release.

It turns out that I had a stale configuration, where 1.8.0 was performing the correct behavior, but i also had 1.6.1 running which was creating the error at the same time. Closing the bug. Sorry for the false alarm.
