### ISSUE TITLE
Lighter Docker image

### ISSUE THREAD

**Issue by cescoferraro** [nginxinc/kubernetes-ingress#11]
Alpine linux supports nginx, got a great package manager and a full container with nginx weights 36MB instead of 255MB just from the ubuntu base image we are using here.
Something like (not tested btw)

```
FROM gliderlabs/alpine:3.3
# Install nginx
RUN apk add --update nginx=1.8.0-r1 && \
    rm -rf /var/cache/apk/* && \
    chown -R nginx:www-data /var/lib/nginx

# Add the files
ADD root /

# Expose the ports for nginx
EXPOSE 80 443

COPY nginx-ingress /
COPY nginx/ingress.tmpl /

RUN rm /etc/nginx/conf.d/*

CMD ["/nginx-ingress"]

```

**Comment by munnerz** [comment]
I'd be inclined to suggest we base off the official nginx image, and defer
these kind of efficiency improvements to the upstream repo. This way we can
fix nginx version in the image.

**Comment by cescoferraro** [comment]
Just realized there is an official alpine base nginx image on dockerhub. We could use that

**Comment by naphthalene** [comment]
There is no reason both an :alpine and a :latest set of images can't be maintained, aside from some additional code. There are certainly benefits and drawbacks to using either.
