### ISSUE TITLE
Filter "spam" updates to endpoints from HA kube-controller-manager and kube-scheduler

### ISSUE THREAD

**Issue by dadux** [nginxinc/kubernetes-ingress#111]
The controller sync the _kube-scheduler_ and _kube-controller-manager_ every 2seconds when they are started with the ```leader-elect=true``` option.

```
I0120 02:06:19.739768       1 controller.go:190] Endpoints kube-controller-manager changed, syncing
I0120 02:06:19.739800       1 utils.go:78] Syncing kube-system/kube-controller-manager
I0120 02:06:19.739807       1 controller.go:323] Syncing endpoints kube-system/kube-controller-manager
I0120 02:06:20.933421       1 controller.go:190] Endpoints kube-scheduler changed, syncing
I0120 02:06:20.933454       1 utils.go:78] Syncing kube-system/kube-scheduler
I0120 02:06:20.933462       1 controller.go:323] Syncing endpoints kube-system/kube-scheduler
I0120 02:06:21.761402       1 controller.go:190] Endpoints kube-controller-manager changed, syncing
```

There should be a filer to exclude those pods as they don't have a "real" endpoint, they only use it to determine which is the master.

see some related Kube issues :
https://github.com/kubernetes/kubernetes/issues/23812
https://github.com/kubernetes/kubernetes/issues/26637

**Comment by pleshakov** [comment]
@dadux many thanks for pointing that out.

**Comment by mmajko** [comment]
Is there a solution for this?
