### ISSUE TITLE
Annotation server-snippets overrides configmap server-snippets

### ISSUE THREAD

**Issue by robertgates55** [nginxinc/kubernetes-ingress#1111]
**Describe the bug**
I don't think this is quite a bug, but I wondered if you could help me. I'd like to set some 'default' server-snippets in a configmap, and then have certain ingresses providing additional snippets in their annotations. Is this possible?

**To Reproduce**
1. Deploy a configmap with `server-snippets` specified
2. Create an ingress - observe the nginx config created for that ingress contains the snippets from the configmap
3. Add the nginx.org/server-snippets annotation with an additional snippet
4. Observe that the 'default' config is overridden entirely by the annotation snippets.

**Expected behavior**
I hoped that the annotation (ingress) snippets would appear below the configmap snippets.

Any suggestions?

**Comment by pleshakov** [comment]
Hi @robertgates55 

Ingress snippets always override ConfigMap snippets. There is no option to enable merging. This could be a good feature to add.

As a workaround, I can suggest creating a custom annotation for server snippets -- https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/custom-annotations/ This way in the config for an Ingress you will get both the snippets from a configmap and the snippet from a custom annotation.
