### ISSUE TITLE
Nginx IC pod getting OOM killed

### ISSUE THREAD

**Issue by dhatri308** [nginxinc/kubernetes-ingress#1116]
We recently saw nginx IC pod getting OOM killed. I am trying to investigate the issue. 

We have 
worker_processes  "auto"
worker-connections: "8192" 

resources:
      limits:
        cpu: 1500m
        memory: 6Gi

If we want to support 8000 worker connections, any suggestions on how do we decide on the memory? Does it depend on request payload as well ? 

We have 3 ingresses, less than 50 secrets, less than 50 endpoints, less than 50 services and pods.
Thank you.

**Comment by pleshakov** [comment]
Hi @dhatri308 

A common reason for OOM of NGINX is too many worker processes. This can happen when the configuration changes are frequent and you also load balance applications with long-lived long-lived connections (WebSocket, applications with file uploading/downloading or streaming). 

When you reload NGINX, NGINX master process creates new worker processes with new configuration. The old worker processes are being shut down: they will exit when they finish any remaining requests they were processing. If you load balance something like WebSockets, an old NGINX worker processes will exit only when connection is terminated by the client or the backend. As a result, if reloads are too frequent, you might have too many old worker NGINX processes still running, which could lead to OOM.

I suggest checking if that was an issue.

There are some tunables for worker processes:
* `worker-shutdown-timeout` - Configures a timeout for a graceful shutdown of worker processes. When the time expires, nginx will try to close all the connections currently open to facilitate shutdown. This means any remaining connections will be terminated! Default is none.
* With `worker_processes "auto"`, NGINX will have N number of worker processes, where N is the number of cores on a node. So the more processes you have, more memory the IC will consume. If you want to decrease the number, you can set `worker_processes "1"` or any other number.

Also, there are some metrics available (https://docs.nginx.com/nginx-ingress-controller/logging-and-monitoring/prometheus/):
- `controller_nginx_reloads_total` - Number of successful NGINX reloads.

Coming in the new release - the new metric `controller_nginx_worker_processes_total`. Number of NGINX worker processes. This metric includes the constant label generation with two possible values old (the shutting down processes of the old generations) or current (the processes of the current generation). Already available in the edge version -- https://github.com/nginxinc/kubernetes-ingress#nginx-ingress-controller-releases

> If we want to support 8000 worker connections, any suggestions on how do we decide on the memory? Does it depend on request payload as well ?

it is hard to predict it as it depends on many factors. So I suggest monitoring the memory with some live traffic.

**Comment by dhatri308** [comment]
@pleshakov Apologies for the delayed response.
Yes, we had too many worker processes. We have added worker-shutdown-timeout and monitoring the number of worker processes. 
Great explanation, thank you very much.
