### ISSUE TITLE
SSL handshake logs are not showing up even after updating the log level to 3.

### ISSUE THREAD

**Issue by dileepyavan** [nginxinc/kubernetes-ingress#1118]
**Describe the bug**

Unable to find any SSL handshake logs. Tried by changing the logLevel to 3 and still couldn't get the logs. Is there anything else that have to be changed in the helm chart configuration for nginx-ingress?

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**
SSL handshake failures should be captured in the logs on nginx-ingress.
**Your environment**
* Version of the Ingress Controller - 1.8.1
* Version of Kubernetes - 1.15.X
* Kubernetes platform : AKS
* Using NGINX

**Comment by pleshakov** [comment]
Hi @dileepyavan 

To view SSL handshake failures, you need to configure NGINX log to `info` verbosity, which is controlled via `error-log-level` ConfigMap key -- https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#logging For helm chart, the ConfigMap is configured via `controller.config.entries` parameter.

As a result, you will see handshake failures in the log. For example:
```
2020/08/31 22:24:58 [info] 42#42: *19 SSL_do_handshake() failed (SSL: error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher) while SSL handshaking, client: 127.0.0.1, server: 0.0.0.0:443
```

**Comment by dileepyavan** [comment]
Thanks @pleshakov  for the update. Will try as you mentioned. Also if I need to get the logs when nginx-ingress fallback to default cert in case of a missing secret, does setting error-log-level to info work.

**Comment by dileepyavan** [comment]
Updated the helm chart values file as below: 
config:
    entries:
      error-log-level: info

I am still not seeing SSL  handshake logs as the error-log-level is not changed to info from notice.

2020/09/01 22:59:03 [notice] 14#14: signal 17 (SIGCHLD) received from 180

**Comment by pleshakov** [comment]
> Also if I need to get the logs when nginx-ingress fallback to default cert in case of a missing secret, does setting error-log-level to info work.

In this case you will see a warning in the IC logs like below:
```
Error trying to get the secret cafe-secret for Ingress cafe-ingress: secret default/cafe-secret not found
```

> I am still not seeing SSL handshake logs as the error-log-level is not changed to info from notice.

> 2020/09/01 22:59:03 [notice] 14#14: signal 17 (SIGCHLD) received from 180

this is expected. the notice level log entries will still retain the `[notice]` part. Can you see any `[info]` related entries?

**Comment by dileepyavan** [comment]
I don't see any info related entries. Is there a way to check the value of error-log-level config map key inside the container.

**Comment by pleshakov** [comment]
@dileepyavan you can check the content of `nginx.conf` -- https://docs.nginx.com/nginx-ingress-controller/troubleshooting/#checking-the-generated-config -- and ensure that error log directive looks like below:
```
error_log  /var/log/nginx/error.log info;
```

**Comment by dileepyavan** [comment]
It shows up as error_log  /var/log/nginx/error.log notice.

Let me try to re-deploy the cluster and verify.

**Comment by dileepyavan** [comment]
I still see this in nginx.conf error_log /var/log/nginx/error.log notice. Is there anything else I am missing

**Comment by pleshakov** [comment]
@dileepyavan could yo describe the configmap https://docs.nginx.com/nginx-ingress-controller/troubleshooting/#checking-the-events-of-the-configmap-resource ? Just to double check that it was created correctly

**Comment by dileepyavan** [comment]
Thanks @pleshakov for the help. This is fixed now. The issue was that we already have a config map and I am trying to add the error-log-level config map key to controller.config.entries. Instead I added it in the config map file that we have and it showed up correctly.
