### ISSUE TITLE
Deploy the Nginx ingress controller in eks with internal ALB

### ISSUE THREAD

**Issue by newtoworld999** [nginxinc/kubernetes-ingress#1123]
Hi 
I wanted to deploy the nginx ingress controller in EKS cluster with internal ALB, I followed the steps  mentioned as per the site 
https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/
Iam getting error that the subnets are not tagged properly. I tagged the subnets and my subnets are private. what config changes needs to be done and where to deploy the internal ALB with NGINX ingress controller in EKS.

**Comment by Dean-Coakley** [comment]
Hi @newtoworld999 

I'm not very familiar with this type of setup but I'll do my best to assist you. :) 

The NGINX Kubernetes Ingress controller doesn't have any support for AWS tagged subnets as it's an AWS specific concept.

Is the error you're seeing from the nginx ingress controller pod? Can you share/paste that error here?

Is your EKS cluster public or private? Are you deploying an internal ALB or internal ALB with an [ALB ingress controller](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html)?
