### ISSUE TITLE
unexpected status code https://dockerhub.azk8s.cn/v2/docker/dockerfile-copy/manifests/sha256:e8f159d3f00786604b93c675ee2783f8dc194bb565e61ca5788f6a6e9d304061: 403 Forbidden

### ISSUE THREAD

**Issue by tulid** [nginxinc/kubernetes-ingress#1128]
**Describe the bug**
i make the nginx-ingress image on mips64le architecture. And i changed the default image to mips64le about golang and nginx.
then i conduct the command "make PREFIX=example.registry.com/nginx-ingress". The bug happens as blow:
# make PREFIX=harbor.cetccloud.com/mips64le/nginx-ingress
docker build  --build-arg IC_VERSION=1.18.0-739e35a7 --build-arg GIT_COMMIT=739e35a7 --build-arg VERSION=1.18.0 --build-arg GOLANG_CONTAINER=harbor.cetccloud.com/mips64le/golang:1.15.1 --target container -f build/Dockerfile  -t harbor.cetccloud.com/mips64le/nginx-ingress:1.18.0 .
[+] Building 1.1s (10/14)
 => [internal] load .dockerignore                                                                           0.1s
 => => transferring context: 2B                                                                             0.0s
 => [internal] load build definition from Dockerfile                                                        0.1s
 => => transferring dockerfile: 32B                                                                         0.0s
 => [internal] load metadata for harbor.cetccloud.com/mips64le/nginx:1.18.0                                 0.0s
 => [internal] load metadata for harbor.cetccloud.com/mips64le/golang:1.15.1                                0.0s
 => ERROR [internal] helper image for file operations                                                       0.1s
 => => resolve docker.io/docker/dockerfile-copy:v0.1.9@sha256:e8f159d3f00786604b93c675ee2783f8dc194bb565e6  0.1s
 => [base 1/4] FROM harbor.cetccloud.com/mips64le/nginx:1.18.0                                              0.0s
 => CANCELED [internal] load build context                                                                  0.1s
 => => transferring context: 922.85kB                                                                       0.1s
 => CACHED [builder 1/3] FROM harbor.cetccloud.com/mips64le/golang:1.15.1                                   0.0s
 => CACHED [base 2/4] RUN ln -sf /proc/1/fd/1 /var/log/nginx/access.log  && ln -sf /proc/1/fd/1 /var/log/n  0.0s
 => CANCELED [base 3/4] RUN mkdir -p /var/lib/nginx  && mkdir -p /etc/nginx/secrets  && mkdir -p /etc/ngin  0.9s
------
 > [internal] helper image for file operations:
------
unexpected status code https://dockerhub.azk8s.cn/v2/docker/dockerfile-copy/manifests/sha256:e8f159d3f00786604b93c675ee2783f8dc194bb565e61ca5788f6a6e9d304061: 403 Forbidden
make: *** [Makefile:57：container] 错误 1

**Expected behavior**
Image be built seccessfully

**Your environment**
* Version of the Ingress Controller - release version or a specific commit 
739e35a7
* Version of Kubernetes
1.15
* rancher
* Using NGINX or NGINX Plus
nginx:1.18.0

**Comment by pleshakov** [comment]
@tulid were you able to solve the issue? It looks like you weren't authenticated with the Docker registry  https://dockerhub.azk8s.cn/ , because you got 403 response code.
