### ISSUE TITLE
Improve handling of client IP information with additional proxy or LB in the front

### ISSUE THREAD

**Issue by hostalp** [nginxinc/kubernetes-ingress#1134]
**Is your feature request related to a problem? Please describe.**
With additional load balancer in the front of the NGINX ingress controller we can't currently see real client IP in the NGINX ingress access logs.

**Describe the solution you'd like**
We'd like to be able to at least see the real client IP in the ingress logs.

**Additional context**
The Kubernetes project NGINX ingress controller (https://github.com/kubernetes/ingress-nginx/) has few interesting features that come handy in the case when any other proxy or load balancer is in the front of the NGINX ingress controller:

> **use-forwarded-headers**
If true, NGINX passes the incoming X-Forwarded-* headers to upstreams. Use this option when NGINX is behind another L7 proxy / load balancer that is setting these headers.
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-forwarded-headers

> **enable-real-ip**
enable-real-ip enables the configuration of http://nginx.org/en/docs/http/ngx_http_realip_module.html. Specific attributes of the module can be configured further by using forwarded-for-header and proxy-real-ip-cidr settings.
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#enable-real-ip

> **compute-full-forwarded-for**
Append the remote address to the X-Forwarded-For header instead of replacing it. When this option is enabled, the upstream application is responsible for extracting the client IP based on its own list of trusted proxies.
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#compute-full-forwarded-for

These help with getting and logging the client real IP both at the NGINX ingress controller itself as well as at the deployment behind it.
Could you please implement these (in your Helm chart) as well?

**Comment by pleshakov** [comment]
Hi @hostalp 
 
In the ConfigMap https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#general-customization , we have: `real-ip-header`, `real-ip-recursive`, `set-real-ip-from`. If you configure them, then NGINX will start using the client IP it gets from the fronting proxy and NGINX will pass it in the `X-Real-IP` header to the backend.

> With additional load balancer in the front of the NGINX ingress controller we can't currently see real client IP in the NGINX ingress access logs.

It seems to me from reading that description that the already implemented features should cover your requirements. Could you possibly double check that those features were configured correctly? If you share your Ingresses and ConfigMap, we can take a look and try to spot any problems.

Also, note that we recently fixed a bug https://github.com/nginxinc/kubernetes-ingress/issues/1072 that made it impossible to see client IP in the NGINX logs for the default server (the server that handles client requests for non-existing host names).

**Comment by hostalp** [comment]
Hello,
awesome, that's it, thank you for the hint. I wouldn't easily find it myself.

Perhaps you shoud consider adding the https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/ link to the Helm chart description so one would easily find it? At least to the `controller.config.entries` param description or maybe elsewhere. It isn't very straightforward when starting from https://hub.helm.sh/charts/nginx/nginx-ingress

**Comment by pleshakov** [comment]
@hostalp 
it makes sense to add links to that page. thanks for the suggestion! we'll add them.
