### ISSUE TITLE
Status 502

### ISSUE THREAD

**Issue by harshsharma22** [nginxinc/kubernetes-ingress#1140]
**Describe the bug**
status 502 keeps comming  . In case of proxy-next-upstream
**To Reproduce**
1. Deploy nginx-ingress via helm . And create virtual server for a microservice use proxy-next-upstream option
2 add hpa to a microservice
3. Make load requests  to that microservice
4. Often recieve 502. While upscaling 

**Expected behavior**
Shouldn't  come  502 as proxy next upstream is set

**Your environment**  
Kubernetes  platform k3s
Kubernetes  version  v1.18.6+k3s1
* Using NGINX or NGINX Plus
Nginx ingress  with virtual  servers  
Version nginx/nginx-ingress1.8.1 deployed via helm

**Comment by lucacome** [comment]
Hi @harshsharma22 

would you mind sharing your configuration so I can better understand the situation?

Thanks

**Comment by harshsharma22** [comment]
@lucacome  
my virtual server configuration
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: vs-__NAMESPACE__
  namespace: __NAMESPACE__
  
spec:
  http-snippets: |
    proxy_cache_path /etc/nginx/cache keys_zone=__NAMESPACE__:10m;
    js_import main from extra-conf/jwt.js;
    js_set $jwtUserEmail main.jwtUserEmail;
    log_format __NAMESPACE__json escape=json '{ "name": "__NAMESPACE__", '
    '"timestamp": "$time_local", '
    '"req_body": "$request_body", '
    '"upstream-status": "$upstream_status", '
    '"user_email": "$jwtUserEmail", '
    '"host": "$host", '
    '"remote_addr": "$remote_addr", '
    '"remote_user": "$remote_user", '
    '"time_local": "$time_iso8601",'
    '"server_protocol": "$server_protocol", '
    '"status": $status, '
    '"bytes_sent": $bytes_sent, '
    '"http_referrer": "$http_referer", '
    '"http_user_agent": "$http_user_agent",'
    '"request_time": $request_time, '
    '"upstream_response_time": $upstream_response_time, '
    '"upstream_connect_time": "$upstream_connect_time", '
    '"request_uri": "$request_uri", '
    '"request_method": "$request_method"}';
  
  host: __NAMESPACE__.xxx.org
  server-snippets: |
    location /privacy {
      proxy_pass http://xxx;
    }
  tls:
    secret: wildcard-xxx-org-ssl-certs
    redirect:
      enable: true
      basedOn: scheme

  upstreams:
  - name: web
    service: web
    port: 80

  - name: mobile-web
    service: mobile-web
    port: 80

  - name: auth
    service: auth
    next-upstream: "error timeout non_idempotent http_503 http_502"
    next-upstream-timeout: 10s
    next-upstream-tries: 10
    port: 80   
  
  - name: es
    service: es
    next-upstream: "error timeout non_idempotent http_503 http_502"
    next-upstream-timeout: 10s
    next-upstream-tries: 10
    port: 80 

  - name: assessment
    service: assessment
    next-upstream: "error timeout non_idempotent http_503 http_502"
    next-upstream-timeout: 10s
    next-upstream-tries: 10
    port: 80   

  - name: upload
    service: upload
    next-upstream: "error timeout non_idempotent http_503 http_502"
    next-upstream-timeout: 10s
    next-upstream-tries: 10
    port: 80 

  - name: object-porting
    service: object-porting
    next-upstream: "error timeout non_idempotent http_503 http_502"
    next-upstream-timeout: 10s
    next-upstream-tries: 10
    port: 80       

  - name: bulkupload
    service: bulkupload
    next-upstream: "error timeout non_idempotent http_503 http_502"
    next-upstream-timeout: 10s
    next-upstream-tries: 10
    port: 80

  - name: henkel-api
    service: henkel-api
    next-upstream: "error timeout non_idempotent http_503 http_502"
    next-upstream-timeout: 10s
    next-upstream-tries: 10
    port: 80        
      

  routes:
  - path: /
    location-snippets: |
      proxy_cache __NAMESPACE__;
      proxy_cache_valid 200 302 304 5m;
    matches:
    - conditions:
      - header: User-Agent
        value: ~* android|ip(ad|hone|od)|nexus|bada|blackberry|phone|mobile|psp
      action:
        pass: mobile-web
    action:
      pass: web

  - path: /api
    location-snippets: |
      include extra-conf/cors.conf;
      access_log /dev/stdout __NAMESPACE__json;
      access_log syslog:server=graylog-output.__NAMESPACE__:33333 __NAMESPACE__json;
    route: vsr-__NAMESPACE__-api-routes

  - path: /api/auth/
    location-snippets: |
      include extra-conf/cors.conf;
      access_log /dev/stdout __NAMESPACE__json;
      access_log syslog:server=graylog-output.__NAMESPACE__:33333 __NAMESPACE__json;
    action:
      proxy:
        upstream: auth
        rewritePath: /

  - path: /api/search/
    location-snippets: |
      include extra-conf/cors.conf;
      access_log /dev/stdout __NAMESPACE__json;
      access_log syslog:server=graylog-output.__NAMESPACE__:33333 __NAMESPACE__json;
    action:
      proxy:
        upstream: es
        rewritePath: /   
          
  - path: /api/resources/uploadResource
    location-snippets: |
      include extra-conf/cors.conf;
      access_log /dev/stdout __NAMESPACE__json;
      access_log syslog:server=graylog-output.__NAMESPACE__:33333 __NAMESPACE__json;
    action:
      proxy:
        upstream: upload
        rewritePath: /  

  - path: /api/assessment/
    location-snippets: |
      include extra-conf/cors.conf;
      access_log /dev/stdout __NAMESPACE__json;
      access_log syslog:server=graylog-output.__NAMESPACE__:33333 __NAMESPACE__json;
    action:
      proxy:
        upstream: assessment
        rewritePath: /     

  - path: /api/app/
    location-snippets: |
      include extra-conf/cors.conf;
      access_log /dev/stdout __NAMESPACE__json;
      access_log syslog:server=graylog-output.__NAMESPACE__:33333 __NAMESPACE__json;
    action:
      proxy:
        upstream: henkel-api
        rewritePath: / 

  - path: /api/upload/
    location-snippets: |
      include extra-conf/cors.conf;
      access_log /dev/stdout __NAMESPACE__json;
      access_log syslog:server=graylog-output.__NAMESPACE__:33333 __NAMESPACE__json;
    action:
      proxy:
        upstream: bulkupload
        rewritePath: / 

  - path: /api/porting/
    location-snippets: |
      include extra-conf/cors.conf;
      access_log /dev/stdout __NAMESPACE__json;
      access_log syslog:server=graylog-output.__NAMESPACE__:33333 __NAMESPACE__json;
    action:
      proxy:
        upstream: object-porting
        rewritePath: /              

  - path: /api/userlogs/userStatus/
    location-snippets: |
      access_log /dev/stdout __NAMESPACE__json;
      access_log syslog:server=graylog-output.__NAMESPACE__:33333 __NAMESPACE__json;
    action:
      return:
        code: 200
        type: text/plain
        body: "1"  

---
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: vsr-__NAMESPACE__-api-routes
  namespace: __NAMESPACE__
spec:
  host: __NAMESPACE__.xxx.org
  upstreams:
  - name: api
    service: api
    next-upstream: "error timeout non_idempotent http_503 http_502"
    next-upstream-timeout: 10s
    next-upstream-tries: 10    
    port: 80
  
  subroutes:
  - path: /api
    action: 
      proxy:
        upstream: api
        rewritePath: /api

**Comment by harshsharma22** [comment]
@lucacome  my virtual server configuration
```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: vs-__NAMESPACE__
  namespace: __NAMESPACE__
  
spec:
  log format ...
  host: __NAMESPACE__.xxx.org
  server-snippets: |
    location /privacy {
      proxy_pass http://xxx;
    }
  tls:
    secret: wildcard-xxx-org-ssl-certs
    redirect:
      enable: true
      basedOn: scheme

  upstreams:
  - name: dummy
    service: dummy
    port: 80

  - name: dummy2
    service: dummy2
    next-upstream: "error timeout non_idempotent http_503 http_502"
    next-upstream-timeout: 10s
    next-upstream-tries: 10
    port: 80   
  
  - name: dummy3
    service: dummy3
    next-upstream: "error timeout non_idempotent http_503 http_502"
    next-upstream-timeout: 10s
    next-upstream-tries: 10
    port: 80 

  routes:
  - path: /
    location-snippets: |
      proxy_cache __NAMESPACE__;
      proxy_cache_valid 200 302 304 5m;
    matches:
    - conditions:
      - header: User-Agent
        value: ~* android|ip(ad|hone|od)|nexus|bada|blackberry|phone|mobile|psp
      action:
        pass: mobile-dummy
    action:
      pass: dummy

  - path: /api
    location-snippets: |
      include extra-conf/cors.conf;
      access_log /dev/stdout __NAMESPACE__json;
      access_log syslog:server=graylog-output.__NAMESPACE__:33333 __NAMESPACE__json;
    route: vsr-__NAMESPACE__-api-routes

  - path: /api/dummy2/
    location-snippets: |
      include extra-conf/cors.conf;
      access_log /dev/stdout __NAMESPACE__json;
      access_log syslog:server=graylog-output.__NAMESPACE__:33333 __NAMESPACE__json;
    action:
      proxy:
        upstream: dummy2
        rewritePath: /

  - path: /api/search/
    location-snippets: |
      include extra-conf/cors.conf;
      access_log /dev/stdout __NAMESPACE__json;
      access_log syslog:server=graylog-output.__NAMESPACE__:33333 __NAMESPACE__json;
    action:
      proxy:
        upstream: dummy3
        rewritePath: /   

---
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: vsr-__NAMESPACE__-api-routes
  namespace: __NAMESPACE__
spec:
  host: __NAMESPACE__.xxx.org
  upstreams:
  - name: api
    service: api
    next-upstream: "error timeout non_idempotent http_503 http_502"
    next-upstream-timeout: 10s
    next-upstream-tries: 10    
    port: 80
  
  subroutes:
  - path: /api
    action: 
      proxy:
        upstream: api
        rewritePath: /api
```

**Comment by harshsharma22** [comment]
@lucacome no route to host also occur in case of downscale

**Comment by Sandeepsinghsamant** [comment]
Even i have faced similar issue
