### ISSUE TITLE
ConfigMap parameter not taken into account while deploying with helm

### ISSUE THREAD

**Issue by sebastienle14** [nginxinc/kubernetes-ingress#1152]
**Describe the bug**
while installing or upgrading nginx-ingress:latest with `helm upgrade --install`, the deployment doesnt take into account any of the following: 
1. the parameter `--set controller.config.enable-underscores-in-headers='"true"'` placed with the  `helm upgrade --install` command
2. the config params within a file called with the command ` helm upgrade --install nginx-ingress nginx-stable/nginx-ingress  -f nginx-ingress/values.yaml` : 
```
controller:
  config:
    enable-underscores-in-headers: "true"
```

**To Reproduce**
1. Deploy the latest version to a kubernetes cluster using either one of the two methods explained above
2. Send a request using a header with underscores to this deployment (using httpheader microservice to catch it, for instance)
3. See error

OR 

1. Deploy the latest version to a kubernetes cluster using either one of the two methods explained above
2. connect to the instance terminal
3. check the absence of  `underscores_in_headers on;` in the generated nginx configuration files

**Expected behavior**
1. the presence of  `underscores_in_headers on;` in the generated nginx configuration files
2. well-formed queries to any services provided by nginx-ingress with correct headers

**Your environment**
* Version of the Ingress Controller : nginx/nginx-ingress:1.8.1 - release version or a specific commit : latest
* Version of Kubernetes : 1.18.2
* Kubernetes platform : Azure
* Using NGINX

**Additional context**
none I could think of, so far.

**Comment by Dean-Coakley** [comment]
Hi @sebastienle14 

`enable-underscores-in-headers` is a configmap entry which is only supported in the [kubernetes community ingress controller](https://github.com/kubernetes/ingress-nginx) which is a different implementation of an ingress controller. 

If you want to use that annotation you'll have to install using their helm chart instead: https://github.com/kubernetes/ingress-nginx/blob/master/docs/deploy/index.md#using-helm

* List of kubernetes community supported configmap entries: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
* List of nginxinc supported configmap entries: https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#summary-of-configmap-keys

**Comment by sebastienle14** [comment]
Thank you!

We changed the image to the one you were advising and it's working perfectly.

Thank you for quick feedback and answer!

Best Regards,
