### ISSUE TITLE
Outgoing traffic stuck with DSR config

### ISSUE THREAD

**Issue by mguggi** [nginxinc/kubernetes-ingress#1156]
**Describe the bug**
I want to balance an incoming UDP (syslog) traffic to different k8s pods in our environment. For this task I want to use the functionality of Nginx (udp load balancing). I used the article [DSR configuration](https://www.nginx.com/blog/ip-transparency-direct-server-return-nginx-plus-transparent-proxy/) as template for my configuration.

As expected Nginx replaces the remote IP with the own IP, so I decided to move to a Direct Server Return (DSR) configuration with binding the remote address. 

When I add the  following line to my stream snippet the incoming traffic works as expected but the outgoing traffic stuck. 

`proxy_bind $remote_addr transparent;`

In the log of Nginx I can see the traffic: 
`10.0.0.152 [24/Sep/2020:05:57:23 +0000] UDP 200 0 57 0.000 "-"`

**To Reproduce**
1. Deploy the kubernetes-ingress with the helm chart. For configuring Nginx I overwrite the following value in the values.yaml file.

```
## The entries of the ConfigMap for customizing NGINX configuration.
    entries:
      stream-snippets: |
        upstream syslog-udp {
          server telegraf-udp.syslog.svc.cluster.local:6514;
        }

        server {
          listen 9998 udp;
          proxy_responses 0;
          proxy_bind $remote_addr transparent;
          proxy_pass syslog-udp;
        }
```

2. Send a sylog request to Nginx

`logger -n 10.0.0.10 -P 9998 -d "#1 syslog test request ... "`

3. I see only that the traffic is received  but no errors. When I remove the proxy_bind directive Nginx sends the traffic to telegraf as expected.

**Expected behavior**
The upstream server(s)  should receive the traffic with the "real" client IP. 

**Your environment**
* Ingress Controller: _1.8.1_
* Version of Kubernetes _1.18.2_
* Kubernetes on: _Bare-Metal (kubeadm)_
* Using _NGINX_ 

**Additional context**
The OS of the worker Nodes is RHEL 7.6 (3.10.0-957.5.1.el7.x86_64)

**Comment by Dean-Coakley** [comment]
Hi @mguggi 

Are you still experiencing this issue?
