### ISSUE TITLE
Sticky session does not work with mergeable-ingress

### ISSUE THREAD

**Issue by vincenzoSantonastasoGithub** [nginxinc/kubernetes-ingress#1164]
I had an application exposed outside with an ingress.
In this ingress, I had configured the sticky session with the following annotations

`    

    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: route
`

I then introduced the mergeable ingress, adding a master over the existing ingress which became the minion.
Everything works correctly except the sticky session no longer works (no session cookies are managed by the application anymore). The configuration on the minion ingress has remained the same. I also tried to move the configuration to the master input but the sticky session still doesn't work

Below the master ingress definition:

![image](https://user-images.githubusercontent.com/43041177/94460424-00dd1b00-01b9-11eb-83ff-a1405b94d459.png)

and the minion ingress definition:
![image](https://user-images.githubusercontent.com/43041177/94460818-91b3f680-01b9-11eb-9b34-41e40e628caa.png)

**Expected behavior**
The sticky session configurated on the minion ingress should work.

**Environment**
* Version of the Ingress Controller :  0.25.1
* Version of Kubernetes : v1.14.6
* Kubernetes platform : Rancher
* Using NGINXs

**Comment by Dean-Coakley** [comment]
Hi @vincenzoSantonastasoGithub 

> Version of the Ingress Controller : 0.25.1

You are using the Kubernetes Community Ingress controller: https://github.com/kubernetes/ingress-nginx
That is a different implementation of an ingress controller which supports a different set of annotations.

The following are all annotations only supported in the Kubernetes Community Ingress Controller:
```
nginx.ingress.kubernetes.io/affinity: cookie
nginx.ingress.kubernetes.io/proxy-body-size: 100m
nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
nginx.ingress.kubernetes.io/session-cookie-hash: sha1
nginx.ingress.kubernetes.io/session-cookie-name: route
```


But `nginxinc.org/mergeable-ingress-type` is an annotation of the nginxinc ingress controller.


Nginxinc docs: https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/
Kubernetes community docs: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/
