### ISSUE TITLE
k8s v1.19.3 crushed 

### ISSUE THREAD

**Issue by sirzak** [nginxinc/kubernetes-ingress#1193]
k8s last version 
bare metal
installed by kubeadm
cni - calico

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

last version `commit 095869944842fe0cc3d9fcc16bddb0b801e30c7e (HEAD -> master, origin/master, origin/HEAD)`
nginx run as daemon-set 
minor changes in common/nginx-config.yaml
Container crush

```
I1015 23:07:47.318273       1 main.go:245] Starting NGINX Ingress controller Version=edge GitCommit=0958699
W1015 23:07:47.325743       1 main.go:284] The '-use-ingress-class-only' flag will be deprecated and has no effect on versions of kubernetes >= 1.18.0. Processing ONLY resources that have the 'ingressClassName' field in Ingress equal to the class.
F1015 23:07:47.327284       1 main.go:288] Error when getting IngressClass nginx: ingressclasses.networking.k8s.io "nginx" not found
```

**Comment by Dean-Coakley** [comment]
Hi @sirzak 

Firstly, note that `edge` is recommended for experimentation with new features and is not recommended for production environments. 
You can see docs for installing the latest stable version instead here: https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/


If you want to continue with `edge`. See [here](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs-web/installation/installation-with-manifests.md#2-create-common-resources) that the ingress class resource must be created as a prerequisite to the ingress controller deployment.

**Comment by sirzak** [comment]
Thx a lot.

**Comment by rayfoss** [comment]
Same issue came back today

**Comment by pleshakov** [comment]
is the issue an error about the IngressClass resource? Note that for k8s >= 1.18, the IC requires creating an IngressClass resource, as described here https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/#create-common-resources
