### ISSUE TITLE
wrong documentation examples

### ISSUE THREAD

**Issue by SergeyMuha** [nginxinc/kubernetes-ingress#1204]
Hello guys,
Can you check please your examples config files for minios and master ingresses from https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/mergeable-ingress-types page
all examples contain 
"kubernetes.io/ingress.class: "nginx""  annotation but should be "nginx.org/ingress.class: nginx"

**Comment by pleshakov** [comment]
Hi @SergeyMuha 

The config looks ok.  The annotation is `kubernetes.io/ingress.class` as described here https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/#ingress-controller-not-related-to-nginx-configuration

**Comment by SergeyMuha** [comment]
I did try with kubernetes.io/ingress.class and it doesn't work.  nginx config error about adding minion ingress object

**Comment by pleshakov** [comment]
@SergeyMuha Could you possible share that error?
