### ISSUE TITLE
502 Bad Gateway while using Dex and Gangway for Kubernetes Authentication

### ISSUE THREAD

**Issue by jashamra** [nginxinc/kubernetes-ingress#1207]
**Describe the bug**
I am trying to use Dex and Gangway for using active directory authentication for Kubernetes based on https://github.com/alexbrand/gangway-dex-tutorial this guide and receiving error in the final step.  I get the same error even while defining the user IDs statically instead of using ldap authentication. Authentication is always successful but not able to get to the last step in the process.
I tried to use Daemonset as well and got the same error.

**To Reproduce**
1. Deploy Dex and Gangway.
2. Navigate to the gangway URL and click on "Sign in" you will redirected to the Dex URL.
3. Login using your AD user ID and password
3. After login click the “Grant Access” button and you will receive 502 Bad Gateway address instead of redirecting back to the gangway callback URL. 

**Expected behavior**
After login click the “Grant Access” button and you should get redirected back to gangway.

**Your environment**
* Version of the Ingress Controller -1.9.0
* Version of Kubernetes - 1.19.3
* Kubernetes on-premise bare metal installation
* Using NGINX

**Additional context**
Nginx controller errors
2020/10/24 12:26:01 [error] 147#147: *72 upstream prematurely closed connection while reading response header from upstream, client: 10.244.0.1, server: gangway.domain.local, request: "GET /callback?code=lb7qrqqlj2mcpdd2pennzv332&state=gYVaGx1J1JVchIYhYyUlP%2Bxzjdep4ov5IRGcFg8HAkQ%3D HTTP/1.1", upstream: "http://10.244.0.236:8080/callback?code=lb7qrqqlj2mcpdd2pennzv332&state=gYVaGx1J1JVchIYhYyUlP%2Bxzjdep4ov5IRGcFg8HAkQ%3D", host: "gangway.domain.local:30877", referrer: "https://dex.domain.local:30877/dex/approval?req=nxm35jomjrc3clwmvt7xkja3i"

10.244.0.1 - - [24/Oct/2020:12:26:01 +0000] "GET /callback?code=lb7qrqqlj2mcpdd2pennzv332&state=gYVaGx1J1JVchIYhYyUlP%2Bxzjdep4ov5IRGcFg8HAkQ%3D HTTP/1.1" 502 157 "https://dex.domain.local:30877/dex/approval?req=nxm35jomjrc3clwmvt7xkja3i" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0" "-"

**Comment by Dean-Coakley** [comment]
@jashamra Sorry you haven't received a response to this issue. We don't have expertise in Dex or Gangway.

Are you still experiencing this issue?
