### ISSUE TITLE
Outdated DockerfileWithAppProtectForPlus

### ISSUE THREAD

**Issue by mcheo** [nginxinc/kubernetes-ingress#1214]
**Describe the bug**
Fail to complete make because of the following error

      62.09 E: Version '2020.09.03-1~stretch' for 'app-protect-attack-signatures' was not found

Most of the variables are outdated as well, for example:
APPPROTECT_MODULE_VERSION should be 22+3.216.0-1~stretch

It will be great if NGINX official documents shows where user can check release number and update the dockerfile content accordingly.

**To Reproduce**
Execute make DOCKERFILE=appprotect/DockerfileWithAppProtectForPlus PREFIX=myprivateregistry/nginx-plus-ingress

**Comment by thresheek** [comment]
Thanks for bringing this to our attention @mcheo.

While your request to update the documentation to check the release numbers is correct, it also highlights the issue with app-protect-attack-signatures repositories - they seem to contain metadata references only to the latest available version.  We're going to fix that soon - I'll get back here to confirm once it's done.

Regarding the docs, I'll let my other colleagues comment.

**Comment by thresheek** [comment]
@mcheo can you please check if Dockerfile is buildable on your side - the repositories should be now fixed.  Thanks!

**Comment by mcheo** [comment]
Thanks. It is working now. I have changed it to use lastest App Protect modules:

ENV APPPROTECT_MODULE_VERSION 22+3.216.0-1~stretch
ENV APPPROTECT_PLUGIN_VERSION 3.216.0-1~stretch
ENV APPPROTECT_ENGINE_VERSION 4.40.0-1~stretch
ENV APPPROTECT_COMPILER_VERSION 4.40.0-1~stretch
ENV APPPROTECT_SIG_VERSION 2020.09.03-1~stretch
ENV APPPROTECT_THREAT_CAMPAIGNS_VERSION 2020.09.01-1~stretch
ENV NGINX_PLUS_VERSION 22-1~stretch
ENV NGINX_PLUS_RELEASE R22

**Comment by pleshakov** [comment]
@mcheo 
It makes sense to add those docs, thanks  Let's keep this issue open until we add them.

**Comment by daniesch** [comment]
@pleshakov Hey Michael, hope you doing great, would you be able to update the Docu. Some of our Customers complained and reached out to us. Cheer Daniel
