### ISSUE TITLE
"complete-example" returns "Connection refused" on HTTPS curl request

### ISSUE THREAD

**Issue by dakshinai** [nginxinc/kubernetes-ingress#1245]
**Describe the bug**
Followed the steps as is to create NGINX ingress controller (minus App Protect/Custom resources) with NodePort and cafe complete example
https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/
https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/complete-example

Unable to access with curl against node IP and Node Port https port. Output leads to connection timeout.
Also tried daemonset deployment with no avail. Set cafe.example.com to node IP in DNS for ease of use but it did not help. 

**Your environment**
* Version of the Ingress Controller - v1.9.0
* Version of Kubernetes- v1.19.3
* Kubernetes platform (e.g. Mini-kube or GCP) - baremetal + docker
* Using NGINX or NGINX Plus - NGINX

**Comment by Dean-Coakley** [comment]
Hi @dakshinai 

With the provided details about your cluster, I would guess that you need to uncomment the `IngressClassName` of your Ingress resource. 

See https://github.com/nginxinc/kubernetes-ingress/blob/master/examples/complete-example/cafe-ingress.yaml#L6

Can you take a look at that and let me know if you're still experiencing issues?

**Comment by dakshinai** [comment]
Hi Dean, Uncommenting IngressClassName did not help. For the time being, we are testing the setup on a single node - controller + worker. NodePort setup works in this case.

I shall reopen this when there is a need to have a separate node for the controller and worker. Please help suggest if anything.
