### ISSUE TITLE
Ingress Controller returns 404 error

### ISSUE THREAD

**Issue by ramabommi** [nginxinc/kubernetes-ingress#1274]
**Describe the bug**
We tried configuring Nginx controller with version 1.9.1 as mentioned in the docs (install with helm charts):
https://github.com/nginxinc/kubernetes-ingress/tree/v1.9.1/deployments/helm-chart
We're getting 404 Not found.

**To Reproduce**
1. Follow installation steps from https://github.com/nginxinc/kubernetes-ingress/tree/v1.9.1/deployments/helm-chart for the above specified versions.
2. while deploying if annotation " kubernetes.io/ingress.class: nginx" is not mentioned in the services/ingress configuration.
3. Seeing  error 404.

**Expected behavior**
Requests are not routing from Nginx  ingress controller to applications/services.

**Your environment**
* Version of the Ingress Controller - v1.9.1
* Version of Kubernetes: v1.18.4
* Kubernetes platform: Azure cloud(AKS)
* Using NGINX Plus

**Additional context**
we cannot use nginx as default ingress class, as 3rd party charts that won't directly expose an ingress class property and we have to use the legacy ingress class annotation.

**Comment by pleshakov** [comment]
Hi @ramabommi 

With annotation `kubernetes.io/ingress.class: nginx` in the Ingress, it should have worked. Could you possibly confirm that the config for the Ingress was generated https://docs.nginx.com/nginx-ingress-controller/troubleshooting/#checking-the-generated-config ? Also, could you confirm that you don't see any errors in the events of the Ingress https://docs.nginx.com/nginx-ingress-controller/troubleshooting/#checking-the-events-of-an-ingress-resource ?

**Comment by ramabommi** [comment]
Hello @pleshakov  

we don't have any issue while using ingress class annotation, but issue seems to be when using  setDefaultIngress property. i don't see any errors in the events of ingress.

**Comment by pleshakov** [comment]
Hi @ramabommi 

I am still a bit confused about the issue. Could you possibly share an example of a problematic Ingress resource?

**Comment by anthonyvk** [comment]
Even I am facing the same issue. The conf gets generated, but getting 404

**Comment by pleshakov** [comment]
@anthonyvk 
If the config gets generated, could you double check that it was applied? If it was applied successfully, you should see an event generated for an Ingress resource, like this one: `Normal  AddedOrUpdated  12s   nginx-ingress-controller  Configuration for default/cafe-ingress was added or updated`  

How do you send requests that generate command? Curl? Browser?

Also, I recommend extending the IC logs to double check that it is not the backend that returns 404 -- https://github.com/nginxinc/kubernetes-ingress/issues/1331#issuecomment-772903153

**Comment by anthonyvk** [comment]
Hi @pleshakov, thanks for responding.

I am deploying the IC and examples on the Docker Desktop.
I am following the instructions mentioned here : https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/
And deploying the examples from this repository : https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/complete-example

```
NAME            TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
nginx-ingress   NodePort   X.X.X.X   <none>        80:32147/TCP,443:32600/TCP   7s
```

When I open the URL in **http://localhost:32147/coffee** in browser I get 404 from Nginx.

Logs : 

```
2021/03/04 06:34:38 [notice] 13#13: signal 29 (SIGIO) received                                                                                                            
192.168.65.3 - - [04/Mar/2021:06:38:35 +0000] "GET / HTTP/1.1" 404 153 "-" "Mozilla/5.0 (Windows NT; Windows NT 10.0; en-IN) WindowsPowerShell/5.1.18362.1171" "-"        
192.168.65.3 - - [04/Mar/2021:06:39:36 +0000] "GET /coffee HTTP/1.1" 404 153 "-" "Mozilla/5.0 (Windows NT; Windows NT 10.0; en-IN) WindowsPowerShell/5.1.18362.1171" "-"  
W0304 06:40:05.278829       1 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress          
W0304 06:46:53.279529       1 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress          
W0304 06:46:54.518817       1 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress          
W0304 06:46:54.521243       1 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress          
192.168.65.3 - - [04/Mar/2021:06:47:37 +0000] "GET /coffee HTTP/1.1" 404 153 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0" "-"     
192.168.65.3 - - [04/Mar/2021:06:47:37 +0000] "GET /favicon.ico HTTP/1.1" 404 153 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0" "-"
W0304 06:53:17.521196       1 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

**Comment by pleshakov** [comment]
@anthonyvk 

http://localhost:32147/coffee  doesn't set the host header to `cafe.example.com`, which NGINX expects. I suggest you run:
```
curl --resolve cafe.example.com:$IC_HTTPS_PORT:$IC_IP https://cafe.example.com:$IC_HTTPS_PORT/coffee --insecure
```
as described in the example https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/complete-example#4-test-the-application  
that command will set the host header

**Comment by massih10** [comment]
I'm facing the exact same problem.

**Comment by massih10** [comment]
solved it via:
kubectl expose deployment coffee --port 80

is there a way to display existing expose statements?

**Comment by danilorsilva** [comment]
same problem here

**Comment by rahbal** [comment]
try the url without "https"

**Comment by rensmanders** [comment]
I resolved it by giving the following annotation to the ingress resource: nginx.ingress.kubernetes.io/rewrite-target: /

Solution by: https://stackoverflow.com/questions/52021925/kubernetes-ingress-non-root-path-404-not-found

**Comment by brianehlert** [comment]
The OP did not respond therefore due to age, I am closing this.
if the rest of you are still having problems, please open issues.

Be aware that NGINX can return a 404 if the target systems (upstreams / backends) are not healthy and therefore none are available.  Also if a path does not match.
