### ISSUE TITLE
Nginx Ingress hostPort

### ISSUE THREAD

**Issue by stefanmb** [nginxinc/kubernetes-ingress#129]
In the example [nginx-ingress.yaml](https://github.com/nginxinc/kubernetes-ingress/blob/master/examples/daemon-set/nginx-ingress.yaml) the `hostPort` is hardcoded:

```
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
```

This means that you cannot run any other containers that require 80/443 on the same k8s nodes, which is problematic if you only want some pods to be terminated by the L7 nginx ingress and others by an L4 load balancer. 

Is there any particular reason the examples suggest hardcoding the `hostPort`?

**Comment by pleshakov** [comment]
> This means that you cannot run any other containers that require 80/443 on the same k8s nodes, which is problematic if you only want some pods to be terminated by the L7 nginx ingress and others by an L4 load balancer.

Not sure If I understand the problem. You can run the conflicting containers on different nodes, or use a different port mappings scheme. What are you trying to achieve? 

> Is there any particular reason the examples suggest hardcoding the hostPort?

In general, it works well.

**Comment by stefanmb** [comment]
Thank you for the quick reply!

> What are you trying to achieve?

I have a large cluster shared between many containers/apps. I run `nginx` using the daemon set example config. Most apps are fine with the `nginx` ingress but some need to do their own TLS termination, so I used a L4 load balancer for them.

When `hostPort` is present that means `iptables` rules like this are inserted by `kube-proxy`:

```
-A KUBE-HOSTPORTS -p tcp -m comment --comment "nginxinc-ingress-6tx83_default hostport 443" -m tcp --dport 443 -j KUBE-HP-KJSQAKEFZWSDUP2Z
```

This means *all* 443 traffic is always forced to `nginx`. Removing `hostPort` resolves this issue and doesn't break any functionality. (This is apparently relatively [recent behaviour](https://github.com/kubernetes/kubernetes/issues/41681).)

The [guidelines](https://kubernetes.io/docs/concepts/configuration/overview/) indicate:

> Don’t use hostPort (which specifies the port number to expose on the host) unless absolutely necessary, e.g., for a node daemon. When you bind a Pod to a hostPort, there are a limited number of places that pod can be scheduled, due to port conflicts

I opened this issue to make sure there were no other special considerations about `hostPort` that I did not take into account. So far I do not see any reason to use `hostPort`.

**Comment by pleshakov** [comment]
Thanks for the details and pointing out the issue. This behavior was not anticipated by our examples.

The daemon set example with hostPorts is targeted for on-prem deployments that don't have a cloud load balancer. 

For cloud environments, it is better to deploy NGINX as a replication controller/deployment, create a Service for NGINX and then expose it as Type LoadBalancer to allocate a cloud TCP/UDP load balancer, without setting any hostPorts. We might need to update the docs/examples to point that out.

**Comment by Winbobob** [comment]
> For cloud environments, it is better to deploy NGINX as a replication controller/deployment, create a Service for NGINX and then expose it as Type LoadBalancer

Hi @pleshakov,  I am a little bit confused. You mentioned that it is better to create a NGINX service (than using NGINX ingress controller)? But it seems that using NGINX ingress controller has many benefits that using NGINX service, like L7 load balance, removing single point of failure, etc.

Please correct me if I am wrong!

**Comment by pleshakov** [comment]
@Winbobob 
I think there is a confusion in what the NGINX service is. In this case the NGINX service is a Kubernetes Services which is used to expose NGINX Ingress controller pods through the Cloud load balancer -- https://kubernetes.io/docs/concepts/services-networking/service/#type-loadbalancer Thus, all the benefits of the Ingress controller are still present.

**Comment by jachicao** [comment]
@pleshakov 
he meant this: https://gist.github.com/jachicao/fd713c3f6048c0e9a0ada551a3803f12

**Comment by isaachawley** [comment]
Here's the preferred way to expose the Ingress Controller: https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/installation.md#4-get-access-to-the-ingress-controller
