### ISSUE TITLE
Custom 404 if subdomain does not match

### ISSUE THREAD

**Issue by 030** [nginxinc/kubernetes-ingress#1295]
**Is your feature request related to a problem? Please describe.**

There is a wildcard DNS entry, i.e. boo.some-domain and foo.some-domain point to the same IP address. The host in the ingress routes the traffic to the correct service. When the subdomain is neither boo, nor foo, a default 404 nginx page is returned.

**Describe the solution you'd like**

An annotation that can be added to the ingress-controller and that overrides the custom 404 page by a html page that one could create themselves.

**Describe alternatives you've considered**

#752, but in this case, there are two subdomains instead of two URIs, e.g. `/tea`. `/coffee`

**Additional context**

**Comment by 030** [comment]
Thank you for merging the PR. Could you indicate whether it will be part of the 1.10 release?

**Comment by 030** [comment]
Related PR: https://github.com/nginxinc/kubernetes-ingress/pull/1297

**Comment by pleshakov** [comment]
Hi @030 

Unfortunately, we can't include it in the 1.10 (which is released this week), because of our code freeze.

however, it will be included in 1.11 release, targeted for late March

**Comment by 030** [comment]
@pleshakov Would it not be possible to release it earlier? We have a production that is running on the edge version right now. I was assuming that it would be merged into the 1.10.0.

**Comment by pleshakov** [comment]
@030 
I can suggest a temporal workaround with a custom template. Please see https://github.com/nginxinc/kubernetes-ingress/tree/v1.10.0/examples/custom-templates

The idea is to put the whole template in `main-template` confgimap key. The `return 404` of the default server can be changed according to your requirements.

Note that for minor releases (1.10.x) custom template doesn't change, as we don't introduce any new features. So it will be safe for upgrades.

**Comment by ogarrett** [comment]
closing - implemented in PR: #1297
