### ISSUE TITLE
ConfigMap proxy-hide-headers config only add directive to Ingresses

### ISSUE THREAD

**Issue by benjamin-bergia** [nginxinc/kubernetes-ingress#1298]
**Describe the bug**
When adding the `proxy-hide-headers` key to the ingress controller configmap, the `proxy_hide_header` statement is added to the config files generated by all the Ingresses but not to the config files generated by VirtualServers

**To Reproduce**

1. Add `proxy-hide-headers: example` to the `nginx-config` configmap
2. Create bunch of Ingresses and VSs
3. Open a shell on one of the nginx pods and `grep -R proxy_hide_header /etc/nginx/`
4. Check if the directive is found in any of the `vs_*` 

**Expected behavior**
I would expect the directive to be added to all the config including the VSs

**Your environment**
* Version of the Ingress Controller : nginx/nginx-ingress:1.7.2
* Version of Kubernetes: 1.15
* Kubernetes platform: Openstack magnum
* Using NGINX

**Comment by benjamin-bergia** [comment]
I updated my ingress controller to v1.9.1 and it doesn't seem to solve the issue.

**Comment by pleshakov** [comment]
Hi @benjamin-bergia 

Could you try to use `responseHeaders` in https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#action-proxy ? There is no support for ConfigMap proxy hide headers in VS. The other limitations are mentioned here https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#customization-via-configmap

**Comment by benjamin-bergia** [comment]
Hi @pleshakov,
I didn't notice this part of the doc, sorry.
I would like to drop a specific header from all the responses, is there an equivalent to `responseHeaders` that would apply to the whole VS? I have tens of path defined in my VS.

**Comment by pleshakov** [comment]
Hi @benjamin-bergia 

I suggest trying to use the `location-snippets` in the ConfigMap like below:
```yaml
  location-snippets: |
    proxy_hide_header header1;
    proxy_hide_header header2;
```

as a result, those directives will be added to every generated location in VirtualServers and will do the job of hiding the specified headers.

at the same time, I think it makes sense to add support the ConfigMap `proxy-hide-headers` in VirtuaServers as for Ingress resources.

**Comment by benjamin-bergia** [comment]
@pleshakov Thank you.
I tried the snippets and it works perfectly

**Comment by Nishanth-kumar-S** [comment]
I tried the above but i am getting server response header
HTTP/1.1 404 Not Found
Server: nginx
Content-Type: application/json
Content-Length: 22
Connection: keep-alive
