### ISSUE TITLE
How do I allow my virtualserver to cross domains?

### ISSUE THREAD

**Issue by JokerDevops** [nginxinc/kubernetes-ingress#1308]
How do I allow my virtualserver to cross domains?
How to add the following header information to allow cross-domain?

```nginx
    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Methods *;
    add_header Access-Control-Max-Age 3600;
    add_header Access-Control-Allow-Credentials true;
    add_header Access-Control-Allow-Headers $http_access_control_request_headers;
```

**Comment by JokerDevops** [comment]
\question

**Comment by pleshakov** [comment]
Hi @JokerDevops 

This is not supported by VirtualServers directly.

However, there is an extension method to add that config to VirtualServers - snippets. Please see https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#using-snippets

**Comment by ogarrett** [comment]
Closing as a dup of https://github.com/nginxinc/kubernetes-ingress/issues/1414
