### ISSUE TITLE
When a new build will be made?

### ISSUE THREAD

**Issue by sfrique** [nginxinc/kubernetes-ingress#131]
I was trying to configure snippets and it wasn't working, but then i realize the commit is after the latest build.

Thanks.

**Comment by pleshakov** [comment]
@sfrique 
We will release the new version next week. Please follow these intructions if you would like to build your own image -- https://github.com/nginxinc/kubernetes-ingress/tree/master/nginx-controller

**Comment by sfrique** [comment]
Thanks!
I've figure out already!
