### ISSUE TITLE
Publish container images for ARM

### ISSUE THREAD

**Issue by c-x-berger** [nginxinc/kubernetes-ingress#1310]
**Is your feature request related to a problem? Please describe.**
My cluster is ARM-based (read: made of Raspberry Pis), and the [Docker image](https://hub.docker.com/r/nginx/nginx-ingress) is apparently only published for amd64.

As a result, I can't really use this controller. (Yes, I could build the images myself, but I personally don't really have the means for that.)

**Describe the solution you'd like**
ARM images (at the very least, 64-bit ARMv8) published under the various `nginx/nginx-ingress` tags

**Describe alternatives you've considered**
... I could use a different controller, I guess?

**Comment by groundhog2k** [comment]
@c-x-berger : I made the same suggestion with #974  :-(
At the moment the best solution is to use https://github.com/kubernetes/ingress-nginx. It provides all platforms with a multi-arch. docker image and the community is very active to keep the controller and the helm chart (https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx) up-to-date. For me this is working great!

**Comment by lucacome** [comment]
Hi @c-x-berger 

I just wanted to let you know that we now build debian and alpine images for arm and arm64.
