### ISSUE TITLE
Expose TCP service through ingress controller

### ISSUE THREAD

**Issue by raeder1986** [nginxinc/kubernetes-ingress#1311]
Good day! Have your controller an opportunity to expose TCP service like this https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/ ?
Problem is:
I have a couple of db's pods that I need access from internet (not http). But I don't want to create additional IPs for them. So I want to expose these services through ingress-controller's kube-service and it's IP using free port.

**Comment by pleshakov** [comment]
Hi @raeder1986 

There are two options:
- TransportServer -- https://docs.nginx.com/nginx-ingress-controller/configuration/transportserver-resource/
- Snippets -- https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/tcp-udp

**Comment by raeder1986** [comment]
@pleshakov Thanks! I'll investigate this
