### ISSUE TITLE
in nginx-ingress 1.9.1,  leader election is failing to get resource lock

### ISSUE THREAD

**Issue by blackgold** [nginxinc/kubernetes-ingress#1319]
**Describe the bug**
nginx-ingress 1.9.1 is having issues with leader election. Its failing to get resource lock

**To Reproduce**
1. Deploy nginx-ingress version 1.9.1
2. View ingress-cintroller container logs
3. See error
E0122 01:46:46.237366       1 leaderelection.go:320] error retrieving resource lock /nginx-ingress-leader-election: an empty namespace may not be set when a resource name is provided
E0122 01:46:57.163598       1 leaderelection.go:320] error retrieving resource lock /nginx-ingress-leader-election: an empty namespace may not be set when a resource name is provided
E0122 01:47:07.526503       1 leaderelection.go:320] error retrieving resource lock /nginx-ingress-leader-election: an empty namespace may not be set when a resource name is provided
E0122 01:47:19.246890       1 leaderelection.go:320] error retrieving resource lock /nginx-ingress-leader-election: an empty namespace may not be set when a resource name is provided

**Expected behavior**
No errors wrt leader election. 

**Your environment**
* Version of the Ingress Controller - release version or a specific commit
   Version=1.9.1 GitCommit=aa19bb45
* Version of Kubernetes
   Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes platform (e.g. Mini-kube or GCP)
  Baremetal in datacenter
* Using NGINX or NGINX Plus
   NGINX

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by pleshakov** [comment]
Hi @blackgold 

Could you possibly share the manifests that was used to deploy the Ingress Controller?
