### ISSUE TITLE
\n in $TOKEN logging output.

### ISSUE THREAD

**Issue by hardymansen** [nginxinc/kubernetes-ingress#132]
I have got so far as:

kubectl get pods:
`coffee-rc-8jv4h    1/1       Running                                        0          1h`
`coffee-rc-xxgfk    1/1       Running                                        0          1h`
`tea-rc-gjtf6       1/1       Running                                        0          1d`
`tea-rc-kvp5s       1/1       Running                                        0          1d`
`tea-rc-wfttm       1/1       Running                                        0          1d`

kubectl get ingress:
`cafe-ingress   cafe.example.com             80, 443   1h`

I have a node with:
`/var/run/secrets/kubernetes.io/serviceaccount/token`
`/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`

I can see with a rest client that i get a well formed json with.
`https://$API-Server:6443/apis/extensions/v1beta1/ingresses?resourceVersion=0`
that contains the ingress information.

I have the  `ingress.tmpl` & `nginx.conf.tmpl` file in the root directory of the nginx-ingress

But when i run
`export KUBERNETES_SERVICE_HOST=$API-Server;export KUBERNETES_SERVICE_PORT=6443;./nginx-ingress -v 10`

Im not getting any server or location/upstream configuration set in /etc/nginx. I do get the base templating but nothing about the ingress.

The debug message is very vague. The one thing i do see is that the curl output that is shown, contains a `\n` after the token which messes up the authentication. I am not sure if this is just a logging issue, and a red hearing in my debugging or if this is the cause, but feels that would been quite obvious already. ( have checked that the \n is not from my token file )

`round_trippers.go:267] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: nginx-ingress/v0.0.0 (linux/amd64) kubernetes/$Format" -H "Authorization: Bearer $TOKEN\n" https://$API-SERVER:6443/api/v1/services?resourceVersion=0`

**Comment by hardymansen** [comment]
I hacked around a little to pinpoint the issue. commented out local = yes and used the client.*Host to go via http instead of https. Then everything works. 
Also noticed the curl debug output from the client have `curl -k` , that sounds like a bad idea in a production environment. Not sure what is going on there. I rather have a option to do plain http but default to secure https.

**Comment by pleshakov** [comment]
@hardymansen thanks for the investigation and the workaround. I see the same issue. I will try to see how to fix that.

**Comment by hardymansen** [comment]
Are you using a old client and that kubernetes have changed to the client-go upstream? 

I started ripping out the unversioned and replace but got it working with the contrib version. ( so far for my user case ) , so will continue there for now.

**Comment by pleshakov** [comment]
@hardymansen 
Yep, we are currently using the old go client. Glad that you got it working with the contrib version.

**Comment by isaachawley** [comment]
We've updated the client 👍
