### ISSUE TITLE
Architecture/ideas

### ISSUE THREAD

**Issue by hardymansen** [nginxinc/kubernetes-ingress#133]
I have started dabble to use this ingress controller and will continue to think about it. Some things im thinking about

`ngxc.Start()`
Why do we want the controller to start nginx? In my case, i already have nginx running and the responsibility of starting nginx is within a service daemon. I rather just have the controller 
- listen to changes in service registry
- update templates -> nginx configuration
- Handle reloading of nginx

` createDir(ngxc.nginxCertsPath)`
Why have the controller create directories in nginx file structure and fail if the directories already exist. Again, for me it feels this is outside the responsibility of the controller. I would rather just have the controller focus on the above tasks, listen, update, reload. 

And let the user have option to use external configuration management to install nginx, like chef, puppet, ansible. 

Also, would make sense to have the directories configurable for ingress, ssl. So user can send in parameters if want to use as a example only /etc/nginx/sites-enabled instead of /etc/nginx/conf.d
And get all hardcoded values out of the controller and into user.

If controller should handle createdirs and starting/stopping, e.g provisioning. Maybe a --provision flag. 

So point being, that more optional and less hard coded stuff and more modular in these aspects. What do you think?

**Comment by pleshakov** [comment]
@hardymansen 
Creating the certificate directory is certainly out of the scope of the controller.
However, starting/stoping is OK, considering that the primary use-case is running the controller in a container, and this simplifies managing NGINX.

Certainly, configuration directories can be made configurable.
To support running the controller outside of a container, I agree, having a flag makes sense.
