### ISSUE TITLE
apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in Helm Chart

### ISSUE THREAD

**Issue by rgstephens** [nginxinc/kubernetes-ingress#1361]
**Is your feature request related to a problem? Please describe.**
When installing on `1.20.2`, get the following error:

```
W0206 13:14:51.076562   15764 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```

**Describe the solution you'd like**
Create update version of CRD's and add a values.yml option to select CRD version

**Comment by Dean-Coakley** [comment]
Hi @rgstephens 

Thanks for reporting this issue.

> Create update version of CRD's and add a values.yml option to select CRD version
While this solution sounds ideal, I don't believe this is possible as templating is not permitted by the Helm client in the `/crds/` directory.

For the next release of the ingress controller we will be supporting Kubernetes versions 1.16+ so we can make `v1` the default(only option) shortly. Anyone who requires Kubernetes 1.15 can remain on the current release.

**Comment by arczibdg** [comment]
Hi @Dean-Coakley - is there any specific date when the mentioned fix will be released?
Strugling with the same error on 1.19.6

**Comment by Dean-Coakley** [comment]
@arczibdg The fix should be present in `nginx-edge` (https://helm.nginx.com/edge, `master` branch) by next week and `nginx-stable` (https://helm.nginx.com/stable `release-1.11` branch) around ~end of March.
