### ISSUE TITLE
Allow/Deny Hosts

### ISSUE THREAD

**Issue by TANguyen1893** [nginxinc/kubernetes-ingress#138]
Currently from looking at the nginx templates, it does not seem possible to create any entry for deny/allow hosts in the nginx configuration. I have also tried using this kubernetes annotation: 
Annotations:
  whitelist-source-range:	1.1.1.1/24
However that does not have an effect either. I am able to access the services even with that whitelisted ip range. Any workaround to this without having to go into the nginx pod and editing the config file then restarting nginx?

Thanks

**Comment by johnjbateman** [comment]
I'd also like this functionality
