### ISSUE TITLE
Ingress does not show the assigned public ip

### ISSUE THREAD

**Issue by vallemar** [nginxinc/kubernetes-ingress#1380]
**Describe the bug**
Ingress does not show the assigned public ip
![image](https://user-images.githubusercontent.com/15719383/107920452-484c2400-6f6d-11eb-941e-9e8c23e6ac0a.png)

**To Reproduce**
1. install metallb
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/namespace.yaml
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml
nano metallb.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - xx.xxx.xx.xx/32  <- IP PUBLIC 
2. Intall kubernetes-ingress
Install according to this guide: https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/.
3. Create deploy, service and ingress.

**Expected behavior**
When doing kubectl get ingress it should show the public IP.

**Your environment**
Ingress Controller -v1.10.0
Kubernetes: v1.20.2

**Additional context**
It seems that everything works as it should, the resource xx.xxx.com responds correctly but the ip is not showing

![image](https://user-images.githubusercontent.com/15719383/107920772-c3add580-6f6d-11eb-953e-1d677e313bf6.png)

**Comment by pleshakov** [comment]
Hi @vallemar 

Could you make sure the IC args include `-report-ingress-status` and `-external-service=nginx-ingress`? See also https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/reporting-resources-status/#ingress-resources

**Comment by vallemar** [comment]
Hi @pleshakov 

I have applied it in deployment / nginx-ingress.yaml and daemon-set / nginx-plus-ingress.yaml file. The situation remains the same. Everything working but without showing the IP address.

Thanks a lot.

**Comment by pleshakov** [comment]
@vallemar 

If you run `kubectl describe ing`, do you see any events reported? Like here https://docs.nginx.com/nginx-ingress-controller/troubleshooting/#checking-the-events-of-an-ingress-resource 

Do you see any errors in the IC logs?  See https://docs.nginx.com/nginx-ingress-controller/troubleshooting/#checking-the-ingress-controller-logs

**Comment by vallemar** [comment]
I have done what you indicate. When I do` kubectl describe ing` this is the output, it seems to be all good.

![image](https://user-images.githubusercontent.com/15719383/108174984-76ae3880-7100-11eb-862a-b20edd2f0f31.png)


Also I have taken the logs of the 2 pods that I have running, I have saved the output in these[ two files.](https://drive.google.com/drive/folders/1R7Tnyl4l-MDzzYFneKWiB9XoLuMtBASc?usp=sharing)

**Comment by pleshakov** [comment]
@vallemar 
thanks for sharing.

Could you add the `kubernetes.io/ingress.class: "nginx"` annotation to the Ingress resource or set the class field:
```
  apiVersion: networking.k8s.io/v1beta1
  kind: Ingress
  metadata:
    name: cafe-ingress
  spec:
    ingressClassName: nginx
    . . .
```
otherwise, the Ingress Controller will not handle the Ingress resources. Right now the IC doesn't handle the `echo-ingress` Ingress. 

Alternatively, you can make the Ingress Controller the default IngressClass by uncommenting this annotation -- https://github.com/nginxinc/kubernetes-ingress/blob/master/deployments/common/ingress-class.yaml#L5-L6  After that, if you deploy an Ingress without a class, k8s will assign the nginx class to it.

**Comment by vallemar** [comment]
@pleshakov Yes now!

I have added `ingressClassName:nginx` and now it displays correctly. I close the issue but: shouldn't this be a little clearer in the docs? It may be somewhere but I can't find it.

Thanks a lot!
