### ISSUE TITLE
Health Status is not working

### ISSUE THREAD

**Issue by woopstar** [nginxinc/kubernetes-ingress#139]
I have added -health-status to the start command of the ingress controller. But when i log into the pod and check nginx.conf, then health check is not added.

Anyone able to reproduce this?

**Comment by pleshakov** [comment]
@woopstar 
it is a bug, thanks for catching it. It is reproducible when you deploy nginx-config ConfigMap. The ConfigMap wrongly overwrites the -health-status setting.
