### ISSUE TITLE
Excuse me, does ingress support Gated Launch through different namespace？ How to do that

### ISSUE THREAD

**Issue by StretchV** [nginxinc/kubernetes-ingress#1397]

**Comment by pleshakov** [comment]
Hi @StretchV 

could you possibly clarify what you mean by gated launch trough different namespace ?

**Comment by StretchV** [comment]
For example, we have two namespaces, namely, namespace-1 and namespace-2. There is a service named A-service in namespace-1, and a service named A-service in namespace-2 too. Now there are two kinds of requests with different headers. How can we distribute the two requests to the services under different namespaces through a ingress,  thank you

**Comment by jasonwilliams14** [comment]
Hi @StretchV

I believe you are looking for this:
https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/cross-namespace-configuration/

**Comment by StretchV** [comment]
I see 
"Known Limitations
Currently a maximum of one canary ingress can be applied per Ingress rule.“on the official website（https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#canary）. If I have more than two service scenarios, how can I complete the similar diversion? How can I remedy this defect？
