### ISSUE TITLE
nginx ingress does not decrypt traffic to the backend 

### ISSUE THREAD

**Issue by shamndor** [nginxinc/kubernetes-ingress#1399]
Greetings,

I deployed the daemon-set deployment
![image](https://user-images.githubusercontent.com/11654099/108537886-3234bf80-72ef-11eb-9638-a439362d56b5.png)

![image](https://user-images.githubusercontent.com/11654099/108538011-5c867d00-72ef-11eb-9b9e-62cf60d77139.png)

 This is ingress
![image](https://user-images.githubusercontent.com/11654099/108538193-96578380-72ef-11eb-9041-397cf08728e7.png)

The problem is the annotation of backend protocol ,proxy-ssl-secret  and proxy-ssl-verify does not take affect.
by checking log of ingress
![image](https://user-images.githubusercontent.com/11654099/108538721-27c6f580-72f0-11eb-9584-f6c9b4a9c7c7.png)

also by checking backend service logs . backend receive plaintext over https channel.
![image](https://user-images.githubusercontent.com/11654099/108539056-87250580-72f0-11eb-9997-2fcd83f81f86.png)

any one can help me to understand why nginx-ingress does not re encrypt the traffic to backend.

Thanks.

**Comment by pleshakov** [comment]
Hi @shamndor 
 
We don't support the proxy-ssl-* and rewrite-target annotations. Those annotations are of a different project -- https://github.com/kubernetes/ingress-nginx

To learn more about differences -- https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/nginx-ingress-controllers.md 

To use TLS to connect to backends -- https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/ssl-services
To use TLS with cert verification and client secret - https://github.com/nginxinc/kubernetes-ingress/tree/master/examples-of-custom-resources/egress-mtls

**Comment by shamndor** [comment]
@pleshakov 
Thank you very much, working now using  nginx.org/ssl-servic
sorry where I did not notice the difference between the two implementation before.
