### ISSUE TITLE
How to enable cors

### ISSUE THREAD

**Issue by RudyBone** [nginxinc/kubernetes-ingress#1414]
I'm using version 1.8.0.  looking for a clear example of how to enable cors in the ingress.yaml

**Comment by pleshakov** [comment]
Hi @RudyBone 

We don't have built-in support for CORS. However, it is something that could be added via snippets.

I suggest taking a look at this example https://enable-cors.org/server_nginx.html and adding those parts to your Ingress resource via `nginx.org/location-snippets` annotation.  See also https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-snippets/

**Comment by rayfoss** [comment]
```
nginx.org/location-snippets: |
      add_header Access-Control-Allow-Origin "*";
      add_header Access-Control-Allow-Methods GET;
      add_header Access-Control-Expose-Headers "Content-Length,Content-Range";
```
