### ISSUE TITLE
How is the nginx-ingress 'selected'

### ISSUE THREAD

**Issue by stefanberger** [nginxinc/kubernetes-ingress#142]
There's some documentation that I am missing in all the Kubernetes Ingress documentation and that is related to how the nginx-ingress is being 'selected'. Looking at the complete-example I see that coffee-svc 'selects' the coffee-rc via 'selector: coffee'. It works the same for the tea-svc that selects the tea-rc via 'selector: tea'. The cafe-ingress in turn selects the tea-svc and coffee-svc. So I see the chain. Now how is the nginx-ingress selected? I don't see a field in the yaml files , other than in nginx-ingress-rc.yml, that would point to nginx-ingress. What's the magic here that activates this nginx-ingress?

**Comment by pleshakov** [comment]
Hi @stefanberger,

Are you asking why a particular Ingress controller, in our case it is NGINX ingress controller, picks up the cafe-ingress resource?

**Comment by stefanberger** [comment]
@pleshakov Yes.

**Comment by pleshakov** [comment]
[This](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/multiple-ingress-controllers) gives the answer.

**Comment by stefanberger** [comment]
Ok. Now when looking at this file [here](https://github.com/nginxinc/kubernetes-ingress/blob/master/examples/complete-example/nginx-ingress-rc.yaml), what exactly makes this an nginx ingress controller? Is it the name 'nginx-ingress' or 'nging-ingress-rc'  or the image name 'nginxdemos/nginx-ingress:0.8.1'. Which one can I freely choose ? Or is there something inside the image that makes it known as an 'nginx' ingress controller during runtime so that the line 
```
kubernetes.io/ingress.class: "nginx"
```
actually selects that one?

**Comment by pleshakov** [comment]
The controller internally assumes that it is the`nginx` controller and that it must handle all Ingress resources with the ingress.class equal `nginx`. The value `nginx` is set [here](https://github.com/nginxinc/kubernetes-ingress/blob/master/nginx-controller/controller/controller.go#L40).

**Comment by stefanberger** [comment]
Thanks. Closing this issue.
