### ISSUE TITLE
I receive 404 errors if I refresh my browser 

### ISSUE THREAD

**Issue by Shaun-Ladd** [nginxinc/kubernetes-ingress#1422]
The infrastructure is running on EKS v1.14, Nginx Ingress controllver v0.35.0.  

The site functions properly most of the time however if I am on the home page and refresh my page (F5), I will get a "404 Page Not Found".  If I keep refreshing it will return to the home page sometimes and others give the 404 error.  I looked at the Ingress logs and it appears to route the traffic to the default-upstream-backend when giving the 404 error.  I am confused why it would work sometimes and not others.  I assumed if the paths were setup incorrectly, it would not work at all.  Since this is still in development I the replicas set to "1" for all deployments.

**Comment by lucacome** [comment]
Hi @Shaun-Ladd, based on the version you're referring to, I believe you're using the [community Ingress Controller](https://github.com/kubernetes/ingress-nginx). 
If that's the case, I think they can help you over there 🙂 

Let us know if otherwise.
