### ISSUE TITLE
uWSGI support of nginx ingress controller?

### ISSUE THREAD

**Issue by yue9944882** [nginxinc/kubernetes-ingress#143]
I didn't find a usable configuration in the [source code](https://github.com/nginxinc/kubernetes-ingress/blob/master/nginx-controller/nginx/config.go) when rendering ingress to a nginx conf file, for example, "uwsgi_pass" option support?

Any one have a practice to integrate uWSGI to the controller ?

**Comment by pleshakov** [comment]
@yue9944882 
uWSGI doesn't fit into Ingress. Could you share your use case?

**Comment by harts-boundless** [comment]
I'll explain this as I understand it.

uwsgi has its own binary protocol to avoid the overhead of gratuitous http parsing. http://uwsgi-docs.readthedocs.io/en/latest/FAQ.html#why-not-simply-use-http-as-the-protocol

When running uwsgi as an app server behind nginx, it is customary to use `uwsgi_pass`, as recommended in uwsgi's docs (e.g. http://uwsgi-docs.readthedocs.io/en/latest/Nginx.html) to tell nginx where to find the upstream and to talk to that upstream using the uwsgi binary protocol.

To be clear: nginx itself does NOT embed uwsgi in-process here, or get involved with WSGI or python: uwsgi is running in another process that may be somewhere else, to take care of the job of a python app server, and it simply talks to nginx as an upstream using the uwsgi _protocol._ This means all that is required on the nginx side is the ability to accept configuration of uwsgi as an upstream and the ability to speak that protocol as is often done with nginx.

So, not speaking for yue9944882, the very typical use case would be:
* running a Python web application,
* via a WSGI interface (most common and typically best option for most web apps written in e.g. Django or Flask),
* using uwsgi as the app server (arguably one of the most common and best options for running WSGI apps behind nginx),
* in the idiomatic recommended way for uwsgi (i.e. using the uwsgi binary protocol), 
* WITHOUT putting another superfluous proxy in the middle to translate between uwsgi protocol and http.

Supporting uwsgi_pass should be analogous to supporting other protocols that are used for app servers to talk to nginx.

Hope this helps.

**Comment by pleshakov** [comment]
@harts-boundless 
thanks for such a thorough response. The use case you described is valid.

However, for an edge load balancer, such as an Ingress controller, it is not typical to support uwsgi.
It is more common to have nginx as a reverse proxy along an uwsgi application server, and then an HTTP load balancer for load balancing those nginx proxies.

**Comment by vdboor** [comment]
What I'd rather do, is using the embedded HTTP server that uWSGI has. Thus, you can run a single container that has uwsgi as main process. Use a config file like:

```
[uwsgi]
module = $(UWSGI_MODULE)
processes = $(UWSGI_PROCESSES)
threads = $(UWSGI_THREADS)

http = :8080
http-enable-proxy-protocol = 1
http-auto-chunked = true
http-keepalive = 75
http-timeout = 75

# Handle docker stop
die-on-term = 1

vacuum = 1
master = true
enable-threads = true
lazy-apps = 1
thunder-lock = 1
buffer-size = 65535
stats = /tmp/stats.socket

# Logging
log-x-forwarded-for = true
#memory-report = true
#disable-logging = true
#log-slow = 200
#log-date = true

# Avoid errors on aborted client connections
ignore-sigpipe = true
ignore-write-errors = true
disable-write-exception = true

#listen=1000
#max-fd=120000
no-defer-accept = 1

# Limits, Kill requests after 120 seconds
harakiri = 120
harakiri-verbose = true
post-buffering = 4096

# Custom headers
add-header = X-Content-Type-Options: nosniff
add-header = X-XSS-Protection: 1; mode=block
add-header = Strict-Transport-Security: max-age=16070400
add-header = Connection: Keep-Alive

# Static file serving with caching headers and gzip
static-map = /static=/app/web/static
static-map = /media=/app/web/media
static-safe = /usr/local/lib/python2.7/site-packages/
static-gzip-dir = /app/web/static/
static-expires = /app/web/media/cache/* 2592000
static-expires = /app/web/static/frontend/images/* 2592000
static-expires = /app/web/static/frontend/fonts/* 2592000
static-expires = /app/web/* 900

# Redirect http -> https
route-if = equal:${HTTP_X_FORWARDED_PROTO};http redirect-permanent:https://${HTTP_HOST}${REQUEST_URI}
```

and set default values for your environment variables in your container:

```
ENV UWSGI_THREADS=5 \
    UWSGI_PROCESSES=2 \
    UWSGI_MODULE=myapp.wsgi:application

# Have gzipped versions ready for 
RUN gzip --keep --best --force --recursive /app/web/static/

CMD /usr/local/bin/uwsgi --ini /app/uwsgi.ini --procname-prefix-spaced "uwsgi: $UWSGI_MODULE"
EXPOSE 8080
VOLUME /app/web/media
```

When you use Django, you can use "whitenoise" to serve media/static files from your container. In this example, I've used UWSGI directly for that. Preferably, those are cached at your loadbalancer / ingres / cloudfrond environment to avoid hitting the container each time. Thanks to the `static-gzip-dir` setting these are already prepared to be sent as gzipped.

**Comment by smekkley** [comment]
It's a shame that this issue was closed without any discussion. It would have opened up more nginx capability. OP probably knew about uwsgi http support already... Fcgi support would be also great. Another benefit of uwsgi is not needing any xforwarded and all the headers  http puts. I also see static files depending on nginx is better, rather than relying on uwsgi with shorter history of supporting http than nginx. Hitting containers is no issue with k8s, if it is, the application should be fixed.

**Comment by c-goosen** [comment]
Thank you @vdboor vdboor. Ive been contemplating editing uwsgi to do this, but your config was a great guide and working. Thanks for the assists.

**Comment by sanzenwin** [comment]
@vdboor , thanks, it is helpful
