### ISSUE TITLE
Can't build NGINX Plus KIC Docker container on Ubuntu 18.04

### ISSUE THREAD

**Issue by tomminux** [nginxinc/kubernetes-ingress#1432]
**Describe the bug**
Can't build NGINX Plus Kubernetes Ingress Controller on Ubuntu 18.04

**To Reproduce**
1. Follow instructions on https://docs.nginx.com/nginx-ingress-controller/installation/building-ingress-controller-image/
2. checkout v1.10.0
3. make DOCKERFILE=DockerfileForPlus PREFIX=myregistry.example.com/nginx-plus-ingress
4. Got error: "Makefile:59: *** recipe commences before first target.  Stop."

**Expected behavior**
Docker Container Built and pushed to registry

**Your environment**
* v1.10.0
* NGINX Plus
* Ubuntu 18.04

**Comment by lucacome** [comment]
Hi @tomminux

Unfortunately it's a known bug, older versions of `make` (like the one in Ubuntu 18.04) don't work with our `Makefile`. 
We already have a fix in the https://github.com/nginxinc/kubernetes-ingress/tree/release-1.10 branch, but we haven't released a new version yet.

I can suggest other workarounds if you don't feel comfortable in using the branch directly or updating `make` to > 4.1.

Let me know.
