### ISSUE TITLE
"ssl_ciphers NULL" in server block

### ISSUE THREAD

**Issue by rodericliu** [nginxinc/kubernetes-ingress#1435]
seems not a problem I will close it

**Comment by sixsax** [comment]
# Description
I faced this issue during a v1.8.1 helm twice deployment. For some reason the **ssl-cipher** configMap key isn't read correctly when it is iterated for **ingress-template**, instead it works properly for **main-template** section.

As I said I deployed v1.8.1 two times on different cluster, once ssl-cipher is not appears into "ingress-template" despite "ssl-cipher" key had been configured into configMap infact "ssl-cipher" had been configured properly into main-template. 
Instead into second v1.8.1 helm deployment "ssl-cipher" key had been valued with NULL into "ingress-templated" causing a lot of connection problem.

A test on a recent release should be done.

# System
## Helm version
{version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

## kubernetes-ingress version
tag v1.8.1

## K8s host 1
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

## K8s host 2
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:09:28Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:00:06Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
