### ISSUE TITLE
ingress controller version with kubernetes v1.20

### ISSUE THREAD

**Issue by pedinil** [nginxinc/kubernetes-ingress#1436]
**Describe the bug**
kubernetes v1.20 is not working with yaml files version v1.10.1

**To Reproduce**
1. install kubernetes v1.20
2. apply all yaml file according to https://github.com/nginxinc/kubernetes-ingress/tree/master/deployments

**Expected behavior**
i get error from nginx contoller 

/home/runner/work/kubernetes-ingress/kubernetes-ingress/internal/k8s/controller.go:574: Failed to watch *v1.Policy: failed to list *v1.Policy: the server could not find the requested resource (get policies.k8s.nginx.org)
E0307 11:00:48.006382       1 reflector.go:138] /home/runner/work/kubernetes-ingress/kubernetes-ingress/internal/k8s/controller.go:573: Failed to watch *v1alpha1.TransportServer: failed to list *v1alpha1.TransportServer: the server could not find the requested resource (get transportservers.k8s.nginx.org)

**Comment by pleshakov** [comment]
Hi @pedinil 

By default the IC expects a number of CRDs created in the cluster. Their installation is described here https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/#create-common-resources
