### ISSUE TITLE
Mark this repo as outdated please.

### ISSUE THREAD

**Issue by cohadar** [nginxinc/kubernetes-ingress#145]
Development of this has obviously moved to kubernetess/ingress. Please notify the people by editing readme here.

**Comment by aledbf** [comment]
@cohadar this repository is not related to `kubernetes/ingress`.

**Comment by cohadar** [comment]
Not related as in not sharing any code?
Sorry for confusion, is this repo the creator of this image gcr.io/google_containers/nginx-ingress-controller:0.8.3

**Comment by pleshakov** [comment]
@cohadar 
This repo is a different implemetation of NGINX Ingress controller, not related to kubernetes/ingress and also to this image `gcr.io/google_containers/nginx-ingress-controller:0.8.3`

**Comment by aledbf** [comment]
@cohadar no, the repo for that image was https://github.com/kubernetes/contrib/tree/master/ingress/controllers

**Comment by cohadar** [comment]
Thank you for the answers. Please indicate somehow that this is alternative implementation to the one under kubernetes tree. I wasted quite some time due to confusion.

**Comment by pleshakov** [comment]
@cohadar Thanks. We'll add something to the README to eliminate any possible confusion.
