### ISSUE TITLE
How to achieve deployment annotations through helm chart?

### ISSUE THREAD

**Issue by jnunham** [nginxinc/kubernetes-ingress#1469]
Hi,

I'm trying to inject a Jaeger sidecar in to my nginx deployment. I'm deploying nginx through the usage of helm. [Per Jaeger's documentation](https://www.jaegertracing.io/docs/1.21/operator/), a deployment annotation needs to be added so that the Jaeger Operator can find the deployments that need sidecars injected. However, I'm not able to see a way to add deployment level annotations through helm, only pod annotations which will not work in this case.

Is there a way to add deployment level annotations through helm?

**Comment by pleshakov** [comment]
Hi @jnunham 

the helm chart doesn't support deployment annotations unfortunately.

as a workaround, I can suggest modifying the helm template for deployment and installing the chart from sources -- https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/#installing-using-chart-sources

**Comment by jnunham** [comment]
I've forked the code and added deployment annotation capabilities. I've now got Jaeger sidecars being injected. I'll have to make a PR to merge this change in, but for now, I've got this working.
