### ISSUE TITLE
/examples-of-custom-resources/oidc: -enable-preview-policies is required

### ISSUE THREAD

**Issue by cleygraf** [nginxinc/kubernetes-ingress#1483]
**Describe the bug**
In KIC 1.10  the OIDC policy is in preview state. In order to get the example working, nginx ingress needs to be deployed with the argument "-enable-preview-policies". This isn't mentioned in the README.

**To Reproduce**
1. Follow README step 1 - 8
2. Step 9 "Test the Configuration" will fail (500)
3. Check the oidc policy:

kc describe policies.k8s.nginx.org oidc-policy
Name:         oidc-policy
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  k8s.nginx.org/v1
Kind:         Policy
Metadata:
  Creation Timestamp:  2021-03-24T07:13:09Z
  Generation:          1
  Managed Fields:
    API Version:  k8s.nginx.org/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:oidc:
          .:
          f:authEndpoint:
          f:clientID:
          f:clientSecret:
          f:jwksURI:
          f:scope:
          f:tokenEndpoint:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2021-03-24T07:13:09Z
  Resource Version:  169055
  Self Link:         /apis/k8s.nginx.org/v1/namespaces/default/policies/oidc-policy
  UID:               877d5804-c856-40bb-a201-80a2fac05496
Spec:
  Oidc:
    Auth Endpoint:   https://keycloak.example.com/auth/realms/master/protocol/openid-connect/auth
    Client ID:       nginx-plus
    Client Secret:   oidc-secret
    Jwks URI:        http://keycloak.default.svc.cluster.local:8080/auth/realms/master/protocol/openid-connect/certs
    Scope:           openid+profile+email
    Token Endpoint:  http://keycloak.default.svc.cluster.local:8080/auth/realms/master/protocol/openid-connect/token
Events:
  Type     Reason    Age   From                      Message
  ----     ------    ----  ----                      -------
  Warning  Rejected  10m   nginx-ingress-controller  Policy default/oidc-policy is invalid and was rejected: spec.oidc: Forbidden: oidc is a preview policy. Preview policies must be enabled to use via cli argument -enable-preview-policies

4. Add the  argument "-enable-preview-policies" to the nginx-ingress deployment.
5. Step 9 "Test the Configuration" works now.

**Expected behavior**
Add a tip to the README that the argument " -enable-preview-policies" is required to test the oidc policy with KIC 1.10. 

**Your environment**
* KIC 1.10.1
* Kubernetes :1.19.7
* Kubernetes platform: Docker Desktop
* NGINX Plus

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by vepatel** [comment]
Hi @cleygraf, thanks for pointing this out. We do mention the `-enable-preview-policies` flag in [OIDC -> Feature status](https://docs.nginx.com/nginx-ingress-controller/configuration/policy-resource/#oidc) but it should be added as the pre-requisite in example readme too.
