### ISSUE TITLE
disable TLS1 thru annotations?

### ISSUE THREAD

**Issue by katlimruiz** [nginxinc/kubernetes-ingress#1489]
**Describe the bug**
I'm using NGINX1.9.1 and I ran some SSL checks, and some weaknesses were found due to still supporting TLS1.

I want to know how can I disable it thru an kubernetes annotation or a server-annotation.

**To Reproduce**
![image](https://user-images.githubusercontent.com/1009107/113045035-f568ad80-9163-11eb-8580-e8d8ae7c629d.png)

**Expected behavior**
Find an annotation or a way to configure it thru the ingress definition. Not thru helm or manual modification.

**Your environment**
* Version of the Ingress Controller - 1.9.1
* Version of Kubernetes 1.17
* Kubernetes platform (e.g. Mini-kube or GCP) AKS
* Using NGINX or NGINX Plus: NGINX

**Comment by pleshakov** [comment]
Hi @katlimruiz 

TLS protocols are configured via `ssl-protocols` ConfigMap key -- https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#auth-and-ssl-tls You can use the value `TLSv1.2 TLSv1.3` if you only want to support TLS 1.2 and 1.3
