### ISSUE TITLE
ssl-prefer-server-cipher does not seem to work

### ISSUE THREAD

**Issue by woopstar** [nginxinc/kubernetes-ingress#149]
Setting `ssl-prefer-server-cipher` to true in the config map does not seem to set the `SSLPreferServerCiphers` to true, and therefore the following is not added to the config:

`{{if .SSLPreferServerCiphers}}ssl_prefer_server_ciphers on;{{end}}`

**Comment by pleshakov** [comment]
There was a typo in the docs. Please use the `ssl-prefer-server-ciphers` instead of `ssl-prefer-server-cipher`.

**Comment by woopstar** [comment]
Confirmed working. Do you upgrade the docs and close the issue @pleshakov ?

**Comment by pleshakov** [comment]
Yep. thx
