### ISSUE TITLE
Ingress Controller not backward compatible on Kubernetes 1.18

### ISSUE THREAD

**Issue by lkishalmi** [nginxinc/kubernetes-ingress#1491]
**Describe the bug**
Kubernetes 1.18 introduces IngressClass document and deprecate the ingress-class annotation. The nginx-ingress supports both, however either this or that. On 1.18 the annotation is no longer supported.

The annotation based ingress-class specification is only deprecated in 1.18 not removed.
```
I0330 22:26:58.932805       1 main.go:257] Starting NGINX Ingress controller Version=1.10.1 GitCommit=81f8ab7
W0330 22:26:58.940558       1 main.go:296] The '-use-ingress-class-only' flag will be deprecated and has no effect on versions of kubernetes >= 1.18.0. Processing ONLY resources that have the 'ingressClassName' field in Ingress equal to the class.
F0330 22:26:58.943651       1 main.go:300] Error when getting IngressClass nginx-ingress: ingressclasses.networking.k8s.io "nginx-ingress" not found
```
**To Reproduce**
1. Deploy 1.10.1 ingress controller on a Kubernetes 1.18 with annotation based ingress classes
2. See the error above

**Expected behavior**
I'd expect to see the deprecation messages, but the ingress controller shall detect ingresses based on the annotation as well.

**Your environment**
* 1.10.1
* 1.18
* GKE (GCP)
* NGINX Plus

Aha! Link: https://nginx.aha.io/features/IC-113

**Comment by pleshakov** [comment]
Hi @lkishalmi 

The class annotation is still supported. However, from 1.18, the IC requires the IngressClass resource to be deployed.  Please see step 3 https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/#create-common-resources

**Comment by lkishalmi** [comment]
Yes, that's the issue!
IC shall support the IngressClass resource when that's deployed, but it shall not require that!
Annotation based ingress-class spec just deprecated in 1.18 it is not removed!
So I expect the IC warn me about the deprecation, but it still has to accept that form.

**Comment by lkishalmi** [comment]
Well, yes, there is a workaround to create a IngressClass resource in 1.18 clusters.
Though, for me backward compatibility would mean, that I have a cluster with Kubernetes 1.17, annotation specified ingress classes with for example NGINX ingress controller 1.6.x

I can upgrade my cluster to Kubernetes 1.18. I'm free to do that, my ingress controller works (it's too old to know about the latest fancy resources). I can add, remove update ingresses, everything is fine. Now I'd like to upgrade the ingress controller image to something recent. It won't start, as it suddenly needs an IngressClass resource.

Or I have an 1.17 cluster, I upgrade the ingress controller to some recent one. It works like a charm. Next I upgrade the Kubernetes version to 1.18. and bang the site is down as the the ingress controller is down as it suddenly needs an IngressClass resource.

Anyway I will have my workaround by defining the IngressClass on newer clusters, still...

**Comment by lkishalmi** [comment]
This became a real issue since Google started to auto upgrade Kubernetes clusters to 1.18.

I'm a bit dissappointed.
