### ISSUE TITLE
WildcardTLS with wildcard hostname for VirtualServer

### ISSUE THREAD

**Issue by svvac** [nginxinc/kubernetes-ingress#1517]
When deploying a Virtual Server resource with the following TLS config :

`yaml host: test.example.com tls: redirect: enable: true `

With an ingress configured with a `wildcardTLS` secret valid for `*.example.com` does _not_ expose the targeted service properly.

- A request to `http://test.example.com` properly redirects to the TLS endpoint
- **`https://test.example.com`**** uses the default certificate instead of the wildcard**
- **`https://test.example.com`**** does not proxy the request to the upstream service**

#### Env

- Kubernetes `1.20`
- Nginx.org ingress controller `1.9.0`

Aha! Link: https://nginx.aha.io/features/IC-101

**Comment by svvac** [comment]
Note : removing the `tls:` block altogether properly exposes the service on the HTTP endpoint

**Comment by svvac** [comment]
@pleshakov Do you mind explaining why this issue has been tagged `proposal`? It seems like a bug to me.

**Comment by pleshakov** [comment]
Hi @svvac 

This was tagged as a proposal because from our point of view it is an enhancement rather than a bug. This wasn't included into the initial VirtualServer implementation (to reduce the scope), rather than something that is a result of an incorrect implementation.

**Comment by svvac** [comment]
Ok that makes sense, thanks for clarifying. So if I understand correctly, there is currently no way to use the wildcard certificate of the ingress in VirtualServers other than duplicating it?

**Comment by pleshakov** [comment]
> So if I understand correctly, there is currently no way to use the wildcard certificate of the ingress in VirtualServers other than duplicating it?

that is correct.  

One other possible workaround approach in case you have multiple namespaces:
*  create VirtualServers in the namespace with that wildcard TLS secret
* configure TLS termination using that Secret for those VirtualServers
* Create VirtualServerRoutes and reference them from VirtualServers

**Comment by brianehlert** [comment]
Just realized that this was accidentally re-opened by an automation integration.  Sorry.
