### ISSUE TITLE
Remove HTTP2 from annotations on ingress

### ISSUE THREAD

**Issue by woopstar** [nginxinc/kubernetes-ingress#152]
If you enable HTTP2 on one ingress, it will automatic be enabled on all server blocks on the same ip. So if one ingress has HTTP2 enabled, then it is auto enabled for all other server blocks.

So maybe it only makes sense to configure it globally in the config map. Either it's on, or it's off?

**Comment by pleshakov** [comment]
@woopstar you're right. it doesn't make sense to have this annotation.
