### ISSUE TITLE
Custom error page configuration

### ISSUE THREAD

**Issue by nitro2003** [nginxinc/kubernetes-ingress#1521]
Hi, good day!

I'm new to nginx-ingress.
I am trying to customize the error pages for 4xx and 5xx errors.
I can't seem to find any documentation regarding this.
Can someone point me in the right direction?

Thanks!

**Comment by lucacome** [comment]
Hi @nitro2003 

if you’re using Virtual Server resources you can find the documentation here https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#errorpage

Let me know if that helps.

**Comment by nitro2003** [comment]
Thank you for responding @lucacome 
Unfortunately, after checking our cluster, the nginx-ingress installed is an old version and does not have.
Upgrading is not an option right now because this would require an upgrade in the k8s version as well.
Is it possible to customize the error pages for 4xx and 5xx errors using the default-backend?
Thanks!

**Comment by nitro2003** [comment]
I started testing the virtual server configuration.
Is there any way to integrate cert-manager to the virtual server?
Our TLS certificates are auto-generated using cert-manager.
Thanks!
