### ISSUE TITLE
error retrieving k8s version

### ISSUE THREAD

**Issue by unixmind** [nginxinc/kubernetes-ingress#1538]
**Describe the bug**
nginx-ingress-nginx-ingress* pod is retrying on error: "main.go:285] error retrieving k8s version: Get 
 https://10.96.0.1:443/version?timeout=32s": dial tcp 10.96.0.1:443: i/o timeout"

**To Reproduce**
1. Running on Kubernetes 1.20.5
2. Use Helm chart to deploy "nginx-ingress-0.9.1.tgz" chart from https://helm.nginx.com/stable with "--set controller.readyStatus.enable=false" option to deactive the probe
3. See error in logs:
    I0416 13:17:49.951335       1 main.go:258] Starting NGINX Ingress controller Version=1.11.1 GitCommit=3274536
    F0416 13:18:19.954934       1 main.go:285] error retrieving k8s version: Get "https://10.96.0.1:443/version?timeout=32s": dial tcp 10.96.0.1:443: i/o timeout

**Expected behavior**
The pod could be able to retrieve the Kubernetes version

**Your environment**
* Version of the Ingress Controller - release version: stable (0.9.1)
* Version of Kubernetes: 1.20.5
* Kubernetes platform: Kubernetes 1.20.5 based on cri-o & calico
* Using NGINX

**Additional context**
I can manually retrieve k8s version running commands as follows:

    export CLUSTER_NAME=$(kubectl config view -o jsonpath="{.clusters[0].name}")
    APISERVER=$(kubectl config view -o jsonpath="{.clusters[?(@.name==\"$CLUSTER_NAME\")].cluster.server}")
    TOKEN=$(kubectl get secrets -o jsonpath="{.items[?(@.metadata.annotations['kubernetes\.io/service-account\.name']=='default')].data.token}"|base64 --decode)
    curl -s -k -X GET $APISERVER/version? --header "Authorization: Bearer $TOKEN" ; echo
    {
      "major": "1",
      "minor": "20",
      "gitVersion": "v1.20.5",
      "gitCommit": "6b1d87acf3c8253c123756b9e61dac642678305f",
      "gitTreeState": "clean",
      "buildDate": "2021-03-18T01:02:01Z",
      "goVersion": "go1.15.8",
      "compiler": "gc",
      "platform": "linux/amd64"
    }

**Comment by pleshakov** [comment]
Hi @unixmind 

The Ingress Controller needs to be able to connect to k8s API when it starts. We've had several similar issues opened in our repo related to Calico. In those issues, Calico prevented the Ingress Controller from connecting to k8s API. For example, https://github.com/nginxinc/kubernetes-ingress/issues/912  

Could you possibly double check the calico configuration?  Unfortunately, I'm not an expert in calico, so I probably won't be able to help troubleshoot it.

**Comment by unixmind** [comment]
Hi Pleshakov,

From any node, I'm able (skipping SSL handshake) to retrieve Kubernetes version:

    wget --no-check-certificate -q -O - https://10.96.0.1/version? ; echo
    {
      "major": "1",
      "minor": "20",
      "gitVersion": "v1.20.5",
      "gitCommit": "6b1d87acf3c8253c123756b9e61dac642678305f",
      "gitTreeState": "clean",
      "buildDate": "2021-03-18T01:02:01Z",
      "goVersion": "go1.15.8",
      "compiler": "gc",
      "platform": "linux/amd64"
    }

But not withing a pod (e.g. this pod is running "cat" command from busybox image):

    kubectl -n my-namespace exec -ti my-first-deployment-58575584bd-d5lg9 -- sh \
    -c "wget --no-check-certificate -q -O - https://10.96.0.1/version?"
    wget: can't connect to remote host (10.96.0.1): Connection timed out
    command terminated with exit code 1

*I have to check how to allow 10.96.0.1/443 access within any pod running Calico CNI*

**Comment by unixmind** [comment]
Hi Pleshakov,

I discoverd an IP addresses conflict between my cluster "Classless Inter-Domain Routing" and my nodes IP addresses.
I used "calicoctl" utility to create a new IP pool, migrated all pods to the new one and I fixed this issue.

Regards.
