### ISSUE TITLE
documentation - policy - need update

### ISSUE THREAD

**Issue by nergalex** [nginxinc/kubernetes-ingress#1545]
**Describe the bug**
Documentation [here](https://docs.nginx.com/nginx-ingress-controller/configuration/policy-resource/#applying-policies) does not reflect CRDs spec [here](https://github.com/nginxinc/kubernetes-ingress/blob/master/deployments/helm-chart/crds/k8s.nginx.org_virtualservers.yaml#L65)

Current documentation:
```
    policies: # route policies
    - policy2
```

Expected configuration:
```
    policies: # route policies
    - name: policy2
      namespace: cafe
```

**To Reproduce**
[output.log](https://github.com/nginxinc/kubernetes-ingress/files/6339042/output.log)

**Expected configuration**
```
    policies: # route policies
    - name: policy2
      namespace: cafe
```

**Your environment**
* Version of the Ingress Controller - release version or a specific commit: 1.11.1
* Version of Kubernetes: 1.19.7
* Kubernetes platform: AKS
* Using NGINX or NGINX Plus: N+ + App Protect

**Comment by lucacome** [comment]
Hi @nergalex 

Thanks for reporting this! We will hopefully have a fix soon.
