### ISSUE TITLE
APPolicy - disable syntax check?

### ISSUE THREAD

**Issue by nergalex** [nginxinc/kubernetes-ingress#1548]
**Describe the bug**
I want to reuse NGINX App Protect base template for API Protection. NGINX App Protect supports for example VIOL_PARAMETER_VALUE_REGEXP value as a [violation name](https://docs.nginx.com/nginx-app-protect/policy/#violations).

But APPolicy does not accept this value.
[appolicy_output.json.txt](https://github.com/nginxinc/kubernetes-ingress/files/6346548/appolicy_output.json.txt)

Could I disable syntax check process done by APPolicy?

**To Reproduce**
See resource definition in attahed file

**Expected behavior**
Accept policy configuration

**Your environment**
* Version of the Ingress Controller - release version or a specific commit: 1.11.1
* Version of Kubernetes: 1.19.7
* Kubernetes platform: AKS
* Using NGINX or NGINX Plus: N+ + App Protect

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by pleshakov** [comment]
Hi @nergalex 

Could you try to update this file https://github.com/nginxinc/kubernetes-ingress/blob/v1.11.1/deployments/common/crds/appprotect.f5.com_appolicies.yaml#L153 by adding `VIOL_PARAMETER_VALUE_REGEXP` to the enum, update it in the cluster and see if that works?

**Comment by nergalex** [comment]
Hi @pleshakov 
Yes modifying CRD works, thx.
