### ISSUE TITLE
Nginx reporting event  EnsuringLoadBalancer multiple times and shutdown messages in logs

### ISSUE THREAD

**Issue by axcosta** [nginxinc/kubernetes-ingress#1564]
**Describe the bug**
Nginx reporting event  EnsuringLoadBalancer a lot of times  (currently x2496 over 8d). At the same time (I'm not sure if it is related), messages such as the following are appearing a lot of times in pod logs:

```(text)
2021/04/28 20:23:29 [notice] 5956#5956: signal process started
2021/04/28 20:23:29 [notice] 12#12: signal 1 (SIGHUP) received from 5956, reconfiguring
2021/04/28 20:23:29 [notice] 12#12: reconfiguring
2021/04/28 20:23:29 [notice] 12#12: using the "epoll" event method
2021/04/28 20:23:29 [notice] 12#12: start worker processes
2021/04/28 20:23:29 [notice] 12#12: start worker process 5957
2021/04/28 20:23:29 [notice] 12#12: start worker process 5958
2021/04/28 20:23:30 [notice] 5953#5953: gracefully shutting down
2021/04/28 20:23:30 [notice] 5954#5954: gracefully shutting down
```

**To Reproduce**
1. Nginx deployed to GKE cluster (GCP) using an internal LoadBalancer through Helm Chart version 0.7.1
2. View logs on service and on pod created
3. See events/messages reported

**Expected behavior**
Should not present so many events and shutdown messages

**Your environment**
* Version of the Ingress Controller: 1.9.1
* Version of Kubernetes: 1.17.17
* Kubernetes platform: GCP (GKE)
* Using NGINX

**Additional context**
N/A

**Comment by pleshakov** [comment]
Hi @axcosta 

The NGINX Ingress Controller doesn't report `EnsuringLoadBalancer` events. If you created a service of the type LoadBalancer for NGINX Ingress Controller, such events would be reported by the cloud controller that provisions the cloud load balancer on Google Cloud.

**Comment by axcosta** [comment]
Hi @pleshakov, thank you. How about the shutting down messages in logs, this should be considered normal?

**Comment by pleshakov** [comment]
@axcosta 
Shutdowns logs are normal. When the IC reloads NGINX configuration, NGINX master process launches new NGINX worker process with new configuration and gracefully shutdowns the worker processes with the old configuration. More about NGINX architecture -- https://www.nginx.com/blog/inside-nginx-how-we-designed-for-performance-scale/

**Comment by axcosta** [comment]
Thank you again @pleshakov! Sorry for opening this as a bug, but did not have another suitable type.
