### ISSUE TITLE
Cannot create policies - "invalid and was rejected: spec.ingressMTLS"

### ISSUE THREAD

**Issue by Mahendrasiddappa** [nginxinc/kubernetes-ingress#1565]
I am following the example - https://github.com/nginxinc/kubernetes-ingress/tree/78bd4239f39f160f9367254167830ed96739ffda/examples-of-custom-resources/ingress-mtls

After creating all the resource I notice that police is in invalid state. When I describe the policy I see the below error - 
Warning  Rejected        67s (x23618 over 96m)   nginx-ingress-controller  Policy ingress-mtls-policy is invalid and was rejected: spec.ingressMTLS: Forbidden: ingressMTLS is a preview policy. Preview policies must be enabled to use via cli argument -enable-preview-policies

I have set -enable-preview-policies=true when I installed from Helm chart and I also see its set on the ingress controller pod - 

===================
containers:
  - args:
    - -nginx-plus=false
    - -nginx-reload-timeout=0
    - -enable-app-protect=false
    - -nginx-configmaps=$(POD_NAMESPACE)/test-api-svc-nginx-nginx-ingress
    - -default-server-tls-secret=$(POD_NAMESPACE)/test-api-svc-nginx-nginx-ingress-default-server-tls
    - -ingress-class=test-service
    - -health-status=false
    - -health-status-uri=/nginx-health
    - -nginx-debug=false
    - -v=1
    - -nginx-status=true
    - -nginx-status-port=8080
    - -nginx-status-allow-cidrs=127.0.0.1
    - -report-ingress-status
    - -external-service=test-api-svc-nginx-nginx-ingress
    - -enable-leader-election=true
    - -leader-election-lock-name=test-api-svc-nginx-nginx-ingress-leader-election
    - -enable-prometheus-metrics=true
    - -prometheus-metrics-listen-port=9113
    - -enable-custom-resources=true
    - -enable-tls-passthrough=false
    - -enable-snippets=false
    - -enable-preview-policies=true
    - -ready-status=true
    - -ready-status-port=8081
    - -enable-latency-metrics=false
    
===================

ingress controller pod is using below image - 
image: nginx/nginx-ingress:1.11.1

What am I missing here. Why is it still saying preview mode should be enabled ?

**Comment by pleshakov** [comment]
Hi @Mahendrasiddappa 

Unfortunately, I can't reproduce the error.  Could you double check that the logs in that IC pods also report that warning?

Perhaps you have another IC running in the cluster, which has `-enable-preview-policies` set to `false`?

**Comment by Mahendrasiddappa** [comment]
@ pleshakoo Thank you for looking into it. I do see the below error in IC pod - 

==================

I0504 12:53:25.951101       1 event.go:282] Event(v1.ObjectReference{Kind:"Policy", Namespace:"telemetry-api-svc", Name:"ingress-mtls-policy", UID:"74576b9e-41da-42fb-82f7-ffb3c0b38c51", APIVersion:"k8s.nginx.org/v1", ResourceVersion:"299908617", FieldPath:""}): type: 'Warning' reason: 'Rejected' Policy telemetry-api-svc/ingress-mtls-policy is invalid and was rejected: spec.ingressMTLS: Forbidden: ingressMTLS is a preview policy. Preview policies must be enabled to use via cli argument -enable-preview-policies

==================

 I was able to make it working in another EKS cluster. The difference between working cluster and not working cluster is that working cluster is Kubernetes version 1.18 and not working cluster is Kubernetes version 1.17. And in the working cluster I have just one deployment of the controller, but in not working cluster I have 3 different controllers running in different namespaces and -enable-preview-policies is not enabled on other controller. I am creating policy by setting the annotation -

 =================

annotations:
    kubernetes.io/ingress.class: "tod-test"

==================


So does the Kubernetes version or multiple controllers on same cluster have any affect on the preview policies ?

**Comment by Mahendrasiddappa** [comment]
on further investigation it turns out if there is already an Nginx IC running with -enable-preview-policies set to false, and then if I deploy second Nginx IC with -enable-preview-policies set to true, -enable-preview-policies argument does not take effect. 

I reproduced the issue by creating a clean EKS cluster and first deploying Nginx IC with -enable-preview-policies disabled. And the in a new namespace I deployed second Nginx IC with -enable-preview-policies enabled. And then when I try to create  Nginx IC policy, I get the error - 

=============

 Policy tod/2ingress-mtls-policy is invalid and was rejected: spec.ingressMTLS: Forbidden: ingressMTLS is a preview policy. Preview policies must be enabled to use via cli argument -enable-preview-policies

=============

What is the global configuration that all IC's are sharing . Can you please help ?

**Comment by Mahendrasiddappa** [comment]
ok. So if we have multiple ingress controllers, the ingress class annotation on Policy resource does not take effect. So we have to enable preview mode on controllers else, there is no way to tell which controller will pickup the policy resource. 

Please add support for ingress class name to policy resource

**Comment by pleshakov** [comment]
Hi @Mahendrasiddappa 
I created a feature request  issue for this problem https://github.com/nginxinc/kubernetes-ingress/issues/1570
