### ISSUE TITLE
ModSecurity WAF for non plus installations

### ISSUE THREAD

**Issue by blackgold** [nginxinc/kubernetes-ingress#1571]
Is there a general guidance or doc on how to enable ModSecurity WAF for non plus installations?

**Comment by pleshakov** [comment]
Hi @blackgold

We don't support ModSecurity firewall in the Ingress Controller. For Plus installations, we support NGINX AppProtect WAF, but it is different different from ModSecurity.

However, note that ModSecurity WAF is supported by another [NGINX-based Ingress Controller](https://github.com/kubernetes/ingress-nginx)

**Comment by brianehlert** [comment]
I am not certain if this is an NGINX Ingress Controller or a general inquiry regarding NGINX.

ModSecurity is a dynamic module supported by NGINX Plus and available for purchase thus with support: https://docs.nginx.com/nginx-waf/
This is not tested by the NGINX Ingress Controller team for use with Ingress Controller.

This is also possible to compile yourself: https://www.nginx.com/blog/compiling-and-installing-modsecurity-for-open-source-nginx/
Again, this is not tested by the NGINX Ingress Controller team for use with Ingress Controller.

**Comment by tomasohaodha** [comment]
Closing as question answered over 2 weeks ago. If follow-on question is required, please open another issue.
