### ISSUE TITLE
Doc Helm - watchNamespace & VS(R) + Policy

### ISSUE THREAD

**Issue by nergalex** [nginxinc/kubernetes-ingress#1602]
[Installation with Helm](https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/#configuration) >> controller.watchNamespace: Namespace to watch for *Ingress* resources.

watchNamespace parameter apply also to watch custom resources as VirtualServer, VirtualServerRoute and Policy.

**Comment by jasonwilliams14** [comment]
Hi @nergalex
Just to confirm, are you asking for additional documentation to include other resources (vs/vsr, policy etc.)
Thank you for your input.

**Comment by nergalex** [comment]
Hi @jasonwilliams14 
Yes in order to indicate that IC watch for Ingress resources and also for other resources (vs/vsr, policy etc.)
