### ISSUE TITLE
OIDC - error - headless service could not be resolved

### ISSUE THREAD

**Issue by nergalex** [nginxinc/kubernetes-ingress#1606]
**Describe the bug**
Following OIDC example [here](https://github.com/nginxinc/kubernetes-ingress/tree/v1.11.1/examples-of-custom-resources/oidc), I got each 6s this error log:

``[error] 175#175: apigw-headless.lab4-sentence-api.svc.cluster.local could not be resolved (3: Host not found)``

**To Reproduce**
- Follow OIDC example [here](https://github.com/nginxinc/kubernetes-ingress/tree/v1.11.1/examples-of-custom-resources/oidc)
- Note at step 7.1: nginx-ingress-headless.yaml >> Spec: clusterIP: **None**
- show logs: kubectl logs ...

**Expected behavior**
Sync zone across Ingress Controllers

**Your environment**
- Version of the Ingress Controller: IC 1.11.1 and nginx-plus-module-appprotect/now 23+3.332.0-1~buster
- Version of Kubernetes: 1.19.7
- Kubernetes platform: AKS
- Using NGINX Plus

**Additional context**
attached nginx.conf
[nginx.conf.txt](https://github.com/nginxinc/kubernetes-ingress/files/6504683/nginx.conf.txt)

**Comment by pleshakov** [comment]
Hi @nergalex 

Could you double check that you can resolve that DNS name `apigw-headless.lab4-sentence-api.svc.cluster.local` in a separate pod? As shown here https://v1-17.docs.kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#create-a-simple-pod-to-use-as-a-test-environment

**Comment by nergalex** [comment]
Hi @pleshakov 

No DNS resolution for ``apigw-headless`` service. Note that apigw-headless has no IP defined as requested [here](https://github.com/nginxinc/kubernetes-ingress/blob/v1.11.1/examples-of-custom-resources/oidc/nginx-ingress-headless.yaml)

```
/ # curl apigw-headless.lab4-sentence-api.svc.cluster.local
curl: (6) Could not resolve host: apigw-headless.lab4-sentence-api.svc.cluster.local

/ # nslookup apigw-headless.lab4-sentence-api.svc.cluster.local
Server:         10.200.1.10
Address:        10.200.1.10#53

** server can't find apigw-headless.lab4-sentence-api.svc.cluster.local: NXDOMAIN
```

```
# kubectl describe service apigw-headless -n lab4-sentence-api 
Name:              apigw-headless
Namespace:         lab4-sentence-api
Labels:            <none>
Annotations:       <none>
Selector:          app=apigw-microapigw
Type:              ClusterIP
IP:                None
Session Affinity:  None
Events:            <none>
```

**Comment by jasonwilliams14** [comment]
@nergalex 
Can you post your config files? Looks like you have changed some settings.
I re-deployed the example in my lab (I kept everything as is, no modifications) and can corectly resolve the `nginx-ingress-headless` correctly:

`[ root@curl-debug:/ ]$ nslookup nginx-ingress-headless.nginx-ingress.svc.cluster.local
Server:    10.43.0.10
Address 1: 10.43.0.10 kube-dns.kube-system.svc.cluster.local

Name:      nginx-ingress-headless.nginx-ingress.svc.cluster.local
Address 1: 10.42.172.166 10-42-172-166.calico-nginx-ingress.nginx-ingress.svc.cluster.local`

Specifically check the `selector` that is being used in the headless service and make sure it i pointing to the ingress pods.

**Comment by nergalex** [comment]
Hi @jasonwilliams14 

Thank you!
Sorry for the inconvenience
