### ISSUE TITLE
Ability to set https port

### ISSUE THREAD

**Issue by raviparekh** [nginxinc/kubernetes-ingress#1610]
This may already exist as a feature but I have not found this ability. The use case is I would like the nginx controllers to start on another port for https other than 443 and thus I think the security context doesn't need privilege execution and so nginx doesn't need to run as root.

Kubernetes-ingress allows the ability to override the default https port. (See https://github.com/kubernetes/ingress-nginx/blob/b1c8e3047ba31d7ea78f6e0915d187db75230ba5/cmd/nginx/flags.go#L151).

Is there a way the same can be achieved with this or the feature can be added?

Thanks

**Comment by pleshakov** [comment]
Hi @raviparekh 

Changing the https port is not supported.

However, NGINX doesn't run as root - it runs under `nginx` user - both the master and NGINX workers. As you mentioned, It just needs `NET_BIND_SERVICE` to be able to bind to ports 80 and 443 https://github.com/nginxinc/kubernetes-ingress/blob/master/deployments/deployment/nginx-plus-ingress.yaml#L38-L45 

Considering that NGINX doesn't run as root, is it still important to being able to change the https port?

> Is there a way the same can be achieved with this or the feature can be added?

As a workaround, custom templates can be used to change the ports in the configuration -- https://github.com/nginxinc/kubernetes-ingress/tree/v1.11.2/examples/custom-templates

**Comment by raviparekh** [comment]
Thanks @pleshakov 

Yes that helps, ended up making a pod security for nginx user only.
