### ISSUE TITLE
Support service DNS names in appprotect.f5.com/app-protect-security-log-destination annotation

### ISSUE THREAD

**Issue by alonsocamaro** [nginxinc/kubernetes-ingress#1617]
**Is your feature request related to a problem? Please describe.**

When using the following format of the annotation:

```
    appprotect.f5.com/app-protect-security-log-destination: "syslog:server=syslog-svc.ingress-nginx:514"
```

The resulting configuration for dest_ip is 127.0.0.1:

```
nginx@ingress-nginx-nginx-ingress-7d4587b44c-9kq26:/$ grep dest_ip /opt/app_protect/config/config_set.json
"dest_ip": "127.0.0.1",
"dest_ip": "127.0.0.1",
"dest_ip": "127.0.0.1",
"dest_ip": "127.0.0.1",
```

Whilst the NGINX POD is able to resolve, the name (otherwise first logger command next would have failed):

```
nginx@ingress-nginx-nginx-ingress-7d4587b44c-9kq26:/$ logger --server syslog-svc.ingress-nginx test
nginx@ingress-nginx-nginx-ingress-7d4587b44c-9kq26:/$ logger --server syslog-svc-blah.ingress-nginx test
logger: failed to resolve name syslog-svc-blah.ingress-nginx port syslog: Name or service not known
```

**Describe the solution you'd like**

Support DNS names

**Comment by pleshakov** [comment]
Hi @alonsocamaro 

Currently, it is a limitation of AppProtect -- https://docs.nginx.com/nginx-app-protect/configuration/#arguments 

> The destination of the log messages in NGINX format. Only stderr, or an absolute path to a local file, or syslog: and IP/hostname options are accepted. Note: Hostname destination, except for localhost, is currently not supported in App Protect.

**Comment by hmi12** [comment]
Can we now use the service DNS name as the destination in annotation appprotect.f5.com/app-protect-security-log-destination?
like  appprotect.f5.com/app-protect-security-log-destination: "syslog:server=**syslog-svc.default**:514"
