### ISSUE TITLE
Helm chart: be able to set update strategy

### ISSUE THREAD

**Issue by JeroenVanOort** [nginxinc/kubernetes-ingress#1626]
**Is your feature request related to a problem? Please describe.**
Using the helm chart, I installed the nginx Ingress Controller  on a 3 node cluster. Because I want the controller to run on every node, I set `controller.replicaCount` to 3. But when I update the helm deployment, it will try to start a 4th pod to replace one of the first 3. The update fails, because that new pod will try to bind to a specific port on the node, which already has an old pod bound to it.

**Describe the solution you'd like**
What I would like to do, is to set `.spec.strategy.rollingUpdate.maxUnavailable` to 1 and set `.spec.strategy.rollingUpdate.maxSurge` to 0. I believe this would make Kubernetes remove one of the old pods, create a new pod after that, and continue doing so until all pods have been replaced by new ones. But the total number of pods is never above the value of `replicaCount`.

In order to do this, I'd like to be able to specify `.spec.strategy.rollingUpdate` as a value in the Helm chart.

**Describe alternatives you've considered**
I've tried lowering the `replicaCount`, in order to allow a new container to be started and then setting the `replicaCount` back to 3 again. It works, but feels more like a hack than a solid solution.

**Additional context**
I'm willing to put time in creating a PR, but I would like to know how you think about this first.

Aha! Link: https://nginx.aha.io/features/IC-99

**Comment by pleshakov** [comment]
Hi @JeroenVanOort 

I wonder if it makes sense to deploy Ingress Controller as a daemonset in your case, via `controller.kind` paramerer. Would it solve your issue?

**Comment by wd** [comment]
I was using `daemonset` now, but I also want to set the `.spec.strategy` to `onDelete` , so that I can control the pod terminate/create process manually.

**Comment by JeroenVanOort** [comment]
> I wonder if it makes sense to deploy Ingress Controller as a daemonset in your case, via `controller.kind` paramerer. Would it solve your issue?

It does! Thank you very much. For me, this issue can be closed. However, others might still like to influence the strategy.

**Comment by pleshakov** [comment]
Thanks. We'll keep it issue open for the `strategy` related parameters.

**Comment by pdabelf5** [comment]
The ability to add the strategy to the helm chart was added in https://github.com/nginxinc/kubernetes-ingress/pull/2672
