### ISSUE TITLE
install by helm v3.6 failed

### ISSUE THREAD

**Issue by MinhDuc010194** [nginxinc/kubernetes-ingress#1642]
I used helm v3.6 and tried to install nginx-ingress via documentation but always stuck at "helm install my-release nginx-stable/nginx-ingress" step.  Please show me how to pass this issue. I had to install via manifest before but it was uninstalled according to the instructions of the documentation.  

> W0531 20:34:04.353863   22657 warnings.go:70] networking.k8s.io/v1beta1 IngressClass is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 IngressClassList
Error: rendered manifests contain a resource that already exists. Unable to continue with install: IngressClass "nginx" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "my-release"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"

![image](https://user-images.githubusercontent.com/57885262/120265237-c25caa80-c2c9-11eb-95b0-64d92020b017.png)

**Comment by jasonwilliams14** [comment]
Hi @MinhDuc010194 
From the error output above, it looks like there is already a NGINX Ingress installed into your cluster:
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: IngressClass "nginx" in namespace "" exists and cannot be imported into the current release

Did you try to previously install NGINX ingress via helm? Manifests?
```
Can you run a few commands, to see what the output is?
```
helm ls -A
```
Also,
```
kubectl get ingressclass
```
THanks

**Comment by MinhDuc010194** [comment]
Yes. I had install using manifest before but it already uninstalled by flow
guide of manifest documentation at last step

Vào 21:58, T.3, 1 Th6, 2021 Jason Williams ***@***.***> đã
viết:

**Comment by jasonwilliams14** [comment]
@MinhDuc010194 
That makes sense. There are probably some left over CRDs that were installed when you installed using manifests.
I would recommend that you delete those CRDs (I would basically undo the steps used in the Manfiest method....kubectl delete -f <file> ) that were applied.
My guess is that the still exist in the cluster, and Helm is running into problems because Helm is also trying to install those CRD's as well.

**Comment by MinhDuc010194** [comment]
I had to try this command line "kubectl delete -f common/crds/" but the issue still there. I flow all these commands. 
1. kubectl delete namespace nginx-ingress
2. kubectl delete clusterrole nginx-ingress
3. kubectl delete clusterrolebinding nginx-ingress
4.  kubectl delete -f common/crds/

**Comment by pleshakov** [comment]
@MinhDuc010194 
Could you manually delete the IngressClass  resource with the name`nginx`  and then try to install using helm again?

**Comment by MinhDuc010194** [comment]
Thank you for your hint. it exactly the way I looking to resolve this problem.
