### ISSUE TITLE
service default/app-svc doesnt exist, while it's actually running when deploy nginx-ingress controller

### ISSUE THREAD

**Issue by mxpang** [nginxinc/kubernetes-ingress#165]
deployed nginx-ingress controller using yaml under path example, however, there's no external ip assigned, kubectl logs po/ngnix-ingress-rc saysing service/app-svc doesnt exist, while it's running now as service of clusterPort. Is there any other i.e. authorization settings I should do here?
When curl http://hostname:80/path on linux, I can get the response. But if I access it in browser, it doesnt work, page could not be displayed.
I searched a lot, but not able to find a solution, Can anyone help?

**Comment by pleshakov** [comment]
@mxpang 
What is your k8s environment? What is your k8s version? Are you using RBAC? Could you also include the relevant lines from the logs?

**Comment by mxpang** [comment]
hello Michael,
thanks for replying. info as below:
k8s environment: master and worker nodes are in the same host, api server, controller manager, and scheduler run as pods, docker 17.03.1-ce, go1.7.6, etcd 3.1.7
k8s version: v1.6.6
For admission control, --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota
used. Not set authorization-mode as RBAC.

logs for nginx pod:
I0808 03:11:01.660241       1 main.go:49] Starting NGINX Ingress controller Version 0.9.0
W0808 03:11:01.932281       1 controller.go:596] Error retrieving endpoints for the service app-svc: service default/app-svc doesn't exists
W0808 03:11:01.932302       1 controller.go:596] Error retrieving endpoints for the service app-svc: service default/app-svc doesn't exists
2017/08/08 03:11:01 [notice] 31#31: signal process started
2017/08/08 03:11:01 [notice] 43#43: signal process started
2017/08/08 05:21:22 [error] 44#44: *1 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 172.17.0.1, server: foo.bar.com, request: "GET / HTTP/1.1", host: "10.144.101.73"
172.17.0.1 - - [08/Aug/2017:05:21:22 +0000] "GET / HTTP/1.1" 404 169 "-" "curl/7.29.0" "-"
172.17.0.1 - - [08/Aug/2017:06:05:04 +0000] "GET /mongotest HTTP/1.1" 200 25 "-" "curl/7.29.0" "-"

thank you.

**Comment by pleshakov** [comment]
@mxpang 
How does your Ingress resource look like? Does the `app-svc` belong to the same namespace as the Ingress resource?

Did everything work correctly for the path `/mongotest`?

**Comment by mxpang** [comment]
hi @pleshakov ,
the ingress looks like below, not using https..
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /mongotest
        backend:
          serviceName: app-svc
          servicePort: 9000
      - path: /redistest
        backend:
          serviceName: app-svc
          servicePort: 9000
it belongs to `default`, and for nginx-ingress-controller, i didnt set namespace, so it's also in `default` namespace.
I can access `/mongotest `on linux using curl http://ip/mongotest, but not work in browser.

thank you.

**Comment by pleshakov** [comment]
@mxpang what error do you see in the browser?

**Comment by mxpang** [comment]
hi @pleshakov ,
it says this page can't be displayed.

thank you.

**Comment by pleshakov** [comment]
@mxpang can you see the request from the browser captured in the logs?

**Comment by mxpang** [comment]
hi @pleshakov ,
no request from browser captured in the logs, no idea why this isnt sent to the host, 80 and 443 is listened by docker -proxy.
if i use nodePort to expose nginx, then able to access it from browser..

thank you.
