### ISSUE TITLE
How to enable other 3rd party modules such as rDNS?

### ISSUE THREAD

**Issue by VictorVilla-Blizz** [nginxinc/kubernetes-ingress#1657]
Hi there,
I was wondering if it is possible to use other 3rd party modules in this case I'm particulaly interested on rDNS https://www.nginx.com/resources/wiki/modules/rdns/?

If so, is there more to it than just:
1. Compiling the module to whatever nginx version is needed
2. Creating an ad-hoc image with the module
3. Using a custom template to load the module  
4. Use advance config snippets to configure rdns

Would something like above be enough? or is this simply a not supported case?

Thanks

**Comment by pleshakov** [comment]
Hi @VictorVilla-Blizz 

> Would something like above be enough? or is this simply a not supported case?

That would be enough, providing that the module works against the NGINX version used in the IC.

> Using a custom template to load the module

You can also use the `main-snippets` ConfigMap key to load the module. https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#snippets-and-custom-templates

Note that we already package one 3rd party modue - OpenTracing - so it should be possible to extend the Dockerifle to build an image with a new module -- https://github.com/nginxinc/kubernetes-ingress/blob/v1.11.3/build/Dockerfile#L181-L221
