### ISSUE TITLE
HELM - http2 error

### ISSUE THREAD

**Issue by nergalex** [nginxinc/kubernetes-ingress#1669]
**Describe the bug**
Installing Ingress Controller with HELM and config map entry ``http2: True`` generates an error. Without this entry it works

**To Reproduce**
1. Deploy Ingress Controller with HELM configuration:
```
controller:
  config:
    entries:
      http2: True
```
Error:
```
Error: ConfigMap in version \"v1\" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadString: expects \" or n, but found t, error found in #10 byte of ...|,\"http2\":true,\"resol|..., bigger context ...|=100m inactive=60m use_temp_path=off;\
\",\"http2\":true,\"resolver-addresses\":\"10.200.3.10\",\"resolver-v|...
```

**Expected behavior**
Have a http2 listener

**Your environment**
Version of the Ingress Controller: IC 1.11.3 and nginx-plus-module-appprotect
Version of Kubernetes: 1.19.11
Kubernetes platform: AKS
Using NGINX Plus

**Additional context**
Objective: have a http2 listener as described [here](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#listeners)

**Comment by jasonwilliams14** [comment]
Hi @nergalex 

Make sure you enclose True in quotes. So change:
```controller:    
  config:    
    entries:    
      http2: True
```
To this:
```controller:    
  config:    
    entries:    
      http2: "True"
```

Try that and re-deploy with helm.

Let us know how it goes.

**Comment by nergalex** [comment]
It works, thank you @jasonwilliams14
