### ISSUE TITLE
Ipv6 issue with NGINX Ingress Controller 1.7.0

### ISSUE THREAD

**Issue by etavene** [nginxinc/kubernetes-ingress#1682]
**Describe the bug**
 The nginx ingress functionality is not working as expected with ipv6 only k8 cluster. The issue is intermittent, some times in a fresh deployment  nginx  is responding to any http/https queries but in other deployments the same config doesnt respond. Is ipv6 fully supported with nginx? Any inputs are appreciated. Where as in a ipv4 only setup's, we dont see any errors any time with respect to nginx.

**To Reproduce**

  In a non working scenario, the request is getting forward to nginx, but some how the conection are reset. But in other deployments the same config working is fine sometimes. Not able to find the reason for this inconsistent behaviour.

 curl -6 -k -v  https://testserver.com either not responding or getting connection refused errors.

![image](https://user-images.githubusercontent.com/60239552/122600269-27b3e800-d08d-11eb-97a0-b297ad3261e3.png)

note: The nginx ingress pod IP ends with  1e8c
          host Ip is 1212:60

 **Expected behavior**
consistent behaviour with ipv6

**Your environment**
* Version of the Ingress Controller - release version or a specific commit 
* nginx version: nginx/1.17.10
built by gcc 8.3.0 (Debian 8.3.0-6)
built with OpenSSL 1.1.1d  10 Sep 2019
TLS SNI support enabled

* Version of Kubernetes
     Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3"
* Kubernetes platform  -kubespray 
* Using NGINX  
      Nginx image verison -  nginx/nginx-ingress:1.7.0

My virtual server config is 

apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: web-app-vs
  annotations:
    nginx.org/rewrites: "rewrite=/"
spec:
  host: testserver.com
  tls:
    secret: server-secret
    redirect:
      enable: true
      code: 301
      basedOn: scheme
  upstreams:
  - name: web-app
    service: web-app-svc
    port: 80
  routes:
  - path: /
    action:
      pass: web-app

The nginx-ingress is running as a daemon-set in a single node, using hostports 80 and 443

**Comment by pleshakov** [comment]
Hi @etavene 

Unfortunately, while NGINX support ipv6, the Ingress Controller doesn't support it yet - the IC doesn't configure NGINX with proper ipv6 configuration. Here is an issue to track the status of the feature -- https://github.com/nginxinc/kubernetes-ingress/issues/991

**Comment by tomasohaodha** [comment]
Closing this issue as we have another one tracking same #991.
