### ISSUE TITLE
-nginx-status-allow-cidrs not working as expected

### ISSUE THREAD

**Issue by arjaiswa** [nginxinc/kubernetes-ingress#1696]
I have setup -nginx-status-allow-cidrs while installing ingress and config is coming as below
 server {
        listen 8080;

        allow 52.188.5.151/2;
        deny all;

        location /stub_status {
            stub_status;
        }
    }
but when i am hitting 52.188.5.151:8080/stub_status is not working. Could you please tell me how to do this ?
I want to access stub and metric externally.
![image](https://user-images.githubusercontent.com/76682247/123258808-6cb69f00-d511-11eb-901e-60c7cd9df549.png)

I have followed below steps from doc https://docs.nginx.com/nginx-ingress-controller/logging-and-monitoring/status-page/
If you want to access the stub status externally (without kubectl port-forward):

Configure -nginx-status-allow-cidrs command-line argument with IPv4 IP/CIDR blocks for which you want to allow access to the status. By default, the access is allowed for 127.0.0.1.
Use the IP/port through which the Ingress Controller pod/pods are available to connect the stub status at the /stub_status path.

**Comment by pleshakov** [comment]
Hi @arjaiswa  

if it is still relevant, what response did you get when tried to access `52.188.5.151:8080/stub_status` ? 
Do you see an error like this in the IC logs? 
```
2021/07/02 22:51:41 [error] 27#27: *5 access forbidden by rule, client: 10.244.0.7, server: , request: "GET / HTTP/1.1", host: "10.244.0.5:8080"
```
