### ISSUE TITLE
Corresponding ConfigMap keys for the template

### ISSUE THREAD

**Issue by shahriak** [nginxinc/kubernetes-ingress#1701]
I want to put the following parameters in the configMap for optimizing performance, however, I am not able to find them in the doc. Any recommendations?

events {
    multi_accept        on;
    use                 epoll;
}

I tried adding the following in the ConfigMap yaml, however, the pod is now in CrashLoopBackoff Status:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-ingress.configName" . }}
  namespace: {{ .Values.controller.namespace }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
{{- if .Values.controller.config.annotations }}
  annotations:
{{ toYaml .Values.controller.config.annotations | indent 4 }}
{{- end }}
data:
{{- if .Values.controller.config.entries }}
{{ toYaml .Values.controller.config.entries | indent 2 }}
{{- end }}
  main-template: |
    worker_processes  {{.WorkerProcesses}};
    {{- if .WorkerRlimitNofile}}
    worker_rlimit_nofile {{.WorkerRlimitNofile}};{{end}}
    {{- if .WorkerCPUAffinity}}
    worker_cpu_affinity {{.WorkerCPUAffinity}};{{end}}
    {{- if .WorkerShutdownTimeout}}
    worker_shutdown_timeout {{.WorkerShutdownTimeout}};{{end}}
    daemon off;

    error_log  stderr {{.ErrorLogLevel}};
    pid        /var/lib/nginx/nginx.pid;

    {{- if .OpenTracingLoadModule}}
    load_module modules/ngx_http_opentracing_module.so;
    {{- end}}

    {{- if .MainSnippets}}
    {{range $value := .MainSnippets}}
    {{$value}}{{end}}
    {{- end}}

    events {
        worker_connections  {{.WorkerConnections}};
        multi_accept        on;
        use                 epoll;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        {{- if .HTTPSnippets}}
        {{range $value := .HTTPSnippets}}
        {{$value}}{{end}}
        {{- end}}
```

**Comment by pleshakov** [comment]
Hi @shahriak 

Do you see any errors in the IC logs? Also, do you see any events reported for the config map https://github.com/nginxinc/kubernetes-ingress/tree/v1.11.0/examples/custom-templates#troubleshooting ?

Since you're using the helm chart, you can also configure the ConfigMap content via `config.entries`, so there is no need to modify the template file. For example, in the values file you can have:
```yaml
  config:    
    entries:    
      http2: "True"
```

**Comment by shahriak** [comment]
> Hi @shahriak
> 
> Do you see any errors in the IC logs? Also, do you see any events reported for the config map https://github.com/nginxinc/kubernetes-ingress/tree/v1.11.0/examples/custom-templates#troubleshooting ?
> 
> Since you're using the helm chart, you can also configure the ConfigMap content via `config.entries`, so there is no need to modify the template file. For example, in the values file you can have:
> 
> ```yaml
>   config:    
>     entries:    
>       http2: "True"
> ```

Which configmap entries refer to the 2 keys below? I am seeing very limited configurations exposed as compared to the Kubernetes nginx ingress. I am basically looking an for an alternative to https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#enable-multi-accept

multi_accept on;
use epoll;

Also, do you have any recommendations on improving performance in nginx-ingress?

So far I have the following configmap and It seems to give very similar latencies as Istio ingressgateway based on performance tests hitting ~100K RPS. I have about 60 nodes 100/200 ingress pods (HPA enabled) with Linkerd service mesh added as a sidecar. Below is the node info:

```
Capacity:
  attachable-volumes-azure-disk:  16
  cpu:                            8
  ephemeral-storage:              101445540Ki
  hugepages-1Gi:                  0
  hugepages-2Mi:                  0
  memory:                         32887268Ki
  pods:                           30
Allocatable:
  attachable-volumes-azure-disk:  16
  cpu:                            7820m
  ephemeral-storage:              93492209510
  hugepages-1Gi:                  0
  hugepages-2Mi:                  0
  memory:                         28386788Ki
  pods:                           30
System Info:
  Machine ID:                 c6093cbffcd2452c930e0c6773cda5f9
  System UUID:                b89c6b9c-da93-46c3-b54f-ec1ec13d4857
  Boot ID:                    604f3f2a-4711-43d5-87a0-4cc2372b7180
  Kernel Version:             5.4.0-1051-azure
  OS Image:                   Ubuntu 18.04.5 LTS
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  docker://19.3.14
  Kubelet Version:            v1.18.17
  Kube-Proxy Version:         v1.18.17
```

```
    ## The entries of the ConfigMap for customizing NGINX configuration.
    entries:
      access-log-off: "true" # Disable access log
      worker-connections: "100000"
      worker-rlimit-nofile: "102400"
      keepalive: "315"
      keepalive-timeout: "315"
      keepalive-requests: "2147483647" # Set to high number when testing for RPS
      worker-cpu-affinity: auto # Binds worker processes to the sets of CPUs
      lb_method: "least_conn" # Overrides default round robin loadbalancing method
      ssl_redirect: "false"
      server-tokens: "false"
      location-snippet: |
        aio threads;
        aio_write on;
      http-snippets: |
        tcp_nopush  on;
        tcp_nodelay on;
```

**Comment by rawdata123** [comment]
Hi @shahriak, your ConfigMap looks fine for maximizing RPS. 
How are you measuring the latency? and can you send me the output of "lscpu" from your nodes?
