### ISSUE TITLE
error retrieving k8s version: Get "https://10.96.0.1:443/version?timeout=32s": dial tcp 10.96.0.1:443: connect: no route to host

### ISSUE THREAD

**Issue by llyons** [nginxinc/kubernetes-ingress#1706]
**Describe the bug**
I am not sure if this is a bug or not but after inadvertent patching on our linux k8 cluster and a resulting upgrade of kubelet to 1.21.2 from 1.21.1,  we now have our ingress controller and metallb controller that are not able to communicate to api server?

we get this error when pulling the logs of the ingress controller.

F0628 17:08:40.967428       1 main.go:285] error retrieving k8s version: Get "https://10.96.0.1:443/version?timeout=32s": dial tcp 10.96.0.1:443: connect: no route to host

we rolled back the version of kubernetes to 1.21.1 like it was, but that did not fix the issue.

![image](https://user-images.githubusercontent.com/1648546/123677299-8fdf9800-d80a-11eb-8319-f4f5fb575afe.png)

**Expected behavior**

**Your environment**
* Kubernetes 1.21.1 --> 1.21.2  ->  1.21.1
* Centos 7 latest
* Baremetal on prem K8 cluster 3 linux and 3 windows nodes.
* nginx 1.11.3

**Additional context**
Both MetalLB controller and nginx ingress controllers are showing the same kind of error.

**kubectl get logs (metallb controller)**

{"branch":"HEAD","caller":"main.go:138","commit":"v0.10.2","goversion":"gc / go1.16.5 / amd64","msg":"MetalLB controller starting version 0.10.2 (commit v0.10.2, branch HEAD)","ts":"2021-06-28T17:14:00.180647554Z","version":"0.10.2"}
{"caller":"main.go:173","error":"Get \"https://10.96.0.1:443/api/v1/namespaces/metallb-system/secrets?fieldSelector=metadata.name%3Dmemberlist\": dial tcp 10.96.0.1:443: connect: no route to host","msg":"failed to create memberlist secret","op":"startup","ts":"2021-06-28T17:14:01.186687477Z"}

**Comment by llyons** [comment]
When i do  the below curl on the master or other linux nodes

 **curl -kv https://10.96.0.1:443/ve**rsion
 
 the response looks proper
 
 
* About to connect() to 10.96.0.1 port 443 (#0)
*   Trying 10.96.0.1...
* Connected to 10.96.0.1 (10.96.0.1) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate not found (nickname not specified)
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: CN=kube-apiserver
*       start date: May 28 15:48:48 2021 GMT
*       expire date: May 28 15:48:49 2022 GMT
*       common name: kube-apiserver
*       issuer: CN=kubernetes
> GET /version HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.96.0.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Cache-Control: no-cache, private
< Content-Type: application/json
< X-Kubernetes-Pf-Flowschema-Uid: 8a247a72-ba37-4af0-9e4a-842bc9ddd0dc
< X-Kubernetes-Pf-Prioritylevel-Uid: 6ddeff8f-40b3-47d8-bca3-140315312099
< Date: Mon, 28 Jun 2021 20:38:47 GMT
< Content-Length: 263
<
{
  "major": "1",
  "minor": "21",
  "gitVersion": "v1.21.1",
  "gitCommit": "5e58841cce77d4bc13713ad2b91fa0d961e69192",
  "gitTreeState": "clean",
  "buildDate": "2021-05-12T14:12:29Z",
  "goVersion": "go1.16.4",
  "compiler": "gc",
  "platform": "linux/amd64"
* Connection #0 to host 10.96.0.1 left intact

**Comment by llyons** [comment]
Sorry for the question.  Learning as I go.

I am not sure what the issue was but I performed the following on all 3 linux nodes (including master) and it cleared my issue.



```
sudo systemctl stop kubelet
sudo systemctl stop docker
sudo iptables --flush
sudo iptables -tnat --flush
sudo systemctl start docker
sudo systemctl start kubelet

```

Is there some known issue where perhaps rebooting cluster nodes during patching, etc cause unknown states that the above commands clear up?

**Comment by tomasohaodha** [comment]
Hi @llyons glad you were able to resolve this, and we appreciate you posting the fix to the issue thread. It certainly appears the node in question was confused, although exactly why I wouldn't be able to say.
