### ISSUE TITLE
Need Clarification 

### ISSUE THREAD

**Issue by harshsingh1002** [nginxinc/kubernetes-ingress#1715]
I am trying to use Nginx ingress for Cross Namespace routing. i am wondering if we can have multiple Virtualserver within the same or different namespace. I want to use host based routing like foo.example.com should route to one namespace and bar.example.com should route to another namespace and both have same nginx-ingress IP in the backend.

**Comment by pleshakov** [comment]
Hi @harshsingh1002 

VirtualServers can be in different namespaces.  A VirtualServer for `foo.example.com` can be in namespace foo and a VirtualServer for `bar.example.com` can be in the namespace bar.   

You can also have a VirtualServer in one namespace and VirtualServerRoutes in different namespaces (like in an example here https://github.com/nginxinc/kubernetes-ingress/tree/master/examples-of-custom-resources/cross-namespace-configuration)

**Comment by tomasohaodha** [comment]
Closing issue Michael has answered this question. Please open another issue if there is a follow-on, thanks.
