### ISSUE TITLE
1 Ingress 2 backends with 2 different ports

### ISSUE THREAD

**Issue by RudyBone** [nginxinc/kubernetes-ingress#172]
I have a single Ingress.yaml with 2 different path definition and backends.  The first backend in the file has servicePort 443, the second had servicePort 445 (and yes the corresponding service definition had port 445).  Calls to the second backend failed with Bad Gateway until I changed its  port to 443 as well.  Is this a bug in the generation of the proxy configuration or is 443 hardwired in when using SSL?

**Comment by pleshakov** [comment]
@RudyBone 
Could you please share the yaml files for your Services, the Ingress resource and Deployments? What version of the Ingress controller do you use?

**Comment by seletskiy** [comment]
@RudyBone: See https://github.com/nginxinc/kubernetes-ingress/pull/171, it does exactly what you want.

**Comment by RudyBone** [comment]
My bad. Using ssl , forget to add the second service to the annotation section
