### ISSUE TITLE
Unable to install module nginx-plus-module-headers-more in nginx-plus image

### ISSUE THREAD

**Issue by Catskan** [nginxinc/kubernetes-ingress#1723]
Hi guys,

I'm trying to add the `nginx-plus-module-headers-more` to forwarded my HTTP Headers sended by IIS (IIS server is in my container) by my Nginx Plus Ingress Controller.
So, after tried many way to forward the right Header without success, I want to try to use this module to try if it will be work.

So, to do that, I tried create a new docker contrainer, with `FROM image-previously-created` but I'm unable to do that.

What is the best way to install custom-module in the nginx-plus image ?

Thanks in advance

**Comment by jasonwilliams14** [comment]
Hi @Catskan 
If you want to use one of the dynamic modules for NGINX Plus with Ingress, you will need to modify the appropriate Dockerfile from our github repo and add the module to the build process so it will be installed during the build process, to your customer NIC image.

Once you have done that, you can load up the container and verify it exists in `nginx.conf` 
```
load_module modules/ngx_http_js_module.so;
```
By default, we load in our NJS module.
After you build your new image, you should see the module for `more-headers`

Let us know if that helps!
Cheers

**Comment by Catskan** [comment]
Sorry for the late response.

Thanks you very much for your help :)
