### ISSUE TITLE
nginxdemos/nginx-ingress:0.9.0 Start the error：

### ISSUE THREAD

**Issue by misteruly** [nginxinc/kubernetes-ingress#173]
"nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)\n2017/08/28 08:35:09 [emerg] 12#12: open() "/var/log/nginx/error.log" failed (13: Permission denied)\n"

**Comment by pleshakov** [comment]
@misteruly How did you deploy the Ingress controller? What image version did you use? What is your Kubernetes environment?

**Comment by misteruly** [comment]
@pleshakov   images: nginxdemos/nginx-ingress : 0.9.0    k8s  1.6.5

**Comment by pleshakov** [comment]
This is an strange error. If you could share additional info about how you deployed the Ingress controller, including yaml files, that'd be helpful.
