### ISSUE TITLE
ingress   annotations：Can't take effect

### ISSUE THREAD

**Issue by misteruly** [nginxinc/kubernetes-ingress#174]
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: test-mirr
  annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.org/client-max-body-size: "100m"
spec:
  rules:
  - host: test.lan.com
    http:
      paths:
      - path: /
        backend:
          serviceName: test-mirr
          servicePort: 80

images：gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.11    gcr.io/google_containers/nginx-ingress-controller:0.8.3   

It's not going to work！！ feel unwell！！

**Comment by pleshakov** [comment]
@misteruly `nginx.org/client-max-body-size:` doesn't work with the NGINX Ingress controller from https://github.com/kubernetes/ingress If you're using that Ingress controller, please see its documentation https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md

**Comment by misteruly** [comment]
@pleshakov  If so, do you need to install  nginx-ingress-controller  and  default-http-backend????
Need, what version does this need image????  think you for asking me !

**Comment by pleshakov** [comment]
@misteruly Yes. Please check https://github.com/kubernetes/ingress/tree/master/controllers/nginx

**Comment by leprechaun** [comment]
For what it's worth, it's working for me, using the latest version of the helm chart.

Edit the cm, and add the `proxy-body-size: 256m` key.
