### ISSUE TITLE
alpine-image-plus not building

### ISSUE THREAD

**Issue by atanev** [nginxinc/kubernetes-ingress#1745]
**Describe the bug**
I am unable to build an alpine-image-plus based image. The issue is related to locating the packages:
```console
ERROR: unable to select packages:
libcap (no such package):
required by: world[libcap]
nginx-plus (no such package):
required by: world[nginx-plus~24]
nginx-plus-module-njs (no such package):
required by: world[nginx-plus-module-njs~24]
```

I believe this should be related to the tilde "~"  on line https://github.com/nginxinc/kubernetes-ingress/blob/9ccf3a1f1629d5d68ab90bc6f86bf43cb171e435/build/Dockerfile#L30
Also the versioning of the alpine packages is a bit difference and I am unsure if additional adaptations will be required.

**To Reproduce**
1. Deploy x to '...' using some.yaml
2. View logs on '....'
3. See error

**Expected behavior**

**Your environment**
* Version of the Ingress Controller - release version or a specific commit
1.12.0
* Version of Kubernetes
* Kubernetes platform (e.g. Mini-kube or GCP)
* Using NGINX or NGINX Plus
NGINX Plus alpine based

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by vepatel** [comment]
Hi @atanev,
Assuming that you have an active nginx plus subscription, please contact F5/Nginx support. They should also be able to help you get setup with the Ingress Controller.

Thanks.

**Comment by brianehlert** [comment]
NGINX Plus supports these version of Alpine: Alpine Linux 3.10 (x86_64), 3.11 (x86_64), 3.12 (x86_64, aarch64), 3.13 (x86_64, aarch64)  (from here: Alpine Linux 3.10 (x86_64), 3.11 (x86_64), 3.12 (x86_64, aarch64), 3.13 (x86_64, aarch64))

If you are a subscriber to NGINX Ingress Controller / NGINX Plus, there might be an issue with your repository access that the support team can assist with.

**Comment by atanev** [comment]
we have active subscription and so far have used debian based nginx plus IC which we have been building ourselves and now want to try out alpine. Access to the repo is just fine as I have testing it programmatically and can see the content.

Any thoughts on the tilde "~" character I have mentioned?

**Comment by lucacome** [comment]
Hi @atanev the tilde should be okay, we tried rebuilding it and everything seems to be working on our side. 

From the initial log it seems it’s also unable to find `libcap` as well? Would you mind pasting the entire output and the command you used?

Thanks
