### ISSUE TITLE
Is there a way to set the backlog in listener?

### ISSUE THREAD

**Issue by rodericliu** [nginxinc/kubernetes-ingress#1757]
Hi,

I was looking for where can I set the backlog in either Configmap or Annotations, but I failed to find.

Is there a way to set that because the default 511 is too low for us to use in production.

Thanks!

Roderic Liu

Aha! Link: https://nginx.aha.io/features/IC-175

**Comment by vepatel** [comment]
Hi @rodericliu,

If you're using ingress resource, you can set if using `annotations`:
```
name: my-ingress
  annotations:
    nginx.org/server-snippets: |
      listen 80 backlog=1024;
```

**Comment by rodericliu** [comment]
hi @vepatel,

Yes, it added a listen backlog in ingress nginx server block, but nginx complained a duplicate listener on 80.

How did you solve it?

Roderic Liu

**Comment by vepatel** [comment]
Hi @rodericliu,

In that case we'd recommend you to use custom-template for ingress in your configmap: https://github.com/nginxinc/kubernetes-ingress/tree/v1.12.0/examples/custom-templates#example you'll have to pass your ingress config there.

**Comment by rodericliu** [comment]
> Hi @rodericliu,
> 
> In that case we'd recommend you to use custom-template for ingress in your configmap: https://github.com/nginxinc/kubernetes-ingress/tree/v1.12.0/examples/custom-templates#example you'll have to pass your whole ingress config there as we don't have a configmap key parameter for `backlog`.
> eg:
> 
> ```
>  ingress-template: |
>     listen 80  backlog=1024;
> ```

Hi vepatel,

Thanks for your help. I managed to fixed it by the solution provided by you!

Roderic Liu

**Comment by bkannadassan** [comment]
@rodericliu Is there a way to specify the backlog in the latest builds ? or is it still via the custom template ?. If its via custom template then how does this co-exist with the streams ?.
