### ISSUE TITLE
Log rotate mechanism

### ISSUE THREAD

**Issue by seletskiy** [nginxinc/kubernetes-ingress#176]
__Not an issue__.

As far as I know nginx supports log rotate (log reopen) via `USR1` (or `nginx -c reopen`).

I understand, that it is not *quite* responsibility of ingress to rotate logs, but consider following scenario.

I have nginx ingress which writes access logs in special format, which is setup through annotation `nginx.org/server-snippets` (defines `access_log`) and `ConfigMap` with `http-snippets` (defines `log_format`).

That log is shared via volume and processed by some other service in side-car container.

Now, as requests are server by nginx, that custom access log will grow without bounds.

Service inside side-car container has a knowledge when it should rotate log file, but because it's running inside different container (e.g. different image) it's not possible for that container to actually send `USR1` to nginx. It looks like k8s does not have built-in signalling facilities.

So, basically, I need some way to notify nginx to reopen log files on the signal from outside.

I see several ways it can be solved, but all of them seems to be bad design:
* override entrypoint for `nginx-ingress` controller to start custom service (like, from mounted volume), which in turn runs ingress controller and looks for external events, at which it finds out nginx PID somehow and sends `USR1`;
* modify ingress controller to have some kind of API for sending reopen signal;
* add custom resource to k8s API and listen on it, do reload on resource change — looks like overblown solution for such simple task;
* have new annotation which will tells to ingress controller what paths to look for, bind inotify on that paths and send reopen when files are moved around (e.g. `access.log` becomes `access.log.0`).

Or, we can include `logrotate` into ingress controller image? And provide a way to configure it through ingress annotations?

@pleshakov: Maybe, you have some thoughts on that topic?

**Comment by pleshakov** [comment]
@seletskiy 
I don't think it should be a responsibility of the Ingress controller to rotate the logs. Some general tool should do that work.

> override entrypoint for nginx-ingress controller to start custom service (like, from mounted volume), which in turn runs ingress controller and looks for external events, at which it finds out nginx PID somehow and sends USR1;

this option looks good to me. However, since this service becomes the third process in the container, maybe it is a good idea to use something like this https://github.com/Yelp/dumb-init to start that service and the Ingress controller.
I think you will end up having a custom Dockerfile for your case.

**Comment by seletskiy** [comment]
@pleshakov: Yes, I agree. Thanks.
