### ISSUE TITLE
Cluster Wide Controller?

### ISSUE THREAD

**Issue by RudyBone** [nginxinc/kubernetes-ingress#177]
Is there any way to run a non-namespace specific controller? i.e a controller that monitors the creation of Ingress routes across ALL namespaces and then incorporates the service.namespace in its proxy settings?

**Comment by pleshakov** [comment]
@RudyBone by default the Ingress controller watches Ingress resources from all namespaces, unless you specify a namespace to watch using `-watch-namespace` flag. 

What do you mean by "incorporates the service.namespace in its proxy settings"?
