### ISSUE TITLE
Ingress Nginx custom backend for errors

### ISSUE THREAD

**Issue by itisguptak** [nginxinc/kubernetes-ingress#1770]
Hi,

/sig network
I have implemented custom default backend for our Ingress nginx controller using https://kubernetes.github.io/ingress-nginx/examples/customization/custom-errors/#customized-default-backend

It's working all fine except that it also overrides the app error responses. E.g. If a backend app is responding with a 401 or a 503, the UI client looks at the app error response to render the response. But now since I have implemented custom backend, it's not seeing the error response from the app but the response from ingress.

Is there any way we can allow original error response from app to go the client with custom backend enabled at ingress level?

Thank you.

**Comment by vepatel** [comment]
Hi @itisguptak,

This project is different from the NGINX Ingress controller in [kubernetes/ingress-nginx](https://github.com/kubernetes/ingress-nginx) which is the one you referenced in your link. See [this](https://docs.nginx.com/nginx-ingress-controller/intro/nginx-ingress-controllers) doc to find out about the key differences.

Thanks,
Venktesh
