### ISSUE TITLE
NTLM not working only with new deployments

### ISSUE THREAD

**Issue by Catskan** [nginxinc/kubernetes-ingress#1785]
Hi guys,

I call your huge experiences with an a new issue with nginx plus ingress.

So, I enabled the ntlm; in my upstream to access in my apis and I have a strange behavior.

My configuration working good with namespace already existing. But, when I deployed a new namespace, I have "HTTP ERROR 400". But, when I change one thing in my configmap and set in the nginx.conf, it fix the error and api works. Only when I add or comment a new line in this config.

For exemple :
I have "tenant1" newly deployed and I have http 400 with my current nginx.conf. I add "keepalive 32;" in the config file and I refresh my "tenant1" page and it's working with http 200.

I deployed now a "tenant2" and I have again http 400. I delete the "keepalive 32;" previously added. Refresh the "tenant2" and working with http 200.

Did you had a same problem ?

Thanks in advance for your advice :)

Edit 1 : It also working by execute nginx -s reload after a new deployment.

**Comment by vepatel** [comment]
Hi @Catskan,

From your explanation above it looks like a concurrent connection issue where its closing the most recent ones causing 400 and increasing the `keepalive` remediates it.
Can you please try setting this value to 32 at the start using snippets? Also I see that you've an active nginx-plus subscription so I'll highly recommend you submit a request to f5/nginx support :)

-Venktesh

**Comment by Catskan** [comment]
Thanks @vepatel for your quick answer.

So, I added `nginx.org/keepalive: 32` in the Ingress resource in my namespace deployment and same. I have error 400 when newly deployed.
Oh yeah, I forgot to ask the support, thanks :).
Yeah, my nginx is set with LB and Azure by `service.beta.kubernetes.io/azure-load-balancer-internal: "true"`

**Comment by vepatel** [comment]
That's great, I'll close this issue then.

-Venktesh
