### ISSUE TITLE
 Round robin not happening for UDP from static src and dst ip/port

### ISSUE THREAD

**Issue by workhorse2020** [nginxinc/kubernetes-ingress#1825]
**NGINX Ingress controller version**: 1.21.0

**Kubernetes version** (use `kubectl version`):
```
[##]# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** 
```
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.2"
```

- **Kernel** (e.g. `uname -a`):
`4.18.0-193.28.1.el8_2.x86_64 #1 SMP Fri Oct 16 13:38:49 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
`
- **Install tools**:
- **Others**:

**What happened**:

> -> Send a udp packet with with src ip: 1.1.1.1 dst ip: 2.2.2.2 and src port 1111 and dst port 2222
> -> Configure Upstream with Multiple IP end points
> -> { Observation packet are not sent in round robin to upstream pods}

**What you expected to happen**:

> -> Send multiple packet as said above and should observe its sent in round robin
> -> I reduced the proxy_timeout to 100ms and was able to achieve but problem is when response from the pod is delayed
>      entries looks like will be deleted from ingress and hitting destination unreachable. Expect it to LB across multiple upstreams 
> 

**How to reproduce it**:

> -> As said above send the stream packets
> -> Have multiple upstream configured
> -> Send traffic and you will find only packet is received in a single node

**Comment by brianehlert** [comment]
NGINX performs the round robin at connection time based on the client.
Subsequent connections from the same client, I would expect to be routed to the same upstream/backend.

That said, the default behavior of NGINX Ingress Controller is 'random with two' - This is all described here: https://www.nginx.com/blog/nginx-power-of-two-choices-load-balancing-algorithm/

Please provide additional detail as to your test set-up.

**Comment by workhorse2020** [comment]
@brianehlert  Please find the details below and let us know if you need any further details on the same..

```
    upstream coredns-udp {
        least_conn;
        server agent-backend.myenv.svc.cluster.local:21233;
    }
    server {
        listen 2123 udp;
        proxy_pass coredns-udp;
        proxy_responses 1;
        proxy_timeout 5s;
    }
```
Above is the upstream configuration in nginx ingress controller.

server agent-backend.myenv.svc.cluster.local

Above is the actual service to which pods are attached.. When there is a single packet sent for every second it lands in same pod. What we expected since its round robin by default it should land on different pod instance.

Requirement:
---------------
> Packets are sent from 1.1.1.1:1111 -> 2.2.2.2:2222. 
> Packets should be sent in round robin to all pods behind the above k8s service. 
> Pods will scale up and down so load distribution of above packet should happen to new pod when created
> Can we apply hash on UDP content ? Since this is not a http packet and we know the packet content.
> 

If our above approach of upstream and parameters are not correct can you please recommend on how we can acheive the same ?.

rgds
Bala

**Comment by jasonwilliams14** [comment]
@workhorse2020 Can you provide us with some additional information. Specifically:

- your NGINX Ingress controller deployment (manifest files or helm values file)
- your Ingress resource file OR your VirtualServer file
- kubectl describe svc on : `agent-backend.myenv.svc.cluster.local:21233;`

Thank you

**Comment by workhorse2020** [comment]
Below is my nginx config
```
data:
  stream-snippets: |
    upstream coredns-udp {
        least_conn;
        server agent-backend.myenv.svc.cluster.local:21233;
    }
    server {
        listen 2123 udp;
        proxy_pass coredns-udp;
        proxy_responses 1;
        proxy_timeout 10s;
    }

```

Below is the service details of the above agent-backend service.
```
apiVersion: v1
kind: Service
  name: agent-backend
  namespace: myenv
spec:
  clusterIP: 10.111.87.131
  ports:
  - name: agent-udp
    port: 21233
    protocol: UDP
    targetPort: 9123
  selector:
    app: agent-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
Since this is udp loadbalancing for a non http packet have only added above 2.. Please let me know if I a missing something. Sometime I see it getting spread sometimes it sticks to just 1/2 nodes.

rgds
Bala

**Comment by jasonwilliams14** [comment]
@workhorse2020 
You can use TransportServer to do UDP load balancing, which is builtin to NGINX Ingress controller. Have you tried this method?

Transportserver Resource:
https://docs.nginx.com/nginx-ingress-controller/configuration/transportserver-resource/

Here is an example:
https://github.com/nginxinc/kubernetes-ingress/tree/master/examples-of-custom-resources/basic-tcp-udp

Let us know if that helps.

**Comment by brianehlert** [comment]
Without seeing your full ingress definition, we suspect that you are providing the nginx.conf using some method such as configmap.  Basically, directly passing in your nginx.conf instead of using ingress resources and allowing NGINX Ingress Controller to build it.

Based on this perception - it appears that you are using DNS service discovery (which would work fine outside of K8s) and providing the DNS of the target service.
Providing the DNS of the service results in resolving the Service endpoint (one IP) and kube-proxy provides extremely simple load balancing - effectively rendering upstream load balancing and health settings useless.
https://kubernetes.io/docs/concepts/services-networking/service/

Using the TransportServer resource as Jason mentions, means that NGINX Ingress Controller will resolve the individual pods and route traffic directly.  Giving you the same level of control you enjoy outside of K8s.

**Comment by workhorse2020** [comment]
Thanks a lot @jasonwilliams14 @brianehlert  I see a decent spread of connections.  I have following questions..
-> When pods scale looks like upstream configs keep getting updated via signal
     What would be the impact on the traffic in this duration ?
-> When the ingress controller crashes { simulated by deleting the ingress controller taking traffic}. I see from the source where I am sending traffic. Am I missing something ?.
```
TTL 0 during transit from ip=10.163.64.1 name=UNKNOWN
TTL 0 during transit from ip=10.163.64.1 name=UNKNOWN
TTL 0 during transit from ip=10.163.64.1 name=UNKNOWN
TTL 0 during transit from ip=10.163.64.1 name=UNKNOWN
TTL 0 during transit from ip=10.163.64.1 name=UNKNOWN
```
-> Its naive but I suppose the fragmentation are resolved eventhough its at UDP level and then fwded to upstream rt ?
-> Have one additional requirement to inspect inside the udp content and provide and insight on which server to choose
     -> Is it possible to take a look into the packet and check some offset ?
     -> Btw Idea here is looking into an offset send to the same backend pod Instance..
     -> Please note here the traffic is static src/dest ip and udp port. But one content inside udp at certain offset changes.

rgds
Bala

**Comment by brianehlert** [comment]
In K8s any single pod can be recycled at any time for any reason.  The client will always need to perform some reconnection in these cases.
NGINX can be deployed as a fully HA load balancer.  That is generally architected as a layer in front of K8s.

In regards to upstream scaling:
NGINX Ingress Controller watches the Service(s) using the K8s API.
based on that - it dynamically configures the upstream using the IP of the pods themselves (bypassing the service IP) and thus giving the full upstream capabilities of NGINX.
This is regardless of version of NGINX.

If you build your image using NGINX Plus, it additionally brings:

- active health checks for individual pods
- zero restart reconfiguration  (no traffic disruption, dynamic reconfiguration)
- session persistence
- support
- authentication/authorization

Checking on your packet inspection question.

**Comment by brianehlert** [comment]
My NGINX expert has given me the following:

http://nginx.org/en/docs/stream/ngx_stream_js_module.html#js_preread
(the TransportServer is the stream module)

The NJS module is the enabler (already built in to the image and by the Dockerfile)

They state: Inspect the datagram as you wish, set a js variable with the name of the appropriate upstream, then proxy_pass to that variable

NJS can be passed in through the TransportServer resource using snippets.
https://docs.nginx.com/nginx-ingress-controller/configuration/transportserver-resource/#using-snippets

There’s some sample code in this blog post that extracts a value from a known offset in a TCP packet. Same principle applies.
https://www.nginx.com/blog/nginx-plus-iot-load-balancing-mqtt/#mqtt-session-persistence

**Comment by workhorse2020** [comment]
@brianehlert  Thanks for the above information will check the same. Btw I was running hping3 and restarted the pod and it started throwing this error.. Please note there was only 1 pod and experiment was to find the downtime. When this single pod restarted hping was throwing this error and never worked..

```
TTL 0 during transit from ip=10.163.64.1 name=UNKNOWN
TTL 0 during transit from ip=10.163.64.1 name=UNKNOWN
TTL 0 during transit from ip=10.163.64.1 name=UNKNOWN
TTL 0 during transit from ip=10.163.64.1 name=UNKNOWN
TTL 0 during transit from ip=10.163.64.1 name=UNKNOWN
```

rgds
Bala

**Comment by workhorse2020** [comment]
This resolved the roundrobin issue closing this
