### ISSUE TITLE
Ingress Controller Pod Restart results in permanent packet loss

### ISSUE THREAD

**Issue by workhorse2020** [nginxinc/kubernetes-ingress#1826]
**Describe the bug**
Packet to Ingress Controller Fails to reach when the active ingress controller is restarted

**To Reproduce**
Send traffic from a single src ip and port to dest ip and port and now when traffic is flowing delete the ingress controller pod and new one comes up but packet doesn't flow through

**Expected behavior**
New Ingress controller should start receiving and forwarding the traffic.

**Your environment**
**NGINX Ingress controller version**: 1.21.0

**Kubernetes version** (use `kubectl version`):
```
[##]# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** 
```
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.2"
```

- **Kernel** (e.g. `uname -a`):
`4.18.0-193.28.1.el8_2.x86_64 #1 SMP Fri Oct 16 13:38:49 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
`

**Additional context**
Packet failure details
https://im.ge/i/hFUzC

**Comment by brianehlert** [comment]
Our expectation is that your client would reconnect or attempt to send a packet again.
Any stateful connection would need to be re-established as the session state would be lost with its respective Ingress Controller pod.

The expectation is that the new pod would connect using the previous nodeport, clusterip, loadbalancer and traffic would begin being forwarded assuming your health rule indicates the upstream is available.

If you could provide details about your configuration, we might be able to be more helpful.
