### ISSUE TITLE
Mount miscellaneous secrets

### ISSUE THREAD

**Issue by sajal** [nginxinc/kubernetes-ingress#183]
It would be nice if the controller could mount some user provided secret into some directory, which we can refer to from various nginx config.

I can do this by myself in the pod template, but if the controller does it, it could monitor and restart nginx if they change.

My current use-case is for providing a secret key for `ssl_session_ticket_key` setting. If I rotate the data in this secret, I have no way to tell the controller something has changed and nginx needs to be restarted.

Alternate request: Can I ask the controller to watch arbitrary kubernetes resources and reload nginx if it changes?
Alternate alternate request: Is there a scriptable way to reload nginx?

**Comment by pleshakov** [comment]
@sajal 
Regarding Secrets watching. It might be useful to have an anotation like this:
`nginx.org/secrets: "secret1,secret2"`
The Ingress controller will places the listed secrets in a special folder. For example, `/etc/nginx/custom-secrets`. If the Secret changes, NGINX will be restarted. This way you can refer to the Secret from NGINX configuration. For example, from the ```nginx.org/location-snippets``` annotation. What do you think?

> Can I ask the controller to watch arbitrary kubernetes resources and reload nginx if it changes?

What other Kubernetes resources do you have in mind?

> Alternate alternate request: Is there a scriptable way to reload nginx?

You mean some script that reacts on something and reloads NGINX?

Also, this issue in a way similar https://github.com/nginxinc/kubernetes-ingress/issues/176
