### ISSUE TITLE
Kubernetes v1.22

### ISSUE THREAD

**Issue by jslay88** [nginxinc/kubernetes-ingress#1832]
**Describe the bug**
k8s v1.22 has moved everything out of the "beta" apiVersions, including IngressClass. Therefore, the old IngressClass is migrated to `networking.k8s.io/v1`, and then the pods are no longer able to find the IngressClass against the api. 

**To Reproduce**
1. Deploy to v1.22 cluster via helm

```
I0805 17:21:16.952792       1 main.go:271] Starting NGINX Ingress controller Version=1.12.0 GitCommit=c9d3618da566b158a53a6da098ff677aac28b7ff Date=2021-06-30T10:34:29Z PlusFlag=false
W0805 17:21:16.967321       1 main.go:310] The '-use-ingress-class-only' flag will be deprecated and has no effect on versions of kubernetes >= 1.18.0. Processing ONLY resources that have the 'ingressClassName' field in Ingress equal to the class.
F0805 17:21:16.969378       1 main.go:314] Error when getting IngressClass nginx: the server could not find the requested resource
```

**Expected behavior**
A working ingress controller

**Your environment**
```
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
nginx-ingress           default         3               2021-08-05 03:56:14.7197197 -0600 MDT   deployed        nginx-ingress-0.10.0            1.12.0
```
* k8s v1.13 -> v1.22 via kubeadm over the past couple years almost.
* Installed via Helm

**Comment by brianehlert** [comment]
We intend to address Ingress v1 in the next release.
Thanks for raising the issue.

**Comment by jslay88** [comment]
> We intend to address Ingress v1 in the next release.
> Thanks for raising the issue.

Awesome. I will be impatiently awaiting, since I have no ingress controller now :)

**Comment by brianehlert** [comment]
v1beta1 works with k8s <1.22 - but obviously you like living on the edge  ;-)

**Comment by jslay88** [comment]
> v1beta1 works with k8s <1.22 - but obviously you like living on the edge ;-)

Hehe, lab cluster, wasn't really paying attention to upgrade docs. My fault, I know. 

I had come from v1.21.3 and was working great there. But alas, "we're doing it live!" has bit me.

**Comment by brianehlert** [comment]
When we get it done, you will see it in our 'edge'.  You can always watch the PRs.
If you build your own container image, you can always choose 'edge' instead of a release.

I am noting this, so the link should get made to the issue.

**Comment by jslay88** [comment]
So from looking at all this, all I should have to do is swap out the `controller.image.tag` on the helm chart with "edge" once the fix is available, no?

**Comment by vepatel** [comment]
Hi @jslay88 you can install it using chart sources from master branch once it's available: https://github.com/nginxinc/kubernetes-ingress/tree/master/deployments/helm-chart#installing-using-chart-sources
```
~/nginx/kubernetes-ingress/deployments/helm-chart master*
 helm install edge-release --namespace=<IC_NAMESPACE> --set controller.kind=deployment --set controller.image.repository=nginx-oss-ingress --set controller.image.tag=edge .
```

**Comment by jslay88** [comment]
Will have to wait till Monday. Not accessible u til the.  But will give it
a shot then. Thanks!

**Comment by jslay88** [comment]
```
unable to recognize "": no matches for kind "IngressClass" in version "networking.k8s.io/v1beta1"
```

I changed `controller-ingress-class.yaml` to `apiVersion: networking.k8s.io/v1` and this works to get the chart deployed. 


However, still end up in crash loop backoff. 
```
I0809 08:11:40.772285       1 main.go:207] Starting NGINX Ingress controller Version=v1.12.0-SNAPSHOT-f44945fc GitCommit=f44945fcef690bfb099e8cc0f7356a14195a96a2 Date=2021-07-29T15:19:40Z PlusFlag=false
W0809 08:11:40.780379       1 main.go:308] The '-use-ingress-class-only' flag will be deprecated and has no effect on versions of kubernetes >= 1.18.0. Processing ONLY resources that have the 'ingressClassName' field in Ingress equal to the class.
F0809 08:11:40.781956       1 main.go:312] Error when getting IngressClass nginx: the server could not find the requested resource
```

**Comment by vepatel** [comment]
Hi @jslay88, It's [not available](https://github.com/nginxinc/kubernetes-ingress/issues/1832#issuecomment-894137182) yet hence not working. You'll have to wait until we push the changes to master.

**Comment by tanzwut2525** [comment]
Hi @vepatel !
Do you know ETA of it? Because I have the same problem.

**Comment by jslay88** [comment]
> Hi @jslay88, It's [not available](https://github.com/nginxinc/kubernetes-ingress/issues/1832#issuecomment-894137182) yet hence not working. You'll have to wait until we push the changes to master.

ahhh sorry, skipped over "once its available" when reading in email. Thanks!

**Comment by brianehlert** [comment]
Yep.  We are working on getting this solid.
Thanks for patience from you folks on the bleeding edge.

**Comment by jslay88** [comment]
For the heck of it (and trying to refamiliarize with golang), I have tried to make my own version by swapping out the v1beta1 stuff throughout the code, as well as implementing the new structs for backend service and service port. I have it discovering ingress again, but 

```
E0811 09:24:03.188912       1 controller.go:559] Error updating endpoints for [jenkins/jenkins]: Error reloading NGINX when updating endpoints: nginx reload failed: Command /usr/sbin/nginx -s reload stdout: ""
stderr: "2021/08/11 09:24:03 [emerg] 84#84: unknown directive \"Name:,Number:5000,}\" in /etc/nginx/conf.d/arkmodding-dmm-discord-member-manager.conf:3\nnginx: [emerg] unknown directive \"Name:,Number:5000,}\" in /etc/nginx/conf.d/arkmodding-dmm-discord-member-manager.conf:3\n"
finished with error: exit status 1
```

progress...

**Comment by daniel-afo** [comment]
Hello together, as i'm also affected by this "bug", i would like to know when the fix will be released, is there a plan?

Greetings 

Daniel

**Comment by brianehlert** [comment]
We are currently working on this.  As stated above.  Literally.

**Comment by brianehlert** [comment]
Ingress v1 is complete on 'edge'
You can build your NGINX Ingress Controller image using the version tag 'edge' to give this a go.
