### ISSUE TITLE
Proxy client cert/key Secret?

### ISSUE THREAD

**Issue by RudyBone** [nginxinc/kubernetes-ingress#185]
Is there a way to configure a cert/key Secret for the proxy side making calls to the configured Ingress services like the TLS Secret facing the external world?  I ended up adding a configuration as a snippet annotation and just referencing the .pem created for the TLS Secret in /etc/nginx/ssl.  Would prefer a separately configurable Secret however.

**Comment by pleshakov** [comment]
@RudyBone 
Could you share your snippet? Do you mean client SSL certificates and keys -- http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_ssl_certificate and http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_ssl_certificate_key ?

**Comment by RudyBone** [comment]
Here is the snippet from my ingress resource yaml:

annotations:
   nginx.org/locations-snippets: |
       proxy_ssl_certificate /etc/nginx/ssl/test-ingress-ingress-tls-secret.pem
       proxy_ssl_certificate_key /etc/nginx/ssl/test-ingress-ingress-tls-secret.pem

The cert and key reference the same file created by the TLS secret I specify later in the file.  Obviously, in the case where I need a different cert/key I could mount them myself via the pod definition and modify the annotation to reference the mount point, but since there Ingress yaml already provides support for the TLS secret I was just wondering if there was something similar for the proxy that would make things a little simpler.
