### ISSUE TITLE
no matches for kind "IngressClass" in version "networking.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by caobo1020** [nginxinc/kubernetes-ingress#1857]
**Describe the bug**
See the following error when following the official guide - https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/#create-common-resources to install ingress

```
git checkout v1.12.0

k8s-master:~/k8s_proj/kubernetes-ingress/deployments$ kubectl apply -f common/ingress-class.yaml
error: unable to recognize "common/ingress-class.yaml": no matches for kind "IngressClass" in version "networking.k8s.io/v1beta1"
```

**Your environment**
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:57:25Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

running ubuntu VM on VMware fusion.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

**Comment by lucacome** [comment]
Hi @caobo1020 

unfortunately k8s `1.22` is not supported in `1.12.0` as you can see in the release notes [here](https://docs.nginx.com/nginx-ingress-controller/releases#:~:text=This%20release%20was%20fully%20tested%20on%20the%20following%20Kubernetes%20versions%3A%201.16-1.21.).

**Comment by caobo1020** [comment]
Hi Luca,

thanks very much for the info.

Bo

**Comment by brianehlert** [comment]
Ingress v1 is complete on 'edge'
You can build your NGINX Ingress Controller image using the version tag 'edge' to give this a go.
