### ISSUE TITLE
Kubernetes 1.7.3 with cni plugin and weave?

### ISSUE THREAD

**Issue by RudyBone** [nginxinc/kubernetes-ingress#187]
I had a simple Ingress example working on my 1.6.5 cluster with flannel and the I upgraded my cluster to 1.7.2 with the cni plugin and weave.  I also went from the kubernetes-ingress 0.9.0 to 1.0.  I update my controller and ingress yaml to reflect any changes between 0.9.0 and 1.0.0.  When re-deployed my setup i get an error similar to the following in the controller log:

controller.go:885] Error getting service java-resource-tester: service test-ingress1/java-resource-tester doesn't exist.

The referenced service definitely exists as I am able to exec into a pod and successfully curl to the service using is fully qualified service name.  The service is in the same namespace as the controller and the service account I used to deploy the controller has full cluster-admin rights.  

Despite the above error, the controller still creates the corresponding proxy config file in /etc/nginx/conf.d. However when I modify my /etc/hosts file to map my test hostpath to the IP of the controller pod instance I get no response when I try to access the service through my browser.

Any tips on furthe debug options would be appreciated.

**Comment by pleshakov** [comment]
@RudyBone Could you enable extensive logging  by uncommenting [this line](https://github.com/nginxinc/kubernetes-ingress/blob/master/examples/complete-example/nginx-ingress-rc.yaml#L33)  and share the corresponding logs?

**Comment by RudyBone** [comment]
I did uncomment the - -v=3 line, and the 'extensive' logging consists of the log statement in my previous post.

**Comment by pleshakov** [comment]
@RudyBone `- -v=3` enables logging of a lot of additional info at that level of verbosity. Is that the case for you?
Also, do you have any problems for Ingress resources that reference some other services?

**Comment by RudyBone** [comment]
Okay, I think maybe I'm barking up the wrong tree here.  When I  look at the file created in /etc/nginx/conf.d for my Ingress everything looks kosher.  The upstream server address does in fact match the IP:Port for my service endpoint and I can hit that endpoint from INSIDE the cluster.  Maybe my problem has to do with the hostPort configured in the controller.  Am I correct in understanding that when I specified the hostPort in the container spec, its NOT necessary to specify hostNetwork? Is there a URL on the nginx-controller (like an status page or something) that I could try hitting directly using the pod's IP address and host port(s) (80 and 443) to establish that the hostPort is working.

**Comment by pleshakov** [comment]
@RudyBone 
It is necessary to use `hostNetwork` when using CNI. If you make a request to <node-ip>:80, you should get a 404-page from NGINX.

**Comment by RudyBone** [comment]
Yup, I just found that out after trying to deploy another pod using hostPort, failing then searching online for cni and hostPort.  Thanks for the help

**Comment by RudyBone** [comment]
Hope your still monitoring this thread.   Updated my controller to use hostNetwork with the cni plugin and things "kind of work".  I'm using SSL, when I access the controller on port 443 I get a 404 error, however port 80 works.  I notice that in the /etc/nginx/conf.d config file, the server section has listen 80.  Shouldn't it be listen 443?

**Comment by pleshakov** [comment]
@RudyBone 
How did you configure SSL termination in your Ingress resource?

**Comment by RudyBone** [comment]
Here is my ingress definition (I'll probably see the issue as soon as I type it in):

apiVersion:
kind: Ingress
metadata:
   name: test-ingress
   namespace: test-ingress
   annotations:
      nginx.org/ssl-services: "java-resource-tester"
      nginx.org/location.snippets: |
        proxy_ssl_certificate /etc/nginx/secrets/default
        proxy_ssl certificate_key /et/nginx/secrets/default
spec:
   rules:
   - host: ingress.example.com
     http:
        paths: /api
        backend: 
          serviceName: java-resource-tester
          servicePort: 443

**Comment by pleshakov** [comment]
@RudyBone you didn't configure SSL termination, that is why you get 404 when connecting through 443 port. See the [cafe-ingress](https://github.com/nginxinc/kubernetes-ingress/blob/master/examples/complete-example/cafe-ingress.yaml#L6) as an example if you would like to configure SSL termination.

The `/etc/nginx/secrets/default` that you reference in `proxy_ssl_certificate` is also used as the default TLS secret and key -- it is used by the default server - https://github.com/nginxinc/kubernetes-ingress/blob/master/nginx-controller/nginx/templates/nginx.tmpl#L57 - the one that sent you a 404 response code. Thus, it is better to upload the secret for the `proxy_ssl_certificate` using the other method. For example, map it as a file -- https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod

**Comment by RudyBone** [comment]
Sweet, that was it.  I could kick myself, somewhere between moving from k8s 1.6.5/flannel to k8s 1.7.3/cni I must have stupidly deleted that section from my Ingress.yaml.

I understand the cert issue, I just did it this way for a quick test, in my production role out we will be using 2 different certs

**Comment by RudyBone** [comment]
Okay, I've got things working within 1 namespace, so I added the same pod/service I used in namespace1 to namespace2 and added an ingress for it with a different path.  I see the a new proxy config created for this ingress in /etc/nginx/conf.d.  However when I try to access the service path to namespace2, I get a 404 error from my namespace1 service.   The path to namespace1 is /api and the path to namespace2 is /api2.  Both proxy config files have 'listen 443 ssl' in their server section.  Perhaps I am misunderstanding the meaning of 'servicePort' inside the ingress backend definition.  I assumed it was the internal listener port of the backend service, is actually the controller port on the host network to use for this service?

**Comment by pleshakov** [comment]
@RudyBone You will have to create two different Ingress resources, one per each namespace, with different hostnames.  For example, `api-ns2.example.com` with `/api1` rule and `api-ns1.example.com` with `/api2` rule. You can't create two Ingresses resource with the same hostname.  `api.example.com` with `/api1` rule and `api.example.com` with `/api2` rule won't work!

The value of servicePort should be the the same as the value of the port you specify in a Service manifest.

**Comment by RudyBone** [comment]
Makes sense. Did I just miss this fact somewhere  in the Readme.md?

**Comment by pleshakov** [comment]
@RudyBone it is not mentioned explicitly anywhere.
