### ISSUE TITLE
How to disable SSL/HTTPS?

### ISSUE THREAD

**Issue by gowthamsadasivam** [nginxinc/kubernetes-ingress#189]
The example files from the repo works as it is with HTTPS enabled. But I wanted to disable "HTTPS/SSL" feature and listen to port "80" by supporting "HTTP" only. I tried editing the existing files from repo and saw ingress-controller crashing with "CrashLoopBackOff". Here are the things I edited:

1. In `nginx-ingress-rc.yaml`       
    - Removed `containerPort: 443` (Line 23)
    - Removed `hostPort: 443` (Line 24)
    - Commented out `-default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret` (Line 35)

2. In `cafe-ingress.yaml`
    - Removed `  tls:
  \- hosts:
    \- cafe.example.com
    \ secretName: cafe-secret` (Lines 6 to 9)

3. Didn't use these following files
    - `default-server-secret.yaml`
    - `cafe-secret.yaml`

4. Created
    - `kubectl create -f nginx-ingress-rc.yaml`
    - `kubectl create -f tea-rc.yaml`
    - `kubectl create -f tea-svc.yaml`
    - `kubectl create -f coffee-rc.yaml`
    - `kubectl create -f coffee-svc.yaml`
    - `kubectl create -f cafe-ingress.yaml`

5. Now get all pods: **_kubectl get pods -o wide --all-namespaces_**
```
NAMESPACE     NAME                                    READY     STATUS             RESTARTS   AGE       IP            NODE
default       coffee-rc-47zkj                         1/1       Running            0          2m        172.30.71.5   minion03
default       coffee-rc-5bd3m                         1/1       Running            0          2m        172.30.89.6   minion02
default       nginx-ingress-rc-57wld                  0/1       CrashLoopBackOff   4          2m        172.30.89.4   minion02
default       tea-rc-47fqs                            1/1       Running            0          2m        172.30.89.5   minion02
default       tea-rc-jnzwb                            1/1       Running            0          2m        172.30.71.4   minion03
default       tea-rc-qz96x                            1/1       Running            0          2m        172.30.71.3   minion03
kube-system   kube-dns-v20-z8lnd                      3/3       Running            0          14d       172.30.71.2   minion03
kube-system   kubernetes-dashboard-3543765157-tmmb8   1/1       Running            1          14d       172.30.89.2   minion02
kube-system   tiller-deploy-833363792-6h5tv           1/1       Running            0          11d       172.30.89.3   minion02

```
^ From the above you can see that `nginx-ingress-rc-57wld                  0/1       CrashLoopBackOff` Nginx Ingress Controller is crashing in a loop.

**Logs from the container**: `docker logs nginx-ingress`
`I0919 12:01:54.516143       1 main.go:58] Starting NGINX Ingress controller Version 1.0.0`
`F0919 12:01:54.518125       1 main.go:113] A TLS cert and key for the default server is not found`

How to avoid this error, What am I doing wrong? Is there any other method that I could use to disable "HTTPS/SSL" completely? Please advice.

**Comment by pleshakov** [comment]
@gowthamsadasivam 
Disabling SSL for the default server is not supported. However, you can disable SSL for Ingress resources.

Is there a particular reason why you don't wont to have SSL enabled for the default server?

**Comment by gowthamsadasivam** [comment]
@pleshakov 
I'm running network/traffic heavy services inside the containers. I want to disable SSL, just to avoid any latencies due to traffic encryption/decryption. Also, all my services run inside a private cloud which is not exposed to public.

> you can disable SSL for Ingress resources


^ This means, from the example files I can disable SSL for the `"cafe ingress"` resource by editing `"cafe-ingress.yaml"` ? if yes please let me know how to do that.

In case of disabling SSL/HTTPS is not at all possible, at-least let me know if there any option to `disable automated http-to-https redirection`? so that I could enforce all traffic through HTTP only to reduce the latency. I've tried adding the annotation `nginx.org/redirect-to-https: "False"` to the `"cafe-ingress.yaml"` file. But it doesn't help to disable the automated redirection.

Any suggestions/help is highly appreciated. Thanks.

**Comment by pleshakov** [comment]
@gowthamsadasivam thanks for the explanation. 

If you define an Ingress resource without the `tls` section, the Ingress controller will not configure SSL termination for that Ingress resource and there will be no redirect to https.

However, SSL termination will be configured for the default server. The default server is a server that responds to any request with an unmatched host header. For example, you have Ingress resources for the domains `app.example.com` and `web.example.com`.  If you make a request to the Ingress controller for a domain other than   `app.example.com` and `web.example.com`, NGINX will respond with a 404-page for such a request, both for HTTP and HTTPS. For example:
```curl app.example.com``` -> 200 OK
```curl web.example.com``` -> 200 OK
```curl random.example.com``` -> 404 Not Found

**Comment by gowthamsadasivam** [comment]
@pleshakov :100: 

Thanks lot for the solution. I just removed the `tls` section from the `cafe-ingress.yaml` and it works like charm. It disabled the automated `http-to-https` redirection for the `cafe ingress` resource.

Also, If I'm not wrong I didn't come across this idea of removing `tls` section will remove `https` for the ingress resource in the current documentation. It would be great and helpful to others if added to the current documentation :)
