### ISSUE TITLE
Enable setting gzip support for OIDC policy

### ISSUE THREAD

**Issue by Binsabbar** [nginxinc/kubernetes-ingress#1893]
**Auth0: OIDC authorization code sent but token response is not JSON**

**Describe the bug** When using OIDC policy in VirtualServer, I faced an issue with token exchange. In the logs I get `OIDC authorization code sent but token response is not JSON`

**To Reproduce** Steps to reproduce the behavior: 1. Create an Application in Auth0 as your authentication backend 2. Follow the steps in [https://github.com/nginxinc/kubernetes-ingress/tree/master/examples-of-custom-resources/oidc](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples-of-custom-resources/oidc) 2. View logs on 'kubectl logs -f nginx-POD-NAME -n nginx-ingress' 3. See error ` 2021/08/21 14:07:30 [error] 10385#10385: *1172246 js: OIDC authorization code sent but token response is not JSON. ∩┐╜∩┐╜∩┐╜═ª∩┐╜∩┐╜-∩┐╜∩┐╜∩┐╜∩┐╜∩┐╜cH┼╛∩┐╜∩┐╜y∩┐╜I∩┐╜╒à∩┐╜hE}∩┐╜∩┐╜∩┐╜∩┐╜∩┐╜╨║Z/∩┐╜-=∩┐╜∩┐╜∩┐╜/7∩┐╜ d∩┐╜∩┐╜ml-hBZ∩┐╜╥éM∩┐╜i_∩┐╜∩┐╜w/<n∩┐╜∩┐╜)d∩┐╜ ∩┐╜Ha∩┐╜∩┐╜∩┐╜∩┐╜∩┐╜]∩┐╜∩┐╜5z\∩┐╜∩┐╜u∩┐╜?nq(nQ(∩┐╜╓╢q∩┐╜∩┐╜╬╡∩┐╜∩┐╜G∩┐╜qLE∩┐╜uw∩┐╜∩┐╜∩┐╜∩┐╜∩┐╜|.∩┐╜∩┐╜∩┐╜∩┐╜═ì∩┐╜T∩┐╜╬ôK∩┐╜∩┐╜∩┐╜4i∩┐╜Q∩┐╜∩┐╜∩┐╜∩┐╜{a∩┐╜∩┐╜ C)hB∩┐╜∩┐╜∩┐╜∩┐╜∩┐╜∩┐╜∩┐╜s∩┐╜∩┐╜∩┐╜∩┐╜╒å6∩┐╜F|∩┐╜╪å>∩┐╜Y∩┐╜∩┐╜c∩┐╜∩┐╜∩┐╜Kb ∩┐╜∩┐╜{∩┐╜∩┐╜/∩┐╜<mL∩┐╜qQ]∩┐╜∩┐╜<∩┐╜?L∩┐╜∩┐╜@∩┐╜▄¼∩┐╜∩┐╜>∩┐╜$∩┐╜;D∩┐╜∩┐╜∩┐╜∩┐╜|H67∩┐╜∩┐╜up∩┐╜∩┐╜∩┐╜E∩┐╜ ∩┐╜V∩┐╜{∩┐╜nWK∩┐╜∩┐╜∩┐╜∩┐╜E∩┐╜∩┐╜M∩┐╜∩┐╜∩┐╜D∩┐╜∩┐╜∩┐╜M)∩┐╜∩┐╜fw∩┐╜&&∩┐╜y∩┐╜∩┐╜F∩┐╜∩┐╜∩┐╜+<∩┐╜╒î∩┐╜ ∩┐╜P∩┐╜∩┐╜∩┐╜∩┐╜OJO∩┐╜∩┐╜F`9∩┐╜k∩┐╜∩┐╜Ik∩┐╜∩┐╜∩┐╜E∩┐╜?∩┐╜∩┐╜z/∩┐╜|6{To∩┐╜ L'5[∩┐╜G∩┐╜∩┐╜8∩┐╜Z∩┐╜∩┐╜∩┐╜9∩┐╜G∩┐╜O∩┐╜3∩┐╜∩┐╜S.YxF5)U∩┐╜&∩┐╜,-∩┐╜/┌óH∩┐╜∩┐╜∩┐╜∩┐╜?∩┐╜∩┐╜. ∩┐╜∩┐╜∩┐╜R∩┐╜∩┐╜W∩┐╜(r∩┐╜R~∩┐╜[,∩┐╜|Tn∩┐╜g∩┐╜∩┐╜∩┐╜LP∩┐╜|∩┐╜╞úI╚á∩┐╜∩┐╜╟Çk5∩┐╜∩┐╜∩┐╜∩┐╜M∩┐╜▐º∩┐╜^∩┐╜∩┐╜xK∩┐╜a?∩┐╜∩┐╜H5x∩┐╜(╟Ö∩┐╜+∩┐╜W∩┐╜mC∩┐╜∩┐╜∩┐╜{∩┐╜P∩┐╜∩┐╜Yg4∩┐╜∩┐╜/<∩┐╜p∩┐╜∩┐╜∩┐╜T(/∩┐╜∩┐╜∩┐╜!S∩┐╜∩┐╜∩┐╜"]∩┐╜∩┐╜∩┐╜b∩┐╜ST∩┐╜∩┐╜∩┐╜∩┐╜∩┐╜_.∩┐╜∩┐╜U∩┐╜∩┐╜µúç∩┐╜!a<∩┐╜∩┐╜o `

**Expected behavior** Expected token to be generated successfully and parsed.

**Your environment** * Version of the Ingress Controller: v1.12.0 * Version of Kubernetes: v1.18.10 * Kubernetes platform: Cloud Managed * Using NGINX or NGINX Plus: Nginx Plus

**Additional context** As per the example in Auth0, we need to add the following `proxy_set_header Accept-Encoding "gzip"; # this is required` when exchanging code for token. [https://auth0.com/docs/quickstart/webapp/nginx-plus/01-login](https://auth0.com/docs/quickstart/webapp/nginx-plus/01-login)

This took me a week of debugging, I should have checked the docs for Auth0!

I had to manually add the above directive in the running pod, which is bad. I must add it to the built image, but I am not sure where in the code it is located.

Aha! Link: https://nginx.aha.io/features/IC-274

**Comment by Binsabbar** [comment]
Create MR for #1894

**Comment by brianehlert** [comment]
Instead of a PR that enables this setting for all customers.
Would it be possible for you to modify this same setting locally, prior to building your NGINX Ingress Controller image, so that it would be enabled by default within your environment.
Essentially, modifying your local copy of the source and building your image from that.

**Comment by brianehlert** [comment]
This should be possible now given the additional OIDC customization that was implemented in 2023
