### ISSUE TITLE
NTLM and VirtualServer resource

### ISSUE THREAD

**Issue by Catskan** [nginxinc/kubernetes-ingress#1896]
Hi everyone,

I begin to use the VirtualServer resource to custom my K8S pods and I need to enable the ntlm; option.

My upstreams that used the ingress resource are ok, but how can I enable the ntlm option in my virtualserver resource ?

I'm using this doc : https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#contents to set all parameters needed, but I don't see how set the ntlm option.

Is it supported in VS resource ? 

Thanks in advance.

Regards,

**Comment by ciarams87** [comment]
Hi @Catskan 

PR for supporting adding the NTLM option in the Upstream of a VS resource has been merged. It will be available in the next release.

In the meantime, it is possible to set the option using a custom template, but please be aware that this will enable ntlm for all upsteams of all VirtualServers. You can see the docs on Custom Templates [here](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/custom-templates/).
