### ISSUE TITLE
Unclear why/when to use which nginx-based ingress controller

### ISSUE THREAD

**Issue by ankon** [nginxinc/kubernetes-ingress#190]
It would be really helpful to have a short statement as to why this controller is better/worse/more awesome/... compared to the nginx ingress controller in the kubernetes/ingress repository.

From reading through the README I only know that it is different, but nothing makes me actually want to even try it :)

**Comment by Sarga** [comment]
This is just nginx, without shitty patches :)

https://github.com/kubernetes/ingress/tree/master/controllers/nginx#nginx-notes

**Comment by pleshakov** [comment]
@ankon we'll document that. thx for the suggestion.

In a few words, below are the main differences:

- Implementation is different, including the templates used to generate NGINX config.
- Support for annotations and extensions. Both Ingress controllers use ConfigMap and annotations to provide extensions for Ingress. The kubernetes/ingress NGINX controller provides more [extensions](https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md). Extensions available in this controller -- https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/customization and https://github.com/nginxinc/kubernetes-ingress/tree/master/examples
- Third-party modules. This controller uses NGINX from DockerHub, as you can see in the [Dockerfile](https://github.com/nginxinc/kubernetes-ingress/blob/master/nginx-controller/Dockerfile). The kubernetes/ingress controller uses custom NGINX with [additional modules](https://github.com/kubernetes/ingress/blob/master/images/nginx-slim/build.sh).
- Support for NGINX Plus. This Ingress controller support NGINX Plus, which allows you to use NGINX Plus features (dynamic reconfiguration, JWT authentication, NGINX Plus extended status) and get support from NGINX Inc.
