### ISSUE TITLE
VirtualServer Operator structs have no omitempty tag

### ISSUE THREAD

**Issue by neathefourteen** [nginxinc/kubernetes-ingress#1905]
I want to use VirtualServer api defined in pkg/apis/configuration/v1/ in my own operator.
Because structures defined there have no omitempty tag I receive validation errors from kube-apiserver.

**Steps to reproduce the behavior:**
1. Import the latest kubernetes-ingress module and add v1 api to your own scheme
2. Try to create VirtualServer resource with reconciler client
3. See validation errors because unspecified properties are serialized to null JSON entries

**Expected behavior**
VirtualServer resource with minimum viable properties set created without problems

**Your environment**
* Version of the Ingress Controller - <=1.12
* Version of Kubernetes v1.18.12

**Example**
For example, if I create a VirtualServer with this upstream configuration, I get a lot of upstream validation errors for unspecified properties

`
upstream := v12.Upstream{
	Name:    appID,
	Service: service.Name,
	Port:    80,
}
`

`{"reconciler group": "conholdate.cloud", "reconciler kind": "Application", "name": "6sol13q2", "namespace": "conholdate-cloud-deploy", "error": "VirtualServer.k8s.nginx.org \"example-com-virtual-server\" is invalid: [spec.upstreams.keepalive: Invalid value: \"null\": spec.upstreams.keepalive in body must be of type integer: \"null\", spec.upstreams.subselector: Invalid value: \"null\": spec.upstreams.subselector in body must be of type object: \"null\", spec.upstreams.queue: Invalid value: \"null\": spec.upstreams.queue in body must be of type object: \"null\", spec.upstreams.buffers: Invalid value: \"null\": spec.upstreams.buffers in body must be of type object: \"null\", spec.upstreams.sessionCookie: Invalid value: \"null\": spec.upstreams.sessionCookie in body must be of type object: \"null\", spec.upstreams.healthCheck: Invalid value: \"null\": spec.upstreams.healthCheck in body must be of type object: \"null\", spec.upstreams.max-fails: Invalid value: \"null\": spec.upstreams.max-fails in body must be of type integer: \"null\", spec.upstreams.max-conns: Invalid value: \"null\": spec.upstreams.max-conns in body must be of type integer: \"null\", spec.upstreams.buffering: Invalid value: \"null\": spec.upstreams.buffering in body must be of type boolean: \"null\" ...]"}`

**Comment by juanpabloaj** [comment]
> I want to use VirtualServer api defined in pkg/apis/configuration/v1/ in my own operator. Because structures defined there have no omitempty tag I receive validation errors from kube-apiserver.
> 
> **Steps to reproduce the behavior:**
> 
> 1. Import the latest kubernetes-ingress module and add v1 api to your own scheme
> 2. Try to create VirtualServer resource with reconciler client
> 3. See validation errors because unspecified properties are serialized to null JSON entries
> 
> **Expected behavior** VirtualServer resource with minimum viable properties set created without problems
> 
> **Your environment**
> 
> * Version of the Ingress Controller - <=1.12
> * Version of Kubernetes v1.18.12
> 
> **Example** For example, if I create a VirtualServer with this upstream configuration, I get a lot of upstream validation errors for unspecified properties
> 
> `upstream := v12.Upstream{ Name: appID, Service: service.Name, Port: 80, }`
> 
> `{"reconciler group": "conholdate.cloud", "reconciler kind": "Application", "name": "6sol13q2", "namespace": "conholdate-cloud-deploy", "error": "VirtualServer.k8s.nginx.org \"example-com-virtual-server\" is invalid: [spec.upstreams.keepalive: Invalid value: \"null\": spec.upstreams.keepalive in body must be of type integer: \"null\", spec.upstreams.subselector: Invalid value: \"null\": spec.upstreams.subselector in body must be of type object: \"null\", spec.upstreams.queue: Invalid value: \"null\": spec.upstreams.queue in body must be of type object: \"null\", spec.upstreams.buffers: Invalid value: \"null\": spec.upstreams.buffers in body must be of type object: \"null\", spec.upstreams.sessionCookie: Invalid value: \"null\": spec.upstreams.sessionCookie in body must be of type object: \"null\", spec.upstreams.healthCheck: Invalid value: \"null\": spec.upstreams.healthCheck in body must be of type object: \"null\", spec.upstreams.max-fails: Invalid value: \"null\": spec.upstreams.max-fails in body must be of type integer: \"null\", spec.upstreams.max-conns: Invalid value: \"null\": spec.upstreams.max-conns in body must be of type integer: \"null\", spec.upstreams.buffering: Invalid value: \"null\": spec.upstreams.buffering in body must be of type boolean: \"null\" ...]"}`

Did you find any solution for that error?

I have got the same message.
