### ISSUE TITLE
Kubernetes v1.22 - Crash Loop after using alpine-edge Version

### ISSUE THREAD

**Issue by daniel-afo** [nginxinc/kubernetes-ingress#1906]
**Describe the bug**
Im using as suggested in issue  #1832 
the alpine-edge version but the nginx-ingress pod is also in this verison in crash-loop.

**Installation steps**
```
git clone https://github.com/nginxinc/kubernetes-ingress/
cd /home/kubernetes/kubernetes-ingress/deployments/daemon-set/
sed -i 's/1.12.0/alpine-edge/g' nginx-ingress.yaml
kubectl apply -f ~/kubernetes-ingress/deployments/common/ns-and-sa.yaml"
kubectl apply -f ~/kubernetes-ingress/deployments/rbac/rbac.yaml"
kubectl apply -f ~/kubernetes-ingress/deployments/common/default-server-secret.yaml
kubectl apply -f ~/kubernetes-ingress/deployments/common/nginx-config.yaml
kubectl apply -f ~/kubernetes-ingress/deployments/common/ingress-class.yaml
kubectl apply -f ~/kubernetes-ingress/deployments/daemon-set/nginx-ingress.yaml
```

**Failures**
`Error: failed to start container "nginx-ingress": Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "-nginx-configmaps=nginx-ingress/nginx-config": stat -nginx-configmaps=nginx-ingress/nginx-config: no such file or directory: unknown`

**Additional info**
The config map nginx-config is available under the namespace nginx-ingress with the following content:
`kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
  uid: ceb2236a-d187-4e15-aa4c-0e587b4a69a2
  resourceVersion: '321649'
  creationTimestamp: '2021-08-26T06:33:57Z'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","data":null,"kind":"ConfigMap","metadata":{"annotations":{},"name":"nginx-config","namespace":"nginx-ingress"}}
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: v1
      time: '2021-08-26T06:33:57Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}`

**Comment by dushanwijesinghe** [comment]
args:
          - -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
          - -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret
          **- -enable-custom-resources=false**
