### ISSUE TITLE
nginx plus fails since 1.0 - complaining missing upstream argument

### ISSUE THREAD

**Issue by nalston** [nginxinc/kubernetes-ingress#191]
Working fine with all releases prior to 0.9.0. I am using weave cni; nginx is running as a DS and using hostNetwork. I have ports 80, 443, and 8080 exposed.

Relevant portion of logs:
```
2017/09/20 15:00:41 [notice] 15#15: using the "epoll" event method
2017/09/20 15:00:41 [notice] 15#15: nginx/1.11.10 (nginx-plus-r12-p2)
2017/09/20 15:00:41 [notice] 15#15: built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2)
2017/09/20 15:00:41 [notice] 15#15: OS: Linux 3.10.0-514.21.2.el7.x86_64
2017/09/20 15:00:41 [notice] 15#15: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2017/09/20 15:00:41 [notice] 15#15: start worker processes
2017/09/20 15:00:41 [notice] 15#15: start worker process 16
2017/09/20 15:00:41 [notice] 15#15: start worker process 17
2017/09/20 15:00:41 [notice] 15#15: start worker process 18
2017/09/20 15:00:41 [notice] 15#15: start worker process 19
2017/09/20 15:00:41 [error] 19#19: *1 missing "upstream" argument, client: 127.0.0.1, server: , request: "GET /upstream_conf HTTP/1.1", host: "127.0.0.1:8080"
F0920 15:00:41.692495       1 main.go:126] Failed to create NginxAPIController: upstream_conf endpoint http://127.0.0.1:8080/upstream_conf is not accessible: expected 400 response, got 404
```

The source of the error, as best as i can tell, is `[error] 19#19: *1 missing "upstream" argument, client: 127.0.0.1, server: , request: "GET /upstream_conf HTTP/1.1", host: "127.0.0.1:8080"` . The issue is that I have always gotten this line in the logs, and it never caused the pods to fail

Previous behavior, prior to the recent release:
```
2017/09/08 20:39:48 [notice] 12#12: using the "epoll" event method
2017/09/08 20:39:48 [notice] 12#12: nginx/1.11.10 (nginx-plus-r12-p2)
2017/09/08 20:39:48 [notice] 12#12: built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2)
2017/09/08 20:39:48 [notice] 12#12: OS: Linux 3.10.0-514.21.2.el7.x86_64
2017/09/08 20:39:48 [notice] 12#12: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2017/09/08 20:39:48 [notice] 14#14: start worker processes
2017/09/08 20:39:48 [notice] 14#14: start worker process 15
2017/09/08 20:39:48 [notice] 14#14: start worker process 16
2017/09/08 20:39:48 [notice] 14#14: start worker process 17
2017/09/08 20:39:48 [notice] 14#14: start worker process 18
2017/09/08 20:39:48 [error] 15#15: *1 missing "upstream" argument, client: 127.0.0.1, server: , request: "GET /upstream_conf HTTP/1.1", host: "127.0.0.1:8080"
I0908 20:39:48.318131       1 controller.go:167] Adding endpoints: kubernetes
I0908 20:39:48.318147       1 controller.go:167] Adding endpoints: kube-controller-manager
I0908 20:39:48.318154       1 controller.go:167] Adding endpoints: kube-scheduler
I0908 20:39:48.318158       1 controller.go:167] Adding endpoints: kube-dns
```

- [DaemonSet is here](https://pastebin.com/X3EGTPpY)
- Outside of the changes to 'args', this daemonset is identical to working version using 0.8 release. 
- In the non working environments, if i revert the image to 0.8 build, everything works as expected

**Comment by pleshakov** [comment]
@nalston Please make sure that you are using [NGINX Plus R13](https://www.nginx.com/resources/admin-guide/nginx-plus-releases/)

**Comment by nalston** [comment]
@pleshakov I built the image using the existing 'DockerfileForPlus' . I never specified the release version of nginx. Is there a way to specify R13 ?

**Comment by pleshakov** [comment]
The layer with NGINX Plus might got cached. Could you try to build the image again,  make sure to use --no-cache option [here](https://github.com/nginxinc/kubernetes-ingress/blob/master/nginx-controller/Makefile#L35): `docker build --no-cache -f $(DOCKERFILE) -t $(PREFIX):$(TAG) .`

**Comment by nalston** [comment]
@pleshakov that worked thanks. I had previously been running 'make clean' before build, but i guess that's not enough. Thanks for your help!

**Comment by pleshakov** [comment]
@nalston thanks. We'll document the issue and add an option to the Makefile to disabling caching.
