### ISSUE TITLE
Isn't NGINX Ingress Controller naming confusing?

### ISSUE THREAD

**Issue by shurup** [nginxinc/kubernetes-ingress#1910]
_I am not associated with any of the projects discussed below. I am also not sure if that's the best place to present this crazy idea, so please let me know if I am completely wrong._

**Is your feature request related to a problem? Please describe.**
We have two different controllers — `ingress-nginx` from Kubernetes and `kubernetes-ingress` from NGINX — for years, and both are officially named as "NGINX Ingress Controller," which seems to bring some confusion. A [recent Reddit post](https://www.reddit.com/r/kubernetes/comments/pcexjt/nginx_ingress_controller_v100_is_released_it/) is another proof that it's not a fictional problem: many K8s users (especially, beginners) are really confused with that naming.

**Describe the solution you'd like**
Wouldn't it be reasonable to consider changing the official project name to make it more distinctive from NGINX Ingress Controller by the Kubernetes community? For example, it can be F5 Ingress Controller or similar. (I wouldn't dare to offer many options as it's definitely not my privilege to do so.) Changing the repo name would be also great, however, it's probably a bit less important. 

**Describe alternatives you've considered**
It might be rational to make this change on "the other side" as well (or at least to discuss with them). However, this issue was created here (not in the `kubernetes-ingress` repo) simply based on the fact the initial commit here is made on Mar/9/2016 and their first commit is dated Feb/8/2016. Not a huge difference of course, but still. Obviously, any other ideas to lessen the existing naming confusion are much appreciated.

**Additional context**
Again, I am not sure if this is the right place for such a discussion, however — to my huge surprise — I couldn't find any other public issues about this problem. Thus, it would be good to have it somewhere around for those who might think about it (and find your official opinion on it somewhat later).

Aha! Link: https://nginx.aha.io/features/IC-418

**Comment by adamdecaf** [comment]
I've used Kubernetes for years and get these projects confused pretty often. Distinct names would benefit the community.

**Comment by brianehlert** [comment]
At KubeCon Paris the Kubernetes Community ingress project revealed that it will be renaming and is taking suggestions.
https://x.com/IngressNGINX/status/1770901117443965124
