### ISSUE TITLE
Does the AWS marketplace offering metric RegisterUsage work at all?

### ISSUE THREAD

**Issue by Skarlso** [nginxinc/kubernetes-ingress#1916]
Hi!

You have this metering code in-place: https://github.com/nginxinc/kubernetes-ingress/blob/master/cmd/nginx-ingress/aws.go

I was wondering if this is used at all? nginx has an aws-marketplace offering. This code is supposed to report usage of that offering and thus enable billing.

However, the marketplace requires an IAM role to be able to use RegisterUsage and yet, this is no-where required when subscribing to or using the nginx ingress container offering. 

I was wondering how is that being done or where that requirement is being satisfied?

Thank you!

**Comment by brianehlert** [comment]
The IAM account is a requirement of AWS for any marketplace product that interacts with the AWS metering API.
AWS machine images track usage differently than containers.  They require that containers interact with the metering API and are not metered in any other way.

**Comment by brianehlert** [comment]
This is the root AWS document describing permissions:
https://docs.aws.amazon.com/marketplace/latest/userguide/iam-user-policy-for-aws-marketplace-actions.html

**Comment by Skarlso** [comment]
Yes. That's what I'm talking about. :) And the fact that there is no such requirement when you install the Kubernetes nginx container in the Marketplace. So where does it get created?

Are you saying that people who install this container: https://aws.amazon.com/marketplace/pp/prodview-fx3faxl7zqeau?sr=0-1&ref_=beagle&applicationId=AWSMPContessa are just supposed to know that they require that account and create it?

Which is fine, of course, but I'm just wondering if that shouldn't be part of the installation description or the requirement at least?
