### ISSUE TITLE
dns-udp can't find the listener

### ISSUE THREAD

**Issue by CaiNiaoHui** [nginxinc/kubernetes-ingress#1947]
**Describe the bug**

Use the yaml file under  examples-of-custome-resources/basic-tcp-udp  folder to deploy.
The status of  transport-server's dns-udp shows "Listener dns-udp donesn't exist"

**To Reproduce**
1.  use the dns yaml to create cm, deployment, service 
![deployment and service](https://user-images.githubusercontent.com/29849201/132665498-00890c7e-70cc-4940-a985-3832c589ca75.png)
![configmap](https://user-images.githubusercontent.com/29849201/132665873-a9a58fd9-cf20-4357-ac29-9061a38ffed1.png)
2. use the global-configuration.yaml to create nginx-configuration, and the global-configuration and pod I created are in the same namespace
![global-configuration](https://user-images.githubusercontent.com/29849201/132666730-f0950708-578e-4d58-8a0f-b24885360457.png)
3.  use the transport-server-udp.yaml to create dns-udp. But the transportServer's status shows refused to listen.
![dns-udp](https://user-images.githubusercontent.com/29849201/132667383-c895dce9-7c82-45d6-9600-c23dff702059.png)
![dns-udp-describe](https://user-images.githubusercontent.com/29849201/132667625-3a83dde5-fc59-4409-9ef2-86b24c6b9167.png)
![nginx-log](https://user-images.githubusercontent.com/29849201/132668857-80e0df8d-d4be-4bfe-9726-a1300dee7567.png)

**Expected behavior**
I hope TransportServer can successfully match with global configuration.

**Your environment**
* Version of the Ingress Controller - current version: v1.11.3
* Version of Kubernetes: v1.18.20
* Kubernetes platform: rancher v2.5.7
* Using NGINX Plus

**Comment by jasonwilliams14** [comment]
@CaiNiaoHui 
Can you check your deployment and verify you have specified your global configuration as part of the command line arguments?
https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/command-line-arguments/

Specifically, you want to look for the following line:
```
- -global-configuration=$(POD_NAMESPACE)/nginx-configuration
```
If that is not set, add that setting then redeploy the ingress as well as your transportserver resources (per our example)
Let us know how that goes.

**Comment by CaiNiaoHui** [comment]
@jasonwilliams14 
Thank you for your answer.
I find the question is my ingress controller DaemonSet don't add the configuration of "gloabl-configuration".
Then I add this setting, the transportServer can successfully match with global configuration.
