### ISSUE TITLE
Allow HTTP access when TLS is defined.

### ISSUE THREAD

**Issue by lseelenbinder** [nginxinc/kubernetes-ingress#198]
I have a service I'd like to expose over HTTP & HTTPS, but the only way to do that currently with this ingress controller is by defining a second ingress that doesn't have TLS defined on it. Is there a way to add a variable/annotation to prevent a universal HTTP -> HTTPS redirect when TLS is enabled?

I'm open to adding the patch, but I'd need some direction to get me started.

**Comment by pleshakov** [comment]
@lseelenbinder We don't have an annotation for that.

 Having the annotation makes perfect sense. There is a standard annotation `ingress.kubernetes.io/ssl-redirect` that takes a boolean argument, which is common among Ingress controllers. The default is `true`.

An example of how to add an annotation can be found here -- https://github.com/nginxinc/kubernetes-ingress/commit/714fd9945b1ff3a62c00951aa7bb9112da77ed2c There is a function [here](https://github.com/nginxinc/kubernetes-ingress/blob/master/nginx-controller/nginx/convert.go#L20) that parses boolean annotations/configmap keys.

**Comment by lseelenbinder** [comment]
Thank you, @pleshakov. I will see what I can do!
