### ISSUE TITLE
UDP Connection towards upstream how to tune the parameters ?

### ISSUE THREAD

**Issue by bnnk** [nginxinc/kubernetes-ingress#1981]
Hi All,

  We increase the worker_connections and when we increase the rate at which traffic is received we hit max worker_connection issues. Please note we are just receiving all the packets from a single node and single connection to our incoming node in K8s.

```
2021/09/18 01:06:38 [alert] 114#114: *88034 1024 worker_connections are not enough while connecting to upstream, udp client: 192.168.144.192, server: 0.0.0.0:3123, upstream: "192.168.93.78:9123", bytes from/to client:1000/0, bytes from/to upstream:0/0
192.168.144.192 [18/Sep/2021:01:06:38 +0000] UDP 500 0 1000 0.000 "-"
2021/09/18 01:06:39 [warn] 114#114: 1024 worker_connections are not enough, reusing connections
2021/09/18 01:06:39 [alert] 114#114: *88036 1024 worker_connections are not enough while connecting to upstream, udp client: 192.168.144.192, server: 0.0.0.0:3123, upstream: "192.168.93.78:9123", bytes from/to client:1000/0, bytes from/to upstream:0/0

```
Initial worker_connections was 1024 and we were not able to send more than 10pkt/sec then we set max connection to 100000 and now we are able to go till 1000 pkt/sec. Please note we are targeting 100k pkt/sec. Any help in fine tuning these parameters ?. Btw once we see above logs no new connections are accepted even at 1pkt/sec.

rgds
Bnnk

**Comment by workhorse2020** [comment]
@bnnk I suppose you are testing this scenario when the upstream pod is delaying the response is that right ?. If so even I am looking for a solution on the same.. Since this is a UDP packet and we can't afford to drop at ingress level we do have sessionParameters timeout set to 10secs but apparently at the rate of 10k packets per second we are seeing connections not getting accepted..

**Comment by pleshakov** [comment]
Hi @bnnk 

Could you share the TransportServer YAML resource?
Additionally, could share the full generated NGINX config? https://docs.nginx.com/nginx-ingress-controller/troubleshooting/troubleshoot-ingress-controller/#checking-the-generated-config

**Comment by bnnk** [comment]
```
    name: transporter-upstream-svc
    namespace: emf
  spec:
    action:
      pass: upstream-svc
    listener:
      name: upstream-svc
      protocol: UDP
    sessionParameters:
      timeout: 20s
    upstreamParameters:
      udpRequests: 1
      udpResponses: 0
    upstreams:
    - name: upstream-svc
      port: 22233
      service: agent-svc
```
Please find above transports config....

```
upstream ts_emf_transporter-func_upstream-svc {
    zone ts_emf_transporter-func_upstream-svc 256k;
    random two least_conn;
    server 192.168.144.245:9123 max_fails=1 fail_timeout=10s max_conns=0;
    server 192.168.39.186:9123 max_fails=1 fail_timeout=10s max_conns=0;
    server 192.168.93.104:9123 max_fails=1 fail_timeout=10s max_conns=0;
    server 192.168.93.113:9123 max_fails=1 fail_timeout=10s max_conns=0;
    server 192.168.93.91:9123 max_fails=1 fail_timeout=10s max_conns=0;
}

server {
    listen 3123 udp;
    proxy_requests 1;
    proxy_responses  0;
    proxy_pass ts_emf_transporter-func_upstream-svc;
    proxy_timeout 20s;
    proxy_connect_timeout 60s;
}
```
If there are 5 upstream pods we expect there should be only one connection with the source port fixed. But we are seeing for every packet its taking new connection. If we say requests as 100 then 100 packet goes to the same upstream pod. Please note we have same source ip/port sending nearly .1M pps.. Btw atleast if each upstream pods are associated with only a fixed number of ports even that should be fine..

rgds
bnnk

**Comment by jasonwilliams14** [comment]
@bnnk 
Can you please share with us the entire `nginx -T` output? There is helpful information that we would like to look at. Scrub your data as needed.
Thanks.
