### ISSUE TITLE
Upstream, for greater justice

### ISSUE THREAD

**Issue by bprashanth** [nginxinc/kubernetes-ingress#2]
Hi @pleshakov, I really like this project. There's an existing nginx controller in kubernetes: https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx-third-party
Would you be interested in upstreaming some of your improvements (espeically around nginx plus)?

**Comment by bprashanth** [comment]
The existing controller also hasn't caught up to using ingress.Spec.TLS yet

**Comment by pleshakov** [comment]
Hi @bprashanth ! Thanks!
Unfortunately, the controllers are mostly incompatible: the nginx-third-party uses the lua module for reconfiguration and these ones don't, so there is not much to upstream.
Once the controller for open-source NGINX controller becomes a bit more stable and have more complete features, I'd like to do PR it to the contrib project.

**Comment by bprashanth** [comment]
Ok, thanks. If you have the cycles the contrib nginx controller still needs Ingress.Spec.TLS integration and the community would welcome help :)

Ingress is most likely going GA in 1.3 and it would be nice to have a full fledged nginx controller by then

**Comment by bprashanth** [comment]
Forgot to follow up, @pleshakov the nginx controller in contrib/ is now 100% in go and we're probably going to split Ingress out from contrib into a sub-repo. It would be a net win IMO to maintain a single codebase, and people continue to ask how they can expose nginx features through the Ingress. If you're open to upstreaming, we can help.

**Comment by pleshakov** [comment]
@bprashanth Thanks for following up. We have to maintain a separate project because we support our Plus version.

**Comment by bprashanth** [comment]
Fwiw I'm not against supporting plus in the other repo :)
