### ISSUE TITLE
Support for regular expression in a path

### ISSUE THREAD

**Issue by pleshakov** [nginxinc/kubernetes-ingress#20]
Ingress Resource allows you to define a path as a  POSIX regex as defined by IEEE Std 1003.1.
NGINX Ingress Controller currently doesn't handle that.

**Comment by valorl** [comment]
Any comments on this ?

**Comment by pleshakov** [comment]
@valorl we aren't planning adding support for that any time soon. However, perhaps you can share your use case with examples of regular expressions? This will help us appropriately design this feature in the future. Additionally, it might be the case that we can find a workaround to support that use case today.
