### ISSUE TITLE
Terminate TLS with two secrets for the same host

### ISSUE THREAD

**Issue by brianehlert** [nginxinc/kubernetes-ingress#2022]
### Discussed in https://github.com/nginxinc/kubernetes-ingress/discussions/2019

<div type='discussions-op-text'>

<sup>Originally posted by **vudex** September 27, 2021</sup>
Hi. I'm trying to make my lab work, there are following prerequisites:

> Single host name test.example.com with two type of certs, RSA and EC based.
> With raw Nginx it is easily solvable with additional `ssl_certificate` and `ssl_certificate_key` directives, but I'm trying to make application work inside kubernetes with nginx ingress controller. 

The need of such separation is dictated by custom mobile devices, which dived in two groups - ones which work with rsa and ec algorithms and second that works only with EC algorithms.

First solution that comes in mind is to just terminate tls before kubernetes cluster with loadbalancer, but I'm curious is there any way to achieve this with ingress controller itself.

</div>

Aha! Link: https://nginx.aha.io/features/IC-302

**Comment by shaun-nx** [comment]
Closing this issue as the original discussion was also closed.
