### ISSUE TITLE
Startup time?

### ISSUE THREAD

**Issue by cu12** [nginxinc/kubernetes-ingress#203]
I started to experiment with your controller, although since I have thousands of ingresses in my setup, startup time takes enormous amount of time as it generates the configs one-by-one. 

My concern is mainly that if I'd like to update the controller to a new version, as `/nginx-health` will report `healthy` during a `RollingUpdate` therefore go live, even tho' only a portion of my ingresses will actually able to respond to requests.

for example
`I1012 15:48:34.960383` First log entry
`I1012 16:30:44.097721` Only finished with `1477` ingresses of  `3962` ingresses

**Comment by pleshakov** [comment]
@cu12 
To help investigate the issue, could you describe how your Ingress resources look like:

- How many hosts and services does each Ingress resource have?
- Do you use SSL termination? Does each Ingress resource have its own certificate and key or they are shared among Ingress resources?

Also, how do you expose the Ingress controller container? Do you have another load balancer in front of it?
