### ISSUE TITLE
Broken url in the README made it hard to compare both projects

### ISSUE THREAD

**Issue by mimusica** [nginxinc/kubernetes-ingress#2033]
https://github.com/nginxinc/kubernetes-ingress/blob/788cbd560f02b1e06cc7d6302296fa0263070554/README.md#L10

[this doc](https://docs.nginx.com/nginx-ingress-controller/intro/nginx-ingress-controllers) has been (re)moved -> http 404

**Comment by lucacome** [comment]
Closing this. The link is now working, thanks everybody!
