### ISSUE TITLE
nginxdemo/nginx-ingress:1.0.0 start error on my k8s cluster

### ISSUE THREAD

**Issue by brianlixw** [nginxinc/kubernetes-ingress#206]
I followed the example https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/complete-example, but after I run the command "$ kubectl create -f nginx-ingress-rc.yaml", I see the pod crushed with the following error:
I1028 12:28:43.031084       1 nginx.go:324] executing nginx -t
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2017/10/28 12:28:43 [emerg] 29#29: open() "/var/log/nginx/error.log" failed (13: Permission denied)
E1028 12:28:43.059355       1 main.go:151] nginx command exited with an error: exit status 1
E1028 12:28:43.059387       1 controller.go:699] Error when updating the default server Secret default/default-server-secret: Error when reloading NGINX when updating the default server Secret: Invalid nginx configuration detected, not reloading: Command nginx -t stdout: ""
stderr: "nginx: [alert] could not open error log file: open() \"/var/log/nginx/error.log\" failed (13: Permission denied)\nnginx: the configuration file /etc/nginx/nginx.conf syntax is ok\n2017/10/28 12:28:43 [emerg] 31#31: open() \"/var/log/nginx/error.log\" failed (13: Permission denied)\nnginx: configuration file /etc/nginx/nginx.conf test failed\n"
finished with error: exit status 1
I1028 12:28:43.059415       1 main.go:161] Shutting down the controller
I1028 12:28:43.059467       1 main.go:136] Waiting for the controller to exit...
I1028 12:28:43.059555       1 main.go:170] Exiting with a status: 1

My k8s cluster is running on the rancher v1.6.7 and the k8s version is v1.7.7. 
Can anyone give me some help about the issue, thanks.

**Comment by pleshakov** [comment]
@brianlixw 
There are two separate issues here. The Ingress controller requires an SSL cert and key for the default server. To fix it, please see https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/complete-example#1-deploy-the-ingress-controller

The second one is for some reason NGINX cannot open the error log file `/var/log/nginx/error.log"`. Does you k8s environment enforce any restrictions on pods?
