### ISSUE TITLE
What is the main difference between this project and ingress-nginx?

### ISSUE THREAD

**Issue by warmchang** [nginxinc/kubernetes-ingress#207]
Hi, 
For community free version of nginx, what is the main difference between this project and [ingress-nginx](https://github.com/kubernetes/ingress-nginx)?
Thanks!

**Comment by pleshakov** [comment]
@warmchang please see https://github.com/nginxinc/kubernetes-ingress/issues/190

**Comment by warmchang** [comment]
@pleshakov thank you for your reply.
