### ISSUE TITLE
AppProtect function not work

### ISSUE THREAD

**Issue by Wonderingkaho** [nginxinc/kubernetes-ingress#2103]
**Describe the bug**
I'm having an issue trying to enable appprotect.

**To Reproduce**
```
  ## Support for App Protect
  appprotect:
    ## Enable the App Protect module in the Ingress Controller.
    enable: true

  ## Enable the custom resources.
  enableCustomResources: true
```

**Expected behavior**
```
[root@master1 ~]# kubectl logs -n ingress-nginx-plus   pod/nginx-plus-ingress-nc4dj
I1018 04:18:01.647935       1 main.go:195] Starting NGINX Ingress controller Version=v2.0.2-SNAPSHOT-bb8ec62 GitCommit=bb8ec62f683d4477ccf6de925c3b5b6902c77160 Date=2021-10-18T02:40:06Z PlusFlag=true
I1018 04:18:01.660217       1 utils.go:163] Kubernetes version: 1.21.5
I1018 04:18:01.665140       1 main.go:397] Using nginx version: nginx/1.21.3 (nginx-plus-r25)
I1018 04:18:01.668937       1 manager.go:465] Starting AppProtect Agent
F1018 04:18:01.669166       1 manager.go:469] Failed to start AppProtect Agent: fork/exec /opt/app_protect/bin/bd_agent: no such file or directory
```

**Your environment**
* Version of the Ingress Controller : helm.sh/chart: nginx-ingress-0.11.2
* Version of Kubernetes : v1.21.5
* Kubernetes platform : Self deploy
* Using NGINX or NGINX Plus : NGINX Plus

**Additional context**
`
F1018 04:18:01.669166       1 manager.go:469] Failed to start AppProtect Agent: fork/exec /opt/app_protect/bin/bd_agent: no such file or directory
`

**Comment by lucacome** [comment]
Hi @Wonderingkaho 

Sorry, I missed that you were using helm in your first message. 

The error you're seeing usually means that you have App Protect enabled with an image that doesn't have it installed, can you double-check that you built/pulled the right Docker image?

You can do something like this with your current image to get the info
```
docker inspect --format '{{ json .Config.Labels }}' <docker image> | jq
```
