### ISSUE TITLE
Make nginx.tmpl support dynamic modules

### ISSUE THREAD

**Issue by kongdewen** [nginxinc/kubernetes-ingress#212]
Any chance to make it happen?

**Comment by pleshakov** [comment]
@kongdewen to support a dynamic module, you need build your own image of the Ingress controller with some changes in the following files:
- Dockerfile -  install/include the module binary 
- nginx.tmpl - load the module binary using the `load_module` directive.

Additionally, to configure the module it might be necessary to further change `nginx.tmpl` or `nginx.ingress.tmpl` files. Alternatively, you can use the `snippets` annotations and the config map key. See https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/customization

**Comment by kongdewen** [comment]
Thanks @pleshakov. Yea, we can do this. our current thought is to stay with the upstream as much as we can, so for the future upgrade/maintenance, we can easily pull from upstream.  we already have http-snippets, server-snippets, location snippets, why don't we have some snippet also for core functionalities?

we would be happy to contribute here(making PRs such).

**Comment by pleshakov** [comment]
@kongdewen I see your point. It makes sense to have a ConfigMap key like `main-snippets` for inserting a custom snippet into the main context. I'd be happy to review the PR.

**Comment by kongdewen** [comment]
Thanks @pleshakov I made a PR. #213.
