### ISSUE TITLE
Passing Client Cert CN from proxy to backend service

### ISSUE THREAD

**Issue by RudyBone** [nginxinc/kubernetes-ingress#215]
I need to pass the client CN from an incoming cert through the ingress controller to backend service.  I tried adding the following to my ingress definition:

...
metadata:
   annotations: 
      nginx.org/location-snippets: |
         proxy_set_header X-ProxyUser-DN $ssl_client_s_dn

When I dump the headers on the backend the X-ProxyUser-DN header is not there

**Comment by pleshakov** [comment]
@RudyBone in your snippet `;` is missing at the end of the snippet. Could you check that the Ingress with this snippet was successfully applied?  To do that, you can run `kubectl describe ing <your-ingress>` and check the events sectiion -- you should see `AddedOrUpdated` event by `nginx-ingress-controller`

**Comment by RudyBone** [comment]
Thats just a typo, I can't cut and paste from my secure network to the public network.  I also tried $ssl_client_s_dn_legacy (didn't work) and $ssl_client_verify (I got NONE).  Do I need to add ssl_verify_client on; as a server-snippet?  How is it that I can access the controller with SSL but don't have to add the ssl_server_certificate/ss_server_key in the server-snippets?

**Comment by RudyBone** [comment]
Got it, your hint to do subscribe on the ingress helped me figure things out, I was expecting to see more information in the controller's log rather then in the ingress resource.  I need to set ssl_verify_client on; and ssl_client_certificate
