### ISSUE TITLE
Can not start ingress controller following complete-demo steps.

### ISSUE THREAD

**Issue by frjaraur** [nginxinc/kubernetes-ingress#217]
Can not start ingress controller following complete-demo steps.
Have tried many changes but I always get errors related to be unable to access secrets namespace although it is there
NAME                    TYPE                                  DATA      AGE
default-server-secret   Opaque                                2         31m

Error on ingress-controller pod is the following:

F1211 19:57:09.075147       1 main.go:101] Error when getting default/default-server-secret: secrets "default-server-secret" is forbidden: User "system:serviceaccount:default:default" cannot get secrets in the namespace "default"

I am using k8 1.8 with calico.
What else can I review?
Thanks,
Javier R.

**Comment by pleshakov** [comment]
@frjaraur 
are you using RBAC? please see [this](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/rbac) example about RBAC and the Ingress controller.

**Comment by frjaraur** [comment]
Thanks a lot, You were right, but I hadn't enabled using --authorization-mode=RBAC. I think it is now enabled by default.
Thanks.

**Comment by rayfoss** [comment]
```
$ kubectl apply -f rbac/rbac.yaml
clusterrolebinding "nginx-ingress" configured
Error from server (Forbidden): error when creating "rbac/rbac.yaml": clusterroles.rbac.authorization.k8s.io "nginx-ingress" is forbidden: attempt to grant extra privileges:
```

Strange on GCE I somehow don't have cluster admin privs... huh
