### ISSUE TITLE
Request for pod affinity and session cookie annotations

### ISSUE THREAD

**Issue by amoonakal** [nginxinc/kubernetes-ingress#2191]
**Is your feature request related to a problem? Please describe.**
We are currently looking at moving from https://github.com/kubernetes/ingress-nginx to https://github.com/nginxinc. The reason we moved to https://github.com/kubernetes/ingress-nginx was there was no support for pod affinity and session cookie in the nginx opensource.

**Describe the solution you'd like**
Is there a plan to introduce pod affinity and session cookies in the open source annotations

**Describe alternatives you've considered**
Is there a plan to introduce pod affinity and session cookies in the open source annotations

**Additional context**
Is there an alternate way or approach which can be used to achieve pod affinity and session cookies with https://github.com/nginxinc

**Comment by amoonakal** [comment]
Can some one pls look into this and let us know the roadmap

**Comment by jasonwilliams14** [comment]
@amoonakal the session persistence functionality is only available in NGINX Plus:

https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/#enabling-session-persistence

You can customize your pod deployment and use pod affinity today, but not for session cookies. That is only for NGINX Plus.
Just update the spec section and use affinity/anti-affinity requirements as needed.

Hope that helps.
