### ISSUE TITLE
Doc: nginx-ingress daemonset requires k8s network CNI support `hostPort` and configured properly

### ISSUE THREAD

**Issue by vincentmli** [nginxinc/kubernetes-ingress#2208]
**Describe the bug**

following steps in 
https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests 
after `kubectl apply -f daemon-set/nginx-ingress.yaml` 

```
# kubectl get no -o wide
NAME                STATUS   ROLES                  AGE     VERSION        INTERNAL-IP     EXTERNAL-IP   OS-IMAGE           KERNEL-VERSION          CONTAINER-RUNTIME
k8s-cilium-master   Ready    control-plane,master   4d14h   v1.22.3+k3s1   10.169.72.127   <none>        Ubuntu 18.04 LTS   5.12.0-051200-generic   containerd://1.5.7-k3s2
```
telnet node ip port 80 failed

```
[root@centos-dev ~]# telnet 10.169.72.127 80
Trying 10.169.72.127...
telnet: connect to address 10.169.72.127: Connection refused

```
the nginx-ingress pod is running, but not listening on node port 80/443

```
root@k8s-cilium-master:/home/vincent/kubernetes-ingress/deployments# kubectl get pods --namespace=nginx-ingress -o wide
NAME                  READY   STATUS    RESTARTS   AGE   IP           NODE                NOMINATED NODE   READINESS GATES
nginx-ingress-ddrzr   1/1     Running   0          15m   10.0.0.228   k8s-cilium-master   <none>           <none>
```
The documents says daemonset port 80/443 should be mapped to node port 80/443
"
4. Get Access to the Ingress Controller
If you created a daemonset, ports 80 and 443 of the Ingress controller container are mapped to the same ports of the node where the container is running. To access the Ingress controller, use those ports and an IP address of any node of the cluster where the Ingress controller is running.
"

am I miss anything?

**To Reproduce**
1. git clone  https://github.com/f5devcentral/f5-cilium.git
2. cd k3s and run ./k3s.sh -n "your node ip"
3. follow https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests

**Expected behavior**

expect nginx-ingress listening on node  80/443 to match the documents description 

**Your environment**
* Version of the Ingress Controller - release version or a specific commit
nginx-ingress 2.0.3
* Version of Kubernetes

k3s v1.22.3+k3s1 

* Kubernetes platform (e.g. Mini-kube or GCP)

standalone single k3s node cluster

* Using NGINX or NGINX Plus

```
kubectl exec -it nginx-ingress-ddrzr -n nginx-ingress -- nginx -v
nginx version: nginx/1.21.3

```

**Comment by brianehlert** [comment]
nginx -T will show us what configurations are applied to Ingress.
If Ingress is installed but not configured, no traffic will flow as there is no where to send traffic.

Also, what is in the Ingress logs?

**Comment by vincentmli** [comment]
I suspect I am running k3s + cilium CNI might be causing this, I will run k3s + flannel CNI to confirm

**Comment by vincentmli** [comment]
yep, my cilium CNI had kube-proxy disabled, thus no iptables rules setup to map the nginx-ingress container port 80/443 on host node, k3s + flannel works and has the proper iptables rules setup 

```
root@k8s-cilium-master:/home/vincent/kubernetes-ingress/deployments# kubectl get pods --namespace=nginx-ingress -o wide
NAME                  READY   STATUS    RESTARTS   AGE   IP          NODE                NOMINATED NODE   READINESS GATES
nginx-ingress-hsbp7   1/1     Running   0          14s   10.42.0.5   k8s-cilium-master   <none>           <none>
root@k8s-cilium-master:/home/vincent/kubernetes-ingress/deployments# iptables-save | grep 80
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
-A CNI-DN-998786f6b2e02de6c49cc -s 10.42.0.0/24 -p tcp -m tcp --dport 80 -j CNI-HOSTPORT-SETMARK
-A CNI-DN-998786f6b2e02de6c49cc -s 127.0.0.1/32 -p tcp -m tcp --dport 80 -j CNI-HOSTPORT-SETMARK
-A CNI-DN-998786f6b2e02de6c49cc -p tcp -m tcp --dport 80 -j DNAT --to-destination 10.42.0.5:80
-A CNI-HOSTPORT-DNAT -p tcp -m comment --comment "dnat name: \"cbr0\" id: \"d96bd6f61da79472cf697fefbe12e53d325b7461b194ea3de64ff325dc4df3e6\"" -m multiport --dports 80,443 -j CNI-DN-998786f6b2e02de6c49cc
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
```
I guess the nginx-ingress documents could add something like Kubernetes clusters that uses kube-proxy/iptables rules for daemonset container port mapping

**Comment by vincentmli** [comment]
cilium actually support `hostPort` https://docs.cilium.io/en/v1.9/gettingstarted/kubeproxy-free/#kubeproxyfree-hostport, I got it working with  cilium `kube-proxy-replacement:  "strict"`,`kube-proxy-replacement:  "partial"` does not work. I think probably the nginx-ingress documents should mention that nginx-ingress daemonset could run on kubernetes network CNI with `hostPort` support and configured properly
