### ISSUE TITLE
Shift automountServiceAccountToken to deployment spec, rather than serviceAccount spec

### ISSUE THREAD

**Issue by AndrewNiven1** [nginxinc/kubernetes-ingress#2219]
**Is your feature request related to a problem? Please describe.**
The ServiceAccount created for the controller sets `automountServiceAccountToken: true` by default. We have a security requirement that no ServiceAccounts have `automountServiceAccountToken: true`. If we set this setting to false in the SA, the ingress-controller pods fail to deploy as they cannot mount the SA token.

**Describe the solution you'd like**
I would like to be able to set `automountServiceAccountToken: true` at the pod level, so that we can set it to false at the SA level and override it at the pod level. This would require adding this line to `controller-deployment.yaml`, with a corresponding input in values.yaml to control it. 

**Describe alternatives you've considered**
n.a.

**Additional context**
I haven't investigated the SA used by the defaultBackend, as we do not use the defaultBackend, but I would expect to make the same enhancement to it for consistency.

**Comment by pleshakov** [comment]
Hi @AndrewNiven1  looks like you're using this project https://github.com/kubernetes/ingress-nginx Please create an issue in that repo.

**Comment by AndrewNiven1** [comment]
Oops, sorry about that - thanks!
