### ISSUE TITLE
Single Service:PORT that handles some REST and some WEBSOCKET calls

### ISSUE THREAD

**Issue by RudyBone** [nginxinc/kubernetes-ingress#222]
I have a Web App that has 2 HTTPS REST paths: /myspo/rest/api and /myspo/rest/logging and 2 WebSocket paths: /myspo/rest/exec and /myspo/rest/logs; all 4 are handled on the same port.  What should my Ingress configuration look like?

**Comment by pleshakov** [comment]
You need to have four paths in your Ingress rule. Additionally, to enable WebSockets, use the web sockets annotation -- https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/websocket

**Comment by RudyBone** [comment]
Okay, but all 4 cases are handled by the same service, so what is the effect of registering this single service as a websocket service when it will also be used as an https rest service for 2 of the paths

**Comment by pleshakov** [comment]
if you configure keepalive connections using `nginx.org/keepalive` or `keepalive`, for non-websockets paths keepalive connections will be disabled. If you would like to use keepalive connections, consider creating an additional Kubernetes Service which refers to the same pods and  don't enable websockets for that service.

**Comment by RudyBone** [comment]
Okay, I'm not really getting that but I have an slightly different twist to add to the problem concerning what happens when 1 hostpath is a substring of another. Let me explain, I have a web ui service with the hostpath /myspo/ui/ . This path maps to the apps index.html page, and is also the starting path for HTTP Ajax calls from the apps javascript back to the app controller at /myspo/ui/api.   The app also makes 2 websocket calls from the browser to /myspo/ui/log and /myspo/ui/exec.  All of these calls can go through the same service on the same port.  Can you provide me an example of what my ingress configuration should look like?  Again, 1 service, handling both HTTPS and WebSockets but with the added twist that the HTTPS hostpath is a subpath of the WebSockets path.

**Comment by pleshakov** [comment]
@RudyBone 
If you have multiple paths where one path is subpath of another, when handling an HTTP request the most specific path always win. For example, if you have a path `/one` and also `/one/two` and you make a request for `/one/two`, it will be handled by the `/one/two` path.

In your case, you can either have one path `path: /myspo/ui/` or 3 paths. Both approaches should work.
