### ISSUE TITLE
Globally enable websockets nginx.org/websocket-services and not per service

### ISSUE THREAD

**Issue by strus38** [nginxinc/kubernetes-ingress#2220]
**Describe the bug**
Is there a way to enable globally the websockets?
I have an app which creates/delete dynamically the ingresses and has not been made for nginx.org, has such, I need  an easy way to authorize nginx.org/websocket-services but for all ingresses in a namespace.
If not, I would have to create a not simple mutation webhook to find the name of the service used and add the annotation which is a pain.

Thanks

Aha! Link: https://nginx.aha.io/features/IC-415

**Comment by pleshakov** [comment]
Hi @strus38 

For Ingresses resources, it is not possible to enable websockets without using annotations.
However, for VirtualServer resources, web sockets are enabled automatically -- https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/  

It should be possible to remove the websockets annotation from Ingress resources and enable websockets automatically, but this needs to be added an enhancement.

**Comment by strus38** [comment]
Well, it was for an application which dynamically creates/delete ingresses
which need websockets, but at the end, the app owner fixed their part to
allow dynamic annotations, so I am happy! You can close this issue. Thanks!

Le lun. 14 févr. 2022 à 19:06, Brian Ehlert ***@***.***> a
écrit :
