### ISSUE TITLE
Server-Side Apply Managed Field Claim Conflicts with other automations

### ISSUE THREAD

**Issue by Luwdo** [nginxinc/kubernetes-ingress#2231]
In my usage of the controller I have two other automations that make adjustments to CRD VirtualServer resources within my cluster.

Terraform for none dynamic ingresses that don't change often and a typescript application that manages more dynamic VirtualServer resources.

When updating a simple grafana ingress that was originally created with Terraform, I altered the referenced policy name on the VirtualServer and came across the following error:

![image](https://user-images.githubusercontent.com/9387842/144081307-d6d2c910-8226-4796-bf2c-3b0cf65f8a66.png)

This was odd because I nor any of my automations had not made any modifications to this VirtualServer between runs of terraform.

I found that the cause was that the ingress controller was claiming .spec.routes as part of the fields that its managing and because I was using Server-Side apply it was showing that I was gonna change a field another manager had claimed.

```
  managedFields:
    - apiVersion: k8s.nginx.org/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            f:name: {}
        f:spec:
          f:host: {}
          f:ingressClassName: {}
      manager: Terraform
      operation: Apply
      time: '2021-11-29T22:38:54Z'
    - apiVersion: k8s.nginx.org/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:http-snippets: {}
          f:policies: {}
          f:routes: {}
          f:server-snippets: {}
          f:tls: {}
          f:upstreams: {}
        f:status:
          .: {}
          f:externalEndpoints: {}
          f:message: {}
          f:reason: {}
          f:state: {}
      manager: nginx-ingress
      operation: Update
      time: '2021-11-29T22:38:54Z'
```

To resolve I updated my terraform to force resolve by overriding: https://kubernetes.io/docs/reference/using-api/server-side-apply/#conflicts

What this does is it will claim the routes field as managed by terraform, update the VirtualServer resource then the nginx-ingress will take it back when it processes the change.

Is there a case where the nginx-ingress controller will modify routes? There is an option in Server-Side apply to become a "Shared Manager" which means the nginx-ingress controller cares about the values but does not modify.

I would expect the nginx-ingress controller to not claim management of fields it doesn't intend to change. Perhaps this is expected behavior if so, would it be expected that updates to VirtualServers always override?

**Environment**
Ingress controller helm chart version: 0.7.1
AWS EKS running Kubernetes: 1.19
Using NGINX

**Comment by brianehlert** [comment]
kubernetes-ingress does update the resources.  But only to update the object status.   It does not modify the body or properties of the resources.
The permissions that kubernetes-ingress requires is covered in the rbac.yaml sample.

I might have missed a fine detail you were trying to articulate.

**Comment by Luwdo** [comment]
Yeah, ideally with Server-Side apply becoming the norm the ingress controller shouldn't be claiming management of those fields, which creates a conflict when external updates are made. 

According to the documentation on managedFields it should all be automatic and if a change isn't made by a specific manager it shouldn't assume that the ingress controller is the manager of those fields. The docs call out that manually editing managedFields is discouraged. Which lead me to thinking that a change was being made to the routes field causing the it to become a managed field of the nginx-ingress controller.

Its possible this is a problem Terraforms implementation of Server-Side apply but this is the first time I have seen a conflict and I am deploying and managing alot of different controllers with Terraform.
