### ISSUE TITLE
add pls underscores_in_headers to annotations

### ISSUE THREAD

**Issue by Nurlan199206** [nginxinc/kubernetes-ingress#2235]
how to set `underscores_in_headers on` ?  

I've not found related annotations here: https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations

**Comment by Nurlan199206** [comment]
also i tried to use custom annotations: it's not works...

![image](https://user-images.githubusercontent.com/22808731/144430805-71e058a2-8e82-4c24-8220-2e6c5be82251.png)

![image](https://user-images.githubusercontent.com/22808731/144430872-b78706d7-469d-4986-a734-8c3a9c937275.png)

![image](https://user-images.githubusercontent.com/22808731/144431042-b7e1d036-7c23-40f0-9f1d-4de2bd2330b4.png)

**Comment by jasonwilliams14** [comment]
@Nurlan199206 Easiest way to do this is to add into your configmap and use snippets.
like so:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  http-snippets: |
    underscores_in_headers on;
```

**Comment by Nurlan199206** [comment]
@jasonwilliams14 thank you! it's works.
