### ISSUE TITLE
Openshift Ingress and Router working together

### ISSUE THREAD

**Issue by MichalDuma** [nginxinc/kubernetes-ingress#224]
There is information how to set up an Ingress on Openshift [https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/openshift](url). First step is to disable Router in Openshift. Is there any possibility to have both Ingress and Router working together?
My goal is to have router and ingress working together - it could be on different External IP addresses. I was following this document [https://docs.openshift.com/container-platform/3.3/admin_guide/tcp_ingress_external_ports.html](url) to set up ingress on different IP address but services are working on high ports (above 30000) instead of default ports (e.g. 80).
Do you have any advices how to do it?

Michal

**Comment by pleshakov** [comment]
You can deploy the Ingress controller on a different node(s), where the router is not running. How to run the Ingress controller on specific nodes is described here -- https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/daemon-set -- at the bottom.

**Comment by MichalDuma** [comment]
Thank you for answer. Definitely I'll try this solution.

Michal
