### ISSUE TITLE
Force SSL client auth onto Ingress Controller 

### ISSUE THREAD

**Issue by prys** [nginxinc/kubernetes-ingress#225]
From the documentation I don't see any way to customise nginx to request a client cert - i.e. to enforce 2-way SSL onto the ingress controller?

**Comment by RudyBone** [comment]
ok, I needed to do this myself.  You need to add the following server-snippets to your Ingress definition

annotations:
   nginx.org/server-snippets: |
      ssl_verify_client on;
      ssl_client_certificate <location of trust cert in the controller container>

Also, you might have to set ssl_verify_depth to something other than its default of 1 depending on the number of signers of your client certs.  I set it to 10 just to be safe.

**Comment by pleshakov** [comment]
thanks for providing the snippet @RudyBone 
in this case, a file with trusted CA certificates for the `ssl_client_certificate` must be mounted on the file system.

**Comment by prys** [comment]
Good stuff - as per the annotation above along with a configmap to mount the ca cert in the ingress pod this is all working.
thanks @RudyBone @pleshakov for the assistance.
