### ISSUE TITLE
Can't turn proxy_buffering off;

### ISSUE THREAD

**Issue by RudyBone** [nginxinc/kubernetes-ingress#227]
When I set proxy_buffering off; in the Ingress location snippets I get an error when the Ingress is deployed saying that the "proxy_buffering" directive is duplicate in /etc/nginx/conf.d/my.conf.  I can move the directive to the servers snippet section and I get no errors in the Ingress BUT each location section in the generated conf file still has a proxy_buffering on; entry

**Comment by RudyBone** [comment]
Never mind, found a work around set X-Accel-Buffering to 'no' in response header

**Comment by pleshakov** [comment]
@RudyBone you can use `nginx.org/proxy-buffering` annotation or `proxy-buffering` configmap key to control buffering. Please see https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/customization
