### ISSUE TITLE
nginx ingress content based routing

### ISSUE THREAD

**Issue by khaaliid** [nginxinc/kubernetes-ingress#2308]
**Describe the bug**
I am not able to do the routing based on the request body ($request_body).

**To Reproduce**
1- follow the [installation guide](https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/) : 
2- run the [advanced routing example](https://github.com/nginxinc/kubernetes-ingress/tree/v2.0.3/examples-of-custom-resources/advanced-routing)
3- append the below routing section at the bottom of [cafe-virtual-server.yaml](https://github.com/nginxinc/kubernetes-ingress/blob/v2.0.3/examples-of-custom-resources/advanced-routing/cafe-virtual-server.yaml) file

  - path: /mytest
    matches:
      - conditions:
        - variable: $request_body
          value: ~*abc*
        action:
          proxy:
            upstream: tea-post
            rewritePath: /api/test
    action:
      pass: coffee-v1

4- try to call this route by any rest client i.e. curl:

curl -X POST -H "Content-Type: text/plain"  -d 'abc' -k -vvv https://test.company.com/testx

5- unfortunately the route is not triggered.
 
**Expected behavior**
The route to be called and the URL to be rewritten  (/api/test)

**Your environment**
* Version of the Ingress Controller : nginx/nginx-ingress:2.0.3
* Version of Kubernetes : 1.20
* Kubernetes platform : 3 nodes kubernetes cluster (Tanzu)
* Using NGINX 

**Additional context**
I have enabled the debug mode and updated the log-format to print the $request & $request_body but these variables printed as empty, PFB.

_config map log-format property update:_

log-format: upstreaminfo $remote_addr xx-xx $remote_user [$time_local]\n $request $request_body $status $body_bytes_sent \n $http_referer $http_user_agent \n

_Logs output :_

2021/12/29 05:22:56 [debug] 90#90: *928 http log handler upstreaminfo 10.54.192.1 xx-xx - [29/Dec/2021:05:22:56 +0000] POST /testx HTTP/1.1 - 404 108 - curl/7.29.0

**Comment by jasonwilliams14** [comment]
@khaaliid 
what does the following output show?
```
kubectl get vs -A
```
Followed by:
```
kubectl describe vs <name_of_vs>
```

**Comment by khaaliid** [comment]
@jasonwilliams14 

Actually I have modified the Manifest file to fit my actual use cases and I removed the tea/coffee endpoints. all other endpoints mentioned below yaml are working fine only the one with the "$request_body".

```
$ kubectl get vs -A
NAMESPACE       NAME             STATE   HOST                        IP    PORTS   AGE
tkgdev   test-routes-vs   Valid   myapp2stg.corp.ae                 17d


$ kubectl describe vs test-routes-vs
Name:         test-routes-vs
Namespace:    tkgdev
Labels:       <none>
Annotations:  <none>
API Version:  k8s.nginx.org/v1
Kind:         VirtualServer
Metadata:
  Creation Timestamp:  2021-12-18T05:02:07Z
  Generation:          50
  Managed Fields:
    API Version:  k8s.nginx.org/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:http-snippets:
        f:ingressClassName:
        f:policies:
        f:server-snippets:
        f:tls:
          f:redirect:
      f:status:
        .:
        f:externalEndpoints:
        f:message:
        f:reason:
        f:state:
    Manager:      nginx-ingress
    Operation:    Update
    Time:         2021-12-28T07:13:03Z
    API Version:  k8s.nginx.org/v1
	    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:host:
        f:routes:
        f:tls:
          .:
          f:secret:
        f:upstreams:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2021-12-29T11:59:29Z
  Resource Version:  51537128
  UID:               9c3ad6ca-9154-48f4-ba42-b934ef2db3eb
Spec:
  Host:  myapp2stg.corp.ae
  Routes:
    Action:
      Pass:  test-zipkin
    Path:    ~ ^/zipkin.*
    Action:
      Redirect:
        Code:  301
        URL:   https://myapp2stg.corp.ae/app/kibana
    Path:      =/app
    Action:
      Pass:  test-kibana
    Path:    ~ ^/app.*|^/bundles/app.*
    Action:
      Pass:  test-isv-service
    Path:    ~ ^/api/myapp.*
    Action:
	      Pass:  test-isv-service
    Path:    ~ ^/CloudSelect.*
    Action:
      Pass:  test-isv-service
    Matches:
      Action:
        Proxy:
          Rewrite Path:  /api/myapp/isv
          Upstream:      test-isv-service
      Conditions:
        Value:     ~*abc*
        Variable:  $request_body
    Path:          /testx
    Action:
      Pass:  test-bpm-webapp
    Path:    ~ ^/test-bpm.*
  Tls:
    Secret:  test-ingress-ssl-certificate
  Upstreams:
    Name:     test-isv-service
    Port:     8201
    Service:  test-isv-service
    Name:     test-zipkin
    Port:     9411
    Service:  test-zipkin
    Name:     test-kibana
    Port:     5601
    Service:  test-kibana
    Name:     test-bpm-webapp
    Port:     8200
    Service:  test-bpm-webapp
Status:
  External Endpoints:
    Ip:
    Ports:
  Message:  Configuration for tkgdev/test-routes-vs was added or updated
  Reason:   AddedOrUpdated
    State:    Valid
Events:     <none>
```
