### ISSUE TITLE
getting 404 error for all service behind ingress controller

### ISSUE THREAD

**Issue by shifali0102** [nginxinc/kubernetes-ingress#2374]
getting this when i describe my ingress resource:

Normal   AddedOrUpdated           17m (x7 over 17m)  nginx-ingress-controller  Configuration for development/dev was added or updated
  Warning  AddedOrUpdatedWithError  17m                nginx-ingress-controller  Configuration for development/dev was added or updated ; but was not applied: Error when updating config from ConfigMap: nginx reload failed: Command /usr/sbin/nginx -s reload stdout: ""
stderr: "2022/01/20 08:07:11 [emerg] 19#19: \"proxy_busy_buffers_size\" must be less than the size of all \"proxy_buffers\" minus one buffer in /etc/nginx/nginx.conf:133\nnginx: [emerg] \"proxy_busy_buffers_size\" must be less than the size of all \"proxy_buffers\" minus one buffer in /etc/nginx/nginx.conf:133\n"
finished with error: exit status 1

everything was working fine . I restarted the controller deployment and now getting 404 for all services.

please help its urgent.

**Comment by pleshakov** [comment]
Hi @shifali0102 

Could you share the Ingress resource? Additionally, could you share the ConfigMap resource?
Specifically, this is to take a look at the values of the annotations/configmap keys related to `proxy_busy_buffers_size`, `proxy_buffers` and `proxy_buffer_size` directives. 

Note that this error `"proxy_busy_buffers_size" must be less than the size of all "proxy_buffers" minus one buffer` suggests to decrease the values of `proxy_busy_buffers_size` directive. See also https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_busy_buffers_size
