### ISSUE TITLE
Annotation to turn off gzip compression 

### ISSUE THREAD

**Issue by shifali0102** [nginxinc/kubernetes-ingress#2398]
I am unable to find a suitable annotation to turn off gzip compression to overcome the BREACH vulnerability.
https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/

**Comment by brianehlert** [comment]
In the template files it appears that gzip compression is commented out.
`#gzip  on;`

Are you seeing that it is enabled in your resulting nginx.conf?
