### ISSUE TITLE
Nginx-Ingress Controller not workking

### ISSUE THREAD

**Issue by rajeevpritraj** [nginxinc/kubernetes-ingress#2421]
**Environment** 
OS : CentOS Linux 7 (Core)
Kubernetes : v1.23.1
3 nodes (1 master, 2 workers).
Following steps as per "https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/"

**Getting error :** with option - -v=3  in deployment yaml file
I0211 11:28:57.495383       1 manager.go:279] Starting nginx
I0211 11:28:57.517007       1 verify.go:68] Starting poll for updated nginx config
I0211 11:28:57.517435       1 verify.go:72] Unable to fetch version: error getting client: Get "http://config-version/configVersion": dial unix /var/lib/nginx/nginx-config-version.sock: connect: no such file or directory

Added below lines in Deployment file
 # added 
        command:
         - /bin/sh
         - "-c"
         - "sleep 10m"
        imagePullPolicy: Always
      # end

Error: When checked the container, getting below error
[root@master deployments]# kubectl exec -it nginx-ingress-698759c6d5-rbvj6 -n nginx-ingress -- sh
$ cd etc/nginx
$ cd conf.d
$ ls -ls
ls: cannot access 'default.conf': No such file or directory
total 0
? ?????????? ? ? ? ?            ? default.conf

Any idea , what is the problem and how to fix it. Thanks.

**Comment by brianehlert** [comment]
Did you build your own image or use a pre-built image from one of the container repositories?
And did you set your version after cloning the repo?

You should not have had to add any commands it should run without modification.

**Comment by rajeevpritraj** [comment]
It was pre-built image downloaded from docker hub and yaml files from git hub (cloning the repository https://github.com/nginxinc/kubernetes-ingress.git) 
We have made no changes except adding below lines to investigate the issue as pod was crashing immediately after deployment.
 command:
     - /bin/sh
     - "-c"
     - "sleep 10m"
    imagePullPolicy: Always
  # end

**Comment by brianehlert** [comment]
Hi @tytsaitw 
Can you please start a new thread and provide logs?

This is a 2 year old thread and I am sure this issue has been resolved.

Please also see here: https://docs.nginx.com/nginx-ingress-controller/troubleshooting/troubleshoot-common/
