### ISSUE TITLE
Regex support in ingress resource

### ISSUE THREAD

**Issue by RavinderKumar1** [nginxinc/kubernetes-ingress#2428]
Nginx IC community version supports regex in ingress resource. https://kubernetes.github.io/ingress-nginx/user-guide/ingress-path-matching/

But, **Ingress with regex doesn't seem to be working with NGINX Plus IC** licensed version.

**Comment by brianehlert** [comment]
Thanks @RavinderKumar1 
This Ingress controller project supports different annotations and a set of CRDs.

For example, regex paths are available using the CRDs: 

- https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#virtualserverroute
- https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#virtualserverroutesubroute
