### ISSUE TITLE
Pb install

### ISSUE THREAD

**Issue by obeyler** [nginxinc/kubernetes-ingress#243]
Thanks to the documentation, I've tried to make install 
kubectl apply -f common/ns-and-sa.yaml
kubectl apply -f common/default-server-secret.yaml
kubectl apply -f deployment/nginx-ingress.yaml

the instance nginx-ingress always crashed 
I try to have last log 
kubectl logs --previous -n nginx-ingress nginx-ingress-7f5c8d467-4lrc7 

main.go:108] Error when getting nginx-ingress/default-server-secret: secrets "default-server-secret" is forbidden: User "system:serviceaccount:nginx-ingress:nginx-ingress" cannot get secrets in the namespace "nginx-ingress"

any idea about what is wrong ?

**Comment by maheshmahadevan** [comment]
Was this resolved ? What was the issue ? I am getting similar error. Please post the resolution

**Comment by pleshakov** [comment]
@maheshmahadevan this error is due to incorrect RBAC configuration. Please make sure you follow step 2 of the install doc https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/installation.md#2-configure-rbac

**Comment by maheshmahadevan** [comment]
@pleshakov Thanks.

**Comment by tsvetan-81** [comment]
thanks a lot
