### ISSUE TITLE
Not able to connect to web socket stream inside a k8s container behind nginx-ingress. 

### ISSUE THREAD

**Issue by OnlifeBuildDotNet** [nginxinc/kubernetes-ingress#2444]
**Describe the bug**
Not able to connect to web socket stream inside a k8s container behind nginx-ingress.   Getting this error.   This may not be a bug but wasnt sure where else I could ask this question.

Error: Unable to connect to the server with any of the available transports. (WebSockets failed: The server returned status code '200' when status code '101' was expected.) (ServerSentEvents failed: The transport is disabled by the client.) (LongPolling failed: The transport is disabled by the client.)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)

Inner Error: WebSockets failed: The server returned status code '200' when status code '101' was expected.

**To Reproduce**
We are using the yaml file below to deploy an app inside a k8s cluster.  THis app has a signalr hub that IS WORKING but the wss websocket is not.   Are we doing something wrong?

we are passing in the a number of variables into the below yaml.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: telephony-{{ENV}}
  labels: 
    app: telephony-{{ENV}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telephony-{{ENV}}
  template:
    metadata:
      labels:
        app: telephony-{{ENV}}
        name: telephony-{{ENV}}
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: telephony-{{ENV}}
        image: onlifehealth.azurecr.io/{{IMAGENAME}}
        imagePullPolicy: IfNotPresent
        env:
        - name: DOTNET_ENVIRONMENT
          value: "{{ENV}}"
        ports:
        - containerPort: 80
      restartPolicy: Always
      imagePullSecrets:
        - name: acr-secret

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: telephony-ingress-{{ENV}}
 annotations:
   kubernetes.io/ingress.class: nginx
   nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
   nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
   nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
spec:
  ingressClassName: nginx
  rules:
  - host: {{HOST}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: telephony-{{ENV}}
            port: 
              number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: telephony-{{ENV}}
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: telephony-{{ENV}}

**Expected behavior**

**Your environment**
Version if ingress controller is 1.11.3
Kubernetes version is 1.21.1
Kubernetes bare bones cluster running on centos 7

* Using NGINX or NGINX Plus
Using NGINX

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by OnlifeBuildDotNet** [comment]
[k8_telephony.txt](https://github.com/nginxinc/kubernetes-ingress/files/8099225/k8_telephony.txt)

**Comment by jasonwilliams14** [comment]
@OnlifeBuildDotNet hello there. 
You are currently using annotations for a different NGINX Ingress project:
```
nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
nginx.ingress.kubernetes.io/configuration-snippet: | 
```
Those will not work.
You will need to use our specific annotations are located here:
https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/

For example, you would need to use these:
```
nginx.org/proxy-read-timeout
nginx.org/proxy-send-timeout
```

For snippets, please look here:
https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/#snippets-and-custom-templates

HTH

**Comment by llyons** [comment]
Ok thanks for that.  Do we also need to use the annotation    nginx.org/websocket-services For these scenarios?

**Comment by jasonwilliams14** [comment]
@llyons If you are using `ingress` resource you will want to use:

```
nginx.org/websocket-services
```

If you use our CRDs, websockets is enabled automatically.

HTH

**Comment by llyons** [comment]
thanks I was able to figure this out with that additional info.  

the nginx.org/websocket-services  needs to actually point to the service that is a websocket service.

`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: telephony-ingress-{{ENV}}
 annotations:
   nginx.org/websocket-services: "telephony-{{ENV}}"
   nginx.org/proxy-read-timeout: "3600"
   nginx.org/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
  - host: {{HOST}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
             name: telephony-{{ENV}}
             port: 
              number: 80


---
apiVersion: v1
kind: Service
metadata:
  name: telephony-{{ENV}}
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: telephony-{{ENV}}`

**Comment by brianehlert** [comment]
> thanks I was able to figure this out with that additional info.
Closing issue.
