### ISSUE TITLE
TLS termination not working properly in ingress-controller pod

### ISSUE THREAD

**Issue by Ed87** [nginxinc/kubernetes-ingress#2451]
I have an issue with my ingress-nginx which I setup for my k0s cluster as per guidelines [here](https://docs.k0sproject.io/v1.22.2+k0s.1/examples/nginx-ingress/). I also have a thread for the full issue [here](https://stackoverflow.com/questions/71233140/504-gateway-timeout-error-on-kubernetes-ingress).

So far I have drilled down the issue to the ingress-controller pod with command  `ks logs ingress-nginx-controller-7f48b8-rgksh -n ingress-nginx` 

`I0224 11:31:17.128524 8 flags.go:211] "Watching for Ingress" class="nginx"
W0224 11:31:17.128603 8 flags.go:216] Ingresses with an empty class will also be processed by this Ingress controller
W0224 11:31:17.131557 8 client_config.go:614] Neither --kubeconfig nor --master was specified. Using the inClusterConfig. This might not work.
I0224 11:31:17.131942 8 main.go:241] "Creating API client" host="[https://10.96.0.1:443](https://10.96.0.1/)"
I0224 11:31:17.141484 8 main.go:285] "Running in Kubernetes cluster" major="1" minor="23" git="v1.23.1+k0s" state="clean" commit="b230d3e4b9d6bf4b731d96116a6643786e16ac3f" platform="linux/amd64"
I0224 11:31:17.740133 8 main.go:105] "SSL fake certificate created" file="/etc/ingress-controller/ssl/default-fake-certificate.pem"
I0224 11:31:17.744059 8 main.go:115] "Enabling new Ingress features available since Kubernetes v1.18"
W0224 11:31:17.745525 8 main.go:127] No IngressClass resource with name nginx found. Only annotation will be used.
I0224 11:31:17.769907 8 ssl.go:532] "loading tls certificate" path="/usr/local/certificates/cert" key="/usr/local/certificates/key"
I0224 11:31:17.804489 8 nginx.go:254] "Starting NGINX Ingress controller"
I0224 11:31:17.823579 8 event.go:282] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"ingress-nginx", Name:"ingress-nginx-controller", UID:"975b3e9e-44a7-47b9-a27e-b1599e350afe", APIVersion:"v1", ResourceVersion:"410202", FieldPath:""}): type: 'Normal' reason: 'CREATE' ConfigMap ingress-nginx/ingress-nginx-controller
E0224 11:31:18.911839 8 reflector.go:138] k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: the server could not find the requested resource
E0224 11:31:19.975277 8 reflector.go:138] k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: the server could not find the requested resource
E0224 11:31:22.297935 8 reflector.go:138] k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: the server could not find the requested resource
E0224 11:31:28.046173 8 reflector.go:138] k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: the server could not find the requested resource
E0224 11:31:37.387495 8 reflector.go:138] k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: the server could not find the requested resource
E0224 11:31:56.464155 8 reflector.go:138] k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: the server could not find the requested resource
I0224 11:32:15.692216 8 main.go:187] "Received SIGTERM, shutting down"
I0224 11:32:15.692261 8 nginx.go:372] "Shutting down controller queues"
E0224 11:32:15.692560 8 store.go:178] timed out waiting for caches to sync
I0224 11:32:15.692639 8 nginx.go:296] "Starting NGINX process"
I0224 11:32:15.692881 8 leaderelection.go:243] attempting to acquire leader lease ingress-nginx/ingress-controller-leader-nginx...
I0224 11:32:15.693633 8 queue.go:78] "queue has been shutdown, failed to enqueue" key="&ObjectMeta{Name:initial-sync,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[]OwnerReference{},Finalizers:[],ClusterName:,ManagedFields:[]ManagedFieldsEntry{},}"
I0224 11:32:15.693672 8 nginx.go:316] "Starting validation webhook" address=":8443" certPath="/usr/local/certificates/cert" keyPath="/usr/local/certificates/key"
I0224 11:32:15.714989 8 status.go:204] "POD is not ready" pod="ingress-nginx/ingress-nginx-controller-7f48b8-rgksh" node="fbcdcesdn02"
I0224 11:32:15.716482 8 leaderelection.go:253] successfully acquired lease ingress-nginx/ingress-controller-leader-nginx
I0224 11:32:15.716590 8 status.go:84] "New leader elected" identity="ingress-nginx-controller-7f48b8-rgksh"
I0224 11:32:15.716720 8 queue.go:78] "queue has been shutdown, failed to enqueue" key="&ObjectMeta{Name:sync status,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[]OwnerReference{},Finalizers:[],ClusterName:,ManagedFields:[]ManagedFieldsEntry{},}"
I0224 11:32:15.721748 8 status.go:132] "removing value from ingress status" address=[]
I0224 11:32:15.721793 8 nginx.go:380] "Stopping admission controller"
I0224 11:32:15.721839 8 nginx.go:388] "Stopping NGINX process"
E0224 11:32:15.722094 8 nginx.go:319] "Error listening for TLS connections" err="http: Server closed"
2022/02/24 11:32:15 [notice] 43#43: signal process started
I0224 11:32:16.728705 8 nginx.go:401] "NGINX process has stopped"
I0224 11:32:16.728727 8 main.go:195] "Handled quit, awaiting Pod deletion"
I0224 11:32:26.728861 8 main.go:198] "Exiting" code=0`

My Enviroment :
NGINX Ingress controller
Release: v0.48.1
Build: https://github.com/kubernetes/ingress-nginx/commit/30809c066cd027079cbb32dccc8a101d6fbffdcb
Repository: https://github.com/kubernetes/ingress-nginx
nginx version: nginx/1.20.1

Debian 10 Buster 
k0S : Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"\"not_available\"", GitTreeState:"", BuildDate:"2021-12-24T13:07:15Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1+k0s", GitCommit:"b230d3e4b9d6bf4b731d96116a6643786e16ac3f", GitTreeState:"clean", BuildDate:"2021-12-24T12:59:32Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

What am I missing ?

**Comment by brianehlert** [comment]
The setup instructions that you have linked to are for the K8s community Ingress Controller, not this NGINX Ingress Controller project.

If you would like to use this NGINX Ingress Controller you can follow our docs and examples:
https://docs.nginx.com/nginx-ingress-controller/
https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/complete-example
