### ISSUE TITLE
Moving the docker data folder on linux nodes caused the ingress controller to fail

### ISSUE THREAD

**Issue by llyons** [nginxinc/kubernetes-ingress#2454]
**Describe the bug**
We where looking at moving the docker data folder from /var/lib/docker to take advantage of additional space on a different disk mount.   after setting up the daemon.json and moving the /var/lib/docker files over to the new location with the procedure shown below and restarting docker, we where no longer able to get the nginx-ingress controllers to come back on line.  Getting the error

I0224 15:54:27.564862       1 main.go:258] Starting NGINX Ingress controller Version=1.11.3 GitCommit=af30f69
W0224 15:54:27.586228       1 main.go:297] The '-use-ingress-class-only' flag will be deprecated and has no effect on versions of kubernetes >= 1.18.0. Processing ONLY resources that have the 'ingressClassName' field in Ingress equal to the class.
W0224 15:54:27.588595       1 warnings.go:70] networking.k8s.io/v1beta1 IngressClass is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 IngressClassList
2022/02/24 15:54:27 [emerg] 12#12: bind() to 0.0.0.0:80 failed (13: Permission denied)
F0224 15:54:31.608710       1 manager.go:284] Could not get newest config version: could not get expected version: 0 after 4s

**To Reproduce**
performed the following steps.

1. stopped docker with sudo systemctl stop docker
2. in the larger mounted folder   we made a docker subfolder  so  /data/docker
3. created a file in /etc/docker/daemon.json wtih the following contents
{
  "data-root": "/data/docker"
}
5. moved the files over from the /var/lib/docker folder to the /data/docker folder with the following command
               sudo rsync -aP /var/lib/docker/ /data/docker
7. renamed the older /var/lib/docker folder to ./var/lib/docker.old
8. restarted docker with sudo systemctl start docker

we also performed the following on all 3 linux machines where we did this change

sudo systemctl stop kubelet
sudo systemctl stop docker
sudo iptables --flush
sudo iptables --flush -tnat
sudo systemctl start docker
sudo systemctl start kubelet

**Expected behavior**
We expected the k8 pods to all pickup and resume running without any issues.
All pods did come back up except the ingress controller and pods

**Your environment**
using 1.11.3 of nginx-ingres
Kubernetes version is 1.21.3
Kubernets platform is baremetal linux machines 1 control plane 2 linx workers and 2 windows workers
* Using NGINX

**Additional context**

after reverting the docker data folder back with the following

stop docker with sudo systemctl stop docker
changing the /etc/docker/daemon.json back to this

{
  "data-root": "/var/lib/docker.old"
}
restarting docker with   sudo systemctl start docker

and performing

sudo systemctl stop kubelet
sudo systemctl stop docker
sudo iptables --flush
sudo iptables --flush -tnat
sudo systemctl start docker
sudo systemctl start kubelet

on every linux worker node

the nginx-ingress controllers came back on line and everything is working again.

I am not sure if the move did not bring accross an needed set of files for the ingress controller

**Comment by brianehlert** [comment]
It is not clear to me which ingress project you are using.
Are you using this project: https://github.com/nginxinc/kubernetes-ingress
or this project: https://kubernetes.github.io/ingress-nginx/

The error that stands out to me is:
`[emerg] 12#12: bind() to 0.0.0.0:80 failed (13: Permission denied)`

Which should have nothing to do with the volume change but rather a clash of port.

**Comment by llyons** [comment]
We are definitely using nginx-ingress  https://github.com/nginxinc/kubernetes-ingress

I agree a move like we did should not have had this kind of impact but it did.   Moving back to the original /var/lib/docker fixed the issue  (even referring to it after the rename as /var/lib/docker.old in the daemon.json works)

**Comment by llyons** [comment]
WHat could potentially get in the way of the ingress controller by just moving the location /var/lib/docker to /data/docker.  as soon as we moved it, we have the ingress controllers crashing but as soon as we move back to the original location, it starts working again with NO other changes.

**Comment by brianehlert** [comment]
Thanks for refreshing the thread.  I was just thinking.  Are you deleting and re-pulling the image after the move?
I am thinking some strange layering thing happening within docker.

**Comment by llyons** [comment]
this is the extendt of what we did.  It was real easy and quick to do.   We didnt delete and repull the image 

stopped docker with sudo systemctl stop docker
in the larger mounted folder we made a docker subfolder so /data/docker
created a file in /etc/docker/daemon.json wtih the following contents
{
"data-root": "/data/docker"
}
moved the files over from the /var/lib/docker folder to the /data/docker folder with the following command
sudo rsync -aP /var/lib/docker/ /data/docker
renamed the older /var/lib/docker folder to ./var/lib/docker.old
restarted docker with sudo systemctl start docker


This should be easy to reproduce.

**Comment by llyons** [comment]
I just tried this again on a 2 linux node cluster (1 master 1 worker)  same results

![image](https://user-images.githubusercontent.com/1648546/156656525-22627043-29a1-4da5-9adc-ac359359e359.png)

**Comment by llyons** [comment]
after changing the daemon.json and point  to /data/docker.old on accident (ie, a blank folder) and restarting docker and kubernetes, it actually all came back up properly

not sure if this is the prescribed method but it seems like it repulled all the images and started from scratch.

**Comment by brianehlert** [comment]
It sounds like there is a method for changing this setting that K8s likes.
Closing this issue.
