### ISSUE TITLE
Add HPA

### ISSUE THREAD

**Issue by akuzni2** [nginxinc/kubernetes-ingress#2462]
**Is your feature request related to a problem? Please describe.**
We should allow users to set a flag to turn autoscaling on to create a basic HPA.

**Describe the solution you'd like**
1) a setting in the controller for HPA min/max replicas, targets to scale on, and whether or not to turn it on.
2) Ability to have custom metrics for the HPA since the defaults are cpu/memory. (san enhancement to the existing requirement 1. This would be a _nice to have_)

**Describe alternatives you've considered**
Manually create the HPA (i do this now) but there are many downsides to managing my own.

**Additional context**

**Comment by akuzni2** [comment]
can I assign this issue to myself and try to add a PR for it?

**Comment by brianehlert** [comment]
If you would like to begin the work to support HPA, I am all for it.
cpu / memory should be good to begin with.

**Comment by akuzni2** [comment]
@brianehlert currently I configured one in our prod environment. Before I implement it I'd like to iron out some of the issues I'm seeing. 

One issue is that scaling up/down can cause 500 errors. Do you know why that might be? Will the ingress controller not drain connections to Nginx before the HPA scales it down?

**Comment by brianehlert** [comment]
This project is on version 2.1
I think one that I am not fully aware of is how long of a drain duration that K8s will tolerate before it kills the pods because the scale in took too long.

**Comment by akuzni2** [comment]
@brianehlert got it. I will see if I can update to latest and test again

**Comment by unitygilles** [comment]
Hi @akuzni2, we're interested in using an HPA with the controller. Any news on the 500 errors you're seeing?

**Comment by philnichol** [comment]
same here, this feature would be really useful for us, any updates?

**Comment by brianehlert** [comment]
I believe this was addressed.
https://github.com/nginxinc/kubernetes-ingress/pull/3276
