### ISSUE TITLE
OpenID Connect (oidc) client credentials token not working

### ISSUE THREAD

**Issue by AlexGoris-KasparSolutions** [nginxinc/kubernetes-ingress#2471]
**Describe the bug**
For machine-to-machine authentication, OpenID connect describes the 'client credentials flow', which consists of getting a token from an identity provider (e.g. Keycloak) using a client id and secret. 
Normally the act of getting the token is completely up to the client, it should make an API call to the IDP, which will return an access token, this access token should then be put in the `Authorization` header as a bearer token.
When setting up a JWT policy this works fine, but when setting op an OIDC policy this fails, and I am redirected to the authentication url of my IDP regardless of the valid bearer token in my authorization header.

**To Reproduce**
1. Deploy the [oidc example](https://github.com/nginxinc/kubernetes-ingress/tree/v2.1.1/examples/custom-resources/oidc)
2. Once you have OIDC working, go to the keycloak admin page
3. Go to Clients
4. Add a new client, give it whatever name, in the configuration, make sure to set 'Access type' to `confidential` and set the `Service accounts enabled' to `ON`
5. In the 'Credentials' tab, copy the client secret of the new client
6. Go to the 'Mappers' tab
7. Click 'Create' to create a new mapper, give it whatever name, select `Audience` as the mapper type, then select the `nginx-plus` client. Make sure 'Add to access token' is enabled and click Save
8. Retrieve an access token by maken the following curl call:
    ```
    curl --request POST \
      --url '<value from oidc policy's tokenEndpoint parameter>' \
      --header 'content-type: application/x-www-form-urlencoded' \
      --data grant_type=client_credentials \
      --data client_id=<whatever client name you specifiec> \
      --data client_secret=<the client secret you copied in step 5>
    ```
9. Now make a call to the path protected by the oidc policy (`/` by default from the example)

This call fails authentication and you are redirected to Keycloak's login page

**Expected behavior**
The call made at step 9 should go through and show the example page, since it was made with a valid JWT token

**Your environment**
* Version of the Ingress Controller: 2.1.1
* Version of Kubernetes: 1.22.8
* Kubernetes platform: Azure AKS
* Using NGINX Plus

**Additional context**
Arguably I could use the JWT policy instead of the oidc policy, however if the protected endpoint should also be able to authenticate users, and forward them to the IDP's login page if they don't yet have a valid token, that wouldn't work.

**Comment by brianehlert** [comment]
Thanks for the issue @AlexGoris-KasparSolutions 
The project that you posted this issue in does not have a version  1.25.1
Did you intend this for the K8s Community Ingress project?
However you mention NGINX Plus.

Are you attempting to use NGINX Plus (instead of nginx OSS) with the K8s Community Ingress project?
Did I miss-understand and you are using N+ outside of ingress controller?

**Comment by AlexGoris-KasparSolutions** [comment]
@brianehlert ah sorry I went off of the version number that nginx reports in the `server` header of its responses. I am indeed using nginx plus v2.1.1 of this project, will edit my post as well.
