### ISSUE TITLE
Unable to add configmap's annotation by using helm update

### ISSUE THREAD

**Issue by mtloaprhn** [nginxinc/kubernetes-ingress#2488]
**Describe the bug**
Hi everyone,

I want to update my nginx configuration by using helm update to add some new options (like HSTS and TLSv1.2/1.3). I already have an Ingress controller working but when I want to update it by using `--set controller.config.annotations."hsts"=true` but doesn't working.
> Error: UPGRADE FAILED: unable to decode "": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found t, error found in #10 byte of ...|:{"hsts":true},"labe|..., bigger context ...|d":"ConfigMap","metadata":{"annotations":{"hsts":true},"labels":{"app.kubernetes.io/instance":"nginx|...

My working configuration : 
```
          helm repo update
          helm install nginx-ingress-vdx nginx-stable/nginx-ingress \
              --set controller.nginxplus=true \
              --set controller.image.repository=$(CONTAINER_REGISTRY)/nginx-plus-ingress \
              --set controller.image.tag=$(INGRESS_IMAGE_NAME) \
              --set controller.config.name=nginx-config \
              --set controller.config.annotations."hsts"=True \
              --set controller.config.annotations."ssl_protocols"=TLSv1.2 TLSv1.3
              --set controller.config.entries."proxy-set-headers"=ingress-nginx/custom-headers \
              --set controller.nodeSelector."kubernetes\.io/os"=linux \
              --set controller.nodeSelector."pods"=ingress \
              --set controller.enableCustomResources=true \
              --set controller.globalConfiguraion.create=true \
              --set controller.enableSnippets=true \
              --set controller.replicaCount=2 \
              --set controller.ingressClass=nginx-vdx \
              --set controller.healthStatus=true \
              --set controller.healthStatusURI=/nginx-health \
              --set defaultBackend.nodeSelector."kubernetes\.io/os"=linux \
              --set controller.service.type=LoadBalancer \kube
              --set controller.service.loadBalancerIP=$(VDX_LB_PUBLIC_IP) \
              --set controller.nginxDebug=false \
              --set controller.logLevel=2 \
              --set configmap.error-log-level=debug \
              --namespace ingress-nginx-vdx
```

My new configuration that I want to apply : 
```
        kubectl apply -f crds/
        helm repo update nginx-stable
        helm --debug upgrade nginx-ingress-vdx nginx-stable/nginx-ingress -n ingress-nginx-vdx \
        ...
        --set controller.config.annotations."hsts"=true \
        ...
```

I checked the helm chart and there are controller.config.annotations. 
I tried to use the `--set controller.config.entries."hsts"=true` and I have another error : 
> Error: UPGRADE FAILED: cannot patch "nginx-config" with kind ConfigMap:  "" is invalid: patch: Invalid value: "{\"apiVersion\":\"v1\",\"data\":{\"hsts\":true,\"ingress-template\":\"# configuration for {{.Ingress.Namespace}}/{{.Ingress.Name}}...
 
 Thanks for your advise :)
 
 Have a good day      

**Your environment**
* 2.1.0
* 1.23
* AKS
* NGINX Plus

**Comment by brianehlert** [comment]
HSTS is under the GlobalConfiguration ConfigMap resource in this NGINX Ingress Controller project (not an annotation)
https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#auth-and-ssltls

https://github.com/nginxinc/kubernetes-ingress/tree/master/deployments/helm-chart#configuration
controller.globalConfiguration.spec

**Comment by mtloaprhn** [comment]
I tried to add under controller.globalConfiguration.spec but same issue 
`            --set controller.globalConfiguraion.spec."hsts"=true
`

> Error: UPGRADE FAILED: cannot patch "nginx-config" with kind ConfigMap:  "" is invalid: patch: Invalid value: "{\"apiVersion\":\"v1\",\"data\":{\"hsts\":true,\"ingress-template\":\"

**Comment by mtloaprhn** [comment]
Oh yes ! Thanks @brianehlert , it's working good :)
