### ISSUE TITLE
add buildah dockerfiles for build

### ISSUE THREAD

**Issue by gattytto** [nginxinc/kubernetes-ingress#2490]
hello, I don't use Docker at all in my setups, I do use cri-o and LXD for the cluster nodes (kubernetes) so it would come in hand to have Dockerfiles that can be used with buildah to include non-merged PR's (like the ipv6 one) before they reach release stage.

also when I try to use the Dockerfile from quay.io it won't work, I guess for the same reasons buildah doesn't. So this would be my first go-to platform if we have those kinds of Dockerfiles.

thank you in advance

**Comment by gattytto** [comment]
> Hi @gattytto thanks for reporting!
> 
> Be sure to check out the [docs](https://docs.nginx.com/nginx-ingress-controller) while you wait for a human to take a look at this 🙂
> 
> Cheers!

you are a bot, sir

**Comment by gattytto** [comment]
> 
> we're not pushing Docker images to quay.io at the moment, which Dockerfiles are you referring to? 🤔

I mean trying to use the Dockerfile as is from my account and forked repo in quay.io doesn't take the multistage dockerfile either

**Comment by lucacome** [comment]
@gattytto are you talking about repository builds in quay.io? If so it looks like they're not very configurable and you would need to pass a few parameters for the build to work anyway

**Comment by vepatel** [comment]
@lucacome can this issue be closed now?
