### ISSUE TITLE
add $port abstraction to nginx-ingress nginx.tmpl 

### ISSUE THREAD

**Issue by gattytto** [nginxinc/kubernetes-ingress#2591]
context: I'm using the daemon-set nginx-ingress.yaml for ipv6 only kubernetes 

with latest ipv6 pr merged to edge I'm trying to also disable escalation on the nginx ingress controller container and hitting this situation where the [template](https://github.com/nginxinc/kubernetes-ingress/blob/b60f25e67674a6287dc81f735224a620d275c292/internal/configs/version1/nginx.tmpl#L109-L110) hardcodes port 80 

the only quick solution I find to this is using the -ingress-template-path arg and change that port to whatever I want but I would like to avoid having to use mounts with the same files for such a small change.

so if at the stage of loading the templates from the golang code we can have a port property the nginx.tmpl can use pulled from the container's template yaml at ports.name=http.containerPort it would be way more straight forward and the mount wouldn't be needed for this scenario

thank you for the ipv6 merge it seems to do the trick for me

**Comment by brianehlert** [comment]
If I am reading correctly, I interpret that you want an easy way to set new listening ports or modify the existing listening ports for the ingress controller.
Is that a correct summary?

**Comment by gattytto** [comment]
yes @brianehlert by doing it the same way it's being done with the virtualhosts using their containerPort property from the yaml instead of having to mount a modified tmpl file for nginx ingress controller

**Comment by gattytto** [comment]
yes @brianehlert by doing it the same way it's being done with the virtualhosts using their containerPort property from the yaml instead of having to mount a modified tmpl file for nginx ingress controller

**Comment by brianehlert** [comment]
Let me know if this might address your issue: https://github.com/nginxinc/kubernetes-ingress/discussions/3724
