### ISSUE TITLE
Running Multiple Ingress Controllers?

### ISSUE THREAD

**Issue by JokerDevops** [nginxinc/kubernetes-ingress#2604]
**Is your feature request related to a problem? Please describe.**

When I install multiple nginx ingress controllers on a cluster, the ingress class shares a controller.
As a result, the contents processed by the two ingressclasses are the same.

<img width="808" alt="image" src="https://user-images.githubusercontent.com/41281305/163115522-02f445e6-5e63-49b6-a98a-0304f6035334.png">

**Describe the solution you'd like**
I hope I can specify the controller of ingressclass. Separate them.

**Describe alternatives you've considered**

**Additional context**

**Comment by JokerDevops** [comment]
@brianehlert 
I configured it according to this document, but found that the controller field is fixed. When I create two ingress classes, they share the same controller.
```
spec:
  controller: nginx.org/ingress-controller
```

```
{{- if semverCompare ">=1.18.0-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: {{ .Values.controller.ingressClass }}
{{- if .Values.controller.setAsDefaultIngress }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
{{- end }}
spec:
  controller: nginx.org/ingress-controller
{{- end }}
```

**Comment by jasonwilliams14** [comment]
@JokerDevops That is correct. However:
```
A very important item to remember is the Ingress controller **only processes resources that belong to its class** 
```
Make sure you define your applications with the ingressClass you want that application to be attached to.
