### ISSUE TITLE
"nginx.org/rewrites" Need to be more flexible

### ISSUE THREAD

**Issue by JokerDevops** [nginxinc/kubernetes-ingress#2605]
**Is your feature request related to a problem? Please describe.**

For example if it's defined this way:

"serviceName=a rewrite=/;"

When my service a has two API interfaces:

/api/   => /
/login/sso => /

but,I want `/api/` rewrite to be `/`,  `/login/sso` reserved:

/api/   => /
/login/sso => /login/sso

**Describe the solution you'd like**

I want `/api/` rewrite to be `/`,  `/login/sso` reserved:

/api/   => /
/login/sso => /login/sso

**Describe alternatives you've considered**

**Additional context**

**Comment by JokerDevops** [comment]
@brianehlert  Thank you! I realized my requirements through virtualserver.

**Comment by JokerDevops** [comment]
However, I found that using ingress can not be achieved, so I proposed this issue.

**Comment by pleshakov** [comment]
Hi @JokerDevops 

A workaround for Ingress resources can be to use mergeable Ingress types -- https://github.com/nginxinc/kubernetes-ingress/tree/main/examples/mergeable-ingress-types 

For your example, you can have two minions:
- one for `/api/` path with a rewrite annotation. that annotation will only apply to that minion.
- another for `/login/sso` path without any rewrite annotation

**Comment by brianehlert** [comment]
This project intends to continue to focus on adding value through expanding the custom resources (VirtualServer, VirtualServerRoute, TransportServer, Policy, GlobalConfiguration, etc.) instead of expanding bespoke annotation patterns on Ingress.
