### ISSUE TITLE
Ingress MTLS is not working in nginx IC version 2.1.1

### ISSUE THREAD

**Issue by charlielj88** [nginxinc/kubernetes-ingress#2608]
**Describe the bug**
I have attempted to reproduce the ingress mtls implementation in my nginx IC environment (in EKS). However, when I tested using even the correct client cert and key as in the example, it still returns me the "400 No required SSL certificate was sent" error.

**To Reproduce**
Same steps as in https://github.com/nginxinc/kubernetes-ingress/tree/main/examples/custom-resources/ingress-mtls except the last step as I use the curl command in the following format,
curl -H "Host: webapp.example.com" https://{eks nlb url}/ -k --key client-key.pem --cert client-cert.pem

**Expected behavior**
Should return the success server response

**Your environment**
* Version of the Ingress Controller - 2.1.1
* Version of Kubernetes - v1.21.5-eks-bc4871b
* Kubernetes platform - AWS EKS
* Using NGINX or NGINX Plus - NGINX

**Additional context**

**Comment by brianehlert** [comment]
May I try to clarify what you are trying to accomplish?

Are you attempting to set up mTLS between the NLB and the Ingress Controller?
Is your intention to decrypt and re-encrypt at the LB layer?  Is your intention to only allow traffic from the LB (using mTLS auth)?

**Comment by charlielj88** [comment]
> May I try to clarify what you are trying to accomplish?
> 
> Are you attempting to set up mTLS between the NLB and the Ingress Controller? Is your intention to decrypt and re-encrypt at the LB layer? Is your intention to only allow traffic from the LB (using mTLS auth)?

I am trying to set up the mTLS between other application (client) with application pod in EKS, and use nginx ingress controller to validate the client cert by using the IngressMTLS policy. For now I am just testing by using curl command with client cert. NLB is just the EKS service for me to access the cluster, and did nothing with the cert or the https request (pass-through).
