### ISSUE TITLE
No annotation for `nginx.org/http-snippets`?

### ISSUE THREAD

**Issue by jaytaylor** [nginxinc/kubernetes-ingress#263]
Greetings,

Is there a reason for not having an annotation for http-snippets via `nginx.org/http-snippets`?

*EDIT:*

Specifically, I'm referring to https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/customization

**Comment by komapa** [comment]
There is such annotation as far as I can see https://www.dropbox.com/s/w1m5fqicr1lmjlo/Screenshot%202018-04-02%2020.53.48.png?dl=0

**Comment by pleshakov** [comment]
@jaytaylor yes, most of the time to customize an Ingress you would want to change the `location` or `server` context.  What is your use case?  

the `http` is a global context that includes all the `upstreams` and `servers` of all the Ingress resources. In general, changing this context will affect all the Ingress resources. That is why there is no annotation, only a configmap key.

**Comment by jaytaylor** [comment]
The use-case is to fix incorrect outbound location headers generated due to a misbehaving upstream LB out of my control.

I'll open an issue the official k8s nginx ingress instead, as that is what comes with kubernetes by default, and the default configuration between nginxinc's version and the k8s version is very different.

**Comment by gautamvij94** [comment]
Greetings, 
I had a requirement of setting up proxy_cache_path for which I was thinking of using http-snippets annotation if it existed. 
Can anyone suggest other possible way to achieve the same without using configmap for ingress controller ?

**Comment by jasonwilliams14** [comment]
@gautamvij94 
Yes, you can use `http-snippets` to setup `proxy_cache_path
Here is a simple example from our docs that show you how to use this exact snippet.

```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
  namespace: cafe
spec:
  http-snippets: |
    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=1r/s;
    proxy_cache_path /tmp keys_zone=one:10m;    
  host: cafe.example.com
  tls:
    secret: cafe-secret
  server-snippets: |
        limit_req zone=mylimit burst=20;
  upstreams:
  - name: tea
    service: tea-svc
    port: 80
  - name: coffee
    service: coffee-svc
    port: 80
  routes:
  - path: /tea
    location-snippets: |
      proxy_cache one;
      proxy_cache_valid 200 10m;      
    action:
      pass: tea
  - path: /coffee
    action:
      pass: coffee
```
https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#using-snippets

HTH
