### ISSUE TITLE
HTTPS to application return 404/timeout

### ISSUE THREAD

**Issue by evenme** [nginxinc/kubernetes-ingress#2640]
**Describe the bug**
Accessing an application behind nginx ingress returns 404 error (if https port enabled) or timeout (if https port disabled). I'm trying to make it SSL terminate at the nginx, not the app service.

**To Reproduce**
Helm package deployed, image tag 2.2.0 and the following changes:
```    
 entries:
      server-names-hash-bucket-size: "128"
      proxy-buffer-size: "128K"
      proxy-buffers: "4 256k"
      proxy-connect-timeout: "60"
      proxy-read-timeout: "60"
      stream-snippets: |
        log_format basic '$ssl_preread_server_name -- $remote_addr -$hostname -$server_addr -$proxy_protocol_addr -$upstream_addr -[$time_local] ' '$protocol $status $bytes_sent $bytes_received ' '$session_time';
        access_log /var/log/nginx/access.log basic;
    httpsPort:
      ## Enables the HTTPS port for the Ingress Controller service.
      enable: false
annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
```

**Expected behavior**
Access https://application.domain.com, it'll use the self-signed certificate from defaultTLS.
Instead it gives me timeout or 404 (depending of the config)

**Your environment**
2.2.0 imagetag from helm chart
AWS EKS k8s 1.19

**Additional context**
We had this working before on a previous cluster but can't figure out how or why, all configs look the same.

**Comment by jasonwilliams14** [comment]
@evenme can you post your .yaml configuration files for how you have setup NGINX Ingress Controller?
Can you also post your full helm `values.yaml` file (scrub as needed)
Thx

**Comment by evenme** [comment]
nvm, switched to the https://github.com/kubernetes/ingress-nginx and all is sorted.

**Comment by brianehlert** [comment]
> nvm, switched to the https://github.com/kubernetes/ingress-nginx and all is sorted.

We take it you were using configurations specific to the other project?

**Comment by evenme** [comment]
> > nvm, switched to the https://github.com/kubernetes/ingress-nginx and all is sorted.
> 
> We take it you were using configurations specific to the other project?

No, I was not, I actually had no extra annotations. We had been using nginxinc/kubernetes-ingress for quite a while but had our SSL in secrets terminating HTTPS on the pod. I wanted to have it terminating at the Nginx using AWS ACM if possible (which I only added now with the other project). Like I said, nvm, using ACM with the other project was painless (and documented).

**Comment by jasonwilliams14** [comment]
@evenme Your use case is supported with this project. You might need to add a view pieces to your `values.yaml` file, which is why I wanted to review your helm file and resource file to help identify what you might need to add.

**Comment by brianehlert** [comment]
Thanks for responding @evenme 
I have been rereading this thread to be sure that we are understanding what you were trying to accomplish.
Allow me to read back what I think I understand.

- External traffic comes into Ingress controller
- Ingress provides TLS termination for the client
- this traffic is then proxied to an internal AWS load balancer (as http) - this load balancer is 'behind' ingress controller

[client (SSL)] <-> [(SSL) ingress] <-> [internal load balancer] <-> [application]

Did I follow that?

At one point we were thinking you were trying to TLS terminate at the load balancer in front of ingress.
