### ISSUE TITLE
Question: how to limit rate/connections differently for each ingress/service. I dont see an annotation for doing that

### ISSUE THREAD

**Issue by devendra-nvidia** [nginxinc/kubernetes-ingress#265]

**Comment by pleshakov** [comment]
@devendra-nvidia there is no annotation for that.  As an alternative, it is possible to configure that by using the location/server snippets annotations and the http-snippets configmap key. See https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/customization Also, you can customize the config template files https://github.com/nginxinc/kubernetes-ingress/tree/master/nginx-controller/nginx/templates and build you own Ingress controller image with the customized templates. 
More info about rate limiting in NGINX -- https://www.nginx.com/blog/rate-limiting-nginx/

**Comment by devendra-nvidia** [comment]
thank you that's what I needed
