### ISSUE TITLE
Geoip database update support for the k8s deployment

### ISSUE THREAD

**Issue by wd** [nginxinc/kubernetes-ingress#2705]
**Is your feature request related to a problem? Please describe.**

We are trying to use the GeoIP module in the k8s ingress. however, we didn't find a way to set up the GeoIP database update job. 

**Describe the solution you'd like**

Maybe we could allow people to set up a sidecar container for the ingress pod? so that users can set up the update process inside that container. 

**Describe alternatives you've considered**

**Additional context**

**Comment by Binsabbar** [comment]
Hi @wd, I am too working on GeoIP for my setup. However, I have not yet tried to use DB update. 

Regarding sidecar, have you checked this https://github.com/nginxinc/kubernetes-ingress/blob/main/deployments/helm-chart/values.yaml#L149 ? seems like it is supported already and here you can declare and mount volumes https://github.com/nginxinc/kubernetes-ingress/blob/main/deployments/helm-chart/values.yaml#L125

Let me know if that works for you.

**Comment by wd** [comment]
oh, thanks. that helps.
