### ISSUE TITLE
nginx.ingress.kubernetes.io/backend-protocol":"HTTPS" not work

### ISSUE THREAD

**Issue by slehlib** [nginxinc/kubernetes-ingress#2749]
version : Image: nginx/nginx-ingress:2.2.2
kube version : v1.21.1
OS version; Red Hat Enterprise Linux Server release 7.9 (Maipo)

i have new application use https backend, i added the nginx.ingress.kubernetes.io/backend-protocol":"HTTPS" annotation but ingress use http.
i have this msg in app log:
022-06-10 09:19:38 +0000 SSL error, peer: 10.233.102.237, peer cert: : #<Puma::MiniSSL::SSLError: OpenSSL error: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request - 156>

In the nginx/conf.d ngnix dont have change the proxy_pass http in proxy_pass https://
i modify manualy, restart nginx et now all work .
this is my ingress file
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
name: ingress
namespace: app
annotations:
kubernetes.io/ingress.class: "nginx"
ingress.kubernetes.io/ssl-redirect: "false"
nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
tls:

    hosts:
        app.compagny.com
        secretName: tls
        rules:
    host: app.compagny.com
    http:
    paths:
    - path: /
    backend:
    serviceName: svc
    servicePort: 35415

**Comment by brianehlert** [comment]
Terribly sorry for the confusion.  The annotations `nginx.ingress.kubernetes.io` are specifically for the K8s community ingress controller project (which also uses NGINX).
The annotations for this project are `nginx.org` and can be found here: https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/

Examples for using the Ingress resource with this project can be here: https://github.com/nginxinc/kubernetes-ingress/tree/v2.2.2/examples
Examples for using the more powerful Custom Resources of this project can be found here: https://github.com/nginxinc/kubernetes-ingress/tree/v2.2.2/examples/custom-resources

**Comment by slehlib** [comment]
sorry for this  am confused.
Thank you for your help

**Comment by uGiFarukh** [comment]
What is the alternative to `nginx.ingress.kubernetes.io/backend-protocol":"HTTPS"` for nginx inc ingress controller? Trying to deploy portainer with cert manager with nginx inc ingress but not able to configure it properly to get the certificates. Self test failing in cert manager. Wondering if the issue is with this annotation somehow.

**Comment by brianehlert** [comment]
https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#upstreamtls

**Comment by brianehlert** [comment]
The link I provided uses the CRDs of this project to implement TLS to the backend / upstream.  Not an annotation.

Instead of using Ingress, you would use VirtualServer
