### ISSUE TITLE
TLS version V1 and V1.1 not getting disabled even after configuration

### ISSUE THREAD

**Issue by shrikar-thite-unskript** [nginxinc/kubernetes-ingress#2779]
**Describe the bug**

Fo security purpose we are trying to disable TLSv1 and TLSv1.1 versions within configuration of ingress controller 

added below line for config chages through configmap which is sucessfully reflect in po config
ssl-protocols: TLSv1.2 TLSv1.3

But still while checking with openssl command we are able connect 

openssl s_client -connect jenkins-public.dev.unskript.io:443 -tls1

**To Reproduce**

1. Deployed ingress with command 
helm upgrade --install ingress-controller nginx-stable/nginx-ingress
versions I tested are 
chart version 0.8.1 and 0.13.2
image tags 1.10.1-alpine and 2.2.2
nginx version nginx/1.19.8

2. See error
it's not error exactly but we get output which not should come if there in configuration done in nginx.conf 
ssl-protocols: TLSv1.2 TLSv1.3
as mentioned above 
command
openssl s_client -connect tenant-pentesting.dev.unskript.io:443 -tls1_1
output
CONNECTED(00000003)
depth=2 C = US, O = Amazon, CN = Amazon Root CA 1
verify return:1
depth=1 C = US, O = Amazon, OU = Server CA 1B, CN = Amazon
verify return:1
depth=0 CN = <removed>
verify return:1
\---
Certificate chain
 0 s:CN = <removed>
   i:C = US, O = Amazon, OU = Server CA 1B, CN = Amazon
.
.
.
.
truncated o/p
\---
Server certificate
-----BEGIN CERTIFICATE-----
.
.
.
.
truncated o/p
-----END CERTIFICATE-----
subject=CN = 

issuer=C = US, O = Amazon, OU = Server CA 1B, CN = Amazon

\---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA
Server Temp Key: ECDH, P-256, 256 bits
\---
SSL handshake has read 5558 bytes and written 356 bytes
Verification: OK
\---
New, TLSv1.1, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.1
    Cipher    :
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 172800 (seconds)
    TLS session ticket:
  <removed>

    Start Time: 1655798750
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
\---

**Expected behavior**

command:
openssl s_client -connect tenant-jayasimha.dev.unskript.io:443 -tls1_1

desired output:
CONNECTED(00000003)
140420453606720:error:141E70BF:SSL routines:tls_construct_client_hello:no protocols available:../ssl/statem/statem_clnt.c:1112:
\---
no peer certificate available
\---
No client certificate CA names sent
\---
SSL handshake has read 0 bytes and written 7 bytes
Verification: OK
\---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)

**Your environment**
* Version of the Ingress Controller - 1.10.1-alpine, 2.2.2
* Version of Kubernetes 1.20
* Kubernetes platform (e.g. Mini-kube or GCP) eks
* Using NGINX 

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by jasonwilliams14** [comment]
@shrikar-thite-unskript 
ok. I see what you are doing. Since you are doing the TLS termination at the ELB, the SSL protocols will not be read by NGINX at all. The ELB terminated the traffic, and you are forwarding traffic on port 80 to the NGINX Ingress controller.

I see two options.
1.) if you still want to do TLS termination on the ELB, see if you can modify it to accept only certain protocols.
2.) Move TLS termination to NGINX ingress controller itself.

Let us know if that helps.

**Comment by shrikar-thite-unskript** [comment]
Hi @jasonwilliams14 ,

Sorry for late reply, but option one I had figured it out, and that worked for me

I managed policy at elb level provided by aws to disable old versions of TLS

Thanks a lot for your valuable input 

Regards

**Comment by shrikar-thite-unskript** [comment]
> @shrikar-thite-unskript ok. I see what you are doing. Since you are doing the TLS termination at the ELB, the SSL protocols will not be read by NGINX at all. The ELB terminated the traffic, and you are forwarding traffic on port 80 to the NGINX Ingress controller.
> 
> I see two options. 1.) if you still want to do TLS termination on the ELB, see if you can modify it to accept only certain protocols. 2.) Move TLS termination to NGINX ingress controller itself.
> 
> Let us know if that helps.

Hi @jasonwilliams14 ,

Sorry for late reply, but option one I had figured it out, and that worked for me

I managed policy at elb level provided by aws to disable old versions of TLS

Thanks a lot for your valuable input

Regards
