### ISSUE TITLE
NIC+NAP+externalReferences - reload external reference not working

### ISSUE THREAD

**Issue by de1chk1nd** [nginxinc/kubernetes-ingress#2820]
**Describe the bug**
I want to deploy a NAP policy in k8s with external references.
When I change local APPolicy, everything works fine.
When working with external references, and I only change the external reference, nothing happens.

I used the nginx troubleshooting guide: 
https://docs.nginx.com/nginx-ingress-controller/troubleshooting/troubleshooting-with-app-protect/

Using the statement with "--force", generates following error message: kubectl replace appolicy -f your-policy-manifest.yaml --force
error: when paths, URLs, or stdin is provided as input, you may not specify resource arguments as well

Using it w/o the "--force", allows me to issue the command - but external policy isn't reloaded.

**To Reproduce**
kubectl replace appolicy -f waf-add-responsepage.yaml --force

**Expected behavior**
Reload of external policy

**Your environment**
* Version of the Ingress Controller - release version or a specific commit
2.2.2 

* Version of Kubernetes
1.21 [edited - was 1.22 before ... my bad - did not cross check; but 1.21 is coded in my tf scripts :( ]

* Kubernetes platform (e.g. Mini-kube or GCP)
AWS EKS

* Using NGINX or NGINX Plus
NGINX+

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by jasonwilliams14** [comment]
@de1chk1nd Since you are using NGINX Plus, you should open up a proper support ticket.
I am going to close this ticket since you are using NGINX plus.
