### ISSUE TITLE
To add content security policy using addheaders in values.yaml file

### ISSUE THREAD

**Issue by praveensounder** [nginxinc/kubernetes-ingress#2827]
### Discussed in https://github.com/nginxinc/kubernetes-ingress/discussions/2826

<div type='discussions-op-text'>

<sup>Originally posted by **praveensounder** July  7, 2022</sup>

Currently we are using Nginx ingress controller 2.1.1 - https://github.com/nginxinc/kubernetes-ingress/tree/v2.1.1

We need to add Content security policy to the config file.

We passed using addheaders but its not getting reflected.

Kindly please let us know How to add content security policy in helm charts values.yaml file

We need to add configuration Inside nginx server {} block like below:

add_header Content-Security-Policy "default-src 'self';";

Link: https://content-security-policy.com/examples/nginx/
</div>

**Comment by brianehlert** [comment]
Responding to this in the discussion thread.
