### ISSUE TITLE
Ingress controller Nginx is not redirecting to kubernetes pods

### ISSUE THREAD

**Issue by Yogaraj-Pandiaraj** [nginxinc/kubernetes-ingress#2833]
**Describe the bug**
When trying to access the application that is hosted in kubernetes container via Ingress controller getting the below error.
2022/07/08 13:05:39 [error] 307#307: *118 "/etc/nginx/html/index.html" is not found (2: No such file or directory)

Used Helm command:
helm install ingress-controller nginx-stable/nginx-ingress -f Internal-Ingress.yaml --set controller.replicaCount=3 --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux --set controller.ingressClass="test-ingress"

**To Reproduce**
1. Deploy a webapp in kubernetes ingress to '...' using webapp.yaml
2. Deploy Ingress controller using Helm chart
3. View the controller pod logs on 
kubectl logs -f ingress-controller-nginx-ingress-794c978449-8ls9x -c ingress-controller-nginx-ingress
5. See error
2022/07/08 13:05:39 [error] 307#307: *118 "/etc/nginx/html/index.html" is not found (2: No such file or directory)

**Expected behavior**
Ingress controller should redirect https calls to my application.

**Your environment**
* Version of the Ingress Controller - 2.2.2 chart verion(nginx-ingress-0.13.2)
* Version of Kubernetes - 1.22.4
* Kubernetes platform - AKS cluster
* Using NGINX

**Comment by brianehlert** [comment]
Since you are using the Helm chart, can you please share your values.yaml file so that we can be effective in assisting.

**Comment by Yogaraj-Pandiaraj** [comment]
Hi @brianehlert 

I dont use any values.yaml or configmap for the ingress controller pods. 
directly using helm install commands.

helm install ingress-controller nginx-stable/nginx-ingress -f Internal-Ingress.yaml --set controller.replicaCount=3 --set controller.nodeSelector."beta.kubernetes.io/os"=linux --set defaultBackend.nodeSelector."beta.kubernetes.io/os"=linux --set controller.ingressClass="test-ingress".

The Ingress server not redirecting the request to the actual application that is hosted inside my cluster.

**Comment by Yogaraj-Pandiaraj** [comment]
build-vm-03:~$ kubectl describe deployment ingress-controller-nginx-ingress
Name:                   ingress-controller-nginx-ingress
Namespace:              default
CreationTimestamp:      Tue, 05 Jul 2022 17:07:07 +0000
Labels:                 app.kubernetes.io/instance=ingress-controller
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=ingress-controller-nginx-ingress
                        helm.sh/chart=nginx-ingress-0.13.2
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: ingress-controller
                        meta.helm.sh/release-namespace: default
Selector:               app=ingress-controller-nginx-ingress
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=ingress-controller-nginx-ingress
  Annotations:      prometheus.io/port: 9113
                    prometheus.io/scheme: http
                    prometheus.io/scrape: true
  Service Account:  ingress-controller-nginx-ingress
  Containers:
   ingress-controller-nginx-ingress:
    Image:       nginx/nginx-ingress:2.2.2
    Ports:       80/TCP, 443/TCP, 9113/TCP, 8081/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP, 0/TCP
    Args:
      -nginx-plus=false
      -nginx-reload-timeout=60000
      -enable-app-protect=false
      -enable-app-protect-dos=false
      -nginx-configmaps=$(POD_NAMESPACE)/ingress-controller-nginx-ingress
      -default-server-tls-secret=$(POD_NAMESPACE)/ingress-controller-nginx-ingress-default-server-tls
      -ingress-class=nginx
      -health-status=false
      -health-status-uri=/nginx-health
      -nginx-debug=false
      -v=1
      -nginx-status=true
      -nginx-status-port=8080
      -nginx-status-allow-cidrs=127.0.0.1
      -report-ingress-status
      -external-service=pinnacle-ingress-controller-nginx-ingress
      -enable-leader-election=true
      -leader-election-lock-name=pinnacle-ingress-controller-nginx-ingress-leader-election
      -enable-prometheus-metrics=true
      -prometheus-metrics-listen-port=9113
      -prometheus-tls-secret=
      -enable-custom-resources=true
      -enable-snippets=false
      -enable-tls-passthrough=false
      -enable-preview-policies=false
      -enable-cert-manager=false
      -enable-oidc=false
      -ready-status=true
      -ready-status-port=8081
      -enable-latency-metrics=false
    Readiness:  http-get http://:readiness-port/nginx-ready delay=0s timeout=1s period=1s #success=1 #failure=3
    Environment:
      POD_NAMESPACE:   (v1:metadata.namespace)
      POD_NAME:        (v1:metadata.name)
    Mounts:           <none>
  Volumes:            <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   ingress-controller-nginx-ingress-794c978449 (1/1 replicas created)
Events:          <none>

**Comment by Yogaraj-Pandiaraj** [comment]
I have followed these steps;
https://docs.microsoft.com/en-us/azure/aks/ingress-basic?tabs=azure-cli

I have attached my pod logs here. I am not using NGINX Plus. I hope I am using NGINX OSS.

[ingress_controller_log.txt](https://github.com/nginxinc/kubernetes-ingress/files/9073267/ingress_controller_log.txt)

**Comment by brianehlert** [comment]
Unfortunately those instructions from Microsoft are for the K8s Community Ingress project.
So I think the wires are crossed a little bit.

If you would like to use this project, the instructions are here: https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/

**Comment by vikram2784** [comment]
Is this fixed? I tried the latest on AKS and it still gives the same error.

**Comment by jasonwilliams14** [comment]
@vikram2784 If you are experiencing similar issues, can you attach your logs and .yaml files on your deployment that is having this challenge? The more information we have, the more we can research the issue and provide feedback.

**Comment by vikram2784** [comment]
Following [this aks link](https://learn.microsoft.com/en-us/azure/aks/ingress-basic?tabs=azure-cli) worked for me.  I was getting the issue with [nginx-stable/nginx-ingress](https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/) on aks.
