### ISSUE TITLE
VirtualServer spec define

### ISSUE THREAD

**Issue by liuqi-sun** [nginxinc/kubernetes-ingress#2840]
I want to modify VirtualServer spec, what should  I do? Where is the KubeBuilder project?

**Comment by euchch** [comment]
(Running the risk of pointing you at the wrong direction but this is how I learn, sorry if I got your question wrong! )
You mean... this? https://github.com/nginxinc/kubernetes-ingress/blob/f83076b64135c0ffe8aeed3b5debf7ee5dfabfdb/internal/configs/virtualserver.go

**Comment by liuqi-sun** [comment]
> (Running the risk of pointing you at the wrong direction but this is how I learn, sorry if I got your question wrong! ) You mean... this? https://github.com/nginxinc/kubernetes-ingress/blob/f83076b64135c0ffe8aeed3b5debf7ee5dfabfdb/internal/configs/virtualserver.go

You got it wrong. What I need is the KubeBuilder project to generate CR

**Comment by lucacome** [comment]
Hi @liuqi-sun 

I believe you're looking for https://github.com/nginxinc/kubernetes-ingress/blob/main/pkg/apis/configuration/v1/types.go#L38 
Then you can run `make update-codegen` and `make update-crds` to update.

Let me know if it makes sense.

**Comment by liuqi-sun** [comment]
> Hi @liuqi-sun
> 
> I believe you're looking for https://github.com/nginxinc/kubernetes-ingress/blob/main/pkg/apis/configuration/v1/types.go#L38 Then you can run `make update-codegen` and `make update-crds` to update.
> 
> Let me know if it makes sense.

I need to copy these files into my own KubeBuilder project and execute make update-codegen and make update-crds to update? Is there no KubeBuilder project repository on Github?

**Comment by liuqi-sun** [comment]
> Hi @liuqi-sun
> 
> I believe you're looking for https://github.com/nginxinc/kubernetes-ingress/blob/main/pkg/apis/configuration/v1/types.go#L38 Then you can run `make update-codegen` and `make update-crds` to update.
> 
> Let me know if it makes sense.

thank you very much. I see the Makefile  in the project's top level directory

**Comment by liuqi-sun** [comment]
> Hi @liuqi-sun
> 
> I believe you're looking for https://github.com/nginxinc/kubernetes-ingress/blob/main/pkg/apis/configuration/v1/types.go#L38 Then you can run `make update-codegen` and `make update-crds` to update.
> 
> Let me know if it makes sense.

If I create a new CR, how do I should?
