### ISSUE TITLE
Support GCP Marketplace deployment of NGINX+ ingress controller

### ISSUE THREAD

**Issue by memes** [nginxinc/kubernetes-ingress#2859]
As a customer, I want to purchase NGINX+ ingress controller through pay-as-you-go deployments in GKE, including variants for App Protect, App Protect DoS, and combinations of the two.

Tagging @brianehlert for review.

PR #2860 includes the following:

- [x] A billing agent is included in builds tagged with `gcp` that retrieves a secret containing billing credentials created as part of GCP's deployment process
- [x] Patched helm charts to support passing GCP specific params to the container
- [x] ~GCP marketplace `deployer` and `apptest` helm charts used to install and test deployments~
- [x] ~Dockerfiles and supporting files for the `deployer` and `apptest` container images~
- [x] Documentation/example

**Comment by memes** [comment]
@lucacome I have made changes to the proposed PR to support embedding the product identifier during build and to pass the GCP Marketplace usage-reporting secret via environment variable at run-time. Branch has been rebased onto main and squashed, please review #2860.

I created a separate repo for required GCP Marketplace `deployer` and `apptest` at https://github.com/memes/kubernetes-ingress-gcp-mp - lmk about transferring repo to nginxinc org.

**Comment by pdabelf5** [comment]
NGINX Ingress Controller is now available on the [GCP Marketplace](https://docs.nginx.com/nginx-ingress-controller/installation/nic-images/use-gcp-image/)
