### ISSUE TITLE
ingress domain based routing is not working in browser but I'm able to curl the URL on ingress controller pod successfully.

### ISSUE THREAD

**Issue by linux17kartik** [nginxinc/kubernetes-ingress#289]
Hi There,

**I have installed the ingress controller using the link:**
https://cloud.google.com/community/tutorials/nginx-ingress-gke
which is up and running 

NAME                       TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)                      AGE
nginx-ingress-controller   LoadBalancer   X.X.X.X   X.X.X.X1   80:123/TCP,443:456/TCP   1d

After that I have installed and exposed the application as nodePort, bot app up and running.

**Ingress Rules are defined as :**

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-resource
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: foo.com
    http:
        paths:
        - backend:
            serviceName: foo-service
            servicePort: 8080

  - host: faa.com
    http:
        paths:
        - backend:
            serviceName: faa-service
            servicePort: 80

**To verify I did exec in inginx-controller pod and test the followings**

Tests: 1
Input :  curl localhost 
Output : default backend - 404

Tests: 2
Input :  curl localhost -H 'Host:foo.com'
Output : app working properly

Tests: 3
Input :  curl localhost -H 'Host:faa.com'
Output : app working properly

Tests: 4 on Browser Chrome
- Input : foo.com
- Input : faa.com
Output : default backend - 404

**I do not able to figureout where am I missing to recheck**

Please support me for for the same.

**Comment by pleshakov** [comment]
@linux17kartik The tutorial uses the Ingress controller from this repo https://github.com/kubernetes/ingress-nginx, which is a different project. Please create an issue in that repo

**Comment by linux17kartik** [comment]
created issue in the concern project, thanks for reply.
https://github.com/kubernetes/ingress-nginx
