### ISSUE TITLE
large client header buffers

### ISSUE THREAD

**Issue by monika3376** [nginxinc/kubernetes-ingress#290]
Hi,

I need to set large_client_header_buffers to different value, is it possible by installing NGNIX using helm chart or can I defined it by creating ingress controller of ngnix?

Thanks,
Monika

**Comment by pleshakov** [comment]
@monika3376 You can set the value of the `large_client_header_buffers` directive using either the `http-snippets` configmaps key or `server-snippets` configmap key or `nginx.org/server-snippets` annotation. See https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/customization Here is an example of using the server-snippets key -- https://github.com/nginxinc/kubernetes-ingress/blob/master/examples/customization/nginx-config.yaml#L39

**Comment by katlimruiz** [comment]
a

> @monika3376 You can set the value of the `large_client_header_buffers` directive using either the `http-snippets` configmaps key or `server-snippets` configmap key or `nginx.org/server-snippets` annotation. See https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/customization Here is an example of using the server-snippets key -- https://github.com/nginxinc/kubernetes-ingress/blob/master/examples/customization/nginx-config.yaml#L39

an example would be great since the examples folder moved and there is no explicit entry for `large_client_header_buffers `
