### ISSUE TITLE
Questions about location-snippets and server-snippets that are not working...

### ISSUE THREAD

**Issue by mastrauckas** [nginxinc/kubernetes-ingress#291]
Just wanted to see if this is a limitation or if I am doing something wrong.

Here are a few settings I have tried with their behavior:

- When I add `add_header` in  `location-snippets` it appears `server-snippets` `add_header` gets ignored.
So if I have
```
nginx.org/server-snippets: |
      add_header X-Frame-Options "DENY" always;
      add_header X-XSS-Protection "1; mode=block" always;
      add_header X-Content-Type-Options "nosniff" always;
      add_header Strict-Transport-Security "max-age=31536000; includeSubdomains preload";

nginx.org/location-snippets: |
      add_header Cache-Control "max-age=365000000, immutable";

```

I only see the `Cache-Control: max-age=365000000, immutable` header.  Is there a way I can add a global headers and location header?

- When adding any of these directives:

```
nginx.org/location-snippets: |
   proxy_cache      
   proxy_cache_valid
   etag off;
   if_modified_since off;
```

I get error 
```
stderr: "nginx: [emerg] \"<directive name>" directive is not allowed here in /etc/nginx/conf.d/default-nginx-ingress.conf:68\nnginx: configuration file /etc/nginx/nginx.conf test failed\n"
```

Is there a way to add these directives?

Thanks for anyones help!

**Comment by pleshakov** [comment]
@mastrauckas 
 > I only see the Cache-Control: max-age=365000000, immutable header. Is there a way I can add a global headers and location header?

that's the expected behavior. if you have the `add_header` in the location context,  the `add_header` directives in the server context are ignored. Solution -- you need to put the other add_header directives in the location snippet. See http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header

> When adding any of these directives: ... 

you need to set the value `off` for each directive, not for all of them together at once 

Note. after you deploy an Ingress resource, you can run `kubectl describe ing <name>` and see the  events related to it. In case of successful deployment, you will see an `AddedOrUpdated` event.

**Comment by mastrauckas** [comment]
@pleshakov 

Thanks for the information on describe.  I have been using `kubectl logs ..` to get all the information for now.

When you say set each directive, you mean like this:
```
nginx.org/location-snippets: proxy_cache default;
nginx.org/location-snippets:  proxy_cache_valid  200 302 60m;
nginx.org/location-snippets:  proxy_cache_valid  404      1m;
nginx.org/location-snippets:  if_modified_since off;
nginx.org/location-snippets:  etag off;
```

When trying above I don't get an error and everything says it was "AddedOrUpdated" but none of the directives seem to get applied.  I assume I am misunderstanding what you're telling me?

**Comment by pleshakov** [comment]
@mastrauckas in your previous example, you had:
```
nginx.org/location-snippets: |
   proxy_cache      
   proxy_cache_valid
   etag off;
   if_modified_since off;
```
by saying " set the value off for each directive" I meant transforming your example into something like below:
```
nginx.org/location-snippets: |
   proxy_cache  off;    
   proxy_cache_valid off;
   etag off;
   if_modified_since off;
```
hope that eliminates any confusion. 

>> nginx.org/location-snippets: proxy_cache default;
nginx.org/location-snippets:  proxy_cache_valid  200 302 60m;
nginx.org/location-snippets:  proxy_cache_valid  404      1m;
nginx.org/location-snippets:  if_modified_since off;
nginx.org/location-snippets:  etag off;

this won't work. you can only have one "location-snippets" annotation per an Ingress resource.

Also, if you need to add a lot of NGINX directives, another approach for customization -- is to change the [template file](https://github.com/nginxinc/kubernetes-ingress/blob/master/nginx-controller/nginx/templates/nginx.ingress.tmpl) that is used to generate the config and build your image with the modified template

**Comment by mastrauckas** [comment]
@pleshakov 
Still getting an error:
```
nginx.org/location-snippets: |
      proxy_cache  off;    
      proxy_cache_valid off;
      etag off;
      if_modified_since off;
```
Doesn't seem to work.  With the above location-snippets this is the response I get:

```HTTP/1.1 200 OK
Server: nginx/1.13.8
Date: Mon, 04 Jun 2018 21:07:37 GMT
Content-Type: text/html
Connection: keep-alive
Vary: Accept-Encoding
Cache-Control: no-cache
Etag: W/"5b1536d3-3ce"
Expires: Mon, 04 Jun 2018 21:07:36 GMT
Last-Modified: Mon, 04 Jun 2018 12:55:47 GMT
Content-Encoding: gzip
```
Which I shouldn't see the `etag`.

**Comment by mastrauckas** [comment]
@pleshakov 

The other thing I noticed is if you put `etag off` inside an if it errors out too.

Here is an example:

```
if ($uri = /) {
  etag off;
}
```

**Comment by pleshakov** [comment]
@mastrauckas in this case, you cannot use the `etag` directive inside the `if` block. 

I suggest (1) figuring out what NGINX directives to use and how and only then (2) trying to configure the Ingress controller with them.

if you'd like to get some help with (1), please ask questions in our mailing list http://mailman.nginx.org/mailman/listinfo/nginx Our community members and core developers can help you find the answers.
