### ISSUE TITLE
Provide a Grafana dashboard 

### ISSUE THREAD

**Issue by JokerDevops** [nginxinc/kubernetes-ingress#2921]
Is there any public Grafana dashboard for this controller? I found many out there but they are for the kubernetes nginx ingress controller (the one managed by kube folks). Thanks.

**Comment by brianehlert** [comment]
I believe you might be looking for this: https://github.com/nginxinc/kubernetes-ingress/tree/main/grafana

**Comment by JokerDevops** [comment]
@brianehlert It may only look like the plus version. Is there a public version? Thanks

**Comment by brianehlert** [comment]
It should be the same dashboard.
Plus outputs far more metrics than NGINX OSS does.  And given the additional richness there are more insights we can derive from NGINX Plus.
And that is literally the only difference - the NGINX data plane under the hood and the differences that introduces (lots of metrics and some capabilities).  The rest of the project is identical.

With the native Prometheus endpoint enabled you can see the source of the metrics available.

**Comment by JokerDevops** [comment]
@brianehlert  ok,Thanks

**Comment by brianehlert** [comment]
Following up - I don't know why I didn't think about this prior.  
Someone brought it to my attention that the dashboard we provide through this sister project focuses on NGINX OSS: https://github.com/nginxinc/nginx-prometheus-exporter/tree/main/grafana
