### ISSUE TITLE
help , my kubernetes version is 1.18.0, I update my nginx-ingress1.7.2 to 1.11.0, tip error.

### ISSUE THREAD

**Issue by lishu2006ll** [nginxinc/kubernetes-ingress#2930]
HI,
 when  i update the nginx-ingress version , my kubernetes version is 1.18.0, I update my nginx-ingress1.7.2 to 1.11.0, tip error.

I0813 15:02:34.966766       1 main.go:258] Starting NGINX Ingress controller Version=1.11.0 GitCommit=b64a2f2
W0813 15:02:34.985322       1 main.go:297] The '-use-ingress-class-only' flag will be deprecated and has no effect on versions of kubernetes >= 1.18.0. Processing ONLY resources that have the 'ingressClassName' field in Ingress equal to the class.
F0813 15:02:34.988438       1 main.go:301] Error when getting IngressClass nginx: ingressclasses.networking.k8s.io "nginx" is forbidden: User "system:serviceaccount:nginx-ingress:nginx-ingress" cannot get resource "ingressclasses" in API group "networking.k8s.io" at the cluster scope

**Comment by brianehlert** [comment]
It looks as if your RBAC settings need to be updated.
However, I believe you are asking about a problem with the NGINX Ingress Controller maintained by the community, which is different from this project.
Support for that project is through their GitHub issues https://github.com/kubernetes/ingress-nginx/ or through their Slack organization: https://kubernetes.slack.com/archives/CANQGM8BA

**Comment by lishu2006ll** [comment]
> It looks as if your RBAC settings need to be updated. However, I believe you are asking about a problem with the NGINX Ingress Controller maintained by the community, which is different from this project. Support for that project is through their GitHub issues https://github.com/kubernetes/ingress-nginx/ or through their Slack organization: https://kubernetes.slack.com/archives/CANQGM8BA

hi,I tried nginx ingress, but I didn't use ingress nginx. That's why I'm here to find out how to solve this problem. Can you give me an upgrade method? Thank you very much, or what needs to be adjusted and what operations should be performed? thank you

**Comment by jasonwilliams14** [comment]
@lishu2006ll Per the error, looks like you are missing the serviceAccount permissions needed to read the CRD.
How did you install NGINX Ingress controller?
Manifests?
helm?
