### ISSUE TITLE
flag provided but not defined: -include-year

### ISSUE THREAD

**Issue by denissabramovs** [nginxinc/kubernetes-ingress#2968]
```
name: nginx-ingress
version: 0.14.0
appVersion: 2.3.0
```

`helm -n api install -f values.yaml nginx .`

Installing from sources, getting error from pod logs:
`flag provided but not defined: -include-year`

**Comment by denissabramovs** [comment]
kubernetes v1.24.3 and kubectl too

**Comment by denissabramovs** [comment]
helm v3.7.0

**Comment by denissabramovs** [comment]
This fixed it for me:
https://github.com/nginxinc/kubernetes-ingress/pull/2969

**Comment by shaun-nx** [comment]
Hi @denissabramovs can you confirm that you are on the latest version of `main` branch. 
The fix you applied in https://github.com/nginxinc/kubernetes-ingress/pull/2969 is working since the default value for `{{- if .Values.controller.includeYear }}` is `false`, so the template is just ignoring the `-include-year` flag.

**Comment by denissabramovs** [comment]
@shaun-nx in any case, need to check why runtime is throwing error `flag provided but not defined` when flag `includeYear` is included into final manifest.

**Comment by denissabramovs** [comment]
flag.Parse() is being called before your flag is defined.

You have to make sure that all flag definitions happen before calling flag.Parse(), usually by defining all flags inside init() functions.

source: https://stackoverflow.com/questions/29699982/go-test-flag-flag-provided-but-not-defined

**Comment by denissabramovs** [comment]
It seems that default values are assigned to undefined variables? I don't remember golang in depth, but shouldn't you define those variables before assigning values to them?
Possibly that's why it is complaining about it?

**Comment by denissabramovs** [comment]
Adding `includeYearInLogs bool` and others here:
```
var (

	// Injected during build
	version string

	// Info read from the binary
	commitHash = "unknown"
	commitTime = "unknown"
	dirtyBuild = true
	includeYearInLogs bool
```

**Comment by denissabramovs** [comment]
Or moving those into a separate function and call before flag.Parse().

**Comment by ciarams87** [comment]
Hi @denissabramovs - it looks like you are using the helm chart from main but the the image version is the last v2.3.0 tag - these flags were not defined yet in v2.3.0. If you want to use the latest version of the code, please use the `edge` image tag. It can be updated in the values.yaml file [here](https://github.com/nginxinc/kubernetes-ingress/blob/main/deployments/helm-chart/values.yaml#L52) Thanks!

**Comment by haywoodsh** [comment]
I was able to reproduce the exact error message when I installed from the sources in main branch with the `v2.3.0` image tag, but when I used the matching versions it worked as expected, i.e., deploying the `edge` image with `main` branch and `v2.3.0` image after checking out the `v2.3.0` tag.
