### ISSUE TITLE
Geo-blocking in Nginx-Ingress Helm Chart doesn't work at all

### ISSUE THREAD

**Issue by dbarranco** [nginxinc/kubernetes-ingress#2975]
Hello team, thanks for the work on the Nginx-Ingress 🙇 

These days I'm trying to enable geo-blocking for the Nginx-Ingress and I've noticed a weird behaviour between the [quick-start version](https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.3.0/deploy/static/provider/cloud/deploy.yaml) and the Nginx-Ingress Helm Chart.

**Describe the bug**

Following the [different tests related to geo-block](https://github.com/kubernetes/ingress-nginx/blob/main/test/e2e/settings/geoip2.go#L80) I configured the main ConfigMap and an Ingress Kubernetes resource to block countries. This is the actual configuration I have:

- Main Nginx-Ingress ConfigMap:

```
apiVersion: v1
data:
  allow-snippet-annotations: "true"
  http-snippet: |
    map $geoip2_city_country_code $blocked_country {
        default 0;
        ES 1;
    }
  use-forwarded-headers: "true"
  use-geoip2: "true"
...
```

- Ingress resource

```
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($blocked_country) {
        return 403;
      }
    nginx.ingress.kubernetes.io/use-regex: "true"
```
- The Nginx-Ingress deployment has configured the `--maxmind-license-key=<...>` and I can see in the logs that Nginx has downloaded the GeoIP2 database.

The main issue I've found after configuring this is that in the Nginx-Ingress Helm Chart (latest version) doesn't work while in the [quick start version](https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.3.0/deploy/static/provider/cloud/deploy.yaml) (latest one too) works fine. I've tried to look for any difference but I didn't find anything (both deployments configured with the same values / same containers and sha256...)

**To Reproduce**
If you would like to reproduce this:

- Install a Nginx-Ingress by getting the quick start link, latest version
- Add a Maxmind license key in the deployment
- Configure the main ConfigMap
- Deploy a dummy Ingress resource (I'm using the cafe example) and configure to block some contries
- Repeat the same with the Nginx-Ingress Helm Chart, latest version

**Expected behavior**
The behaviour should be the same in the quick start version and the Helm Chart one.

**Your environment**
- GKE 1.22.10-gke.600
- Helm Chart: ingress-nginx-4.2.3
- Quick start: latest available on the Nginx Ingress website.
- Using NGINX

**Comment by brianehlert** [comment]
The quickstart you reference is for the K8s community nginx ingress controller project (kubernetes/ingress-nginx)
This project is a separate and unique code base with different annotations.

Your best source for assistance with the community ingress project is their slack channel: https://kubernetes.slack.com/archives/CANQGM8BA
Or their GitHub: https://kubernetes.github.io/ingress-nginx

If you are using this project, please check your annotations.

**Comment by dbarranco** [comment]
Hey @brianehlert,

Thanks for your comment. Closing this issue.
