### ISSUE TITLE
Allow to specify image with digest in helm chart

### ISSUE THREAD

**Issue by hafe** [nginxinc/kubernetes-ingress#2978]
**Is your feature request related to a problem? Please describe.**
I want to be able to specify image with digest (instead of tag) for the following reasons:

- Using OKD/OpenShift ImageContentsourcePolicy requires you to specify image by digest
- It is more secure and a recommended practice to specify image by digest

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hafe** [comment]
Do I need todo something to get the pr reviewed?

**Comment by lucacome** [comment]
Hi @hafe thanks for bringing this up, I think it's a nice addition and we'll review the PR shortly.
