### ISSUE TITLE
Helm Chart values are not sorted alphabetically

### ISSUE THREAD

**Issue by aknot242** [nginxinc/kubernetes-ingress#2999]
**Describe the bug**
Helm Chart values are not sorted alphabetically, making it easy to miss specific values when scanning the page.

**Comment by brianehlert** [comment]
Through internal conversation we learned that the current scheme has functionality groupings, that would be broken by a blanket alphabetical sort.
We are looking into how to improve the usability and maintain some level of logical grouping without introducing breaking changes.

**Comment by aknot242** [comment]
Thank you @brianehlert!
