### ISSUE TITLE
New line at end of file required in TLS certificate & key

### ISSUE THREAD

**Issue by munnerz** [nginxinc/kubernetes-ingress#3]
When using TLS, it is required to have a newline at the end of the certificate and key, else nginx will fall into a crash loop as the certificate is invalid. I believe this is because the certificate and key are concatenated and loaded from the same file, and without the new line the certificate and key merge into one.

This should either be optional or documented behaviour to save others spending ages debugging!

Side note: thanks for the ingress controller!

**Comment by pleshakov** [comment]
Thx! I'll investigate the issue and add a comment/write a fix

**Comment by pleshakov** [comment]
Indeed, without a newline encoded in the value of a key, NGINX would fail to parse the generated pem file, which is a concatenation of a key and a certificate, and the controller would crash

https://github.com/nginxinc/kubernetes-ingress/pull/9 fixes the issue
