### ISSUE TITLE
can't create nginx-ingress-rc

### ISSUE THREAD

**Issue by YingBurden** [nginxinc/kubernetes-ingress#30]
docker logs container：
```
E0524 08:48:01.817603       1 nginx.go:200] Command nginx stdout: ""
E0524 08:48:01.817785       1 nginx.go:201] Command nginx stderr: "nginx: [alert] could not open error log file: open() \"/var/log/nginx/error.log\" failed (13: Permission denied)\n2016/05/24 08:48:01 [emerg] 13#13: open() \"/var/log/nginx/error.log\" failed (13: Permission denied)\n"
F0524 08:48:01.817898       1 nginx.go:202] Command nginx finished with error: exit status 1
```

**Comment by pleshakov** [comment]
What version of the controller are you using? Please make sure it is the latest -- nginxdemos/nginx-ingress:0.2

Do you pull the image from the DockerHub or you build the image on your own? Did you make any changes to the Dockerfile?

What version of Kubernetes are you running?

**Comment by YingBurden** [comment]
@pleshakov thanks，sorry，it's my wrong，I don‘t create the coffee-svc
