### ISSUE TITLE
How to use this in my private non GCP,AWS,Azure cloud

### ISSUE THREAD

**Issue by sujai1009** [nginxinc/kubernetes-ingress#300]
Hi, 

This solution is not working for me in windows machine. Plus if i have a private IP, how to assign it to ingress.

Simple how to setup my custom private cloud with a private ip, with a dns name configured in internet.

Thanks

**Comment by pleshakov** [comment]
Hi @sujai1009 

Consider using the NodePort to expose the Ingress controller pods or use a DeamonSet with port mapping as described here https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/installation.md#4-get-access-to-the-ingress-controller
