### ISSUE TITLE
NGINX Kubernetes POD goes into a crashloopback.

### ISSUE THREAD

**Issue by workhorse2020** [nginxinc/kubernetes-ingress#3012]
**Describe the bug**
When pod boots up it goes into a crashloopback

**To Reproduce**
'''
W0903 00:29:39.795830       1 flags.go:273] Ignoring unhandled arguments: []
I0903 00:29:39.795975       1 flags.go:190] Starting NGINX Ingress Controller Version=main_int_bld_29_SNAPSHOT_96b2cee PlusFlag=false
I0903 00:29:39.795980       1 flags.go:191] Commit=unknown Date=unknown DirtyState=true Arch=linux/amd64 Go=go1.18.5
I0903 00:29:39.804481       1 utils.go:167] Kubernetes version: 1.21.2
I0903 00:29:39.804516       1 main.go:210] Kubernetes version: 1.21.2
I0903 00:29:39.812461       1 main.go:326] Using nginx version: nginx/1.22.0
I0903 00:29:39.819979       1 manager.go:209] Writing secret to /etc/nginx/secrets/default
I0903 00:29:39.824053       1 manager.go:140] Writing main config to /etc/nginx/nginx.conf
I0903 00:29:39.824074       1 manager.go:141]
worker_processes  16;
daemon off;

error_log  stderr notice;
pid        /var/lib/nginx/nginx.pid;

events {
    worker_connections  20000;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    map $upstream_trailer_grpc_status $grpc_status {
        default $upstream_trailer_grpc_status;
        '' $sent_http_grpc_status;
    }

    access_log  /dev/stdout  main;

    log_format response_time '{"upstreamAddress":"$upstream_addr", "upstreamResponseTime":"$upstream_response_time", "proxyHost":"$proxy_host", "upstreamStatus": "$upstream_status"}';
    access_log syslog:server=unix:/var/lib/nginx/nginx-syslog.sock,nohostname,tag=nginx response_time;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout 65s;
    keepalive_requests 100;

    #gzip  on;

    server_names_hash_max_size 1024;
    server_names_hash_bucket_size 256;

    variables_hash_bucket_size 256;
    variables_hash_max_size 1024;

    map $request_uri $request_uri_no_args {
        "~^(?P<path>[^?]*)(\?.*)?$" $path;
    }

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }
    map $http_upgrade $vs_connection_header {
        default upgrade;
        ''      $default_connection_header;
    }

    server {
        # required to support the Websocket protocol in VirtualServer/VirtualServerRoutes
        set $default_connection_header "";
        set $resource_type "";
        set $resource_name "";
        set $resource_namespace "";
        set $service "";

        listen 80 default_server;
        listen [::]:80 default_server;

        listen 443 ssl default_server;
        listen [::]:443 ssl default_server;

        ssl_certificate /etc/nginx/secrets/default;
        ssl_certificate_key /etc/nginx/secrets/default;

        server_name _;
        server_tokens "on";

        location / {
            return 404;
        }
    }
    # stub_status
    server {
        listen 8080;
        listen [::]:8080;

        allow 127.0.0.1;

        deny all;

        location /stub_status {
            stub_status;
        }
    }
    server {
        listen unix:/var/lib/nginx/nginx-status.sock;
        access_log off;

        location /stub_status {
            stub_status;
        }
    }

    include /etc/nginx/config-version.conf;
    include /etc/nginx/conf.d/*.conf;

    server {
        listen unix:/var/lib/nginx/nginx-502-server.sock;
        access_log off;

        return 502;
    }

    server {
        listen unix:/var/lib/nginx/nginx-418-server.sock;
        access_log off;

        return 418;
    }
}

stream {
    log_format  stream-main  '$remote_addr [$time_local] '
                      '$protocol $status $bytes_sent $bytes_received '
                      '$session_time "$ssl_preread_server_name"';

    access_log  /dev/stdout  stream-main;

    include /etc/nginx/stream-conf.d/*.conf;
}
I0903 00:29:39.824266       1 manager.go:350] Writing config version to /etc/nginx/config-version.conf
I0903 00:29:39.824323       1 manager.go:351] server {
    listen unix:/var/lib/nginx/nginx-config-version.sock;
        access_log off;

    location /configVersion {
        return 200 0;
    }
}
map $http_x_expected_config_version $config_version_mismatch {
        "0" "";
        default "mismatch";
}
I0903 00:29:39.824412       1 manager.go:276] Starting nginx
I0903 00:29:39.824967       1 verify.go:68] Starting poll for updated nginx config
F0903 00:29:39.824984       1 manager.go:291] Could not get newest config version: could not get expected version: 0 after 0s
'''
Above is logs 

**Expected behavior**
This is built from the 2.3.0 source code official build loads fine. 

**Your environment**
Version of the Ingress Controller 2.3.0
Version of Kubernetes 1.21
Kubernetes platform onPrem
Using NGINX

**Comment by workhorse2020** [comment]
I came across
https://my.f5.com/manage/s/article/K000091316

but I am not using a nginx plus version

**Comment by brianehlert** [comment]
The solution can still apply.  The only difference is nginx vs nginx plus - the rest of the code is the same.
