### ISSUE TITLE
DNS01 Solver support from VirtualServer 

### ISSUE THREAD

**Issue by ntpct1993** [nginxinc/kubernetes-ingress#3016]
Hi, currently, our system will block all HTTP requests (port 80 traffics), but the VirtualServer now only supports the HTTP01 solver (According to the 2.3.0 Release Notes)
Thus, in order to solve this issue, we would like to use DNS01 instead (which already supported in Issuers - cert-manager)

**Comment by ntpct1993** [comment]
Here is the release notes link: https://docs.nginx.com/nginx-ingress-controller/releases/#nginx-ingress-controller-230

Support HTTP01 type ACME Issuers for use with VirtualServer resources with [cert-manager](https://cert-manager.io/docs/).

**Comment by brianehlert** [comment]
Release 2.2 added initial support for cert-manager for VirtualServer, including the DNS01 issuer.  
Release 2.3 extended that with added support for HTTP01 ACME issuer.

The first entry in the overview: https://docs.nginx.com/nginx-ingress-controller/releases/#nginx-ingress-controller-220

**Comment by ntpct1993** [comment]
That 2.2 entry description is quite confusing to me about the DNS01 support
Anyway, thanks for your clarification
