### ISSUE TITLE
Nginx rewrite to external site

### ISSUE THREAD

**Issue by sanjinp** [nginxinc/kubernetes-ingress#302]
Hello, I was digging about this option, but couldn't find any resolution.
Particular case is that ingress will be used to route example.com -> example.io (external, out of kubernetes)
But other subdirectories example.com/test1, example.com/test2, example.com/test3 would be redirected to internal services respectively, is it something supported by ingress?

**Comment by pleshakov** [comment]
@sanjinp unfortunately, we don't support routing to external destinations yet. you can take a look at this ingress controller  https://github.com/kubernetes/ingress-nginx which might support it.
