### ISSUE TITLE
Customization of proxy_* parameters within /location

### ISSUE THREAD

**Issue by devops-42** [nginxinc/kubernetes-ingress#309]
Hi,

is it possible to customize the`proxy_*` parameters? For my deployment I need to set a special "Host" header by `proxy_set_header`. As far as I can see in the templates an immutable  `proxy_*` parameter block will be created for each location.

Thx for your help!

**Comment by isaachawley** [comment]
Hi,

While we don't officially support setting a custom host it looks like this can be accomplished using location snippets, and in the next release we will support [custom templates](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/custom-templates).

I added a location snippet to the ingress resource similar to [this](https://github.com/nginxinc/kubernetes-ingress/blob/master/examples/customization/cafe-ingress-with-annotations.yaml)
```
nginx.org/location-snippets: |
         proxy_set_header Host custom-host;
```

I'm using the [nginx hello demo](https://hub.docker.com/r/nginxdemos/hello/) as my test upstream and I edited the config file so it returns the Host request header as well (`$http_host`):
```
server {
    listen 80;

    location / {
        default_type text/plain;
        expires -1;
        return 200 'Server address: $server_addr:$server_port\nServer name: $hostname\nDate: $time_local\nURI: $request_uri\nRequest ID: $request_id\n host: $http_host \n';
    }
}
```

The response body:
```
curl -k -H "Host: cafe.example.com" https://35.234.117.213/coffee
Server address: 10.8.1.10:80
Server name: coffee-f5cd54465-nhjw8
Date: 13/Jul/2018:13:07:40 +0000
URI: /coffee
Request ID: bc284ce740f77349948c2717b28b1e3d
 host: custom-host
```

This is a bit hacky but I hope it works for you.

**Comment by isaachawley** [comment]
If you want to test your setup with custom templates you could [build from source](https://github.com/nginxinc/kubernetes-ingress/tree/master/nginx-controller), then you'd be ready to go when the release is ready.

We're trying to squeeze a couple more features into the next release. It might be ready in the next couple of weeks, but we haven't committed to a date yet.
