### ISSUE TITLE
Enforce HTTPS for backend service

### ISSUE THREAD

**Issue by sumanraja** [nginxinc/kubernetes-ingress#3164]
Do we have any way by which we can enforce nginx ingress controller to backend service over https only. 
I found below annotation on nginx kubernetes.io, 
nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

Do we have any equivalent annotation or mechanism to enforce end to end encryption with tls. 

We are using nginxinc/kubernetes-ingress only.

**Comment by jasonwilliams14** [comment]
@sumanraja Hello there.
Take a look at our annotation page:

https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/#auth-and-ssltls

Specifically, the one I believe you are looking for is:

```
nginx.org/ssl-services
```

HTH

**Comment by sumanraja** [comment]
Thanks @jasonwilliams14.
We are actually trying to enforce https communication for pod to pod connectivity from nginx ingress controller. So want to enforce https backend only for ingress.yaml.
nginx controller pod ----tls---- application pod.

Do you know any global configuration (preferably via configmap) so it will discard any backend communication without https.

**Comment by jasonwilliams14** [comment]
@sumanraja you can use snippets for ingress resource, or you can use your CRDs that have built in functionality, making it make easier and far more powerful than standard ingress:

Take a look at our IngressMTLS and EgressMTLS:

https://docs.nginx.com/nginx-ingress-controller/configuration/policy-resource/#ingressmtls

https://docs.nginx.com/nginx-ingress-controller/configuration/policy-resource/#egressmtls

**Comment by brianehlert** [comment]
There are two ways to look at this.

1. TLS offload at the ingress controller and re-encryption to the backend service.  
     This is what http://nginx.ingress.kubernetes.io/backend-protocol HTTPS does
     And also what https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/#auth-and-ssltls:~:text=nginx.org/ssl%2Dservices does.

2. mTLS authentication to the backend service or an externalName service
     This is using the certificate for both TLS and authentication (identity verification), which is additional protection beyond encryption.

The certificates used for each option are different.  And both require the backend service to handle a server certificate in some way.

Considering the original annotation that you inquired about, I suspected you are really looking for the first one.
Or, you are actually looking for something entirely different.

**Comment by agill17** [comment]
I had a similar issue, is it true that we have use this annotation `nginx.org/ssl-services` over `nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"` when running nginx-plus ?

**Comment by rd-an** [comment]
@agill17  Thank you for your response, it solved a problem that has been troubling me for several days
