### ISSUE TITLE
Client max body size - Nginx/Aks

### ISSUE THREAD

**Issue by vandhanaelango** [nginxinc/kubernetes-ingress#3166]
I’m trying to increase the limit for client_max_body_size to 5m in nginx configuration. This change is not reflected, it defaults to 1m and ends up with 413 error. Please find the ingress file below

Ngnix Ingress Controller: 2.3.0

ingress.yaml:

apiVersion: http://networking.k8s.io/v1
kind: Ingress
metadata:
  name: cafe-ingress
  annotations:
    http://nginx.org/proxy-connect-timeout: "30s"
    http://nginx.org/proxy-read-timeout: "20s"
    http://nginx.org/client_max_body_size: "999m"
    http://nginx.org/server-snippets: |
      location / {
          return 302 /coffee;
      }
    http://nginx.org/location-snippets: |
            add_header Content-Security-Policy "default-src 'self'";
            add_header X-XSS-Protection "1";
            add_header X-Content-Type-Options nosniff;
            add_header Referrer-Policy "strict-origin";
            add_header X-Frame-Options "SAMEORIGIN";
            add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    http://nginx.ingress.kubernetes.io/server-snippet: |
      ssl_stapling on;
      ssl_stapling_verify on;
spec:
        #  tls:                                # add those 4 lines
        #  - hosts:                            #
        #    - http://cafe.example.com                 #
        #secretName: ingress-local-tls     #
  ingressClassName: nginx-1
  rules:
  - host: http://cafe.example.com
    http:
      paths:
      - path: /tea
        pathType: Prefix
        backend:
          service:
            name: tea-svc
            port:
              number: 80
      - path: /coffee
        pathType: Prefix
        backend:
          service:
            name: coffee-svc
            port:
              number: 80

**Comment by brianehlert** [comment]
Have you already tried the configmap-resource?
https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/

**Comment by brianehlert** [comment]
Also, you might want to check your server-snippet annotation
https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-snippets/

the ssl_stapling won't be applied if that is important to your verification.

**Comment by vandhanaelango** [comment]
Will share that shortly

**Comment by vandhanaelango** [comment]
sources:
  - https://github.com/nginxinc/kubernetes-ingress/tree/v2.3.0/deployments/helm-chart

values.yaml

 config:
    ## The name of the ConfigMap used by     the Ingress controller.
    ## Autogenerated if not set or set to "".
    # name: nginx-config
    proxy-body-size: "256m"
    client_max_body_size: "5m"
    proxy-buffer-size: "8k"
    keepalive-timeout: "10s"
    ## The annotations of the Ingress Controller configmap.
    annotations:
       [nginx.org/client-max-body-size](http://nginx.org/client-max-body-size): "3m"

    ##headers under config
    add-headers: "nginx-ingress/custom-headers"
    headers:
      X-XSS-Protection: "1; mode=block"
      Content-Security-Policy: "default-src 'self';"

    ## The entries of the ConfigMap for customizing NGINX configuration.
    entries:
      keepalive: "7"
      client_max_body_size: "5m"
      proxy-body-size: "5m"
      proxy-connect-timeout: "10s"
      proxy-read-timeout: "10s"
      proxy-buffer-size: "4k"
  



app.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tea
  template:
    metadata:
      labels:
        app: tea
    spec:
      containers:
      - name: tea
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tea-svc
  labels:
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: tea

**Comment by vandhanaelango** [comment]
sources:   - https://github.com/nginxinc/kubernetes-ingress/tree/v2.3.0/deployments/helm-chart

values.yaml
 config:
    ## The name of the ConfigMap used by the Ingress controller.
    ## Autogenerated if not set or set to "".
    # name: nginx-config
    proxy-body-size: "256m"
    client_max_body_size: "5m"
    proxy-buffer-size: "8k"
    keepalive-timeout: "10s"
    ## The annotations of the Ingress Controller configmap.
    annotations:
       [nginx.org/client-max-body-size](http://nginx.org/client-max-body-size): "5m"

    ##headers under config
    add-headers: "nginx-ingress/custom-headers"
    headers:
      X-XSS-Protection: "1; mode=block"
      Content-Security-Policy: "default-src 'self';"
## The entries of the ConfigMap for         customizing NGINX configuration.
    entries:
      keepalive: "7"
      client_max_body_size: "5m"
      proxy-body-size: "5m"
      proxy-connect-timeout: "10s"
      proxy-read-timeout: "10s"
      proxy-buffer-size: "4k"
  

app.yaml
apiVersion: apps/v1 kind: Deployment metadata:   name: tea spec:   replicas: 3   selector:     matchLabels:       app: tea   template:     metadata:       labels:         app: tea     spec:       containers:       - name: tea         image: nginxdemos/nginx-hello:plain-text         ports:         - containerPort: 80 --- apiVersion: v1 kind: Service metadata:   name: tea-svc   labels: spec:   ports:   - port: 80     targetPort: 80     protocol: TCP     name: http   selector:     app: tea

**Comment by vandhanaelango** [comment]
sources:
  - https://github.com/nginxinc/kubernetes-ingress/tree/v2.3.0/deployments/helm-chart

values.yaml

 config:
    ## The name of the ConfigMap used by the Ingress controller.
    ## Autogenerated if not set or set to "".
    # name: nginx-config
    proxy-body-size: "256m"
    client_max_body_size: "5m"
    proxy-buffer-size: "8k"
    keepalive-timeout: "10s"
    ## The annotations of the Ingress Controller configmap.
    annotations:
       [nginx.org/client-max-body-size](http://nginx.org/client-max-body-size): "3m"

    ##headers under config
    add-headers: "nginx-ingress/custom-headers"
    headers:
      X-XSS-Protection: "1; mode=block"
      Content-Security-Policy: "default-src 'self';"

    ## The entries of the ConfigMap for customizing NGINX configuration.
    entries:
      keepalive: "7"
      client_max_body_size: "5m"
      proxy-body-size: "5m"
      proxy-connect-timeout: "10s"
      proxy-read-timeout: "10s"
      proxy-buffer-size: "4k"

  

app.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tea
  template:
    metadata:
      labels:
        app: tea
    spec:
      containers:
      - name: tea
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tea-svc
  labels:
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: tea

**Comment by vandhanaelango** [comment]
@brianehlert Is there any solution you could suggest after checking our deployment files ?

**Comment by DeyvsonL** [comment]
I was able to work around this one by setting the annotation for the ingress resource.

nginx.ingress.kubernetes.io/proxy-body-size: 5m

By setting the proxy-body-size, it is going to update the client_max_body_size.
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#proxy-body-size
