### ISSUE TITLE
Helm chart CRD and/or documentation issue

### ISSUE THREAD

**Issue by AlexGoris-KasparSolutions** [nginxinc/kubernetes-ingress#3196]
**Describe the bug**
The current [helm chart documentation](https://github.com/nginxinc/kubernetes-ingress/tree/main/deployments/helm-chart) describes the following under [Installing the chart](https://github.com/nginxinc/kubernetes-ingress/tree/main/deployments/helm-chart#installing-the-crds):
> ... The Helm client will install those CRDs....

Then under [Upgrading the chart](https://github.com/nginxinc/kubernetes-ingress/tree/main/deployments/helm-chart#upgrading-the-crds
> Helm does not upgrade the CRDs during a release upgrade. Before you upgrade a release, run the following command to upgrade the CRDs:
   ```
   $ kubectl apply -f crds/
   ```

Which tells me the chart will install the CRD's only once during an initial install, but henceforth not upgrade them ever again during a release upgrade.
However, the instruction given on how to upgrade the CRD's (running `kubectl apply -f crds/`) is confusing because it obviously requires to have the CRD definitions available in a `crds` subfolder relative to the working directory you're residing in when running the command.

From this perspective this should be a documentation issue, it should be clear to the reader of said documentation that through some process, one is to obtain the CRD definitions and save them in a `crds` subfolder. When reading the domentation on [Nginx's website](https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/), it is not at all obvious that one might find those CRD definitions in the github repo linked to the helm chart they are deploying.

I'm also wondering how one is supposed to manage this in an environment where this helm chart is deployed in a CD pipeline. The best solution I can come up with, is the copy the CRD's from this repo in our internal repo's, and deploy them like that, but I don't like copy/pasting external code into our own repositories, they should be provided as build artifacts in a well-known fixed location (github release artifact e.g.) so one can use the well-known link in a CD pipeline.

A much nicer solution would be to have the helm chart upgrade the CRDs as well as install them initially, perhaps that can be looked into.

**To Reproduce**
1. Install using the helm chart
2. See everything working (including CRDs)
3. Upgrade helm chart to next version
4. Find outdated CRDs and no clear documentation on how to update them

**Expected behavior**
PReferably helm chart should upgrade CRDs as part of a release upgrade. If this is too difficult, documentation should provide clear steps on how to upgrade CRDs as well.

**Your environment**
* Version of the Ingress Controller: 2.3.0
* Version of Kubernetes: 1.24.4
* Kubernetes platform (e.g. Mini-kube or GCP): Azure AKS
* Using NGINX or NGINX Plus: Nginx plus

**Comment by jasonwilliams14** [comment]
@AlexGoris-KasparSolutions Hello there and thank you for your feedback.

> Which tells me the chart will install the CRD's only once during an initial install, but henceforth not upgrade them ever again during a release upgrade.

That is correct. That is actually a helm specific item and how the project decided to handle CRDs. You can read more on their site, but here is a document that discusses this exact topic.

https://github.com/helm/community/blob/f9e06c16d89ccea1bea77c01a6a96ae3b309f823/architecture/crds.md

> However, the instruction given on how to upgrade the CRD's (running kubectl apply -f crds/) is confusing because it obviously requires to have the CRD definitions available in a crds subfolder relative to the working directory you're residing in when running the command.

The expectation from our docs is that the user has already cloned our repo, to gain access to the `crd` folder:

```
git clone https://github.com/nginxinc/kubernetes-ingress.git --branch v2.4.1
```

However, I think we can add a step in the upgrade section that would ensure the customer has cloned the repo or updated it to grab the latest changes and CRDs, making the install/upgrade documents more complete. I will look at to add that to our documentation.

**Comment by AlexGoris-KasparSolutions** [comment]
@jasonwilliams14 thanks for your reply. The helm article you linked was a very interesting read and clarifies why this issue is not trivial to solve.

As I stated in my original question, cloning the crds from this repo and applying them when needed works for a human performing an installation, but for installing nginx through a CD pipeline (using helm) this becomes non-trivial. The easiest solution I found thus far is to copy the crd definitions into our own codebase (the same as where our terraform scripts reside which control the helm deployment for nginx), but it doesn't feel right and might cause unwanted overhead (we have a pull-request with mandatory appovals process in place for all our repositories) in the future if those CRDs need updating.

Might I suggest taking a look at the way linkerd seems to have solved this ([relevant docs](https://linkerd.io/2.12/tasks/install-helm/))? They provide separate charts for the application (`linkerd-control-plane`) and the crds (`linkerd-crds`), which gives the user complete control over when to update which component.

**Comment by jasonwilliams14** [comment]
@AlexGoris-KasparSolutions The option to create a separate chart for our CRDs is something that we have discussed internally for some time now. Without divulging too much right now,, we do have quite a few things planned for our project, including adding helm capabilities and/or options.  Keep a close eye on our project and look for our announcements. 👍
