### ISSUE TITLE
Ingress resource in different namespace

### ISSUE THREAD

**Issue by achandak123** [nginxinc/kubernetes-ingress#328]
Hi,
    Is it possible to have a single ingress controller catering to 2 ingress resources, each one in different namespace? I tried setting up using minion way, but doesn't seem to be working.

**Comment by Dean-Coakley** [comment]
Hi @achandak123 

Can you provide details of what you've tried? If you need some ideas of what to include, please see the [bug template](https://github.com/nginxinc/kubernetes-ingress/issues/new?template=bug_report.md) and post what you can here.

If you want to try debugging your issues yourself setting [logging verbosity](https://github.com/nginxinc/kubernetes-ingress/blob/master/install/deployment/nginx-ingress.yaml#L37) to 3 can be very helpful

I just tested a modified [minion example](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/mergeable-ingress-types#running-the-example): 
* Ingress Controller in nginx-ingress namspace
* Master cafe ingress resource in default namespace
* Coffee minion ingress resource in coffee-minion namespace
* Tea minion ingress resource in tea-minon namespace

[Get access to the Ingress Controller](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/installation.md#4-get-access-to-the-ingress-controller)

Successfully tested `curl` command to both tea and coffee minions


Hope this helps!
