### ISSUE TITLE
Client-max-body-size in nginx ingress controller 

### ISSUE THREAD

**Issue by vandhanaelango** [nginxinc/kubernetes-ingress#3308]
Hi,

I am using nginx ingress controller in AKS and also increased the file upload size limit by adding the following annotation to the ingress file,
nginx.org/client-max-body-size: "20m"

Could you please help me with the min/max limit size for the client-max-body-size.

Regards,
Vandhana

**Comment by tomasohaodha** [comment]
Hello @vandhanaelango 

The reference documentation for that directive can be found here: https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

The units used are here: https://nginx.org/en/docs/syntax.html

Setting it to 0 turns off size checking. Max setting would probably be max_int gigabytes.

**Comment by vepatel** [comment]
closing this as per https://github.com/nginxinc/kubernetes-ingress/blob/main/ISSUE_LIFECYCLE.md
