### ISSUE TITLE
RBAC issue - endpoints list api access missing?!

### ISSUE THREAD

**Issue by de1chk1nd** [nginxinc/kubernetes-ingress#3314]
**Describe the bug**
Just installed a new version of ingress controller in my lab - it failed working.
It started - but readiness probe was down

NAME                             READY   STATUS    RESTARTS   AGE
nginx-ingress-7477944d9f-8fxbf   0/1     Running   0          18s

checked logs he complained about RBAC:

W1126 21:06:42.415149       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.25.3/tools/cache/reflector.go:169: failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:nginx-ingress:nginx-ingress" cannot list resource "endpoints" in API group "" at the cluster scope
E1126 21:06:42.415180       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.25.3/tools/cache/reflector.go:169: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:nginx-ingress:nginx-ingress" cannot list resource "endpoints" in API group "" at the cluster scope
W1126 21:06:44.224638       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.25.3/tools/cache/reflector.go:169: failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:nginx-ingress:nginx-ingress" cannot list resource "endpoints" in API group "" at the cluster scope
E1126 21:06:44.224667       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.25.3/tools/cache/reflector.go:169: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:nginx-ingress:nginx-ingress" cannot list resource "endpoints" in API group "" at the cluster scope
E1126 21:06:47.455966       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.25.3/tools/cache/reflector.go:169: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:nginx-ingress:nginx-ingress" cannot list resource "endpoints" in API group "" at the cluster scope

manually added:

- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - list

to RBAC.yaml - now it seems to work.

**To Reproduce**
1. deployed current version of ingress controller - most resourced directy pulled from git.
2. nginx starts - but does not get ready - ingress link do not add ressources to bigip
3. added new rbac statement according to nginx logs -> seems to work

**Expected behavior**
install working w/o need to modify rbac ;)

**Your environment**
* 2.4.1
* EKS ->v1.22.15-eks-fb459a0
* EKS
* Using NGINX Plus

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by jasonwilliams14** [comment]
@de1chk1nd what branch are you using?
Sounds like you are on edge.
Try using a branch like 2.4.1

**Comment by de1chk1nd** [comment]
> @de1chk1nd what branch are you using? Sounds like you are on edge. Try using a branch like 2.4.1

hi - yes. i was in main branch (my script pulls it from main). in 2.4.1 it seems to be solved...waiting to get this pushed to main than and pull this rbac from 2.4.1 branch :D

thx!
