### ISSUE TITLE
Support for custom environment variables

### ISSUE THREAD

**Issue by AaronShiels** [nginxinc/kubernetes-ingress#3319]
**Is your feature request related to a problem? Please describe.**
The Helm charts supports customisation of ports and volume mounts, but no customisation of environment variables. For those using technologies like NJS, being able to set additional environment variables is incredibly useful and, when it comes to things like JWT decryption, an outright security requirement.

**Describe the solution you'd like**
Extend the templates such that the below block would work in a values.yaml override
```
controller:
  env:
  - name: FOO
    value: bar
```

**Describe alternatives you've considered**
There are currently no workarounds outside of dropping the Helm chart and working with raw manifests.

**Additional context**
N/A

**Comment by brianehlert** [comment]
For things like JWT or token decryption, I would not introduce these as env vars, but rather as aspects of the related Policy YAML.
Token.foo=$foo
Token.bar=$bar

And define a format in which to actually break down the necessary portions of the token and possibly even the headers to associate them with.

Maybe help us understand the variable that you have and how you would use them?

**Comment by AaronShiels** [comment]
I'm using the NJS method of validating JWTs due to some additional custom logic I'd like to run. My code is inspired by the most comprehensive set of examples found [here](https://github.com/nginx/njs-examples#generating-jwt-token-http-authorization-gen-hs-jwt). where you can see they are mounting the secrets through environment variables.

Without the ability to set environment variables, the entire NJS featureset is severely limited, as env vars are the JS standard method of passing configuration at runtime, and the standard method of passing secrets to containers.

**Comment by brianehlert** [comment]
I am trying to take the Docker container assumptions of env vars and bring those to K8s, secret management methods, etc.

The pattern I already see is that a JWT is passed by a client and needs verification and parsing and evaluation.
And secrets are commonly handled by K8s and resolved when the secret object is retrieved through the K8s API.

A client token as part of the request comes in as a known variable.
I see env vars as vars that are introduced at start time.  So, all the pods derived from a particular image start with the same vars and all the pods in a deployment would share the same starting value for a particular var.

I am not making the leap of full grasping the pattern you are proposing.  Sorry for that, if you could help me it would be appreciated.  Maybe it is that I am not understanding how you are using JWT.

**Comment by AaronShiels** [comment]
Not a problem, I appreciate your time!

The point of confusion could be the fact that I am using NJS to validate JWTs using some additional custom logic, so I am _not_ using the default functionality for validating JWTs available in the Nginx Controller.

# Problem with Official Example
The implementation I have is based off of this specific snippet https://github.com/nginx/njs-examples#authorizing-requests-using-auth-request-http-authorization-auth-request. I've copy-pasted the relevant blocks below.
nginx.conf:
```
env SECRET_KEY;

http {
  js_path "/etc/nginx/njs/";

  js_import main from http/authorization/auth_request.js;

  upstream backend {
      server 127.0.0.1:8081;
  }

  server {
      listen 80;

      location /secure/ {
          auth_request /validate;

          proxy_pass http://backend;
      }

      location /validate {
          internal;
          js_content main.authorize;
      }
  }

  server {
      listen 127.0.0.1:8081;
      return 200 "BACKEND:$uri\n";
  }
}
```
example.js:
```
function authorize(r) {
    var signature = r.headersIn.Signature;

    if (!signature) {
        r.error("No signature");
        r.return(401);
        return;
    }

    if (r.method != 'GET') {
        r.error(`Unsupported method: ${r.method}`);
        r.return(401);
        return;
    }

    var args = r.variables.args;

    var h = require('crypto').createHmac('sha1', process.env.SECRET_KEY);

    h.update(r.uri).update(args ? args : "");

    var req_sig = h.digest("base64");

    if (req_sig != signature) {
        r.error(`Invalid signature: ${req_sig}\n`);
        r.return(401);
        return;
    }

    r.return(200);
}

export default {authorize}
```

As you can see in the JavaScript snippet, validating the JWT hinges on `process.env.SECRET_KEY`. I need to be able to load an environment variable securely onto the Nginx Controller container.

# Solution
Exposing this in the Helm chart alongside other pod mutators like `customPorts`,` volumeMounts`, `initContainers` feels like the most intuitive solution for this one, and relatively easy. I'm actually preparing a PR now, so let me know if that makes sense and you're happy for me to proceed.

**Comment by shaun-nx** [comment]
Closing as feature request is now merge in https://github.com/nginxinc/kubernetes-ingress/pull/3326
