### ISSUE TITLE
Nginx-Plus pod is not starting (Expecting: TRUSTED CERTIFICATE)

### ISSUE THREAD

**Issue by andreyshamray** [nginxinc/kubernetes-ingress#333]
**Describe the bug**
Hi guys, we have trying to deploy helm chart with nginx-plus and for some reason, a pod is not starting - CrashLoopBackOff
**To Reproduce**
1. Deploy Nginx Plus chart to Kubernetes cluster using values-plus.yaml
```helm install --name my-release -f values-plus.yaml .```
Before that, I have created cert using generate_default_cert_and_key.sh, because 
```Set GENERATE_DEFAULT_CERT_AND_KEY to 1```
 is not creating a file for some reason. Also, I have added certificate (nginx-repo.crt) and the key (nginx-repo.key) to nginx-controller folder and run make command. 

2. View logs on k8s master node using kubectl
```
$ kubectl logs nginx-ingress-5cbf7f9668-gvdnn
```
3. See error
```
$ kubectl get pods
NAME                                           READY     STATUS             RESTARTS   AGE
nginx-ingress-5cbf7f9668-gvdnn                 0/1       CrashLoopBackOff   1          15s
```
```
$ kubectl logs nginx-ingress-5cbf7f9668-gvdnn
I0807 12:59:19.848623       1 main.go:92] Starting NGINX Ingress controller Version=1.2.0 GitCommit=f446d72
2018/08/07 12:59:19 [emerg] 16#16: PEM_read_bio_X509_AUX("/etc/nginx/secrets/default") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
nginx: [emerg] PEM_read_bio_X509_AUX("/etc/nginx/secrets/default") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
F0807 12:59:20.364882       1 main.go:211] Failed to create NginxAPIController: error accessing the API: http://127.0.0.1:8080/api is not accessible: Get http://127.0.0.1:8080/api: dial tcp 127.0.0.1:8080: getsockopt: connection refused
```
**Expected behavior**
I am expecting pod STATUS should be Running. And Ingress Controller will start to work)

**Your environment**
* Version of the Ingress Controller - release version or a specific commit
nginx-plus-ingress   1.2.0
* Version of Kubernetes
v1.10.3
* Kubernetes platform (e.g. Mini-kube or GCP)
On premisses cluster
* Using NGINX or NGINX Plus
NGINX Plus
**Additional context**
So there is not enough self-signed cert for deploying Nginx Plus? Should we need to buy a Trusted one? 
Thanks in advance!

**Comment by Dean-Coakley** [comment]
Hi @andreyshamray

Thanks for including all this detail in this bug report. Highly appreciated!

I haven't been able to reproduce your issue, but I suspect you haven't uncommented the `ADD` step in the Dockerfile as mentioned [here](https://github.com/nginxinc/kubernetes-ingress/tree/master/nginx-controller#makefile-variables)?

Hope this helps!

**Comment by andreyshamray** [comment]
Hi, sure, it was uncommented)

**Comment by andreyshamray** [comment]
Hi, yes, I have replaced these values with the output of generate_default_cert_and_key.sh.
Also, I have tried to deploy chart with default one cert/key and pod is Starting.

**Comment by andreyshamray** [comment]
So maybe the problem with cert/key string( I am extracting values by this command:
```echo `cat default.pem` | sed 's/ //g'```

**Comment by Dean-Coakley** [comment]
Ah I see

The issue here is that cert/key in values.yaml are expecting base64 encoded cert/key
```
$ openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout default.key -out default.crt -subj "/CN=NGINXIngressController"
$ cat default.key | base64
$ cat default.crt | base64
```

**Comment by andreyshamray** [comment]
Aha, thanks now it works. Unfortunately, it was not so clear for me threw instruction steps)
But, really thank you with helping on this)!

**Comment by Dean-Coakley** [comment]
No problem @andreyshamray 

I agree, I'll try think about how to make this clearer in the instructions! Thanks for the feedback
