### ISSUE TITLE
backend service name annotation value for nginx.org/ssl-services

### ISSUE THREAD

**Issue by ArchanaSoundararajan** [nginxinc/kubernetes-ingress#3330]
**Describe the bug**
We are adding annotation nginx.org/ssl-services: <backend service name> in ingress file
**To Reproduce**
Add annotation in ingress file nginx.org/ssl-services: <backend service name>

how to pass the backend service name automatically something like this {{ .backend.service.name }}
nginx.org/ssl-services:  {{ .backend.service.name }}

is it possible?
**Your environment**
* Version of the Ingress Controller - 2.3.0

* Kubernetes platform- aks
* Using NGINX 

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by ArchanaSoundararajan** [comment]
hi team,

can you please let us know how to add all the backend service names in nginx.org/ssl-services instead of adding each backend service names is there any wildcard can we use?

**Comment by jasonwilliams14** [comment]
@ArchanaSoundararajan Hello. I am not sure what you are asking. 
Are you asking how to use other tools to populate your value for `nginx-org/ssl-services` ?
the annotation itself needs to point to a service, that you will connect via HTTPS or gRPC over ssl, to the service endpoint.

We have an example located here:
https://github.com/nginxinc/kubernetes-ingress/tree/v2.4.2/examples/ingress-resources/ssl-services

**Comment by Samizr** [comment]
@jasonwilliams14 I'm facing this issue too.

Basically I want to annotate my ingress with 
```
nginx.org/ssl-services: <serviceName>
```
But in many cases I do not know the name of the service, for example if I'm using a helm chart that has the service built in.
Instead I just want something like
```
nginx.org/ssl-services: "*"
```
Where Nginx will treat ALL backend services as TLS backends. 
Is this possible?
