### ISSUE TITLE
Missing role for endpoints in rbac.yaml

### ISSUE THREAD

**Issue by gyaka4** [nginxinc/kubernetes-ingress#3393]
**Describe the bug**
I just did a vanilla setup via manifest without App Protect and with "-enable-custom-resources=false" flag and ingress-controller pod was unable to start, due to a missing cluster role:

W1222 14:36:41.653278       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.25.3/tools/cache/reflector.go:169: failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:nginx-ingress:nginx-ingress" cannot list resource "endpoints" in API group "" at the cluster scope

Issue was cleared out after adding "list,watch" verbs for "endpoints" in the mentioned cluster role.

**To Reproduce**
1. Follow "Installation with Manifests" guide
2. kubectl logs $pod-name -n nginx-ingress
3. See error

**Expected behavior**
ingress-controller pod should be able to list endpoints out-of-the-box.

**Your environment**
* Version of the Ingress Controller - release version or a specific commit
2.4.2
* Version of Kubernetes
1.23.4
* Kubernetes platform (e.g. Mini-kube or GCP)
Open Telekom Cloud CCE
* Using NGINX or NGINX Plus
NGINX

Could you please have a look?

**Comment by vepatel** [comment]
Hi @gyaka4, if you're installing  NIC 2.4.2 via manifests can you please make sure you're on `v2.4.2` tag or `release-2.4 `branch not `main`? 
those verbs are there for 2.4.2, see https://github.com/nginxinc/kubernetes-ingress/blob/v2.4.2/deployments/rbac/rbac.yaml#L10

**Comment by gyaka4** [comment]
Hi @vepatel, ah you are right sry. Then all good, thanks for checking it quickly.
