### ISSUE TITLE
Add option to set location-snippets per location

### ISSUE THREAD

**Issue by nicon89** [nginxinc/kubernetes-ingress#3398]
**Is your feature request related to a problem? Please describe.**
Problem: when I set location-snippets they are applied to all locations.

**Describe the solution you'd like**
I would like to set different location snippets depending on the location. 
For example I would like to add caching for location ~* \.(jpg|png), but not for /

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by vepatel** [comment]
Hi @nicon89, If you're using `virtualserver` then you can define `location-snippets` per `path`:
`routes:
  - path: /tea
    location-snippets: |
      proxy_cache one;
      proxy_cache_valid 200 10m;      
    action:
      pass: tea
  - path: /coffee
    action:
      pass: coffee`
      
 see: https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#using-snippets

**Comment by nicon89** [comment]
Thanks, that did the work!
