### ISSUE TITLE
"...Expecting: TRUSTED CERTIFICATE..." error when using nginx kubernetes ingress

### ISSUE THREAD

**Issue by dick-twocows** [nginxinc/kubernetes-ingress#341]
**Describe the bug**

invalid nginx configuration after applying ingress

$ kubectl describe ingress ydos-ingress -n ydos
Name:             ydos-ingress
Namespace:        ydos
Address:
Default backend:  default-http-backend:80 (<none>)
TLS:
  wildcard-yellowdog-tech-secret terminates yellowdog.tech
Rules:
  Host            Path  Backends
  ----            ----  --------
  yellowdog.tech
                  /ydos   ydos-svc:80 (<none>)
Annotations:
Events:
  Type     Reason                   Age   From                      Message
  ----     ------                   ----  ----                      -------
  Warning  AddedOrUpdatedWithError  4m    nginx-ingress-controller  Configuration for ydos/ydos-ingress was added or updated, but not applied: Error when adding or updating ingress ydos/ydos-ingress: Invalid nginx configuration detected, not reloading: Command nginx -t stdout: ""
stderr: "nginx: [emerg] PEM_read_bio_X509_AUX(\"/etc/nginx/secrets/default\") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)\nnginx: configuration file /etc/nginx/nginx.conf test failed\n"
finished with error: exit status 1

both crt and key pass openssl verification and are in use else where.

**To Reproduce**
create a secret from key and crt, either using cli or yaml file.
describe ingress to show error.

**Expected behavior**
nginx to use k8s secrets and create a conf in conf.d/

**Your environment**
* Version of the Ingress Controller - release version or a specific commit
current
* Version of Kubernetes
1.10.3
* Kubernetes platform (e.g. Mini-kube or GCP)
oracle cloud infrastructure
* Using NGINX or NGINX Plus
nginx
**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by dick-twocows** [comment]
That's was my initial thought but...

I've run both the cert.pem and key.pem through openssl to validate they are correct.

Used kubectl create secret tls wildcard-yellowdog-tech-secret --cert=cert.pem --key=key.pem to create the tls secret.

Used base64 to convert the cert and key and sed to insert them into a yaml file.

Both give the same error.

These are in use on other apache and nginx deployments.

I was of the understanding that the kubectl cli would create the two keys properly based on the file.

That said is there a way from kubectl to get and validate the based64 encoding of a key?

**Comment by pleshakov** [comment]
@dick-twocows 
my mistake. the problem is with the certificate and key `/etc/nginx/secrets/default`, which is the cert and key for the default server.  

We had a similar issue recently -- https://github.com/nginxinc/kubernetes-ingress/issues/333 

how did you install the Ingress Controller?

**Comment by dick-twocows** [comment]
Used the nginxinc/kubernetes_ingress install folder including rbac into OCI k8s.

Used the cafe example for coffee/tea and checked working using curl.

Added ydos deployment and ingress using cafe-secret and checked working using curl.

Removed ydos and modified to use yellowdog secrets and added.

Broke it... :-(

Should I have overwritten the default secret with my cert/key from the start?

I can start/redo this k8s from scratch if required...

If it's any help the cert/key are being created in nginx/secrets with the correct name from the ingress definition. The default one appears to be binary if I cat it, the others are text..?

**Comment by pleshakov** [comment]
@dick-twocows 
> Should I have overwritten the default secret with my cert/key from the start?

for testing purposes, it is OK to use the provided default secret. For production deployments, we recommend generating your own certificate and key.

**Comment by dick-twocows** [comment]
I'll redeploy tomorrow am (UK time) and update as requested.

Thank you.

**Comment by dick-twocows** [comment]
I deleted the default secret and recreated it with our cert/key and all is well...

**Comment by pleshakov** [comment]
@dick-twocows thanks for the update. I'm glad that it is working for you now. 

With that said, it is not yet clear if the default secret was updated with invalid data in Kubernetes  or it was the Ingress Controller that somehow changed the `/etc/nginx/secrets/default` file while the default secret in Kubernetes was remaining valid.

**Comment by dick-twocows** [comment]
I had not knowingly changed the default secret. I only thought to cat it when I investigated the structure of the pod to see how the ingress was applied. The issue occured after the ingress failed  to modify due to annotation issues. Maybe that caused the issue. We have a number of further deployments so I will watch.
