### ISSUE TITLE
Certificate error in pod logs

### ISSUE THREAD

**Issue by IvanPletnyov** [nginxinc/kubernetes-ingress#3424]
**Describe the bug**
I have error in ingress pods 

`[nginx-ingress-controller-nginx-ingress-5b67849cc9-fl4th] W0111 16:23:56.404473       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.25.2/tools/cache/reflector.go:169: failed to list *v1.Certificate: the server could not find the requested resource (get certificates.cert-manager.io) `

I have two clusters, in staging cluster I no have error but on production cluster this error appear periodically.

**Expected behavior**
Logs doesn't contains this error.

**Your environment**
* Version of the Ingress Controller - helm chart https://helm.nginx.com/stable ingress-nginx 0.15.1
* Version of Kubernetes - 1.23.7
* Kubernetes platform (e.g. Mini-kube or GCP) - Custom deploy(3 masters, 3 etc and 6 workers)
* Using NGINX or NGINX Plus

**Comment by brianehlert** [comment]
Do you have the same version of cert-manager in both environments?
Do you have the same RBAC applied?

Also see: 
https://github.com/nginxinc/kubernetes-ingress/issues/3314
https://github.com/nginxinc/kubernetes-ingress/issues/3393

Who reported the same error
-

**Comment by IvanPletnyov** [comment]
> Do you have the same version of cert-manager in both environments? Do you have the same RBAC applied?
> 
> Also see: #3314 #3393
> 
> Who reported the same error

Is cert-manager required for install this ingress ? I use my keys for production and docnot install cert manager on it. RBAC the same

**Comment by brianehlert** [comment]
Sorry, I extracted that from the error.
Did you re-apply the rbac.yaml if you updated?  rabc.yaml does change from time to time.
Does the certificate exist

`failed to list *v1.Certificate: the server could not find the requested resource`

**Comment by IvanPletnyov** [comment]
> Sorry, I extracted that from the error. Did you re-apply the rbac.yaml if you updated? rabc.yaml does change from time to time. Does the certificate exist
> 
> `failed to list *v1.Certificate: the server could not find the requested resource`

As I described above I was install nginx ingress via helm chart. 
All options which I change in values is:
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/26973706/212024370-755cd68a-d1a9-470b-916c-0139f635359a.png">

Any other values is default for chart version 0.15.1

**Comment by shaun-nx** [comment]
> Is cert-manager required for install this ingress ? I use my keys for production and do not install cert manager on it. RBAC the same

If you are setting the `controller.enableCertManager=true` option in production then cert-manager will need to be installed in production.

I ran two test to confirm this:
1. Deploy the Ingress Controller using chart version 0.15.1 with `controller.enableCertManager=true` and cert manager is **not** installed

With this test I get the same error:
``W0112 09:46:39.147905       1 reflector.go:424] k8s.io/client-go@v0.25.4/tools/cache/reflector.go:169: failed to list *v1.Certificate: the server could not find the requested resource (get certificates.cert-manager.io)``

2. Deploy the Ingress Controller using chart version 0.15.1 with `controller.enableCertManager=true` and cert manager is installed

With this test I did not get the error.

**Comment by IvanPletnyov** [comment]
> > Is cert-manager required for install this ingress ? I use my keys for production and do not install cert manager on it. RBAC the same
> 
> If you are setting the `controller.enableCertManager=true` option in production then cert-manager will need to be installed in production.
> 
> I ran two test to confirm this:
> 
> 1. Deploy the Ingress Controller using chart version 0.15.1 with `controller.enableCertManager=true` and cert manager is **not** installed
> 
> With this test I get the same error: `W0112 09:46:39.147905 1 reflector.go:424] k8s.io/client-go@v0.25.4/tools/cache/reflector.go:169: failed to list *v1.Certificate: the server could not find the requested resource (get certificates.cert-manager.io)`
> 
> 2. Deploy the Ingress Controller using chart version 0.15.1 with `controller.enableCertManager=true` and cert manager is installed
> 
> With this test I did not get the error.

Oh... Make sense, ok, I will delete this option from my installation and check it again. Thanks !
If it will work properly I will close issue.

**Comment by IvanPletnyov** [comment]
@shaun-nx I'll check it on two days.

**Comment by IvanPletnyov** [comment]
Hello, yeah, I've change value controller.enableCertManager to false and error disappear from ingress pod logs, thank @shaun-nx and @brianehlert for the help!
