### ISSUE TITLE
cert manager challenge request not working with enabled ssl-redirect

### ISSUE THREAD

**Issue by IvanPletnyov** [nginxinc/kubernetes-ingress#3441]
**Describe the bug**
I was add _"ssl-redirect: True"_ option to my config map but cert manager doesn't work with enabled this option because it try http request which redirects to https by ingress. Also I can't disable this option from config map and rule 
`if ($scheme = 'http') {
        return 301 https://$host$request_uri;
    }`
always present in my nginx configuration.

**Expected behavior**
Redirect 301 disappear from nginx configuration if I disable ssl-redirect when set option _"ssl-redirect: False"_ or cert manager challenge request works with enabled this option

**Your environment**
* Version of the Ingress Controller - helm chart https://helm.nginx.com/stable ingress-nginx 0.15.1
* Version of Kubernetes - 1.23.7
* Kubernetes platform (e.g. Mini-kube or GCP) - Custom deploy(3 masters, 3 etc and 6 workers)
* Using NGINX or NGINX Plus - NGINX

**Comment by hahahannes** [comment]
Hi, I had a similar problem and the solution was to add the `acme.cert-manager.io/http01-edit-in-place: "true"`
 annotation to my ingress as proposed here: https://github.com/nginxinc/kubernetes-ingress/issues/2698#issuecomment-1174900207. This will update cert manager to use the exisiting ingress for the ACME challenge and not to create a new ingress.

**Comment by IvanPletnyov** [comment]
> Hi, I had a similar problem and the solution was to add the `acme.cert-manager.io/http01-edit-in-place: "true"`
> annotation to my ingress as proposed here: [#2698 (comment)](https://github.com/nginxinc/kubernetes-ingress/issues/2698#issuecomment-1174900207). This will update cert manager to use the exisiting ingress for the ACME challenge and not to create a new ingress.

@hahahannes Hi! Did you add this annotation to ingress controller pods(I mean controller.pod.annotations in chart values) or another place ?

**Comment by hahahannes** [comment]
Ah sorry, yes I added it to the Ingress. How do you declare your certificate? With the `Certificate` Resource?

**Comment by IvanPletnyov** [comment]
@hahahannes I think this resource automatically installs via cert-manager(I was install cert-manager using helm). After install cert-manager I was install only one extra resource - `ClusterIssuer`, any other resources like `Certificate` added automatically and it's magic for me :D

**Comment by hahahannes** [comment]
Yes sometimes it feels a bit magic :D 
I am just wondering where the certificate is specified in your manifests. Because normally, I think, there is no certificate created when you just install cert-manager. For example, you can use an `Ingress` with the `cert-manager.io/cluster-issuer` annotation or a `Certificate` resource (like `kind: Certificate`). Then cert-manager will pick these up and will try to request a certificate.

**Comment by IvanPletnyov** [comment]
@hahahannes I don't now :( 
In my case I'm creating nginx virtual server with secret name, cert-manager rename this secret(add random suffix) and modify ingress controller configuration(add acme request section to nginx file conf). When ACME request successfully performed secret renamed to name that I was specify and Certificate created(I don't now is Certificate creates before creqte ACME request or after).

**Comment by shaun-nx** [comment]
Hi @IvanPletnyov 
Can you provide full details on your deployments? Use the command `kubectl get all -A` to show all resources in your cluster.

You mentioned that you created a VirutalServer resources. Can you show what your VirtualServer yaml file looks like?

**Comment by shaun-nx** [comment]
Also what version of CertManager did you install on your cluster?
For example this command here will install v1.11.0 of CertManager:
```
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml
```

**Comment by IvanPletnyov** [comment]
Hi @shaun-nx
kubectl get all: https://gist.github.com/IvanPletnyov/58964564ba7c4f67e1c762f7899bc20d 
VS resource one of test servers(real URL was masked): https://gist.github.com/IvanPletnyov/a8f3dc99484323725ec8e79d5f4c7371

I was install Cert Manager v1.10.0 via helm with set installCRDs=true, also I was create ClusterIssuer: https://gist.github.com/IvanPletnyov/f3a598dba46ab32de132eff0dbfb110e

**Comment by shaun-nx** [comment]
Hi @IvanPletnyov 

In your VirtualServer resource you have SSL redirect enabled here: https://gist.github.com/IvanPletnyov/a8f3dc99484323725ec8e79d5f4c7371#file-gistfile1-txt-L49-L51

Setting `ssl-redirect` in a configmap doesn't apply to VirtualServer resources.
You will need to remove the redirect configuration in your VirtualServer resource if you want the ACME challenge to work.

**Comment by IvanPletnyov** [comment]
@shaun-nx Ok I got it, but, I need redirect all http requests to https for "non-ACME requests"

**Comment by shaun-nx** [comment]
> I need redirect all http requests to https for "non-ACME requests"

We don't support doing this natively. It is possible to get this working using snippets.

This is an example VirtualServer configuration where this would work:

```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
spec:
  host: foo.bar
  tls:
    secret: cafe-secret
    cert-manager:
      cluster-issuer: letsencrypt-staging
  server-snippets:
      set $redirect 1;

      if ($scheme != 'http') {
          set $redirect 0;
      }

      if ($uri ~ "^/.well-known/acme-challenge(.*)") {
          set $redirect 0;
      }

      if ($redirect) {
          return 301 https://$host$request_uri;
      }
  upstreams:
  - name: tea
    service: tea-svc
    port: 80
  - name: coffee
    service: coffee-svc
    port: 80
  routes:
  - path: /tea
    action:
      pass: tea
  - path: /coffee
    action:
      pass: coffee
```

Below are example responses I got when testing this

HTTPS request
```
» curl --resolve foo.bar:$IC_HTTPS_PORT:$IC_IP https://foo.bar/:$IC_HTTPS_PORT/tea --insecure
Server address: 10.42.0.29:8080
Server name: tea-7f5799695f-hs26t
Date: 24/Jan/2023:16:57:30 +0000
URI: /tea
Request ID: 634897998cc0b320ee34fcd000f1b3f5
```

HTTP request
```
» curl --resolve foo.bar:$IC_HTTP_PORT:$IC_IP http://foo.bar/:$IC_HTTP_PORT/tea --insecure
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.23.2</center>
</body>
</html>
```

ACME Challenge request
```
» curl --resolve foo.bar:$IC_HTTP_PORT:$IC_IP http://foo.bar/:$IC_HTTP_PORT/.well-known/acme-challenge/RCrHlAge8SW0oE0klshlqwy9FJvpLD9zvwFaz0p1JJQ
RCrHlAge8SW0oE0klshlqwy9FJvpLD9zvwFaz0p1JJQ.O3s02gal13-vRmwwBIDELEqnFXoiJ9W5-IsRLPEHE7o%
```

**Comment by IvanPletnyov** [comment]
Hello @shaun-nx
Ok, thanks for the help, I'll change to redirect via snippet.

**Comment by svvac** [comment]
@alanivey I've opened #4408 on that topic.
