### ISSUE TITLE
Disabling Leader Election in helm chart

### ISSUE THREAD

**Issue by trevor-jack** [nginxinc/kubernetes-ingress#3455]
**Describe the bug**
There is no way to disable leader election and report-ingress-status in conjunction when deploying nginx to kubernetes using the provided helm templates. Also related to this, currently the "controller-leader-election-configmap.yaml" will be deployed regardless of the controller.reportIngressStatus.enableLeaderElection setting.

**To Reproduce**
1. Set controller.reportIngressStatus.enable: false and controller.reportIngressStatus.enableLeaderElection: false in values.yaml
2. Running a helm template will show that enable-leader-election is not being explicitly set. The default value for this is true, so nginx will still attempt a leader election + attempt to create/update configmap resources.
3. When installed using helm the deployment is successful and nginx seems to run normally, but constantly throws errors
```
error initially creating leader election record: configmaps is forbidden: User "system:serviceaccount:<>" cannot create resource "configmaps" in API group "" in the namespace "<>"
```
This is because the RBAC permissions required are being removed when controller.reportIngressStatus.enableLeaderElection is false. This specific error is also present because leader-election-lock-name is not being explicitly set in this scenario.

**Expected behavior**
The nginx deployment should pass -enable-leader-election=false as an argument to in the container spec when controller.reportIngressStatus.enableLeaderElection=false. This setting is not a dependency of reportIngressStatus.

**Your environment**
* Version of the Ingress Controller - 3.0.0
* Version of Kubernetes 1.21
* Kubernetes platform GCP

**Comment by shaun-nx** [comment]
Hi Trevor. You confirm the version of the Ingress Controller?
We currently don't have a version 1.23.3

**Comment by brianehlert** [comment]
To clarify what Shaun stated.
The project where you posted this is: https://github.com/nginxinc/kubernetes-ingress
And this project has never released a version 1.23, so we can only assume your issue might be related to the community ingress controller project which is here: https://github.com/kubernetes/ingress-nginx/
Thanks.

**Comment by brianehlert** [comment]
Looking at the other project I am not seeing a 1.23 as an Ingress version.  So maybe I am simply a bit confused.

**Comment by trevor-jack** [comment]
Apologies for the confusion. In relation to this project the release is v3.0.0.
The resulting version of nginx deployed in this release is 1.23.3

**Comment by brianehlert** [comment]
Thanks for the issue @trevor-jack .  
Disabling leader election is something we don't see often (so we may have missed something) - can you help us understand why you are disabling leader election?

**Comment by trevor-jack** [comment]
Hi Brian,
As far as I can tell reading about this feature, the only thing the leader is there for is to prevent multiple replicas from updating the "status" of Ingress/VirtualServer/VirtualServerRoute resources. We are not using VirtualServer/VirtualServerRoute resources.
For Ingress resource the only status that would be updated is "the address (an IP address or a DNS name), through which the hosts of that Ingress resource are publicly accessible."
That has the option of being provided either through a load-balancer service, all of our services are clusterIP, or I believe I could manually define this in the config map using the external-status-address key. This has never been set by us and I wouldn't consider adding it to be meaningful.
So from what I can gather this is currently doing an election for no reason, which doesn't seem to be a big issue by any means, but I figured I would remove it as it's unnecessary.

If I'm misunderstanding something about the leader election please let me know.

**Comment by brianehlert** [comment]
Leader election is about any resources that the NGINX Ingress Controller is updating.  Not specifically the CRDs delivered with the project.
It is about reducing impacts on the K8s API that may result in overall throttling that impact the entire cluster.
As each pod in a NIC deployment will be repeating the same updates to the same objects.  And creating unnecessary load on the K8s API.

There are a number of status updates that are pushed to the objects.
But, you are correct that disabling should actually disable.

**Comment by trevor-jack** [comment]
Looking through some more of the code I'm not seeing where else the leader would be involved with other k8s API/objects outside of updating that singular ingress external ip address when report-ingress-status is enabled, and then the custom resource status updates.

One thing I did notice is that the custom-resource status updates are based off of custom resources being enabled, not off of the report-ingress-status setting. Given that it seems odd to me that the leader election settings are nested under reportIngressStatus in the chart.

**Comment by brianehlert** [comment]
I don't know if this is helpful at all: https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/command-line-arguments/

We don't really describe leader election specifically though.  But we have had situations where clusters have gone unresponsive (from a management perspective) due to the K8s API being flooded.

And since you are poking around: https://docs.nginx.com/nginx-ingress-controller/intro/how-nginx-ingress-controller-works/

**Comment by trevor-jack** [comment]
Thanks for the links, I'll do some more research and I'm going to run some more tests just for my own curiosity. 
Taking a quick look at one of our dev envs shows a drop in k8s api calls from ~4k/hour to ~300/hour after disabling leader elections, so it's surprising to me that enabling it alleviates api flooding issues in some scenarios.

**Comment by vepatel** [comment]
@trevor-jack the flag to disable leader-election is `controller.reportIngressStatus.enableLeaderElection` not `controller.enableLeaderElection`, please refer to [this](https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/#configuration) doc for more information on this.

**Comment by shaun-nx** [comment]
Hi @trevor-jack 
I'm running tests on this feature now. Will get back to you as soon as I can.
