### ISSUE TITLE
Non standard Ingress path requirement for pathType: ImplementationSpecific breaks k8s compatibility (and 3rd party services)

### ISSUE THREAD

**Issue by thecrazyrussian** [nginxinc/kubernetes-ingress#3498]
**Describe the bug**
Unable to get nginx ingress controller (3.0.1) to validate a k8s compatible Rancher (any version to 2.7.1) ingress that utilizes "pathType: ImplementationSpecific" and does not specify a path. This prevents easy usage of Rancher with later (>2.3.0) nginx controller.

**To Reproduce**
1. On K8s (tested on k3s) k8s v1.24
2. Deploy Nginx controller (3.0.1) via helmchart
3. Deploy Cert Manager (1.8.2)
4. Deploy Rancher (any, tested 2.6.9, 2.6.10, 2.7.1)
5. Nginx fails to validate ingress.

```
I0128 20:30:52.803167       1 event.go:285] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"cattle-system", Name:"rancher", UID:"0d2ea447-9f6d-4ef4-ae0f-a207aa8e8c43", APIVersion:"networking.k8s.io/v1", ResourceVersion:"28689", FieldPath:""}): type: 'Warning' reason: 'Rejected' cattle-system/rancher was rejected: with error: spec.rules[0].http.path[0].path: Required value
```

**Expected behavior**
Nginx properly handles `ImplementationSpecific` with no path specified and defaults to '/' or provides ability to input default implementation specific path.

**Your environment**
* Version of the Ingress Controller -[v3.0.1](https://github.com/nginxinc/kubernetes-ingress/releases/tag/v3.0.1)
* Version of Kubernetes 1.24
* Kubernetes platform k3s
* Using NGINX

**Additional context**
Looks like this is related to the change in 2.3.0 https://github.com/nginxinc/kubernetes-ingress/pull/2775
The error was later qualified: https://github.com/nginxinc/kubernetes-ingress/pull/2971

**Comment by brianehlert** [comment]
If you are using Rancher and the 'built-in' nginx ingress controller you are deploying the Kubernetes Community ingress controller.
Using the Helm chart of this project you will be deploying the one maintained by NGINX.
These two are unique.

This project does not support an empty path.
see the Restrictions section here: https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/basic-configuration/
