### ISSUE TITLE
Expose UDP or TCP service throught https ingress

### ISSUE THREAD

**Issue by StoryDevOffical** [nginxinc/kubernetes-ingress#3500]
### Discussed in https://github.com/nginxinc/kubernetes-ingress/discussions/3499

<div type='discussions-op-text'>

<sup>Originally posted by **StoryDevOffical** January 29, 2023</sup>
Hello, 

I am trying to route TCP and UDP traffic through 2 HTTPS ingress.
So i use nginxinc NGINX Controller, it seems it can be done with custom resources and not with [configmap like i did usually](https://github.com/kubernetes/ingress-nginx/blob/e8d81034b8f6b3308caac85280e4cf3d93baee1c/docs/user-guide/exposing-tcp-udp-services.md) with other controller.

But i am bit confused about the doc ... which should i use ? 

- with a custom resource like [official nginxinc repo example ](https://github.com/nginxinc/kubernetes-ingress/tree/v3.0.1/examples/custom-resources/basic-tcp-udp)
or 
- with [TransportServerResource ](https://docs.nginx.com/nginx-ingress-controller/configuration/transportserver-resource/)configuration.

From my research, it seems it can only be configured at the top ingress configuration level but is it possible to apply these specific tcp/udp ingress routing configuration by namespace ?
In other word, can i make custom tcp/udp ingress routing configurations for each app according to their namespace ?

Regards, 
Story

NGINX Ingress Controller (helm v0.16.1)</div>

**Comment by brianehlert** [comment]
The way that NGINX works under the hood is that http (layer 7) is distinct from tcp (layer 4).  If you looked at the nginx.conf you would find an http block and a stream block - with different behavior.

Using this project TCP/UDP is better addressed using the TransportServer resource.  It was designed specifically for TCP/UDP.
This is combined with the GlobalConfiguration resource to define listeners for NGINX.  And in turn is linked to the ports exposed for the deployment itself.

The document you link to and the example you link to are complimentary to each other.  They are both the TransportServer.
In the docs the GlobalConfiguration resource is mentioned in the prerequisites.
