### ISSUE TITLE
Nginx Ingress Controller pod fails to start on AKS private cluster with `failed to list *v1.VirtualServer`

### ISSUE THREAD

**Issue by rgaduput** [nginxinc/kubernetes-ingress#3510]
**Describe the bug**
When deployed Nginx Ingress Controller on AKS cluster which is in private mode, Controller pod fails in readiness probe.
Below is from the Controller pod logs
```
I0201 06:31:22.166205       1 listener.go:54] Starting Prometheus listener on: :9113/metrics
I0201 06:31:22.166490       1 leaderelection.go:248] attempting to acquire leader lease sm-infra/sm-infra-nginx-ingress-leader-election...
W0201 06:31:22.168469       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.6/tools/cache/reflector.go:167: failed to list *v1.VirtualServer: the server could not find the requested resource (get virtualservers.k8s.nginx.org)
E0201 06:31:22.168628       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.6/tools/cache/reflector.go:167: Failed to watch *v1.VirtualServer: failed to list *v1.VirtualServer: the server could not find the requested resource (get virtualservers.k8s.nginx.org)
W0201 06:31:22.168752       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.6/tools/cache/reflector.go:167: failed to list *v1alpha1.TransportServer: the server could not find the requested resource (get transportservers.k8s.nginx.org)
```
Because of this even though ingress service gets the LoadBalancer IP assigned, Address is not assigned to `ingresses.networking.k8s.io` resource.

```
root@vm-bastion:~/chart# kubectl get ingress -n infra
NAMESPACE   NAME      CLASS            HOSTS                  ADDRESS   PORTS   AGE
infra     grafana   infra-nginx   grafana.svc.com                        80     14h
```

**To Reproduce**
1. Deploy ingress helm chart on private AKS cluster of version v1.23.12
2. Verify that ingress controller pod fails to start with readiness probe issue
3. See the above exception the pod logs

**Expected behavior**
Nginx controller pod should come up properly and `ingresses.networking.k8s.io` resources should have address assigned 

**Your environment**
* Version of the Ingress Controller -> Helm chart version: 0.14.0, App version: 2.3.0
* Version of Kubernetes -> v1.23.12
* Kubernetes platform -> AKS (Private)
* Using NGINX or NGINX Plus -> NGINX

**Comment by rgaduput** [comment]
After checking the other issue mentioned here it seems CRDs were not applied which cause this
https://github.com/nginxinc/kubernetes-ingress/issues/1184
When I manually applied the CRDs controller pod came up fine and also address assigned to the ingress resource.
In our values file we do have `enableCustomResources: true`, so not sure why helm skipped those CRDs apply.
Any idea in why the CRDs apply skipped ?

**Comment by jasonwilliams14** [comment]
@rgaduput hello there. Yep, those errors in the logs are pointing directly at the CRDs not being installed.
As to why they were not installed, I would look at your `values.yaml` file
You can see here on our document about CRDs with `helm`:

https://github.com/nginxinc/kubernetes-ingress/tree/main/deployments/helm-chart#installing-the-crds

Specifically:

```
If you do not use the custom resources that require those CRDs (which corresponds to controller.enableCustomResources set to false and controller.appprotect.enable set to false and controller.appprotectdos.enable set to false), the installation of the CRDs can be skipped by specifying --skip-crds for the helm install command.
```

Let us know if that helps.

**Comment by rgaduput** [comment]
Hi @jasonwilliams14 ,
You are right, but what I do not understand is I have used the default values of the chart which supposed to install CRDs.

**Comment by rgaduput** [comment]
I am closing this since in the different cluster same chart worked fine (CRDs applied automatically during the installation)
