### ISSUE TITLE
Allow configuring `ngx_http_realip_module` per server/location

### ISSUE THREAD

**Issue by sigv** [nginxinc/kubernetes-ingress#3595]
**Is your feature request related to a problem? Please describe.**

When running multiple load balancers/reverse proxies in front of Kubernetes, the Ingress Controller can receive `X-Forwarded-For` headers from multiple sources. This allows tracing requests to their actual origin. Current global [ConfigMap](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/) allows configuring [`ngx_http_realip_module`](https://nginx.org/en/docs/http/ngx_http_realip_module.html), but it cannot be configured explicitly on a VirtualServer or VirtualServerRoute.

**Describe the solution you'd like**

The configuration could be overridden via [Policy resource](https://docs.nginx.com/nginx-ingress-controller/configuration/policy-resource/) linked to VirtualServer or VirtualServerRoute.

```yaml
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: realip
spec:
  realIp:
    setFrom:
    - 10.0.0.0/8
```

**Describe alternatives you've considered**

These same options could be overridden on Ingress resource level via `nginx.org/set-real-ip-from` [annotations](https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/).

**Additional context**

**Comment by brianehlert** [comment]
set-real-ip-from is part of the GlobalConfiguration resource
https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#general-customization
As well as the other two settings.

Can you help us understand why this might not work for your situation?  It is not clear in the request.

**Comment by sigv** [comment]
I am not seeing a way to override this in VirtualServer or in VirtualServerRoute level.

I was mentioning the Ingress resource as I am coming from `ingress-nginx`. Sorry about that.

The scenario is that one application is expected to be proxied to from `10.0.1.1-2` and a different application inside the same Kubernetes cluster is trusting proxied requests from `10.0.2.1-2`.

We can configure both as trusted sources if need be, but would like a way to be specific inside the VirtualServer Policy.

**Comment by brianehlert** [comment]
I have been reviewing this in trying to better understand what you are seeking, and I get the impression there is some overlap with https://github.com/nginxinc/kubernetes-ingress/issues/3594
Can you help clarify?

**Comment by sigv** [comment]
Both are related to the same underlying use-case: requests are generally coming in via a CDN proxy. Then there are specific administrative locations that are allowed only via a separate load balancer.

I closed the ACL request after understanding `nginx-ingress` prefers use of custom resources (where Policy resource can be applied to VirtualServer and VirtualServerRoute as needed).

I did not close this request as the realip module can only be configured at Controller level (global http). As I said, we can configure both sources as globally trusted for `X-Real-Ip`/`X-Forwarded-For` but I would prefer that locations can specify which proxy is expected to send traffic in. Imo this would make the security teams' job easier as they can identify sources.

At the same time I understand the argument for allowing both globally, as it reduces the feature set to implement. Let me know if this is a `WONTFIX` and we will just move forward with the available functionality.

**Comment by jasonwilliams14** [comment]
heya @sigv 
Great questions. I just want to confirm a few pieces to make sure I understand correctly.

>Then there are specific administrative locations that are allowed only via a separate load balancer    

The idea for the above is that you want to use access control lists, to only allow specific IPs to access a specific path? (ability to explicitly allow/deny capability)

Building on the above, you mention:

> realip module can only be configured at Controller level (global http). We can configure both sources as globally trusted for X-Real-Ip/X-Forwarded-For but I would prefer that locations can specify which proxy is expected to send traffic in.   

Is the requirement that you would like to change the `set_real_ip_from, `real_ip_header` at the path level, instead of at a global level?

If that is the case, I can do some testing as well as put together and example of how you can do this with our project.
Thanks and looking forward to your response.

**Comment by sigv** [comment]
> The idea for the above is that you want to use access control lists, to only allow specific IPs to access a specific path? (ability to explicitly allow/deny capability)

Yes, it would be a Policy that explicitly allows a specific proxy to forward requests. This already exists in the CRD and would serve as an additional layer of isolation for hardening in our infrastructure.

> Is the requirement that you would like to change the `set_real_ip_from` and `real_ip_header` at the path level, instead of at a global level?

Yes, this is the part of the picture I am missing currently.

**Comment by jasonwilliams14** [comment]
@sigv Ok great. Thank you for confirming. I will put together an example for you and post it here as soon as I finish testing it.

**Comment by jasonwilliams14** [comment]
@sigv I put together a very simple setup with what I believe is your goal.
Basically, I am using our CRDs (virtualServer and Policy) with a snippet.
NOTE: I just put random values in my testing so those would be changed for your environment. :)

Here is the `policy` (very basic) where set our `allow` range.

```
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: webapp-policy
spec:
  accessControl:
    allow:
    - 10.0.0.0/8
```
We are going to use this policy in combination with a `virtualServer` and `virtualServerRoute` as you want these settings set at a specific path.
Here is the configuration:
```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: webapp
spec:
  host: cafe.example.com
  upstreams:
  - name: coffee
    service: coffee-svc
    port: 80
  - name: tea
    service: tea-svc
    port: 80
  routes:
  - path: /coffee
    route: coffee
  - path: /tea
    action:
      pass: tea
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: coffee
spec:
  host: cafe.example.com
  upstreams:
  - name: coffee
    service: coffee-svc
    port: 80
  subroutes:
  - path: /coffee
    policies:
    - name: webapp-policy
    location-snippets: |
      set_real_ip_from 172.16.0.0/24;
      real_ip_header  X-Forwarded-For;
    action:
      pass: coffee
```
We use snippets in the `location` block to leverage the `ngx_ttp_realip_module` capabilities.
The reason for the snippets is that we currently do not have those directives for the module enabled in the CRD (something we can add to our backlog as a future enhancement).

If I look at the `nginx.conf` generated for the `/coffee` location:
```
location /coffee {                                                                                                                                                                                                                                                                           
    set $service "coffee-svc";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
    set $resource_type "virtualserverroute";                                                                                                                                                                                                                                                 
    set $resource_name "coffee";                                                                                                                                                                                                                                                             
    set $resource_namespace "default";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
    set_real_ip_from 172.16.0.0/24;                                                                                                                                                                                                                                                          
    real_ip_header  X-Forwarded-For;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
    allow 10.0.0.0/8;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
    deny all;  
```

Let me know if that is what you are looking for and is helpful.
If you have any further questions, please ask away.

Cheers.

**Comment by sigv** [comment]
@jasonwilliams14, thanks for the example! Snippet approach makes sense. I don't have any follow-up questions here.

> The reason for the snippets is that we currently do not have those directives for the module enabled in the CRD (something we can add to our backlog as a future enhancement).

Do you want this Github issue to be left open to track that potential improvement?
