### ISSUE TITLE
PDB is not getting deployed

### ISSUE THREAD

**Issue by mykolaichuk** [nginxinc/kubernetes-ingress#3614]
I have enabled PDB in my helm snippet and it's not getting deployed to the cluster.

I use a helm snippet like this:
```
helm upgrade \
--install \
nginx-ingress \
nginx-stable/nginx-ingress \
--set controller.podDisruptionBudget.enabled=true \
--set controller.podDisruptionBudget.minAvailable=1 \
-n ingress-basic \
--create-namespace \
--kubeconfig ~/.kube/config \
-f values.yaml
```
and PDB doesn't get deployed to the cluster.

**Environment**
* Helm version.BuildInfo{Version:"v3.11.0", GitCommit:"472c5736ab01133de504a826bd9ee12cbe4e7904", GitTreeState:"clean", GoVersion:"go1.18.10"}
* Version of the Ingress Controller - release version 3.0.2
* Version of Kubernetes: 1.25.5
* Kubernetes platform: Azure Kubernetes Service

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by vepatel** [comment]
Hi @mykolaichuk, this feature is not available in `v3.0.2` but is slated for our next major release however you're free to checkout `main` and build an image from there.

**Comment by mykolaichuk** [comment]
Hi @vepatel 

Thanks for the clarification! When new major version is gonna be released approximately?

**Comment by lucacome** [comment]
Tentatively by the end of the month. You can also use the `edge` chart and container in the meantime.

**Comment by vepatel** [comment]
closing this as `3.1.0` is now available
