### ISSUE TITLE
Add explicit "Plus-only" messaging to Deep Service Insight doc

### ISSUE THREAD

**Issue by aknot242** [nginxinc/kubernetes-ingress#3666]
**Describe the bug**
Deep Service Insight is for Plus only. The [documentation page](https://docs.nginx.com/nginx-ingress-controller/logging-and-monitoring/service-insight/) *mentions* Plus, but doesn’t explicitly say it is a Plus-only feature. 

**To Reproduce**
N/A

**Expected behavior**
I would like to see explicit messaging in the public docs that this is a Plus-only feature. The Helm parameter mentions it as well as a comment in the values file, so those won't need to be updated.

**Your environment**
N/A

**Additional context**
N/A

**Comment by jjngx** [comment]
Fixed with [PR](https://github.com/nginxinc/kubernetes-ingress/pull/3684)
