### ISSUE TITLE
-nginx-status and  -nginx-status-port cli arguments are not working

### ISSUE THREAD

**Issue by vinodhbasavani** [nginxinc/kubernetes-ingress#367]
**Describe the bug**
-nginx-status and  -nginx-status-port cli arguments are not working in ingress controller deployment file.

**To Reproduce**
1) save the content in a file named test.yml
`apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
    spec:
      serviceAccountName: nginx-ingress
      containers:
      - image: nginx/nginx-ingress:1.3.0
        name: nginx-ingress
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args:
          - -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
          - -default-server-tls-secret=$(POD_NAMESPACE)/darwinbox-in
         #- -v=3 # Enables extensive logging. Useful for trooublshooting.
          - -ingress-class=gvkbio
          - -report-ingress-status
          - -external-service=nginx-ingress
          - -enable-leader-election
          - -nginx-status
          - -nginx-status-port=8080
      - image: nginx/nginx-prometheus-exporter:0.1.0
        name: nginx-prometheus-exporter
        ports:
        - name: prometheus
          containerPort: 9113
        args:
          - -web.listen-address
          - :9113
          - nginx.scrape-uri
          - "http://127.0.0.1:8080/stub_status"`
2.  kubectl apply -f test.yml
3.  both containers are going to error state. kubectl logs <pod> -c nginx-ingress is printing the help of nginx-ingess command.

**Expected behavior**
It should start the listening on port 8080

**Your environment**
* Version of the Ingress Controller - version as in the deployment file
* Version of Kubernetes: 1.8.8
* Kubernetes platform  AWS
* Using NGINX 

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by isaachawley** [comment]
Hi @vinodhbasavani,

Those options are not available yet in v1.3.0. We do [Edge Releases](https://github.com/nginxinc/kubernetes-ingress#nginx-ingress-controller-releases) now that are built from master, which would include those options. However, the edge release may be less stable.

Thanks

**Comment by vinodhbasavani** [comment]
@isaachawley 

Thanks for the information. when can we expect a stable release with these options.

**Comment by isaachawley** [comment]
For NGINX Plus, the status and dashboard are supported by default [on localhost:8080](https://github.com/nginxinc/kubernetes-ingress/blob/v1.3.0/nginx-controller/nginx/templates/nginx-plus.tmpl#L91).

For NGINX, you can add a [server snippet](https://github.com/nginxinc/kubernetes-ingress/tree/v1.3.0/examples/customization) with [stub_status](http://nginx.org/en/docs/http/ngx_http_stub_status_module.html):
```
    server {
        listen 8080;

        allow 127.0.0.1;
        deny all;

        location /stub_status {
            stub_status;
        }
    }
```

**Comment by Dean-Coakley** [comment]
Closing, these cli-arguments are now available in the [latest stable release](https://github.com/nginxinc/kubernetes-ingress/releases/)
