### ISSUE TITLE
 The cafe secret has expired.

### ISSUE THREAD

**Issue by dick-twocows** [nginxinc/kubernetes-ingress#369]
**Describe the bug**
Error generating CA certificate chain for Secret "default/cafe-secret": x509: certificate has expired or is not yet valid.

The cafe secret has expired, i.e. its after 31 Aug 2018...

**To Reproduce**

Deploy cafe example.

Get logs on controller;

[opc@sysops-control oci]$ kubectl logs -n ingress-nginx nginx-ingress-controller-7bdcf5b8c-knhn9 | tail
E0912 15:45:15.713155       8 backend_ssl.go:161] Error generating CA certificate chain for Secret "default/cafe-secret": x509: certificate has expired or is not yet valid
...
E0912 15:54:15.718132       8 backend_ssl.go:161] Error generating CA certificate chain for Secret "default/cafe-secret": x509: certificate has expired or is not yet valid

Query controller using openssl;

[opc@sysops-control oci]$ kubectl exec -it -n ingress-nginx nginx-ingress-controller-7bdcf5b8c-knhn9 -- openssl x509 -in /etc/ingress-controller/ssl/default-cafe-secret.ut
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            e7:25:c0:1c:d9:91:b8:9a
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: C = US, ST = CA, O = Internet Widgits Pty Ltd, CN = cafe.example.com
        Validity
            Not Before: Aug 31 10:17:20 2017 GMT
            Not After : Aug 31 10:17:20 2018 GMT
        Subject: C = US, ST = CA, O = Internet Widgits Pty Ltd, CN = cafe.example.com

!!! Not After : Aug 31 10:17:20 2018 GMT

**Expected behavior**

A valid certificate.

**Your environment**
Latest git pull as of 12/09/2018

**Comment by pleshakov** [comment]
@dick-twocows 
it looks like you're using https://github.com/kubernetes/ingress-nginx Ingress Controller, not the Ingress Controller from this repo. In our Ingress Controller we don't check if a certificate is expired, so you will not get this error.

Note that the example certificates in this repo are self-signed and only meant for testing purposes.

Thanks for reporting. We'll update our example certificates.

**Comment by dick-twocows** [comment]
I am indeed testing the other ingress alongside the nginxinc one. But I like your cafe example to demo :-) We have deployed using nginxinc ingress with valid certificates but this one threw me for a bit.when I went to demo/compare...

Thanks for the update.
