### ISSUE TITLE
SysctlForbidden on Deployment when controller.hostNetwork = true

### ISSUE THREAD

**Issue by davefinster** [nginxinc/kubernetes-ingress#3714]
**Describe the bug**
With the advent of #3573 it appears that any deployment using hostNetwork=true on a deployment (not sure about daemonset) will now encounter an error with 

```
forbidden sysctl: "net.ipv4.ip_unprivileged_port_start" not allowed with host net enabled
```

**To Reproduce**
1. Deploy using the HELM charts with controller.hostNetwork set to true

**Expected behavior**
nginx pods start up successfully

**Your environment**
* Version of the Ingress Controller - 3.1.0
* Version of Kubernetes: 1.24
* Kubernetes platform (e.g. Mini-kube or GCP): Microk8s 
* Using NGINX or NGINX Plus: nginx

Kube Version Info:
```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:39:03Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.12-2+36e803be0d732b", GitCommit:"36e803be0d732b9da15f6568ed23e5c1929f8701", GitTreeState:"clean", BuildDate:"2023-03-17T18:58:08Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
```

Pinning the HELM chart version to 0.16.2 resolves the problem

**Comment by brianehlert** [comment]
I am curious if the contributor of the change @sigv might have any comments.

**Comment by sigv** [comment]
This is not great.

Looking back at Kubernetes documentation ([ref](https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/#setting-sysctls-for-a-pod)) it is clear that the `net.*` sysctls are not safe to use in combination with host networking.

I for some reason believed that it would be okay in Kubernetes, even though I was myself considering host-networking on Docker would not be viable, [before opening that PR](https://github.com/nginxinc/kubernetes-ingress/issues/3544#issuecomment-1436918481), when I was looking at [`moby/moby/daemon/oci_linux.go`](https://github.com/moby/moby/blob/6caaa8cadc9e4f1e122b7b2bb4451500bbec6086/daemon/oci_linux.go#L772-L773).

This should be patched, as host networking support should be restored.. but I am yet not 100% sure of the best compromise.

**Comment by sigv** [comment]
Adding a simple `if controller.hostNetwork` would not be viable, as the process no longer gets `NET_BIND_SERVICE`.

The chart should be kept as simple as possible, so mixing the Capability with Sysctl feels like asking for trouble down the line. If the Sysctl is not viable, then it should be dropped, and replaced with IC process receiving `NET_BIND_SERVICE` which is then inherited over to Nginx process.

The cap should be dropped by IC after starting Nginx, and by Nginx after binding the ports, but this is not a blocker.

Currently not seeing any other approach to this, except a revert, which brings back the escalation concern.
