### ISSUE TITLE
Helm GlobalConfiguration Argument

### ISSUE THREAD

**Issue by Seneti42** [nginxinc/kubernetes-ingress#3753]
I'm a bit confused as to how the global configuration argument is being set by the Helm chart templates and would appreciate someone explaining to me how it works or if I'm doing something wrong.

When setting controller.globalConfiguration.create to true, the template creates a globalConfiguration custom resource with the contents of the controller.globalConfiguration.spec. The globalConfiguration resource it creates is named using the nginx-ingress.fullname value:

**controller-globalconfiguration.yaml template**
![image](https://user-images.githubusercontent.com/88775596/231409101-af82e400-d7ca-46c4-828c-28d769c8d4c6.png)

However when the argument -global-congfiguration is set during the deployment of the controller to tell the controller which globalConfiguration resource to use, it is using nginx-ingress.name:

**controller-deployment.yaml template**
![image](https://user-images.githubusercontent.com/88775596/231411237-8312232b-40d9-435e-8003-a517fa8c6ce8.png)

When I then run the helm to deploy the controller with a globalConfiguration the argument is telling the controller to look for a globalConfiguration resource name that doesn't exist:

**Helm created deployment**
![image](https://user-images.githubusercontent.com/88775596/231413352-f53bdc6f-77fe-4bdb-a6a3-b5b3fd7c80f5.png)
![image](https://user-images.githubusercontent.com/88775596/231412385-999f5bd4-f296-41cc-bff8-4feb8b318887.png)

**Helm created globalConfiguration**
![image](https://user-images.githubusercontent.com/88775596/231412509-794a90e8-28ee-4777-b569-975df0756c2d.png)

Apologies in advance I'm relatively new to Kubernetes and Helm, but is this by design, am I doing something wrong or is there an issue with the templates?

Thanks for your help.

**Comment by haywoodsh** [comment]
Hi @Seneti42, thank you for bringing in to our attention. I'm working on testing and confirming the behaviour you have reported. I will keep you updated once I have new information on this.
