### ISSUE TITLE
Helm chart: requests and limits on init container

### ISSUE THREAD

**Issue by bj0rn** [nginxinc/kubernetes-ingress#3804]
**Is your feature request related to a problem? Please describe.**
Gatekeeper in our cluster requires that a request/limit is set on all containers. When we set "readOnlyRootFilesystem: true" an init container is generated without a resource block.

https://github.com/nginxinc/kubernetes-ingress/blob/main/deployments/helm-chart/templates/controller-deployment.yaml#L257

**Describe the solution you'd like**
We want it to be possible to set resources on the init container that is generated when readOnlyRootFilesystem: true is set

**Comment by jasonwilliams14** [comment]
@bj0rn Thank you for the request.
We will review and take a look on our side.
