### ISSUE TITLE
Bug - Helm Chart: template "controller-leader-election-configmap" has incorrect indentation for annotations which breaks on apply

### ISSUE THREAD

**Issue by brian-provenzano** [nginxinc/kubernetes-ingress#3819]
**Describe the bug**
The template `controller-leader-election-configmap.yaml` in the latest helm chart has a bug that breaks apply of `controller-leader-election` configmap due to incorrect indentation of the `annotation`.  We use this option in the chart to populate this annotation for spinnaker config options.  We ran into this while moving from chart 0.15.2 (v2.4.2) --> chart 0.17.0 (v3.1.0)

Can see the issue [here](https://github.com/nginxinc/kubernetes-ingress/blob/main/deployments/helm-chart/templates/controller-leader-election-configmap.yaml#L10).  Appears to have been introduced in this [PR](https://github.com/nginxinc/kubernetes-ingress/pull/3475/files#diff-2449c810962f5f4c8f99c031cbae2f8615d84b06a41561d0a2cfc99ca8dc2469)?

**To Reproduce**
1. Use the attached values.yaml
2. Run helm template using current chart version `0.17.0` and render the templates
3. Inspect `controller-leader-election-configmap.yaml` and notice that `annotation` indentation is not under `metadata` - if you were to apply the rendered template k8s fails validation with `error validating "STDIN": error validating data: ValidationError(ConfigMap): unknown field "annotations" in io.k8s.api.core.v1.ConfigMap; if you choose to ignore these errors, turn validation off with --validate=false`

**Expected behavior**
I expect the annotation to render under metadata as required (and correctly written in other templates like this [one](https://github.com/nginxinc/kubernetes-ingress/blob/main/deployments/helm-chart/templates/controller-configmap.yaml#L10) )
__
**Your environment**
* Version of the Ingress Controller - `v3.10 using chart 0.17.0`
* Version of Kubernetes - `v1.23`
* Kubernetes platform - `EKS`
* Using NGINX or NGINX Plus - `NGINX`

**Additional context**
[values-file-with-annotation.txt](https://github.com/nginxinc/kubernetes-ingress/files/11346272/values-file-with-annotation.txt)

Adding sample `values `that populates the annotation - works fine in older chart (no changes) but fails in new chart.

**Comment by vepatel** [comment]
Thanks @brian-provenzano for reporting this, we are able to reproduce this issue in `3.1.0` as upgrade throws a warning as well:
`W0503 10:44:02.820672   62266 warnings.go:70] unknown field "annotations"`
