### ISSUE TITLE
SSL Passthrough?  

### ISSUE THREAD

**Issue by sereeth** [nginxinc/kubernetes-ingress#383]
**Is your feature request related to a problem? Please describe.**
Trying to get a grpc service to work with nginx, which seems to require http2.  Furthermore, in order for http2 to work over SSL, termination needs to happen at the pod NOT at nginx.

**Describe the solution you'd like**
Like the other nginx ingress, support ssl pass-through?

**Comment by pleshakov** [comment]
this Ingress controller does not support ssl passthrough.

yes, in order for gRPC to work, you need to enable http2 through the confimap https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/customization

In your case, is that a requirement that you terminate SSL at the pod? You can terminate SSL in NGINX and then NGINX will proxy GRPC connections to your backend pods without SSL.

**Comment by sereeth** [comment]
I don't need to terminate at the pod, but from what I've read http2 doesn't support grpc without the ssl connection terminating at the pod, maybe that's not true?

**Comment by sereeth** [comment]
I have a single service right now that is grpc, no http required for it at this time.

**Comment by pleshakov** [comment]
Great! thx
