### ISSUE TITLE
 Docs https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/installation.md#33-check-that-the-ingress-controller-is-running incorrect

### ISSUE THREAD

**Issue by patsevanton** [nginxinc/kubernetes-ingress#385]
```
git clone https://github.com/nginxinc/kubernetes-ingress.git
cd kubernetes-ingress
kubectl apply -f common/ns-and-sa.yaml
kubectl apply -f common/default-server-secret.yaml
kubectl apply -f common/nginx-config.yaml
kubectl apply -f rbac/rbac.yaml
kubectl apply -f daemon-set/nginx-ingress.yaml
```

Run the following command to make sure that the Ingress controller pods are running:

$ kubectl get pods --namespace=nginx-ingress

```
kubectl get svc nginx-ingress --namespace=ingress-nginx
No resources found.
Error from server (NotFound): services "nginx-ingress" not found
```
Is different namespace. Docs https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/installation.md#33-check-that-the-ingress-controller-is-running incorrect
```

ingress-nginx   default-http-backend-797c5bc547-qhpsn     1/1       Running     0          3h
ingress-nginx   nginx-ingress-controller-8wz4r            1/1       Running     0          3h
ingress-nginx   nginx-ingress-controller-rmgvs            1/1       Running     0          3h
ingress-nginx   nginx-ingress-controller-vz4d8            1/1       Running     0          3h
```

**Comment by pleshakov** [comment]
@patsevanton all our manifests use `nginx-ingress` namespace for the Ingress Controller. In your 
 `kubectl get svc` command you're using  `ingress-nginx` namespace, which is different. Please use `nginx-ingress` namespace.

From your output it looks that you also deployed an NGINX Ingress Controller from https://github.com/kubernetes/ingress-nginx/ , which is a different project. The major differences are described here https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/nginx-ingress-controllers.md

**Comment by Dean-Coakley** [comment]
Closing as it seems the NGINX Ingress Controller from https://github.com/kubernetes/ingress-nginx/ (which is a different project to this one) was deployed with our manifests.

If this was not the case, or you have further questions feel free to open a new issue.
