### ISSUE TITLE
Updated README.md

### ISSUE THREAD

**Issue by JasonHe-WQ** [nginxinc/kubernetes-ingress#3874]
**Describe the bug**
The newest version came to 3.1.1 And I made a [pull request](https://github.com/nginxinc/kubernetes-ingress/pull/3873) to change README.md.

**Comment by haywoodsh** [comment]
Hi @JasonHe-WQ, we haven't fully completed our release process. We already included your proposed change in the PR https://github.com/nginxinc/kubernetes-ingress/pull/3869

**Comment by JasonHe-WQ** [comment]
> Hi @JasonHe-WQ, we haven't fully completed our release process. We already included your proposed change in the PR #3869

Sorry for disturbing and thanks for reply.
