### ISSUE TITLE
Default to TLS 1.3

### ISSUE THREAD

**Issue by brianehlert** [nginxinc/kubernetes-ingress#3875]
Align with the latest releases of NGINX & NGINX Plus and security best practice by updating the default template and update TLS settings to using TLS v1.3 by default.

This is also requested here: https://github.com/nginxinc/nginx-ingress-helm-operator/issues/55

https://www.nginx.com/blog/nginx-plus-r29-released/#:~:text=Changes%20Inherited%20from%20NGINX%20Open%20Source

**Comment by hafe** [comment]
Some thought needs to be done how to handle TLS session tickets. By default nginx generates a random encryption key which means load sharing between several ingress controllers will make session resumption not working.

**Comment by hafe** [comment]
I was thinking the leader controller could generate an encryption key, put it into a secret and followers use the key. Rotation needs to be considered

**Comment by hafe** [comment]
Any feedback @brianehlert ?

**Comment by brianehlert** [comment]
This TLS issue was in reference to anything that we needed to do to catch up with NGINX who made a shift to default to TLS 1.3 with the last releases.  For example, if we had a lower TLS setting embedded within our templates anywhere.

I am not on the engineering team for NGINX, but the way that I believe the process works is that the TLS session happens prior to any other execution, in other words, the initial socket with the client forms the session based on the default setting or behavior of NGINX and what the client is capable of.

Now, I believe you might be raising the issue of the statefulness of the client connection.  Normally when customers need fully stateful session we suggest daemonset instead of deployment as this avoids kubeproxy and its inherent randomness to the ingress controller pods.  This way the session can be consistent from the loadbalancer to the specific ingress controller pod to the individual service backend pod.  We also realize this does not work for everyone.

That said.  NGINX Plus does to state sharing.  And we have a method to enable that for NGINX Ingress Controller.  This is most commonly used for token sharing with OIDC.
I am not certain, however, if this will address the concern you raise.  We would have to look into if NGINX Plus loadbalancing solves your issue.

**Comment by brianehlert** [comment]
Closing this as upgrading to NGINX Plus R29 handles this.
There were no dangling artifacts in the templates.
