### ISSUE TITLE
Ingress enable health check but no use.

### ISSUE THREAD

**Issue by chengxus** [nginxinc/kubernetes-ingress#3893]
**Describe the bug**
Ingress enables health checks, and the profile URL is sometimes updated when the pod probe URL is updated, but never reloaded.

**To Reproduce**
The file used in the current repository 1.12.4 version.
1. apply  examples/complete-example/cafe.yaml
2. apply examples/complete-example/cafe-secret.yaml
3. edit examples/complete-example/cafe-ingress.yaml add annotations 'nginx.com/health-checks: "true"' and apply
4. edit examples/complete-example/cafe.yaml add probe '
       readinessProbe:
          httpGet:
            port: 8080
            path: /healthz/tea
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 4
          successThreshold: 2
          failureThreshold: 3 '
5. get /api/6/http/upstreams not found health check.

**Expected behavior**
I expect to update the nginx config file and reload when I modify the probe。

* Version of the Ingress Controller：1.12.4
* Version of Kubernetes ：v1.17.4
* Kubernetes platform Mini-kube 
* Using NGINX Plus

I've fixed this。
cache pod probe config，and reload nginx when probe update。

**Comment by brianehlert** [comment]
Thanks for bringing this to our attention @chengxus we are looking into this.
