### ISSUE TITLE
go mod list error

### ISSUE THREAD

**Issue by LuoYuWuSheng** [nginxinc/kubernetes-ingress#3908]
**Describe the bug**
go: github.com/Venafi/vcert/v4@v4.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000)
can solve this problem according to :
https://github.com/ecordell/contour/commit/fff01bd7c52a7b22c9d5c75c1682de36b11cdb8d

**To Reproduce**
1. run "go list -modfile=go.mod -m -json -mod=mod all"
2. View on consoul
3. See error "go: github.com/Venafi/vcert/v4@v4.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000"

**Expected behavior**
success run go list

**Your environment**
* branch "main"
* commit "7dd4a965a971cc1159bd7975a2d866ac32766074"

**Comment by lucacome** [comment]
This was fixed by https://github.com/nginxinc/kubernetes-ingress/pull/3924
