### ISSUE TITLE
opentracing support

### ISSUE THREAD

**Issue by devendra-nvidia** [nginxinc/kubernetes-ingress#394]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Dean-Coakley** [comment]
Hi @devendra-nvidia 
Thanks for the feature request. Unfortunately adding opentracing support is not in our short term plans.

Can you provide any details about your use case, and/or any specific requirements?

In the mean-time you could try adding this https://github.com/opentracing-contrib/nginx-opentracing dynamic module to your images, configure open tracing config files, and then use our [snippets](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/customization#customization-of-nginx-configuration) or [custom templates](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/custom-templates#custom-templates) to insert opentracing related config.

**Comment by Rulox** [comment]
Hi @devendra-nvidia ,

Native support for OpenTracing has been added in the `edge` version of the Ingress Controller.
