### ISSUE TITLE
JWKs Remote Location - proxy_pass not resolving at runtime using variable

### ISSUE THREAD

**Issue by uniquemind27** [nginxinc/kubernetes-ingress#3965]
I am trying to have JWT auth enabled for Nginx Ingress via VirtualServerRoute. I created a policy with jwksURI and applied the same against the VirtualServerRoute. VirtualServer and VirtualServerRoute are in valid state but when a request is triggered the proxy_pass is not resolving the remote location endpoint successfully causing 500. Please note that resolver is already added explicitly via a configmap.

Config - location block:
```
location = /app1_jwks_uri {
            internal;
            proxy_method GET;
            
            proxy_cache /app1_jwks_uri;
            proxy_cache_valid 200 12h;
            
            
            proxy_set_header Host example.com;
            set $idp_backend example.com;
            proxy_pass https://$idp_backend/oauth/keys;
            
        }
```

Error message:
`[error] 48#48: *4 example.com could not be resolved (3: Host not found), client: x.x.x.x, server: *.com.au, request: "GET /app1 HTTP/1.1", subrequest: "/app1_jwks_uri", host: "xxxx"  `

When i tried to replace the proxy_pass without the variable it is getting successfully resolved and I am getting a 200 using curl. Please help.

`proxy_pass https://example.com/oauth/keys;`

Install the Nginx Ingres Controller.
Apply the service, deployment and servicedefaults.
Apply the policies, VirtualServer & VirtualServerRoute.
When a request is triggered with curl with the token you will see a 500. In the logs you can see the above error. 

Expected behavior:
Once the policy is applied successfully to the VirtualServerRoute I am expecting the token to get successfully validated against the JWK from remote location.

Versions:
Nginx Ingres Controller Version - 3.0.2
Helm chart version - 0.16.2
Nginx Plus

Kubernetes: AKS
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.26.0
[NginxIngress.zip](https://github.com/nginxinc/kubernetes-ingress/files/11666697/NginxIngress.zip)

**Comment by shaun-nx** [comment]
Hi @uniquemind27 thanks for reporting this and for all of the details provided. I'll see if I can reproduce this behaviour and get back to you.

Can you also confirm if you see the same behaviour from the latest release 3.1.1? We made a lot of changes to how JWK auth is implemented in that release.

**Comment by uniquemind27** [comment]
@shaun-nx I can confirm that the behaviour is same with 3.1.1. I had raised the issue 3964 for which they had asked me to uplift from 3.0.2 to 3.1.x. Now we are on 3.1.1. It helped issue 3964 but this proxy_pass issue still persist.

**Comment by shaun-nx** [comment]
@uniquemind27 we recently did a deployment using JWKS on an EKS cluster using AzureAD as the IdP using v3.1.1. We didn't see the same issue as you are describing.

Below is the config map, JWT location block, policy, VirtualServer and VirtualServerRoute resources that was configured in our testing.
Please confirm if your configuration is different is some way.

Note: the `subrequest_output_buffer_size 64k;` is in our config map to accommodate for the size of the response the comes from AzureAD.

ConfigMap:
```
~/nginx/kubernetes-ingress/examples/custom-resources/jwks on tags/v3.1.1 λ k describe cm test-release-nginx-ingress
Name:         test-release-nginx-ingress
Namespace:    default
Labels:       app.kubernetes.io/instance=test-release
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=nginx-ingress
              app.kubernetes.io/version=3.1.1
              helm.sh/chart=nginx-ingress-0.17.1
Annotations:  meta.helm.sh/release-name: test-release
              meta.helm.sh/release-namespace: default

Data
====
http-snippets:
----
subrequest_output_buffer_size 64k;

resolver-addresses:
----
kube-dns.kube-system.svc.cluster.local
```

JWT location block:
```

    location = /_jwks_uri_server_default/jwt-policy {
        internal;
        proxy_method GET;
        proxy_set_header Content-Length "";
        
        proxy_cache jwks_uri_webapp;
        proxy_cache_valid 200 12h;
        
        proxy_set_header Host login.microsoftonline.com;
        set $idp_backend login.microsoftonline.com;
        proxy_pass https://$idp_backend/<tennent_id>/discovery/v2.0/keys;
        
    }
```

Policies, VirtualServer and VirtualServerRoute:
```
~/nginx/kubernetes-ingress/examples/custom-resources/jwks on tags/v3.1.1 λ k describe policies.k8s.nginx.org 
Name:         jwt-policy
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  k8s.nginx.org/v1
Kind:         Policy
Metadata:
  Creation Timestamp:  2023-06-08T10:41:58Z
  Generation:          1
  Resource Version:    14838273
  UID:                 348d032d-d035-4a0b-9a9f-b10e993b9ce9
Spec:
  Jwt:
    Jwks URI:   https://login.microsoftonline.com/<tennent_id>/discovery/v2.0/keys
    Key Cache:  1h
    Realm:      MyProductAPI
    Token:      $http_token
Status:
  Message:  Policy default/jwt-policy was added or updated
  Reason:   AddedOrUpdated
  State:    Valid
Events:
  Type    Reason          Age   From                      Message
  ----    ------          ----  ----                      -------
  Normal  AddedOrUpdated  19m   nginx-ingress-controller  Policy default/jwt-policy was added or updated
```
```
~/nginx/kubernetes-ingress/examples/custom-resources/jwks on tags/v3.1.1 λ k get policies.k8s.nginx.org 
NAME         STATE   AGE
jwt-policy   Valid   17m
~/nginx/kubernetes-ingress/examples/custom-resources/jwks on tags/v3.1.1 λ k get vs
NAME     STATE   HOST                 IP              PORTS      AGE
webapp   Valid   webapp.example.com   20.190.25.254   [80,443]   16m
~/nginx/kubernetes-ingress/examples/custom-resources/jwks on tags/v3.1.1 λ k get vsr
NAME         STATE   HOST                 IP              PORTS      AGE
webapp-vsr   Valid   webapp.example.com   20.190.25.254   [80,443]   28s
```

Curl result:
```
~/nginx/kubernetes-ingress/examples/custom-resources/jwks on tags/v3.1.1 λ curl --resolve webapp.example.com:$IC_HTTP_PORT:$IC_IP http://webapp.example.com/:$IC_HTTP_PORT/ -H "token: ${TOKEN}" 

Server address: 10.244.0.11:8080
Server name: webapp-6bf64d6dcd-prd25
Date: 08/Jun/2023:11:10:30 +0000
URI: /
Request ID: dcc2d551676abdc2615b3c05f5111553
```

**Comment by jasonwilliams14** [comment]
@uniquemind27 Can you also provide us with the output of `nginx -T` so we can review the generated NGINX configuration file?
Can you also provide the following:

```
kubectl get virtualserver -A
kubectl get virtualserverroute -A
kubectl describe <jwks_policy>
```

Could you also provide the logs for NGINX Ingress controller as well? (pod logs)
Thank you.

**Comment by uniquemind27** [comment]
The output of nginx -t is as below:

`nginx@nginx-ingress-nginx-ingress-8679647dfb-64fhl:/$ nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
2023/06/09 03:57:27 [emerg] 131#131: bind() to 0.0.0.0:80 failed (13: Permission denied)
nginx: configuration file /etc/nginx/nginx.conf test failed
nginx@nginx-ingress-nginx-ingress-8679647dfb-64fhl:/$ `

`kubectl get virtualserver -A
NAMESPACE   NAME                       STATE   HOST               IP       PORTS   AGE
component   iwa-nginx-virtual-server   Valid   *.sample.com.au   x.x.x.x   [443]   44h


kubectl get virtualserverroute -A
NAMESPACE   NAME                                  STATE   HOST               IP       PORTS   AGE
component   iwa-app1-nginx-virtual-server-route   Valid   *.sample.com.au   x.x.x.x   [443]   44h`

Nginx Ingress Controller pod logs when I get a 500.
`2023/06/09 04:18:45 [error] 52#52: *97 example.com could not be resolved (3: Host not found), client: x.x.x.x, server: *.sample.com.au, request: "GET /iwa/app1 HTTP/1.1", subrequest: "/_jwks_uri_server_component/dynamic-nidp-jwt-policy", host: "sample.com.au" 
x.x.x.x - - [09/Jun/2023:04:18:45 +0000] "GET /iwa/app1 HTTP/1.1" 500 177 "-" "curl/7.29.0" "-"`

I have attached the describe policy.  
[policy.yml.zip](https://github.com/nginxinc/kubernetes-ingress/files/11702262/policy.yml.zip)

Meanwhile I am also trying to compare the working config that has been shared.

**Comment by vepatel** [comment]
Hi @uniquemind27 , re `bind() to 0.0.0.0:80 failed` issue, can you please verify if you're on correct tag i.e. v3.1.1 (`git checkout v3.1.1`) ?

**Comment by uniquemind27** [comment]
I can see that it is using 3.1.1. I have attached the screengrab for helm and the configmap below as a confirmation which is including resolver.

``` apiVersion: v1
kind: ConfigMap     
metadata:     
  name: nginx-config
  namespace: infra  
  labels:     
    helm.sh/chart: nginx-ingress-0.17.1
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: nginx-ingress
    app.kubernetes.io/version: "3.1.1" 
    app.kubernetes.io/managed-by: Helm 
data:         
  http-snippets: |  
    subrequest_output_buffer_size 64k; 
  resolver-addresses: x.x.x.x
  ```
    
![NIC version](https://github.com/nginxinc/kubernetes-ingress/assets/34367675/5d10691c-91df-4cd7-b99b-51be20096e9f)

**Comment by brianehlert** [comment]
>   http-snippets: |  
>    subrequest_output_buffer_size 64k; 
>  resolver-addresses: x.x.x.x

Resolver should be set in the configMap, not via snippet.
https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/

**Comment by hvindin** [comment]
I think the indenting provided by uniquemind27 is important. resolver-address is not part of the snippet, it is part of the configmap. Which appears to be correct.

**Comment by uniquemind27** [comment]
I was able to get this fixed by setting ipv6 to false against the resolver in the below manner.

`## The entries of the ConfigMap for customizing NGINX configuration.
entries:
resolver-addresses: "x.x.x.x"
resolver-ipv6: "False"`
