### ISSUE TITLE
Documentation specify `server-snippet` instead of `server-snippets` for the ConfigMap option

### ISSUE THREAD

**Issue by raravena80** [nginxinc/kubernetes-ingress#397]
**Describe the bug**
No really a bug, but a typo in the documentation.

Looks like the following in the documentation [here](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#server-snippet) are singular where they should be plural according to the example [here](https://github.com/nginxinc/kubernetes-ingress/blob/3f0740d182a9f46cfc83ef085d9721cb102c97b9/examples/customization/nginx-config.yaml#L43).

- server-snippet
- location-snippet
- http-snippet
- main-snippet
- stream-snippet

**To Reproduce**

Try nginx ingress controller ConfigMap with `server-snippet`. More background [here](https://stackoverflow.com/questions/52782415/nginx-ingress-config-map-snippets-being-ignored-by-the-nginx-conf/52783328?noredirect=1#comment92503518_52783328) 

**Expected behavior**
Configuration takes effect

**Your environment**
Kubernetes all.

**Additional context**

[Background](https://stackoverflow.com/questions/52782415/nginx-ingress-config-map-snippets-being-ignored-by-the-nginx-conf/52783328?noredirect=1#comment92503518_52783328)

**Comment by Dean-Coakley** [comment]
Hi @raravena80 

This is a duplicate issue of: https://github.com/nginxinc/kubernetes-ingress/issues/395

The documentation at https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#server-snippet refers to the [Kubernetes community Ingress Controller](https://github.com/kubernetes/ingress-nginx). 

So the `server-snippets` entry from our [ConfigMap example](https://github.com/nginxinc/kubernetes-ingress/blob/3f0740d182a9f46cfc83ef085d9721cb102c97b9/examples/customization/nginx-config.yaml#L43) is only correct for this Ingress Controller.
