### ISSUE TITLE
NGINX Ingress Controller Enables TCP Forwarding

### ISSUE THREAD

**Issue by liujie-jss** [nginxinc/kubernetes-ingress#3975]
I am using this configuration to enable TCP forwarding: --tcp-services-configmap=$(POD_NAMESPACE)/ingress-nginx-tcp. However, the ingress is showing an error message: "flag provided but not defined: -tcp-services-configmap."
kubernetes-ingress   v2.2.0

**Comment by liujie-jss** [comment]
Okay, I will try forwarding TCP using a different method.

**Comment by brianehlert** [comment]
This project handles TCP using a combination of the TransportServer to define the behavior, the GlobalConfiguration to define the listener, and opening the necessary port at the Service.

There is straight TCP or TLSPassthrough
https://docs.nginx.com/nginx-ingress-controller/configuration/transportserver-resource/
