### ISSUE TITLE
Introduced changes to the immutable MatchLabels to the daemonset in #3606

### ISSUE THREAD

**Issue by hanyouqing** [nginxinc/kubernetes-ingress#3976]
**Describe the bug**
The immutable MatchLabels for DaemonSet was changed in #3606 with no override values option defined in the templates which will cause unexpected downtime for production, cause we have to upgrade by deleting and reinstalling.

```bash
cannot patch "nginx-ingress-nginx-ingress" with kind DaemonSet: DaemonSet.apps "nginx-ingress-nginx-ingress" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"nginx-ingress", "app.kubernetes.io/name":"nginx-ingress"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

**To Reproduce**
Upgrade ingress-nginx 3.0.2 to 3.1.1 

**Expected behavior**
Upgrade ingress-nginx (or make some changes in vaules.yaml in advance) to the target version successfully. 

**Your environment**
* Version of the Ingress Controller: `v3.0.2`
* Version of Kubernetes: `v1.24.10`
* Kubernetes platform (e.g. Mini-kube or GCP): 
* Using NGINX or NGINX Plus: `NGINX Plus`

**Additional context**
Revert this [changes](https://github.com/nginxinc/kubernetes-ingress/pull/3606/files#diff-2eccfbc1886b3803b5035aad15dc3f9f38ecfd0b5c5a540408c828f32d6ab3d3R12-R15) or keep it be compatible with the previous version would be better. FYI @lucacome

**Comment by vepatel** [comment]
Hi @hanyouqing thanks for creating this issue, can you please give us the steps to reproduce the error in the description. We did an upgrade from 3.0.2 to 3.1.1 using `helm upgrade...` and didn't run into it. Please see describe outputs from 3.0.2 and 3.1.1 below.

```
~/nginx/kubernetes-ingress/deployments/helm-chart on tags/v3.0.2 λ k describe daemonsets.apps 
Name:           nginx-ingress-nginx-ingress
Selector:       app=nginx-ingress-nginx-ingress
Node-Selector:  <none>
Labels:         app.kubernetes.io/instance=nginx-ingress
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=nginx-ingress-nginx-ingress
                helm.sh/chart=nginx-ingress-0.16.2


~/nginx/kubernetes-ingress/deployments/helm-chart on tags/v3.1.1 λ k describe daemonsets.apps 
Name:           nginx-ingress-controller
Selector:       app.kubernetes.io/instance=nginx-ingress,app.kubernetes.io/name=nginx-ingress
Node-Selector:  <none>
Labels:         app.kubernetes.io/instance=nginx-ingress
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=nginx-ingress
                app.kubernetes.io/version=3.1.1
                helm.sh/chart=nginx-ingress-0.17.1
```

**Comment by haywoodsh** [comment]
@hanyouqing We noticed in https://github.com/nginxinc/kubernetes-ingress/pull/3977#issuecomment-1583803999 you mentioned you weren't able to reproduce the issue. Could you come back to us if you have any updates on Terraform or Helm?

**Comment by wd** [comment]
@vepatel Yes, you are correct. The problem we are facing is the daemonset will be recreated to change the `MatchLabels` field of the daemonset. That will remove all the pods and recreate them with new labels. This will cause downtime in our production cluster.

**Comment by hanyouqing** [comment]
Sorry @haywoodsh @wd, I finally reproduced the issue with `helm upgrade`.

Let me try to explain what I met first. 

I set the `controller.name` with the previous default value for the upgrading to prevent the daemonset recreation, which will recreate all nginx-ingress pods at the same time, this is not expected and will greatly affect the production services. We prefer to roll update it one by one with the ip address removed from the DNS records in advance during the off-peak period.

The issue is caused by [the matchLables](https://github.com/nginxinc/kubernetes-ingress/compare/v3.0.2...v3.1.1#diff-2eccfbc1886b3803b5035aad15dc3f9f38ecfd0b5c5a540408c828f32d6ab3d3R14-R15) and the [default name](https:github.com/nginxinc/kubernetes-ingress/compare/v3.0.2...v3.1.1#diff-89b93bb7b67a65ee4a4f3de28220b139bf61b94ff603c1e72a9b234fe3904450R1-R2) changes.

Here is how I re-produce it.

```bash
$ helm upgrade --install nginx-ingress nginx-stable/nginx-ingress \
        --version 0.16.2 \
        -n ingress-nginx \
        -f sandbox/11.yaml
Release "nginx-ingress" does not exist. Installing it now.
NAME: nginx-ingress
LAST DEPLOYED: Thu Jun 29 13:47:26 2023
NAMESPACE: ingress-nginx
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
The NGINX Ingress Controller has been installed.

$ helm upgrade --install nginx-ingress nginx-stable/nginx-ingress \
        --version 0.17.1 \
        -n ingress-nginx \
        -f sandbox/22.yaml
Error: UPGRADE FAILED: cannot patch "nginx-ingress-nginx-ingress" with kind DaemonSet: DaemonSet.apps "nginx-ingress-nginx-ingress" is invalid: spec.selector: Invalid value: v1. LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"nginx-ingress", "app.kubernetes.io/name":"nginx-ingress"}, MatchExpressions:[]v1. LabelSelectorRequirement(nil)}: field is immutable
```

The values content of `11.yaml`

```yaml
controller:
  kind: daemonset
  nginxplus: true
  hostNetwork: true
  strategy:
    type: OnDelete
  image:
    tag: 3.0.2
  service:
    create: false
  nginxStatus:
    enable: true
    port: 8080
    allowCidrs: "172.21.0.0/16,127.0.0.1,10.0.0.0/8"
  enableSnippets: true
  defaultTLS:
    secret: ingress-nginx/nginx-default-cert
  enableTLSPassthrough: true
  healthStatus: true
  healthStatusURI: "/health"
  dnsPolicy: ClusterFirstWithHostNet
prometheus:
  create: true
  port: 9113
```

The difference between `11.yaml` and `22.yaml`

```bash
$ diff -urN 11.yaml 22.yaml
--- 11.yaml	2023-06-29 13:46:09
+++ 22.yaml	2023-06-29 13:46:38
@@ -1,12 +1,13 @@
 controller:
+  name: nginx-ingress
   kind: daemonset
   nginxplus: true
   hostNetwork: true
   strategy:
     type: OnDelete
   image:
-    tag: 3.0.2
+    tag: 3.1.1
   service:
     create: false
   nginxStatus:
```

Thanks!

**Comment by vepatel** [comment]
@lucacome

**Comment by vepatel** [comment]
thanks @hanyouqing , we were able to repro this as well:
```
λ helm upgrade test-release --set controller.kind=daemonset --set controller.image.repository=repo_name --set controller.image.tag="tag_name" --set controller.image.pullPolicy=Always .

Error: UPGRADE FAILED: cannot patch "test-release-nginx-ingress" with kind DaemonSet: DaemonSet.apps "test-release-nginx-ingress" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"test-release", "app.kubernetes.io/name":"nginx-ingress"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

**Comment by coolbry95** [comment]
I think a fix for this would look like this.

```
{{/*
 Selector labels
 */}}
 {{- define "nginx-ingress.selectorLabels" -}}
+{{- if .Values.selectorLabelsOverride }}
+{{- .Values.selectorLabelsOverride | toYaml }}
+{{- else }}
 app.kubernetes.io/name: {{ include "nginx-ingress.name" . }}
 app.kubernetes.io/instance: {{ .Release.Name }}
+{{- end}}
 {{- end }}
```

Then you will be able to define the previous selector labels used `app: nginx-ingress`.

**Comment by hanyouqing** [comment]
Thanks @danielnginx , I have also a fixed PR #3977 .

**Comment by hanyouqing** [comment]
Hi @vepatel @haywoodsh, any progress on this issue?

**Comment by vepatel** [comment]
Hi @hanyouqing we're working to find best possible solution to this issue and you can track progress on project tab on right hand side, thanks for your patience!

**Comment by hanyouqing** [comment]
Good to know, thank you so much! @vepatel

**Comment by vepatel** [comment]
Hi @hanyouqing https://github.com/nginxinc/kubernetes-ingress/pull/3977 has been approved 👍🏼
