### ISSUE TITLE
Path to template folders is broken on page

### ISSUE THREAD

**Issue by brianehlert** [nginxinc/kubernetes-ingress#4042]
**Describe the bug**
The two links to the template folders at examples/shared-examples/custom-templates/README.md are broken.

**To Reproduce**
1. https://github.com/nginxinc/kubernetes-ingress/tree/v3.1.1/examples/shared-examples/custom-templates
2. Select the embedded links in the "Notes" section
3. See error

**Comment by ojuschugh1** [comment]
Hi @brianehlert, Is this issue still open, I am interested in working on this issue.

Thanks and Regards

**Comment by brianehlert** [comment]
I thought this might have gotten picked up by our documentation lead.  
Let me reach out to @ADubhlaoich and see if this got taken care of and I missed it.

**Comment by j1m-ryan** [comment]
This was fixed in `v3.4.0`
https://github.com/nginxinc/kubernetes-ingress/tree/v3.4.0/examples/shared-examples/custom-templates
