### ISSUE TITLE
Nginx as Rverese Proxy outside the cluster

### ISSUE THREAD

**Issue by praqmaTim** [nginxinc/kubernetes-ingress#405]
First off, this is more a question than a feature request. I am sorry if this is the wrong place for this. But I simply cannot seem to find the answer any other way.

**Describe situation**
I have a bare metal cluster running a set of **single** container pods. The intent is to get some resiliency, not scaling. 

Right now I have traefik running on a machine as a service. The machine is inside the cluster but nothing is scheduled on it. It is just playing reverse proxy. 

Basically Traefik just points its backend to the cluster api-server. It will discover ingresses and works fine for HTTP. Several of the applications in the cluster expose some service over TCP. Right now I have exposed them as NodPorts, which is why I have this machine as a cluster node.

**Describe the solution you'd like**
What I would like to do is.

Have a pair of Nginx services running on two machines, with a floating VIP. DNS points to these machines with round robin. 

These Nginx's can rout external traffic both HTTP and TCP according to the ingresses in the cluster. So **not** expose the TCP services as NodePorts. But rather have requests routed over the same ingress "host" (http://myapplication.com:TCP-PORT) to the proper service exposed as an ingress.

This looks like a possible solution to me. But I am not sure. If so do you have any example configurations?

**Comment by pleshakov** [comment]
@praqmaTim thanks for the question. the issues is a good place for asking a question.

Please let me know if the following approach can work for you:

* You can run the Ingress Controller on two dedicated nodes of your cluster using a [DaemonSet](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/installation.md#32-create-a-daemonset)
* Between those nodes, you can configure a VIP. Unfortunately, there is no ready solution or instructions that we can provide for this.
* To expose TCP applications, additional step is required for the IC configuration -- please see this example -- https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/tcp-udp
* You map ports 80 and 443 of NGINX Ingress Controller container to same ports of the nodes or use `hostNetwork: True` in the pod template.

**Comment by praqmaTim** [comment]
@pleshakov Thanks for the response. Sorry for the slow reply. 

This looks like it will work for me. 

Not sure I quite get bullet three. I have a question regarding bullet three.

- coredns pods are already running in my cluster. It was setup with kubeadm. So do I need that step? It seems that the configMap at least is different...

**Comment by pleshakov** [comment]
@praqmaTim 
Coredns is not required. In our tcp-udp example a specially configured coredns deployment is used as an application to load balance, so that we can show and test that TCP/UDP load balancing works. you can use the NGINX config from that example as a starting point for TCP/UDP config for your applications.
