### ISSUE TITLE
Helm chart HPA condition 

### ISSUE THREAD

**Issue by glieske** [nginxinc/kubernetes-ingress#4069]
**Describe the bug**

https://github.com/nginxinc/kubernetes-ingress/blob/v3.2.0/deployments/helm-chart/templates/controller-hpa.yaml#L1

I'm having issues with the last condition, `(semverCompare ">=1.23.0" .Capabilities.KubeVersion.Version)` while working with an AWS EKS 1.25 cluster. The value stored under ".Capabilities.KubeVersion.Version" is `v1.25.10-eks-c12679a`, which is a newer version than 1.23 but not a valid semver version. As a result, the HPA is not being deployed by the helm chart.

**To Reproduce**
1. `Deploy the helm chart with autoscaling enabled on AWS EKS with the 1.25 cluster.

**Expected behavior**
An HPA resource should be created.

**Your environment**
* Version of the Ingress Controller - 3.2.0
* Version of Kubernetes - 1.25
* Kubernetes platform (e.g. Mini-kube or GCP) AWS EKS
* Using NGINX or NGINX Plus - NGINX

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by vepatel** [comment]
Thanks @glieske for opening this issue, looks like EKS specific and they've no plans to address this either https://github.com/helm/helm/issues/10375#issuecomment-986496851, I'll have a discussion on this with the wider team.
cc @coolbry95

**Comment by lucacome** [comment]
I think we can check if HPA is available rather than checking the version of k8s

**Comment by vepatel** [comment]
with changes in https://github.com/nginxinc/kubernetes-ingress/pull/4070

```
~/nginx/kubernetes-ingress/deployments/helm-chart on main ● λ k get hpa
NAME                                    REFERENCE                                          TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
test-release-nginx-ingress-controller   Deployment/test-release-nginx-ingress-controller   12%/50%, 2%/50%   3         4         3          32s
```
