### ISSUE TITLE
nginx.ingress.kubernetes.io/default-backend annotation  is not working

### ISSUE THREAD

**Issue by endejoli** [nginxinc/kubernetes-ingress#4077]
**Describe the bug**
We have a default backend service for nginx ingress that handles the 404, 503 errors etc.  With one of our applications, we want to overwrite the default backend with a specific service.
we have added the annotation under ingress of our service 
```
  annotation:
    nginx.ingress.kubernetes.io/default-backend: mybackend-svc
```
This annotation has no effect.  Ingresss is serving the HTML pages that are pointed by the default backend service. 

version:  registry.k8s.io/ingress-nginx/controller:v1.5.1@sha256:4ba73c697770664c1e00e9f968de14e08f606ff961c76e5d7033a4a9c593c629
Kubernetes version: v1.24.10
Kubernetes platform: AKS
Using NGINX

**Comment by vepatel** [comment]
Hi @endejoli looks like you're referring to https://github.com/kubernetes/ingress-nginx which is a totally different project. See
https://www.nginx.com/blog/guide-to-choosing-ingress-controller-part-4-nginx-ingress-controller-options/#NGINX-vs.-Kubernetes-Community-Ingress-Controller
