### ISSUE TITLE
Add imagepullsecrets to daemonset and deployment spec helm-chart

### ISSUE THREAD

**Issue by jrmercier1** [nginxinc/kubernetes-ingress#415]
Currently the process to build plus involves us pushing an image to an internally hosted repo that requires authentication.  The current chart from what I can tell does not allow you to specify imagepullsecrets on release deployment.

**Additional context**
The current work around is for me to attach secret to service account or alter the helm chart to process an imagePullSecrets section.  I am currently using the chart modification route which will eventually cause issues keeping the local chart in sync with the latest nginxinc chart.

**Current work around**
>>cat controller-daemonset.yaml
spec:
     ...
      {{- if .Values.imagePullSecrets.name }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name | quote }}
      {{- end }}
     ...

>> cat values-plus.yaml
...
imagePullSecrets:
  name:
...

**Comment by pleshakov** [comment]
@jrmercier1 
Thanks for the suggestion. We will add the `imagePullSecrets` parameter to the Helm chart.

is there any special reason you placed `imagePullSecrets` into the daemonset template rather then the service account template?

**Comment by jrmercier1** [comment]
No reason other than not having to taint the service account namespace wide.  Either would work in this particular case since we are only using a single release/service account.
