### ISSUE TITLE
Add documentation to provide instructions for no downtime upgrade using helm

### ISSUE THREAD

**Issue by vepatel** [nginxinc/kubernetes-ingress#4153]
**Is your feature request related to a problem? Please describe.**
When user is upgrading IC version from 3.0.2 to later ones, the helm upgrade process is doing a recreate for deployment/daemonset and service due to naming and label changes introduced in 3.1.0 causing a downtime for customer.

This should also cover moving from a 2.x such as 2.4.2

**Describe the solution you'd like**
Add step-by-step instructions on how to upgrade without having to recreate these resources and add the document o docs.nginx.com

**Comment by coolbry95** [comment]
Please make sure controller.selectorLabels are documented.

https://github.com/nginxinc/kubernetes-ingress/blob/main/deployments/helm-chart/values.yaml#L9
