### ISSUE TITLE
in nginx-ingress pod is not creating the application conf

### ISSUE THREAD

**Issue by vadlakiran** [nginxinc/kubernetes-ingress#4226]
once we have deployed the nginx-ingress as a deamonset everything looks fine but we are not able to reach the endpoint, when i checked inside the daemonset pod, not created the dynamic application config files under /etc/nginx/conf.d

what might be the reason, could you please guide me on this ?

**To Reproduce**

1. Deploy x to '...' using some.yaml
2. View logs on '....'
3. See error

**Expected behavior**

**Your environment**

- Version of the Ingress Controller - release version or a specific commit : v2.0.3
- Version of Kubernetes  -- v1.22.3
- Kubernetes platform (e.g. Mini-kube or GCP) ; vms
- Using NGINX or NGINX Plus : NGINX

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by vadlakiran** [comment]
`kubectl exec -it nginx-ingress-lsjtg -n nginx-ingress bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
nginx@nginx-ingress-lsjtg:/$ cd /etc/nginx/conf.d
nginx@nginx-ingress-lsjtg:/etc/nginx/conf.d$ ls -ltr
total 0
nginx@nginx-ingress-lsjtg:/etc/nginx/conf.d$
`

**Comment by brianehlert** [comment]
Beyond the deployment, there are configuration objects.  Those are either in the same namespace at the ingress controller or different namespaces that the ingress controller must know to monitor.
In what namespace(s) are your Ingress or VirtualServer YAML configurations defined?

Can you please provide a describe of your deployment and configuration objects.

**Comment by vadlakiran** [comment]
@brianehlert below are the daemonset yaml file and configmap which we deployed

`
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
     #annotations:
       #prometheus.io/scrape: "true"
       #prometheus.io/port: "9113"
    spec:
      serviceAccountName: nginx-ingress
      containers:
      - image: nexus.monad.moneris.com:8445/nginx-ingress:2.0.3
        imagePullPolicy: Always
        name: nginx-ingress
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
        # - name: prometheus
          # containerPort: 9113
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args:
          - -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
          - -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret
          - -v=3 # Enables extensive logging. Useful for troubleshooting.
          - -nginx-debug
         #- -report-ingress-status
         #- -external-service=nginx-ingress
         #- -enable-leader-election
         #- -enable-prometheus-metrics
         #- -global-configuration=$(POD_NAMESPACE)/nginx-configuration
         #- -enable-custom-resources
      imagePullSecrets:
        - name: internal-registry-credentials
`

below is the configmap

`
kind: configMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  error-log-level: "debug"
  worker-process: "auto"
  worker-connections: "100000"
  worker-rlimit-nofile: "102400"
  keepalive-timeout:  "315s"
  keepalive-requests: "10000000"
  keepalive: "200"
  access-log-off: "true"
`

**Comment by vadlakiran** [comment]
we have deployed nginx-ingress namespace only

**Comment by brianehlert** [comment]
Do you have any Ingress or VirtualServer or TransportServer resources?

**Comment by vadlakiran** [comment]
below is the ingress resource which we deployed

`
apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{},"name":"aci-rest-client-ingress","namespace":"aci"},"spec":{"rules":[{"host":"aci-rest-clientdevnx.devad.moneris.com","http":{"paths":[{"backend":{"service":{"name":"aci-rest-client-service","port":{"number":8080}}},"path":"/","pathType":"ImplementationSpecific"}]}}],"tls":[{"hosts":["aci-rest-clientdevnx.devad.moneris.com"],"secretName":"aci-rest-client-cert"}]}}
    creationTimestamp: "2023-08-10T22:12:28Z"
    generation: 1
    name: rest-client-ingress
    namespace: aci
    resourceVersion: "293085028"
    uid: 3956c6cc-43a6-4a42-880f-626079c7513a
  spec:
    rules:
    - host: rest-clientdevnx.devad.example.com
      http:
        paths:
        - backend:
            service:
              name: rest-client-service
              port:
                number: 8080
          path: /
          pathType: ImplementationSpecific
    tls:
    - hosts:
      - rest-clientdevnx.devad.example.com
      secretName: rest-client-cert
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
`

**Comment by jasonwilliams14** [comment]
@vadlakiran can you provide the entire output of `nginx -T` ?
```
kubectl exec -it -n nginx-ingress <pod> -- nginx -T
```

**Comment by vadlakiran** [comment]
`
λ kubectl exec -it nginx-ingress-xn4f5 -n nginx-ingress -- nginx -T
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
# configuration file /etc/nginx/nginx.conf:

worker_processes  auto;
worker_rlimit_nofile 102400;
daemon off;

error_log  stderr debug;
pid        /var/lib/nginx/nginx.pid;

events {
    worker_connections  100000;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';


    access_log off;




    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout 315s;
    keepalive_requests 10000000;

    #gzip  on;

    server_names_hash_max_size 1024;
    server_names_hash_bucket_size 256;

    variables_hash_bucket_size 256;
    variables_hash_max_size 1024;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }
    map $http_upgrade $vs_connection_header {
        default upgrade;
        ''      $default_connection_header;
    }








    server {
        # required to support the Websocket protocol in VirtualServer/VirtualServerRoutes
        set $default_connection_header "";
        set $resource_type "";
        set $resource_name "";
        set $resource_namespace "";
        set $service "";

        listen 80 default_server;


        listen 443 ssl default_server;



        ssl_certificate /etc/nginx/secrets/default;
        ssl_certificate_key /etc/nginx/secrets/default;






        server_name _;
        server_tokens "on";






        location / {
            return 404;
        }
    }
    # stub_status
    server {
        listen 8080;

        allow 127.0.0.1;
        deny all;

        location /stub_status {
            stub_status;
        }
    }

    include /etc/nginx/config-version.conf;
    include /etc/nginx/conf.d/*.conf;

    server {
        listen unix:/var/lib/nginx/nginx-502-server.sock;
        access_log off;



        return 502;
    }

    server {
        listen unix:/var/lib/nginx/nginx-418-server.sock;
        access_log off;



        return 418;
    }
}

stream {
    log_format  stream-main  '$remote_addr [$time_local] '
                      '$protocol $status $bytes_sent $bytes_received '
                      '$session_time "$ssl_preread_server_name"';

    access_log  /dev/stdout  stream-main;





    include /etc/nginx/stream-conf.d/*.conf;
}

# configuration file /etc/nginx/mime.types:

types {
    text/html                                        html htm shtml;
    text/css                                         css;
    text/xml                                         xml;
    image/gif                                        gif;
    image/jpeg                                       jpeg jpg;
    application/javascript                           js;
    application/atom+xml                             atom;
    application/rss+xml                              rss;

    text/mathml                                      mml;
    text/plain                                       txt;
    text/vnd.sun.j2me.app-descriptor                 jad;
    text/vnd.wap.wml                                 wml;
    text/x-component                                 htc;

    image/png                                        png;
    image/svg+xml                                    svg svgz;
    image/tiff                                       tif tiff;
    image/vnd.wap.wbmp                               wbmp;
    image/webp                                       webp;
    image/x-icon                                     ico;
    image/x-jng                                      jng;
    image/x-ms-bmp                                   bmp;

    font/woff                                        woff;
    font/woff2                                       woff2;

    application/java-archive                         jar war ear;
    application/json                                 json;
    application/mac-binhex40                         hqx;
    application/msword                               doc;
    application/pdf                                  pdf;
    application/postscript                           ps eps ai;
    application/rtf                                  rtf;
    application/vnd.apple.mpegurl                    m3u8;
    application/vnd.google-earth.kml+xml             kml;
    application/vnd.google-earth.kmz                 kmz;
    application/vnd.ms-excel                         xls;
    application/vnd.ms-fontobject                    eot;
    application/vnd.ms-powerpoint                    ppt;
    application/vnd.oasis.opendocument.graphics      odg;
    application/vnd.oasis.opendocument.presentation  odp;
    application/vnd.oasis.opendocument.spreadsheet   ods;
    application/vnd.oasis.opendocument.text          odt;
    application/vnd.openxmlformats-officedocument.presentationml.presentation
                                                     pptx;
    application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
                                                     xlsx;
    application/vnd.openxmlformats-officedocument.wordprocessingml.document
                                                     docx;
    application/vnd.wap.wmlc                         wmlc;
    application/wasm                                 wasm;
    application/x-7z-compressed                      7z;
    application/x-cocoa                              cco;
    application/x-java-archive-diff                  jardiff;
    application/x-java-jnlp-file                     jnlp;
    application/x-makeself                           run;
    application/x-perl                               pl pm;
    application/x-pilot                              prc pdb;
    application/x-rar-compressed                     rar;
    application/x-redhat-package-manager             rpm;
    application/x-sea                                sea;
    application/x-shockwave-flash                    swf;
    application/x-stuffit                            sit;
    application/x-tcl                                tcl tk;
    application/x-x509-ca-cert                       der pem crt;
    application/x-xpinstall                          xpi;
    application/xhtml+xml                            xhtml;
    application/xspf+xml                             xspf;
    application/zip                                  zip;

    application/octet-stream                         bin exe dll;
    application/octet-stream                         deb;
    application/octet-stream                         dmg;
    application/octet-stream                         iso img;
    application/octet-stream                         msi msp msm;

    audio/midi                                       mid midi kar;
    audio/mpeg                                       mp3;
    audio/ogg                                        ogg;
    audio/x-m4a                                      m4a;
    audio/x-realaudio                                ra;

    video/3gpp                                       3gpp 3gp;
    video/mp2t                                       ts;
    video/mp4                                        mp4;
    video/mpeg                                       mpeg mpg;
    video/quicktime                                  mov;
    video/webm                                       webm;
    video/x-flv                                      flv;
    video/x-m4v                                      m4v;
    video/x-mng                                      mng;
    video/x-ms-asf                                   asx asf;
    video/x-ms-wmv                                   wmv;
    video/x-msvideo                                  avi;
}

# configuration file /etc/nginx/config-version.conf:
server {
    listen unix:/var/lib/nginx/nginx-config-version.sock;
        access_log off;



    location /configVersion {
        return 200 1;
    }
}
map $http_x_expected_config_version $config_version_mismatch {
        "1" "";
        default "mismatch";
}

`

**Comment by jasonwilliams14** [comment]
@vadlakiran One more question.
Can you provide the output of

```
kubectl get ing -A
```

Also, can you provide the logs for NIC as well

**Comment by vadlakiran** [comment]
@jasonwilliams14  below are the ingress which we created

`
master1:~$ kubectl get ing -A
NAMESPACE   NAME                  CLASS   HOSTS                      ADDRESS   PORTS     AGE
default     ingress           nginx   test.example.com                 80, 443   4d6h
default     ingress           nginx   test.example.com                 80, 443   4d6h
default     rest-ingress      nginx   test.example.com             80, 443   4d6h
default     webapp-ingress-ipv4   nginx   webapp.test.example.com              80, 443   4d6h
draj@master1:~$

`

**Comment by vadlakiran** [comment]
@jasonwilliams14 
i just resolved the issue to updated the nginx-vs-ingress correct values

**Comment by brianehlert** [comment]
> @jasonwilliams14 i just resolved the issue to updated the nginx-vs-ingress correct values

Would you mind sharing additional detail for other uses that might discover this thread matches a problem they are experiencing?
