### ISSUE TITLE
Use `lease` instead of a `configmap` to acquire leader election lock

### ISSUE THREAD

**Issue by shaun-nx** [nginxinc/kubernetes-ingress#4295]
**Is your feature request related to a problem? Please describe.**
TBD

**Describe the solution you'd like**
TBD

**Describe alternatives you've considered**
TBD

**Additional context**
TBD

**Comment by brianehlert** [comment]
I see automation closed this.
However, I am curious if this is indeed something that needs to be addressed to catch up with K8s.

**Comment by brianehlert** [comment]
Looks like this was implemented with #4276 
Is that correct?

**Comment by vepatel** [comment]
@brianehlert yes this one can be closed 👍🏼

**Comment by oseoin** [comment]
Closing as completed in #4276

**Comment by brianehlert** [comment]
I am fishing if configmap still works at all?
Since I understand the command line option is still present, which implies the configmap code is still present.
And thus to potential for someone to use both configmap and lease at the same time.
