### ISSUE TITLE
SSL Termination example via configMap

### ISSUE THREAD

**Issue by hkailantzis** [nginxinc/kubernetes-ingress#431]
Could you please shed some light/point to the right direction, on how to enable https for ingresses ?. Thanks in advance.

Tried the following example, but not sure how to load the ssl certificates for the domains that I have at the moment, 6 in total.

https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/ssl-services

I get an error: 
2018/11/09 08:29:38 [error] 46#46: *1760 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream

Environment: minikube 1.10
ingress controller version: edge
using NGINX

**Comment by pleshakov** [comment]
Please take a look at this example -- https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/complete-example

**Comment by hkailantzis** [comment]
Thanks for the pointer @pleshakov . Missed to specify though that, since I have a lot of ingresses to maintain, I'm looking for a way to do it via the configMap. Is there such option ?

**Comment by pleshakov** [comment]
@hkailantzis it is not possible to configure TLS termination via ConfigMap

**Comment by hkailantzis** [comment]
@pleshakov thanks for your reply. In the meantime, I tried defining in 'http-snippets' in configMap, with repeating server blocks like below.
I get the green lock on the browser for the domains that I'm trying to, but 404 from nginx. the certificates are loaded correctly, ie they're valid, so I was thinking that is a matter of configuration only. so I guess is not a possibility, right ?
```
server {
      listen 443 ssl;
      server_name domainone.com;

      ssl_certificate       /ssl/domainone.pem;
      ssl_certificate_key   /ssl/domainone.key;
    }

**Comment by hkailantzis** [comment]
@pleshakov I followed the example you posted. e.g. added the tls section in the ingress, and also with or without the "nginx.org/ssl-services", annotation as indicated here:  https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/ssl-services, 
I still get 404 from nginx. and nothing in the logs via https (via http I get the infamous ssl handshake error if that annotation is added). So not sure how to debug this. Do you have any hint ? Please, let me know if you need anything from my end.

**Comment by hkailantzis** [comment]
had to restart nginx to see this, but nginx logs state that it can't find the tls secret. Which is strange as its deployed at the same namespace as the ingress. so not sure why it can't find it.

**Comment by pleshakov** [comment]
@hkailantzis 
my apologies. I completely missed your latest messages.

if you still have the issue, please share the Ingress resource that you used and the logs from the IC pod. That should help identify the problem.
