### ISSUE TITLE
404 error ingress controller

### ISSUE THREAD

**Issue by mahendra03** [nginxinc/kubernetes-ingress#4312]
Hi Team,

I am using k8s version - 1.27.3-gke.100 and trying to install ingress controller with below command in my GKE k8s cluster 
under default namespace with below commands.
Using nginx version: nginx/1.25.2
nginx-ingress: nginx/nginx-ingress:3.2.

helm pull oci://ghcr.io/nginxinc/charts/nginx-ingress --untar --version 0.18.1
cd nginx-ingress
helm install my-release .

I need to create internal load balancer so i have added below annotation 

networking.gke.io/load-balancer-type: "Internal"
networking.gke.io/internal-load-balancer-allow-global-access: "true"
nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

I have also deploy some service but when I am checking the logs of k8s ingress controller then getting below error 

HTTP/1.1" 404 153 "-" "curl/7.61.1"

**Comment by jasonwilliams14** [comment]
@mahendra03 It looks like your deploying of NGINX Ingress is successful. The 404 from NGINX Ingress is saying it cannot find the request you made.
Can you provide your curl request and the application you are trying to access via curl?
Can you also provide the output of your resources (Ingress our virtualserver) so we can verify they are being created correctly.
THanks

**Comment by mahendra03** [comment]
Hi @jasonwilliams14 ,

We are hitting below url and yes we are trying to access application with below url.

curl -s --location --request POST 'http://10.0.33.44:80/add/stand' 

Below is the output 

<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.25.2</center>
</body>
</html>


When I go inside the pod and then i run exec command and run http://service-name:80 then it is giving some repsonse.

**Comment by jasonwilliams14** [comment]
@mahendra03 try specifying a hostname or passing in a host header.
Similar to one of our examples:

```
curl --resolve cafe.example.com:$IC_HTTPS_PORT:$IC_IP https://cafe.example.com:$IC_HTTPS_PORT/coffee --insecure
```
https://github.com/nginxinc/kubernetes-ingress/tree/main/examples/custom-resources/basic-configuration

**Comment by mahendra03** [comment]
Hi @jasonwilliams14 ,

I am doing this then getting below
