### ISSUE TITLE
Fresh installing 3.2.1 requires previous versions 3.1.1

### ISSUE THREAD

**Issue by davisli** [nginxinc/kubernetes-ingress#4316]
**Describe the bug**
Fresh installing 3.2.1 requires previous versions 3.1.1?

**To Reproduce**
Trying to pull private-registry.nginx.com/nginx-ic/nginx-plus-ingress:3.2.1...
Error: determining manifest MIME type for docker://private-registry.nginx.com/nginx-ic/nginx-plus-ingress: 3.2.1: reading manifest sha256:a81c42
e71d06d91b79a2dc5d7631ac81274adb0af8a20c62b57bedf7d2be741a in private-registry.nginx.com/nginx-ic/nginx-plus-ingress: manifest unknown: OCI manifest found, but accept header does not support OCI manifests

**Expected behavior**
In a fresh install, pulling 3.2.1 will fail. We had to pull 3.1.1 before pulling 3.2.1. It seems 3.2.1 had dependencies to previous versions? 

**Your environment**

**Additional context**

**Comment by vepatel** [comment]
Hi @davisli Can yo provide more details? I just tried and fresh install of 3.2.1. on GKE and it went without a hitch.

**Comment by jasonwilliams14** [comment]
@davisli Please provide more information, including the command you are using if using helm as well as how you can configured your .yaml files and secret.
I tested 3.2.1 in my local cluster and it works as expected.
