### ISSUE TITLE
Helm chart HPA condition fix not released.

### ISSUE THREAD

**Issue by AlessioCasco** [nginxinc/kubernetes-ingress#4323]
**Describe the bug**

Hello!

It seems that the fix for issue #4069 that was merged with PR #4070 is still not present in the latest helm chart [0.18.1](https://artifacthub.io/packages/helm/nginx/nginx-ingress/0.18.1)

We are also impacted by this and were hoping that the fix would have been released by now.

Doing a `helm pull` and opening the `controller-hpa.yaml` file still shows the incriminated first line :-)

```yaml
{{- if and .Values.controller.autoscaling.enabled (eq .Values.controller.kind "deployment") (semverCompare ">=1.23.0" .Capabilities.KubeVersion.Version) -}}
[...]
```

Thanks a ton
Alessio

**Comment by vepatel** [comment]
Hi @AlessioCasco, this fix will be released in next major release i.e. NIC `v3.3.0` and helm chart `v0.19.0` by the end of September.

**Comment by AlessioCasco** [comment]
Hi! @vepatel, thanks for the quick update and explanation. 
Closing
