### ISSUE TITLE
main builds are broken

### ISSUE THREAD

**Issue by vepatel** [nginxinc/kubernetes-ingress#4324]
**Describe the bug**
Unable to build NIC images locally after merging https://github.com/nginxinc/kubernetes-ingress/pull/4152

**To Reproduce**
1.  `make debian-image PREFIX=nginx-ingress VERSION=main DOCKER_BUILD_OPTIONS="--platform linux/amd64" TARGET=container`

**Expected behavior**
Build should be successful

**Your environment**

- Version of the Ingress Controller - `main`
- Version of Kubernetes : 1.27
- Kubernetes platform (e.g. Mini-kube or GCP): GKE
- Using NGINX or NGINX Plus

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by vepatel** [comment]
@9bany any insights into this, I'm unable to build locally and getting: 
```
#26 0.456 no required module provides package github.com/nginxinc/kubernetes-ingress/cmd/nginx-ingress; to add it:
#26 0.456       go get github.com/nginxinc/kubernetes-ingress/cmd/nginx-ingress
------
executor failed running [/bin/sh -c CGO_ENABLED=0 GOOS=linux GOARCH=$TARGETARCH go build -trimpath -ldflags "-s -w -X main.version=${IC_VERSION}" -o /nginx-ingress github.com/nginxinc/kubernetes-ingress/cmd/nginx-ingress]: exit code: 1
make: *** [debian-image-plus] Error 1
```

running `go get github.com/nginxinc/kubernetes-ingress/cmd/nginx-ingress` installs an older package

**Comment by 9bany** [comment]
Thanks @vepatel  

I was fix: https://github.com/nginxinc/kubernetes-ingress/pull/4326

And after that, i was run build locally and i got this error

```                                                                                                                                 ─╯
fatal: No names found, cannot describe anything.
Docker version 24.0.5, build ced0996
go version go1.21.0 darwin/amd64
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags "-s -w -X main.version=untagged-SNAPSHOT" -o nginx-ingress github.com/nginxinc/kubernetes-ingress/cmd/nginx-ingress
# github.com/nginxinc/kubernetes-ingress/internal/k8s
../../../pkg/mod/github.com/nginxinc/kubernetes-ingress@v1.12.5/internal/k8s/leader.go:29:23: undefined: resourcelock.ConfigMapLock
../../../pkg/mod/github.com/nginxinc/kubernetes-ingress@v1.12.5/internal/k8s/status.go:133:40: cannot use status (variable of type []"k8s.io/api/core/v1".LoadBalancerIngress) as []"k8s.io/api/networking/v1beta1".IngressLoadBalancerIngress value in assignment
make: *** [Makefile:77: build] Error 1
```

i think `nginxinc/kubernetes-ingress@v1.12.5` incompatible with `k8s.io/client-go v0.28.0`, but i ain't update `k8s.io/client-go` version, Do you have an idea for this issue ?

**Comment by vepatel** [comment]
yeah I was expecting an updated library in dev go-pkg with this change, @9bany I'll probably revert this one for now and have a discussion with wider team on remediation strategies later on.

**Comment by 9bany** [comment]
yeah ! Thanks @vepatel
let's me pick it up

**Comment by vepatel** [comment]
@9bany you okay with me reverting https://github.com/nginxinc/kubernetes-ingress/pull/4152? I'd rather have this go in along with local build fix.

**Comment by 9bany** [comment]
@vepatel it's okey, please revert it
