### ISSUE TITLE
VirtualServerRoute "NoVirtualServerFound", because VirtualServer is added after the VirtualServerRoute 

### ISSUE THREAD

**Issue by kevinskyba** [nginxinc/kubernetes-ingress#4340]
**Describe the bug**
My VirtualServerRoute is throwing the "NoVirtualServerFound" error/warning. I feel like the issue is that the VirtualServerRoute is "evaluated" first? So it throws a NoVirtualServerFound error because the VirtualServer "AddedOrUpdated"-Event is triggered slightly after that?

I had this setup running for 8 hours and the state did not change. The controller never managed to properly detect and add the VirtualServerRoute. At first I thought it might have to do with my configuration or the fact that the VirtualServerRoute is in another namespace, but then I saw the controller logs and that the VirtualServerRoute is actually appearing there, so there must be some kind of communication going on.

So is there a way for me to fix this?

My nginx-ingress controller logs look like this:

> 2023/09/11 19:12:13 [notice] 12#12: nginx/1.25.2
> 2023/09/11 19:12:13 [notice] 12#12: built by gcc 12.2.0 (Debian 12.2.0-14)
> 2023/09/11 19:12:13 [notice] 12#12: OS: Linux 5.10.186-179.751.amzn2.x86_64
> 2023/09/11 19:12:13 [notice] 12#12: getrlimit(RLIMIT_NOFILE): 1048576:1048576
> 2023/09/11 19:12:13 [notice] 12#12: start worker processes
> 2023/09/11 19:12:13 [notice] 12#12: start worker process 13
> 2023/09/11 19:12:13 [notice] 12#12: start worker process 14
> I0911 19:12:13.678762       1 listener.go:55] Starting Prometheus listener on: :9113/metrics
> I0911 19:12:13.679579       1 leaderelection.go:245] attempting to acquire leader lease default/controller-nginx-ingress-leader-election...
> I0911 19:12:13.780507       1 event.go:298] Event(v1.ObjectReference{Kind:"VirtualServerRoute", Namespace:"test-customer", Name:"cms-service-virtual-route", UID:"94530139-acc4-4f59-be80-4af77bc594a9", APIVersion:"k8s.nginx.org/v1", ResourceVersion:"319653", FieldPath:""}): type: 'Warning' reason: 'NoVirtualServerFound' VirtualServer is invalid or doesn't exist
> I0911 19:12:13.780735       1 event.go:298] Event(v1.ObjectReference{Kind:"VirtualServer", Namespace:"default", Name:"master-virtual-server", UID:"cea7cb75-526e-4bca-81c7-07a52f76fb73", APIVersion:"k8s.nginx.org/v1", ResourceVersion:"318485", FieldPath:""}): type: 'Normal' reason: 'AddedOrUpdated' Configuration for default/master-virtual-server was added or updated
> 2023/09/11 19:12:13 [notice] 12#12: signal 1 (SIGHUP) received from 19, reconfiguring

**To Reproduce**

I have the following resources:

service.yaml in namespace "test-customer""

> ... 
> 
> ---
> 
> apiVersion: v1
> kind: Service
> metadata:
>   name: cms-service
> spec:
>   ports:
>     - port: 80
>       targetPort: 1337
>       protocol: TCP
>   type: NodePort
>   selector:
>     app: cms
> 
> ---
> 
> apiVersion: k8s.nginx.org/v1
> kind: VirtualServerRoute
> metadata:
>   name: cms-service-virtual-route
> spec:
>   host: KUSTOMIZE_API_HOST
>   ingressClassName: "elb"
>   upstreams:
>     - name: cms-service-upstream
>       service: cms-service
>       port: 1337
>   subroutes:
>     - path: /
>       action:
>         pass: cms-service-upstream
> 

my main-stack in default namespace:

>         ...
>         const nginxChart = cluster.addHelmChart('IngressController', {
>             chart: 'nginx-ingress',
>             repository: 'https://helm.nginx.com/stable',
>             release: ingressControllerReleaseName,
>             values: {
>               controller: {
>                 publishService: {
>                   enabled: true,
>                 },
>                 ingressClass: "elb",
>                 service: {
>                   annotations: {
>                     'service.beta.kubernetes.io/aws-load-balancer-type': 'nlb',
>                     'service.beta.kubernetes.io/aws-load-balancer-backend-protocol': 'http',
>                     'service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout': '3600'
>                   },
>                 },
>               },
>             },
>           });
> 
>         const elbAddressObject = new eks.KubernetesObjectValue(this, 'elbAddress', {
>             cluster,
>             objectType: 'Service',
>             objectName: `${ingressControllerReleaseName}-nginx-ingress-controller`,
>             jsonPath: '.status.loadBalancer.ingress[0].hostname',
>         });
> 
>         this.nlbDomain = elbAddressObject.value;
> 
>         const masterVirtualServer = new eks.KubernetesManifest(this, "VirtualServer", {
>             cluster: cluster,
>             overwrite: true,
>             manifest: [{
>                 "apiVersion": "k8s.nginx.org/v1",
>                 "kind": "VirtualServer",
>                 "metadata": {
>                     "name": "master-virtual-server"
>                 },
>                 "spec": {
>                     "host": `${this.nlbDomain}`,
>                     "ingressClassName": "elb"
>                 }
>             }]
>         });

**Expected behavior**
I expect the VirtualServerRoute and VirtualServer  both to be properly added to the controller and my nginx config being created based on the VirtualServer configuration.

**Your environment**

- Version of the Ingress Controller: **latest / stable**
- Version of Kubernetes: **1.24**
- Kubernetes platform: **AWS EKS**

**Comment by shaun-nx** [comment]
Hi @kevinskyba 
Thanks for opening this issue! I'll do my best to help you resolve this.

Can you provide your virtualserver.yaml file as well? We will need to see how your route is configured to know exactly why your VirtualServerRoute has not been found.

**Comment by shaun-nx** [comment]
Hi @kevinskyba 

Thank for opening this issue! I'll do my best to explain why this is happening.

Looking at the main stack output that you provided, I see that your VirtualServer does not have a reference to your VirtualServerRoute

```
 manifest: [{
            "apiVersion": "k8s.nginx.org/v1",
            "kind": "VirtualServer",
            "metadata": {
                "name": "master-virtual-server"
            },
            "spec": {
                "host": `${this.nlbDomain}`,
                "ingressClassName": "elb"
            }
        }]
    });
```

You will need to add a `route` to your VirtualServer `spec` and configure it to point to your VirtualServerRoute

Here is an example of what your VirtualServer might look like.
```yaml
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: master-virtual-server
spec:
  host: KUSTOMIZE_API_HOST
  routes:
  - path: /cmsService
    route: test-customer/cms-service-virtual-route  #namespace/name of the VirtualServerRoute
```

Note: Since your VirtualServerRoute exists in a different namespace, the namespace needs to be included in the `route` of your VirtualServer. This is why the example route here is `route: test-customer/cms-service-virtual-route`

If anything here is unclear, please do ask!

I also recommend looking at our documentation on configuring VirtualServerRoutes here if you need more defaults: https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/

**Comment by shaun-nx** [comment]
Hi @kevinskyba
Closing this issue as it has been several weeks since there has been any conversation. Please feel free to re-open this issue if the problem persists or if the advice given did not resolve your issue. Thank you!
