### ISSUE TITLE
Extend listener controls to Ingress

### ISSUE THREAD

**Issue by danielnginx** [nginxinc/kubernetes-ingress#4393]
```[tasklist]
### Tasks
- [ ] Design Solution
```

**Comment by danielnginx** [comment]
Consider interaction/dependency to GC CRD:

Maintaining existing functionality 
Alerting on non supported annotation

**Comment by shaun-nx** [comment]
Closing this issue as currently Ingress has the same capabilities as VirtualServer in terms of listener controls.
