### ISSUE TITLE
Enable an option to omit http/s listeners entirely

### ISSUE THREAD

**Issue by danielnginx** [nginxinc/kubernetes-ingress#4394]
Use case:

- I want to disable default HTTP/S listeners
- I want https listener and not http listener
- corporate requirement to close 80/443 and only listen on alternate ports for http/s

Support reading:

L7 Listen:  https://nginx.org/en/docs/http/ngx_http_core_module.html#listen
L4 Listen: https://nginx.org/en/docs/stream/ngx_stream_core_module.html#listen
```[tasklist]
### Tasks
- [x] Design Solution
```

**Comment by shaun-nx** [comment]
Current plan is to implement a "disallowedPorts" option via a ConfigMap.
Intention of this configuration is to provider users with a means to prevent Ingress, VirtualServer and TransportServers from being deployed into a cluster when configured with specific ports.

**Comment by brianehlert** [comment]
My interpretation of the term "disallowedPorts" is that these ports are blocked from ever having a listener, it is global, and we will have business logic and messages enforcing that.

But how does that relate to the default http listeners that the templates always try to add?

**Comment by shaun-nx** [comment]
> My interpretation of the term "disallowedPorts" is that these ports are blocked from ever having a listener, it is global, and we will have business logic and messages enforcing that.

Yes that's the idea. You configure a list of ports that are not allowed to be used in the `listen` directive.
So if you wanted ports 80 and 443 to be blocked, deploying a VirtualServer and/or an Ingress resource with their default settings should be blocked as, by default, they would setup listeners with 80 and 443 (with tls enabled)

**Comment by brianehlert** [comment]
To copy something forward, the violation event could look like this:
`Events:
  Type     Reason    Age   From                      Message
  ----     ------    ----  ----                      -------
  Warning  Rejected  38s   nginx-ingress-controller  [[]: Forbidden: port 80 is blocked, []: Forbidden: port 443 is blocked]`

**Comment by shaun-nx** [comment]
Closing this issue and opening two new issues.
These two issues together will address each of the use cases listed above

1. https://github.com/nginxinc/kubernetes-ingress/issues/4444
2. https://github.com/nginxinc/kubernetes-ingress/issues/4443
