### ISSUE TITLE
Route 53 compability in daemonset mode

### ISSUE THREAD

**Issue by dmitriy-myz** [nginxinc/kubernetes-ingress#442]
**Describe situation**
I have a bare metal cluster, running nginx-ingress as daemonset. Also have route 53 with health checks.
Want to update daemonset or maintain node.
Currently if I just stop pod with nginx-ingress daemon, it just immediately kill it and run new one. All requests, that send to it will be lost it that period.
I want to pod serve requests, but fail route 53 checks, so it can exclude it from DNS responses.

**Describe the solution you'd like**
Allow to add custom locations to default server directive
Then this can be done by adding this to default server directive.
```
location /aws-health {
    if ( -e /tmp/maintenance ) {
        return 404;
    }
    return 200;
}
```

and lifecycle rule like this

```
    lifecycle:
      preStop:
        exec:
          command: ["bash", "-c", "touch /tmp/maintenance && sleep 120"]
  terminationGracePeriodSeconds: 125
```

**Describe alternatives you've considered**

Current workaround:
create an ingress rule on some namespace with some service (e.g. `nginx-ingress`)

```
apiVersion: v1
kind: Service
metadata:
  name: dummy-service
  namespace: nginx-ingress
  labels:
    app: dummy-service
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: dummy-service
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aws-health-checks
  namespace: nginx-ingress
  annotations:
    nginx.org/server-snippets: |
      location /aws-health {
          if ( -e /tmp/maintenance ) {
              return 404;
          }
          return 200;
      }
spec:
  rules:
  - host: aws.checks
    http:
      paths:
      - path: /
        backend:
          serviceName: dummy-service
          servicePort: 80
```

**Comment by pleshakov** [comment]
@dmitriy-myz 
thanks for describing the use case and the workaround.

Note that we already have a health check location in the default server https://github.com/nginxinc/kubernetes-ingress/blob/master/internal/nginx/templates/nginx.tmpl#L73 which can be enabled via `-health-status` flag.  (See https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/cli-arguments.md).  Perhaps it makes sense to reuse it.

Right now when the Ingress Controller receives a SIGTERM , it quits NGINX by running `nginx -s stop`. What if we had an additional command-line argument, let's say `-delay-before-quitting`, which would introduce a delay between receiving the SIGTERM and quitting NGINX and at the same time making the health-check location return 404.  Do you think it would solve your problem?

In this case you would not have to specify any lifecycle hook, just use a command-line argument and increase `terminationGracePeriodSeconds`.

Alternatively, as you suggested, we can introduce something like the `default-server-snippets` configmap key, which will insert snippets into the default server `server` context. However, this would require you to specify a lifecycle hook. 

Please let me know.

**Comment by dmitriy-myz** [comment]
I think first solution can completely solve compatibility with route53/other external balancer/checkers.
But I'm not sure if this should be part of  nginx-ingress controller. 

In this case adding `default-server-snippets` look like more flexible solution. And integration with route53/etc can be written as example.

**Comment by pleshakov** [comment]
@dmitriy-myz thanks for the feedback

what do you think about the following approach instead of the `default-server-snippets`, which is a slightly modified version of your workaround?

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  http-snippets: |
    server {
      listen 80;
      server_name aws.checks;

      location /aws-health {
        if ( -e /tmp/maintenance ) {
          return 404;
        }
        return 200;
      }
    }
```
will it work for you?

**Comment by dmitriy-myz** [comment]
Yes, this work. I think this issue can be closed.
Thank you!
