### ISSUE TITLE
nodeSelector, nodeAffinity and tolerations support in helm chart

### ISSUE THREAD

**Issue by tobysmith** [nginxinc/kubernetes-ingress#444]
I'm currently installing through the helm chart and need to add the nodeSelector and tolerations fields to the deployment resource. In the cluster I'm deploying to we use taints on node pools to distinguish between separate teams so it is necessary to add a toleration to the deployment. I also wish to constrain the deployment to it's own node pool so I want to use a nodeSelector/nodeAffinity.

Would it be possible to upgrade the deployment helm chart to support these fields?

**Comment by Dean-Coakley** [comment]
Hi @tobysmith 

Thanks for the suggestion.

We will add nodeSelector, affinity and tolerations fields to the helm chart and I'll update you here once it is implemented.

**Comment by Dean-Coakley** [comment]
nodeSelector, tolerations and tolerations are now available in deployments on the latest version of the helm chart. https://github.com/nginxinc/kubernetes-ingress/pull/456
