### ISSUE TITLE
latest version 1.4.0 cannot be installed

### ISSUE THREAD

**Issue by liakouras** [nginxinc/kubernetes-ingress#445]
Hello,
trying to install nginx/nginx-ingress:1.4.0, but the pod crashes. When checking the logs, I get this:

```
I1109 18:15:10.993042       1 main.go:118] Starting NGINX Ingress controller Version=1.4.0 GitCommit=37455199
F1109 18:15:10.996421       1 main.go:189] A TLS cert and key for the default server is not found

```
when I change to image "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0", it works properly. 

what I am missing here?

**Comment by Dean-Coakley** [comment]
Hi @liakouras 

You must add a TLS cert and key to the default server. See [Installation instructions](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/installation.md#installing-the-ingress-controller) for more details on how to do that, and next steps.

When you change the image to `quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0` you are pulling an image of [kubernetes/ingress-nginx](https://github.com/kubernetes/ingress-nginx) which is a different implementation of an ingress controller. More information about the differences between the two ingress controllers can be found [here](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/nginx-ingress-controllers.md#differences-between-nginxinckubernetes-ingress-and-kubernetesingress-nginx-ingress-controllers)
