### ISSUE TITLE
Test configurations before apply

### ISSUE THREAD

**Issue by danielnginx** [nginxinc/kubernetes-ingress#4451]
### Discussed in https://github.com/nginxinc/kubernetes-ingress/discussions/4406

<div type='discussions-op-text'>

<sup>Originally posted by **brianehlert** September 21, 2023</sup>
As an additional measure of safety this implementation should validate new nginx configurations before applying them.

The theory is that a temporary nginx.conf should be written and validated similar to `nginx -t -c <filename>.conf`
The intention of doing this is to intercept any errors that customers may introduce through the use of snippets or custom templates or other ways to extend NGINX configuration.

When customers apply configurations using a CRD we are able to provide input validation and safety through the API itself.  When a customer takes advantage of the ways that we allow the capabilities to be extended beyond the limitations of the CRDs or Ingress object they can put themselves in a situation where a missing ';' at the end of a line can result in a non-operational nginx configuration and thus cause a momentary outage while they revert the changes.

Acceptance Criteria:

- write the new configuration to an isolated temporary path
- use nginx to validate the configuration
- if the new configuration passes, "promote" the configuration to the running configuration
- if the new configuration fails, do nothing and report the errors back as error events against the configuration

This can potentially leave the customer in a state where configurations are not being applied and thus the configuration objects need to be inspected for errors or the Ingress Controller needs to be inspected for errors.  But that is a better result than allowing the customer in inadvertently breaking their applications and causing an outage due to a missing ';'</div>

**Comment by brianehlert** [comment]
We have decided to close this issue as already addressed.
We will be producing some additional troubleshooting collateral so that everyone understands how errors and events are reported back to both Resources and emitted by the ingress controller pods in an attempt to close an understanding loop here that seems to be wound up in this issue and feedback.
