### ISSUE TITLE
External Name Support

### ISSUE THREAD

**Issue by SeanRobb** [nginxinc/kubernetes-ingress#446]
I would like to have a way to route traffic using ExternalName services and the ingress controller. The kubernetes/ingress-nginx project has solved this issue but I would like to use NGINX Plus to proxy this traffic. 

I would like to see this project match the feature set for ExternalName services on the kubernetes/ingress-nginx project.

Thank you!

**Comment by SeanRobb** [comment]
Initially we would most like to see routing services outside of the cluster but we are also interested in the cross namespace routing.  

Glad to hear that it is currently being planed.  The re-resolving feature is a nice addition for NGINX Plus.

Thank you for the quick response.

**Comment by Dean-Coakley** [comment]
Alright, that's helpful to know.

For cross namespace routing: 
You can use mergeable ingresses. So you can have a collection of 'minion-ingresses' defined across many namespaces that are merged into a single 'master-ingress' resource. Please see the example [here](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/mergeable-ingress-types#mergeable-ingress-types-support).

Thank you!
