### ISSUE TITLE
Annotations not reflected

### ISSUE THREAD

**Issue by sundipnair** [nginxinc/kubernetes-ingress#447]
**Describe the bug**
When I apply an ingress with annotations, they do not get reflected in the nginx.conf and the website.

**To Reproduce**
1. Setup as per https://docs.microsoft.com/en-us/azure/aks/ingress-tls (with the change mentioned in step 2)
2. Only change is to add the location snippet
    nginx.org/location-snippets: |
      location / {
        proxy_set_header X-Custom-String "Ingress Custom string for website";
      }

3. THis does not reflect on the conf file in the controller pod when I check using 
 kubectl exec nginx-ingress-controller-68cb886df4-cp6pd -n kube-system cat /etc/nginx/nginx.conf

**Expected behavior**
I would expect the request to be populated with the custom header. Also the conf file to reflect the change in configuration.

**Your environment**
* Version of the Ingress Controller - nginx-ingress-0.31.0
* Version of Kubernetes
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes platform (e.g. Mini-kube or GCP)
 - AKS
* Using NGINX or NGINX Plus - NGINX

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by sundipnair** [comment]
`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aks-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.org/location-snippets: |
      location / {
        proxy_set_header X-Custom-String "Ingress Custom string for website";
      }
spec:
  tls:
  - hosts:
    - aks.westeurope.cloudapp.azure.com
    secretName: tls-secret
  rules:
  - host: aks.westeurope.cloudapp.azure.com
    http:
      paths:
      - path: /
        backend:
          serviceName: application
          servicePort: 80`

**Comment by Dean-Coakley** [comment]
Hi @sundipnair 

The tutorial referenced uses [kubernetes/ingress-nginx](https://github.com/kubernetes/ingress-nginx) which is a different implementation of a nginx-based ingress controller

More information about the differences between the two ingress controllers can be found [here](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/nginx-ingress-controllers.md#differences-between-nginxinckubernetes-ingress-and-kubernetesingress-nginx-ingress-controllers)

`nginx.org/location-snippets` is not a valid annotation for the `kubernetes/ingress-nginx` ingress controller. Please take a look at https://kubernetes.github.io/ingress-nginx/ for their documentation to see how to add a location snippet, and open an issue in [their repository](https://github.com/kubernetes/ingress-nginx) if you are still experiencing any issues.

Closing this issue for now, but please feel free to let me know if you have any further questions.

**Comment by sundipnair** [comment]
Thanks.
