### ISSUE TITLE
Publish Helm chart in a repository

### ISSUE THREAD

**Issue by dottedmag** [nginxinc/kubernetes-ingress#455]
### Problem

I can't seem to find Helm chart from this Git repository to be published in any Helm repositories. That precludes installing it using one-line `helm install <chart>` syntax, and also does not allow one to specify it as a dependency in another chart.

### Proposed solution

Create a public Helm repository and publish the new version of the chart in it for every chart release.

### Alternatives considered

- I could create a private repository and publish a copy of Helm chart there.
  - Advantages: none I can think of
  - Disadvantages: I need to maintain a private repository (by watching this Git repository and publishing a new version of chart any time it changes), and anyone else who wants to use the chart also needs to maintain one.
- I could copy-paste this chart into a subchart of mine.
  - Advantages: I can customize the chart
  - Disadvantages: I need to manually synchronize two repositories.

**Comment by dottedmag** [comment]
@pleshakov Sure, for the time being I have copy-pasted stable chart into my Git repo, but I'll gladly get rid of it once there is a repository.

**Comment by ameijer-corsha** [comment]
would love to see the nginxinc helm chart published to one of the 'well known' helm repos such as the incubator @ https://github.com/helm/charts/tree/master/incubator!

**Comment by pleshakov** [comment]
@ameijer-corsha we're in the process of launching our own public repo with helm charts, which will include the chart for the Ingress Controller. should be ready in the next two weeks.

**Comment by pleshakov** [comment]
@dottedmag @ameijer-corsha the helm chart for the latest stable version is now available through our Helm repo. More info -- https://github.com/nginxinc/kubernetes-ingress/tree/v1.4.4/deployments/helm-chart#installing-via-helm-repository
