### ISSUE TITLE
Add string comparison Go template functions

### ISSUE THREAD

**Issue by ianyong** [nginxinc/kubernetes-ingress#4555]
**Is your feature request related to a problem? Please describe.**

I would like to intercept proxied responses with codes greater than or equal to 300 and return an error HTML page, but only for non-API routes. To achieve this, I would like to be able to make use of the following ingress template:
```yaml
{{range $location := $server.Locations}}
location {{$location.Path}} {
  ...
  {{- if not contains $location.Path "/api/"}}
  proxy_intercept_errors on;
  {{- end}}
  ...
}
```

However, the `contains` function is not defined in the Go template, nor are any other string comparison functions.

**Describe the solution you'd like**

I would like to add the following helper string comparison functions to the Go templates so as to enable the possibility of performing string comparisons in the templates:
* `contains` - [`strings.Contains`](https://pkg.go.dev/strings#Contains)
* `hasPrefix` - [`strings.HasPrefix`](https://pkg.go.dev/strings#HasPrefix)
* `hasSuffix` - [`strings.HasSuffix`](https://pkg.go.dev/strings#HasSuffix)
* `toLower` - [`strings.ToLower`](https://pkg.go.dev/strings#ToLower)
* `toUpper` - [`strings.ToUpper`](https://pkg.go.dev/strings#ToUpper)

The latter 2 functions are not exactly string comparison functions, but they do help in comparing strings with different casing.

**Describe alternatives you've considered**

I have considered making use of the `if` directive but I'm told that [it is evil when used in a location context](https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/).

**Additional context**

I am willing to work on the PR to implement this change. This issue is being opened so as to get approval from the core development team first.

**Comment by ianyong** [comment]
Related to #2207, although this feature request is more specific.

**Comment by vepatel** [comment]
@ianyong we think it's a good candidate for implementation if you wish to open a PR with tests. Thanks!
