### ISSUE TITLE
Add support for new annotation for canary or B/G deployments

### ISSUE THREAD

**Issue by idanlevin** [nginxinc/kubernetes-ingress#464]
**Is your feature request related to a problem? Please describe.**
A user should be able to split traffic between several backends

**Describe the solution you'd like**
We should use the same solution as Kubernetes' version implemented, using custom annotations in the Ingress rule object
`nginx.ingress.kubernetes.io/canary: "true"`

**Describe alternatives you've considered**
Either move to using Kubernetes' version or import this capability here

**Additional context**
The Kubernetes version of Nginx Ingress controller just added this - 
https://www.elvinefendi.com/2018/11/25/canary-deployment-with-ingress-nginx.html
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#canary

**Comment by pleshakov** [comment]
@idanlevin 
thanks for the suggestion. 

Canary or B/G deployments are important use cases. Unfortunately, there is no easy workaround to add this to our Ingress Controller while a proper implementation will require significant efforts.

We want to support those use cases in the future. However, I cannot provide an ETA at this point.

**Comment by idanlevin** [comment]
@pleshakov thanks for the quick response.

We used to use the Kubernetes Nginx Ingress-Controller version until a few months ago when you guys introduced the mergable ingress that we found very useful.

Now we have another very useful capability in the Kubernetes version and we are considering to switch back.

What is the strategy behind this split? I think we should either merge this project with the Kubernetes version or at least make sure new features are imported quickly.

**Comment by pleshakov** [comment]
@idanlevin 
The current approach with the Ingress Controller extensions based on annotations has a number of shortcomings and limitations. Our long-term goal is to provide better configuration for supporting many load-balancing/proxy features of NGINX based on [custom resources](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/), *including* blue-green and canary deployments, without the limitations of the annotation-based approach. Right now this is the top priority for us. Unfortunately, this cannot be done quickly.

At the same time, we will continue to support the existing annotations as well as the Ingress resource. However, we will not invest in creating any new major annotations, such as the ones for blue-green/canary releases.

To answer your question about the strategy, the main focus of our GitHub project are long-term stability, including maintaining performance and compatibility across every release both for NGINX users and NGINX Plus customers, as well as commercial support for NGINX Plus customers.

**Comment by pleshakov** [comment]
@idanlevin In Release 1.5 we added new [VirtualServer and VirtualServerRoute](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/virtualserver-and-virtualserverroute.md) resources that support advanced routing based on headers, cookies as well as traffic splitting. See the examples https://github.com/nginxinc/kubernetes-ingress/tree/master/examples-of-custom-resources
