### ISSUE TITLE
loadBalancerSourceRanges is not an option in service spec, why?

### ISSUE THREAD

**Issue by sandywang1982** [nginxinc/kubernetes-ingress#465]
When I was deploying nginx controller using helm chart 
`\kubernetes-ingress\deployments\helm-chart`
I had no option to provide loadBalancerSourceRanges, as this is not available in `deployments\helm-chart\templates\controller-service.yaml`
Is there another way to provide the cidr or could this option be added into the helm chart?

**Comment by pleshakov** [comment]
@sandywang1982 thanks, we will add this option to the Helm Chart. For now, the workaround is manually editing the controller-service.yaml file to include the `loadBalancerSourceRanges` field.

**Comment by pleshakov** [comment]
loadBalancerSourceRanges was implemented in https://github.com/nginxinc/kubernetes-ingress/pull/468
