### ISSUE TITLE
Wrong default value for main-template-path and virtualserver-template-path flag in the docs

### ISSUE THREAD

**Issue by haywoodsh** [nginxinc/kubernetes-ingress#4679]
**Describe the bug**
Wrong default value in the docs

- -main-template-path 
https://github.com/nginxinc/kubernetes-ingress/blob/main/docs/content/configuration/global-configuration/command-line-arguments.md#-main-template-path-string

- -virtualserver-template-path
https://github.com/nginxinc/kubernetes-ingress/blob/main/docs/content/configuration/global-configuration/command-line-arguments.md#-virtualserver-template-path-string

The correct paths should be "nginx.tmpl" and "nginx-plus.tmpl"  as used in the codebase

**To Reproduce**

1. Deploy x to '...' using some.yaml
2. View logs on '....'
3. See error

**Expected behavior**

**Your environment**

- Version of the Ingress Controller - release version or a specific commit
- Version of Kubernetes
- Kubernetes platform (e.g. Mini-kube or GCP)
- Using NGINX or NGINX Plus

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by opencmit2** [comment]
Hi @haywoodsh 
Please assign it to me, I will take care of it.
