### ISSUE TITLE
contrib version

### ISSUE THREAD

**Issue by danny-waite** [nginxinc/kubernetes-ingress#47]
Guys, I'm a bit confused as to how this project relates to the one on kubernetes contrib https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx

Can anybody shed any light? I see your images are hosted on Docker Hub whereas the contrib ones are on the GCR.

Couldn't find anything relating to this in the docs, but I may have missed it.

**Comment by aledbf** [comment]
@danny-waite the Ingress controllers in the repositories `nginxinc/kubernetes-ingress` and `kubernetes/contrib` are different projects.
The controller in `kubernetes/contrib` is maintained by the community and is not related in any way with NGINX, Inc.

**Comment by danny-waite** [comment]
thanks for the clarification on this @aledbf
