### ISSUE TITLE
Installation Failure when Setting Label with Quoted Boolean Value in NGINX Ingress Controller Helm Chart

### ISSUE THREAD

**Issue by ahmadhusaini** [nginxinc/kubernetes-ingress#4729]
**Describe the bug**
When attempting to install the NGINX Ingress Controller using the Helm chart and specifying a label with a value of true, the installation fails. This issue persists even when adding quotes around the value. For example:

--set controller.pod.extraLabels."azure\.workload\.identity/use"="true"

**To Reproduce**
Deploy NGINX Ingress Controller using Helm chart with the specified label with a value of true: --set controller.pod.extraLabels."azure\.workload\.identity/use"="true"

**Expected behavior**
The NGINX Ingress Controller should be successfully deployed with the specified label and value.

**Your environment**
- Version of Helm Chart: 1.0.2
- Version of the Ingress Controller: 3.3.2
- Version of Kubernetes: 1.26.6
- Kubernetes platform: AKS (or Any)
- Using NGINX

**Comment by oseoin** [comment]
Hi @ahmadhusaini, this is due to how helm parses CLI arguments. This can be resolved either by using the values file or by using `--set-string` instead of `--set`, for example:
```shell
--set-string controller.pod.extraLabels.azure\\.workload\\.identity\\/use=true
```

**Comment by ahmadhusaini** [comment]
Thank you @oseoin. I confirm that it works using `--set-string`. Happy to close the ticket.
