### ISSUE TITLE
Split automated tests with more markers for better concurrency in CI jobs

### ISSUE THREAD

**Issue by vepatel** [nginxinc/kubernetes-ingress#4736]
- Create new markers for python tests (includes figuring out the basis on which they'll be created)
- Use the newly created markers to setup the test matrix in CI for test job

```[tasklist]
### Tasks
- [ ] https://github.com/nginxinc/kubernetes-ingress/pull/4784
```

**Comment by pdabelf5** [comment]
https://github.com/nginxinc/kubernetes-ingress/pull/4784
