### ISSUE TITLE
Token based Authentication in incoming request header ?

### ISSUE THREAD

**Issue by rkrgarlapati** [nginxinc/kubernetes-ingress#475]
Is there any annotation or service exists with in 'NGINX Ingress Controller' which can authenticate incoming requests/token before routing them to a destination micro-service. Each incoming request is authenticated before routing to its destination. I know there is **nginx.ingress.kubernetes.io/auth-type: [basic|digest]**, but i want similar kind of thing for Token based Authentication.
If a token is not passed in the request or if it fails to authenticate, 'NGINX Ingress Controller' should throw back UnAuthenticated exception.

**Comment by pleshakov** [comment]
there is support for JWT. See https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/jwt However, it is only available in NGINX Plus (paid version)

Please note that the `nginx.ingress.kubernetes.io/auth-type: [basic|digest]` annotation is only available in https://github.com/kubernetes/ingress-nginx Ingress Controller
