### ISSUE TITLE
Dashboard variable server is unused

### ISSUE THREAD

**Issue by hafe** [nginxinc/kubernetes-ingress#4761]
**Describe the bug**
The "server" variable is defined but not used in any panel.

**To Reproduce**

1. Deploy x to '...' using some.yaml
2. View logs on '....'
3. See error

**Expected behavior**

**Your environment**

- Version of the Ingress Controller - release version or a specific commit
- Version of Kubernetes
- Kubernetes platform (e.g. Mini-kube or GCP)
- Using NGINX or NGINX Plus

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by vepatel** [comment]
@hafe Is this related to grafana dashboard and has your earlier PR fixed this issue?

**Comment by hafe** [comment]
Akaik it was also unused before. I created this issue to clean it up

**Comment by hafe** [comment]
No it's just cleaning up

**Comment by hafe** [comment]
But I would like to improve the dashboard in other ways. For example add resource usage. Do I need a ticket for such contribution?

**Comment by shaun-nx** [comment]
Hi @hafe 
If you have a few changes you'd like to make, I would open an issue where you can describe those changes! 
If the team thinks those changes seem good we can then go forward with a new PR with those changes :)
