### ISSUE TITLE
Intermittent GitHub Actions failures due to buildkit mount failures

### ISSUE THREAD

**Issue by oseoin** [nginxinc/kubernetes-ingress#4802]
**Describe the bug**

Seeing intermittent failures in the actions pipelines due to failed mounts
```shell
ERROR: failed to solve: lstat /tmp/buildkit-mount983082568/dist: no such file or directory
Error: buildx failed with: ERROR: failed to solve: lstat /tmp/buildkit-mount983082568/dist: no 
```

**To Reproduce**

1. Intermittently occurs during the test or docker build stages of the pipeline

**Expected behavior**
Pipeline behaviour should be consistent

**Your environment**

- Version of the Ingress Controller - `main`
- Version of Kubernetes - N/A
- Kubernetes platform (e.g. Mini-kube or GCP) - GitHub actions
- Using NGINX or NGINX Plus - Both

**Additional context**
Possibly related:
- https://github.com/docker/build-push-action/issues/761
- https://github.com/docker/build-push-action/issues/517

**Comment by aravazzibb** [comment]
up

**Comment by serhiikartashov** [comment]
up
