### ISSUE TITLE
Update AppProtect docker images with bot signature builds

### ISSUE THREAD

**Issue by shaun-nx** [nginxinc/kubernetes-ingress#4864]
Hi, this is for rpm based OSes
   `rpm -qa | grep app-protect-bot`
and this is for deb:
   `apt list --installed | grep app-protect-bot`

for geo-ip, they might change the name that we use next week (as it is not released yet). but it should be "app-protect-geoip"

**Comment by brianehlert** [comment]
I assume this is tied to regular image updates?
