### ISSUE TITLE
nginx-ingress controller Address field empty

### ISSUE THREAD

**Issue by Ram-kuruva-nokia** [nginxinc/kubernetes-ingress#488]

**Comment by Ram-kuruva-nokia** [comment]
Hello All,

I have a kubernetes setup with RBAC,Hence i have followed below two files to create and setup the nginx-controller.set up and everything done.but when i create a service its showing with ADDRESS column empty.
files:
nginx-deply.yaml : https://github.com/kubernetes/ingress-nginx/blob/master/deploy/with-rbac.yaml
nginx-rbac.yaml:               https://github.com/kubernetes/ingress-nginx/blob/master/deploy/rbac.yaml

kubectl create -f nginx-rbac.yaml
kubectl create -f nginx-deploy.yaml

    Got created successfully,and checked nginx version using below.
POD_NAMESPACE=ingress-nginx
POD_NAME=$(kubectl get pods -n $POD_NAMESPACE -l app.kubernetes.io/name=ingress-nginx -o jsonpath='{.items[0].metadata.name}')
kubectl exec -it $POD_NAME -n $POD_NAMESPACE -- /nginx-ingress-controller --version

Then now i tried to deploy a service on this.

ram@instance-1:~$ cat ing1.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  backend:
    serviceName: testsvc
    servicePort: 80

kubectl create -f ing1.yaml -n ingress-nginx

   Then checked as below,observed address port was empty...may i know any reason..and i am new to this and learning.
ram@instance-1:~$ kubectl get ingresses.extensions -n ingress-nginx test-ingress
NAME           HOSTS   ADDRESS   PORTS   AGE
test-ingress   *                                  80      40m

**Comment by pleshakov** [comment]
@Ram-kuruva-nokia looks like you using NGINX Ingress Controller from https://github.com/kubernetes/ingress-nginx, which is a different project. Please submit an issue in that repo.
