### ISSUE TITLE
Missing ingress.class annotation ?

### ISSUE THREAD

**Issue by renaudguerin** [nginxinc/kubernetes-ingress#49]
Hi,

I've tried running the examples in a Kubernetes cluster on GKE, and it looks the nginx controller isn't claiming the ingress object, instead the built-in GCE Ingress is. 

The problem might be that there's no "kubernetes.io/ingress.class" annotation provided in the examples ? What's the correct value to use for this controller ?

**Comment by pleshakov** [comment]
Hi, currently the NGINX controller claims all Ingress resources, regardless of the value of the *kubernetes.io/ingress.class* annotation.  It should've claimed your Ingress resources.

We will add support for the *kubernetes.io/ingress.class* annotation to be consistent with other Ingress controllers.
