### ISSUE TITLE
Question: Is nginx.org/ssl-services does SSL Passthrough ?

### ISSUE THREAD

**Issue by srikantheee84** [nginxinc/kubernetes-ingress#492]
I’m trying to implement SSL passthrough for my https service via nginx-ingress-controller. My question is it possible to terminate SSL at the pod rather Nginx controller ? I see there is annotation nginx.org/ssl-services does it support SSL passthrough ?

**Comment by pleshakov** [comment]
@srikantheee84 passthrough is not supported unfortunately

**Comment by srikantheee84** [comment]
@pleshakov then what is the use for nginx.org/ssl-service annotation ?

**Comment by pleshakov** [comment]
@srikantheee84 this annotation is used to enable HTTPS between NGINX and the backends. 

 In this case clients can use either HTTP or HTTPS to connect to the NGINX Ingress Controller, but NGINX will always establish an HTTPS connection with a backend.
```
Client --- HTTP or HTTPS --> NGINX Ingress Controller ---- HTTPS ---> Backend 
```
Note that NGINX will always terminate an HTTPS connection from the client (meaning it will decrypt the connection) and establish a new HTTPS connection with a backend.

Please also see this example https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/ssl-services

**Comment by srikantheee84** [comment]
@pleshakov Thanks for clarifying this!
