### ISSUE TITLE
CRD Upgrade Issue from v1alpha1 to v1 in Nginx Ingress Controller Helm Chart

### ISSUE THREAD

**Issue by nikolaigut** [nginxinc/kubernetes-ingress#4931]
### Describe the bug
After upgrading from the Nginx Ingress Controller Helm Chart version 1.0.0 to 1.1.0, the CRDs globalconfigurations.k8s.nginx.org and transportservers.k8s.nginx.org do not upgrade from version v1alpha1 to version v1 as expected. This issue is evident in the Kubernetes logs, which show errors indicating that the system cannot find the requested resource for transportservers.k8s.nginx.org.

### Log Error
```
W0116 08:41:22.223067       1 reflector.go:539] pkg/mod/k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: failed to list *v1.TransportServer: the server could not find the requested resource (get transportservers.k8s.nginx.org)
E0116 08:41:22.223099       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: Failed to watch *v1.TransportServer: failed to list *v1.TransportServer: the server could not find the requested resource (get transportservers.k8s.nginx.org)
```

### To Reproduce

1. Deploy the Nginx Ingress Controller using Helm Chart version 1.0.0 with a specific configuration.
2. Upgrade to Helm Chart version 1.1.0 following the standard upgrade procedure.
3. Check the versions of CRDs globalconfigurations.k8s.nginx.org and transportservers.k8s.nginx.org.
4. Observe the log errors related to transportservers.k8s.nginx.org.
5. Expected behavior
6. The CRDs globalconfigurations.k8s.nginx.org and transportservers.k8s.nginx.org should upgrade from version v1alpha1 to v1 without issues. The Kubernetes system should correctly recognize and interact with these resources post-upgrade.

The problem also occurs if the release of Helm Chart version 1.0.0 is uninstalled first.

### Your environment

Version of the Ingress Controller: nginx/nginx-ingress:3.4.0
Version of Kubernetes: v1.26.10
Kubernetes platform: Azure Kubernetes Service
Using NGINX or NGINX Plus: NGINX
Additional relevant environment details: Helm Version v3.13.1

### Additional context
Add any other context about the problem here, such as additional log files, error messages, or screenshots that might help diagnose the issue.

**Comment by oseoin** [comment]
Hi @nikolaigut, the CRDs are not upgraded automatically by Helm and need to be applied manually. Please see [this](https://docs.nginx.com/nginx-ingress-controller/installation/installing-nic/installation-with-helm/#upgrading-the-crds) document on upgrading the CRDs.

**Comment by nikolaigut** [comment]
Thank you for your prompt answer. This is correct, but should be made clear in the documentation so that there is no confusion. Perhaps you could add a note in the documentation that the CRDs are installed but not updated.

**Comment by oseoin** [comment]
@nikolaigut I will get the documentation updated as soon as possible and will leave this issue open until it is available, thank you for the feedback!

**Comment by vepatel** [comment]
@briangautreau @oseoin @nikolaigut https://docs.nginx.com/nginx-ingress-controller/installation/installing-nic/installation-with-helm/#upgrading-the-chart does says to upgrade the CRDs first, maybe we can highlight it better and Helm's explanation around the same.
cc @ADubhlaoich
