### ISSUE TITLE
QUESTION - daemonset and routing

### ISSUE THREAD

**Issue by luigikitten** [nginxinc/kubernetes-ingress#494]
Hi all, 
    newbie here :) I am trying to use the ingress with a DaemonSet to expose a couple of microservices.
Desired output is:
<nodeip>/apple -->forwarded to service apple, url=/
<nodeip>/apple/foo -->forwarded to service apple, url=/foo/
<nodeip>/banana -->forwarded to service banana, url=/

I have followed all the steps of https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/installation.md and works nicely, i.e. I can connect to a node ip and get a 404

The question is: I don't find a place where to put my "rules": could you give me some pointers?
thanks!!
Luigi

**Comment by pleshakov** [comment]
@luigikitten please take a look at the following example https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/rewrites  your requirements look very similar to the example
