### ISSUE TITLE
Indentation discrepancies in output of nginx.conf (nginx -T)

### ISSUE THREAD

**Issue by jasonwilliams14** [nginxinc/kubernetes-ingress#4951]
**Describe the bug**
As of 3.4.0, I noticed some indentation issues in the output of the `nginx -T` making the output slightly difficult to read.

Here we can see the LB algorithm is not on its own line, making it difficult to read:

```
upstream vs_default_prometheus_prometheus {
    zone vs_default_prometheus_prometheus 512k;random two least_conn;
    server 10.42.0.8:9090 max_fails=1 fail_timeout=10s max_conns=0;


}
```

`random two least_conn` should be on its own line.

Second one is slight indentation of `ssl_cert` and `ssl_key`:

```
ssl_certificate $secret_dir_path/default-prometheus-secret;
	ssl_certificate_key $secret_dir_path/default-prometheus-secret;
```

Tidying up these to lineup is ideal. (NOTE: You will run `nginx -T` to see the indentation issue.

**To Reproduce**
Install 3.4.0 NGINX Ingress
Install resources (virtualServer)

Get the output of the .conf running `nginx -T` against the NIC pod.

**Expected behavior**
Expected clean indentation in the .conf to make it easy to read and intrpret

**Your environment**

Tested on `k3d` and `aks`

**Comment by vepatel** [comment]
could be a templating issue similar to what we observed in https://github.com/nginxinc/kubernetes-ingress/issues/4824
