### ISSUE TITLE
Empty reply from server

### ISSUE THREAD

**Issue by pjain-minidukan** [nginxinc/kubernetes-ingress#498]
**Describe the bug**
Followed the nginx ingress deployment link
 https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/installation.md
When I try to run cafe.yml or my own service  I get Empty reply from server
**To Reproduce**
Output
* Rebuilt URL to: 104.211.211.54/
*   Trying 104.211.211.54...
* TCP_NODELAY set
* Connected to 104.211.211.54 (104.211.211.54) port 80 (#0)
> GET / HTTP/1.1
> Host: 104.211.211.54
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host 104.211.211.54 left intact
curl: (52) Empty reply from server
**Expected behavior**

**Your environment**
Azure AKS
* Version of the Ingress Controller - release version or a specific commit
1.4
* Version of Kubernetes
1.9
* Kubernetes platform (e.g. Mini-kube or GCP)
Azure
* Using NGINX or NGINX Plus
Nginx
**Additional context**
Any help on nginx ingress

**Comment by pleshakov** [comment]
@pjain-minidukan 
what is the command that you used to send the request?
how did you exposed the Ingress Controller pods behind  the `104.211.211.54` IP?
