### ISSUE TITLE
Is there a way to initiate an internal load balancer than an external load balancer

### ISSUE THREAD

**Issue by chsaiimannoj** [nginxinc/kubernetes-ingress#499]
Hi, Is it possible to initiate an internal load balancer than an external load balancer? in our case we use API gateway to expose the services externally then we route the requests to load balancer and from there to the backend service so we just want the load balancer to be internal.

**Comment by pleshakov** [comment]
Hi @chsaiimannoj 

Are you referring to the load balancer created by this service https://github.com/nginxinc/kubernetes-ingress/blob/master/deployments/service/loadbalancer.yaml ? If so, then yes, it is possible by adding the cloud-provider specific annotation. Please see https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
