### ISSUE TITLE
Is there a way to setup a sticky session based on cookies?

### ISSUE THREAD

**Issue by AndreiBrajnicov** [nginxinc/kubernetes-ingress#500]
Hello.

I've an fronted app which is not working if it has more than one replica. I found several examples on the internet, like:
```
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
```
But unfortunately they are not working. I even don't see any cookies. Any ideas how to solve this?

Some info about infrastructure:
EKs Cluster
k8s version 1.11.5
nginx version 1.15.8
nginx as daemonset
elb configured in TCP mode ( 4 layer )

Thanks in advance

**Comment by AndreiBrajnicov** [comment]
ok. I understood my failure, I was using annotations for another ingress module.

I read carefully documentation and added following annotation:
`     nginx.com/sticky-cookie-services: serviceName=webportal cookieName expires=1h`
Unfortunately my app is still not working.

Any ideas what I'm doing wrong?

**Comment by pleshakov** [comment]
Hi @AndreiBrajnicov 

That annotation is only supported by NGINX Plus, the commercially supported version of NGINX. Please see https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/nginx-plus.md

**Comment by boxer3379** [comment]
I started working on this stuff a couple daysago lol I really can remember
how I did it..I had been learning but to mess with that just recently a
couple days ago..never messed with stuff in my life
