### ISSUE TITLE
rules for generation of cert/key for controller

### ISSUE THREAD

**Issue by hollowimage** [nginxinc/kubernetes-ingress#51]
Is there a specific format that the controller needs in order to be able to parse it? The example key seems to work fine, but when I generate a pair using 
`openssl req -x509 -nodes -days 365 -sha256 -newkey rsa:4096 -keyout mycert.pem -out mycert.pem` 
and then feed the key and cert (with tags) through a base64 encoder, the controller can't seem to decode it.

What was the exact process that generated the cafe-secret in the example?

**Comment by pleshakov** [comment]
You can use the following commands:

 1) Generate a certificate and a key:
```
openssl req -x509 -nodes -days 365 -sha256 -newkey rsa:4096 -keyout tls.key -out tls.crt
```
2) [Create a secret](http://kubernetes.io/docs/user-guide/secrets/#creating-a-secret-using-kubectl-create-secret) from the generated files:
```
kubectl create secret generic my-tls-secret --from-file=tls.crt,tls.key
```
A secret with `tls.crt` and `tls.key` keys will be created

**Comment by hollowimage** [comment]
Thank you, that helped.
