### ISSUE TITLE
Exposing nginx along with haproxy 

### ISSUE THREAD

**Issue by srikantheee84** [nginxinc/kubernetes-ingress#512]
We need to run both haproxy and nginx plus in our openshift cluster. Since haproxy is exposed on hostPort 80 and 443. Is it possible to expose on any other ports apart from these two? If not, how to do expose via NodePort without specifying hostPort. Thanks!

**Comment by pleshakov** [comment]
@srikantheee84 
it is possible to expose NGINX pods on ports different then 80 and 443. One approach is to use port mapping, specifying the required host ports. See https://github.com/nginxinc/kubernetes-ingress/blob/master/deployments/daemon-set/nginx-ingress.yaml#L26 Can this work for you?

**Comment by srikantheee84** [comment]
Yes. That approach should work. How would ingress object know to use specified port ?

**Comment by pleshakov** [comment]
@srikantheee84 
Once port mapping is specified, the Ingress resources will start use those ports

**Comment by srikantheee84** [comment]
@pleshakov
I was using nginx.org/listen-ports-ssl annotations within ingress object and it was not working as expected. Once it is removed, it is working! Thanks
