### ISSUE TITLE
nginx.org/rewrites is not working

### ISSUE THREAD

**Issue by SameerTi** [nginxinc/kubernetes-ingress#514]
My reWrite Def looks like below

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rewrite
  annotations:
    nginx.org/rewrites: "serviceName=impact-service rewrite=/m2m"
    ingress.citm.nokia.com/sticky-route-services: "$cookie_JSESSIONID ip_cookie"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-redirect-from: "http://"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "$pass_access_scheme://"
spec:
  tls:
    - hosts:
      - devbcmt-edge-01
      secretName: impact-tls-secret
  rules:
  - host: devbcmt-edge-01
    http:
      paths:
      - path: /impact/m2m
        backend:
          serviceName: impact-service
          servicePort: 9090

-----

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: impactapi-ingress
  annotations:
     ingress.citm.nokia.com/sticky-route-services: "$cookie_JSESSIONID ip_cookie"
     nginx.ingress.kubernetes.io/ssl-redirect: "false"
     nginx.ingress.kubernetes.io/proxy-redirect-from: "http://"
     nginx.ingress.kubernetes.io/proxy-redirect-to: "$pass_access_scheme://"
spec:
  tls:
    - hosts:
      - impact-service
      secretName: impact-tls-secret
  rules:
  - host: impact-service 
    http:
      paths:
      - path: /m2m/device
        backend:
          serviceName: cigserver-service
          servicePort: 7443
      - path: /m2m
        backend:
          serviceName: impact-service
          servicePort: 9090

..
..
..

However when "/impact/m2m" is called from Rest-Client, i get 404
However when "/m2m" is called, it's SUCCESS

**Comment by Dean-Coakley** [comment]
Hi @SameerTi 

It appears that you may have https://github.com/kubernetes/ingress-nginx/ deployed. Which is different implementation of an nginx ingress controller. `nginx.org/rewrites` is only a valid annotation for the nginxinc ingress controller. 

Can you check the version of Ingress controller you have deployed?

If you validate that you are running a [kubernetes community ingress controller release](https://github.com/kubernetes/ingress-nginx/releases) please see https://kubernetes.github.io/ingress-nginx/examples/rewrite/ for the correct annotation.

**Comment by SameerTi** [comment]
Thanks for quick response

Here's what i got from my nginx pod, so based on below, could you please
tell me, if i'm using the wrong annotation or right one..!?

[root@samt-control-01 ~]# kubectl describe pods nginx-ic-95f98649b-2sk6r
Name:               nginx-ic-95f98649b-2sk6r
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               samt-edge-01/192.168.199.4
Start Time:         Fri, 15 Mar 2019 09:21:44 +0000
Labels:             app=nginx-ic
                    pod-template-hash=95f98649b
Annotations:        kubernetes.io/psp: privileged
                    prometheus.io/port: 10254
                    prometheus.io/scrape: true
Status:             Running
IP:                 192.168.1.2
Controlled By:      ReplicaSet/nginx-ic-95f98649b
Containers:
  nginx-ic:
    Container ID:
docker://7fdbaa6637112862febd917365aa235abe50df6496f0d3256a87609a7605ed0a
    *Image:
 csf-docker-releases.repo.lab.pl.alcatel-lucent.com/nginx:1.12.2-33
<http://csf-docker-releases.repo.lab.pl.alcatel-lucent.com/nginx:1.12.2-33>*
    Image ID:      docker-pullable://
csf-docker-releases.repo.lab.pl.alcatel-lucent.com/nginx@sha256:da94b880a83dc0edaf8aecceb2f74be22ac1058f69e2b8749eb7072a2f4f100b
    Ports:         80/TCP, 443/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      /nginx-ingress-controller
      --default-backend-service=$(POD_NAMESPACE)/default-http-backend1
      --configmap=$(POD_NAMESPACE)/nginx-load-balancer-conf1
      *--v=5*
..
..

**Comment by Dean-Coakley** [comment]
Here is how I'd validate what version you are running:
`$ kubectl exec -it POD_NAME bash`

```
$ ./nginx-ingress -version
Version=1.4.4 GitCommit=39aec4b9
```

If you see version `0.x.x` or cannot find this binary. You are running the other Ingress Controller. `nginx.org/rewrites` is not a valid annotatioin for this IC, you should follow the link I posted above: https://kubernetes.github.io/ingress-nginx/examples/rewrite/
Or open an issues in https://github.com/kubernetes/ingress-nginx/ to get help from them.


If you are running our Ingress controller. Please see our set of redirect annotations: https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/configmap-and-annotations.md#auth-and-ssltls

**Comment by SameerTi** [comment]
[root@samt-control-01 ~]# kubectl exec -it nginx-ic-95f98649b-2sk6r bash
bash-4.2# ./nginx-ingress-controller -version
crond: can't lock /var/run/crond.pid, otherpid may be 12: Resource
temporarily unavailable
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:    1.12.2-33
  Build:      git-8e8c38a
  Repository: ssh://gerrit.ext.net.nokia.com:29418/CSF-DOCKER
-------------------------------------------------------------------------------

**Comment by Dean-Coakley** [comment]
@SameerTi This is not the nginxinc Ingress Controller. So unfortunately I cannot assist you in it's configuration.
