### ISSUE TITLE
Trying to use LetsEncrypt seems to fail.

### ISSUE THREAD

**Issue by dealproc** [nginxinc/kubernetes-ingress#518]
When trying to use LetsEncrypt to generate TLS certificates, nginx is reporting 404's for the ./well-known/acme-challenge/.... url that is necessary for verifying the hostname with letsencrypt before the tls certificate is issued.

What my expected behavior would be is that the call to `./well-known/acme-challenge/....` would work and the tls certificate is generated and created.

I'm running the :latest tag of nginx on AKS

**Comment by pleshakov** [comment]
@dealproc could you possibly provide more details about the issue? Please refer to the issue template https://github.com/nginxinc/kubernetes-ingress/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by dealproc** [comment]
Sure.  In order for nginxinc's k8s helm chart to come up as-expected, you have two options:

* Use a shared trusted TLS certificate
* Use a "key" within your k8s cluster

Not providing **at least** one of the two options seems to make the helm script, and subsequent booting of the docker container, to fail. [The only case that I had not tried was to comment out anything to do with TLS and the helm chart's values.yml]

When you use LetsEncrypt, you will not know either of the two above items until after you configure your site(s) and LetsEncrypt, via certbot and the like, execute, resolve your http01 entries, order the certificate, and load that into the definition for your site.

In my unique case, I needed the capability of TLS termination for TCP streams to a back-end service.  Had it not been for that, I would have stayed with the kubernetes-nginx helm chart, which has worked with LetsEncrypt without cause for issue. [which, by the way, for streams, it would be a grand feature if we could somehow slip the TLS certificate into the config in a method whereas it was more of an "approved" use case, where we don't have to hack it into the script(s).  Yes.. I realize this is a dedicated feature request, but including it for completeness]

When I investigate the logs from the docker container, I am seeing where I have duplicate hostnames registered within nginxinc's helm chart.  The first is the config generated because of the site that I'm trying to implement within nginx; the second is certbot's configuration for http01 resolution before the order can be completed.  Again, using kubernetes-nginx helm chart did not seem to have this issue.

I am hosting my kubernetes cluster on AKS's latest version of their stack (1.12.6)

**Comment by pleshakov** [comment]
@dealproc thanks for providing more details 

the certificate that the IC asks to provide at the start is a special certificate - it is used for TLS termination for unknown hosts -- the hosts for which no Ingress resources were created.

> In my unique case, I needed the capability of TLS termination for TCP streams to a back-end service. 

Unfortunately, the Ingress Controller doesn't support TLS termination for TCP, only for HTTP, gRPC.

**Comment by dealproc** [comment]
With nginxinc's version of an ingress controller, I'm able to slip a custom stream snippet into the values.yml which allows this... can we at least support this scenario (somehow)?

I'm probably doing a bit of a hack to get it to work, but so far, it's working...

Here's my config:

```
      stream-snippets: |
        upstream mqtt-tcp {
            server mqtt-vernemq.default.svc.cluster.local:1883;
        }

        server {
            listen                8883 ssl;
            proxy_pass            mqtt-tcp;

            ssl_certificate       /etc/nginx/secrets/default;
            ssl_certificate_key   /etc/nginx/secrets/default;
            ssl_protocols         TLSv1.2;
            ssl_ciphers           ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:!ADH:!AECDH:!MD5;
            ssl_session_cache     shared:SSL:20m;
            ssl_session_timeout   4h;
            ssl_handshake_timeout 30s;
        }
```

**Comment by pleshakov** [comment]
@dealproc how do you configure lets encrypt integration in this case?

**Comment by dealproc** [comment]
Within your image, it was not possible, which is my gripe overall.  With the above snippet, I am treating the "default" certificate from the yml file as the one to use for TLS termination.

**Comment by pleshakov** [comment]
@dealproc if you have a pre-provisioned certificate, as an alternative to `stream-snippets`, I can suggest deploying `nginx` image from DockerHub. This way instead of using the Ingress Controller to configure NGINX, you configure it directly: you can attach your stream configuration by mounting a ConfigMap and your TSL cert/key by mounting a Secret, which you will reference in the stream configuration.
