### ISSUE TITLE
Secret not being added to ingress controller

### ISSUE THREAD

**Issue by rmtodd618** [nginxinc/kubernetes-ingress#519]
When adding JWT Auth to a Ingress it is not adding the secret to the actual ingress controller. It is configuring it properly in the config it creates but not actually putting the secret on the docker container for it to find it.
We are using NGINX+ 1.4.4 for this.
**To Reproduce**
To reproduce this issue
1. Create a generic secret with your key. (ex: kubectl create secret generic my-jwk --from-file=key.jwk )
2. Add to your annotation of an ingress nginx.com/jwt-key: my-jwk
3. Attempt to hit the ingress (ex: curl -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IlJ5YW4gVG9kZCIsImlhdCI6MTUxNjIzOTAyMn0.YayO5_mtfCOobzQ4sSKMwcA1k6Bb9FiItB__VtjpcM8" https://website.com/chirp
4. Go to the logs of your ingress controller and you will see a message saying /etc/nginx/secrets/test-my-jwk" failed (2: No such file or directory)

**Expected behavior**
When attempting to hit the end point we should receive a proper response and in the Nginx+ ingress container I would expect to see the secret assigned to the ingress in /etc/nginx/secrets/

**Your environment**
* Version of the Ingress Controller - 1.4.4
* Version of Kubernetes Server Version: version.Info{Major:"1", Minor:"11"
* Kubernetes platform AKS
* Using  NGINX Plus

**Additional context**
I am able to get it to work if I manually put the jet key in the secrets folder.

**Comment by pleshakov** [comment]
@rmtodd618 
Could you possible share your Ingress resource, the secret (excluding the .jwk field)? 
Could you also increase the verbosity of the logs to `3`, reproduce the issue again and share the logs from the Ingress Controller? Please see https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/troubleshooting.md#checking-the-ingress-controller-logs

**Comment by rmtodd618** [comment]
Here is what the ingress looks like.
{
  "kind": "Ingress",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "canary-rest-test",
    "namespace": "test",
    "selfLink": "/apis/extensions/v1beta1/namespaces/test/ingresses/canary-rest-test",
    "uid": "e1227202-4ccc-11e9-babe-8ec0d2ef5e34",
    "resourceVersion": "8541466",
    "generation": 1,
    "creationTimestamp": "2019-03-22T18:04:04Z",
    "annotations": {
      "kubernetes.io/ingress.class": "nginx",
      "kubernetes.io/tls-acme": "true",
      "nginx.com/jwt-key": "my-jwk",
      "nginx.org/mergeable-ingress-type": "minion"
    }
  },
  "spec": {
    "rules": [
      {
        "host": "nextedge.com",
        "http": {
          "paths": [
            {
              "path": "/chirp",
              "backend": {
                "serviceName": "canary-rest-test-svc",
                "servicePort": 8080
              }
            }
          ]
        }
      }
    ]
  },
  "status": {
    "loadBalancer": {}
  }
}

Here is the secret
{
  "kind": "Secret",
  "apiVersion": "v1",
  "metadata": {
    "name": "my-jwk",
    "namespace": "test",
    "selfLink": "/api/v1/namespaces/test/secrets/my-jwk",
    "uid": "eb7a2be4-4cd6-11e9-babe-8ec0d2ef5e34",
    "resourceVersion": "8549379",
    "creationTimestamp": "2019-03-22T19:15:56Z"
  },
  "data": {
    "jwt-key": "eyJrZXlzIjoKICAgIFt7CiAgICAgICAgImsiOiJibWRwYm5neE1qTSIsCiAgICAgICAgImt0eSI6Im9jdCIKICAgIH1dCn0K"
  },
  "type": "Opaque"
}

Ill get you more logs in a few.

**Comment by pleshakov** [comment]
@rmtodd618 thanks for sharing. the Ingress Controller expects that a JWK Secret includes the jwk in the `jwk` field. Could you update your secret by changing `jwt-key` to `jwt`  and see if that works?

**Comment by rmtodd618** [comment]
Same amount of logs.
10.240.0.5 - - [25/Mar/2019:18:26:15 +0000] "GET /chirp HTTP/1.1" 500 177 "-" "curl/7.58.0" "-"
2019/03/25 18:26:15 [error] 37#37: *17045 open() "/etc/nginx/secrets/test-my-jwk" failed (2: No such file or directory), client: 10.240.0.5, server: nextedge.com, request: "GET /chirp HTTP/1.1", host: "nextedge.com"

**Comment by rmtodd618** [comment]
Perfect. Thanks. It is working now
