### ISSUE TITLE
Is Metalb Supported as a LoadBalance Provider?

### ISSUE THREAD

**Issue by liuhll** [nginxinc/kubernetes-ingress#521]
When I Use [Metalb](https://metallb.universe.tf/) Supported as a LoadBalance Provider, Use `sudo kubectl get ing` to get empty addresses！

**Comment by pleshakov** [comment]
@liuhll 
did you configure the Ingress Controller set the addresses of  Ingress resources ? Please  see https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/report-ingress-status.md

**Comment by liuhll** [comment]
how to use command-line for  Ingress controller?

**Comment by liuhll** [comment]
thanks @pleshakov
