### ISSUE TITLE
Allow helm chart to support external cluster level RBAC

### ISSUE THREAD

**Issue by hafe** [nginxinc/kubernetes-ingress#5228]
**Is your feature request related to a problem? Please describe.**
The helm chart comes with a ClusterRole and a ClusterRoleBinding. The ClusterRoleBinding gives very wide access to the whole cluster for example read access to every secret in the cluster. This does not align well with function provided by the -watch-secret-namespace option.

**Describe the solution you'd like**
A simple knob to disable the cluster level RBAC resource generation from the helm chart. This gives users a way to provide more suited cluster level RBAC externally yet use the upstream helm chart.

**Describe alternatives you've considered**

**Additional context**

**Comment by danielnginx** [comment]
Hi @hafe, could you please add the documentation for this feature?

**Comment by hafe** [comment]
Sure, exactly where do you mean?

**Comment by danielnginx** [comment]
For example: Add the configuration on helm installation - [Configuration](https://github.com/nginxinc/kubernetes-ingress/blob/main/docs/content/installation/installing-nic/installation-with-helm.md#configuration) 

https://docs.nginx.com/nginx-ingress-controller/installation/installing-nic/installation-with-helm/#configuration

**Comment by vepatel** [comment]
Thanks @hafe!
