### ISSUE TITLE
Question: Canary deployment

### ISSUE THREAD

**Issue by srikantheee84** [nginxinc/kubernetes-ingress#531]
Is it possible to implement label based canary deployment using nginx plus ? Is there any best practice around this implementation ? Thanks!

**Comment by pleshakov** [comment]
@srikantheee84 
could you possibly provide an example of a label based canary deployment? 
thanks

**Comment by pleshakov** [comment]
@srikantheee84 In Release 1.5 we added new [VirtualServer and VirtualServerRoute](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/virtualserver-and-virtualserverroute.md) resources that support advanced routing based on headers, cookies as well as traffic splitting. See the examples https://github.com/nginxinc/kubernetes-ingress/tree/master/examples-of-custom-resources

**Comment by srikantheee84** [comment]
@pleshakov thanks!
