### ISSUE TITLE
Fix weight changes dynamic reload invalid status

### ISSUE THREAD

**Issue by j1m-ryan** [nginxinc/kubernetes-ingress#5319]
When using weight change dynamic reloads:

- [ ] A VS or VSR updated with incorrect weights is marked invalid (currently this is warning for VSR when using weight change dynamic reloads)
- [ ] A VS or VSR with incorrect weights, (and, i.e in an invalid state), should not be able to take traffic

**Comment by brianehlert** [comment]
Wasn't there a PR to address this?

**Comment by j1m-ryan** [comment]
No, not yet
