### ISSUE TITLE
unable to install in an air-gapped environment

### ISSUE THREAD

**Issue by angeloxx** [nginxinc/kubernetes-ingress#5374]
**Describe the bug**
Installing or templating with helm, using current helm cart nginxinc/charts/nginx-ingress is not possible in an air-gapped environment due the reference, in values.schema.json, to external resources like https://raw.githubusercontent.com/nginxinc/kubernetes-json-schema/master/v1.29.0/_definitions.json event if the configuration is correct.

**To Reproduce**
Deploy the application in an air-gapped environment and launch

```
helm --version=1.2.0 template --create-namespace -f=/tmp/nginx-1.yaml ingress-tier-1 oci://ghcr.io/nginxinc/charts/nginx-ingress
```
and error is
```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
nginx-ingress:
Get "https://raw.githubusercontent.com/nginxinc/kubernetes-json-schema/master/v1.29.0/_definitions.json": dial tcp 185.199.108.133:443: i/o timeout
```

**Expected behavior**
Install the controller as expected, the configuration is correct because on a connected environment, with same values, the application is installed without issues.

**Your environment**

- Version of the Ingress Controller Helm Chart - 1.2
- Version of Kubernetes 1.29

**Comment by angeloxx** [comment]
Value file is:

```python
controller:
  ingressClass:
    name: nginx-tier-1
  tolerations:
    - key: "node-role.kubernetes.io/network-node"
      operator: "Exists"
      effect: "NoSchedule"
  affinity:
    selector.ingress: tier-1
  pod:
    annotations:
      selector: tier-1
service:
  create: false
```

**Comment by brianehlert** [comment]
The project has included this schema file in the Operator to accommodate OpenShift customers in this scenario.
I believe that the schema was first separated due to concerns about its size and thus the resulting size of the chart.
If the schema was incorporated, I would love to see some effort to reduce the size of the schema itself and if that is possible.

**Comment by vepatel** [comment]
@angeloxx as a temporary measure, is it possible for you to remove the values.schema.json file (only if you're building from source after checking out v3.5.0 tag).

@brianehlert the only way I see for now is to either:

- do same as operator i.e. move the schema to this repo or
- remove the schema validation

**Comment by vepatel** [comment]
Also finally there seems to be some traction on https://github.com/helm/helm/issues/10398 with https://github.com/helm/helm/pull/12743

**Comment by angeloxx** [comment]
> @angeloxx as a temporary measure, is it possible for you to remove the values.schema.json file (only possible if you're building from source).

Yes, already applied the W/A downloading the chart and removing the file before the deploy but isn't a viable long-term solution. We still have the same issues with other charts via a wrong values.schema.json and for that reason we still waiting for the --skip-schema-validation flag in Helm (and its adoption in helmfile).

**Comment by vepatel** [comment]
@angeloxx yes the `--skip-schema-validation` is pretty much a requirement at this point, i guess as part of this issue we'll try to see if there's a short term solution or not, will keep you posted 👍🏼

**Comment by vepatel** [comment]
https://github.com/nginxinc/kubernetes-ingress/pull/5528 reverting above PR because of issue with helm relative path
