### ISSUE TITLE
Write report marker

### ISSUE THREAD

**Issue by brianehlert** [nginxinc/kubernetes-ingress#5385]
### Overview 
Write a simple txt file that contains `name:value` pairs of the following:
- Integration - (string) (N1) this identifies the instance as part of a NIC or NGF (or other) integration.
- ClusterID - (string) (per cluster) cluster relationship for the deployment.
- ClusterNodeCount - (int) (per cluster & per node) the number of nodes in the cluster.
- InstallationID - (string) (per instance) this identifies the individual NIC/NGF deployment relationship.

Output location: `/etc/nginx/reporting/tracking.info`

### Acceptance Criteria
- Output file is a simple text file
- Must work with `readOnlyRootFilesystem: true`
- Should be written near startup.
- File is updated periodically updated. (once per 24 hours, for example)
- Entry referencing file is defined in NGINX mgmt block

### Data Format
File format is simple JSON-based format with these values supported:
```json
{
    "Integration": "nic",
    "ClusterID": "6B29FC40-CA47-1067-B31D-00DD010662DA",
    "ClusterNodeCount": 5,
    "InstallationID": "6B29FC40-CA47-1067-B31D-00DD010662DB"
}
```

```[tasklist]
### Tasks
- [x] Confirm Data to be sent is correct
- [x] Get data format from NGINX team
```

**Comment by vepatel** [comment]
```
Integration:nic
ClusterID:6B29FC40-CA47-1067-B31D-SOMETHING
ClusterNodeCount:5
InstallationID:6B29FC40-CA47-1067-B31D-SOMETHING-ELSE
```
@brianehlert can you clarify if its going to be a ':' or '-' between the values?
