### ISSUE TITLE
Helm chart: `controller.reportIngressStatus.leaderElectionLockName` is not auto-generated

### ISSUE THREAD

**Issue by kyrofa** [nginxinc/kubernetes-ingress#5389]
The [helm chart README](https://github.com/nginxinc/kubernetes-ingress/blob/main/charts/nginx-ingress/README.md) contains the following line:

> |`controller.reportIngressStatus.leaderElectionLockName` | Specifies the name of the ConfigMap, within the same namespace as the controller, used as the lock for leader election. controller.reportIngressStatus.enableLeaderElection must be set to true. | Autogenerated |

And indeed, this _needs_ to be auto-generated in order to support multiple ingress controllers in the same namespace. However, it's actually [hard-coded in the values.yaml](https://github.com/nginxinc/kubernetes-ingress/blob/f88286b820830c88abe71077a2e665cdb89cd886/charts/nginx-ingress/values.yaml#L445) to `nginx-ingress-leader`, which means by default you cannot install multiple ingress controllers in the same namespace.

It does look like the [nginx-ingress.leaderElectionName](https://github.com/nginxinc/kubernetes-ingress/blob/f88286b820830c88abe71077a2e665cdb89cd886/charts/nginx-ingress/templates/_helpers.tpl#L122) definition does actually support auto-generating it, but the fact that the value is hard-coded means it's not done by default.

I propose updating the the default `leaderElectionLockName` value to be an empty string so that the README is telling the truth.
```[tasklist]
### Tasks
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/5388
```

**Comment by brianehlert** [comment]
Leader election lock name was invalidated when this project moved to using the leases API.
This bit of code causes two leader election methods to be active at the same time and thus causes inappropriate load on the K8s API.

**Comment by kyrofa** [comment]
I'm not completely following. Are you saying we can actually remove this configmap altogether? Because the way it stands today, if you try to install two ingress controllers alongside each other, you get something along the lines of:

> Error: rendered manifests contain a resource that already exists. Unable to continue with install: ConfigMap "nginx-ingress-leader" in namespace "nginx-ingress" exists and cannot be imported into the current release

**Comment by vepatel** [comment]
Hi @kyrofa, thanks for opening the issue. autogenerating name makes sense!

We're keeping the both objects i.e. old `configmap` and new `lease` type to provide some overlap after it was introduced in 3.4.0. see https://github.com/nginxinc/kubernetes-ingress/blob/v3.5.0/charts/nginx-ingress/templates/controller-leader-election-configmap.yaml

We will be talking about this issue in our next community call, please feel free to join on 6th May 3pm GMT

**Comment by danielnginx** [comment]
We should implement https://github.com/nginxinc/kubernetes-ingress/issues/5388 before fixing this issue.

**Comment by ksemele** [comment]
+1 do you plan to resolve this task in nearest future?

**Comment by shaun-nx** [comment]
Closing this issue
Fix addressed in https://github.com/nginxinc/kubernetes-ingress/pull/6372
