### ISSUE TITLE
Ability to utilize controller.service.httpPort.enable in helm chart

### ISSUE THREAD

**Issue by jrmercier1** [nginxinc/kubernetes-ingress#543]
**Is your feature request related to a problem? Please describe.**
Feature Request

This feature would enable the use of the **controller.service.httpPort.enable** option to give the chart deployer the ability to enable or disable the non SSL port.  The override available options lists it but it does not appear to be functional.

**Describe the solution you'd like**
I would like the appropriate chart templates to recognize and deploy accordingly in response to the **controller.service.httpPort.enable** override value.

Mainly the following templates
controller-daemonset.yaml
controller-deployment.yaml
controller-service.yaml

**Comment by pleshakov** [comment]
@jrmercier1 
**controller.service.httpPort.enable** only enables/disables the HTTP port in the service, but not in the Ingress Controller container and the NGINX configuration. 

Am I correct assuming that you would like to disable the HTTP port everywhere -- the service, the container, the NGINX configuration? If not, could you possibly provide more details about your use case?

**Comment by jrmercier1** [comment]
That would be correct. Disable it throughout.

**Comment by pleshakov** [comment]
@jrmercier1 ok. Thanks. 

This is a useful feature. We need to think about the configuration and implementation carefully, and it might take some time to implement it. I'll update this issue once we have more details about the feature.

In the meantime, as a workaround, I can suggest using [custom templates](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/custom-templates). To disable HTTP, you can remove [this line](https://github.com/nginxinc/kubernetes-ingress/blob/master/internal/configs/version1/nginx.tmpl#L68) from the main template and [these lines](https://github.com/nginxinc/kubernetes-ingress/blob/master/internal/configs/version1/nginx-plus.ingress.tmpl#L24-L26) from the Ingress template. Can this work for you?

**Comment by jrmercier1** [comment]
Sure this will work for the time being
