### ISSUE TITLE
Custom Trasnportserver Template

### ISSUE THREAD

**Issue by ssrahul96** [nginxinc/kubernetes-ingress#5459]
**Is your feature request related to a problem? Please describe.**
We have [custom-templates](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/custom-templates/) for `Ingress` , `VirtualServer`. The `TransportServer` is missed out

**Describe the solution you'd like**
Create a `custom-templates`  for `TransportServer` as well

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by j1m-ryan** [comment]
Hi @ssrahul96, we will discuss this on Tuesday next week in our community call which you are welcome to join. The meeting info is in the README.
