### ISSUE TITLE
499 reflect on service

### ISSUE THREAD

**Issue by trevezani** [nginxinc/kubernetes-ingress#5466]
I tries capture the close connection in the service associate with the ingress-nginx but I cant find a way. When this situation occur the log of nginx shows the correct status code on log:

172.21.0.224 - user [29/Apr/2024:13:21:41 +0000] "POST /execute HTTP/1.1" 499 0 "-" "Apache-HttpClient/4.5.12 (Java/1.8.0_382)" 409 2.702 [service-8080] [] 172.21.72.106:8080 0 2.702 - da6c85d6276498086c97ccb1380ed096

But in the service the process continue. I think the correct behavior is the nginx close the connection with the service to interrupt the process.

In the documentation I only found the flag **proxy_ignore_client_abort** .

Have a way to change this behavior?

**Comment by j1m-ryan** [comment]
Hello @trevezani,

To better assist you with this, could you please provide a bit more detailed information? Specifically, we need:

- NIC Version.
- k8s version.
- relevant manifests and helm chart values / flags

Additionally, I noticed that you mentioned using "ingress-nginx". To clarify, are you using the [community-managed Ingress controller](https://github.com/kubernetes/ingress-nginx), or are you using this project, the [NGINX Inc. managed Ingress controller](https://github.com/nginxinc/kubernetes-ingress)?

**Comment by trevezani** [comment]
I'm using the [community-managed Ingress controller](https://github.com/kubernetes/ingress-nginx) following the instructions to install on [aws](https://kubernetes.github.io/ingress-nginx/deploy/#aws) changing only VPC CIDR and ACM. I installed the version 1.10.0 on k8s version 1.29.

**Comment by j1m-ryan** [comment]
These are separate projects with different codebases, you can make an issue for this on https://github.com/kubernetes/ingress-nginx
