### ISSUE TITLE
Not possible to install multiple times in different namespaces

### ISSUE THREAD

**Issue by kytart** [nginxinc/kubernetes-ingress#549]
### Issue

I'm setting up `production` and `staging` namespaces in my kubernetes cluster and I'd like to have a completely separate setup for each one. Each environment will contain it's own nginx ingress (i.e. this repo) with different configuration for each environment. 

The problem is, right now it's not possible to install this using Helm. If I use the default values, it attempts to create rbac resources. That means a service account `nginx-ingress` in that namespace and cluster role named `nginx-ingress` and cluster role binding named `nginx-ingress` for that service account.

Cluster roles and cluster role bindings are global, not namespaced and because they're names are hardcoded in the Helm templates, when I install it to the second namespace, it throws an error, because it's trying to create the cluster role and cluster role bindings that already exist.

### Solution

It looks pretty easy to solve this. It's enough to make cluster role and cluster role binding names configurable from values, like:

```
# values.yaml
controller:
  clusterRole:
    name: nginx-ingress
  clusterRoleBinding:
    name: nginx-ingress
```

**Comment by Dean-Coakley** [comment]
Hi @kytart 

Currently trying to resolve this in https://github.com/nginxinc/kubernetes-ingress/pull/546
