### ISSUE TITLE
Allow adding pod spec annotations to nginx plus daemonset/deployment chart template

### ISSUE THREAD

**Issue by jrmercier1** [nginxinc/kubernetes-ingress#551]
**Is your feature request related to a problem? Please describe.**
Feature

**Describe the solution you'd like**
I would like the ability to include custom(extra) pod spec annotations when deploying plus ingress via the helm chart deployment/daemonset.

Since plus tends to have different calls/api paths/port to pull stats than regular nginx ingress we have a couple monitoring solutions that require annotation overrides.  In this case annotations in the .spec.templates.metadata or pod spec.  Pod spec may make more sense due to also the fact prometheus-exporter may need different annotations.

**Describe alternatives you've considered**
Currently I edit the chart before deployment which long term defeats the purpose of relying on the published chart.

**Comment by Rulox** [comment]
Hi @jrmercier,

Now you can add custom annotations in the IC pods using the Helm Chart. This feature is available in the `edge` version of the IC. Check [Releases](https://github.com/nginxinc/kubernetes-ingress#nginx-ingress-controller-releases) for more info regarding versioning.
