### ISSUE TITLE
Investigate removal of external NGINX dependencies

### ISSUE THREAD

**Issue by oseoin** [nginxinc/kubernetes-ingress#5529]
Currently the `ubi`, `opentracing-lib`, and `alpine-opentracing-lib` Docker targets rely on external builds which blocked the use of NGINX 1.25.5 for the 3.5.1 release. This task is to investigate the possibility of replacing those dependencies with alternatives which this project can directly rely on. This will involve creating a ppc64le build of NGINX OSS for ubi and building the opentracing module for the version of NGINX that we are delivering.

```[tasklist]
### Tasks
- [ ] OpenTracing
```

**Comment by danielnginx** [comment]
References: https://github.com/lucacome/nginx-ubi/blob/main/Dockerfile
