### ISSUE TITLE
Method Based Routing in Nginx Ingress

### ISSUE THREAD

**Issue by abhijitvikash** [nginxinc/kubernetes-ingress#5552]
Hi Nginx, I want to implement method based routing(GET PUT OPTIONS) in Nginx Ingress. But seems like this is not supported either using :
**nginx.ingress.kubernetes.io/configuration-snippet
nginx.ingress.kubernetes.io/server-snippet:**

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testing-ingress-01
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      set $target_backend "httpd-service.default.svc.cluster.local";
      if ($request_method = 'PUT') {
        set $target_backend "httpd-service.default.svc.cluster.local"; # Change this to your PUT service if needed
      }
      if ($request_method = 'GET') {
        set $target_backend "httpd-service.default.svc.cluster.local"; # Change this to your GET service if needed
      }
      proxy_pass http://$target_backend;
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: httpd-service
            port:
              number: 80

**Comment by brianehlert** [comment]
Method based routing.
As in, a GET is sent to one service, a PUT to a different service, a POST to yet a different service, and so on.
Did I get that correct?

I am asking because the project offers Method filtering / blocking which might also meet the need.
https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#match

**Comment by vepatel** [comment]
@brianehlert I think @abhijitvikash is using community project looking at the annotations here.
@abhijitvikash can you please specify which project you're using along with version?

**Comment by abhijitvikash** [comment]
This one - https://github.com/kubernetes/ingress-nginx

**Comment by abhijitvikash** [comment]
helm template my-nginx ingress-nginx/ingress-nginx --values values-ext.yaml --namespace ingress-nginx > nginx-ingress-external-manifest.yaml

**Comment by jasonwilliams14** [comment]
@abhijitvikash Hello there. 
That repo you listed is a different NGINX ingress controller project.
This repo is the official NGINX Ingress controller project maintained by NGINX.

You can see our documentation located here:

https://docs.nginx.com/nginx-ingress-controller/

If you are using the `ingress` resource, you can use snippets:

https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-snippets/

If you are using our CRD definitions, you can use snippets as well:

https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#using-snippets

Let us know if that helps.
