### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by fabio-lab15** [nginxinc/kubernetes-ingress#556]
While reading the following doc:

https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/nginx-ingress-controllers.md

In the table of Key differences section, these two links for the Configuration templates *1 row are broken:
See the templates (nginxinc/kubernetes-ingress with NGINX) -> https://github.com/nginxinc/kubernetes-ingress/tree/master/internal/configs/templates
See the templates (nginxinc/kubernetes-ingress with NGINX Plus) -> https://github.com/nginxinc/kubernetes-ingress/tree/master/internal/configs/templates

**Comment by pleshakov** [comment]
@fabio-lab15 thanks for reporting
