### ISSUE TITLE
enable TLS1.3

### ISSUE THREAD

**Issue by vadlakiran** [nginxinc/kubernetes-ingress#5643]
we have deployed as nginx-controller v1.25.5 version, how to enable the TLSv1.3
we have changed in configmap but no use it not working, still its taking TLSv1.2

**To Reproduce**

1. Deploy x to '...' using some.yaml
2. View logs on '....'
3. See error

**Expected behavior**

**Your environment**

- Version of the Ingress Controller - release version or a specific commit
- Version of Kubernetes
- Kubernetes platform (e.g. Mini-kube or GCP)
- Using NGINX or NGINX Plus

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by brianehlert** [comment]
If you are using the ingress controller from this GitHub repo TLS 1.3 is enabled by default.  As NGINX core move to defaulting to TLS 1.3 a few releases back.

However, version 1.25.5 appears to refer to a version of NGINX and not a specific version of any NGINX ingress controller project (not this one nor the one maintained by the K8s community by the same name).
However, NGINX 1.25.5 was released in April 2024 and thus should default to TLS 1.3 unless a lower level is expressly defined.

Check ssl-protocols in the ConfigMap resource if using this project.
https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#auth-and-ssltls

**Comment by brianehlert** [comment]
Clients negotiate up, not down.
So if NGINX is configured with 1.2 and 1.3 any client that supports both will generally use 1.2 and stop.
If you want only 1.3, then NGINX should only be configured with 1.3

What do you have defined in the configmap?

**Comment by jjngx** [comment]
@vadlakiran could you please provide more information:

- version of the NIC
- config maps
- logs
- deployment

**Comment by haywoodsh** [comment]
We're closing this issue for now as it has been inactive for a month. Feel free to reopen it again if you think this is an issue that needs to be resolved.
