### ISSUE TITLE
how does one do SSL passthrough with source ip preservation

### ISSUE THREAD

**Issue by sandys** [nginxinc/kubernetes-ingress#57]
hi guys,
this has been a big question on the k8s slack group.. but nobody is a big enough expert in nginx to figure out.

the requirement is very simply - i dont want to terminate my ssl at the ingress controller: I want to terminate them on the nginx pods that i have running inside. how do I do this ?

also - nginx ingress controller does not preserve source ip. we need the original client source-ip for audit purposes.

now i figured out that one must use "stream" and "proxy-protocol" to somehow configure this, but we are just not able to figure this out on the k8s slack. An example would be truly awesome!

**Comment by pleshakov** [comment]
@sandys 
It is possible with the [ngx_stream_ssl_preread_module](https://nginx.org/en/docs/stream/ngx_stream_ssl_preread_module.html), which was added recently in 1.11.5 release, combined with proxy protocol and stream module.

For example, this can be your load balancer configuration:
```nginx
...
stream {
  map $ssl_preread_server_name $name {
      backend.example.com      backend;
      default                  default-backend;
  }

  upstream backend {
      server 192.168.0.1:443;
  }

  upstream default-backend {
      server 192.168.0.2:443;
  }

  proxy_protocol on;

  server {
      listen      443;
      proxy_pass  $name;
      ssl_preread on;
  }
}
...
```

You nginx web server configuration can lool like this:
```nginx
server {
    listen 443 ssl proxy_protocol;

    ssl_certificate my.crt;
    ssl_certificate_key my.key;

    set_real_ip_from <address or CIDR  see http://nginx.org/en/docs/http/ngx_http_realip_module.html#set_real_ip_from >;
    real_ip_header proxy_protocol;
    ...
}
```
However, it's not supported by the Ingress controller. You have to configure NGINX without the Ingress controller.

**Comment by aledbf** [comment]
@pleshakov thanks for this awesome example. Is valid to use the `stream` feature to listen in port `443` and for the default case in the map send traffic to the same nginx instance in a different port (like 442) with multiple servers (all this servers provide SSL)?

**Comment by pleshakov** [comment]
@aledbf yep, that should work

**Comment by aledbf** [comment]
@pleshakov awesome. Thanks!

**Comment by aledbf** [comment]
@pleshakov 

```
stream {
    # map FQDN that requires SSL passthrough
    map $ssl_preread_server_name $stream_upstream {
        foo-898.bar.com                 default-echoheaders-x-80-0-pt;
        foo-997.bar.com                 default-echoheaders-x-80-1-pt;
        kubernetes.foo-bar.com          default-echoheaders-x-80-2-pt;
        # send SSL traffic to this nginx in a different port
        default                         nginx-ssl-backend;
    }

    log_format log_stream '$remote_addr [$time_local] $protocol [$ssl_preread_server_name] [$stream_upstream] '
        '$status $bytes_sent $bytes_received $session_time';

    access_log /var/log/nginx/access.log log_stream;
    error_log  /var/log/nginx/error.log;

    # configure default backend for SSL
    upstream nginx-ssl-backend {
        server 127.0.0.1:442;
    }

    upstream default-echoheaders-x-80-0-pt {
        server 10.2.18.8:8080;
    }
    upstream default-echoheaders-x-80-1-pt {
        server 10.2.18.8:8080;
    }
    upstream default-echoheaders-x-80-2-pt {
        server 10.2.18.8:8080;
    }

    server {
        listen                  443;
        proxy_pass              $stream_upstream;
        ssl_preread             on;
    }
}
```

using

```
curl -v -H 'Host: kubernetes.foo-bar.com' https://172.17.4.99 -k
```

I see this in the logs:
```
10.2.18.1 [26/Oct/2016:15:11:25 +0000] TCP [] [nginx-ssl-backend] 200 2100 273 0.022
```

(no `$ssl_preread_server_name`) 
How I can debug the issue?
Thanks

**Comment by pleshakov** [comment]
@aledbf might be the case that curl isn't sending the SNI information

**Comment by aledbf** [comment]
@pleshakov yes, that's the issue. It's working fine in a browser.
Thanks!

**Comment by sandys** [comment]
@pleshakov sorry to comment on an old bug, but is the ssl_preread_server_name going to be surfaced into the ingress configuration ?

**Comment by kedlav** [comment]
use curl --resolve, not curl -H 'Host:...'

**Comment by shyamkhakhar9** [comment]
@pleshakov I'm using the same thing that you had shown in your load balancer configuration above where in one of the upstream i have proxy ip and port. So the nginx and proxy runs fine with this but in the proxy log where i'm logging the ip from where the requests comes is same for all which is my server ip which i configured in upstream block and i want the actual client ip address. I'm not able to figure out how to configure that. I have also tried proxy_protocol but that also doesn't work. Can you help me with this?

**Comment by pleshakov** [comment]
@shyamkhakhar9 do I understand correctly that you want to pass client IP from NGINX to your backends?

**Comment by shyamkhakhar9** [comment]
@pleshakov yes.

**Comment by pleshakov** [comment]
@shyamkhakhar9 please take a look at this blog post https://www.nginx.com/blog/ip-transparency-direct-server-return-nginx-plus-transparent-proxy/  Hope that helps

**Comment by shyamkhakhar9** [comment]
@pleshakov I'm using this:

stream {
  map $ssl_preread_server_name $name {
      backend.example.com      backend;
      backend1.myloft.xyz         backend1;
      default                  default-backend;
  }

  upstream backend {
      server 192.168.0.1:1701;
  }

  upstream backend1 {
      server 192.168.0.2:1701;
  }

  upstream default-backend {
      server 192.168.0.1:1701;
  }

  server {
      listen      443;
      proxy_pass  $name;
      ssl_preread on;
  }
}

where on 192.168.0.1:1701 and 192.168.0.2:1701 my proxy is running.
So if I try backend1.myloft.xyz:443 then instead of using 192.168.0.2:1701 it uses 192.168.0.1:1701

Can you help me?

**Comment by pleshakov** [comment]
@shyamkhakhar9 
could you double check that your client sends the correct SNI `backend1.example.com` ? If you using curl, try the `-resolve` option. For example, `curl --resolve cafe.example.com:<IP>:443 https://cafe.example.com:443/coffee --insecure` 
If the SNI is not set correctly, NGINX will route the connection to the default backend.

Please note that this repo https://github.com/nginxinc/kubernetes-ingress is for the NGINX Ingress Controller issues, not NGINX.

To get help with NGINX, consider reaching out to our community support mailing list nginx@nginx.org See http://nginx.org/en/support.html
