### ISSUE TITLE
jwt-login-url

### ISSUE THREAD

**Issue by KRISHS68** [nginxinc/kubernetes-ingress#574]
Hi Team,

i have a service in kubernetes cluster which provides JWT , and i am trying to fetch the same from nginx controller by defining the jwt-login-url in Ingress resource , however the login service is not being hit by nginx . can you please let me know for any other cofiguration to be done.

----
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.com/jwt-key: "jwt-secret" 
    nginx.com/jwt-realm: "Cafe App"  
    nginx.com/jwt-token: "$cookie_auth_token"
    nginx.com/jwt-login-url: "http://<service name>.default.svc.cluster.local:<port>/login"
  spec:
  tls:
  - hosts:
    - cafe.example.com
    secretName: cafe-secret
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /tea
        backend:
          serviceName: tea-svc
          servicePort: 80
      - path: /coffee
        backend:
          serviceName: coffee-svc
          servicePort: 80
        

----
Thanks,
Srinidhi

**Comment by pleshakov** [comment]
Hi @KRISHS68 

`nginx.com/jwt-login-url` defines a URL where the client will be redirected if the request doesn't include a JWT or include an invalid JWT. For example, if `nginx.com/jwt-login-url: "https://login.example.com"` and the client doesn't provide a JWT, NGINX Plus will respond with a 302 redirect to `https://login.example.com` to the client.

**Comment by KRISHS68** [comment]
Hi ,

Thanks for your reply , i see my login service is returns JWT when i hit seperately , however i dont see log entry in my login service when i try to redirect for JWT from nginx ingress ,

can i know where to check in nginx container for more logs? or any specific confiuration i am missing.

Thanks,
Srinidhi

**Comment by pleshakov** [comment]
Can the client that you use follow redirects?

In nginx logs of the Ingress controller you should be able to see a 302 response to the client.

**Comment by KRISHS68** [comment]
i am using curl with below command to follow redirect , and i would get JWT in return , however if i use with out '-L' i would get 302 Found. 
i think nginx should redirect to fetch jwt , validate it and proceed further , but i am getting 302 Found.

curl -v -L --resolve cafe.example.com:443:<publicIP> https://cafe.example.com:443/tea --insecure

Thanks,
Srinidhi

**Comment by pleshakov** [comment]
This behavior is expected. Nginx Plus sends a 302 response with a redirect to the client.  Alternatively, nginx Plus can send a 401 response if the client knows  how to handle that.  

Perhaps I don’t understand your issue completely. Do you expect that the client will get redirected back to nginx Plus after it follows the redirect from nginx Plus?

**Comment by KRISHS68** [comment]
Hi , 

i understand now , Thanks for the update.
i have one more question , is it possible to skip JWT validation to specific services by defining in Ingress.

like for login end point , i dont want to validate JWT as there wouldnt be any JWT initially , so i am trying to skip JWT validation at nginx plus controller for /login context URL's.

Please let me know.

Thanks,
Srinidhi

**Comment by pleshakov** [comment]
@KRISHS68 
Please take a look at mergeable Ingress resources -- https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/mergeable-ingress-types

With mergeable Ingresses, you can split your paths across multiple minion Ingresses, so that paths that require JWT validation belong to one minion and paths that don't require belong to another minion. The former minion will include the JWT annotation, the latter minion won't include any.

**Comment by KRISHS68** [comment]
Hi ,

yes i tried the same today morning it worked as expected. Thanks for your reply.
