### ISSUE TITLE
kind: Ingress (just Ingress)

### ISSUE THREAD

**Issue by fhfournier** [nginxinc/kubernetes-ingress#5792]
Hi!

**Is your feature request related to a problem? Please describe.**
There is a big problem for me when trying to set multiple URL on that helm chart. When I try i got multiple error and i figure it out the probleme was the type was **ingressClass** and not **Ingress**. There not supose to be more than one i think

**Describe the solution you'd like**
```
ingress = {
  create = true (default false)
  # set everything else, port, url, etc..
}
```

With that i can easy add many website to my node group. For a systeme redirect or something else :)

**Comment by brianehlert** [comment]
IngressClass is singular for a deployment.  And required by K8s.
Ingress is the resource that represents a hostname.  And can be multiple.

Can you please further describe your issue?  I don't think we are following your problem.
