### ISSUE TITLE
nginxplus pod is not starting with errors (CrashloopBackOff)

### ISSUE THREAD

**Issue by beth2016** [nginxinc/kubernetes-ingress#582]
Need some help....
The nginx plus pod is showing "CrashloopBackOff " error.
I0606 14:14:13.870504       1 main.go:155] Starting NGINX Ingress controller Version=edge GitCommit=55a55642
F0606 14:14:14.022712       1 main.go:261] Error trying to get the default server TLS secret kube-system/nginx-plus-ingress-nginx-ingress-default-server-secret: could not get kube-system/nginx-plus-ingress-nginx-ingress-default-server-secret: Get https://30.65.0.1:443/api/v1/namespaces/kube-system/secrets/nginx-plus-ingress-nginx-ingress-default-server-secret: x509: cannot validate certificate for 30.65.0.1 because it doesn't contain any IP 

how do i fix this issue?  What am i missing?   Thanks.

**Comment by Rulox** [comment]
Hi @beth2016,

This doesn't look like an issue of the Ingress Controller. Seems like an issue with your self-signed certificate. The Ingress Controller is very strict about certificate validation and will not accept a certificate for an IP address unless it is properly listed in the certificate as a Subject Alternative Name (SAN).

Could you possibly add that IP in the certificate as a SAN and try again? 

Thanks

**Comment by beth2016** [comment]
User error.  thanks for your help.
