### ISSUE TITLE
failed to "StartContainer" for "nginx-ingress" with CrashLoopBackOff: "Back-off 10s restarting failed container=nginx-ingress

### ISSUE THREAD

**Issue by jainesh123** [nginxinc/kubernetes-ingress#59]
I am trying to run the https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/complete-example and these the [steps](https://github.com/nginxinc/kubernetes-ingress/blob/master/examples/complete-example/README.md) for the same.
And the on running the kubectl create -f nginx-ingress-rc.yaml

Output for kubectl logs <pod>
`F1020 09:41:15.385209       1 main.go:46] Failed to create client: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory.
`

Any pointers for the same?

**Comment by pleshakov** [comment]
To access the Kubernetes API the controller uses a [service account](http://kubernetes.io/docs/user-guide/service-accounts/). A credential (token) for that service account is placed into the filesystem tree of the Ingress controller container at `/var/run/secrets/kubernetes.io/serviceaccount/token` by Kubernetes. In your case, the token folder doesn't exist. Please check http://kubernetes.io/docs/user-guide/service-accounts/ and http://kubernetes.io/docs/user-guide/accessing-the-cluster/#accessing-the-api-from-a-pod
How did you setup your Kubernetes cluster?

**Comment by jainesh123** [comment]
Apologies for the delay in response.  I had not configured the service account in the cluster and wasn't aware that it was mandatory for this.
Once I configured those, it no longer gave the above error.

**Comment by gvenka008c** [comment]
@jainesh123 I am also seeing the same error while running the Ingress Controller. Can you point me to the steps that you followed to setup the service account?

```
/var/run/secrets/kubernetes.io/serviceaccount/token
```

```
# ls -ltr /var/run/secrets/kubernetes.io/serviceaccount
ls: cannot access /var/run/secrets/kubernetes.io/serviceaccount: No such file or director

# kubectl get serviceaccounts
NAME      SECRETS   AGE
default   0         21d

# kubectl get secrets
NAME          TYPE                                  DATA      AGE
cafe-secret   Opaque                                2         10d
default       kubernetes.io/service-account-token   0         13m

```
