### ISSUE TITLE
Re-add FIPS related images to tests, image patching & release process 

### ISSUE THREAD

**Issue by shaun-nx** [nginxinc/kubernetes-ingress#5914]
> [!IMPORTANT]  
> OpenSSL v3.4.0 is planned for October 14th
> This version addresses the issue related to OpenSSL and FIPs
> [Comment regarding the release and patching](https://github.com/openssl/openssl/issues/24826#issuecomment-2220416732)
> "There will likely be new patch releases for the 3.1 series, but no fixed date is planned yet"

For release `v3.6.1`, we were unable to build and release FIPS compliant images for NGINX Ingress Controller. This was due to  an update in openssl version `3.1.6-r0`.

[PR that removed FIPS images from tests, image patching & release](https://github.com/nginxinc/kubernetes-ingress/pull/5912)

Details of issue captured here: https://github.com/nginxinc/kubernetes-ingress/issues/5913

**Comment by chandlerkent** [comment]
@shaun-nx is there a timeline on when the FIPS images will be added again?
