### ISSUE TITLE
Provide a Grafana dashboard

### ISSUE THREAD

**Issue by kalise** [nginxinc/kubernetes-ingress#597]
Is there any public Grafana dashboard for this controller? I found many out there but they are for the kubernetes nginx ingress controller (the one managed by kube folks). Thanks.

**Comment by Rulox** [comment]
Hi @kalise 

We don't provide any Grafana dashboard for the NGINX Ingress Controller at the moment. However, there are plans to add this in the future. For now we are focusing in creating a dashboard for the [NGINX Prometheus exporter](https://github.com/nginxinc/nginx-prometheus-exporter) (check this issue https://github.com/nginxinc/nginx-prometheus-exporter/issues/48 for more information)

The Ingress Controller uses that exporter for NGINX and NGINX Plus related metrics, so it will be possible to use it as a base, and then add the missing panels for Ingress Controller metrics. This is something we are planning to do soon.

**Comment by kalise** [comment]
Thks
