### ISSUE TITLE
Supported Kubernetes versions table is confusing

### ISSUE THREAD

**Issue by jputrino** [nginxinc/kubernetes-ingress#5983]
**Describe the bug**

🗒️ Filed on behalf of a user who submitted feedback via the docs site feedback form.

Doc URL: https://docs.nginx.com/nginx-ingress-controller/technical-specifications/#supported-kubernetes-versions
Doc Feedback: 

Having the Supported Kubernetes Version going from max supported to min supported is super confusing. Either having one column of min to max or two columns for min version and max version would make the table much clearer.

**Comment by j1m-ryan** [comment]
Thanks for reporting Jodie, closing as we have switched to showing the supported versions as min - max. We will cherry pick this change shortly.
