### ISSUE TITLE
[Help] clarify multiple Ingress repo use cases

### ISSUE THREAD

**Issue by panpan0000** [nginxinc/kubernetes-ingress#599]
There're several popular kubernetes ingress repos living in github.

- https://github.com/nginxinc/kubernetes-ingress
- https://github.com/aledbf/ingress-nginx
- https://github.com/kubernetes/ingress-nginx

I guess this one is enhanced with nginx-plus. but can I propose to write a doc to tell people the major difference , and different use cases , to help people make choice ?

**Comment by pleshakov** [comment]
Please take a look at this doc https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/nginx-ingress-controllers.md Hope you find it useful.

**Comment by panpan0000** [comment]
Thank you ,it helps a lot.
close this.
