### ISSUE TITLE
Templating nginx.ingress.tmpl proxy_pass not set when backend-protocol annotation is set

### ISSUE THREAD

**Issue by chris8205** [nginxinc/kubernetes-ingress#6030]
**What happened**:

nginx-ingress can't get response from https-backend-(service)

2024/07/16 14:12:02 [error] 48#48: *32 upstream sent no valid HTTP/1.0 header while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: myhost-fqdn, request: "GET /xxxx/xxxxxxxx?xxxx HTTP/1.1", upstream: "http://xxx.xxx.6.3:8443/xxxx/xxxxxxxx?xxxx", host: "myhost-fqdn"

**What you expected to happen**:

in the template proxy_pass seems to be "broken"

```
                   {{- if $location.SSL}}
                proxy_pass https://{{$location.Upstream.Name}}{{$location.Rewrite}};
                {{- else}}
                proxy_pass http://{{$location.Upstream.Name}}{{$location.Rewrite}};
                {{- end}}
```

the following annotation is set...

```
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
```

**NGINX Ingress controller version** 
nginx/nginx-ingress:3.6.1

**Kubernetes version** (use `kubectl version`):
v1.29.4

**Environment**:
Azure K8s

Hope this information are sufficient; maybe i use the wrong annotation; but i can't find the corresponding to set the "flag" to enforce the {{- if $location.SSL}} 

!!! We don't want to pass-thru SSL directly to the back-end !!!

**Comment by vepatel** [comment]
Hi @chris8205 `annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS`
isn't a valid annotation for this project unfortunately, this belongs to[ k8s community ingress controller](https://github.com/kubernetes/ingress-nginx)

**Comment by hamelchRIT** [comment]
Thank You, 
to many different helm charts out there ;)

**Comment by vepatel** [comment]
hi @chris8205 is your issue now resolved?

**Comment by chris8205** [comment]
@vepatel Yes this one is done...
