### ISSUE TITLE
helm.nginx.com/stable chart not updated with new changes

### ISSUE THREAD

**Issue by sujeeth-alef** [nginxinc/kubernetes-ingress#604]
**Describe the bug**
The public helm chart available at helm.nginx.com/stable is not updated with new changes in the master branch.

**Comment by pleshakov** [comment]
@sujeeth-alef 
the chart available via `helm.nginx.com/stable` is the latest stable version of our Helm chart. Right know that version is 0.3.0 and it corresponds to this release https://github.com/nginxinc/kubernetes-ingress/releases/tag/v1.5.0 Once we release a new stable version, `helm.nginx.com/stable` will be updated to include it.

the master branch has the edge version of the helm chart. we don't publish that version.

**Comment by sujeeth-alef** [comment]
@pleshakov Thanks for your response.
