### ISSUE TITLE
Question: nginx ingress pod health check

### ISSUE THREAD

**Issue by srikantheee84** [nginxinc/kubernetes-ingress#605]
How do we setup monitoring for nginx ingress pods with tools like Prometheus or Sysdig ? What endpoints do they expose ? How do we access it ?

**Comment by pleshakov** [comment]
@srikantheee84 
the Ingress Controller exposes the Prometheus endpoint. Please see https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/prometheus.md

We don't have the doc for Sysdig integration. However, it seems that Sysdig [supports](https://sysdig.com/blog/monitor-nginx-kubernetes-metrics-alerts/) NGINX/NGINX Plus on Kubernetes.  Note that you can expose the stub_status/NGINX Plus API via `-nginx-status` group of cli arguments. See https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/cli-arguments.md Unfortunately, I'm not familiar with Sysdig and can't provide you any additional pointers.
