### ISSUE TITLE
Disable Nginx version number in the error pages  

### ISSUE THREAD

**Issue by cyperplex** [nginxinc/kubernetes-ingress#606]
Hi,

Currently having a problem with disabling the version of NGINX in the error pages being displayed by ingress controller.  I added the below option to the ingress values file. That the helm chart is using, but the error page still displays the version number. 

Is there some thing missing from the below?

controller:
  name: controller
  image:
    repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
    tag: "0.21.0"
    pullPolicy: IfNotPresent
    # www-data -> uid 33
    runAsUser: 33

  config:
    large-client-header-buffers: "8 64k"
    proxy-buffer-size: "16k"
    use-proxy-protocol: "true"
    server-tokens: "false"

**Comment by Dean-Coakley** [comment]
Hi @cyperplex 

`repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller`
This repository pulls the [kubernetes community ingress controller](https://github.com/kubernetes/ingress-nginx) which is a different implementation to this one. Please open an issue in that repository if you need assistance.

If you have not decided which ingress controller you wish to use, or are curious about the differences between each implementation you can read about them here: https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/nginx-ingress-controllers.md
