### ISSUE TITLE
Issue while installing ingress nginx controller v1.11.1

### ISSUE THREAD

**Issue by irfansdj** [nginxinc/kubernetes-ingress#6079]
We are trying to install ingress controller v1.11.1 on EKS v1.29 using below manifest and docker images.

https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.1/deploy/static/provider/aws/deploy.yaml
docker pull nginx/nginx-ingress:1.11.1 from docker hub.

But post applying manifest, controller pod is not coming up with below errors.

kubectl -n ingress-nginx logs ingress-nginx-controller-f9648c9bc-tg6gj
I0729 04:15:57.284882 1 main.go:258] Starting NGINX Ingress controller Version=1.11.1 GitCommit=3274536
W0729 04:15:57.294535 1 main.go:297] The '-use-ingress-class-only' flag will be deprecated and has no effect on versions of kubernetes >= 1.18.0. Processing ONLY resources that have the 'ingressClassName' field in Ingress equal to the class.
F0729 04:15:57.296616 1 main.go:301] Error when getting IngressClass nginx: the server could not find the requested resource

Ingress class pretty much exists, but still controller is not able to find ingress class.

kubectl -n ingress-nginx get IngressClass -o yaml
apiVersion: v1
items:

apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"networking.k8s.io/v1","kind":"IngressClass","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"ingress-nginx","app.kubernetes.io/name":"ingress-nginx","app.kubernetes.io/part-of":"ingress-nginx","app.kubernetes.io/version":"1.11.1"},"name":"nginx"},"spec":{"controller":"k8s.io/ingress-nginx"}}
creationTimestamp: "2024-07-26T11:54:21Z"
generation: 1
labels:
app.kubernetes.io/component: controller
app.kubernetes.io/instance: ingress-nginx
app.kubernetes.io/name: ingress-nginx
app.kubernetes.io/part-of: ingress-nginx
app.kubernetes.io/version: 1.11.1
managedFields:
apiVersion: networking.k8s.io/v1
fieldsType: FieldsV1
fieldsV1:
f:metadata:
f:annotations:
.: {}
f:kubectl.kubernetes.io/last-applied-configuration: {}
f:labels:
.: {}
f:app.kubernetes.io/component: {}
f:app.kubernetes.io/instance: {}
f:app.kubernetes.io/name: {}
f:app.kubernetes.io/part-of: {}
f:app.kubernetes.io/version: {}
f:spec:
f:controller: {}
manager: kubectl-client-side-apply
operation: Update
time: "2024-07-26T11:54:21Z"
name: nginx
resourceVersion: "169027338"
uid: e0c974fc-fbc9-4822-97e4-c567d50302a4
spec:
controller: k8s.io/ingress-nginx
kind: List
metadata:
resourceVersion: ""
selfLink: ""
Can somebody help me to fix this issue.

Regards
Irfan

**Comment by pdabelf5** [comment]
Hi @irfansdj 
It looks like you are installing https://github.com/kubernetes/ingress-nginx, you could request help by logging an issue in that project.

Alternatively, you can use the [migration guide](https://docs.nginx.com/nginx-ingress-controller/installation/ingress-nginx/) to move to the F5 NGINX Ingress Controller.  You could then use this project or our [community slack](https://nginxcommunity.slack.com/channels/nginx-ingress-controller) to request help.

I hope this helps.
