### ISSUE TITLE
Investigate codecov reports

### ISSUE THREAD

**Issue by pdabelf5** [nginxinc/kubernetes-ingress#6161]
CodeCov reports have not been functioning correctly since April https://app.codecov.io/github/nginxinc/kubernetes-ingress. Investigate why reports uploaded are showing `Unknown error` or file parse errors 
https://app.codecov.io/github/nginxinc/kubernetes-ingress/commit/0f0e040f2a32887a13573eef94a2c2c4de09f6ed

**Comment by vepatel** [comment]
@pdabelf5  in this [example report](https://storage.googleapis.com/codecov/shelter/github/nginxinc%3A%3A%3A%3Akubernetes-ingress/6cfb60a14939c7903338c52741415ad048ae28f2/d75cc8c2-0cd6-4397-8d48-bda9fba49500.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=GOOG1EJOGFN2JQ4OCTGA2MU5AEIT7OT5Z7HTFOAN2SPG4NWSN2UJYOY5U6LZQ%2F20240813%2Fus-west2%2Fs3%2Faws4_request&X-Amz-Date=20240813T115649Z&X-Amz-Expires=30&X-Amz-SignedHeaders=host&X-Amz-Signature=2ce80649078fbba1ebac1cfc182a785bb537347efc36d97ff72dc87d59dc5a52), i wonder if the bit till `<<<<<< network` is causing issue
