### ISSUE TITLE
Lack of clarity in README for `values-plus.yaml` file

### ISSUE THREAD

**Issue by mjang** [nginxinc/kubernetes-ingress#6217]
**Describe the bug**

In the official docs for deploying NGINX Plus using Helm:
- https://docs.nginx.com/nginx-ingress-controller/installation/nic-images/using-the-jwt-token-docker-secret/#helm-deployment.
   - The Official docs are correct. 
- What is not correct/clear/accurate is the GitHub side here - https://github.com/nginxinc/kubernetes-ingress/tree/main/charts/nginx-ingress 
   - it does not explain what needs to be done to configure the values-plus.yaml properly. 
 
You can see that the example values-plus.yaml file is also not aligned with the example from the docs. It is unclear what private repository needs to be used, etc. I would take the example from the docs almost as it, into the values-plus.yaml file in the GitHub repository and briefly explain that in the README.md file.

**To Reproduce**

README bug as described

**Expected behavior**
Clear content, which includes info on what to do with `values-plus.yml`

**Your environment**

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by ADubhlaoich** [comment]
Closed by #6235 .

**Comment by mjang** [comment]
cc @chrisakker . The one remaining "missing link" is the reference to a blog post that explains the "values-icp.yaml" file. I've asked that we restore the post on the new site for f5.com blogs.

The content of the blog posts still exists at http://web.archive.org/web/20200809142432/https://www.nginx.com/blog/nginx-ingress-controller-ibm-cloud-private/.
