### ISSUE TITLE
Unable to get realip from AWS ALB

### ISSUE THREAD

**Issue by prawen** [nginxinc/kubernetes-ingress#6228]
**Describe the bug**
Hello,

I'm trying to capture and pass the Client IP or Real IP to the upstream. Below is my deployment model.

`Client -> AWS ALB -> Nginx-Ingress deployed on self managed K8s Cluster (1.30) on AWS EC2`

I tried using snippet

```
    nginx.org/location-snippets: |
      proxy_set_header X-ABC-CLIENTIP $proxy_add_x_forwarded_for;
```

But it is not capturing the real IP, rather giving the private IP.

Also, the header case is not retained. It is shown as `X-Abc-Clientip` 

I have tried setting `X-ABC-CLIENTIP` to `$remote_addr` and `$X-Forwarded-For` but it did not help

I did not face this issue with below model

`Client -> Nginx -> Nginx-Ingress deployed on self managed K8s Cluster (1.30) on AWS EC2`

AWS ALB gives real ip using X-Forwarded-For it seems. May I know how we can configure to use that header as is and get the real IP ?

Does anyone has experience on similar setup ? Any help is appreciated. Thanks.

**To Reproduce**
Described above

**Expected behavior**
Capture realip and set that to header `X-ABC-CLIENTIP`

**Your environment**

- Version of the Ingress Controller - 3.5.2
- Version of Kubernetes - 1.30.0
- Kubernetes platform - Self managed K8s 
- Using NGINX or NGINX Plus - NGINX

**Additional context**
N/A

**Comment by j1m-ryan** [comment]
Hi @prawen,

You may have to set up proxy protocol. There is an example of this [here](https://github.com/nginxinc/kubernetes-ingress/tree/v3.6.2/examples/shared-examples/proxy-protocol).  I suggest setting the below values.

```
proxy-protocol: "True"
real-ip-header: "proxy_protocol"
set-real-ip-from: "0.0.0.0/0"
```

Then you may need to find the aws alb proxy protocol annotation. It might be [this one](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.8/guide/service/annotations/#proxy-protocol-v2) but I have not tried it out, then add this annotation to your ingress.

Let us know how you get on.

**Comment by prawen** [comment]
Hi @j1m-ryan ,

Thanks for your response. I will try out the config map. 

However, I forgot to mention. I have not deployed nginx-ingress using helm.

**Comment by j1m-ryan** [comment]
That's np, you don't need the helm chart for adding the service annotation, you can also add it like this.
`kubectl annotate svc/nginx-ingress-controller service.beta.kubernetes.io/aws-load-balancer-proxy-protocol="*"`

**Comment by AlexFenlon** [comment]
@prawen did this solution work for you?
