### ISSUE TITLE
Panic when creating VirtualServer

### ISSUE THREAD

**Issue by hafe** [nginxinc/kubernetes-ingress#6231]
**Describe the bug**
When a VirtualServer references a Policy in a non-watched namespace a panic occurs in getPolicies().

Backtrace:

 E0809 09:30:34.926461       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 568 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1dd0e40?, 0x365e490})
      pkg/mod/k8s.io/apimachinery@v0.29.1/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
      pkg/mod/k8s.io/apimachinery@v0.29.1/pkg/util/runtime/runtime.go:49 +0x6b
panic({0x1dd0e40?, 0x365e490?})
      $GOROOT/src/runtime/panic.go:914 +0x21f
github.com/nginxinc/kubernetes-ingress/internal/k8s.(*LoadBalancerController).getPolicies(0xc000323180, {0xc000aca080?, 0x1, 0x26?}, {0xc000b8a378, 0x16})
      /home/runner/work/kubernetes-ingress/kubernetes-ingress/internal/k8s/controller.go:3290 +0x200
github.com/nginxinc/kubernetes-ingress/internal/k8s.(*LoadBalancerController).createVirtualServerEx(0xc000323180, 0xc000177400, {0x0, 0x0, 0x0})
      /home/runner/work/kubernetes-ingress/kubernetes-ingress/internal/k8s/controller.go:2996 +0x3bc
github.com/nginxinc/kubernetes-ingress/internal/k8s.(*LoadBalancerController).processChanges(0xc000323180, {0xc00053ac30, 0x1, 0x16?})
      /home/runner/work/kubernetes-ingress/kubernetes-ingress/internal/k8s/controller.go:1541 +0x165
github.com/nginxinc/kubernetes-ingress/internal/k8s.(*LoadBalancerController).syncVirtualServer(0xc000323180, {0x26?, {0xc000b14780?, 0xbd00000000bef059?}})
      /home/runner/work/kubernetes-ingress/kubernetes-ingress/internal/k8s/controller.go:1490 +0x254
github.com/nginxinc/kubernetes-ingress/internal/k8s.(*LoadBalancerController).sync(0xc000323180, {0x10?, {0xc000b14780?, 0x1?}})
      /home/runner/work/kubernetes-ingress/kubernetes-ingress/internal/k8s/controller.go:1003 +0x39b
github.com/nginxinc/kubernetes-ingress/internal/k8s.(*taskQueue).worker(0xc000282af8)
      /home/runner/work/kubernetes-ingress/kubernetes-ingress/internal/k8s/task_queue.go:95 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
      pkg/mod/k8s.io/apimachinery@v0.29.1/pkg/util/wait/backoff.go:226 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x8d77e0?, {0x25659c0, 0xc000847a40}, 0x1, 0xc00095a960)
      pkg/mod/k8s.io/apimachinery@v0.29.1/pkg/util/wait/backoff.go:227 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0xd8?, 0xc000bb8000?)
      pkg/mod/k8s.io/apimachinery@v0.29.1/pkg/util/wait/backoff.go:204 +0x7f
k8s.io/apimachinery/pkg/util/wait.Until(...)
      pkg/mod/k8s.io/apimachinery@v0.29.1/pkg/util/wait/backoff.go:161
github.com/nginxinc/kubernetes-ingress/internal/k8s.(*taskQueue).Run(0xc000a8f7d0?, 0x8d7065?, 0xc0008a1380?)
      /home/runner/work/kubernetes-ingress/kubernetes-ingress/internal/k8s/task_queue.go:44 +0x3a
created by github.com/nginxinc/kubernetes-ingress/internal/k8s.(*LoadBalancerController).Run in goroutine 1
      /home/runner/work/kubernetes-ingress/kubernetes-ingress/internal/k8s/controller.go:721 +0xad3
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
      panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x130 pc=0x1b400a0]

**To Reproduce**

- Configure NIC to watch a single namespace with a certain label
- Label the NIC namespace
- Create a VS in the NIC namespace with a policy referencing another, not watched namespace

**Expected behavior**
NIC should not panic but just log a warning and VS should be invalid.

**Your environment**

- NIC 3.6.1
- Kind

**Additional context**

**Comment by j1m-ryan** [comment]
Hi @hafe, I can't seem to replicate this.

Here's what I did:

1. Deployed NIC v3.6.1 in the default namespace with the helm value `watchNamespaceLabel: "foo=bar"`
2. Labeled the default namespace with  `k label ns default foo=bar`
3. In the example here `kubernetes-ingress/examples/custom-resources/rate-limit`, I deployed `virtual-server.yaml` and `webapp.yaml`, i.e everything but the policy
4. Then I created a new namespace `test`
5. Then i deployed the policy in the `test` namespace

After these steps NIC does not panic for me. The VirtualServer is invalid (as it should be) as the policy does not exist in its namespace.
The policy exists but is not watched by NIC.

Do these steps cause the panic for you?, or have I gone about this replication wrong?

**Comment by hafe** [comment]
In my testcase the second namespace did not even exist. 

Look at the testcase I added. The watch namespace feature was not tested.

If you run the new testcase against the current code base you get the panic

**Comment by j1m-ryan** [comment]
> In my testcase the second namespace did not even exist.

I would have still expected it to panic at step 3 then, when applying the VirtualServer with a policy that does not exist (in the labeled namespace that NIC is watching), but it did not panic for me.

> If you run the new testcase against the current code base you get the panic

I have done this and see that this is true, also thanks for adding this test coverage (and the fix too).

Never the less, it would be useful to reproduce it from the users perspective, rather than just seeing the test case do it programmatically. PR looks good irrespective, but it would be a nice to have as we could add a python test for this too.

**Comment by hafe** [comment]
Let's see if I can come up with something reproducible. 

There are many similar code constructs that make me a bit worried!

**Comment by hafe** [comment]
Let's see if I can come up with something reproducible. 

There are many similar code constructs that make me a bit worried!

**Comment by hafe** [comment]
In the example you referenced, the policy in the vs is not referenced with a namespace

**Comment by j1m-ryan** [comment]
Ah ok thanks @hafe! yeah I can replicate this now. Same steps before, but `namespace: test` in the policy array as you said. Then it fails at step 3.

```yaml
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: webapp
spec:
  host: webapp.example.com
  policies:
  - name: rate-limit-policy
    namespace: test
  upstreams:
  - name: webapp
    service: webapp-svc
    port: 80
  routes:
  - path: /
    action:
      pass: webapp
```
