### ISSUE TITLE
HSTS not working using hsts-behind-proxy

### ISSUE THREAD

**Issue by bilby91** [nginxinc/kubernetes-ingress#627]
Hello,

I'm trying to setup HSTS support using annotations in the ingress but I'm not having luck with it. We have the nginx-ingress in front of an AWS ALB that handles SSL termination.

This is how the ingress looks like:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/hsts: "True"
    nginx.org/hsts-behind-proxy: "True"
    nginx.org/hsts-include-subdomains: "True"
    nginx.org/hsts-max-age: "2592000"
    nginx.org/mergeable-ingress-type: master
    nginx.org/redirect-to-https: "True"
  creationTimestamp: 2019-07-03T15:02:57Z
  generation: 1
  name: nginx-host-master-app.dev.company.net
  namespace: default
  resourceVersion: "50956162"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/nginx-host-master-app.dev.company.net
  uid: a434f4e8-9da3-11e9-9d08-1296d0bc4772
spec:
  rules:
  - host: app.dev.company.net
status:
  loadBalancer:
    ingress:
    - {}
```

I've checked the dynamic configuration that is built by the controller under `/etc/nginx/conf.d/` and the expected directives are not there. 

I verified that changing `nginx.org/proxy-connect-timeout` did actually make a change on the nginx configuration so the annotations are working to a degree.

**Expected behavior**
The HSTS relevant headers are added in the response.

**Your environment**
* Version of the Ingress Controller: 1.5.1-alpine
* Version of Kubernetes: 1.11
* Kubernetes platform: EKS
* Using NGINX or NGINX Plus: NGINX

**Comment by bilby91** [comment]
I turned on the debugging feature and the following headers are being sent to the ingress:

```
2019/07/18 23:28:34 [debug] 83#83: *30 http proxy header:
"GET /overview HTTP/1.1
Host: app.dev.company.net
X-Real-IP: 10.4.52.34
X-Forwarded-For: 10.200.100.164, 10.4.52.34
X-Forwarded-Host: app.dev.company.net
X-Forwarded-Port: 80
X-Forwarded-Proto: https
Connection: close
X-Amzn-Trace-Id: Root=1-5d3100a2-8aa88a95f87597ed4cb7cb33
cache-control: max-age=0
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,es;q=0.8,pt;q=0.7
```

Based on the docs, since `X-Forwarded-Proto` value is `https`, the `nginx.org/hsts-behind-proxy` annotation should in theory trigger the HSTS support.

**Comment by bilby91** [comment]
I've been looking into the source code and could narrow it down to this piece of the template.

```
	{{if $server.SSL}}
	{{if not $server.GRPCOnly}}
	{{- if $server.HSTS}}
	set $hsts_header_val "";
	proxy_hide_header Strict-Transport-Security;
	{{- if $server.HSTSBehindProxy}}
	if ($http_x_forwarded_proto = 'https') {
	{{else}}
	if ($https = on) {
	{{- end}}
		set $hsts_header_val "max-age={{$server.HSTSMaxAge}}; {{if $server.HSTSIncludeSubdomains}}includeSubDomains; {{end}}preload";
	}

	add_header Strict-Transport-Security "$hsts_header_val" always;
	{{end}}

	{{- if $server.SSLRedirect}}
	if ($scheme = http) {
		return 301 https://$host:{{index $server.SSLPorts 0}}$request_uri;
	}
	{{- end}}
	{{end}}
	{{- end}}
```

This made me wonder if I might be missing an annotation/config-map value that would make `$server.SSL` true.

**Comment by Dean-Coakley** [comment]
Hi @bilby91 

> This made me wonder if I might be missing an annotation/config-map value that would make $server.SSL true.

There is no configmap/annotation for `server.SSL`, instead it is set to true when ssl termination is done by the ingress controller and configured correctly. 

Therefore, this bug makes the HSTSBehindProxy annotation/AWS ALB SSL termination use case not possible. Terribly sorry about that.


We will get this fixed as soon as possible. In the meantime, if you need this urgently you can:
* Use a [custom template](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/custom-templates#custom-templates) for the ingress template to fix the logic there.
* Or if you feel up for the task, you can open a Pull Request.

**Comment by bilby91** [comment]
@Dean-Coakley Hello! 

Thanks for taking the time to read the comments! I ended up solving it using a `server-snippet` so it wasn't that bad :)

I'm willing to make the fix if you haven't!

Let me know!

**Comment by Dean-Coakley** [comment]
@bilby91 Great to hear you were able to resolve the issue! :)


> I'm willing to make the fix

That would be great!

**Comment by bilby91** [comment]
@Dean-Coakley I sent some code that should fix the issue. PR #632 

I would appreciate any advice in regards to contributing since it's my first time on this project.

Thanks!
