### ISSUE TITLE
Include info on values-icp..yaml, original in a blog post

### ISSUE THREAD

**Issue by mjang** [nginxinc/kubernetes-ingress#6273]
**Describe the bug**

In several places, we refer to a blog post for more info on the `values-icp.yaml` file.

In the transition from blogs on NGINX -> F5, that info was "lost".
The content is still available via the "[Wayback machine](http://web.archive.org/web/20200809142432/https://www.nginx.com/blog/nginx-ingress-controller-ibm-cloud-private/)"

### Location

- https://docs.nginx.com/nginx-ingress-controller/installation/installing-nic/installation-with-helm/

(The problem also existed in the nginx-ingress README, but was replaced with a link to the noted "installation-with-helm" doc [on Aug 19](https://github.com/nginxinc/kubernetes-ingress/pull/6235/files#diff-0ba161dd052247c6e21fb8101c5979dfa0eef87ef0632a16f572560e76ccd087))

The problem also exists in two other private, **archived** repositories. Since those are essentially inactive, we will limit work to the docs in this repository. cc @jputrino @ADubhlaoich 

**"Solution"**

Plan: include minimum necessary content from the noted blog post into the documentation

**To Reproduce**

**Expected behavior**

**Your environment**

**Additional context**
A prospective customer discovered bad links in these docs. They did _not_ specifically cite the noted blog post.

**Comment by ADubhlaoich** [comment]
I discussed this with the PM @brianehlert: the blog post is from 2018, and although IBM Cloud should still be conformant, it is not a use case with formal support, and thus, there is no need to document it.

I suspect that someone probably jumped the gun when adding any mention of it to the documentation in the first place - the remediation is to remove the link altogether. Service Mesh is also EOD/EOL, so I will remove that entire section.

**Comment by ADubhlaoich** [comment]
PR up and linked to this issue.
