### ISSUE TITLE
Ingress proxy not connecting to upstreams, multiple retries required

### ISSUE THREAD

**Issue by sgrzemski** [nginxinc/kubernetes-ingress#640]
**Describe the bug**
The nginx proxies from our k8s cluster ingress have multiple problems connecting to upstream servers. We've deployed an ingress with nginx/nginx-ingress:edge and in general it's working fine. Sometimes, on random time of the day it just stops connecting to the upstreams and needs multiple retries to finally reach the upstream.

The basic nginx configuration is:
```user  nginx;
worker_processes  auto;                     
worker_rlimit_nofile 1047552;
worker_shutdown_timeout 10s;
daemon off;                                                    
                                                           
error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;   
                                                                            
events {                                                                                                   
    worker_connections  16384;
    use epoll;
    multi_accept on;
}                                                  
                                                       
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream; 
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    access_log  /var/log/nginx/access.log  main;
    sendfile            on;
    aio                 threads;
    aio_write           on;
    log_subrequest      on;
    tcp_nopush  on;           
    tcp_nodelay on;
    keepalive_timeout 60s;
    reset_timedout_connection on; 
    proxy_buffer_size 32k;
    proxy_buffers 4 32k;
    proxy_busy_buffers_size 32k;
    client_body_timeout 60s;
    real_ip_header      X-Forwarded-For;
    gzip  on;
    gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/json application/xml application/javascript;
    gzip_min_length 1024; 
    server_names_hash_max_size 512;
    variables_hash_bucket_size 256;
    variables_hash_max_size 1024;
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }
```
Then, there is a basic port 80 server where upstreams and locations are taken from Kubernetes API (services, pods' addresses, etc.). The pods are communicating to each other over the service mesh created with nginx ingress proxies. All services has defined nginx endpoint as fqdn. Ingress is deployed as a daemon set with node port. We tweaked sysctl on each of the nodes with the following settings:
```
net.core.rmem_max=16777216
net.core.wmem_max=16777216
net.ipv4.tcp_rmem=4096 87380 16777216
net.ipv4.tcp_wmem=4096 65536 16777216
net.ipv4.tcp_syncookies=1
vm.swappiness=0
net.netfilter.nf_conntrack_max=262144
net.ipv4.tcp_max_syn_backlog=100000
net.core.somaxconn=100000
net.core.netdev_max_backlog=100000
net.ipv4.tcp_max_syn_backlog=100000
net.ipv4.ip_local_port_range=10000 65535
net.ipv4.tcp_tw_reuse=0
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6=1
net.ipv6.conf.lo.disable_ipv6=1
net.ipv4.ip_forward=1
net.ipv4.ip_local_port_range=10000 65535
kernel.sched_migration_cost_ns=5000000
kernel.sched_autogroup_enabled=0
net.ipv4.tcp_orphan_retries=4
net.ipv4.tcp_slow_start_after_idle=0
net.ipv4.tcp_window_scaling=1
net.ipv4.tcp_rfc1337=1
net.ipv4.tcp_keepalive_time=7200
net.ipv4.tcp_keepalive_probes=9
net.ipv4.tcp_keepalive_intvl=75
net.ipv4.tcp_no_metrics_save=0
net.ipv4.tcp_max_syn_backlog=100000
net.ipv4.tcp_fin_timeout=10
net.ipv4.tcp_synack_retries=2
```

With this configuration we're getting occasional waves of requests with multiple conneciton retries. The nginx is not able to connecto to an upstream and it has an empty `$upstream_addr` variable. The error message is:
```{"log":"2019/08/01 11:14:36 [error] 6436#6436: *227487 upstream timed out (110: Connection timed out) while connecting to upstream, client: HIDDEN, server: ```
```
and
```request_time:0.158 upstream_resp_time:0.052, 0.052, 0.052 upstream_connect_time:-, -, - upstream_header_time:-, -, - response_status:504```
We're deploying the ingress with `somaxconn` set to `10240` for each proxy. We've run the proxy in debug mode, but no luck to find anything. The conntrack usage on the nodes is 6% tops. Withour the connection timeout we saw logs with establishing connections for 30-40s, while on other proxies it was connecting blazingly fast.

**To Reproduce**
Steps to reproduce the behavior:
1. Deploy nginx-ingress to kuberneres
2. Initiate over 250 req/s on one upstream
3. See connections retrying

**Expected behavior**
Succesfully establish new connections 24h/7.

**Your environment**
* Version of the Ingress Controller - nginx:edge
* Version of Kubernetes - 14.4
* Kubernetes platform - custom
* Using NGINX

**Comment by Rulox** [comment]
Hey @sgrzemski could you figure this out or you still need help? (eg if this was really an issue we will need to have a look). Thanks

**Comment by nandeeshb09** [comment]
@Rulox , we are also facing this issue intermittently.

As this issue we are facing in for all our services , whenever this issue accours , need to restart ingress controller pod. We don't want to do this.
Is there any work around for this or is this bug.? Your help would help great.

*47813033 connect() failed (111: Connection refused) while connecting to upstream, client: 3.9.38.162, server: integration-ja.mediaiqdigital.com, request: "GET /aiq/api/client/basic HTTP/1.1", upstream: "http://10.12.20.54:80/aiq/api/client/basic", host: "hostname", referrer: "https://url.com/"

**Comment by Rulox** [comment]
Hey @nandeeshb09 , sorry to hear you're experiencing this.

This should not be happening at all, so let's try to find out why this happens to you.

Can you provide the following?

* When is this happening? Just randomly?
* Are you using any network provider (like Calico) in your cluster?
* Are you seeing error logs in your applications behind the Ingress Controller as well?
* Can you let me know what version of the Ingress Controller and Kubernetes you're using (also NGINX Open source or Plus)?
* And additionally, the Ingress Resource config and generated nginx conf?

Thanks

**Comment by sgrzemski-ias** [comment]
@nandeeshb09 
In our case setting proxy connection timeout to some small value (like 50-100ms) solved the problem. We did some more proxy timeout tuning as well (for example `proxy_read_timeout`). We've also set `proxy_next_upstream` to retry failed connections (also the non_idempotent/PUT ones).
