### ISSUE TITLE
Multiple master ingresses with singles minion ingress (with multiple host rules)

### ISSUE THREAD

**Issue by bilby91** [nginxinc/kubernetes-ingress#644]
We stumbled upon this scenario yesterday and we were wondering if this is a bug or not. Basically we have multiple master ingresses:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/mergeable-ingress-type: master
    nginx.org/redirect-to-https: "True"
  creationTimestamp: 2019-07-03T15:02:57Z
  generation: 1
  name: nginx-host-master-app.dev.company.net
  namespace: default
  resourceVersion: "50956162"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/nginx-host-master-app.dev.company.net
  uid: a434f4e8-9da3-11e9-9d08-1296d0bc4772
spec:
  rules:
  - host: app.dev.company.net
status:
  loadBalancer:
    ingress:
    - {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/mergeable-ingress-type: master
    nginx.org/redirect-to-https: "True"
  creationTimestamp: 2019-07-03T15:02:57Z
  generation: 1
  name: nginx-host-master-app.dev.company.com
  namespace: default
  resourceVersion: "50956162"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/nginx-host-master-app.dev.company.com
  uid: a434f4e8-9da3-11e9-9d08-1296d0bc4772
spec:
  rules:
  - host: app.dev.company.com
status:
  loadBalancer:
    ingress:
    - {}
```

And then we have a single minion ingress with multiple rules that target the two master domains.
 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/mergeable-ingress-type: minion
  creationTimestamp: 2019-08-01T22:35:05Z
  generation: 1
  name: my-app
  namespace: my-app
  resourceVersion: "49808295"
  selfLink: /apis/extensions/v1beta1/namespaces/my-app/ingresses/my-app
  uid: 9c24b64e-b4ac-11e9-a1a1-025f8c9cbae8
spec:
  rules:
  - host: app.dev.company.com
    http:
      paths:
      - backend:
          serviceName: my-app
          servicePort: my-app-svc
        path: /
  - host: app.dev.company.net
    http:
      paths:
      - backend:
          serviceName: my-app
          servicePort: my-app-svc
        path: /

status:
  loadBalancer:
    ingress:
    - {}

```

What happens when using this configuration is that non of the ingresses work. I looked at the nginx configuration file and the upstream services were not there.

**Expected behavior**
Ingress is able to route traffic for the two rules inside the minion ingress. 

**Your environment**
* Version of the Ingress Controller: 1.5.1-alpine
* Version of Kubernetes: 1.11
* Kubernetes platform: EKS
* Using NGINX or NGINX Plus: NGINX

**Comment by pleshakov** [comment]
@bilby91 
Both mergeable master and minions are only allowed to have one host. For your case, splitting the current minion into two minions with different hosts should solve the issue.  I wonder what are the downsides of this limitation for you.

**Comment by bilby91** [comment]
@pleshakov We fixed our issue by creating two minions as you just said. There is no limitation, I was wondering if this was a bug or not. 

Is this beahviour documented somewhere ?

Thanks!

**Comment by pleshakov** [comment]
@bilby91 
ok. thanks.

yep, it is documented in https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/mergeable-ingress-types in the paragraph above the Example section.

**Comment by bilby91** [comment]
I looked on that file yesterday but clearly missed it! Closing. Thanks for taking the time to review the issue!
