### ISSUE TITLE
SSO in ingress nginx with Github not working as expected

### ISSUE THREAD

**Issue by nguyenphu123** [nginxinc/kubernetes-ingress#6468]
I am using this example to set up SSO for my ingress controller: [ingress-nginx/docs/examples/auth/oauth-external-auth/oauth2-proxy.yaml at main · kubernetes/ingress-nginx · GitHub](https://github.com/kubernetes/ingress-nginx/blob/main/docs/examples/auth/oauth-external-auth/oauth2-proxy.yaml)
and I am facing two issues: If I used the same hostname for both ingresses, one ingress will lose all IPs. If I switch to a different hostname, the SSO work but I can still access the service even when I am not logged in.

I tried with two public hosts on cloudflare but can still access the service with or without login. My system is an on-premise which is running on metallb ARP mode. Thanks in advanced.

**Comment by vepatel** [comment]
hi @nguyenphu123, looks like you're using a k8s community Ingress Controller not Nginx Ingress Controller (this project), please open an issue in https://github.com/kubernetes/ingress-nginx/ or feel free to give a try to this one.
