### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by bilalmalik777** [nginxinc/kubernetes-ingress#667]
**Describe the bug**
I created a web portal and it is working perfectly in Kubernetes with loadbalancer over https protocol. But when i tried to run it with ingress it starts to land on bad gateway page. 

**Additional information**
the application is developed in Dotnet core and running over SSL

**yaml files**
The following is my portal,portal service and ingress YAML respectively:

**portal yaml**
> 
apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  labels:
    app: tt-core-web
  name: tt-core-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tt-core-web
    spec:
      containers:
      - image: webportal:latest
        name: webportal
        imagePullPolicy: Always
        ports:
          - containerPort: 443
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: dev
**poral service yaml**
> 
apiVersion: v1
kind: Service
metadata:
  name: tt-core-web-service-dev
spec:
  type: ClusterIP
  selector:
    app: tt-core-web
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443

**ingress yaml**
> 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
       paths:
        - path: /
          backend:
            serviceName: tt-core-web-service-dev
            servicePort: 443
        - path: /api/
          backend:
            serviceName: tt-core-web-service-dev
            servicePort: 443
        - path: /api/
          backend:
            serviceName: tt-core-web-service-dev
            servicePort: 443

Please help me to solve this error

**Comment by pleshakov** [comment]
@bilalmalik777 
it looks like you need to enable HTTPs between the Ingress Controller and your backend. For that, please see [this example](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/ssl-services). Additionally, it is required that you set the host field in your Ingress resource. For example, see https://github.com/nginxinc/kubernetes-ingress/blob/master/examples/complete-example/cafe-ingress.yaml#L11

Note that `nginx.ingress.kubernetes.io/rewrite-target: /` annotation is supported by another NGINX Ingress Controller -- https://github.com/kubernetes/ingress-nginx, which is a different project. The differences are described [here](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/nginx-ingress-controllers.md). If you're using that project, please check its documentation and consider opening an issue in that repo.

**Comment by bilalmalik777** [comment]
Thanks for your response. We are using a different nginx ingress controller. i am closing this issue
