### ISSUE TITLE
[Bug]: Missing "/v3" in the go.mod file breaks go fetching project as module

### ISSUE THREAD

**Issue by smuda** [nginxinc/kubernetes-ingress#6763]
### Version

3.6.2

### What Kubernetes platforms are you running on?

Openshift

### Steps to reproduce

I want to include github.com/nginxinc/kubernetes-ingress in another golang project (for example to be able to read/write Policy objects to the K8s api) so I use the following command:

```
% go get github.com/nginxinc/kubernetes-ingress@v3.6.2 
go: github.com/nginxinc/kubernetes-ingress@v3.6.2: invalid version: module contains a go.mod file, so module path must match major version ("github.com/nginxinc/kubernetes-ingress/v3")
```

This seems to be by design by the golang authors. Referenses:

- [How To Upgrade To A Major Version In Go](https://golang.cafe/blog/how-to-upgrade-to-a-major-version-in-go.html)
- [invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2](https://github.com/golang/go/issues/35732)

So this means that the following command should work:
```
% go get github.com/nginxinc/kubernetes-ingress/v3@v3.6.2 
go: github.com/nginxinc/kubernetes-ingress@v3.6.2: invalid version: module contains a go.mod file, so module path must match major version ("github.com/nginxinc/kubernetes-ingress/v3")
```

It seems that this is because the go.mod in the project does not include "/v3".

**Comment by danielnginx** [comment]
Hi @smuda

Thank you for your contribution but we will not accept it this time. 

This is not how we intended our project to be used so we will not support it for now.

**Comment by smuda** [comment]
@danielnginx I don't really understand, could you elaborate?

My usecase is that with the latest version of the WAF I need to supply the apBundle and apLogBundle to the nginx container but to do that I need to read the Policy object from the k8s api. Since that is a CRD, I need the definitions and the easiest way to do that would be to use your definition of the objects instead of copy-paste.

**Comment by jjngx** [comment]
@smuda could you please provide info which package from the module you want to import to another Go application. Please note that if the package is under `internal` you won't be able to import it.

**Comment by smuda** [comment]
I wanted to import roughly everything under `/pkg`. Now I switched to using dynamic client and copied the files from /pkg/apis/configuration to my own project but that's really not how I want to do it, neither from a license view nor a maintenance view.

So, please follow golang best practices to enable using this project as a dependency.
