### ISSUE TITLE
[Proposal]: Add large_client_header_buffers,client_header_buffer_size as configmap keys

### ISSUE THREAD

**Issue by niruse** [nginxinc/kubernetes-ingress#6857]
I’ve opened a second issue case here as well:
https://github.com/nginxinc/nginx-ingress-helm-operator/issues/426
### Version
3.6.1

### What Kubernetes platforms are you running on?

Openshift

### Steps to reproduce

# Bug Report: 400 Error When Request URL/Header Is Too Long
![Image](https://github.com/user-attachments/assets/383224e3-3104-427b-9ccf-d186978ad079)

## **Describe the Bug**
We couldn't find the proper setting to add to my `configmap` for updating `large_client_header_buffers` and `client_header_buffer_size`.  
We could publish different configurations based on the article, but those two are not working.

---

## **To Reproduce**
1. Deploy the NGINX operator.
2. Deploy the ConfigMap (CM) with the following configuration:
    ```yaml
    apiVersion: v1
    data:
      client-header-buffer-size: 512k
      client-max-body-size: 100m
      keep-alive-requests: "10000"
      large-client-header-buffers: 4 64k
    ```
3. Run the following command on one of the nodes:
    ```bash
    oc exec -it ngx1-nginx-ingress-controller-77dd6577b8-wfx89 -n nginx-ingress -- grep -r "client_header_buffer_size" /etc/nginx/
    ```
   - The configuration contains `client_header_buffer_size` changed to the new size.
4. Run the same command with `large_client_header_buffers`:
    ```bash
    oc exec -it ngx1-nginx-ingress-controller-77dd6577b8-wfx89 -n nginx-ingress -- grep -r "large_client_header_buffers" /etc/nginx/
    ```
   - **Issue:** The configuration does not reflect the changes for `large_client_header_buffers`.

---

## **Expected Behavior**
You should see the updated configuration in the NGINX configuration.

---

## **Manual Solution**
When I updated the `large_client_header_buffers` and `client_header_buffer_size` manually in the `nginx.conf` file, the error 400 was resolved, and I gained access to the web application.

---

## **Environment**
- **Version of the NGINX Ingress Operator:** 2.3.1
- **Version of the Ingress Controller:** 3.6.1
- **Version of Kubernetes:** v1.27.16+e826056
- **Kubernetes Platform:** OpenShift
- **Using NGINX or NGINX Plug:** Using NGINX
- **Client Version:** 4.14.18
- **Kustomize Version:** v5.0.1
- **Server Version:** 4.14.35

---

**Comment by j1m-ryan** [comment]
Hi @niruse,
`large-client-header-buffers` and `client-header-buffer-size` are not supported config map keys. You can see a list of supported keys [here](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource). 

The way to do this at the moment is to use a [http or server snippet in the configmap](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#snippets-and-custom-templates).

I will change this issue from a bug to a proposal to add these keys as first class config map keys.

**Comment by niruse** [comment]
Hi Ryan,
Thank you for your response.
Could you provide an example of how to add it as snippets or HTTP in configmap?
We’ve tried different methods without success.
