### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by aledbf** [nginxinc/kubernetes-ingress#7]
The nginx plus controller builds a docker images using 1 license. That's ok? 
I mean I assumed that 1 license is for 1 running instance of nginx but using a replication controller with 2 replicas will use the same license

**Comment by pleshakov** [comment]
That's ok. The license is a certificate and a key file that gives you access to NGINX Plus repository. The files are the same for every instance you purchase.
However, the number of Plus replicas should be limited by the number of purchased instances.
