### ISSUE TITLE
NGINX Incubator Chart Repo

### ISSUE THREAD

**Issue by ameijer-corsha** [nginxinc/kubernetes-ingress#711]
**Is your feature request related to a problem? Please describe.**
I contributed a bit of code to the ingress helm chart back in June, but am a little frustrated to see that I still cannot obtain the updated code from the official NGINX helm repo since it hasn't yet gone into a stable release. This requires me to clone the git repo to use the new code which breaks our existing chart deployment workflows. At the same time, I understand the need for the delay before promoting a given piece of code to the 'stable' set of artifacts.

**Describe the solution you'd like**
Similar to how the official chart repos work (separate 'stable' and 'incubator' repos), I suggest solving this problem via the introduction of an NGINX 'incubator' repo that holds packaged helm charts built from the HEAD of master. The charts in incubator could have the disclaimer stating that the code is unstable, etc, but would allow us to use the features we have contributed/requested sooner, until they are promoted to stable at a later date.

**Describe alternatives you've considered**
I currently clone master HEAD as a submodule, then deploy as a local chart.

**Comment by pleshakov** [comment]
@ameijer-corsha thanks for the proposal! we'll discuss it internally and get back to you next week.

**Comment by pleshakov** [comment]
@ameijer-corsha we will start publishing the edge version through our help repo shortly. Please stay tuned.

**Comment by dboenig** [comment]
@ameijer-corsha we're happy to announce, that the edge version of the NGINX ingress controller is now publicly available! You can find the instructions here: https://hub.helm.sh/charts/nginx-edge/nginx-ingress
