### ISSUE TITLE
Websocket proxy timeout

### ISSUE THREAD

**Issue by Archanian** [nginxinc/kubernetes-ingress#715]
I'm having an issue with my proxied websocket connections getting timed out, even though I have implemented a heartbeat mechanism (ping/pong). Connection handshake goes smoothly, I am able to send/receive messages, and I am seeing the pong response being logged server-side from clients every 10 seconds, but it doesn't seem to be resetting the timeout ... my connections are still dropped exactly on the configured read_timeout elapsed time.

From some posts on nginx forums I've read the heartbeat _should_ reset the timeout ... but I'm not sure. Regular messages do in fact reset the timeout, just not the ping/pong.

I've verified it is in fact the read timeout by setting the `proxy_read_timeout` value, which alters the point at which the timeout occurs (ie. if I set to 120s, disconnects after 2 minutes, 300s = 5 minutes, etc.)

I also see in the logs:
`[nginx-ingress-2zbxs] 2019/10/01 02:33:15 [info] 27#27: *519 upstream timed out (110: Connection timed out) while proxying upgraded connection ...`

Any advice or suggestions on what the correct behaviour is here would be greatly appreciated. It seems like setting a really high `proxy_read_timeout` would kind of work, although not ideal? Is there anything else I can check or might be doing wrong?

**Comment by Rulox** [comment]
Hi @Archanian we're sorry this is not working for you. We'll have a look on our end and will get back to you soon.

**Comment by pleshakov** [comment]
@Archanian 
> From some posts on nginx forums I've read the heartbeat should reset the timeout

You're right: the heartbeat should reset the timeout.  The proxied server can be configured to periodically send WebSocket ping frames to reset the timeout.

Could you possibly attach the generated config (https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/troubleshooting.md#checking-the-generated-config) and the corresponding Ingress resource?

**Comment by Archanian** [comment]
Sure thing, thanks for looking into this.

Generated config for nginx:
`
server {
	listen 80 proxy_protocol;

	set_real_ip_from 0.0.0.0/0;
	real_ip_header proxy_protocol;

	server_tokens on;

	server_name <OMITTED>;
	
	gzip on;
	gzip_proxied any;
	gzip_types 
	  text/plain
	  text/css
	  text/xml
	  text/javascript
	  application/javascript;
		
	location / {
		
		proxy_http_version 1.1;
		
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;

		proxy_connect_timeout 60s;
		proxy_read_timeout 120s;
		proxy_send_timeout 60s;
		client_max_body_size 1m;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Port $server_port;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_buffering on;
		
		proxy_pass <OMITTED>;		
		
	}
	
}
`

Ingress definition:
`
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hd-ingress
  annotations:
    nginx.org/websocket-services: "web-service"
    nginx.org/server-snippets: |
      gzip on;
      gzip_proxied any;
      gzip_types 
        text/plain
        text/css
        text/xml
        text/javascript
        application/javascript;
spec:
  rules:
  - host: <OMITTED>
    http:
      paths:
      - path: /
        backend:
          serviceName: web-service
          servicePort: 80
`

**Comment by pleshakov** [comment]
@Archanian 
the config looks correct. 

it looks like the reason for the web socket connection drop is that the upstream server times out. i.e. it stopped responding.

Do you have this problem for every websocket connection or just for some of them?

**Comment by Archanian** [comment]
This happens for every connection that is idle (ie. only sending ping/pong every 10 seconds). I tried implementing my own application-level "ping" messages, and the connection doesn't time out in this case.

**Comment by pleshakov** [comment]
@Archanian 
I think it makes sense to double check if the ping-pong mechanism works.

could you possibly enable the debug logging in NGINX? this way it is possible to see if the ping pong messages are going through a connection. 

To enable the debug log:
*   Start the IC with the `-nginx-debug` argument set.
*  Put `'error-log-level: debug' in the ConfigMap` in the configmap.

For every established websocket connection, you will be able to see when it is established, when the data is going through and when it is terminated.

For example:
```
2019/10/01 23:01:45 [debug] 15851#15851: *7 recv: fd:9 129 of 4096
2019/10/01 23:01:45 [debug] 15851#15851: *7 http proxy status 101 "101 Switching Protocols"
2019/10/01 23:01:45 [debug] 15851#15851: *7 http proxy header: "Upgrade: websocket"
2019/10/01 23:01:45 [debug] 15851#15851: *7 http proxy header: "Connection: Upgrade"
2019/10/01 23:01:45 [debug] 15851#15851: *7 http proxy header: "Sec-WebSocket-Accept: jBOkltuW7IXfgy0yPrHgbT5RSl4="
2019/10/01 23:01:45 [debug] 15851#15851: *7 http proxy header done
2019/10/01 23:01:45 [debug] 15851#15851: *7 HTTP/1.1 101 Switching Protocols

. . .

2019/10/01 23:01:59 [debug] 15851#15851: timer delta: 10012
2019/10/01 23:01:59 [debug] 15851#15851: *7 event timer del: 9: 6188368
2019/10/01 23:01:59 [debug] 15851#15851: *7 http upstream request: "/?"
2019/10/01 23:01:59 [debug] 15851#15851: *7 http upstream process upgraded, fu:1
2019/10/01 23:01:59 [info] 15851#15851: *7 upstream timed out (110: Connection timed out) while proxying upgraded connection, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8010/", host: "127.0.0.1:9001"
2019/10/01 23:01:59 [debug] 15851#15851: *7 finalize http upstream request: 504
2019/10/01 23:01:59 [debug] 15851#15851: *7 finalize http proxy request
2019/10/01 23:01:59 [debug] 15851#15851: *7 free rr peer 1 0
2019/10/01 23:01:59 [debug] 15851#15851: *7 close http upstream connection: 9
2019/10/01 23:01:59 [debug] 15851#15851: *7 free: 0000560100E2BB30, unused: 48

. . .
```

**Comment by Archanian** [comment]
I do see those logs:

On connect:
```
2019/10/03 07:14:14 [debug] 21#21: *1762 recv: fd:18 166 of 4096
2019/10/03 07:14:14 [debug] 21#21: *1762 http proxy status 101 "101 Switching Protocols"
2019/10/03 07:14:14 [debug] 21#21: *1762 http proxy header: "Connection: Upgrade"
2019/10/03 07:14:14 [debug] 21#21: *1762 http proxy header: "Date: Thu, 03 Oct 2019 07:14:13 GMT"
2019/10/03 07:14:14 [debug] 21#21: *1762 http proxy header: "Upgrade: websocket"
2019/10/03 07:14:14 [debug] 21#21: *1762 http proxy header: "Sec-WebSocket-Accept: Imw3+38E5f9bdC2xn9qYDlMs4yw="
2019/10/03 07:14:14 [debug] 21#21: *1762 http proxy header done
2019/10/03 07:14:14 [debug] 21#21: *1762 HTTP/1.1 101 Switching Protocols
```
On timeout
```
2019/10/03 07:16:11 [debug] 21#21: epoll timer: 2847
2019/10/03 07:16:14 [debug] 21#21: timer delta: 2848
2019/10/03 07:16:14 [debug] 21#21: *1762 event timer del: 18: 7879807788
2019/10/03 07:16:14 [debug] 21#21: *1762 http upstream request: "/api/chat/connect?token=6cdcf634-2440-428f-a8bf-f0e28675b2e4"
2019/10/03 07:16:14 [debug] 21#21: *1762 http upstream process upgraded, fu:1
2019/10/03 07:16:14 [info] 21#21: *1762 upstream timed out (110: Operation timed out) while proxying upgraded connection, client: 127.0.0.1, server: mydomain.com, request: "GET /api/chat/connect?token=6cdcf634-2440-428f-a8bf-f0e28675b2e4 HTTP/1.1", upstream: "http://10.244.2.220:80/api/chat/connect?token=6cdcf634-2440-428f-a8bf-f0e28675b2e4", host: "mydomain.com"
2019/10/03 07:16:14 [debug] 21#21: *1762 finalize http upstream request: 504
2019/10/03 07:16:14 [debug] 21#21: *1762 finalize http proxy request
2019/10/03 07:16:14 [debug] 21#21: *1762 free rr peer 2 0
2019/10/03 07:16:14 [debug] 21#21: *1762 close http upstream connection: 18
2019/10/03 07:16:14 [debug] 21#21: *1762 free: 000055F9725C7920, unused: 48
```

... but I'm not sure what to look for in terms of the ping-pong messages, nothing stands out to me, is there a correlation id for the connection or something I can search by? What should I be looking for to verify those messages? I know for sure they are being sent/received ok as my app is logging the pong response, but in terms of the nginx logs what should I look for?

**Comment by pleshakov** [comment]
@Archanian 
>  is there a correlation id for the connection or something I can search by

Yep. For example, in the logs you shared, the ID is `*1762`. 

> What should I be looking for to verify those messages?

If ping pong messages are going through a connection, you should be able to see the entries in the debug log like this one :
```
2019/10/03 22:27:52 [debug] 15850#15850: epoll: fd:12 ev:0005 d:00007F01778912F8
2019/10/03 22:27:52 [debug] 15850#15850: *33 http run request: "/?"
2019/10/03 22:27:52 [debug] 15850#15850: *33 http upstream process upgraded, fu:0
2019/10/03 22:27:52 [debug] 15850#15850: *33 recv: eof:0, avail:1
2019/10/03 22:27:52 [debug] 15850#15850: *33 recv: fd:12 6 of 4096
2019/10/03 22:27:52 [debug] 15850#15850: *33 send: fd:13 6 of 6
2019/10/03 22:27:52 [debug] 15850#15850: *33 event timer: 13, old: 41274385, new: 41274385
2019/10/03 22:27:52 [debug] 15850#15850: *33 http run request: "/?"
2019/10/03 22:27:52 [debug] 15850#15850: *33 http upstream process upgraded, fu:1
2019/10/03 22:27:52 [debug] 15850#15850: *33 event timer: 13, old: 41274385, new: 41274385
2019/10/03 22:27:52 [debug] 15850#15850: timer delta: 0
2019/10/03 22:27:52 [debug] 15850#15850: worker cycle
2019/10/03 22:27:52 [debug] 15850#15850: epoll timer: 10000
```
Note the `send` and `recv` lines.

**Comment by lazee** [comment]
Hi, we're having the same issue. Any updates?

**Comment by pleshakov** [comment]
@lazee 
could you possibly verify that the ping pong messages are going through the connection? Please take a look at https://github.com/nginxinc/kubernetes-ingress/issues/715#issuecomment-537269011
