### ISSUE TITLE
SSL Passthrough

### ISSUE THREAD

**Issue by Semmix** [nginxinc/kubernetes-ingress#718]
We have been using nginx-ingress helm chart for a while, until recently we decided to purchase an nginx-plus license for it's Key-Val store.

When transitioning between charts, we noticed the `nginxinc/kubernetes-ingress` chart doesnt allow for [SSL Passthrough](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#ssl-passthrough) like nginx-ingress does.

We would like to add the capabilities missing via a PR if it is not possible to do so using the current configuration.

**Comment by pleshakov** [comment]
@Semmix 
At this point, our Ingress Controller doesn't offer SSL passthrough functionality. 

Longer-term, we'd like to support SSL passthrough via our  [Custom resources](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/virtualserver-and-virtualserverroute.md).

Short term, I think we can come up with a reasonable workaround -- a solution based on [custom templates](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/custom-templates) and [custom annotations](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/custom-annotations.md).

Could you possibly clarify the following requirements? This will help us prepare a workaround solution:
(1) Are you planning to use simultaneously SSL passthrough and Ingress resources with TLS termination?
(2) Do you need to use [PROXY protocol](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/proxy-protocol) for connections to NGINX ?
(3) What would be preferable? (a) SSL passthrough configuration is defined in one Ingress resource for all hosts or  (b) in multiple Ingress resources, each one configuring only one host?

Thanks

**Comment by Semmix** [comment]
1. Yes, i would like to apply ssl passthrough to certain services, and to other terminate via nginx.

2. Yes, some ingress resources will use proxy protocol.

3. I believe option a. Is preferable.
Something similiar to the way nginx-ingress treats the ssl-passthrough annotation.

Thanks for the quick response, appreciated.

**Comment by Semmix** [comment]
@pleshakov hey michael, was wondering if you were planning to offer a viable "short-term" solution, or was that just for the purpose of clarification.

Thanks either way :)

**Comment by pleshakov** [comment]
@Semmix 
we're investigating a workaround currently. we'll let you know the results shortly

**Comment by pleshakov** [comment]
@Semmix I created a gist with a workaround. Please see https://gist.github.com/pleshakov/d97a01cf15d9bb4c1c17decf8e3f7dee The approach is similar to this example -- https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/tcp-udp Unfortunately, we can't use Ingress resources to drive passthrough configuration, so we need to use the ConfigMap.

**Comment by Dean-Coakley** [comment]
SSL Passthrough is available in the 1.7.0 release: https://github.com/nginxinc/kubernetes-ingress/releases/tag/v1.7.0
