### ISSUE TITLE
Issue with Kubernetes on bare metal

### ISSUE THREAD

**Issue by gaord** [nginxinc/kubernetes-ingress#72]
Hi,

I have kubernetes cluster running on bare metal. I wonder if this supports bare metal deployment. In my case, the node running ingress controller doesn't have any extenalIP. I tried accessing the tea/coffee by the node physical network IP that is routable outside K8S cluster as instructed in example page, can't get through it anyway. What should I do to make this work in the case?

Thanks
Ben

**Comment by TheTechNick** [comment]
Hi,
we are running this ingress controller on bare metal as a daemon-set binding to ports 80 and 443 and it works just fine.
If you have a multi node cluster and have the replication controller example (https://github.com/nginxinc/kubernetes-ingress/blob/master/examples/complete-example/nginx-ingress-rc.yaml) running, it may be that the ingress controller is scheduled on another host. To expose the nginx ingress controller on every machine you need to use either a Daemon-Set or use a service with "nodePort".

**Comment by pleshakov** [comment]
@gaord 
The Ingress controller supports bare-metal deployments. 

I agree with @TheTechNick . Make sure you're making a request to the correct node. 

Additionally, 
What error are you getting when you're making a request to the controller?
Can you access the tea or coffee service from the node where the controller is running?

If you cannot, I suggest to enable extensive logging in the Ingress controller by uncommenting [lines 27-28](https://github.com/nginxinc/kubernetes-ingress/blob/master/examples/complete-example/nginx-ingress-rc.yaml#L27-L28) and check the logs to see if there are any errors.

**Comment by gaord** [comment]
@pleshakov @TheTechNick Thanks for your help on this. It turns out to be issues of hostPort in case of cni integration. With CNI as network layer, the hostPort doesn't work in kubernetes. I use hostNetwork  for the ingress container to get around it. It would be good to have hostPort work anyway. But for this ingress controller, it just works fine itsself in the end. 

See the following link for the CNI issue discussion at your convenience.

[https://github.com/kubernetes/kubernetes/issues/23920](url)

**Comment by pleshakov** [comment]
Great. Thanks for the link!
