### ISSUE TITLE
Allow nginx-health path to be configurable

### ISSUE THREAD

**Issue by warmfusion** [nginxinc/kubernetes-ingress#721]
**Is your feature request related to a problem? Please describe.**
as per https://github.com/nginxinc/kubernetes-ingress/issues/90 a healthcheck endpoint can be requested on the controller, however the path is hardcoded as `/nginx-health`. This means that in an environment using multiple ingress controllers or different balancers any monitoring systems have to have different paths for different endpoints.

**Describe the solution you'd like**
I'd like to be able to specify the health-check path through annotation (as suggested on https://github.com/nginxinc/kubernetes-ingress/issues/90) so that I can choose my own endpoint and make it consistent across our ecosystem of different balancer tools.

**Describe alternatives you've considered**
- Patching the code directly and forking my own ingress controller
- Switching to a totally different ingress controller
- Forcing all my other (non-nginx) balancers to use the `nginx-health` as a status path

**Comment by Rulox** [comment]
Hi @warmfusion thanks for the proposal.

That's actually a valid use case, we'll discuss this internally and will get back to you with a response as soon as possible.

Thanks!

**Comment by pleshakov** [comment]
@warmfusion 
thanks for the proposal. it makes sense to be able to customize the health check path.

In the meantime, as a workaround, you can use a custom template with the location for the health check changed to the required one:
```
        {{if .HealthStatus}}
        location /standard-health-endpoint {
            default_type text/plain;
            return 200 "healthy\n";
        }
        {{end}}
```
Please see [custom templates](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/custom-templates).
