### ISSUE TITLE
nginx user 101 can t create directories , permission denied 

### ISSUE THREAD

**Issue by itninja-hue** [nginxinc/kubernetes-ingress#723]
**Describe the bug**
user 101 #nginx couldn't create a temp file for the file /etc/nginx/secrets/default: open /etc/nginx/secrets/default191091540: permission denied.

**To Reproduce**
1. Follow installation steps of release-1.5

**Expected behavior**
Nginx user can create needed directories .

Run directories creation in protected directories as root.
 
**Your environment**
* Version of the Ingress Controller - 1.5
* Version of Kubernetes 1.12
* Kubernetes platform : baremetal (the hard way) 

**Additional context**
release 1.14 is working perfectly.

**Comment by mbecker** [comment]
Hi,

Same with ICP (IBM Cloud Private).

**Comment by Dean-Coakley** [comment]
Hi,

I've been able to reproduce this issue.

This issue occurs for me when I deploy the `latest` manifests with the `1.5` release.

Please ensure you use the relevant manifests in:
https://github.com/nginxinc/kubernetes-ingress/tree/release-1.5/deployments
rather than:
https://github.com/nginxinc/kubernetes-ingress/tree/master/deployments/

Hope this helps!

**Comment by mbecker** [comment]
Hi @Dean-Coakley ,

so the only difference is that the securityContext was added as seen here:
[https://github.com/nginxinc/kubernetes-ingress/commit/6b6ca410cd1e1bd4a24f0607cab1ffb0f7869ad3#diff-b0e37578050bb0db625a7d269e75c065](https://github.com/nginxinc/kubernetes-ingress/commit/6b6ca410cd1e1bd4a24f0607cab1ffb0f7869ad3#diff-b0e37578050bb0db625a7d269e75c065)

Besides taht I do not see any changes for the deployment script at all. Is that correct?

Thanks for your help!

**Comment by Dean-Coakley** [comment]
Hi @mbecker 

Yes, `securityContext` is the only change to manifests. This change was applied to make the ingress controller run as non-root. However, the ingress controller will not run if you pull the `1.5` release image as it does not include the rest of the required changes.

Release manifests are tied to a specific release so please use the manifests at:
https://github.com/nginxinc/kubernetes-ingress/tree/release-1.5/deployments

**Comment by pleshakov** [comment]
each release is tagged. The manifests for the latest stable release are available via  [`v1.5.6`](https://github.com/nginxinc/kubernetes-ingress/tree/v1.5.6) tag.

**Comment by itninja-hue** [comment]
@Dean-Coakley  as of kubernetes 1.16 extensions/v1beta1 is deprecated,  change it to apps/v1 .
you can read more about changes at https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ .

**Comment by pleshakov** [comment]
@itninja-hue thanks!

we updated the manifests to `apps/v1 ` in the master branch. The next major release later this year will include those updates.

**Comment by Dean-Coakley** [comment]
@mbecker Have you been able to resolve your issue?

Can this issue be closed?

**Comment by Dean-Coakley** [comment]
@mbecker 

Ok, so:

If you build your image from master, use the manifests on master.
https://github.com/nginxinc/kubernetes-ingress/tree/master/deployments

If you build your image from `release-1.5` branch, use the manifests located on that branch.
https://github.com/nginxinc/kubernetes-ingress/tree/release-1.5/deployments

Both the image and the manifests are versioned. If one doesn't match the other, the pod won't start.
**Note:** Master/edge is not recommended for production use.


> Besides that the running "nginx plus container" is creating weird configs for upstream.

Perhaps you can share an example, or describe why this is problematic?

**Comment by mbecker** [comment]
Hi @Dean-Coakley ,

so tested it again as follows:

(1) Build image from master; used manifest from master -> Still the original issue reported
(2a) Build image from master; used manifest from release 1.5.6 -> Works as reported (at least it's deployed and running)
(2b) Build image from release 1.5.6; used manifest from release 1.5.6 -> Not yet tested (Should I test it?)

Form the deployment (2a) I see the following nginx config for Ingress ressources as follows:
```bash
root@nginx-ingress-6chdb:/# cat /etc/nginx/conf.d/core-logging-ingress.conf | grep "proxy_pass"
        proxy_pass http://core-logging-ingress-logging.dpccp-dev.rz.aareon.com-logging-service-servicehttpport;
```

("core-logging" is the name of the Ingress ressource)

I would say the FQDN for the service is not correct; that's why no Ingress resource / deployment is working.

**Comment by pleshakov** [comment]
@mbecker 
>  Build image from release 1.5.6; used manifest from release 1.5.6 -> Not yet tested (Should I test it?)

this is the recommended option. For production use, we recommend using the latest stable release (currently, 1.5.6). Please see https://github.com/nginxinc/kubernetes-ingress/#nginx-ingress-controller-releases

> Form the deployment (2a) I see the following nginx config for Ingress ressources as follows:

Could you possibly provide more details about the problem with upstreams: Ingress and service resources, IC logs and steps to reproduce the problem? This will help us to solve the issue.

**Comment by Dean-Coakley** [comment]
Closing issue. Resolved as an error that occurs when there is a mismatch between manifests and deployed images.

For any further issues feel free to open a new issue!
