### ISSUE TITLE
Nginx Cache key per Location block through Ingress 

### ISSUE THREAD

**Issue by prakharjoshi** [nginxinc/kubernetes-ingress#733]
**Is your feature request related to a problem? Please describe.**
If we define multiple paths in an Ingress it creates multiple location blocks in a single server block which is perfect but our use case is we need separate cache key per location block and it seems like we can configure caching keys using ingress annotations which will be same for both the location blocks. We should allow configuring different cache keys based on location blocks.

**Describe the solution you'd like**
It will be great if we can define Nginx directive at location level because with annotations it will be same for all the locations block created through that Ingress. Location level directives should we configurable per location block. We can allow annotations per location block maybe?

**Describe alternatives you've considered**
We tried to update the custom template to achieve this by adding a custom annotation which is sort of map with key as path and value is cache_key for that path. This becomes a bit complex as we have to keep track of updating map when a new path is added and increases the complexity.

**Comment by Rulox** [comment]
Hi @prakharjoshi 

What about using [Mergeable Ingress Resources](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/mergeable-ingress-types#mergeable-ingress-types-support)?

You will be able to specify 1 different Ingress Resource per path, and you can use different annotations in each of the resources.

Let me know if that would solve your issue or you still need more assistance. 

Thanks!
