### ISSUE TITLE
Significant latency increase  when using ingress controller

### ISSUE THREAD

**Issue by jeanluclariviere** [nginxinc/kubernetes-ingress#756]
**Describe the bug**
We are performing load tests against our application and are experiencing significant latency when going through the nginx ingress controller. When using 1000 concurrent threads in jmeter and hammering our service using nodeports, the average latency is only around 4-7ms, but this skyrockets to 300-400ms when we go through the ingress controller.

**Expected behavior**
Although we are expecting to see a slight latency increase because we're leveraging TLS with the ingress controller, the increase we're seeing is just too high and we believe something is not configured correctly.

**Your environment**
* Version of the Ingress Controller - release version or a specific commit
nginx-ingress:1.5.3

* Version of Kubernetes
1.14.8

* Kubernetes platform (e.g. Mini-kube or GCP)
Bare-metal

* Using NGINX or NGINX Plus
NGINX

**Additional context**
We've attempted to optimize our nginx configmap for higher throughput, which seems to have helped a little, but not enough. We do see an error however when the controller attempts to set the worker-rlimit-nofile to 102400, "2019/11/08 15:34:48 [alert] 79#79: setrlimit(RLIMIT_NOFILE, 102400) failed (1: Operation not permitted)"

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  error-log-level: "notice"
  worker-process: "auto"
  worker-connections: "100000"
  worker-rlimit-nofile: "102400"
  keepalive-timeout:  "315s"
  keepalive-requests: "10000000"
  keepalive: "200"
```

**Comment by pleshakov** [comment]
@jeanluclariviere 
To help us better understand problem, could you possibly answer the following questions?

1. How is the NGINX Ingress Controller exposed to the JMeter? NodePort? Service?
2. How many IC pods do you have running?
3. Do you see any other problems/error in the IC logs?
4. Could you possibly share the generated config - the main config and the config for your Ingress resources? https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/troubleshooting.md#checking-the-generated-config


Additionally: 
*  `worker-rlimit-nofile to 102400, "2019/11/08 15:34:48 [alert] 79#79: setrlimit(RLIMIT_NOFILE, 102400) failed (1: Operation not permitted)"`  This means that NGINX hits the limit of your node.  It is necessary to increase  `sys.fs.file-max` limit on the node.
* Could you extend the access log to include the following variables (`$request_time`, `$upstream_connect_time`, `$upstream_header_time`, `$upstream_response_time` and see in the logs how quickly or slow the upstreams respond? see also https://www.nginx.com/blog/using-nginx-logging-for-application-performance-monitoring/  and https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/configmap-and-annotations.md#logging

**Comment by jeanluclariviere** [comment]
@pleshakov
Thanks for your response, here are some answers to your questions:

1. How is the NGINX Ingress Controller exposed to the JMeter? NodePort? Service?
We've deployed the daemonset using host ports 80 and 443.

2. How many IC pods do you have running?
We have 3 IC pods, one running on each of the workers in our cluster.

3. Do you see any other problems/error in the IC logs?
We've run our tests with debug logging and have not seen any errors in the IC logs, only an increase in latency regarding the overall length of the connection.

4. Could you possibly share the generated config - the main config and the config for your Ingress resources? https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/troubleshooting.md#checking-the-generated-config

```
user  nginx;
worker_processes  auto;
worker_rlimit_nofile 102400;
daemon off;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  100000;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';


    access_log  /var/log/nginx/access.log  main;


    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout 315s;
    keepalive_requests 10000000;

    #gzip  on;

    server_names_hash_max_size 512;


    variables_hash_bucket_size 256;
    variables_hash_max_size 1024;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }





    server {
        listen 80 default_server;
        listen 443 ssl default_server;

        ssl_certificate /etc/nginx/secrets/default;
        ssl_certificate_key /etc/nginx/secrets/default;

        server_name _;
        server_tokens "on";
        access_log off;



        location / {
           return 404;
        }
    }
    # stub_status
    server {
        listen 8080;

        allow 127.0.0.1;
        deny all;
        location /stub_status {
            stub_status;
        }
    }

    include /etc/nginx/config-version.conf;
    include /etc/nginx/conf.d/*.conf;

    server {
        listen unix:/var/run/nginx-502-server.sock;
        access_log off;

        location / {
            return 502;
        }
    }
}

stream {
    log_format  stream-main  '$remote_addr [$time_local] '
                      '$protocol $status $bytes_sent $bytes_received '
                      '$session_time';

    access_log  /var/log/nginx/stream-access.log  stream-main;


}
```

For setting the additional logging, how i only have to set the configmap key as follows?

```
data:
  log-format: log_format apm '"$time_local" client=$remote_addr '
               'method=$request_method request="$request" '
               'request_length=$request_length '
               'status=$status bytes_sent=$bytes_sent '
               'body_bytes_sent=$body_bytes_sent '
               'referer=$http_referer '
               'user_agent="$http_user_agent" '
               'upstream_addr=$upstream_addr '
               'upstream_status=$upstream_status '
               'request_time=$request_time '
               'upstream_response_time=$upstream_response_time '
               'upstream_connect_time=$upstream_connect_time '
               'upstream_header_time=$upstream_header_time';
```

I feel this isn't correct, so would I instead have to update the template file? How can this be done?
---

Now i don't want to mix up two issues in one, but regarding sys.fs.file-max, the max currently set on those machines currently is "2424275",  so i'm not at all sure why setting "102400" for the worker-rlimit-nofile would cause a problem.

**Comment by pleshakov** [comment]
@jeanluclariviere 
Thanks for sharing additional details. 

> We've deployed the daemonset using host ports 80 and 443.

does the JMeter send requests to only one node or multiple?

> For setting the additional logging, how i only have to set the configmap key as follows?

Please use the following snippet as an example of configuring log format:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  log-format: '"$time_local" client=$remote_addr upstream_response_time=$upstream_response_time upstream_connect_time=$upstream_connect_time  upstream_header_time=$upstream_header_time'
```

> Now i don't want to mix up two issues in one, but regarding sys.fs.file-max, the max currently set on those machines currently is "2424275", so i'm not at all sure why setting "102400" for the worker-rlimit-nofile would cause a problem.

The docker daemon can also set limits on the NGINX processes. You can check the limits by running `$ cat /proc/<pid of nginx process>/limits` You can change those limits by reconfiguring the docker daemon. If you run it with systemd,  you can change `LimitNOFILE` in the `/usr/lib/systemd/system/docker.service` file

Could you also possibly share the generated file that correspond to the Ingress resource?

**Comment by jeanluclariviere** [comment]
> does the JMeter send requests to only one node or multiple?
We're load balancing traffic via an F5 to all 3 worker nodes, we can see traffic on each of the IC pods.

After updating the log format, I re-ran my test and have cropped our IC logs for each of the three pods and attached them. The results are certainly interesting! 

When running our jmeter load, the average response time ****when bypassing the the IC** was around 7ms. Now I have re-run the same test but going through the IC, and looking at the logs for each pod, we can observe an identical average upstream_response_time to our application. Jmeter however tells us that the average response time has jumped up to ~300-400ms. To me this would indicate that the issue lies between nginx and jmeter, as the response times are identical within the Kubernetes cluster regardless of whether nginx is used or not.

My concern here is that the final response back to the client (jmeter in this case) appears to be much slower when going through the IC, any thoughts on how we might address this?

[IC-pod3.log](https://github.com/nginxinc/kubernetes-ingress/files/3847183/IC-pod3.log)
[IC-pod1.log](https://github.com/nginxinc/kubernetes-ingress/files/3847184/IC-pod1.log)
[IC-pod2.log](https://github.com/nginxinc/kubernetes-ingress/files/3847185/IC-pod2.log)

And here is the ingress rule we created to hit the service - might be some typos, i've omitted sensitive info.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{},"name":"example-ingress","namespace":"example"},"spec":{"rules":[{"host":"example.com","http":{"paths":[{"backend":{"serviceName":"example-service","servicePort":4567},"path":"/"}]}}],"tls":[{"hosts":["example.com"],"secretName":"example-cert"}]}}
  creationTimestamp: "2019-08-29T13:21:12Z"
  generation: 3
  name: example-ingress
  namespace: example
  resourceVersion: "11769558"
  selfLink: /apis/extensions/v1beta1/namespaces/example/ingresses/example-ingress
  uid: df26b884-ca5f-11e9-9f62-0050568d82d7
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: example-service
          servicePort: 4567
        path: /
  tls:
  - hosts:
    - example.com
    secretName: example-cert
status:
  loadBalancer: {}
```

**Comment by pleshakov** [comment]
@jeanluclariviere 

thanks for providing additional details.

> We're load balancing traffic via an F5 to all 3 worker nodes, we can see traffic on each of the IC pods
> My concern here is that the final response back to the client (jmeter in this case) appears to be much slower when going through the IC, any thoughts on how we might address this?

Is F5 configured as a TCP load balancer? Does F5 load balance among the nodes on the 80,443 ports on which the IC pods are mapped?

One optimization you can make is to add `hostNetwork: true` to the pod template of nginx-ingress so that NGINX binds directly to nodes interfaces without port mapping.

One other handy metric you can capture in the logs is `$request_time`, which shows Full request time, starting when NGINX reads the first byte from the client and ending when NGINX sends the last byte of the response body.

**Comment by jeanluclariviere** [comment]
> Is F5 configured as a TCP load balancer? Does F5 load balance among the nodes on the 80,443 ports on which the IC pods are mapped?
Yes, TCP load balancer and we are load balancing ports 80 and 443 to each of the worker nodes.

> One optimization you can make is to add hostNetwork: true to the pod template of nginx-ingress so that NGINX binds directly to nodes interfaces without port mapping.

We are using the nginx IC daemonset which already exposes the hostPort 80 and 443, so would that make any difference?

**Comment by pleshakov** [comment]
> We are using the nginx IC daemonset which already exposes the hostPort 80 and 443, so would that make any difference?

Yep, it is a performance optimization. Please also see https://docs.docker.com/network/host/

**Comment by jeanluclariviere** [comment]
thanks @pleshakov, i made this change and refreshed the pods, we are still seeing the high latency, averaging around 300-400ms when running the load tests w/jmeter.

**Comment by jeanluclariviere** [comment]
@pleshakov  just wanted to see if there was anything else you thought might help? We're going to try and improve the performance at the F5 LB level this week by switching to fastl4 instead of the standard TCP, i'll update this post on our findings if this does help resolve the issues were facing.

**Comment by pleshakov** [comment]
@jeanluclariviere thanks for the update! sorry, for a little delay.
Unfortunately, I don't have any concrete ideas that might help.

**Comment by jeanluclariviere** [comment]
Just wanted to add an update that fast layer 4 settings on the LB didn't help this issue unfortunately.

**Comment by Mohit-Hurkat** [comment]
Did any particular change/workaround resolve the significant latency issue ??

**Comment by romanvog** [comment]
Experiencing the same latency increase, can we reopen this issue?

**Comment by brianehlert** [comment]
Can you please open an issue or discussion and detail your situation.
