### ISSUE TITLE
Presented with default invalid cert for valid ingress rule using TLS

### ISSUE THREAD

**Issue by jeanluclariviere** [nginxinc/kubernetes-ingress#760]
**Describe the bug**
After creating an nginx IC ingress rule for one of our services, if we try to access the site the service is hosting for the first time via a browser, we are presented with the nginx default (invalid) certificate and are unable to proceed. However, if we wait a few minutes and refresh the page, the proper TLS certificate (which we configured in the ingress rule) appears and we can continue to access the site normally.

**Expected behavior**
Since the ingress rule we created is valid, we expect to be able to access to the service immediately, without being presented the default nginx IC certificate. It was my understanding that this certificate is presented in the event of an "error 404, page not found", but the ingress rule is functioning normally, because if we wait and refresh, everything works just fine.

**Your environment**
* Version of the Ingress Controller - release version or a specific commit
1.5.3

* Version of Kubernetes
1.14.8

* Kubernetes platform (e.g. Mini-kube or GCP)
bare-metal

* Using NGINX or NGINX Plus
NGINX

**Other**
We plan on implementing a valid signed cert to address the invalid cert error we're getting, but we shouldn't be getting this in the first place, so we're not sure where we're going wrong.

**Comment by pleshakov** [comment]
@jeanluclariviere 
The behavior you got is expected *if* you deploy an Ingress resource with TLS termination configured, but the referenced secret doesn't exist in the cluster yet. Once the secret is deployed, NGINX Ingress Controller will pick it up and you will be able to access the URL normally.

Was it the case for you?

**Comment by jeanluclariviere** [comment]
> @jeanluclariviere
> The behavior you got is expected _if_ you deploy an Ingress resource with TLS termination configured, but the referenced secret doesn't exist in the cluster yet. Once the secret is deployed, NGINX Ingress Controller will pick it up and you will be able to access the URL normally.
> 
> Was it the case for you?

@pleshakov 
Hi Michael,
This is not the case. We have deployed the ingress resource with TLS termintation configured AND the referenced secret does exist. As i stated in the initial issue, we are presented the invalid certificate when attempting to access the site, and if we wait a few minutes and refresh the page, we stop seeing this error and the proper TLS certificate is presented. This is true for any user attempting to access the page, and is true of any new sessions being made to the site. While this is happening, we aren't touching the ingress resource, it's as if there is a delay, and the ingress resource doesn't see the service endpoints and / or the referenced secret immediately.

Jean Luc

**Comment by jeanluclariviere** [comment]
Found the problem, this was configuration related. We were load balancing between two clusters and the ingress was misconfigured on one of the clusters, sorry for the trouble and thanks for the help.

**Comment by pleshakov** [comment]
@jeanluclariviere np! glad you found the problem.
