### ISSUE TITLE
Run Ingress as non root

### ISSUE THREAD

**Issue by dhatri308** [nginxinc/kubernetes-ingress#762]
**Describe the bug**
We are currently using version v1.4.6. We want to run ingress as non root . runAsUser: 33/101 but these users have issue with permissions to etc/nginx. 

**To Reproduce**
1. Deploy v1.4.6 daemon set 
2. In pod definition, have runAsUser: 33/101 in container SecurityContext
3. In pod logs, we see **"nginx.go:248] Couldn't create a temp file for the secret file default: open /etc/nginx/secrets/default664345291: permission denied"**

**Expected behavior**
Ingress controller starts fine

**Your environment**
* Version of the Ingress Controller - v1.4.6
* Version of Kubernetes - 1.11
* Using NGINX

**Additional context**
We did try adding a shell script and override permissions of /etc/nginx but only owner/root can do this. So the operation cannot be performed. Please suggest.

**Comment by pleshakov** [comment]
@dhatri308 
Unfortunately, it is not possible to run the IC with non-root user in release 1.4.* and release 1.5.*

we recently added support for non-root user in the master branch (https://github.com/nginxinc/kubernetes-ingress/pull/710) and it is available in the IC [edge](https://github.com/nginxinc/kubernetes-ingress/#nginx-ingress-controller-releases) version. 

We will include that feature in 1.6.0 release, which we plan for the first half of December.

**Comment by dhatri308** [comment]
@pleshakov Thanks for your quick response. As far as I know, edge version is not recommended for production use right ?
