### ISSUE TITLE
helm install validation failed

### ISSUE THREAD

**Issue by andrewm41** [nginxinc/kubernetes-ingress#763]
Trying install nginxinc kubernetes-ingress via helm as written in readme on bare-metal Kubernetes and get this error:

```
[root@hostname /usr/local/src/kubernetes-ingress/deployments/helm-chart]# git status
# HEAD detached at v1.5.7
nothing to commit, working directory clean
[root@hostname /usr/local/src/kubernetes-ingress/deployments/helm-chart]# helm install --name my-release .
Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
```
Kubernetes version is 1.16.2

**Comment by Dean-Coakley** [comment]
Hi @andrewm41 

The 1.5 release does not support Kubernetes 1.16.

We did not update the manifests of 1.5 as 1.6 IC release is expected to be released in the first half of December.

So you can either: 
* Wait for the 1.6 release
* Use the edge version
* Make the simple edit of [daemonset manifest template](https://github.com/nginxinc/kubernetes-ingress/blob/release-1.5/deployments/helm-chart/templates/controller-daemonset.yaml#L2) and/or [deployment manifest template](https://github.com/nginxinc/kubernetes-ingress/blob/release-1.5/deployments/helm-chart/templates/controller-deployment.yaml#L2) to use `apps/v1`

**Comment by Dean-Coakley** [comment]
@andrewm41 

The 1.6 release was delayed due to circumstances outside of our control. I pushed a new `v1.5.8` release which includes Kubernetes 1.16 support.

Enjoy! :)
