### ISSUE TITLE
 Ingress Controller Command-line Arguments,  can you help me 

### ISSUE THREAD

**Issue by 3tem** [nginxinc/kubernetes-ingress#767]
i find this  article :
https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/cli-arguments.md
i use helm  deploy ,but my pod in not start, see the  log  and this article is very like，I want to know why and how to deal with him

 -alsologtostderr
        log to standard error as well as files
  -default-server-tls-secret string
        A Secret with a TLS certificate and key for TLS termination of the default server. Format: <namespace>/<name>.
                If not set, certificate and key in the file "/etc/nginx/secrets/default" are used. If a secret is set,
                but the Ingress controller is not able to fetch it from Kubernetes API or a secret is not set and
                the file "/etc/nginx/secrets/default" does not exist, the Ingress controller will fail to start

**Comment by 3tem** [comment]
ok，I have found the problem ，i user the master helm but the images is version 1.5.7 ,replace 1.5.7 helm is ok

**Comment by Dean-Coakley** [comment]
Good to hear you were able to resolve your issue. :)
