### ISSUE TITLE
How to disable default proxy_set_header (X-Real-IP)?

### ISSUE THREAD

**Issue by andrewm41** [nginxinc/kubernetes-ingress#769]
These "proxy_set_header ..." rules seem hardcoded in location sections
but I need to disable 
```proxy_set_header X-Real-IP $remote_addr;```
as it is already passed by upstream before ingress, is there any way I can do it?

**Comment by Rulox** [comment]
Hi @andrewm41 

The `X-Real-IP` header normally is the IP of the last peer that sent the request to the current server. This means, if you have a `client` <> `load balancer` <> `server` and you inspect that header in your server, it would be the IP of the load balancer, not the client.

Wouldn't `X-Forwarded-For` be sufficient to check the client IP Address? Or what are you trying to achieve with this?

However, if you would still like to remove it, you can use [custom templates ](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/custom-templates) to create your own template removing that directive. In particular, it would be the `ingress-template` key in your ConfigMap.

Thanks

**Comment by andrewm41** [comment]
I should read docs carefully.
Custom template via ConfigMap is exactly what I need.
Thank you.
