### ISSUE TITLE
Nginx ingress doesnt work with ELB when configuring UDP ports

### ISSUE THREAD

**Issue by rsingh2411** [nginxinc/kubernetes-ingress#776]
**Describe the bug**
As per following example, tried following steps, the load balancer is not getting created,
https://github.com/nginxinc/kubernetes-ingress/tree/v1.5.7/examples/tcp-udp
` following error is seen
Error creating load balancer (will retry): failed to ensure load balancer for service nginx-ingress/nginx-ingress: Only TCP LoadBalancer is supported for AWS ELB
`

**To Reproduce**
https://github.com/nginxinc/kubernetes-ingress/tree/v1.5.7/examples/tcp-udp
1. created config map, 
`
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
    proxy-protocol: "True"
    real-ip-header: "proxy_protocol"
    set-real-ip-from: "0.0.0.0/0"
    stream-snippets: |
      upstream udptest-udp {
          server udptest.kube-system.svc.cluster.local:5005;
      }
      server {
          listen 5353 udp;
          proxy_pass udptest-udp;
          prooxy_responses 1;
      }

modified in deployment
 spec:
      serviceAccountName: nginx-ingress
      containers:
      - image: nginx/nginx-ingress:1.5.7
        name: nginx-ingress
        ports:
        - name: udp
          containerPort: 5353
          protocol: UDP
       #- name: prometheus
         #containerPort: 9113
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

creating load balancer
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
spec:
  type: LoadBalancer
  ports:
  - port: 5353
    targetPort: 5353
    protocol: UDP
    name: udp
  selector:
    app: nginx-ingress

Note: Tried this with nlb as well
`
**Expected behavior**
ELB should be created with udp ports also, Is the support needed from kubernetes side, or there is an open issue.

**Your environment**
* Version of the Ingress Controller - release version or a specific commit
* Version of Kubernetes 1.14
* Kubernetes platform (e.g. Mini-kube or GCP) AWS EKS
* Using NGINX

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by pleshakov** [comment]
Hi @rsingh2411 

Unfortunately, ELB doesn't support UDP protocol.

However, NLB supports UDP. An NLB load balancer could be provisioned if you use https://github.com/nginxinc/kubernetes-ingress/blob/master/deployments/service/loadbalancer.yaml Unfortunately, while NLB supports UDP, the protocol is not supported through a LoadBalancer Service yet.

Below are related issues:
* https://github.com/kubernetes/kubernetes/issues/79523
* https://github.com/kubernetes/kubernetes/pull/80394
