### ISSUE TITLE
Rewrite the URI of a request before sending it to the application for VirtualServer configuration

### ISSUE THREAD

**Issue by crossdot** [nginxinc/kubernetes-ingress#777]
Is there a way to rewrite the URI of a request if use kind: VirtualServer?
Something like nginx.org/rewrites works for kind: Ingress

**Comment by Rulox** [comment]
Hi @crossdot 

Currently it is not possible to use `rewrite` in VirtualServers. We're working to keep adding features to our CRDs (VS and VSR) and this is a good use case/feature for it. It will take some time to have all of the features from annotations into our CRDs, but they will be there (and more!)

We'll use this issue to keep track of this, thanks for your suggestion.

**Comment by choldrim** [comment]
LGTM, it is a real good feature for us as well. In some cases, like multi not-related backends are forwarded by one domain, and use different paths to forward the traffic, and the backends don't want to know what the prefix paths are. It would be helpful in this case.

And any progress for this feature?

**Comment by LorcanMcVeigh** [comment]
This was implemented [here](https://github.com/nginxinc/kubernetes-ingress/commit/9bc383caa142cf192b244dc9be65147ff59bb022) as `rewritePath`
