### ISSUE TITLE
Ingress Controller Always Returns 404 Not Found with VirtualServer Configuration

### ISSUE THREAD

**Issue by vichetsen** [nginxinc/kubernetes-ingress#784]
**Describe the bug**
I configured VirtualServer as described in document below, however ingress controller always returns 404 Not Found and not routing to upstream service.

**To Reproduce**
1. Follow installation at this url: https://github.com/nginxinc/kubernetes-ingress/tree/release-1.5/examples-of-custom-resources/basic-configuration
2. Test the virtual server setup with curl or using browser
3. Ingress Controller returns 404 Not Found

**Expected behavior**
Successfully route to upstream services and return response.

**Your environment**
* Version of the Ingress Controller - v1.5.8
* Version of Kubernetes - 1.16.2
* Kubernetes platform - Digitalocean Managed Kubenetes
* Using NGINX 

**Additional context**
I setup all the components as described in the document. I attached my manifests here for your reference.
[ingress.zip](https://github.com/nginxinc/kubernetes-ingress/files/3938531/ingress.zip)

**Comment by pleshakov** [comment]
@vichetsen thanks for sharing the manifests. The VS looks goods.

Could you possibly provide an example of the curl command you used?  The curl command must supply the correct host header. For example:
```
$ curl <Ingress-Controller-IP> -H "host: test.ezplay.stream"
```
If the host header is not provided, you will get a 404 response from NGINX. I suspect that was a problem. Could you possibly confirm?

Also, slightly unrelated, but in your manifests I noticed that you added `nginx.org/...` annotations to the Service and ConfigMap resource. Please note that the IC only recognize annotations when they are added to Ingress resources.

**Comment by vichetsen** [comment]
Hello @pleshakov ,

I have use run the curl command as below:
`curl 206.189.144.19 -H "host: test.ezplay.stream"`

this is going to timeout as show below:
`curl: (7) Failed to connect to 206.189.144.19 port 80: Timed out`

Thank you about notice related to nginx.org/... annotations, so that means I cannot use with VirtualServer?

**Comment by pleshakov** [comment]
@vichetsen
the curl command looks correct! although when using `--resolve` option, specifying the host header is no longer necessary - the curl will set the correct header.
 
Could you possibly redeploy the IC with the argument `-v=3` (see also https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/cli-arguments.md), reproduce the problem  and share the logs with us?  this will help us pinpoint the issue.

**Comment by vichetsen** [comment]
I deployed the IC as demonset. I upload them here.

[demonset1.txt](https://github.com/nginxinc/kubernetes-ingress/files/3940331/demonset1.txt)
[demonset2.txt](https://github.com/nginxinc/kubernetes-ingress/files/3940332/demonset2.txt)

**Comment by pleshakov** [comment]
@vichetsen 
Thanks for the logs! I think I found the issue.

Since you're using 1.5.8 version of the Ingress Controller, please make sure that that you're using the deployment manifests from the v1.5.8 tag (https://github.com/nginxinc/kubernetes-ingress/tree/v1.5.8) as well as the documentation (https://github.com/nginxinc/kubernetes-ingress/tree/v1.5.8/docs) For example, in 1.5.8 version, the api version of the VirtualServer resource is `apiVersion: k8s.nginx.org/v1alpha1` not `apiVersion: k8s.nginx.org/v1`.

In your case you were using the manifests from the master branch, while the IC version was 1.5.8

Hope that helps!

**Comment by vichetsen** [comment]
@pleshakov I re-apply my manifests from the urls here:
- https://github.com/nginxinc/kubernetes-ingress/blob/v1.5.8/deployments/common/custom-resource-definitions.yaml
- https://github.com/nginxinc/kubernetes-ingress/blob/v1.5.8/deployments/daemon-set/nginx-ingress.yaml

I also changed api version of my virtual server to `apiVersion: k8s.nginx.org/v1alpha1`.
This is still 404 Not Found.

**Comment by pleshakov** [comment]
@vichetsen thanks for the descriptions again. helps a lot!  

Looking at the events of the VS resource, we can see that it was rejected.
```
Events:
  Type     Reason    Age                From                      Message
  ----     ------    ----               ----                      -------
  Warning  Rejected  12m (x3 over 19m)  nginx-ingress-controller  VirtualServer cdn/ezplay-stream is invalid and was rejected: spec.routes[0]: Invalid value: "": must specify exactly one of: `upstream`, `splits`, `rules` or `route`
  Warning  Rejected  12m (x3 over 19m)  nginx-ingress-controller  VirtualServer cdn/ezplay-stream is invalid and was rejected: spec.routes[0]: Invalid value: "": must specify exactly one of: `upstream`, `splits`, `rules` or `route`
```

In the normal event, you will have the events like below:
```
Events:
  Type    Reason          Age   From                      Message
  ----    ------          ----  ----                      -------
  Normal  AddedOrUpdated  16s   nginx-ingress-controller  Configuration for default/cafe was added or updated
```

While you changed the API version of the resource to `k8s.nginx.org/v1alpha1`, the spec wasn't updated. For `k8s.nginx.org/v1alpha1`, the spec should look like this:
```yaml
spec:
  host: test.ezplay.stream
  upstreams:
  - name: origin-home
    service: nginx-cache-service
    port: 80
  routes:
  - path: /
    upstream: origin-home
```

Note the with the update to `v1`, we also changed the spec to address its limitations.

Could you possibly update the spec of the VS accordingly with the snippet above?

**Comment by vichetsen** [comment]
@pleshakov Awesome, updating the spec solve my problem. Thank you a lot for your help.
