### ISSUE TITLE
Unable to deploy using deployment and service NodePort, but working with DaemonSet (without service)

### ISSUE THREAD

**Issue by Mr-Reca** [nginxinc/kubernetes-ingress#787]
**Describe the bug**
I need to deploy the IngressController using Deployment and Service (for Jenkins) on premise. When  I deploy the service using `daemon-set` works fine. But when I use `deployment `and `NodePort`, the Ingress doesn't work properly. Logs are not showing any info, so maybe the nginx config is generated the wrong way.

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone Repo
2. Add `- -wildcard-tls-secret=$(POD_NAMESPACE)/default-wildcard-secret` in `spec.args` at `deployment/nginx-ingress.yaml` (I'm using an internal cert as a wildcard).
3. Create the mentioned secret correctly.
4. Apply `ns-and-sa`, `default-server-secret`, `nginx-config`, `rbac`, `custom-resource-definitions`, `deployment/ngins-ingress.yaml` and `service/nodeport.yaml`
5. Create an Ingress sample that works when using daemonset
6. Receiving "network violation" in browser.

**Expected behaviour**
able to interact with the service that ingress sets.

**Your environment**
* Version of the Ingress Controller - latest in master
* Version of Kubernetes: 1.16.3
* Kubernetes platform (e.g. Mini-kube or GCP) on premise (KTHW)
* Using NGINX or NGINX Plus: NGINX

**Additional context**
I can send nginx.conf o logs if required, but they don't seem incorrect.

**Comment by pleshakov** [comment]
Hi @Mr-Reca 

thanks for the details! 

Could you possibly describe the error that you get in the browser?  If possibly, could you also try to use curl to send http quests to NGINX and see what error you're getting?

**Comment by Mr-Reca** [comment]
Hi @pleshakov 

thank you for your response and sorry for being late.

These are my steps to make a "clean install" of the IngressController using Deployment & Service:

```
kubectl delete ns nginx-ingress
kubectl delete clusterrole nginx-ingress
kubectl delete clusterrolebinding nginx-ingress
kubectl apply -f common/ns-and-sa.yaml -f common/default-server-secret.yaml -f common/nginx-config.yaml -f common/custom-resource-definitions.yaml -f rbac/rbac.yaml -f deployment/nginx-ingress.yaml -f service/nodeport.yaml
<script_to_create secret/default-wildcard-secret>
```

curl returns me this:
```
curl https://<my-site>
curl: (7) Failed to connect to <my-site> port 443: Connection refused
```

When using Firefox, the message is the following one:

```
Corrupted Content Error
The site at https://<my-site>/ has experienced a network protocol violation that cannot be repaired.

The page you are trying to view cannot be shown because an error in the data transmission was detected.

    Please contact the web site owners to inform them of this problem.
```

`secret/default-wildcard-secret` is located at namespace `nginx-ingress`. The Ingress is located in another namespace (the same namespace the Service I'm trying to reach). Can it be something related with SSL?

Thank you so much for your time,

**Comment by pleshakov** [comment]
@Mr-Reca 
My apologies for the late reply!

After a clean install, the curl command must have succeeded.  Are you using the correct IP addresses and ports in your command? 

An example of the correct curl command is here -- https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/complete-example#4-test-the-application Since you're using the NodePort service, make sure that `IC_IP` stores the IP address of one of the nodes of the cluster and `IC_HTTPS_PORT` stores the NodePort that corresponds to the HTTPs port of the nginx-ingress service.

> The Ingress is located in another namespace (the same namespace the Service I'm trying to reach). Can it be something related with SSL?

this should not affect the Ingress Controller - the [wildcard secret](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/wildcard-tls-certificate) can reside in a namespace different from the namespace where the Ingress resource exists.

**Comment by Mr-Reca** [comment]
Hi @pleshakov 
Sorry for my late response, I was o.o.o.

When I deploy the NodePort svc, I only have 1 pod available (I have a 2-node cluster), and I retrieve the port from the kubectl output.

when I run:
`curl --resolve <name>:$IC_HTTPS_PORT:$IC_IP https://<name>:$IC_HTTPS_PORT` I receive HTML content. This matches so much with this page: [https://gitea.io/en-us/]( https://gitea.io/en-us/)

**Comment by pleshakov** [comment]
@Mr-Reca is it unexpected response? is there a possibility that you're sending curl requests to a wrong NodePort?

**Comment by Mr-Reca** [comment]
Good morning,

This is the output of `kubectl get po,svc -n nginx-ingress -owide`

```
NAME                                 READY   STATUS    RESTARTS   AGE   IP               NODE     NOMINATED NODE   READINESS GATES
pod/nginx-ingress-6fcdbfc6df-pkp8g   1/1     Running   0          20s   192.168.34.219   node-0   <none>           <none>

NAME                    TYPE       CLUSTER-IP   EXTERNAL-IP   PORT(S)                      AGE   SELECTOR
service/nginx-ingress   NodePort   10.32.0.32   <none>        80:31694/TCP,443:30171/TCP   20s   app=nginx-ingress
```

So my curl command should be:
```
curl --resolve <hostname>:30171:<node-0-public-IP> https://<hostname>:30171
```

If I put the IP `192.168.34.219` (just for test) it returns me Connection refused to port 30171

**Comment by pleshakov** [comment]
@Mr-Reca  
> ```curl --resolve <hostname>:30171:<node-0-public-IP> https://<hostname>:30171```

this command looks correct

> If I put the IP 192.168.34.219 (just for test) it returns me Connection refused to port 30171

this is expected as nothing is listens on port 30171 in the IC container.

**Comment by Mr-Reca** [comment]
Is it possible that I need some additional configuration on the firewall on both machines? Like accept all traffic from master IP to node IP. Is there some configuration to add verbosity to nginx, so we can analyse what's really happening and if something is going wrong?

**Comment by pleshakov** [comment]
> Like accept all traffic from master IP to node IP. 

Not sure if this will help solve your issues

> Is there some configuration to add verbosity to nginx, so we can analyse what's really happening and if something is going wrong?

Yes, you control verbosity of NGINX logs https://docs.nginx.com/nginx-ingress-controller/logging-and-monitoring/logging/ 
By default, you will be able to see access logs? Could you confirm that your curl requests hits NGINX - can you see the corresponding log lines?

**Comment by Mr-Reca** [comment]
I'm running the deployment with the flag `v=3`. What I'm trying to deploy is Gitea using they official image from Docker Hub. Using Daemonset works fine, but using Deployment (event setting all pods on same machine) does not work. I also have another pods, which also are not working with this change when I try to reach them through an Ingress.

I can't see any line in NGINX logs showing some hit or request on the hostname... That's unusual

**Comment by pleshakov** [comment]
> I can't see any line in NGINX logs showing some hit or request on the hostname... That's unusual

could you possibly share the Ingress resource that you used? 
could you also share the curl commands that weren't successful and any reported errors?

**Comment by Mr-Reca** [comment]
If you mean the YAML of the Ingress, is this one:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: <gitea-ing>
  namespace: <ns>
  annotations:
    nginx.org/client-max-body-size: "0" #Now we can push to repo
spec:
  tls:
  - hosts:
    - <hostname>
    secretName: <gitea-tls>
  rules:
  - host: <hostname>
    http:
      paths:
      - path: /
        backend:
          serviceName: <gitea-svc>
          servicePort: <gitea-svc-port>
```

The only error log that I have is the "Corrupted content site" error that Firefox shows me and the connection refused of curl.

**Comment by pleshakov** [comment]
@Mr-Reca thanks for sharing. the Ingress looks ok.

Could you run the same command curl command but from one of the nodes of the cluster, using the correct nodeport. For example:
```
curl --resolve <hostname>:30171:127.0.0.1 https://<hostname>:30171
```

**Comment by Mr-Reca** [comment]
If you mean running curl on the master node (for example), this is what I was doing previously.

I'll do it now with a remote machine. Sorry for not doing it before. This is the output:
```
 (7) Failed to connect to <hostname> port <IC_PORT>: Timed out
```

I have a DNS rule to redirect the traffic that matches the hostname to the master node. In case this helps.

Thank you so much for your time,

**Comment by pleshakov** [comment]
> Is it possible that I need some additional configuration on the firewall on both machines? 

@Mr-Reca if you can't connect to the nodes on nodeports from outside of the cluster, yep, please make sure that firewall rules allow those connections on your nodes.

**Comment by Mr-Reca** [comment]
Do I need to set them through iptables? I have lots of chains and rules there (because of the CNI) and I don't know where to put it

**Comment by pleshakov** [comment]
@Mr-Reca I assume so, but that would depend on your environment and infrastructure, so I can't give you any concrete advise :(
