### ISSUE TITLE
Kubernetes DNS Required as a dependency 

### ISSUE THREAD

**Issue by thecanadianbaker** [nginxinc/kubernetes-ingress#8]
The controller has a hard dependency on DNS being present in the cluster instead of using the API to discover upstreams.

**Comment by pleshakov** [comment]
Yep, NGINX Plus controller uses DNS to get endpoints of a service. This works great and significantly simplifies the implementation. What could be the reasons to disable DNS add-on? What are the possible problems?

The NGINX controller uses API to discover endpoints on the other hand.
