### ISSUE TITLE
How to disable list/watch on virtualserver and virtualserverroutes

### ISSUE THREAD

**Issue by dhatri308** [nginxinc/kubernetes-ingress#802]
We are updating ingress from 1.4.6 to 1.6 mainly to run Ingress as non root. We do not have VirtualServer and VirtualServerRoutes so we like to disable watch/list on both. We do not have rbac policy for resources VirtualServer and VirtualServerRoutes for same reason. We see below error in pod logs. We do not have CustomResourceDefinition as well. 

`E1231 16:33:14.450062      16 reflector.go:280] /home/ec2-user/workspace/C_kubernetes-ingress_release-1.6/internal/k8s/controller.go:332: Failed to watch *v1.Pod: unknown (get pods)
E1231 16:33:14.855893      16 reflector.go:123] /home/ec2-user/workspace/C_kubernetes-ingress_release-1.6/internal/k8s/controller.go:340: Failed to list *v1.VirtualServer: virtualservers.k8s.nginx.org is forbidden: User "system:serviceaccount:oci:nginx-ingress" cannot list virtualservers.k8s.nginx.org at the cluster scope: no RBAC policy matched
E1231 16:33:14.857343      16 reflector.go:123] /home/ec2-user/workspace/C_kubernetes-ingress_release-1.6/internal/k8s/controller.go:341: Failed to list *v1.VirtualServerRoute: virtualserverroutes.k8s.nginx.org is forbidden: User "system:serviceaccount:oci:nginx-ingress" cannot list virtualserverroutes.k8s.nginx.org at the cluster scope: no RBAC policy matched`

Is there any way we can turn these off ?

**Comment by pleshakov** [comment]
@dhatri308 yes, it is possible to disable those if you set the `-enable-custom-resources` flag to false in your deployment/daemonset manifest. See also https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/command-line-arguments/#cmdoption-enable-custom-resources

**Comment by dhatri308** [comment]
Awesome. This resolved the issue. Thanks!
