### ISSUE TITLE
Run Nginx master process as nginx but container as root

### ISSUE THREAD

**Issue by dhatri308** [nginxinc/kubernetes-ingress#805]
We are upgrading from 1.4.6 to 1.6. We need to run container as Root as we have an init.d service script which needs root permission. Is it possible to run container as root but run nginx master as nginx instead of root. (looks like worker processes are already running as nginx)

**Comment by pleshakov** [comment]
@dhatri308 
if you use the following security context for the IC container, the IC process and the NGINX master process will run as root while the worker processes will run as NGINX user:
```yaml
securityContext:
  runAsUser: 0
```
Note that NGINX master process will run as the user of the IC process.

**Comment by dhatri308** [comment]
Thanks.

**Comment by dhatri308** [comment]
@pleshakov Is there a simple way to run the container as ROOT but IC and NGINX master as NGINX user instead ? 
We are starting container as ROOT and then trying to start NGINX as NGINX user. There are a bunch of permission issues, NGINX not able to find .tmpl files etc.

**Comment by pleshakov** [comment]
@dhatri308 
We would like to better understand the use case and the need before we come up with a solution.  If it is possible, could you share the details of why it is necessary to run the commands inside the IC container and also run them as ROOT user?

**Comment by dhatri308** [comment]
@pleshakov To help debugging. If the container is running as root, we can install packages and debug. Nginx user doesn't have enough permissions. Apart from that we have a requirement to run init.d service in same container. We follow this model where containers are running as root but the processes are running as non-root.

**Comment by dhatri308** [comment]
We are trying with `gosu `

`gosu nginx /nginx-ingress [args]`

**Comment by pleshakov** [comment]
@dhatri308 thanks for the additional context.

For you case, would it be possible to use a sidecar container or init containers?

What errors are you getting when trying to run with`gosu`?

**Comment by dhatri308** [comment]
@pleshakov I am not sure about the init containers.
We are planning to change permissions//handle errors in the Dockerfile with 1.6.0/1.6.1 as base image.

Very first error we see is `No such file or directory for /var/log/nginx/error.log (Permission denied)`

We see below code in Dockerfile is creating link

`# forward nginx access and error logs to stdout and stderr of the ingress
# controller process
RUN ln -sf /proc/1/fd/1 /var/log/nginx/access.log \
	&& ln -sf /proc/1/fd/1 /var/log/nginx/stream-access.log \
	&& ln -sf /proc/1/fd/2 /var/log/nginx/error.log`

But we would lose error logs.

**Comment by dhatri308** [comment]
Another error, bunch of 
`Unable to fetch version: error getting client: Get http://config-version/configVersion: dial unix /var/lib/nginx/nginx-config-version.sock: connect: no such file or directory
`
Then, 
`F0117 16:14:51.968168      44 manager.go:195] Could not get newest config version: could not get expected version: 0`

**Comment by pleshakov** [comment]
@dhatri308 
it looks like  this error `F0117 16:14:51.968168 44 manager.go:195] Could not get newest config version: could not get expected version: 0` appears because NGINX wasn't able to start

**Comment by dhatri308** [comment]
@pleshakov Thanks. Any idea how to handle Permission denied issues for `/var/log/nginx/` mentioned above ?

**Comment by dhatri308** [comment]
Also, in case we can use init container, how can we handle this case ?

**Comment by dhatri308** [comment]
Solved it by unlinking log files, creating log files with appropriate permissions and tail log files.

**Comment by pleshakov** [comment]
@dhatri308 glad you were able to solve it!
