### ISSUE TITLE
Reload /etc/init.d/nginx reload does not work in version 1.6

### ISSUE THREAD

**Issue by dhatri308** [nginxinc/kubernetes-ingress#823]
We have upgraded to version 1.6. Running IC container as nginx user. We have a use case where we want to reload nginx after a particular scenario. 

When we run `/etc/init.d/nginx reload` we get below error
`[FAIL] Reloading nginx: nginx failed!`

I saw the do_reload() in etc/init.d/nginx has below code
`do_reload() {
    #
    start-stop-daemon --stop --signal HUP --quiet --pidfile $PIDFILE
    RETVAL="$?"
    return "$RETVAL"
}`
PIDFILE points to `PIDFILE=${PIDFILE:-/var/run/nginx.pid}`

However, there is no nginx.pid in /var/run. Instead its been changed to /var/lib/nginx.
https://github.com/nginxinc/kubernetes-ingress/pull/710/files

Is this the reason it fails to reload or is there any other reason possible ?

**Comment by pleshakov** [comment]
@dhatri308
 it is possible to reload NGINX if you run `/usr/sbin/nginx -s reload` inside the container.
Additionally, if you make any change to the [ConfigMap](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/), the Ingress Controller will regenerate NGINX config and reload NGINX.

**Comment by dhatri308** [comment]
Thanks. Is there a way to confirm on running above command, nginx reload was successful.
Example - On running ` /etc/init.d/nginx reload`, it says
`[ ok ] Reloading nginx: nginx.` or `[FAIL] Reloading nginx: nginx failed!`

**Comment by pleshakov** [comment]
@dhatri308 
If you make a reload by  changing the ConfigMap, you can check the events for that ConfigMap https://docs.nginx.com/nginx-ingress-controller/troubleshooting/#checking-the-events-of-the-configmap-resource
Additionally, there are some Prometheus metics related to reloads https://docs.nginx.com/nginx-ingress-controller/logging-and-monitoring/prometheus/#available-metrics

It is better not to reload NGINX directly, but let the Ingress Controller do that. The Ingress Controller doesn't expect that anything else reloads NGINX.
