### ISSUE TITLE
E0122   1 reflector.go:123] /home/ec2-user/workspace/PI_IC_kubernetes-ingress_master/internal/k8s/controller.go:340: Failed to list

### ISSUE THREAD

**Issue by infrainuxumedia** [nginxinc/kubernetes-ingress#829]
I have installed the ingress controller step by step as mentioned, it is working fine but there are continuous errors in logs.
Error:
E0122 09:33:21.980347       1 reflector.go:123] /home/ec2-user/workspace/PI_IC_kubernetes-ingress_master/internal/k8s/controller.go:340: Failed to list

**To Reproduce**
1. Deploy ingress
2. View logs "kubectl logs <pod>"
3. See error

**Expected behavior**
There should be no errors in logs.

**Comment by Rulox** [comment]
Hi @infrainuxumedia

Can you tell me which version of the Ingress Controller you are using? And also if you did a fresh install or you were using an older version and then just updated the Ingress Controller image?

Also, if you are not using our CRDs ([VirtualServer and VirtualServerRoute](https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/)) , can you try to set `enable-custom-resources` to false? It's a command line argument (more info [here](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/command-line-arguments/#cmdoption-enable-custom-resources)) and check if the error is gone?

Thanks!

**Comment by infrainuxumedia** [comment]
OMG!!
It was my mistake. Thanks, Rulox. I missed CRD while deploying ingress.
After running following problem solved.

kubectl create -f kubernetes-ingress/deployments/common/custom-resource-definitions.yaml

Thanks for the help.

**Comment by Rulox** [comment]
Glad I could help!

Closing this

**Comment by alionur07** [comment]
hello everyone i have same issue. i deployed custom-resource-definitions.yaml but it didnt work. Could any one help me?

**Comment by alionur07** [comment]
hi again. 

i did     "- -enable-custom-resources=false " like as Rulox said. İt worked. 

But i have another issue :). Is there anyone has an idea about that issue ?

1 leaderelection.go:252] successfully acquired lease default/nginx-ingress-leader-election
E0717 15:09:02.329342       1 leaderelection.go:320] error retrieving resource lock default/nginx-ingress-leader-election: Get "https://10.0.0.1:443/api/v1/namespaces/default/configmaps/nginx-ingress-leader-election": context deadline exceeded
I0717 15:09:02.329739       1 leaderelection.go:277] failed to renew lease default/nginx-ingress-leader-election: timed out waiting for the condition
