### ISSUE TITLE
ingress returning 404 for all enpoints.

### ISSUE THREAD

**Issue by KevinEdry** [nginxinc/kubernetes-ingress#830]
**Describe the bug**
I am trying to connect an ingress to microservices, and make them accessible via the same ip address. I have setup a load balancer for every microsevice (which makes them accessible with the external ip of the assigned load balancer) but when I am trying to add them all to an ingress service, it doesn't work and returning 404.

my ingress yaml file looks like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.global-static-ip-name: ingress-ip
    nginx.ingress.kubernetes.io/rewrite-target: /
  creationTimestamp: "2020-01-22T20:04:39Z"
  generation: 8
  name: microservice-ingress
  namespace: microservices
  resourceVersion: "412959"
spec:
  rules:
      - host: sub.domain.com
        http:
            paths:
                - backend:
                      serviceName: serviceA-ntpfw
                      servicePort: 80
                   path: /api/v1/serviceA/*
status:
  loadBalancer:
    ingress:
    - ip: 34.107.194.159
```

**Comment by lucacome** [comment]
Hi @KevinEdry 

from your annotation, it looks like you're using the [kubernetes ingress-nginx](https://github.com/kubernetes/ingress-nginx. That's a different project. Could you please double-check?
