### ISSUE TITLE
Question: Can least_conn and sticky work together ? 

### ISSUE THREAD

**Issue by rere16** [nginxinc/kubernetes-ingress#833]
Hello,

Is it possible to make least_conn and sticky work together?

For a new sticky session, what algorithm is used to decide an upstream server for this session and then assign a cookie "route" to it ?

Thank you

**Comment by pleshakov** [comment]
Hi @rere16 

Yes, sticky cookie and least_coon work together. For a new sticky sessions, NGINX will choose an upstream server using the configured load balancing method. If you configure the Ingress Controller to use the least_conn, then NGINX will use the least_conn.

Note that sticky cookie is only available in NGINX Plus.
