### ISSUE TITLE
Pass Client certificate to backend during mtls

### ISSUE THREAD

**Issue by ranajoy97** [nginxinc/kubernetes-ingress#849]
**Is your feature request related to a problem? Please describe.**
I have an appication that needs client certificate authentication for a particular API. If I try to authenticate using client certificate using the POD or service URL it works fine.

As soon as I try to do that using the nginx ingress URL it stops working resulting in a 502 Error. The ingress logs show:

`2020/02/11 13:07:36 [error] 7285#7285: *8030939 SSL_do_handshake() failed (SSL: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:SSL alert number 42) while SSL handshaking to upstream, client: 10.246.226.47, server: sample.domain.com, request: "GET /openidm/info/login HTTP/2.0", upstream: "https://10.246.226.91:8444/openidm/info/login", host: "sample.domain.com"
2020/02/11 13:07:36 [warn] 7285#7285: *8030939 [lua] sticky.lua:134: balance(): failed to get new upstream; using upstream nil while connecting to upstream, client: 10.246.226.47, server: sample.domain.com, request: "GET /openidm/info/login HTTP/2.0", upstream: "https://10.246.226.91:8444/openidm/info/login", host: "sample.domain.com"
2020/02/11 13:07:36 [warn] 7285#7285: *8030939 [lua] balancer.lua:269: balance(): no peer was returned, balancer: sticky_balanced while connecting to upstream, client: 10.246.226.47, server: sample.domain.com, request: "GET /openidm/info/login HTTP/2.0", upstream: "https://10.246.226.91:8444/openidm/info/login", host: "sample.domain.com"
2020/02/11 13:07:36 [crit] 7285#7285: *8030939 connect() to 0.0.0.1:80 failed (22: Invalid argument) while connecting to upstream, client: 10.246.226.47, server: sample.domain.com, request: "GET /openidm/info/login HTTP/2.0", upstream: "https://0.0.0.1:80/openidm/info/login", host: "sample.domain.com"
2020/02/11 13:07:36 [warn] 7285#7285: *8030939 upstream server temporarily disabled while connecting to upstream, client: 10.246.226.47, server: sample.domain.com, request: "GET /openidm/info/login HTTP/2.0", upstream: "https://0.0.0.1:80/openidm/info/login", host: "sample.domain.com"`

I tried enabling client certificate authentication on Ingress level but that breaks other APIs that does not require a client certificate authentication.

**Describe the solution you'd like**
Is there a way in which Ingress won't try to do a certificate authentication but will pass the certificate to the application so that the application can take care of the certificate authentication.

**Describe alternatives you've considered**
Enable mutual TLS and protect all the APIs with that.

**Additional context**

**Comment by pleshakov** [comment]
@ranajoy97 
Hi,
 
I believe you're using the [kubernetes ingress-nginx](https://github.com/kubernetes/ingress-nginx). That's a different project - if you create an issue over there they might be able to help.
