### ISSUE TITLE
Helm Chart - Expose volumes to load additional configuration / files in /etc/nginx/conf.d

### ISSUE THREAD

**Issue by cdunford** [nginxinc/kubernetes-ingress#855]
I am following along the blog post [Using the NGINX Plus Ingress Controller for Kubernetes with OpenID Connect Authentication from Azure AD](https://www.nginx.com/blog/nginx-plus-ingress-controller-for-kubernetes-openid-connect-azure-ad/) in order to integrate with Azure AD.

I am trying to use the [helm chart](https://github.com/nginxinc/kubernetes-ingress/tree/master/deployments/helm-chart) to accomplish this, however one of the requirements is mounting a volume (2 actually) in `/etc/nginx/conf.d` for `openid_connect.js` and `openid_connect.server_conf`. This cannot be accomplished today without modifying the existing helm chart to include these volumes.

It would be great if the out the box helm chart could be enhanced/extended to enable the ability to attach volumes to the controller container in order to simplify implementation of use cases similar to this.

**Comment by pleshakov** [comment]
@cdunford Thanks for the proposal! The feature makes sense. We will add it soon. Please stay tuned! :)

**Comment by cdunford** [comment]
Great, thanks!
