### ISSUE TITLE
Equivalent of `kubernetes.io/ingress.class` annotation for `VirtualServer`s

### ISSUE THREAD

**Issue by defect** [nginxinc/kubernetes-ingress#863]
Hi!

We are running a couple of nginx ingress instances for isolation of different kinds of workloads. We currently do this using "normal" `Ingress` resources and annotating them with `kubernetes.io/ingress.class`

I've now started experimenting with `VirtualServer` as we're planning to move more complicated nginx configs over from bare-metal and it seems powerful. Is there an annotation or similar to make only a specific ingress class pick up a `VirtualServer`? I tried `kubernetes.io/ingress.class` but the virtual server was added to all the ingress instances.

Thanks in advance!

**Comment by pleshakov** [comment]
Hi @defect 

There is nothing similar to `kubernetes.io/ingress.class` annotation for VirtualServer resource.

Adding the class annotation (or something similar to that) would not be a difficult thing to implement.

Our next release - 1.7. - is planned for end of March. I will let you now next week if we will be able to implement this feature for 1.7.

For now, the only way to use different Ingress Controllers for different VirtualServers is to isolate them on a per namespace basis.

**Comment by defect** [comment]
Okay, thank you @pleshakov! That's all understandable. I might have a go at implementing that. I'd like to get familiarized with the codebase anyway :)

**Comment by pleshakov** [comment]
@defect  just an update. I don't think we'll make this feature available in the upcoming 1.7, but we'll  definitely include it in 1.8.
