### ISSUE TITLE
how to config mutilpath rewrite with the same service

### ISSUE THREAD

**Issue by turbokernel** [nginxinc/kubernetes-ingress#865]
here is my ingress yaml file:
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/rewrites: "serviceName=service1 rewrite=/"
  name: auto-survey
  namespace: zx-news
spec:
  rules:
  - host: domain.com
    http:
      paths:
      - backend:
          serviceName: service1
          servicePort: 80
        path: /auto/
      - backend:
          serviceName: service1
          servicePort: 80
        path: /admin/

and here is my propose：
request from domain.com/auto/admin rewrite to domain.com/admin
and request from domain.com/admin keep the request to domain.com/admin

after apply the yaml file,i find that the first propose has no problem, but the second has rewrite to domain.com/.
So, how to config mutilpath rewrite with the same service?

**Comment by pleshakov** [comment]
Hi @turbokernel 

Yep, the annotation applies per service, not per path.

As a possible solution, you can split the Ingress resource into a multiple mergeable Ingress resources (https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/mergeable-ingress-types) and use the annotation with different values in each Ingress resource. An annotation applied per a mergeable minion can has the scope of the paths of that minion.

Alternatively, would it be possible to create an additional service that references the same pod?

**Comment by turbokernel** [comment]
thx,your solution is worked!i also try to create another service that point the same deploy,it also works~
