### ISSUE TITLE
Watch for secret changes

### ISSUE THREAD

**Issue by kbrownlees** [nginxinc/kubernetes-ingress#87]
This is mentioned in https://github.com/nginxinc/kubernetes-ingress/issues/78 but it looks like the fix he is working on will only force a retry if the secret does not exist yet.

Would be nice if it also watched for secret changes so it triggered a reload when a certificate gets updated.

**Comment by pleshakov** [comment]
Fixed in https://github.com/nginxinc/kubernetes-ingress/pull/166
