### ISSUE TITLE
Issue with 413 error client-max-body-size.  I'm using Microsofts AKS environment

### ISSUE THREAD

**Issue by AechLyons** [nginxinc/kubernetes-ingress#880]
**When developers submit form data they recieve a 413 error on Azure's AKS deployment even after trying to edit configmap (I also tried Ingress Route)

**Steps to reproduce the behavior:
1. Create AKS deployment
2. Create nginx ingress via Helm as per M$'s instructions:
```
# Create a namespace for your ingress resources
kubectl create namespace ingress-basic

# Add the official stable repo
helm repo add stable https://kubernetes-charts.storage.googleapis.com/

# Use Helm to deploy an NGINX ingress controller
helm install nginx stable/nginx-ingress \
    --namespace ingress-basic \
    --set controller.replicaCount=2 \
    --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux \
    --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux
```
3. I edited configmap:
```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  client-max-body-size: 0m
  proxy-connect-timeout: 10s
  proxy-read-timeout: 10s
kind: ConfigMap
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"nginx-nginx-ingress-controller-7b9bff87b8-vxv8q","leaseDurationSeconds":30,"acquireTime":"2020-03-10T20:52:06Z","renewTime":"2020-03-10T20:53:21Z","leaderTransitions":1}'
  creationTimestamp: "2020-03-10T18:34:01Z"
  name: ingress-controller-leader-nginx
  namespace: ingress-nginx
  resourceVersion: "23928"
  selfLink: /api/v1/namespaces/ingress-nginx/configmaps/ingress-controller-leader-nginx
  uid: b68a2143-62fd-11ea-ab45-d67902848a80
```

**Expected behavior**
nginx.conf of pod should show the value of the clinet body size to be higher then 1m.  When I grep the conf file it shows 1m and developers continue to get the 413 error:

```
kubectl exec -n ingress-nginx nginx-nginx-ingress-controller-7b9bff87b8-p4ppw cat nginx.conf | grep client_max_body_size
            client_max_body_size                    1m;
            client_max_body_size                    1m;
            client_max_body_size                    1m;
            client_max_body_size                    1m;
            client_max_body_size                    21m;

```
**Your environment**
* use Helm to install stable/nginx......Not sure how to query the version.  i tried helm search -l stable/nginx and got an error
* 1.13.11
* Microsoft AKS
* Using NGINX

**Additional context**
We previously had clusters with older versions of k8's working on AKS but they are not working now.  I suspect because M$ upgrades k8's as their support drops off for older versions.  I have engaged M$ and they are blaming it on nginx but they are willing to help.  Apparently an engineer got it to work on their side but when I took the steps they said worked for them I got the same result.

**Comment by Rulox** [comment]
Hi @AechLyons 

It seems, per your description of:

```
# Add the official stable repo
helm repo add stable https://kubernetes-charts.storage.googleapis.com/

# Use Helm to deploy an NGINX ingress controller
helm install nginx stable/nginx-ingress \
```

That you are using the [Ingress Controller](https://github.com/kubernetes/ingress-nginx) created by the community. Can you open an issue in their repository? This Ingress Controller is managed by NGINX Inc for NGINX and NGINX Plus, it's a different project. You can find the differences [here](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/nginx-ingress-controllers.md).

Thanks

**Comment by AechLyons** [comment]
Oops.  Sorry I didnt realize it was not the official nginx (Maybe thats my problem).

**Comment by Rulox** [comment]
For more info in our helm charts please visit our official [doc](https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/).
