### ISSUE TITLE
Kubernetes Nginx ingress Controller Security Hardening 

### ISSUE THREAD

**Issue by muradmomani** [nginxinc/kubernetes-ingress#887]
**Is your feature request related to a problem? Please describe.**
I'm following CIS Benchmark documents for hardening Nginx, this seems easy and simple for standalone Nginx -downloaded through Nginx packages or Linux packages as well-, but when it comes to Kubernetes Nginx deployed using helm charts or other methods I found i hard to mirror those security hardening from the CIS Benchmark document to the ingress controller, like files and directory permissions, user accounts, and network configuration. 

**Describe the solution you'd like**
Is there any security hardening document suggested from your side as that supported by CIS Benchmark that is suitable for the ingress controller!
or any other way to reflect those hardening from the CIS benchmark to the Nginx controller?

**Describe alternatives you've considered**
I tried to follow the CIS document on the Nginx controller but it seems wired and no sense for some points. 

**Additional context**

Aha! Link: https://nginx.aha.io/features/IC-107

**Comment by pleshakov** [comment]
Hi @muradmomani 

> Is there any security hardening document suggested from your side as that supported by CIS Benchmark that is suitable for the ingress controller!
or any other way to reflect those hardening from the CIS benchmark to the Nginx controller?

Unfortunately, we don't provide anything like that for the Ingress Controller.

At the same time, It should be possible to use [ConfigMaps](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/), [annotations](https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/) and [custom templates](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/custom-templates/) to customize/fine-tune  the security-related NGINX configuration (like disabling server tokens or configuring SSL ciphers).

**Comment by muradmomani** [comment]
HI @pleshakov 

Thanks for your response, 

yes that right we can fine-tune the configuration by configmaps, but regarding other configuration like file permissions and the user who runes the Nginx for privilege issues, how this handled? 

Also, I would like to recommend if there is security documentation for the Nginx ingress controller for Kubernetes the describes the current security posture and what Nginx supports for that as you know the security, especially for Kubernetes and its component, is very important. 

Thanks.

**Comment by timdeluxe** [comment]
Hi,
from one of our customers we got the request to apply the CIS Benchmark recommendations to the nginx ingress solution.
I went through each of the single points there and looked, if nginx ingress implemented it as default, if an action is possible by configuration (through configmaps, annotations or templates) or if a modification of the "core" code would be required. It is not 100% clean/done yet, but i would like to provide it publicly.

@pleshakov: Is there any place in the repo(s), where it would make sense? If yes i would provide a PR. If not i will publish it in an own repo...

**Comment by pleshakov** [comment]
Hi @timdeluxe 

I think your knowledge could be helpful for the community.  However, this seems like a specialized topic, so not sure if it makes sense to put that in our [docs](https://docs.nginx.com/nginx-ingress-controller/) or examples.

Perhaps it would be appropriate to keep this issue open and have a link to your repo?
Additionally, we can also create a section in our docs for links to external guides, so we can link to your guide.

What do you think?

**Comment by muradmomani** [comment]
@timdeluxe 
Hi,
Thanks for your efforts, after this issue I went to checked all the points of CIS Benchmark and made a document with each point, and if there a possible configuration or implemented by default, it not also completed but at the same time it may be helpful. 
Also would like to check your one which will help the community, Thanks for your efforts.

**Comment by timdeluxe** [comment]
In the meantime i had the chance to work on this.

I now published a markdown document: https://github.com/dodevops/k8s-ingress-nginx-hardening
It is not complete yet, there are still open topics marked with question marks. Pull requests are welcome @muradmomani :)

**Comment by brianehlert** [comment]
I believe the spirit of this has been addresses with the capabilities of removing elevated privileges and the option for readOnlyRootFileSystem
Beyond that, any customer can harden their own image and use that as the base image to build their image.  That is commonly where CIS hardening comes to play.
