### ISSUE TITLE
Support for Prometheus Operator ServiceMonitor

### ISSUE THREAD

**Issue by nahuel242** [nginxinc/kubernetes-ingress#889]
**Is your feature request related to a problem? Please describe.**
I've noticed that this helm chart doesn't provide support for prometheus servicemonitor CRD, so if you have Prometheus Operator installed and you want to monitor the nginx ingress controller deployed with this chart you can't do it out of the box.
 

**Describe the solution you'd like**
Support out of the box for prometheus operator, for example the chart https://hub.helm.sh/charts/bitnami/nginx-ingress-controller provides this with metrics.serviceMonitor.*  values.

**Describe alternatives you've considered**
Create a ServiceMonitor yaml specific for this chart and apply it after every helm install / upgrade.

**Additional context**

Thank you very much!

**Comment by Rulox** [comment]
Hi @nahuel242 thanks for your request.

First of all we have to understand which Ingress Controller you are using. There are 2 NGINX Ingress Controllers out there. The [first one](https://github.com/kubernetes/ingress-nginx) is maintained by the k8s community. The second one (this repository) is maintained by NGINX Inc.

The helm chart that you posted in your issue refers to the first one (k8s community). If that's the one you are using I suggest you create the issue in their repository as there's nothing we can do to help with that different project.

To learn more about the differences between these 2 Ingress Controllers check [this](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/nginx-ingress-controllers.md).

Makes sense? Thanks

**Comment by nahuel242** [comment]
Hi @Rulox , thanks for reaching out so fast!

I'm using the NGINX Ingress controller mantained by NGINX Inc. I referred to the NGINX Ingress Controller mantained by the K8s community only to show an example of the feature that I was asking for.

**Comment by Rulox** [comment]
Great! I'll discuss this with the team and get back to you then, sorry for the missunderstanding @nahuel242

**Comment by nahuel242** [comment]
No problemo, thank you very much!!!!

**Comment by widgetpl** [comment]
Hi @Rulox any feedback about adding servicemonitor or we need to maintain this by ourselves ?

**Comment by Rulox** [comment]
Hi @widgetpl 

I'm not part of NGINX anymore, pinging @Dean-Coakley @LorcanMcVeigh

**Comment by pleshakov** [comment]
Hi @widgetpl 

Unfortunately, we haven't made made any progress on this feature request.

Would you be interested in sharing your service monitor in this issue so other people can reuse it or contributing the service monitor to the helm chart?

**Comment by hostalp** [comment]
It would be great to finally implement this since this is now a common method instead of the `prometheus.io/scrape` annotation.

**Comment by hostalp** [comment]
Does the #2831 actually deliver the complete functionality? It appears to add the service monitor, but one still needs the service resource for the nginx prometheus endpoint (see my example above), otherwise the service monitor can't be tied to anything useful (service that provides prometheus metrics).

And unless I'm missing something there isn't a way to create this service via the helm chart a.t.m.
