### ISSUE TITLE
Double HSTS header

### ISSUE THREAD

**Issue by weihan1394** [nginxinc/kubernetes-ingress#890]
**Describe the bug**
I have currently deployed 2 apps at my k8 cluster but I realize there is one with HSTS enabled at the backend, while the other app does not have HSTS enabled. When I try to apply the HSTS at the config map from what was suggested at [#404](https://github.com/nginxinc/kubernetes-ingress/issues/404) it will then cause app1 to have double **Strict-Transport-Security** header. 
app1: HSTS enabled at the backend
app2: No HSTS

**To Reproduce**
I am trying to clarify on whether how I can disable HSTS using `proxy-hide-headers`.

**Expected behavior**
I am looking at the [docs](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#request-uri-header-manipulation) and I saw that there is `proxy-hide-headers`. I was thinking if I could use this to hide the HSTS header from my app1 and apply the **Strict-Transport-Security** header for both apps at the Nginx level.

**Your environment**
* Ingress Controller (1.6.3-alpine)
* Kubernetes (v1.16.6)
* NGINX

**Comment by pleshakov** [comment]
Hi @weihan1394 

Are you using the Ingress resource or  the [VirtualServer](https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/) resource?

With the Ingress resource, hsts is supported if you use the hsts key in the ConfigMap:
```yaml
hsts: "True"
```

There are a few additional keys that customize hsts. Please see https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#auth-and-ssl-tls

When configured that way, the NGINX configuration will hide the hsts header if it is sent by a backend.

**Comment by weihan1394** [comment]
Hi @pleshakov 

Thank you for the help! Sorry, I was not clear on whether I am using the Ingress resource or the virtual resource. I am currently adopting the VirtualServer resource. 

When I apply the `hsts: "True"` it doesn't seem to apply the header unless I am using ` server-snippets: 'add_header Strict-Transport-Security "max-age=31536000" always;' # enable hsts`.

**Comment by pleshakov** [comment]
@weihan1394 
Great. Thanks for the clarification.

The following server-snippets should help you. Note that as per hsts specification we only set the hsts header for HTTPs requests. Additionally, if the backend sets `Strict-Transport-Security` header, NGINX will clear it out, replacing it with the correct one:
```yaml
server-snippets: |
  proxy_hide_header Strict-Transport-Security;
  set $hsts_header_val "";
  if ($https = on) {
     set $hsts_header_val "max-age=31536000";
  }
  add_header Strict-Transport-Security "$hsts_header_val" always;
```

**Comment by weihan1394** [comment]
@pleshakov 

It works now! But may I know where is the documentation on the variables available such as `$https`?

Thank you for your help. :)

**Comment by pleshakov** [comment]
Hi @weihan1394 

List of all NGINX variables can be found here -- http://nginx.org/en/docs/varindex.html 

We don't have anything better for server snippets, other than the already mentioned https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#auth-and-ssl-tls

Using snippets requires some understanding on how NGINX is configured. When using them, it could be helpful to check the generated config - it is described here https://docs.nginx.com/nginx-ingress-controller/troubleshooting/#checking-the-generated-config With snippets, it is also easy to make a mistake (for example, forgetting to add ";" at the end of NGINX config line) - so after updating snippets, it makes sense to check the events of the ConfigMap - https://docs.nginx.com/nginx-ingress-controller/troubleshooting/#checking-the-events-of-the-configmap-resource

General NGINX configuration techniques can be found here -- https://docs.nginx.com/nginx/
