### ISSUE TITLE
Nginx throws 502 on rolling deployment of applications behind nginx.

### ISSUE THREAD

**Issue by Sushma10037017** [nginxinc/kubernetes-ingress#891]
We have Nginx installed on our Kubernetes setup and a couple of applications deployed behind Nginx for caching. When we rolling deployment any application, we are seeing intermittent 502s at Nginx ALB. 

**What we investigated?**
1. Enabled debug logs and started some request load on the application.
2. Deleted an application container.
2. Cross verified the Nginx config file for terminating container IP.
As soon as the container is marked as terminating, we could see the Nginx reconfigures(logs) and the old container IP gets removed.

3. Tried reducing the keep-alive timeout and keep-alive connections, but still observing 502s.  

**Expected behavior**
When an application container is deleted, Nginx should handle the draining smoothly and the existing requests should be served without 5xx.

**Your environment**
* Version of the Ingress Controller - NGINX_VERSION 1.17.4, docker image - nginx/nginx-ingress:1.5.6
* Version of Kubernetes - 1.14.9
* Kubernetes platform  - self-hosted k8s(kops) on AWS
* Using NGINX

**Additional context**
Nginx main config file
`load_module modules/ngx_http_vhost_traffic_status_module.so;
user  nginx;
worker_processes  4;
daemon off;
error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;
events {
    worker_connections  40000;
}
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    vhost_traffic_status_zone shared:vhost_traffic_status:32m;
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    access_log off;
    sendfile        on;
    #tcp_nopush     on;
    keepalive_timeout 30s;
    keepalive_requests 100;
    #gzip  on;
    server_names_hash_max_size 512;
    server_names_hash_bucket_size 512;
    variables_hash_bucket_size 256;
    variables_hash_max_size 1024;
    map $http_upgrade $connection_upgrade {
        default upgrade;
             close;
    }
    server {
        listen 80 default_server;
        listen 443 ssl default_server;
        ssl_certificate /etc/nginx/secrets/default;
        ssl_certificate_key /etc/nginx/secrets/default;
        server_name _;
        server_tokens "on";
        access_log off;
        location /status {
            vhost_traffic_status_display;
            vhost_traffic_status_display_format json;
        }
        location /nginx-health {
            default_type text/plain;
            return 200 "healthy\n";
        }
        location / {
           return 404;
        }
    }
    # stub_status
    server {
        listen 8080;
        allow 127.0.0.1;
        deny all;
        location /stub_status {
            stub_status;
        }
    }
    server {
        listen unix:/var/run/nginx-status.sock;
        access_log off;
        location /stub_status {
            stub_status;
        }
    }
    include /etc/nginx/config-version.conf;
    include /etc/nginx/conf.d/*.conf;
    server {
        listen unix:/var/run/nginx-502-server.sock;
        access_log off;
        location / {
            return 502;
        }
    }
}
stream {
    log_format  stream-main  '$remote_addr [$time_local] '
                      '$protocol $status $bytes_sent $bytes_received '
                      '$session_time';
    access_log  /var/log/nginx/stream-access.log  stream-main;
}`

Service-specific nginx conf
`upstream test-in-load-apse1-test-minion-cache-ingress-nginx-test-nginx-in-load.ld.test-labs.com-test-443 {
	random two least_conn;

	server <IP>:<PORT> max_fails=1 fail_timeout=10s;
	server <IP>:<PORT> max_fails=1 fail_timeout=10s;
	server <IP>:<PORT> max_fails=1 fail_timeout=10s;
	server <IP>:<PORT> max_fails=1 fail_timeout=10s;
	server <IP>:<PORT> max_fails=1 fail_timeout=10s;
	keepalive 32;
}
upstream test-in-load-apse1-test-minion-non-cache-ingress-nginx-test-nginx-in-load.ld.test-labs.com-test-443 {
	random two least_conn;

	server <IP>:<PORT> max_fails=1 fail_timeout=10s;
	server <IP>:<PORT> max_fails=1 fail_timeout=10s;
	server <IP>:<PORT> max_fails=1 fail_timeout=10s;
	server <IP>:<PORT> max_fails=1 fail_timeout=10s;
	server <IP>:<PORT> max_fails=1 fail_timeout=10s;
	keepalive 32;
}

proxy_cache_path /var/nginx/test-in-load-apse1-test-master-ingress-nginx/ levels=1:2 keys_zone=test-in-load-apse1-test-master-ingress-nginx:100m max_size=2g inactive=60m use_temp_path=off;

server {
	listen 80;
	server_tokens on;
	server_name test-nginx-in-load.ld.test-labs.com;
	location /o/v1/episode/get/next {
		# location for minion test-in-load-apse1/test-minion-cache-ingress-nginx
		proxy_http_version 1.1;
		proxy_set_header Connection "";

		proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
		proxy_cache_revalidate on;
		proxy_cache_background_update on;
		proxy_cache_lock on;
		proxy_cache_valid 200 302 2m;
		proxy_cache_valid 404 20s;
		proxy_cache_key $scheme$proxy_host$uri$is_args$arg_contentId$http_x_country_code;
		add_header X-Cache-Status $upstream_cache_status;

		proxy_cache test-in-load-apse1-test-master-ingress-nginx;

		proxy_connect_timeout 60s;
		proxy_read_timeout 60s;
		client_max_body_size 1m;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Port $server_port;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_buffering on;

		proxy_pass http://test-in-load-apse1-test-minion-cache-ingress-nginx-test-nginx-in-load.ld.test-labs.com-test-443;
	}`

Anything are we missing here?  Any help would be appreciated. Thanks!

Aha! Link: https://nginx.aha.io/features/IC-114

**Comment by pleshakov** [comment]
Hi @Sushma10037017

To help us better understand the problem, could you possibly share the logs, the parts where NGINX returns 502 errors?
Additionally, do you configure readiness probes in your application pods?

Also note that after the Ingress Controller removes an upstream server from an upstream and reloads NGINX, NGINX will stop sending any new requests that server. However, NGINX will make sure to finish processing any existing requests to that server.

**Comment by Sushma10037017** [comment]
Hi @pleshakov 
I have attached the Nginx logs below(when an application pod terminated).
[nginx.log](https://github.com/nginxinc/kubernetes-ingress/files/4366052/nginx.log)


Here is the readiness probe configured for the application pods
`    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 90
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: 4001
      timeoutSeconds: 3`
We also have a prestop hook with 90 seconds of sleep.
`    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sleep
          - "90"`

**Comment by gamunu** [comment]
Not just application pods, If I did a rolling restart of the Nginx deployment, I get 502 errors behind AWS LB. I was able to reduce almost all the errors using below preStop command.

```
lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - sleep 15; /usr/local/nginx/sbin/nginx -c /etc/nginx/nginx.conf -s quit; while pgrep -x nginx; do sleep 1; done`
```
