### ISSUE TITLE
can't configure my server to allow download huge video file from server to client

### ISSUE THREAD

**Issue by goodidea-kp** [nginxinc/kubernetes-ingress#901]
**Describe the bug**

proxy_max_temp_file_size 3000m; #<---Assuming video file size is 2G

**To Reproduce**
1. Deploy x to '...' using some.yaml
2. No error messages
3. Download stall on 1024M

**Expected behavior**
Allow me to configure max limit of file size which client can download from the server

**Your environment**
Ubuntu 18.04 as k8 container
* Version of the Ingress Controller - release version or a specific commit

* Version of Kubernetes
1.18.00
* Kubernetes platform (e.g. Mini-kube or GCP)
* Using NGINX 

**Additional context**
nginx version: nginx/1.17.9
built by gcc 8.3.0 (Debian 8.3.0-6) 
built with OpenSSL 1.1.1d  10 Sep 2019
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-g -O2 -fdebug-prefix-map=/data/builder/debuild/nginx-1.17.9/debian/debuild-base/nginx-1.17.9=. -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie'

**Comment by pleshakov** [comment]
Hi @goodidea-kp 

Could you possibly provide additional details about the issue?
* the logs that correspond to the problem from the Ingress Controller pod.
* Ingress file you used for configuration and the generated NGINX config for that Ingress file as well as the main config -- https://docs.nginx.com/nginx-ingress-controller/troubleshooting/#checking-the-generated-config
* the version of the Ingress Controller

Thanks

**Comment by goodidea-kp** [comment]
Ingress file:
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service-angular
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.org/client-max-body-size: "10g"
    nginx.org/proxy-send-timeout: "2400s"
    nginx.org/proxy-read-timeout: "2400s"
    nginx.org/proxy-connect-timeout: "2400s"
    nginx.org/send-timeout: "2400s"
    nginx:org/proxy-buffering: off
    nginx.org/proxy-max-temp-file-size: "0"
    nginx.org/error-log-level: "debug"
    nginx.org/rewrites: "serviceName=cast-cluster-0 rewrite=/hls;serviceName=cast-cluster-1 rewrite=/hls;serviceName=cast-cluster-2 rewrite=/hls;serviceName=cast-cluster-3 rewrite=/hls;"
    nginx.org/server-snippets: |
      ssl_certificate /etc/nginx/secrets/crt;
      ssl_certificate_key /etc/nginx/secrets/key;
      server_name myhost;
      if ($host = myhost) {
        return 302 $scheme://myhost$request_uri;
      }
      include /etc/nginx/mime.types;
      gzip on;
      gzip_min_length 1000;
      gzip_proxied expired no-cache no-store private auth;
      gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;
      ssl_protocols TLSv1.3 TLSv1.2;
      #ssl_ciphers                 TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-256-GCM-SHA384:TLS13-AES-128-GCM-SHA256:EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH;
      ssl_prefer_server_ciphers   on;
      ssl_ecdh_curve              secp384r1;
spec:
  tls:
    - hosts:
        - myhost
      secretName: ag0-nginx-ingress-default-server-secret
  rules:
    - host: myhost
      http:
        paths:
          - path: /ag/api/v1
            backend:
              serviceName: tomcat-cluster
              servicePort: 3051
======
I wasn't able to see a proper generation, so I did just override configuration with manually changed file. The issue with generation is different, so I attached file I modified:
The following code I only removed my host name...
=====
# configuration for default/ingress-service-angular


upstream default-ingress-service-angular-angular-cluster-8082 {
	zone default-ingress-service-angular-angular-cluster-8082 256k;
	random two least_conn;
	
	server 10.244.2.2:80 max_fails=1 fail_timeout=10s max_conns=0;
	
}
upstream default-ingress-service-angular-cast-cluster-0-9090 {
	zone default-ingress-service-angular-cast-cluster-0-9090 256k;
	random two least_conn;
	
	server 127.0.0.1:8181 max_fails=1 fail_timeout=10s max_conns=0;
	
}
upstream default-ingress-service-angular-tomcat-aaa001-cluster-3052 {
	zone default-ingress-service-angular-tomcat-aaa001-cluster-3052 256k;
	random two least_conn;
	
	server 10.244.1.2:8080 max_fails=1 fail_timeout=10s max_conns=0;
	server 10.244.2.4:8080 max_fails=1 fail_timeout=10s max_conns=0;
	server 10.244.3.5:8080 max_fails=1 fail_timeout=10s max_conns=0;
	server 10.244.5.3:8080 max_fails=1 fail_timeout=10s max_conns=0;
	
}
upstream default-ingress-service-angular-tomcat-cluster-3051 {
	zone default-ingress-service-angular-tomcat-cluster-3051 256k;
	random two least_conn;
	
	server 10.244.3.4:8080 max_fails=1 fail_timeout=10s max_conns=0;
	server 10.244.4.3:8080 max_fails=1 fail_timeout=10s max_conns=0;
	
}
upstream default-ingress-service-angular-tomcat-ffmpeg-cluster-aaa001-3053 {
	zone default-ingress-service-angular-tomcat-ffmpeg-cluster-aaa001-3053 256k;
	random two least_conn;
	
	server 10.244.5.2:8080 max_fails=1 fail_timeout=10s max_conns=0;
	
}


server {
	
	error_log debug;
	listen 80;
	
	
	listen 443 ssl;
	ssl_certificate /secret;
	ssl_certificate_key /secret;
	
	
	
	
	

	server_tokens on;

	server_name myhost;

	
	

	
	
	if ($scheme = http) {
		return 301 https://$host:443$request_uri;
	}
	

	
	location /images {
		
		
		proxy_http_version 1.1;
		

		proxy_connect_timeout 600s;
		proxy_read_timeout 2400s;
		proxy_send_timeout 2400s;
		client_max_body_size 10g;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Port $server_port;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_buffering on;

		proxy_pass http://default-ingress-service-angular-angular-cluster-8082;
		
		
	}
	location /icon {
		
		
		proxy_http_version 1.1;
		

		proxy_connect_timeout 60s;
		proxy_read_timeout 60s;
		proxy_send_timeout 60s;
		client_max_body_size 1m;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Port $server_port;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_buffering on;
		
		proxy_pass http://default-ingress-service-angular-angular-cluster-8082;
		
		
	}
	location /ag/api/v1 {    #<----THAT DOES'T WORK AS I EXPECTED!!!
		
		
		proxy_http_version 1.1;
		

		proxy_connect_timeout 600s;
		proxy_read_timeout 2400s;
		proxy_send_timeout 2400s;
		client_max_body_size 10g;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Port $server_port;
		proxy_set_header X-Forwarded-Proto $scheme;
		#proxy_buffering off;
		#send_timeout 600s;
		proxy_max_temp_file_size 3000m;
        #aio threads;
        #directio 512;
        #output_buffers 1 4m;
        #keepalive_timeout 30s;
        #expires max;
        #sendfile on;
		
		proxy_pass http://default-ingress-service-angular-tomcat-cluster-3051;
		
		
	}
	location /ag/heatmap {
		
		
		proxy_http_version 1.1;
		

		proxy_connect_timeout 60s;
		proxy_read_timeout 60s;
		proxy_send_timeout 60s;
		client_max_body_size 1m;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Port $server_port;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_buffering on;
		
		proxy_pass http://default-ingress-service-angular-tomcat-cluster-3051;
		
		
	}
	location /aaa001/ffmpeg {
		
		
		proxy_http_version 1.1;
		

		proxy_connect_timeout 60s;
		proxy_read_timeout 60s;
		proxy_send_timeout 60s;
		client_max_body_size 1m;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Port $server_port;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_buffering on;
		
		proxy_pass http://default-ingress-service-angular-tomcat-ffmpeg-cluster-aaa001-3053;
		
		
	}
	location /aaa001/ffmpeg/imgsnapshot {
		
		
		proxy_http_version 1.1;
		

		proxy_connect_timeout 60s;
		proxy_read_timeout 60s;
		proxy_send_timeout 60s;
		client_max_body_size 1m;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Port $server_port;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_buffering on;
		
		proxy_pass http://default-ingress-service-angular-tomcat-ffmpeg-cluster-aaa001-3053;
		
		
	}
	location /aaa001/ffmpeg/imgdigest {
		
		
		proxy_http_version 1.1;
		

		proxy_connect_timeout 60s;
		proxy_read_timeout 60s;
		proxy_send_timeout 60s;
		client_max_body_size 1m;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Port $server_port;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_buffering on;
		
		proxy_pass http://default-ingress-service-tomcat-ffmpeg-cluster-aaa001-3053;
		
		
	}
	location /hls0 {
		
		
		proxy_http_version 1.1;
		

		proxy_connect_timeout 60s;
		proxy_read_timeout 60s;
		proxy_send_timeout 60s;
		client_max_body_size 1m;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Port $server_port;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_buffering on;
		
		proxy_pass http://default-ingress-service-angular--cast-cluster-0-9090
		
		
	}
	location /aaa001 {
		
		
		proxy_http_version 1.1;
		

		proxy_connect_timeout 60s;
		proxy_read_timeout 60s;
		proxy_send_timeout 60s;
		client_max_body_size 1m;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Port $server_port;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_buffering on;
		
		proxy_pass http://default-ingress-service-angular-tomcat-aaa001-cluster-3052;
		
		
	}
	location / {
		
		
		proxy_http_version 1.1;
		

		proxy_connect_timeout 60s;
		proxy_read_timeout 60s;
		proxy_send_timeout 60s;
		client_max_body_size 1m;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Port $server_port;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_buffering on;
		
		proxy_pass http://default-ingress-service-angular-angular-cluster-8082;
		
		
	}
	
	
}

**Comment by pleshakov** [comment]
Thanks for sending  the additional details.

As mentioned [here](https://trac.nginx.org/nginx/ticket/1472#comment:1), because a download stalls after 1G, it looks like the problem is due to `proxy_max_temp_file_size`. 

Could you double check that your latest configuration is successfully applied? (you can do it by looking at the events as described here https://docs.nginx.com/nginx-ingress-controller/troubleshooting/#checking-the-events-of-an-ingress-resource)

Are there any logs that you see at the backend that might be hepful?

Do you see this problem across different paths as well? (I noticed that `proxy_max_temp_file_size 3000m` is only applied in one path)

**Comment by goodidea-kp** [comment]
cannot confirm as NGINX issue. Looks like my env issue
