### ISSUE TITLE
getting the dial tcp 10.96.0.1:443: i/o timeout issues

### ISSUE THREAD

**Issue by mohit5577** [nginxinc/kubernetes-ingress#912]
Hello All,

I have created kubernetes cluster on centos 7 with one master node and 2 worker nodes. 
[causer@master deployments]$ kubectl get nodes
NAME     STATUS   ROLES    AGE    VERSION
master   Ready    master   9d     v1.18.0
node1    Ready    <none>   7d8h   v1.18.0
node2    Ready    <none>   7d8h   v1.18.0

i am using calico cni for networking. All the pods are running fine except the ingress pods on worker nodes
i.e. 
[causer@master deployments]$ kubectl get pods --all-namespaces -o wide
NAMESPACE       NAME                                       READY   STATUS             RESTARTS   AGE    IP                NODE     NOMINATED NODE   READINESS GATES
kube-system     calico-kube-controllers-5fc5dbfc47-ktfzc   1/1     Running            2          9d     192.168.219.72    master   <none>           <none>
kube-system     calico-node-bwhff                          1/1     Running            2          9d     192.168.29.85     master   <none>           <none>
kube-system     calico-node-mg7rp                          1/1     Running            1          7d7h   192.168.29.161    node2    <none>           <none>
kube-system     calico-node-rn9zg                          1/1     Running            1          7d7h   192.168.29.16     node1    <none>           <none>
kube-system     coredns-66bff467f8-vkz47                   1/1     Running            2          9d     192.168.219.71    master   <none>           <none>
kube-system     coredns-66bff467f8-w4b45                   1/1     Running            2          9d     192.168.219.73    master   <none>           <none>
kube-system     etcd-master                                1/1     Running            2          9d     192.168.29.85     master   <none>           <none>
kube-system     kube-apiserver-master                      1/1     Running            2          9d     192.168.29.85     master   <none>           <none>
kube-system     kube-controller-manager-master             1/1     Running            2          9d     192.168.29.85     master   <none>           <none>
kube-system     kube-proxy-7b9jd                           1/1     Running            1          7d7h   192.168.29.161    node2    <none>           <none>
kube-system     kube-proxy-8bbjc                           1/1     Running            1          7d7h   192.168.29.16     node1    <none>           <none>
kube-system     kube-proxy-b96b5                           1/1     Running            2          9d     192.168.29.85     master   <none>           <none>
kube-system     kube-scheduler-master                      1/1     Running            3          9d     192.168.29.85     master   <none>           <none>
kube-system     tiller-deploy-754f98dbfc-f7ztt             1/1     Running            1          7d7h   192.168.104.2     node2    <none>           <none>
nginx-ingress   nginx-ingress-f2lh6                        0/1     CrashLoopBackOff   7          16m    192.168.104.3     node2    <none>           <none>
nginx-ingress   nginx-ingress-htclm                        0/1     CrashLoopBackOff   7          16m    192.168.166.129   node1    <none>           <none>
nginx-ingress   nginx-ingress-lssvl                        1/1     Running            0          16m    192.168.219.74    master   <none>           <none>

after looking into the logs for failing ingress pods i am getting the following logs

[causer@master deployments]$ kubectl logs nginx-ingress-htclm -n nginx-ingress
I0407 14:34:18.403254       1 main.go:169] Starting NGINX Ingress controller Version=1.6.3 GitCommit=b9378d56
F0407 14:34:48.409730       1 main.go:275] Error trying to get the default server TLS secret nginx-ingress/default-server-secret: could not get nginx-ingress/default-server-secret: Get https://10.96.0.1:443/api/v1/namespaces/nginx-ingress/secrets/default-server-secret: dial tcp 10.96.0.1:443: i/o timeout

Anyone else got this issue  ? The ingress pod running on master is able to connect with kube api server but the ingress pods running on worker nodes are not able to connect. 
Any hint or suggestions will be very helpful.

-Regards
  Mohit

**Comment by pleshakov** [comment]
Hi @mohit5577 

Looks like a possible problem with calico configuration. Unfortunately, I can't provide any specific advice.

However, please take a look at instructions here on how you can check that you can access the k8s API from a pod in a cluster https://github.com/nginxinc/kubernetes-ingress/issues/911#issuecomment-610321571 In order for the IC to operate, it must be able to connect to the k8s API. That issue is similar to yours

**Comment by mohit5577** [comment]
Thanks pleshakov

**Comment by yujiannj** [comment]
Hi @mohit5577,

Finally i solved my issue in earlier post by changing to Flannel CNI plugin. 

Regards
