### ISSUE TITLE
Throttling limit by IP to two per second

### ISSUE THREAD

**Issue by Ajeeshb** [nginxinc/kubernetes-ingress#913]
I am trying to add a throttling limit by IP to 2 per second on my k8s cluster which is actually running the below infrastructure.
HAProxy is configured in front and redirects to the Ingress Controller Node port.
listen ingress-https
bind 0.0.0.0:443
balance leastconn
option tcpka option hefault-server port XXX inter 2s downinter 4s rise 3 fall 2 slowstart 60s weight 1
server k8s4 workernode_ip:XXX check 
server k8s5 workernode_ip:XXX check

I have added the below values in the config map for the Nginx ingress controller. 
  proxy-protocol: "True"
  real-ip-header: proxy_protocol
  set-real-ip-from: <Internal_IP address of HAProxy>

1. Ingress controller POD logs, we are not getting the client IP( source IP), so we tried the following solutions. But nothing is working.
A. Updated Nginx ingress service spec withexternalTrafficPolicy: "Local"

B. The tried the below parameters in the Configmap of Nginx ingress controller( In the "Data" section).        
  proxy-protocol: "True"
  real-ip-header: proxy_protocol
  set-real-ip-from: <Internal_IP address of HAProxy>

and another one I tried 
use-proxy-protocol: "true"
But adding I got some error message. 
+++++++++++++++++
Error: exit status 1
2020/04/06 05:29:03 [emerg] 116#116: unknown "proxy_protocol_server_port" variable
nginx: [emerg] unknown "proxy_protocol_server_port" variable
nginx: configuration file /tmp/nginx-cfg240258624 test failed
+++++++++++++++++++

2. For the IP restriction, I have added the below annotation in ingress for the application domain.nginx.ingress.kubernetes.io/limit-rps: "2"

Could you please find what is causing my setting not working, Is it possible to handle the throttling limit in the Nginx controller?

**Comment by lucacome** [comment]
Hi @Ajeeshb 

I believe you're using the [kubernetes ingress-nginx](https://github.com/kubernetes/ingress-nginx), that's a different project. Could you please check which version you're using?

Thanks,
Luca
