### ISSUE TITLE
Issue  with using Client Certificate Annotations with Nginx Plus

### ISSUE THREAD

**Issue by ksummersill2** [nginxinc/kubernetes-ingress#929]
Currently using Nginx Plus Image. I am having an issue getting an annotation that works for getting the client certification prior to accessing any of the domains within the ingress resource. 
My current annotations being used in the ingress resource are:
`annotations:
    # Enable client certificate authentication
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    # Create the secret containing the trusted ca certificates
    nginx.ingress.kubernetes.io/auth-tls-secret: "appddiction1-dev/ca-secret"
    # Specify the verification depth in the client certificate
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    # Specify if certificates are passed to upstream server
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    # acme.cert-manager.io/http01-ingress-class: "nginx"
    # nginx.ingress.kubernetes.io/rewrite-target: /
    # acme.cert-manager.io/http01-edit-in-place: "true"
    # Converting Http to only Https
    # Not this flag can be turned to false for certificate challenges
    ingress.kubernetes.io/ssl-redirect: "true"
    # Identify the Ingress Type
    kubernetes.io/ingress.class: nginx
`
Are there any annotations to deal with a client certificate with a CA verification?
Any assistance would be most appreciated.

**Comment by pleshakov** [comment]
Hi @ksummersill2 

Annotations like `nginx.ingress.kubernetes.io/auth-tls-verify-client` are not supported by this Ingress Controller. Those are supported by https://github.com/kubernetes/ingress-nginx

In our Ingress Controller we don't support client certificate validation, so we don't have any similar annotations, unfortunately.
