### ISSUE TITLE
Can't rewrite from root path to backend path

### ISSUE THREAD

**Issue by afsilvasantos** [nginxinc/kubernetes-ingress#931]
Hello.
I am using this controller, and i managed to make my application work. But right now it is working as follows:
I have only 1 path, which is / (root). And this path connects to the service where the application is served. The application in order to present the WebUI, needs to be accessed at /path. So right now, i can access by entering ip_address/path. 

My goal would be to access ip_address/ (in other words, on path root) and that path being redirected in the backend to /path.

To do that i left the path configuration the same, and added the annotation:
nginx.org/rewrites: "serviceName=service-frontend rewrite=/path"

What happens is that now the page is accessible, but the resources in the backend do not handle the path well. In the console for example, it shows the following:
"Failed to load resource... /pathrwt-resources/340/rap-client.js)"
Note this: **/path**rwt-resources/340/rap-client.js
If i add rewrite=/path/, then it says path not found. I am almost sure this is due how the backend application is made (i did not develop it), but i need to be sure i am doing everything right in this front.

Thanks

**Comment by pleshakov** [comment]
Hi @afsilvasantos 

`nginx.org/rewrites: "serviceName=service-frontend rewrite=/path/"`
For your situation, that seems to be a correct rewrite to use. In that case you will get rewriting as below:
* `example.com` -> `example.com/path/`
* `example.com/abc` -> `example.com/path/abc`

> If i add rewrite=/path/, then it says path not found.

Does it mean that NGINX return 404 for the request to `/` (the backend for the path `/path/`)? Will any other paths work? (like `/foo` ? )

**Comment by afsilvasantos** [comment]
Hi @pleshakov 
With the current setting, i can access `/path`, and the page works. 
```
-path: /
  backend:
    serviceName: service-frontend
    servicePort: service-port
```
If i access `/` i get a 404, but from the application, not from the nginx. The same if i access `/foo`, i get an error message from the application that it is not found. I guess this happens because i am exposing the service on `/` and therefore anything that does not match another path in the ingress get forwarded to the application.

**Comment by afsilvasantos** [comment]
I closed it because it is indeed a backend problem. No matter what we do on the nginx, whether barebones or controller, it won't work.
Thank you for your time
