### ISSUE TITLE
virtualserver-template

### ISSUE THREAD

**Issue by nataraj24** [nginxinc/kubernetes-ingress#932]
1.  What is the key we need to pass in configmap for customizing virtualserver-template similar to ingress-template.

2.  How to pass password file using ssl_password_file directive to virtualserver resource

3. How to pass .pem file using proxy_ssl_trusted_certificate directive to virtualserver resource.

**Comment by Rulox** [comment]
Hi @nataraj24 

The VirtualServer template path argument is `-virtualserver-template-path <string>` you can check this an other parameters [here](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/command-line-arguments/).

In order to add the files for the `ssl_password_file` and `proxy_ssl_trusted_certificate` you need to use a custom VirtualServer template (as you already mentioned) and have the files in the Ingress Controller pod. You can use [ConfigMap volumes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#populate-a-volume-with-data-stored-in-a-configmap) for example, or any volume, to make sure these files are in the pod.

Let me know if this makes sense.

**Comment by nataraj24** [comment]
Thank you Rulox for prompt reply

I had tried giving virtualserver-template as key in config map of nginx-config config map object and customize virtualserver template code in the place of value.  but the changes haven't got reflected for the virtual server conf file.  Kindly let me know the exact key which we need to pass in the config map.

For ssl_password_file what is the key we need to use.  also can it be passed using in kubernetes secret  when its loaded as secret volume in the pod its giving error saying read only file system.  

The nginx documentation has only example to create secret having tls.crt and tls.key as keys.  if we generate crt file with password/passphrase what should be the key we need to mention in the secret.  Please let me know the key for passing password file.

Please let me know mechanism to load .pem file to the nginx controller pod for proxy_ssl_trusted_certificate directive.

**Comment by pleshakov** [comment]
Hi @nataraj24 

> I had tried giving virtualserver-template as key in config map of nginx-config config map object and customize virtualserver template code in the place of value. but the changes haven't got reflected for the virtual server conf file. Kindly let me know the exact key which we need to pass in the config map.

`virtualserver-template` is not supported unfortunately.  As @Rulox said, you need to use `-virtualserver-template-path <string>` command-line argument. Note that the modified template file must be present in the container. As an option, you can put in a separate ConfigMap and mount as a file on the filesystem of the container. 

Alternatively, you can consider using the `snippets` configmap keys (https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#snippets-and-custom-templates). For example:
```yaml
location-snippets: |
  proxy_ssl_certificate     /somepath/tls.crt;
  proxy_ssl_certificate_key /somepath/tls.key;
```
As a result, the proxy_ssl directives will appear in the generated location blocks of the NGINX config.

Please read this doc https://docs.nginx.com/nginx/admin-guide/security-controls/securing-http-traffic-upstream/ that shows how to configure HTTPS between NGINX and upstreams.

> For ssl_password_file what is the key we need to use. also can it be passed using in kubernetes secret when its loaded as secret volume in the pod its giving error saying read only file system.

If you need to specify a password file, you also need to mount it on the filesystem and reference it correctly in the config.

I suggest taking a look at this example https://github.com/nginxinc/kubernetes-ingress/blob/master/examples-of-custom-resources/tls-passthrough/secure-app.yaml It mounts a secret for TLS termination to a regular NGINX pod. Your approach with mounting a cert/key for `proxy_ssl` directives for NGINX Ingress Controller should be similar.

**Comment by nataraj24** [comment]
Thank you Michael for details.  I am getting below error for nginx controller log.  

PEM_read_bio_PrivateKey() failed (SSL: error:2807106B:UI routines:UI_process:processing error:while reading strings error:0906406D:PEM routines:PEM_def_callback:problems getting password error:0906A068:PEM routines:PEM_do_header:bad password read)\n"

the certificate file is created using a password with option -passout pass:xxxx.  

i had created the secret using below option 

kubectl create secret generic nginx-ssl --from-file=tls.crt=./nginx.pem --from-file=tls.key=./nginx.key --from-file=tls.password=./key.password

the same is refered in virutalserver definition as below
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: nginx-virtualserver
  annotations:
    nginx.org/server-snippets: |
       ssl_password_file /etc/nginx/ssl/tls.password;
    nginx.org/location-snippets: |
       proxy_ssl_password_file /etc/nginx/ssl/tls.password;
       proxy_ssl_trusted_certificate /etc/nginx/ssl/clusterCA.pem;
spec:
  host: test.com
  tls:
    secret: nginx-ssl
    redirect:
      enable: true

Request your help to know the procedure to pass password file so that virtualserver code will be able to read it.  and i can overcome the error.  

i had made the password file available as part of secret and also through config map

 ls -lrt /etc/nginx/ssl
total 0
lrwxrwxrwx 1 root root 20 Apr 22 08:21 clusterCA.pem -> ..data/clusterCA.pem
lrwxrwxrwx 1 root root 19 Apr 22 08:30 tls.password -> ..data/tls.password

**Comment by pleshakov** [comment]
@nataraj24 
> nginx.org/location-snippets

VirtualServer doesn't support those annotations. I suggest using the corresponding configmap keys -- location-snippets and server-snippets 

> PEM_read_bio_PrivateKey() failed (SSL: error:2807106B:UI routines:UI_process:processing error:while reading strings error:0906406D:PEM routines:PEM_def_callback:problems getting password error:0906A068:PEM routines:PEM_do_header:bad password read)\n

This looks like NGINX wasn't configured to use the the password file. Could you double check that it is using? I suggest taking a look at this section https://docs.nginx.com/nginx-ingress-controller/troubleshooting/#checking-the-generated-config which shows how to view the generated config.
Alternatively, could you create your keys without passwords?

**Comment by nataraj24** [comment]
Thank you Michael once again your help. 

The conf seems to be ok.  below the output of the command you had given me.  only difference is i need to enter the passphrase.  if you could let me know how to do it for virtualserver that would be helpful.  the similar configuration, certificates having passphrase work for normal nginx.  i am trying the same for virtualserver in kubernetes.

ng nginx-ingress-7dbb9bb5d5-jn8mq -- nginx -T
Enter PEM pass phrase:
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
# configuration file /etc/nginx/nginx.conf:

worker_processes  auto;
daemon off;

error_log  /var/log/nginx/error.log notice;
pid        /var/lib/nginx/nginx.pid;

**Comment by pleshakov** [comment]
@nataraj24 
Could you share the content of the file that was generated in the `conf.d` folder? as well as could you double check the content of the password file in the `etc/nginx/ssl` folder?

**Comment by nataraj24** [comment]
Thanks a lot Michael for your excellent guidance i had solved the issue by using config map and secret    

ls -lrt /etc/nginx/ssl
total 0
lrwxrwxrwx 1 root root 20 Apr 27 08:46 clusterCA.pem -> ..data/clusterCA.pem
lrwxrwxrwx 1 root root 15 Apr 28 11:23 tls.pass -> ..data/tls.pass
lrwxrwxrwx 1 root root 14 Apr 28 11:23 tls.key -> ..data/tls.key
lrwxrwxrwx 1 root root 14 Apr 28 11:23 tls.crt -> ..data/tls.crt

Below is the virtual server file construct
server {
    listen 80;
    server_name k8s.ad.com;
    listen 443 ssl;
    ssl_certificate /etc/nginx/secrets/gs-k8s-nginx-ssl;
    ssl_certificate_key /etc/nginx/secrets/gs-k8s-nginx-ssl;
	server_tokens "on";
    ssl_certificate /etc/nginx/ssl/tls.crt;
    ssl_certificate_key /etc/nginx/ssl/tls.key;
    ssl_password_file /etc/nginx/ssl/tls.pass;

Only issue i could see two entries of the directives.  do you see any issue because of this?  kindly guide me.

**Comment by pleshakov** [comment]
@nataraj24 glad you were able to solve this issue!

I wonder why do you need to use these direcrives at all?
```
ssl_certificate /etc/nginx/ssl/tls.crt;
ssl_certificate_key /etc/nginx/ssl/tls.key;
ssl_password_file /etc/nginx/ssl/tls.pass;
```

Cause you already configure TLS termination by using a Secret resource?

**Comment by nataraj24** [comment]
without ssl directives at server i am getting the below error and nginx process is not up

stderr: "Enter PEM pass phrase:\nnginx: [emerg] cannot load certificate key 

Kindly suggest on the below two points
1. Any alternative other than using ssl directives at server 
2. Any impact of having ssl directives multiple times at server.  as informed you earlier.

**Comment by pleshakov** [comment]
Hi @nataraj24 

I see.  

I suggest:
*  configuring `ssl_password_file /etc/nginx/ssl/tls.pass;` through the snippets
* configuring TLS termination by referencing a secret in a VirtualServer/Ingress resource. That will make the Ingress Controller generate appropriate  `ssl_certificate` and `ssl_certificate_key`, so that you don't need to mount that Secret to the pod and use snippets to reference it. This method is recommended for TLS termination.

Could that work for you?

Alternatively,  removing the passphrase  from the cert can also solve the issue, so that you don't need any `_password_file` directives.

**Comment by nataraj24** [comment]
Thank you @pleshakov  for the information.  i was able achieve it through config map
