### ISSUE TITLE
[feature request] Support ppc64le

### ISSUE THREAD

**Issue by runlevel5** [nginxinc/kubernetes-ingress#944]
I am using Linux (PowerPC64 LE) bare metal to host kubernetes cluster. The `docker.io/nginx/nginx-ingress` image does come in ppc64le so I am unable to use the ingress controller.

**Describe the solution you'd like**
1st-class support for ppc64le

**Describe alternatives you've considered**
Custom build the docker image locally as workaround for the time-being. My images are uploaded to docker hub if anyone is interested https://hub.docker.com/repository/docker/powerpc64el/nginx-ingress

**Additional context**
- None

**Comment by runlevel5** [comment]
It is not stale

**Comment by ogarrett** [comment]
NGINX (the team) don't actively develop on ppc64le or ship new packages for that platform.

We don't plan to ship official docker images for that paltform

**Comment by lucacome** [comment]
Hi @runlevel5 

just wanted to let you know that we now build debian and apline images for ppc64le.

**Comment by runlevel5** [comment]
@lucacome :+1: Great news. Thanks much for letting me know
