### ISSUE TITLE
[Helm] Trying to install a second release

### ISSUE THREAD

**Issue by katlimruiz** [nginxinc/kubernetes-ingress#950]
**Describe the bug**
I have a cluster where I want to setup many different websites, each with its own nginx ingress.
I already have one that is running correctly. I used this command:
```
helm install myapp1 nginx-stable/nginx-ingress --namespace myapp1 --set controller.ingressClass=nginx-myapp1
```
which the ingressClass matches with an `ingress` resource. This runs fine.

So I want to add another website. I want to use this command:
```
helm install myapp2 nginx-stable/nginx-ingress --namespace myapp2 --set controller.ingressClass=nginx-myapp2
```
However, this gives me the following error:
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: namespace: , name: transportservers.k8s.nginx.org, existing_kind: apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition, new_kind: apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition
```
**Expected behavior**
The second installation should be inserted correctly. Since it is under a different namespace and a different release name.

**Your environment**
* Version of the Ingress Controller = NGINX Ingress Controller 1.7.0
* Version of Kubernetes = 1.15
* Kubernetes platform (e.g. Mini-kube or GCP) = Azure
* Using NGINX or NGINX Plus = NGINX

**Comment by Dean-Coakley** [comment]
@katlimruiz Thanks for the bug report. We will fix it!

**Comment by katlimruiz** [comment]
cool, I thought I was doing something wrong 👍 

when is the next release?

**Comment by Dean-Coakley** [comment]
Next release is planned for June/July.

The fix should be in master shortly. Which leaves you with some options for work arounds in the meantime:
* Download the chart locally and do similar edits
* Move to using the `nginx-edge/nginx-ingress` chart. **Note that this is not recommended for production use.**
* Do `helm template [chart]` and edit the output to no longer have the CRDs.

Sorry for the hassle

**Comment by Dean-Coakley** [comment]
Additionally, If you are not using our CRDs(if you are using ingress resources only) the following workaround should work:
* Simply set `controller.enableCustomResources` to `false`.

**Comment by katlimruiz** [comment]
How could I know if I'm using the CRDS or not? Sorry I'm still new in kubernetes.

**Comment by Dean-Coakley** [comment]
Ah, no problem.

If you are using CRDs you will route requests using our custom VirtualServer/VirtualServerRoute resources which are an alternative to Ingress resources:
https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#virtualserver-specification


If you are not using CRDs you will route requests via Ingress resources:
https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/basic-configuration/


You can check the manifests you have deployed. Or verify the deployed resources with `kubectl`.
E.g something like:
`kubectl get ingress -n myapp1` // check if you have ingresses deployed in the `myapp1 `namespace
`kubectl get vs -n myapp1 ` // check if you have virtualservers deployed in the `myapp1 `namespace

If you have no `virtualserver`/`vs` resources in any namespace you can disable them as described above. 
You then should be able to install the Ingress Controller in multiple namespaces via helm without issues.


Hope that clears things up.

**Comment by katlimruiz** [comment]
It worked. I was not using the new CRDs, therefore I set the flag as false, and it worked as expected.

Thanks!
