### ISSUE TITLE
Add security headers to response

### ISSUE THREAD

**Issue by dhatri308** [nginxinc/kubernetes-ingress#959]
We would like to have bunch of security headers inserted by nginx. One of those headers  `HTTP Strict Transport Security` is supported by configMap key `hsts`. We would like to know what are the options to add other security headers below ? 

```
X-Frame-Options: 
Content-Security-Policy:
X-Content-Type-Options: 
X-XSS-Protection: 
Referrer-Policy: 
```

**Comment by Rulox** [comment]
Hi @dhatri308 

You can add custom NGINX configuration in different places using our snippets, you can use these snippets to set custom headers with the `proxy_set_header` [directive](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header):

1. If you want to set those headers in **all** your Ingress Resources, you can use [ConfigMap](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#snippets-and-custom-templates) keys for these snippets (select the one that suits best for your case, `http`, `location` or `server`).
1. If you want only certain Ingress Resources to have these snippets, use [annotations](https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/#snippets-and-custom-templates) of the Ingress Resource instead.

Let me know if this makes sense, thanks.

**Comment by Rulox** [comment]
PS: @dhatri308 If you'd like to use response headers instead, the [directive](http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header) you have to use in snippets is `add_header` instead.

**Comment by dhatri308** [comment]
@Rulox Great explanation. Thank you!

I have couple of questions/looking for suggestions. 
- Looks like we are already using `annotations` for couple of Ingress resources to customize NGINX using `server-snippets` (no add_header directives present)

- We want to add Security headers to **all** Ingress resources. So if we use configMap key `server-snippets`. The headers won't be added to the Ingress resources I mentioned above because annotation `server-snippets` takes precedence over configMap key `server-snippets`(although no add_header present). Is that right ?

- Adding headers using configMap key `http-snippets` might add headers to all Ingress resources. However, adding configMap key `hsts` ( to enable HTTP Strict Transport Security), adds the `add_header` to server context. That means if we add other Security headers to `http` context, the `hsts` in server context hides other headers in `http`. So we may have to remove  configMap key `hsts` and add HTTP Strict Transport Security header manually in `http` context using configMap key `http-snippets`. Is that right ?

**Comment by Rulox** [comment]
Hi @dhatri308, your assumptions are right:

For 2: Yes, Annotations take precedence over ConfigMaps (this is done so you can fine-tune configurations for specific Ingress Resources in case you don't want an Ingress to share a global config parameter)

For 3:  Yes you are right. The way `add_header` works is as you say, if you have the directive in the `server` block due to the `hsts` ConfigMap, the headers in the `http` block are ignored.

Because you're using `server-snippets` in some of your Ingress Resources, a solution for your use case could be do as you say, do not use the `htst` ConfigMap provided key and add the header manually with the other sever-snippets. Would that work for you?

Thanks

**Comment by dhatri308** [comment]
@Rulox Adding all the headers in configMap key `http-snippets` works fine. Thank you.
