### ISSUE TITLE
Compatibility with Kubernetes nginx ingress

### ISSUE THREAD

**Issue by saggiyogesh** [nginxinc/kubernetes-ingress#960]
**Is your feature request related to a problem? Please describe.**
With [Kubernetes nginx ingress](https://github.com/kubernetes/ingress-nginx), I can specify SSL certs directly to service. Also, it works pretty well with cert-manager to issue and renew Lets Encrypt Certificates. 

**Describe the solution you'd like**
Support for enabling SSL cert from K8s secret & certificates. 

**Describe alternatives you've considered**
[Kubernetes nginx ingress](https://github.com/kubernetes/ingress-nginx)

However, I think this is possible with change in `ingress.tmpl` etc but that would require many changes and can't be automated.

**Comment by pleshakov** [comment]
Hi @saggiyogesh 

The two projects are not compatible. This doc describes the main differences https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/nginx-ingress-controllers.md Hope that helps.

> Describe the solution you'd like
Support for enabling SSL cert from K8s secret & certificates.

The Ingress Controller supports TLS termination using the standard approach with Secrets. Please take a look at this example -- https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/complete-example

**Comment by saggiyogesh** [comment]
Hi @pleshakov 
Very thanks again. Looks like I have to be more attentive to docs. 
Closing the issue.
