### ISSUE TITLE
unknown field "preserveUnknownFields" when installing controller.

### ISSUE THREAD

**Issue by dmitriy-myz** [nginxinc/kubernetes-ingress#961]
**Describe the bug**
Trying to install ingress controller in kubernetes v1.14
Follow this [doc](https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/#create-common-resources). Step 3 failed with error

**To Reproduce**
kubernetes cluster version 1.14. For example in gke
```Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}```
Run
```
kubectl apply -f vs-definition.yaml
error: error validating "vs-definition.yaml": error validating data: ValidationError(CustomResourceDefinition.spec): unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

**Expected behavior**
CRD should install without error. Or minimum k8s version noticed in [Prerequisites](https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/)

**Your environment**
* Version of the Ingress Controller - release version or a specific commit
v1.7.0
* Version of Kubernetes
1.14
* Kubernetes platform (e.g. Mini-kube or GCP)
GKE
* Using NGINX or NGINX Plus
NGINX
**Additional context**
simular issue in kubernetes repo https://github.com/kubernetes/kubernetes/issues/82874

**Comment by dmitriy-myz** [comment]
it look like workaround is to add `--validate=false`

**Comment by pleshakov** [comment]
Hi @dmitriy-myz 
It shall work if you use your workaround.
Yep, that should be mentioned in our docs.

**Comment by amirdamirov** [comment]
I have the same issue. But im trying install ingress with helm. How can i validate false in helm version 3 ?

**Comment by Dean-Coakley** [comment]
@amirdamirov You should be able to skip the validation by appending `--disable-openapi-validation` to `helm install`/`helm upgrade` commands.

**Comment by Dean-Coakley** [comment]
Added docs workaround in: https://github.com/nginxinc/kubernetes-ingress/pull/1065
