### ISSUE TITLE
case-insensitive not working in Ingress resource.

### ISSUE THREAD

**Issue by pratham98k** [nginxinc/kubernetes-ingress#964]
**Describe the bug**
not able to achieve case-insensitive for path based routing.
 
I am using basic ingress configuration 

https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/basic-configuration/

in document is not given how to expose service with case-insensitive.

https://example.com/AbCdE

**To Reproduce**
1. Deploy x to '...' using some.yaml
2. View logs on '....'
3. See error

**Expected behavior**
https://example.com/AbCDe
case-insensitive should work
**Your environment**
* Version of the Ingress Controller - release version or a specific commit
1.7.0
* Version of Kubernetes
1.15.x
* Kubernetes platform (e.g. Mini-kube or GCP)
AKS
* Using NGINX or NGINX Plus
Nginix
**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by pleshakov** [comment]
Hi @pratham98k 

Unfortunately, case insensitive paths are not supported with Ingress resource.

I recommend taking a look at the VirtualServer resource -- https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/

The VirtualServer supports regex matching, so you can configure case-insensitive matching. For example:
```yaml
  - path: ~*^/abcde
    action:
      pass: backend
```

**Comment by pratham98k** [comment]
Thanks for your quick response. Working case insensitive for urls is very important for us.
 I have few questions befor exploring virtual servers. Can you please help me with that.

 1)Is virtual servers support Annotations ?

nginx.org/server-snippets: |

Currently I am using server snippets annotations for ingress resource.same can I use for virtual server configuration?

2) What is best way to convert nginx resource configuration to virtual server virtualserver and virtualserverroute resources configuration.

I am having 20+ microservices running. 
Planning to go with nginx plus soon for production.

**Comment by pleshakov** [comment]
@pratham98k 

> 1)Is virtual servers support Annotations ?
nginx.org/server-snippets: |

VirtualServer doesn't support the snippets annotations. However, you can use the ConfigMap keys (`server-snippets`) -- it works both for Ingress resource and VirtualServer resource.

At the same time, we're planning to bring snippets and custom templates in the next 1.8.0 release in July.

> What is best way to convert nginx resource configuration to virtual server virtualserver and virtualserverroute resources configuration.

We don't have a converter, unfortunately. However, the best way to start, I think, is to take a look at two similar examples -- the complete example for [Ingress resources](https://github.com/nginxinc/kubernetes-ingress/tree/v1.7.0/examples/complete-example)  and a similar  example for [VirtualServer](https://github.com/nginxinc/kubernetes-ingress/tree/v1.7.0/examples-of-custom-resources/basic-configuration).

**Comment by pleshakov** [comment]
@pratham98k 
there is a way to support case insensitive matching with Ingress resource. However, it is not built-in and requires you to modify the template.

You can add a [custom annotation](https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/custom-annotations/) by modifying the Ingress template:
You need to replace this line:
```
 location {{$location.Path}} {
```
with this line:
```
location {{if index $.Ingress.Annotations "custom.nginx.org/regex-insensitive-prefix"}}~* ^{{end}}{{$location.Path}} {
```
Then you will be able to turn on case insensitive matching in the Ingress resource:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    custom.nginx.org/regex-insensitive-prefix: "true"
spec:
. . .
```

Hope that helps

**Comment by pratham98k** [comment]
could you please provide me exact snippet used for nginx & nginx-plus.

same I will try to  push from configmaps.
