### ISSUE TITLE
error: endpoints "default-http-backend" not found

### ISSUE THREAD

**Issue by zhouyp520** [nginxinc/kubernetes-ingress#966]
# kubectl describe ingress demo-app
Name:             demo-app
Namespace:        default
Address:          
 **Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)**
Rules:
  Host             Path  Backends
  ----             ----  --------
  www.happylau.cn  
                   /   demo-svc:8000 (10.244.3.61:8000,10.244.4.43:8000,10.244.7.29:8000)
Annotations:       kubernets.io/ingress.class: nginx
Events:
  Type    Reason          Age   From                      Message
  ----    ------          ----  ----                      -------
  Normal  AddedOrUpdated  33s   nginx-ingress-controller  Configuration for default/demo-app was added or updated
  Normal  AddedOrUpdated  32s   nginx-ingress-controller  Configuration for default/demo-app was added or updated
  Normal  AddedOrUpdated  31s   nginx-ingress-controller  Configuration for default/demo-app was added or updated

kubernetes 1.18.1
# kubectl get pods -n nginx-ingress 
NAME                  READY   STATUS    RESTARTS   AGE
nginx-ingress-2mwj5   1/1     Running   0          33m
nginx-ingress-gjwvr   1/1     Running   0          33m
nginx-ingress-zm2sw   1/1     Running   0          33m

# kubectl get svc
NAME         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
demo-svc     ClusterIP   10.103.253.137   <none>        8000/TCP   45m
kubernetes   ClusterIP   10.96.0.1        <none>        443/TCP    7d1h

# cat demo-ingress.yaml 
apiVersion: extensions/v1beta1
kind: Ingress
metadata: 
  name: demo-app
  labels: 
    ingres-controller: nginx
  annotations: 
    kubernets.io/ingress.class: "nginx"
spec: 
  rules: 
  - host: www.happylau.cn
    http: 
      paths:
      - path: / 
        backend: 
          serviceName: demo-svc
          servicePort: 80

# cat hello-node.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-node
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
      - name: hello-node
        image: hello-nodejs:0.2
        ports:
        - containerPort: 8000
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  labels:
    app: hello-node
spec:
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
  selector:
    app: hello-node

**Comment by LorcanMcVeigh** [comment]
Hi @zhouyp520, 

the `(<error: endpoints "default-http-backend" not found>)` error is fine, we don't support default-http-backend. However we might implement this in the future https://github.com/nginxinc/kubernetes-ingress/issues/892

Your problem is in the demo-ingress.yaml file the servicePort is set to 80 but in the hello-node.yaml file the port is defined to 8000. Changing the `servicePort: 80` to `servicePort: 8000` in the demo-ingress.yaml file should fix your problem.

**Comment by wuqunfei** [comment]
`spec:
  backend:
    serviceName: nginx-ingress-default-backend
    servicePort: 8080
  rules:`

**Comment by velcrine** [comment]
This error saying, u are missing an endpoint to be shown, when there is no route matched. i.e. 404 rule

**Comment by warthur1214** [comment]
```
spec:
  defaultBackend:
    service:
      name: nginx
      port:
        number: 80
```

**Comment by yomofo2s** [comment]
I am also having a similar issue. I will be glad if any form of help could be rendered. I couldnt obtain an external-IP, thereby difficult to reach it externally..Below are my configuration.. 

**deployment.yml**
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rendertron-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: rendertron-kube
        image: yomofo2s/rendertron:latest
        ports:
        - containerPort: 80


**ingress.yml**
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: anywebsite.com
    http:
      paths:
      - path: /testpath2
        pathType: Prefix
        backend:
          service:
            name: ingress-nginx
            port:
              number: 80
        
**Service.yml**
---
apiVersion: v1
kind: Service
metadata:
  name: rendertron-service
spec:
  selector:
    app: rendertron-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

![image](https://user-images.githubusercontent.com/44329653/123528511-f6b86080-d6e7-11eb-9fac-a5f6129ac789.png)

**Comment by AlexanderYastrebov** [comment]
I think this is related to https://github.com/kubernetes/kubernetes/issues/107720
