### ISSUE TITLE
Can't disable default backend or handle direct public IP Request

### ISSUE THREAD

**Issue by JohnGalt1717** [nginxinc/kubernetes-ingress#971]
**Describe the bug**
If you request http directly http(s)://xxx.xxx.xxx.xxx the default backend is invoked. This is an issue for PCI compliance because it is using a self-signed cert and even if you were using an official cert, it would still fail because it wouldn't match the host obviously.  There doesn't appear to be any way to intercept IP direct at all nor is there a way to tell the ingress controller to ignore the request outright. (i.e. I don't want it to respond at all to https at the very least for anything that isn't a valid and mapped route.

**To Reproduce**
Any ingress config that is bound to a public IP will exhibit this behavior.

**Expected behavior**
Should by default not respond on https at all for the default backend or at the very least allow us to define in the setup that we don't want a default backend at all.

**Additional context**
As it stands right now, this will fail all PCI scans.

**Comment by pleshakov** [comment]
Hi @JohnGalt1717 

> Should by default not respond on https at all for the default backend or at the very least allow us to define in the setup that we don't want a default backend at all.

There is a way to make NGINX break any client attempts to establish a TLS connection. For connections to the default server, you need to configure: `ssl_ciphers NULL;` in the default server.

Unfortunately, it is only possibly if you modify the main config template -- https://github.com/nginxinc/kubernetes-ingress/blob/master/internal/configs/version1/nginx.tmpl#L102 You can add the line `ssl_ciphers NULL;` to the default server and specify the modified template via a ConfigMap https://github.com/nginxinc/kubernetes-ingress/tree/v1.7.0/examples/custom-templates

Could this approach work for you?

**Comment by JohnGalt1717** [comment]
@pleshakov  Thanks for the suggestion, but no because I need SSL working everywhere EXCEPT if there is a direct request to the IP only.

I.e. http://some.domain.com as a default-backend is fine. I don't really care.  but https://1.1.1.1 should neve respond. This should be actively blocked because it can never be a secure configuration.

AND I should be able to dump everything except for the healthz entirely. I.e. no response at all to http not https unless it's to a properly mapped configuration. I.e. the default-backend should only respond to the healthz endpoint and nothing else per a configuration, because only then do you have a secure configuration.

**Comment by sharkymcdongles** [comment]
I am also facing this exact same issue with compliance.

**Comment by gluckzhang** [comment]
Same problem here. Every week I get an alert from our cloud vendor that the k8s cluster is using a self-signed certificate for web service https://x.x.x.x.

**Comment by gluckzhang** [comment]
Hi all, I succeeded in disabling the default backend's request handling on direct public IPs based on @pleshakov 's comment. `ssl_ciphers NULL;` is wrapped with an if condition:

```diff
+       {{/* disable https requests to a direct ip in our default backend */}}
+       {{ if eq $server.Hostname "_" }}
+       ssl_ciphers NULL;
+       {{ end }}
```

You can either adjust the `nginx.tmpl` by using a ConfigMap, or simply by building your own default backend controller on top of the original image and replace the `nginx.tmpl` with the adjusted one.

**Comment by pleshakov** [comment]
Hi @gluckzhang 

it seems your advice applies to this project https://github.com/kubernetes/ingress-nginx , which is a different project. The key differences are https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/nginx-ingress-controllers.md

**Comment by gluckzhang** [comment]
Hi @pleshakov , sorry for the misleading information. I just notice that. Should I remove the previous comment?

**Comment by pleshakov** [comment]
@gluckzhang no problem at all! up to you. I added that clarification to prevent possible confusion for people who will read this thread

**Comment by gluckzhang** [comment]
OK, thanks for the clarification @pleshakov :)
I will leave the comment there then. It is good to have a complete trace of the discussion. Both my solution and your clarification might be helpful in some cases. Thanks!
