### ISSUE TITLE
Is it possible to route on the basis of port?

### ISSUE THREAD

**Issue by iamnewspecies** [nginxinc/kubernetes-ingress#98]
I have two services (S1, S2). When a request comes on port 2775 or 8443 I have to forward the request to S1 and when request comes on port 443 I have to forward it to S2. 

I was trying to do this using  the example given but it seems that ingress doesn't allow routing on the basis of port but only on the basis of path.
https://github.com/nginxinc/kubernetes-ingress/blob/master/examples/complete-example/cafe-ingress.yaml

How do I achieve the above mentioned goal. It is possible that there is a better way of doing this. Please suggest if one exists.

**Comment by pleshakov** [comment]
@iamnewspecies 
> I was trying to do this using the example given but it seems that ingress doesn't allow routing on the basis of port but only on the basis of path

That's correct. Ingress doesn't allow to specify the port.

For your use-case, do you need HTTP or TCP load balancing?

**Comment by iamnewspecies** [comment]
One service uses SMPP(TCP) and we also require HTTP load balancing.

**Comment by pleshakov** [comment]
We might add support for TCP load balancing for the Ingress controller in the future.  Unfortunately, it's not part of the Ingress API yet. Please check the contrib controller if  it can help you, as it has support for load balancing TCP services via ConfigMaps  -- https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx#exposing-tcp-services
