### ISSUE TITLE
How to configure external OAuth authentication?

### ISSUE THREAD

**Issue by edahlseng** [nginxinc/kubernetes-ingress#982]
**Question**
I'm currently using the [kubernetes/nginx-ingress](https://github.com/kubernetes/ingress-nginx) controller but am looking to move over to using this ingress controller instead. Nevertheless, I currently rely on [external OAUTH authentication](https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/) for securing services with OAuth. I cannot figure out how to configure external OAuth authentication when using this ingress controller. Can someone help point me in the right direction?

**Comment by pleshakov** [comment]
Hi @edahlseng 

Unfortunately, we don't support that integration out of the box.

At the same time, the Ingress Controller includes a number of extensibility options - [snippets](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#snippets-and-custom-templates), [custom templates](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/custom-templates/) and [custom annotations](https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/custom-annotations/) -- so it might be possible to integrate the oauth2 proxy with those methods using the following [NGINX conifg](https://oauth2-proxy.github.io/oauth2-proxy/configuration#configuring-for-use-with-the-nginx-auth_request-directive) as a reference.`

**Comment by edahlseng** [comment]
Thanks @pleshakov, the documentation about custom annotations and the NGINX config you linked to are particularly helpful!
