### ISSUE TITLE
TLS Pass through is not working even after enabling it while deploying the Nginx controller

### ISSUE THREAD

**Issue by vperi1730** [nginxinc/kubernetes-ingress#988]
Hi Team,

We have installed the Nginx controller with TLS pass-through enabled by using the following helm chart. However, while trying to perform any operation, it is expecting a TLS handshake instead of passing it.

helm install nginx stable/nginx-ingress --set "rbac.create=true" --set "controller.service.type=LoadBalancer" --set "controller.extraArgs.annotations-prefix=nginx.ingress.kubernetes.io" --set "controller.extraArgs.enable-ssl-passthrough="

I need help here.

**Comment by pleshakov** [comment]
Hi @vperi1730 ,
 
It looks like you're using the  [kubernetes ingress-nginx](https://github.com/kubernetes/ingress-nginx) Ingress Controller. That's a different project - they key differences are described here https://github.com/nginxinc/nginx-ingress-controller-docs

 if you create an issue over there they might be able to help.

**Comment by vperi1730** [comment]
Sure, thank you.
