### ISSUE TITLE
more customization nginx config

### ISSUE THREAD

**Issue by gaord** [nginxinc/kubernetes-ingress#99]
It looks like I have to manually edit ingress.tmpl and build docker image to get the following options into nginx configuration. Would it be good to support sort of more of customizing nginx through ingress object?
ssl_client_certificate /etc/nginx/certs/ca.crt;
ssl_verify_client on;
ssl_crl /etc/nginx/clientcertauth/my_crl.pem;
ssl_password_file /etc/nginx/clientcertauth/password;

**Comment by pleshakov** [comment]
@gaord 
We can have annotations in an Ingress resource for those directives.

What do you think of the best place to put the referenced files? Kubernetes Secrets?  Files on the container file system added either during the build process or via volumes?

**Comment by gaord** [comment]
@pleshakov thanks for quick response.

for crt,pem and password, it sounds like a secret would be a good place to go. for switches, it could be in one of conf files.

**Comment by dwradcliffe** [comment]
Any plans to allow a custom ingress template at runtime like the contrib version of the nginx controller does?

**Comment by pleshakov** [comment]
@dwradcliffe We don't have any plans for that. Could you explain why this is important for you?

**Comment by isaachawley** [comment]
We'll support [custom templates via config map](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/custom-templates) in our next release.

**Comment by Dean-Coakley** [comment]
Closing, as mentioned above: [custom templates](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/custom-templates#custom-templates) are now available in the 1.3.0 release
