### ISSUE TITLE
IPv6 SVCs not supported (missing `[ ]`)

### ISSUE THREAD

**Issue by Frankkkkk** [nginxinc/kubernetes-ingress#991]
**Describe the bug** on IPv6 kubernetes clusters (and thus SVCs with IPv6 addresses), the nginx configuration for the ingress is wrongly generated and thus doesn't work

**To Reproduce** Steps to reproduce the behavior:

Get an IPv6 only kubernetes cluster. And create an ingress pointing to a IPv6 svc. For example: ` $ kl get svc NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE kubernetes ClusterIP 2001:1600:aaa:bbb:ffff::1 <none> 443/TCP 3d4h `

Then create a simple ingress: `yaml apiVersion: networking.k8s.io/v1beta1 kind: Ingress metadata: name: test spec: rules: - host: foo.bar.com http: paths: - path: / backend: serviceName: kubernetes servicePort: 443 `

This generates a wrong nginx configuration ``` upstream default-simple-fanout-example-foo.bar.com-kubernetes-443 { --- snip --- server 2001:1600 max_fails=1 fail_timeout=10s max_conns=0;<br/>}

` **Expected behavior** The IPv6 should not be truncated and enclosed in brackets: ` server [2001:1600:aaa:bbb:ffff::1] max_fails=1 fail_timeout=10s max_conns=0;<br/>```

**Your environment** \* Version of the Ingress Controller: GitCommit=7d341058 \* Version of Kubernetes: v1.17.6 \* Using NGINX or NGINX Plus: NGINX

Aha! Link: https://nginx.aha.io/features/IC-104

**Comment by pleshakov** [comment]
Hi @Frankkkkk 

We don't support IPv6 in the Ingress Controller, unfortunately. I can't share any ETA.

I suggest leaving this issue open. We'll use it to track this feature.

**Comment by Frankkkkk** [comment]
Still present :-)

**Comment by Frankkkkk** [comment]
👋

**Comment by brianehlert** [comment]
Thanks @Frankkkkk.  IPv6 support is something I have added to our roadmap.

**Comment by centromere** [comment]
Hi @brianehlert. Is this still on the road map now that #2361 is available?

**Comment by lucacome** [comment]
Fixed in https://github.com/nginxinc/kubernetes-ingress/pull/2576
